### ISSUE TITLE
[3.6.0-beta.1] Block can't editable on layout

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3699]
**Describe the bug**  

Block can't editable on layout field.

**To Reproduce**  
1. Go to panel
2. Edit any page that have layout field
3. Add new layout and block
4. Try to edit preview of block
5. See issue

**Kirby Version**  

3.6.0-beta.1

**Comment by afbora** [comment]
@distantnative Tracked down and this issue about following change that moving to top importing `"@/components/Forms/Blocks/index.js"` 😵 

https://github.com/getkirby/kirby/commit/b9e654d17808af7d2f58b363472813f937f92e01#diff-3031c2bbe6dcab57d8ac84a1c7009158624a422249876441d7bc72012c952db8

**Comment by distantnative** [comment]
You mean moving these lines further up in `config/components.js`?
https://github.com/getkirby/kirby/blob/master/panel/src/config/components.js#L371-L372

**Comment by afbora** [comment]
No, to down :) You currently viewing master branch. Here develop branch:

https://github.com/getkirby/kirby/blob/develop/panel/src/config/components.js#L51-L52

**Comment by bastianallgeier** [comment]
☑️
