### ISSUE TITLE
[3.6.0-beta.1] Not all former CSS variables have fallbacks

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#3706]
While some of the former CSS variables like `--color-text` have fallback definitions in the *style.css* (in this case for example `--color-text: var(--color-gray-900);`), not all former CSS variables appear to be covered.

For example `--font-size-small` was defined pre-3.6 but the corresponding variable in 3.6.0-beta.1 is now `--text-sm`. Plugins using `var(--font-size-small)` in customized panel components are now displayed with the wrong font size.

This appears to be
- either a bug (missing fallback variables)
- or a breaking change that could be useful to be documented.

PS. Sorry about the small confusion on Discord; a few issues were piling up and it took me a moment to figure out what is going on here.

**Comment by sebastiangreger** [comment]
During my plugin migration attempt, I noticed at least the following CSS variables to be no longer working:
- `--font-size-*`
- `--font-family-*`
- `--box-shadow-*`

**Comment by bastianallgeier** [comment]
I think it really doesn't hurt to reintroduce them and then maybe deprecate them in a later release. @distantnative what do you think?

**Comment by distantnative** [comment]
Agreed

**Comment by bastianallgeier** [comment]
✅
