### ISSUE TITLE
Confirming empty password dialog throws error

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#3716]
**Describe the bug**  
If you change the password of an account and don't provide any input in the dialog, submitting the dialog causes an exemption to be thrown.

**Expected behavior**  
Input properly validated and an information to the user shown.

**Kirby Version**  
v3.6 beta 1

**Console output**  
Kirby\Cms\UserRules::validPassword(): Argument #2 ($password) must be of type string, null given, called in [...]\kirby\config\areas\users\dialogs.php on line 181

**Desktop (please complete the following information):**  
Windows 10, Firefox

**Comment by bastianallgeier** [comment]
✅
