### ISSUE TITLE
[3.6.0-alpha.1] Weird translation & language behaviors

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3725]
![language](https://user-images.githubusercontent.com/3393422/134823387-7c835074-3eb2-4920-bc1e-6082c8e97952.gif)

I tested this issue with this PR, and the issue I'm having seems to be the subject of this PR as well.

**Steps to reproduce**

1. TR default, EN, secondary, EN user language
2. You'll see login screen as default language
3. Log-in panel
4. You will see some parts in Turkish and some parts in English
5. Logout
6. You will see login screen as English
7. When you refresh login screen, you'll see Turkish again

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/3713#issuecomment-927366963_

**Comment by afbora** [comment]
From discord by Oliver Mayer:

> We have a warning pop up when someone edits in English using CSS and refer to <html lang="en">. Although the language of the user is set to German it's still English after login, at least in the code. After a refresh everything is ok again! Is there an error in the event listener or something? This doesn't happens in Kirby 3.5.x

https://user-images.githubusercontent.com/3393422/135602101-7653e2fd-d1fb-42fa-ad0b-6afb181c6b9d.mp4

**Comment by afbora** [comment]
I can not reproduce issue on 3.5.7.1 and can reproduce on 3.6.0-alpha.1 So this is regression.

**Comment by bastianallgeier** [comment]
✅
