### ISSUE TITLE
[3.6.0-beta.1] Checkbox fields + required option display an error

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#3726]
**Describe the bug**  
When I use a checkbox field in a blueprint with the required option, it display a message error :+1: 
 "(intermediate value).minLegth is not a function"

Remarque : typo in ".minLegth" ... should be ".minLength" ?

**To Reproduce**  
Try this code in a blueprint
```
mediatype:
        type: checkboxes
        columns: 2
        required: true
        help: Champ obligatoire
        label: Type de média
        options:
          Télévision: Télévision
          Radio: Radio
          Presse écrite: Presse écrite
          Web: Web
          Groupe de presse: Groupe de presse
          Agence de presse: Agence de presse
          Agence photo: Agence photo
```

**Expected behavior**  
Display a list of checkbox on two columns, the field should be required

**Kirby Version**  
3.6 beta 1

**Comment by bastianallgeier** [comment]
✅
