### ISSUE TITLE
[3.6.0-alpha.4] Copy & Paste in list blocks doesn't work on the first try

### ISSUE THREAD

**Issue by MaluNoPeleke** [k-next/kirby#3728]
**Describe the bug**  
Copying & pasting content into a list block doesn't work at the first try.

**To Reproduce**  
1. Copy some list items from a page (e.g. https://getkirby.com/features/designers "For designers")
2. Create a new list block
3. Paste the content
4. Nothing happens
5. Click outside of the list block
6. Click inside the list block
7. Paste the content
8. Content gets added

**Expected behavior**  
I expect that I can add content to list blocks immediately.

**Screenshots**  
![screencast-dev peleke de-2021 09 28-12_34_28](https://user-images.githubusercontent.com/1446541/135071984-49362db2-8792-44e5-8bb7-2770e5c5bdc4.gif)

**Kirby Version**  
3.6.0-beta.1

**Console output**  
None

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome
 - Version: 94

**Additional context**  
@MaluNoPeleke I guess this is a different issue. Can you open a new issue about this?

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/3721#issuecomment-929051900_

**Comment by afbora** [comment]
@MaluNoPeleke By the way, this issue only exists in 3.6, right?

**Comment by MaluNoPeleke** [comment]
I haven't tested it again but as far as I can remember, yes.

**Comment by afbora** [comment]
I've tested and seems this issue started in alpha.4.

**Comment by afbora** [comment]
I've looked into the changes in alpha.4 but haven't been able to find the cause of this issue.

**Comment by bastianallgeier** [comment]
I cannot reproduce this after https://github.com/getkirby/kirby/pull/3758

**Comment by afbora** [comment]
Yes, seems fixed 🎉
