### ISSUE TITLE
Beta 3.6.0 Alpha 1 / After creation, blocks within the field type "layout" cannot be edited

### ISSUE THREAD

**Issue by obear** [k-next/kirby#3731]
Beta 3.6.0 Alpha 1

After creation, blocks within the field type "layout" cannot be edited. Also drag'n drop within layouts does not work anymore. An overlay appears with the message "No blocks".

**Comment by afbora** [comment]
Thanks for report 👍 This issue fixed https://github.com/getkirby/kirby/issues/3699 and will be release in 3.6.0-beta.2
