### ISSUE TITLE
API Permission error

### ISSUE THREAD

**Issue by MaluNoPeleke** [k-next/kirby#3737]
**Describe the bug**  
With the Matomo plugin I get a permission error in the console since Kirby 3.6.0-beta 2

**To Reproduce**  
1. Install and configure [Kirby Matomo](https://github.com/sylvainjule/kirby-matomo)
2. Add it to a blueprint
3. Open the blueprint page

> {"status":"error","message":"Unauthenticated","code":403,"exception":"Kirby\\Exception\\PermissionException","key":"error.permission","file":"..\/dev.domain.de\/kirby\/config\/api\/authentication.php","line":14,"details":[],"route":"matomo-panel\/get-overview-content"}

**Expected behavior**  
Plugin is working as in beta.1

**Screenshots**  
![image](https://user-images.githubusercontent.com/1446541/135526749-11072431-a9f2-4dff-a13e-1b48c64d14f7.png)

**Kirby Version**  
Kirby 3.6.0-beta.2

**Console output**  

> The message port closed before a response was received.
> (anonymous) @ bundle.js:2
> /panel/pages/blog+new-wave-by-zenibyfajnie-on-deviantart:1 Autofocus processing was blocked because a document already has a focused element.
> /api/matomo-panel/get-bulk-summary:1 Failed to load resource: the server responded with a status of 400 ()
> index.js:1 Objecterror: "file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed"plugin: "matomo"status: "error"[[Prototype]]: Object
> onError @ index.js:1
> /api/matomo-panel/get-bulk-summary:1 Failed to load resource: the server responded with a status of 400 ()
> index.js:1 Object
> onError @ index.js:1
> /api/matomo-panel/get-chart-data?method=VisitsSummary.getUniqueVisitors&period=day&date=last31:1 Failed to load resource: the server responded with a status of 400 ()
> /api/matomo-panel/get-bulk-widgets?widgets=[%22referrerType%22,%22websites%22,%22socials%22,%22devicesType%22,%22keywords%22,%22popularPages%22]&period=month&date=today&lang=de&limit=5:1 Failed to load resource: the server responded with a status of 400 ()
> /api/matomo-panel/get-realtime-number:1 Failed to load resource: the server responded with a status of 400 ()
> index.js:1 Object
> onError @ index.js:1
> /api/matomo-panel/get-bulk-summary:1 Failed to load resource: the server responded with a status of 400 ()
> /api/matomo-panel/get-overview-content?method=VisitsSummary.get&period=day&date=last62:1 Failed to load resource: the server responded with a status of 400 ()
> index.js:1 Object
> onError @ index.js:1
> index.js:1 Object
> onError @ index.js:1
> index.js:1 Object
> onError @ index.js:1
> index.js:1 Objecterror: "file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed"plugin: "matomo"status: "error"[[Prototype]]: Object
> onError @ index.js:1

**Desktop (please complete the following information):**  
 - OS: Windows
 - Browser: Chrome
 - Version: 94

**Additional context**

**Comment by afbora** [comment]
I've created trial account on matomo and set from config. 
The console had errors like yours when I first installed it and misconfigured it. 
It works with the correct settings and there are no errors in the console.

Make sure the url, id and token are correct in the config.

**Comment by MaluNoPeleke** [comment]
Strange, it works again today without changing anything. Maybe it was related to another problem connected with my previous session.
