### ISSUE TITLE
[3.6.0] Weird hover effect on disabled buttons

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#3742]
**Describe the bug**  

Hovering on a disabled button (tested with a disabled plugin menu button) reduces the opacity of that button.

**Expected behavior**  

IMO a disabled button shouldn't react on hovering to avoid the impression that the button is interactive and can be clicked.

**Screenshots**  

![Untitled](https://user-images.githubusercontent.com/1595007/135724621-fbe4c3ea-8d74-4b1d-862b-edfd2d507f52.gif)

**Kirby Version**  

3.6.0-beta.2

**Desktop (please complete the following information):**  
 - OS:  macOS
 - Browser:  Safari
 - Version:  15.0

**Comment by bastianallgeier** [comment]
✅
