### ISSUE TITLE
[3.6.0-beta.2] pages field low quality thumbnail panel preview

### ISSUE THREAD

**Issue by garethworld** [k-next/kirby#3756]
**Describe the bug**  
Pages field shows a low quality thumbnail the first time a page is added. This is fixed after a hard refresh. 

**To Reproduce**  
Add a page to a pages field

**Expected behavior**  
Standard thumbnail quality as seen after page refresh 

**Screenshots**  
![Screenshot 2021-10-05 at 14 35 37](https://user-images.githubusercontent.com/55981730/136034210-f0cd1a9b-4063-46c2-bad4-6aab72903175.png)

**Kirby Version**  
3.6.-beta.2

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome

**Comment by afbora** [comment]
I tried to fix this. I solved the problem in upload but I couldn't when selecting any page/file. Previously, [there were list and cards props for the image](https://github.com/getkirby/kirby/blob/master/panel/src/helpers/previewThumb.js#L10-L15). We were selecting it according to the layout, but now the image has only one `srcset` information. It seems a little difficult for me to fix this.

**Comment by bastianallgeier** [comment]
✅

**Comment by mullema** [comment]
I just saw that the users field can also be layouted with cards and cardlets and would need the layout property aswell in the api request https://github.com/getkirby/kirby/blob/fae90f5678b3ccd52fd9a066fda74035faa086da/config/fields/users.php#L78

**Comment by afbora** [comment]
@mullema Good catch 👍 I've created PR https://github.com/getkirby/kirby/pull/3772
