### ISSUE TITLE
[3.6.0-beta.2] files field with `uploads: false` doesn't work

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#3768]
**Describe the bug**  
Setting `uploads: false` on a files field results in an error.

**To Reproduce**  
1. Add a files field like this:
```yml
file:
  type: files
  multiple: false
  uploads: false
```
2. Click on "Select"
4. See error: `t.apply is not a function`

**Kirby Version**  
3.6.0 beta 2

**Console output**  
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'open')`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Chrome
 - Version: 94.0.4606.61

**Comment by afbora** [comment]
It works when I make the `click` prop an inline function. But I am not sure if it is the right solution.

https://github.com/getkirby/kirby/blob/develop/panel/src/components/Forms/Field/FilesField.vue#L74

````js
return {
  options: [{ icon: "check", text: this.$t("select"), click: () => this.open() }]
};
````

**Comment by bastianallgeier** [comment]
✅
