### ISSUE TITLE
Namespace issue after upgrade 3.6 from 3.5.x

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3778]
I came trough an undocumented (3.6) breaking change (namespace issue) : is_a($page, 'Page') returns false after updating from 3.5.? to 3.6-beta-3. Fix: `is_a($page, 'Kirby\Cms\Page')`

[My use case](https://github.com/Daandelange/kirby3-simplestats/commit/00cc567d6e7948939c12c457f8a8adc3469d4830) is in a `route::after` hook, while visiting a Page object.
Same result printing it in a page template. Using php 7.4.2 locally on os x.
```php
// use Kirby\Cms\Page; <-- Result with namespace declaration : bool(true) bool(true) bool(false) bool(true)
App::plugin('daandelange/simplestats', [
    'hooks' => [
        'route:after' => function ($result) {
            var_dump(
                is_a($result, 'Kirby\Cms\Page'),
                $result instanceof Kirby\Cms\Page,
                is_a($result, 'Page'),
                $result instanceof Page,
                $result
            );
            die();
        }
    ]
]);
```
Result:

```
bool(true) 
bool(true) 
bool(false) 
bool(false) 
object(Kirby\Cms\Page)#584 (15) [...]
```

_Originally posted by @Daandelange in https://github.com/getkirby/kirby/issues/3485#issuecomment-939261836_

**Comment by afbora** [comment]
@Daandelange I've created separated issue to better digging. 

I'm getting following output with your hook for PHP 8.0 and 7.3:

````
bool(true)
bool(true)
bool(true)
bool(true)
object(Kirby\Cms\Page)#215 (15) {}
````

Any ideas @getkirby/kirby-staff ?

**Comment by Daandelange** [comment]
Thanks for opening an issue + testing.
Not sure what's going on; I've just tested with a fresh starterkit + 3.6-beta-3 and I get the same results as you, so there's probably something else going on in my website config...
Also, `is_a($result, 'Kirby\Cms\Page')` seems more correct and always returns the good value. (not sure if this is worth digging).

**Comment by distantnative** [comment]
Are you using any custom models, classes, plugins that could have taken over the global `Page` name?

**Comment by bnomei** [comment]
untested: what if a custom page model method has the alias "Page" as declared return value? would get_class resolve that to the FQCN?

// not use \Kirby\Cms\Page
function mypage(): Page // the alias
{ return $this; }

**Comment by bnomei** [comment]
see examples here:

https://www.php.net/manual/en/function.class-alias.php

comparing to alias with instanceof yields true. 

(edited: yields true. the fals is from ===)

**Comment by Daandelange** [comment]
Yes, I am using a `BasePage extends Page` class as custom model, all my pages are custom pages and inherit from it; but I keep failing to reproduce it in the starterkit...
I also use lots of plugins, many being untested on 3.6. I'll try to remove other plugins to trace this down. 

Meanwhile, I figured out this weirdness : _(maybe something php dynamic-classname-resolver related ?)_
```php
// new Page(['slug'=>'test3']);
var_dump( new Kirby\Cms\Page(['slug'=>'test3']) instanceof Page ); // <-- prints: false (but true when line above is uncommented)
```

**Comment by bastianallgeier** [comment]
Uff, I'm completely lost here. I just had another look at the way we load class aliases and nothing has changed between 3.5 and 3.6 there.

**Comment by lukasbestle** [comment]
Same for me. :/

**Comment by afbora** [comment]
@Daandelange Could you try with different PHP versions as 7.3 and 8.0? In the last example you post, it always returns `true` for me.

**Comment by Daandelange** [comment]
I've tried php 7.3.9 and the result is the same... Php 8, I haven't installed.
Btw, I was on K5.3.1 before upgrading to K3.6-beta3.
`instanceof` is better to use as when the object is unknown, it throws a php error, making my issue less obscure.

It's still not clear to me what's happening here too.
Meanwhile, I got it to reproduce on the starterkit.
It's related with having multiple inheritance on all pages, without any "direct `Page` inheritance" in `site/models`.
Also, it might not be exclusively 3.6 related.
1. Fresh 3.6 starterkit.
2. Install this plugin in `site/plugins/basepage/index.php` : 
 ````php
 use Kirby\Cms\Page;
 class BasePage extends Page {};
 
 Kirby::plugin('daandelange/basepage', [
     'hooks' => [
         'route:after' => function ($method, $result, $final) {
             if( $final === true && empty($result) === false && $method==='GET') var_dump([
                'pageIsaPage' => is_a($result, 'Page'), // <-- watch this var
                'pageIsaKirbyCmsPage' => is_a($result, 'Kirby\Cms\Page'),
                'finalTemplate' => $result->template()->name(),
                'intendedTemplate' => $result->intendedTemplate()->name(),
                'pageClassName' => get_class($result),
                'pageInstanceofPage' => $result instanceof Page,
            ]);

            return $result;
         }
     ]
 ]);
 ````
3. Visit any page and see correct `is_a($page, 'Page')` behaviour.
4. Edit `site/models/album.php` **and** `site/models/note.php` : change `Page` to `BasePage`.
5. Visit any page and see weird `is_a($page, 'Page')` behaviour.

**Comment by distantnative** [comment]
I can reproduce the problem with your instructions both on PHP 7.4 and 8.0

**Comment by distantnative** [comment]
I'll just document my findings

| Call | Result | Correct? |
|-|-|-|
| `is_a($result, Page::class)` | `true` | ✅ |
| `is_a($result, 'Kirby\Cms\Page')` | `true` | ✅ |
| `$result instanceof Page` | `true` | ✅ |
| `is_a($result, 'Page')` | `false` | 💥 |

Adding the following before the whole `var_dump` block resolves the wrong `is_a` return:

```php
$name = 'Page';
$alternative = new $name(['slug' => 'foo']);
```

Though the issue remains if I only do

```php
$alternative = new Page(['slug' => 'foo']);
```

So it really seems to be somehow connected to the transformation of a string `'Page'` to the class `Kirby\Cms\Page` via its alias.

**Comment by lukasbestle** [comment]
It's still so weird why it only happens in 3.6 and not 3.5.x...

**Comment by afbora** [comment]
I saw a comment like this, could it have something to do with it?

> A use statement will not resolve namespace dependencies in that is_a() function.

https://www.php.net/manual/tr/function.is-a.php#119972

**Comment by distantnative** [comment]
Sounds to me like something we can't/won't fix then and `is_a` should be either used with full class name `'Kirby\Cms\Page'` or like

```php
use Kirby\Cms\Page;

// ...

is_a($result, Page::class)
```

**Comment by Daandelange** [comment]
Yes, sounds legit to me, php-related. Thanks for your replies. Why it was working pre-3.6 is still a mystery to me too.

**Comment by distantnative** [comment]
Closing this as we cannot find the cause of the issue, but workaround as outlined do exists.
