### ISSUE TITLE
[3.6.0-beta.3] Saving required blocks field with no blocks causes an exception

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#3779]
**Describe the bug**  
Saving a required blocks field with no blocks inside should throw no exception.

**To Reproduce** 
1. create a page with a blocks field
2. save and publish the page
3. remove all blocks in the blocks field
4. save to get an error in console

**Expected behavior**  
no technical error thrown

**Console output**  
```
Object { status: "error", message: "Invalid form with errors", code: 400, exception: "Kirby\\Exception\\InvalidArgumentException", key: "error.invalidArgument", file: "/kirby/kirby/src/Cms/ModelWithContent.php", line: 616, details: {…}, route: "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)" }
```

**Desktop (please complete the following information):**  
Windows 10, latest Firefox

**Comment by afbora** [comment]
If I understood correctly;

This is intended behavior. If the required field is empty, an error is expected.

**Comment by GiantCrocodile** [comment]
@afbora Yes, there is a popup telling the user to fill out the required field. This is expected behavior regarding usability. But on the other hand, you have a technical error (an exception) thrown from deep inside just for violating a frontend validation. If Kirby 3 should throw exceptions like this on invalid input, it should be like this on other places too but I doubt this is what the developer wanted to happen.

**Comment by afbora** [comment]
If you mean the detailed error in the console, you should disable debug from config file with `'debug' => false`.

**Comment by GiantCrocodile** [comment]
Hm, you are right that this is influenced by the debug parameter in the config. This feels inconsistent though: For example if I try to create an user acc and try to save without entering a valid email address, I get an exemption that tells me to enter a proper email address. So there are like 2 types of errors: one (more or less nothing-saying technical exception) and one very clear one: You did enter something wrong. I think there are other places like this as well. I would have expected to get an exception that tells me that the user input is wrong/illegal according to validation.

**Comment by bastianallgeier** [comment]
I think this can be closed. Our exception handling is exactly intended like that. 

We have the following visual error notifications for users: 

- The red error bar in dialogs
- The error dialog for form validation and other errors in views
- The red error fallback bar if a section or field cannot be loaded

All three are targeted at "normal" users

The additional console errors are a reference for plugin developers and for us to find out what happens behind the curtains. They can be extended by enabling debug mode. Otherwise they are rather plain.
