### ISSUE TITLE
Page can be published although not all required fields are filled out

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#3781]
**Describe the bug**  
You can get a page into published status without filling out all required fields.

**To Reproduce**  
1. Create a new page with required fields
2. Set it to status 'In Review'
3. Then set it to published.

**Expected behavior**  
Setting status to published from 'In Review' throws the same error as if you set the page from draft to published. In both cases the required fields were not filled out.

**Kirby Version**  
[3.6.0-beta.3]

**Desktop (please complete the following information):**  
 Windows 10, latest Firefox

**Additional context**  
debug on, multilang site with only 1 language

**Comment by afbora** [comment]
I guess, `changeStatus` checks weren't moved to dialogs

https://github.com/getkirby/kirby/blob/master/panel/src/components/Dialogs/PageStatusDialog.vue#L103-L114

**Comment by afbora** [comment]
I tried to fix the issue, but when I throw an exception from the dialog, it gives a simple alert instead of a detailed form error.

**Comment by bastianallgeier** [comment]
I fixed it. Fun fact: it isn't a regression. It was possible before. Just not through the dialog, but still through the API. 🙈

**Comment by bastianallgeier** [comment]
✅
