### ISSUE TITLE
$page->panelIcon() is broken in 3.6-beta-3

### ISSUE THREAD

**Issue by Daandelange** [k-next/kirby#3782]
**Describe the bug**  
`$page->panelIcon()` throws an error :
> Whoops\Exception\ErrorException thrown with message "array_merge(): Expected parameter 2 to be an array, null given"
> ```
> Stacktrace:
> #11 Whoops\Exception\ErrorException in /starterkit/kirby/src/Panel/Model.php:121
> #10 array_merge in /starterkit/kirby/src/Panel/Model.php:121
> #9 Kirby\Panel\Model:image in /starterkit/kirby/src/Cms/ModelWithContent.php:671
> #8 Kirby\Cms\ModelWithContent:panelIcon in /starterkit/site/templates/home.php:24
> #7 include in /starterkit/kirby/src/Filesystem/F.php:410
> #6 Kirby\Filesystem\F:loadIsolated in /starterkit/kirby/src/Filesystem/F.php:387
> #5 Kirby\Filesystem\F:load in /starterkit/kirby/src/Toolkit/Tpl.php:36
> #4 Kirby\Toolkit\Tpl:load in /starterkit/kirby/src/Cms/Template.php:167
> #3 Kirby\Cms\Template:render in /starterkit/kirby/src/Cms/Page.php:1061
> #2 Kirby\Cms\Page:render in /starterkit/kirby/src/Cms/App.php:704
> #1 Kirby\Cms\App:io in /starterkit/kirby/src/Cms/App.php:1077
> #0 Kirby\Cms\App:render in /starterkit/index.php:5
> ```

**To Reproduce**  
Tested on a clean Maegazine/Starterkit + `composer require getkirby/cms ^3.6.0-beta-3` + php 7.4.1.
Insert code below in any template.
```php
<?php
var_dump($page->panelIcon());
?>
```

**Expected behavior**  
`$page->panelIcon()` returns the icon object.

**Kirby Version**  
Kirby 3.6-beta-3

**Comment by bastianallgeier** [comment]
✅
