### ISSUE TITLE
Allow to open a calendar of a date field if it's a read-only field

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#3784]
Hello,

this could be a feature request but most likely it's a too little change for that: I would like to be able to open the calendar of a date field even if it's read-only. Reason: This way you can see which week day a specific date was without going to the specific date in your own calendar of your operating system. This helps especiallys if we talk about weeks or years back or forth in future for a specific date.

Best Regards

**Comment by afbora** [comment]
This may also make users think that they can select dates. I think it would be better to move this to the feedback platform: https://kirby.nolt.io/.

**Comment by bastianallgeier** [comment]
I agree that this should be posted on Nolt.
