### ISSUE TITLE
Drawer issue when few tabs available on mobile

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3794]
**Describe the bug**  

![screen-capture-1191-Home - Restoran-localhost](https://user-images.githubusercontent.com/3393422/136804154-4b86bf04-e169-42c5-957f-e2fdce37c266.png)

The solution that comes to my mind is; we can fix it by keeping the existing compact view only if the tabs are placed under the block header on mobile screens.

**Kirby Version**  
3.6.0-beta.3

**Comment by bastianallgeier** [comment]
The perfect solution would be a similar "More …" dropdown that we already have for the main tabs. Maybe we can make the Tabs component more versatile to also work for the drawer.

**Comment by afbora** [comment]
I like the idea and tried to implement it but the problem persists. There are 3 parts in the header and there is a shortage of space on mobile.

Also, I haven't even tried nested blocks yet. The longer the breadcrumb gets, the more the problem will appear on widescreens.

IMO If we always place the tabs under the header, we can solve the problem permanently.

![screen-capture-1194-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/137100659-9e31325e-a2fb-4693-9549-81afc646fb4d.png)

**Comment by afbora** [comment]
### Alternative 1

![screen-capture-1196-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/137125989-fc2aa47d-0f8e-46cf-929d-3732ddf2fb36.png)

![screen-capture-1199-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/137126628-05a249f2-1a28-4920-95dc-80924cfef54d.png)

### Alternative 2

![screen-capture-1197-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/137126100-c96f4e1e-cff5-48c4-b7a1-26deabdd4f00.png)

![screen-capture-1198-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/137126516-b024dc3e-4112-432b-a98e-691e4082dd29.png)
