### ISSUE TITLE
Writer field with 'inline: false': convert paragraph breaks to `<br>`

### ISSUE THREAD

**Issue by maxackerman** [k-next/kirby#3796]
# Kirby Team summary
## Status quo
A writer field with `inline: true` still accepts paragraphs on paste. Drops everything but the first paragraph on save.

## Goal
A writer field with `inline: true` should convert paragraph breaks to `<br>` on paste or save.

## Solution
_tbd_

# Original post by @maxackerman

using kirby 3.6.0-beta.3

if a writer field has `inline: true` i can still copy multiple paragraph breaks from another field and paste them into the writer field. but when saving the page, the content after the first paragraph break is not saved. However that clipping of the content is not clear until you save and refresh the page.

ideal behavior: the paragraph breaks would be converted to line breaks when pasted into the writer field with `inline: true`

**Comment by afbora** [comment]
Paragraphs with `inline` enabled should be converted to `<br>` when pasting.

**Comment by lukasbestle** [comment]
Fixed by #4351.
