### ISSUE TITLE
video block no preview for youtu.be url [3.6.0-beta]

### ISSUE THREAD

**Issue by maxackerman** [k-next/kirby#3799]
To recreate the bug:
- using 3.6.0-beta.3
- In the panel, with the default video block enter a youtu.be url, for example: https://youtu.be/RaNiHfXCp8A

The issue:
- The panel should show a preview of the video iframe, but the block looks empty and says "enter a video url"

Notes:
- The preview does work if you use vimeo or the full  youtube url, example https://www.youtube.com/watch?v=RaNiHfXCp8A
- Switching to kirby 3.5.7 fixes the issue

**Comment by bastianallgeier** [comment]
✅
