### ISSUE TITLE
panel keyboard modifier 'ctrl' gets stuck [3.6.0-beta]

### ISSUE THREAD

**Issue by maxackerman** [k-next/kirby#3800]
- using 3.6.0-beta-3
- the latest firefox

i often switch tabs using [ctrl]+[tab], when working in the with blocks in the panel, this causes an issue. if i switch focus away from the panel using [ctrl]+[tab], the panel seems to think i still have [ctrl] pressed when i come back. this means that when i click a block i can only get the abbreviated menu:
<img width="174" alt="Screen Shot 2021-10-12 at 1 10 59 PM" src="https://user-images.githubusercontent.com/1308505/137000057-506f2dbe-1925-4d0d-9a9e-3b5b26ab1de6.png">

instead of the full menu:
<img width="204" alt="Screen Shot 2021-10-12 at 1 11 14 PM" src="https://user-images.githubusercontent.com/1308505/137000106-236544b0-ae9c-4463-af6c-6aacff3d6829.png">

took me a minute to figure out what was going on. i can work around this by pressing and releasing [ctrl], or refreshing the page.

**Comment by afbora** [comment]
This is intended behavior. The `CTRL/ALT/CMD + Click` combination is used for multiple selection in blocks field. To multiple copy or delete.

**Comment by maxackerman** [comment]
@afbora i think you're missing the bug - im *not* pressing CTRL but the panel acts like i am.

if i use [ctrl]+[tab] to switch tabs, i think the panel registers the keydown event but not the keyup. so when  i come back to the panel, it acts like [ctrl] is pressed when it is not.

**Comment by afbora** [comment]
Sorry, I missed that. Yes, I've reproduce the issue 🤯

**Comment by bastianallgeier** [comment]
✅
