### ISSUE TITLE
[3.6.0-beta.3] html from page model used as 'info text' in pages section is not being parsed as html anymore

### ISSUE THREAD

**Issue by ralfgoeke** [k-next/kirby#3809]
**Describe the bug**  

**To Reproduce**  

```php
# page model
public function htmlTest()
{
  return '<span style="color: red;">should be red</span>';
}
```

```yml
sections:
  test_sect:
    type: pages
    info: "{{ page.htmlTest }}"
```

**Expected behavior**  
Text should be rendered as HTML, like it worked before, until beta.3

**Screenshots**  

![html-not-parsed](https://user-images.githubusercontent.com/6228942/137275312-29d8d6f2-a827-4b09-a610-bee8a4b5a5d3.png)

**Kirby Version**  
3.6.0-beta.3

**Comment by afbora** [comment]
@ralfgoeke Thanks for report. There is a breaking change here, you need to use like that `{< page.htmlTest >}`

> Several blueprint options that use the query syntax were updated to escape the placeholder values against raw HTML output that may lead to XSS attacks. HTML code directly in the query (like This is <strong>{{ page.important }}</strong>) still works as normal. If placeholders need to return HTML, you can use the new {< site.myMethodWithHtml >} syntax. In this case you need to ensure manually that the returned HTML code is safe. With the {{ }} syntax, Kirby performs the escaping for you.

https://getkirby.com/releases/3.6/breaking-changes#panel

**Comment by ralfgoeke** [comment]
Damn, I overlooked that one. Thanks for the headsup and sorry for the extra work. 🥴
