### ISSUE TITLE
False alarm when using `sort()` on page collection

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#3818]
**Describe the bug**  
I’m using `sort()` on a page collection and get an error regarding the usage of `sort()` on a **single** page.

```
Whoops \ Exception \ ErrorException (E_USER_DEPRECATED)
$page->sort() is deprecated, use $page->changeSort() instead. $page->sort() will be removed in Kirby 3.6.0.
```

**To Reproduce**  
Create a template using the `sort()` method on a page collection, e. g.:
```
$entries = $page->children()->listed()->sort('sort', 'asc');
```

**Expected behavior**  
Sort the collection.

**Kirby Version**  
3.5.7.1

**Comment by afbora** [comment]
This method updates the sort data of the collection items. This is just deprecation warning. What are you aiming at here?

````php
$entries = $page->children()->listed()->sort('sort', 'asc');
````

If you want to get the collection in a certain order:

- `->listed()` method is already returns sorted list. 
- If you want the reverse, you can use `->listed()->flip()` 
- You can sort custom attribute with `->listed()->sortBy('sort', 'asc')`

**Comment by silllli** [comment]
> This is just deprecation warning. 

I know, but it makes development impossible, because it breaks the site.

> ->listed() method is already returns sorted list.

Good to know, I thought I had to manually sort using `sort()`, but apparently that’s only the case with file collections (since files are by default sorted by the filesystem).

> You can sort custom attribute with ->listed()->sortBy('sort', 'asc')

This throws the same error, since `sortBy()` is only an

> Alias for Kirby\Toolkit\Collection::sort

as it says in the [docs](https://getkirby.com/docs/reference/objects/cms/pages/sort-by).

**Comment by texnixe** [comment]
If you wanted to explicitly sort listed pages by sorting number, you would sort by `num` not `sort`: https://getkirby.com/docs/reference/objects/cms/page/num. However, since Kirby does that automatically, there is no need for the sorting argument. I think we should therefore close this issue.

**Comment by silllli** [comment]
Sorry, you probably understand this better. As far as I understood, the error that I am seeing concerns a different scenario.

I’m using `sort()` on a collection, but the error that gets raised is about using `sort()` on a single page.

**Comment by texnixe** [comment]
You are not getting the error because you are using `sort` on a collection, but because you are using `sort` as argument of the `sort` method. Using

```
$entries = $page->children()->listed()->sort('num', 'asc');
```

(or any other value like `title` will work perfectly fine.

**Comment by silllli** [comment]
Ah, ok, now I get it—thank you! Thought it was a bug.
