### ISSUE TITLE
Tab in front of k-tabs-badge

### ISSUE THREAD

**Issue by gitlabisbetterthangithub** [k-next/kirby#3822]
**Describe the bug**  
If tab A has a badge and tab B is clicked, tab B will be in front of the badge.

**To Reproduce**  
1. Click on a page with tabs
2. Edit some text so the unsaved badge appears
3. Click on a different tab

**Expected behavior**  
The badge shouldn't be blocked by the other tab.

**Screenshots**  
![image](https://user-images.githubusercontent.com/40391197/138012646-de00412f-88ff-439b-a9be-dfcd2b0c34c7.png)

**Kirby Version**  
3.6.0-rc.1

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94

**Comment by afbora** [comment]
It may not be that easy. Also here's what it looks like when there are changes for each tab. I'm not sure that it can be a little confusing.

![screen-capture-1212-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/138179314-486be910-44da-47b6-bd4d-69b81c4e7a33.png)

Alternatively, view inside the tab:

![screen-capture-1213-Test - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/138179837-9a2374cb-f097-4325-843a-7243cfbcd934.png)

**Comment by distantnative** [comment]
I have to say I like that alternative design a lot

**Comment by bastianallgeier** [comment]
@afbora I like your version as well. Could you create a PR for it?

**Comment by bastianallgeier** [comment]
✅
