### ISSUE TITLE
Layout shift when dialog or drawer is opened

### ISSUE THREAD

**Issue by gitlabisbetterthangithub** [k-next/kirby#3823]
**Describe the bug**  
Opening a dialog (such as rename) or block drawer causes a layout shift due to the scroll bar disappearing.

**Expected behavior**  
There should not be any layout shift

**Kirby Version**  
3.6.0-rc.1

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94

**Comment by afbora** [comment]
@bastianallgeier You marked it easy. I tried to fix this yesterday, but if I fix one place, the other places are broken 🙂

**Comment by bastianallgeier** [comment]
✅
