### ISSUE TITLE
Image previews in files section lists no longer take up full container

### ISSUE THREAD

**Issue by gitlabisbetterthangithub** [k-next/kirby#3824]
**Screenshots** 
3.6.0-rc.1
![image](https://user-images.githubusercontent.com/40391197/138014310-61d2d592-2c74-44b5-8ee2-abc9606703fb.png)
3.5.7.1
![image](https://user-images.githubusercontent.com/40391197/138014398-d89b8349-a427-46a2-a4bd-f8e205e7229d.png)

**Kirby Version**  
Kirby 3.6.0-rc.1

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome
 - Version: 94

**Comment by bastianallgeier** [comment]
This is not a bug but a feature of 3.6. In earlier versions the cover option for images did not have any effect in list views. With 3.6 you can now decide if the preview images should be cropped or not, just like in the cards or cardlets layout. You could say that the cover option was broken for list views before 3.6. Just set cover: true in your blueprint to get back the old behavior.

**Comment by gitlabisbetterthangithub** [comment]
@bastianallgeier Thank you. I think having cover: true as the default for lists makes more sense for smaller images otherwise the image preview is much smaller and space is probably being wasted. With this in mind and for backwards compatibility perhaps it's worth making cover: true as the default for file lists?
