### ISSUE TITLE
 Issue rendering markdown in blocks within a structure

### ISSUE THREAD

**Issue by viciouskitten** [k-next/kirby#3831]
**Describe the bug**  
I am using blocks within a structure. All of the other types of block seem to be working fine but when i use the Markdown block it’s not rendering correctly.

This is how the .yml file is saving my markdown. It seems to be adding quotes around it
`  documentation: '[{"content":{"text":"# An H1 Header\n## An H2 Header\n### An H3 Header\n#### An H4 Header"},"id":"d99269ab-21a5-4d21-94e7-7e9ff838238b","isHidden":false,"type":"markdown"}]' `

If i change it to this in the .yml file it works fine:
`documentation: |
    [{"content":{"text":"# An H1 Header\n## An H2 Header\n### An H3 Header\n#### An H4 Header"},"id":"d99269ab-21a5-4d21-94e7-7e9ff838238b","isHidden":false,"type":"markdown"}]`

**To Reproduce**  
1. In a .yml file create a 'structure' field
2. Nested within the structure field create a 'blocks' field
3. Go into the panel and add a structure and a markdown block within that
4. When you view the page in the browser the markdown isn't rendering correctly

**Expected behavior**  
For markdown to be rendered correctly in the browser

**Screenshots**  
How the panel looks with the markdown code:
<img width="836" alt="Screenshot 2021-10-20 at 20 41 30" src="https://user-images.githubusercontent.com/6408631/138175804-0a2bd1ca-f318-4ca7-9495-3ce9adb62380.png">

How it looks:
<img width="586" alt="Screenshot 2021-10-20 at 22 27 23" src="https://user-images.githubusercontent.com/6408631/138176141-6ef399b8-eeec-4f56-a531-be907eaacc18.png">

How it should look:
<img width="525" alt="Screenshot 2021-10-20 at 22 39 39" src="https://user-images.githubusercontent.com/6408631/138176220-fd3cd119-aed7-4612-81e4-32dea7e9f99f.png">

**Kirby Version**  
3.5.7.1

**Console output**  
No errors

**Desktop (please complete the following information):**  
 - OS: Mojave 10.14.6
 - Browser: Firefox
 - Version: 93.0

**Comment by bastianallgeier** [comment]
Thanks for the detailed issue report. This is an issue with the yaml parser. We are already planning a fix for this by switching to JSON for structure fields. I'm afraid I cannot offer a good fix for this in the meantime.

**Comment by afbora** [comment]
I'm closing this for now. We have a ticket connected to this issue in the backlog and we will follow up 🧐

**Comment by viciouskitten** [comment]
Thank you!
