### ISSUE TITLE
[3.6.0] Fiber dialogs closed on nested dialog submit

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#3840]
I have a Fiber form dialog that has a page picker on one custom field.
When the page picker opens its dialog and a page is selected, the Fiber dialog closes as well instead staying open and receiving the value.

**Comment by distantnative** [comment]
https://user-images.githubusercontent.com/3788865/138562490-cbce4039-8350-4d51-be65-91300799a15b.mov

**Comment by bastianallgeier** [comment]
Oh wow, did this work in 3.5.x? I never thought that nested dialogs worked or were used at all. This is going to be tricky to fix.

**Comment by distantnative** [comment]
To be honest, I was using a drawer with nested dialog before. So can't say for sure.

Aldo happy about alternative ideas how to deal with a page picker inside a form dialog.

**Comment by bastianallgeier** [comment]
So the main problem is that you cannot use the drawer with Fiber so far, right?

**Comment by distantnative** [comment]
Drawer also wasn't a favorite with users since the current drawer is very much made for the blocks and not a good dialog replacement, e.g. no proper way to cancel.

**Comment by distantnative** [comment]
Closing this for now.

**Comment by steirico** [comment]
Do you guys have any suggestion on how to solve or workaround this issue? We are facing the very same situation with the [Custom Add Fields plugin](https://github.com/steirico/kirby-plugin-custom-add-fields/issues/65).

**Comment by distantnative** [comment]
@steirico havent found a way for nested dialogs so far
