### ISSUE TITLE
[3.6.0] `Panel::go()` doesn't work on dialog submit event

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3843]
According to 3.6 release document:
http://getkirby.test/releases/3.6/fiber/dialogs#submit-event-responses

> You can redirect the Panel to a different location after submitting the dialog by calling:

But `Panel::go()` doesn't work in dialog submit event. Is this bug or removed feature?

> The dialog could not be submitted

Related line:
https://github.com/getkirby/kirby/blob/3.6.0-beta.3/panel/src/components/Dialogs/FiberDialog.vue#L34-L37

---

As workaround, I've used returning array that includes `redirect` option, instead of using `Panel::go()`:

````php
 return [
  'redirect' => '/panel/pages/path'
];
````

**Comment by bastianallgeier** [comment]
Ups, seems like I didn't close this. It's already fixed in the RC.
