### ISSUE TITLE
User language is not correctly set in a multi-language site via the panel

### ISSUE THREAD

**Issue by mlthrk** [k-next/kirby#3844]
**Describe the bug**

In a multi-language site you can only set the user language (via the panel) after switching the language of the page and only between the languages set up for the site.

**To Reproduce**

1. Set up a multi-language site
2. Go to “Your Account” and change user language (not working)
3. Switch language of the page via the panel
4. Change user language
5. User language changes to the other set up language

**Kirby Version**

3.6.0-rc.1 (everything works as expected in 3.5.7.1)

**Additional context**

Post request seems to be set to the language the page has been switched to:
`POST | …/panel/dialogs/users/…/changeLanguage?language=de`

**Comment by afbora** [comment]
The `$_POST` language parameter seems to conflict with the `$_GET` language parameter. If we change the `$_POST` language parameter to `lang` or `userLanguage` it will work.

**Comment by bastianallgeier** [comment]
✅
