### ISSUE TITLE
[3.6.0-rc.1] Error on install: Call to a member function id() on null

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#3846]
**Describe the bug**  
When trying to install Kirby 3.6.0 RC 1 from scratch, I get the following error after providing all needed credentials:

> Call to a member function id() on null

After dismissing the error message, I still see the installation form without any notice about what to do now. Manually navigating to `/panel` gives me the login form and allows me to actually login, too.

**To Reproduce**  

1. Download the plainkit.
2. Update the `kirby` folder to the latest files from the RC 1.
3. Go to `/panel` and follow the installation instructions.
4. Hit install and see the error dialog.

**Expected behavior**  
There should be no error and the user should be redirected to panel.

**Screenshots**  
<img width="351" alt="grafik" src="https://user-images.githubusercontent.com/25466/138692536-2a5e835f-362b-4e8b-8dc6-90e68c47380f.png">

**Kirby Version**  
Kirby 3.6.0 RC 1

**Console output**  
No output.

**Desktop (please complete the following information):**  
Latest Firefox on macOS Big Sur

**Comment by bastianallgeier** [comment]
I cannot reproduce this. Which language do you choose when you install the panel? Anything else that could be special in your setup?

**Comment by nilshoerrmann** [comment]
I chose German in this case. This is more or less the plainkit with some plugins. I'll try again without any plugins (there shouldn't be any interacting with installation process though). Am I right, that the only hooks fired during installation are user related?

**Comment by nilshoerrmann** [comment]
Okay, I'm sorry, this is indeed plugin related and works without them.
