### ISSUE TITLE
Navigation layout on small screens

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#3847]
Using the German localisation, the navigation doesn't break well on smaller screens:

<img width="510" alt="grafik" src="https://user-images.githubusercontent.com/25466/138711465-6f67f00f-f137-42a0-98d2-e0776961664c.png">

This happens shortly before the UI hides the labels on small screens and might be related to word length in German.

### Kirby Version

Kirby 3.6.0-rc.1 (and prior, I guess).

**Comment by distantnative** [comment]
Let's break this down what would be the ideal case

### The problem
When the left button group gets too long and wraps, all starts to fall apart.

### Solution?
 - ensure that prev/next buttons don't wrap but stay next to each other
 - let prev/next block wrap to next line first before wrapping buttons from left slot
 - sure flexible height for the wrapper (so that buttons don't overspill into headline and horizontal line)

**Comment by nilshoerrmann** [comment]
On very small screens, the navigation removes the text labels to keep things compact. I think this layout switch is determined by a static breakpoint. It might be an idea to toggle the compact layout with a class instead, comparing the required space for the navigation with the actual screen width using JavaScript.

**Comment by distantnative** [comment]
We haven't been fans that much of measuring things with JS to do styling. This adds up with each component and often that's when applications start feeling not so responsive. Container queries of course would be the solution. Let's see if there's ways to tackle this without JS measuring.

**Comment by nilshoerrmann** [comment]
Being conservative with JavaScript for measurement is certainly a good rule of thumb. But this is one of the situation where it might be actually more useful than harmful, especially with an UI already rendered with JavaScript. Making the navigation break into multiple lines is of course way better than the current situation but it will in the end add up to a lot of vertical space used by the navigation.

But I understand your reservations regarding my suggestion.
