### ISSUE TITLE
Default not stored on field with translate: false, when creating from secondary lang

### ISSUE THREAD

**Issue by plagasul** [k-next/kirby#3852]
**Describe the bug**  

If a field has a default value AND is `translate: false` AND a page with such field is created **while in a secondary language in the panel** THEN the default value is not stored at all in the text file

**To Reproduce**  

1. On a site with at least two languages, create a blueprint that includes such a field, example:

```
test:
    type: number
    default: 1
    translate: false
```

2. Switch to the secondary language
3. Create a new instance of the page containing the field
4. The default value is not stored on the text file, and then not shown on the panel

**Expected behavior**  

The default value should be applied regardess of translate being set to false.

**Kirby Version**  
3.5.6

**Desktop (please complete the following information):**  
 - OS: Linux Mint 20.1 Cinnamon
 - Browser: Chrome
 - Version: 92.0.4515.159 

**Additional context**  

> I actually think if the value is stored in the default language when translate is [true] or not set, then the same logic should also apply when the translate: false is set. @texnixe 

https://forum.getkirby.com/t/when-translate-false-creating-in-second-lang-does-not-apply-default-value/23770/4

**Comment by plagasul** [comment]
Would like to know if this is not considered a bug, or if there is missing info etc.

Thank you

**Comment by texnixe** [comment]
@plagasul Your example code should have `translate: false` instead of `translate: true`.

**Comment by plagasul** [comment]
This does not seem to have received any attention since I posted it. Is there info missing? Should this be a reccomendation instead of a bug ?

**Comment by distantnative** [comment]
I can confirm it is a bug, though we have not found a fix for it so far
