### ISSUE TITLE
[3.6.0-rc.2] Files name and link broken in unsaved changes

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3854]
**Describe the bug**  

**To Reproduce**  
1. Go to panel (demokit)
2. Go to file detail (`/pages/portfolio+projects+sky/files/tent-in-the-woods.jpg`)
3. You'll see unsaved changes
4. See file name missing
5. Nevertheless click it, you'll see broken link that missing `files` segment (`/panel/pages/portfolio+projects+sky+tent-in-the-woods.jpg`)

**Kirby Version**  
3.6.0-rc.2

**Comment by bastianallgeier** [comment]
✅
