### ISSUE TITLE
[3.6.0-rc.2] Hidden blocks shows in layout field

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3857]
**Describe the bug**  

Although a block is hidden in the layout field, it is still shown.

**To Reproduce**  
1. Go to panel
2. Enter any page that have layout field
3. Hide any block and save page
4. Preview page and see issue

**Expected behavior**  

**Screenshots**  

![image (30)](https://user-images.githubusercontent.com/3393422/139157432-7af58882-576d-4ca2-b153-557115d2e2bf.png)

**Kirby Version**  

3.6.0-rc.2

**Comment by bastianallgeier** [comment]
Interesting! Is this a regression or did this happen in 3.5.7.1 as well?

**Comment by afbora** [comment]
I don't know which would be better but it's not regression :))

**Comment by bastianallgeier** [comment]
Hm, it looks like this is more of a conceptual question. 

We filter hidden blocks in the toBlocks method, but to render blocks within layouts, we simply use `$column->blocks()`T This will return all blocks unfiltered and create the HTML foreach. 

The big question now is, where do we solve it? 

Maybe we should think about actually hiding blocks in the toHTML method instead. When a block is hidden, the toHTML method could simply return null or an empty string.

**Comment by afbora** [comment]
I guess we should add filter here:
https://github.com/getkirby/kirby/blob/develop/src/Cms/LayoutColumn.php#L43-L45

````php
$this->blocks = Blocks::factory($params['blocks'] ?? [], [
    'parent' => $this->parent
])->filter('isHidden', false);
````

**Comment by bastianallgeier** [comment]
We have to be careful because when we implement it like that there's no chance to get the full list of columns unfiltered anymore. That's kind of the big conceptual problem.

**Comment by afbora** [comment]
Ohh, I see.. I've an idea for `LayoutColumn::blocks()` method, what do you think?

````php
public function blocks(bool $includeHidden = false)
{
    if ($includeHidden === false) {
        return $this->blocks->filter('isHidden', false);
    }
    
    return $this->blocks;
}
````

**Comment by bastianallgeier** [comment]
That looks like a good idea. We could do the same for the toBlocks method to keep it consistent.

**Comment by bastianallgeier** [comment]
✅
