### ISSUE TITLE
Undo breaking change on `Kirby\Form\FieldClass`

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3866]
> Declaration of Kirby\Form\Field\CustomField::store($value) must be compatible with Kirby\Form\FieldClass::store($value = null)

Existing plugins started giving compatibility issues. This breaking change should be documented.

**Comment by bastianallgeier** [comment]
TBH, I think we should undo the breaking change. It's not necessary. I only changed it because I thought it doesn't have any side-effects.

**Comment by bastianallgeier** [comment]
✅
