### ISSUE TITLE
[3.6.0-rc.2] Language dropdown missing when adding languages manually

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#3888]
**Describe the bug**  
When I manually add languages ([as described here](https://getkirby.com/docs/guide/languages/introduction#adding-languages__manually)), the language dropdown no longer appears in the panel header on each page. 

When I enable languages in the config ([as described here](https://getkirby.com/docs/guide/languages/introduction#enabling-the-multi-lang-feature-in-the-panel)), the language dropdown is displayed in the panel header.

**To Reproduce**  
1. Download plainkit
2. Update to Kirby 3.6.0-rc.2
3. Manually add php files for languages

**Kirby Version**  
3.6.0-rc.2

**Comment by afbora** [comment]
Did you enabled with `languages` option?

https://getkirby.com/docs/guide/languages/introduction#enabling-the-multi-lang-feature-in-the-panel

**Comment by afbora** [comment]
For multi-language app, you need to have the `languages` option enabled in the config file and have added at least one language.

**Comment by SebastianEberlein-JUNO** [comment]
I’ve never enabled `languages` in the config before, because I do not want our clients to add or delete languages.
In Kirby 3.5 and older, I just added the PHP files in `/site/languages` and the languages dropdown appeared.

**Comment by afbora** [comment]
To be honest, I didn't know that either 😅 I'm not sure if this is an expected breaking change, let's ask @bastianallgeier 

Also now in 3.6 the language and system view are separated and you can now hide them from permissions:

https://getkirby.com/releases/3.6/features/language-view

**Comment by bastianallgeier** [comment]
✅
