### ISSUE TITLE
[3.6-rc.2] Error notifications not working anymore

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#3890]
![CleanShot_2021-11-01_at_19 29 33](https://user-images.githubusercontent.com/3788865/139722682-dc4b2982-8889-494e-bab5-c9b2bf61f3d2.png)

These calls have no effect anymore.

It used to be that `k-error-dialog` automatically displays itself if there is an error notification set in the store: https://github.com/getkirby/kirby/blob/main/panel/src/components/Dialogs/ErrorDialog.vue

The component got refactored to work for Fiber responses that return an error: https://github.com/getkirby/kirby/blob/develop/panel/src/components/Dialogs/ErrorDialog.vue

However, the whole notification store logic was completely dropped and also not moved to any other part of the Panel code. We need to reintroduce that logic.

**Comment by bastianallgeier** [comment]
✅
