### ISSUE TITLE
"Invalid redirect URL" error message without using "Redirect URLs"

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#3892]
**Describe the bug**  
I sporadically get an "Invalid redirect URL" error message after login, even though I don't have any redirect URL configured. 

**To Reproduce**  
Unknown. 😢 

It happened 2 times now, both times after waiting enough to have the session expire and be logged out of the panel. PC was "suspended" in the meantime (server is on another machine). I already know that the CSRF token is expired at that time, so I refresh the login page to get a new one, after the login (which works), I'm being shown the error page (the top bar with the menu is visible).

**Expected behavior**  
When no redirect URL is configured and I have access to the "Site" area, I should be redirected to the "Site" area without error. :)

**Kirby Version**  
3.6.0-RC.2

**Console output**  
> Failed to load resource: the server responded with a status of 400 (Bad Request)

(sadly I don't have more details, since I had dev tools closed when the page loaded)

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95

**Additional context**  
After refreshing the page with the error, it goes away and I see the correct content. So, no big problem. :)

**Comment by bastianallgeier** [comment]
✅
