### ISSUE TITLE
[3.6.0-rc.3] File rename action: `TypeError: Cannot read properties of undefined (reading 'changes')`

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3896]
**Describe the bug**  

Getting `TypeError: Cannot read properties of undefined (reading 'changes')` error when file rename dialog submitted. File renamed successfully but error thrown.

**To Reproduce**  
1. Go to panel
2. Try to rename any file
3. See console error: `TypeError: Cannot read properties of undefined (reading 'changes')`
4. Change page and see error dialog

**Kirby Version**  

3.6.0-rc.3

**Comment by bastianallgeier** [comment]
✅
