### ISSUE TITLE
Blank screen in panel

### ISSUE THREAD

**Issue by chrisbeluga** [k-next/kirby#3897]
**Description**  
When loading the panel on shared hosting it returns a blank screen on the latest release. The output of the page is blank with zero mark-up, scripts or styles. No Error logs.

**Kirby Version**  
3.6.0-rc.2

** Environment **
Linux Shared Hosting with cPanel
PHP 8.0

I don't have any further details at the moment, will find out as currently on a clients server.

**Comment by afbora** [comment]
Did you try to delete `/media` folder?

**Comment by chrisbeluga** [comment]
Yes, Media folder has been deleted, all plugins have been removed. Front end works fine, just the panel which isnt loading

**Comment by bastianallgeier** [comment]
Can you please try with rc 3?

**Comment by chrisbeluga** [comment]
This is the same with rc3, I'm speaking to the hosting company to see if they can shed any light on the issue and whether they can spot anything. The panel did load originally and returned this error to the console

```index.js:1 Uncaught (in promise) Error: The JSON response from the API could not be parsed
    at Object.onParserError (index.js:1)
    at Q (index.js:1)
    at async Object.request (index.js:1)
    at async Object.go (index.js:1)
```

then went back to a blank screen...

**Comment by bastianallgeier** [comment]
Is there a chance we can have a look at the installation? Could it maybe also be a browser issue? Which browser do you use?

**Comment by bastianallgeier** [comment]
We were able to track this down.
