### ISSUE TITLE
[3.6.0-rc.3] Slugs are not created correctly in a multilanguage website

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#3900]
**Describe the bug**  
Umlauts are not "slugified" correctly in a multilanguage website.

**To Reproduce**  
1. Download plainkit
2. Update to kirby 3.6.0 rc.3
3. Add new user to panel, use German as Panel language
3. Enable languages in `config.php`: `'languages' => true`
4. Add German and English languages in Panel
5. Create new page with umlaut

**Expected behavior**  
In Kirby 3.5, umlauts are slugified correctly in a multilanguage website. Without having to add language specific slug rules (https://getkirby.com/docs/guide/languages/slug-rules).

**Screenshots**  
<img width="514" alt="Screenshot" src="https://user-images.githubusercontent.com/77532479/140030938-ffff7431-cc4e-4f85-97bc-691efac8583c.png">

**Kirby Version**  
3.6.0-rc.3

**Comment by bastianallgeier** [comment]
✅
