### ISSUE TITLE
[3.6.0-rc.3] Title in site blueprint cannot be changed

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#3901]
**Describe the bug**  
Changing the `title` in the site blueprint does no longer work.

**To Reproduce**  
1. Download plainkit
2. Update to kirby 3.6.0 rc.3
3. Open `site.yml`, change `title:`

**Expected behavior**  
In Kirby 3.5, changing the title is possible: https://getkirby.com/docs/reference/panel/blueprints/site#title

**Kirby Version**
3.6.0-rc.3

**Comment by bastianallgeier** [comment]
✅
