### ISSUE TITLE
[3.6.0-rc.3] Monospace font not working in textarea

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#3902]
**Describe the bug**  
Monospace font not working in textarea

**To Reproduce**  

1. Download plainkit
2. Update to kirby 3.6.0 rc.3
3. Open `site/blueprints/pages/default.yml` and set the textarea field to `font: monospace`

**Expected behavior**  
In Kirby 3.5, it works. https://getkirby.com/docs/reference/panel/fields/textarea#monospace

**Kirby Version**  
3.6.0-rc.3

**Comment by bastianallgeier** [comment]
✅

**Comment by afbora** [comment]
@SebastianEberlein-JUNO We appreciate your tests and bug reports 👏 💛

**Comment by bastianallgeier** [comment]
@SebastianEberlein-JUNO @afbora 💯
