### ISSUE TITLE
Pages section with no ability to add pages shows cursor icon

### ISSUE THREAD

**Issue by trych** [k-next/kirby#3915]
**Describe the bug**  
If I have an empty pages section with `status: listed` or `status: unlisted` that does not offer me a possibility to add pages, the mouse still changes to a cursor icon when I hover over the section. This indicates that I can do something, which I can't.

**To Reproduce**  
Create a pages section with `status: listed` and default settings otherwise, check out the result in the panel and move your mouse over it.

**Expected behavior**  
It should just show the regular mouse cursor in this case.

**Screenshots**  
![cursor](https://user-images.githubusercontent.com/9803905/140612095-21f5d183-13fe-4151-9430-b0c7ac21edfc.jpg)

**Kirby Version**  
3.5.7.1

**Desktop (please complete the following information):**  
macOS, 10.13.6

**Comment by bastianallgeier** [comment]
✅
