### ISSUE TITLE
Pages section on user page without parent field throws cryptic error message

### ISSUE THREAD

**Issue by trych** [k-next/kirby#3916]
**Describe the bug**  
~~If I want to add a pages section to a user blueprint (for example to list all the user's pages, especially when their permissions dis-allow them to access the site), it does not show up and I just get an error:~~
If I add a pages section to a user page without using a parent field, I get this far too cryptic error:
```
The section "projects" could not be loaded: Undefined property: Kirby\Cms\Field::$data
```

**To Reproduce**  
Create a user blueprint and add any pages section without `parent` setting to the blueprint.

**Expected behavior**  
~~It should display the pages section like it does on other pages.~~
While I now understand that this would not work (as a user cannot be parent to subpages), this should throw a more helpful error messages, to allow users to figure out *why* this does not work and what they should do instead. Same might go for file pages (I assume?).

**Screenshots**  
![20211106-145719_Screenshot_GoogleChrome](https://user-images.githubusercontent.com/9803905/140612258-0af96458-306a-4b24-9f91-23ddd568e35b.png)

**Kirby Version**  
3.5.7.1

**Desktop (please complete the following information):**  
macOS 10.13.6, Chrome 95.0

**Comment by texnixe** [comment]
Have you passed a parent, e.g.

```
    sections:
      pages:
        type: pages
        parent: site.find('notes')
```

**Comment by trych** [comment]
🤦‍♂️

Sorry, I realize my mistake now.
However, I will edit this issue to suggest to give a more helpful error message in this case, then maybe users like me could better figure out themselves why it's not working.

Edit: Done. And thanks for pointing out my error @texnixe !

**Comment by bastianallgeier** [comment]
✅
