### ISSUE TITLE
The Writer Field. Strikethrough-ing text removes it completely

### ISSUE THREAD

**Issue by herrajon** [k-next/kirby#3920]
When the user strikethroughs a text in the writer field in the backend/panel it is removed from the .txt/.md file completely on Save.

This is in order in 3.5.7.1 but the observed behaviour is confirmed present in 3.6-RC1, 3.6-RC3 & 3.6-RC4. 

**To Reproduce**  
1. On a page with the Writer Field
2. Write some text..
3. Then strikethrough it or some part of it for best results ..
4. Save
5. Refresh the page 
6. Behold. it is gone

**Expected behavior**  
The text should stay in its place with its strikethrough marks.

**Screenshots**  
![image](https://user-images.githubusercontent.com/182769/140775614-57ccbd0a-2f29-4c0a-8ab9-8ede3185039c.png)

**Kirby Version**  
Seems this is present in the latest RC versions of Kirby.

Thanks
-j

**Comment by bastianallgeier** [comment]
✅
