### ISSUE TITLE
Removing layout from layout field causes scrollbar disappear

### ISSUE THREAD

**Issue by janherman** [k-next/kirby#3923]
**Describe the bug**  
After the layout is deleted from layout field the scroll bar disappears.

**To Reproduce**  
1. Add new layout to layout field.
2. Remove the layout.
3. The page scrollbar disappears (it seems HTML element gets *overflow: hidden*).

**Kirby Version**  
3.6.0-rc.4

**Desktop:**  
 - OS: Windows 10
 - Browser: Mozilla Firefox Developer, Google Chrome
 - Version: 95.0b4, 95.0.4638.69

**Comment by afbora** [comment]
So similiar issue with #3823

**Comment by bastianallgeier** [comment]
✅
