### ISSUE TITLE
Title position in section cards

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#3932]
**Describe the bug**
Titles in section cards are incorrectly positioned and display centered and not aligned to the top.

**To Reproduce**  
Use this blueprint:

```yaml
title: Card Titles
preset: pages
listed:
  extends: sections/articles
  layout: cards
```

**Expected behavior**  
Title should be aligned to the card's top.

**Screenshots**  
<img width="952" alt="Bildschirmfoto 2021-11-15 um 14 35 58" src="https://user-images.githubusercontent.com/25466/141796611-9c37c927-e7ee-4ab5-a721-439d4707cdad.png">
See the third card with centered text.

**Kirby Version**  
3.6.0 RC 5, not sure about previous versions.

**Additional consideration**  
Card titles are restricted to a very narrow width. For sections with longer titles, it would be interesting to have them span the full card width to improve readability (especially with hyphenated words).

*currently:*
<img width="1112" alt="Bildschirmfoto 2021-11-15 um 14 32 25" src="https://user-images.githubusercontent.com/25466/141797356-27bdfa02-7db0-4db0-9254-f3da78cfdd49.png">

*suggestion:*
<img width="1114" alt="Bildschirmfoto 2021-11-15 um 14 29 53" src="https://user-images.githubusercontent.com/25466/141797380-8b3db3fa-98a9-4217-9524-eefece36d726.png">

**Comment by distantnative** [comment]
✅
