### ISSUE TITLE
Pages section doesn't accept a content representation as an image anymore

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#3933]
**Describe the bug**  

If you create a content representation for a model, e.g. `album.svg.php`, in 3.5.7.1 you can then return this content representation as a preview image to the pages section.

**To Reproduce**  
1. Create new starterkit site
2. Create template `album.svg.php` with any valid svg code
3. Change the `models/album.php:cover()` function to return `new Asset()`
4. Observe it working in 3.5.7.1
5. Upgrade to 3.6-rc5
6. Observe it not working and be sad.

**Expected behavior (3.5.7.1)**  

![CleanShot 2021-11-15 at 16 53 10](https://user-images.githubusercontent.com/481362/141812541-0abccca8-da73-4c10-a9f5-22e81f425d65.png)

**Actual behaviour (3.6)**  

![CleanShot 2021-11-15 at 16 53 45](https://user-images.githubusercontent.com/481362/141812687-f445a3f8-6be1-47eb-9eaf-08f85d89d4c3.png)

**Additional context**  

Full repo of what I'm testing: https://github.com/adamkiss/kirby3.6-svg

Switching between the version with following commands:

``` sh
# upgrade to rc
composer remove getkirby/cms && composer require getkirby/cms:3.6.0-rc5 -W
# latest stable
composer remove getkirby/cms && composer require getkirby/cms
```

**Comment by adamkiss** [comment]
Update: tested `rc.1` and `alpha.1` and neither shows the SVG. I suppose it's somewhere in the `k-item` switch

**Comment by bastianallgeier** [comment]
✅
