### ISSUE TITLE
Single-item pages() deprecation warning should be silenced when explicitly passing an array

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#3938]
**Describe the bug**  
When passing an array with a single item to the `pages()` helper, the should deprecation warning be silenced.

**To Reproduce**  

```php
$pages = pages(['example-page']);
```
returns a Pages collection on Kirby 3.5.x, there should be no need to warn about behavior change in this situation

**Expected behavior**  
Throw no exception.

**Screenshots**  

<img width="541" alt="Screen Shot 2021-11-16 at 3 56 47 PM" src="https://user-images.githubusercontent.com/417182/142084833-6188c204-7c41-4a28-a68b-b842a4727d02.png">

**Kirby Version**  
`3.6.0`

**Comment by distantnative** [comment]
✅
