### ISSUE TITLE
Slug sync each time reloading the Panel

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#3940]
There is a strange behavior with field 'Slug'. To reproduce it, do the following:

1. create a blueprint with a label and a slug field (sync slug with label).
2. go to the panel and set the label
3. change the value of the slug as you like
4. save and reload the panel

**To expect:**
The slug should keep its value (no matter what the label is).

**What happens:**
The slug resynchronizes with the label

**Comment by distantnative** [comment]
If I understand you correctly, the field just does what it's supposed to do:
A slug field with `sync: label` will always sync itself automatically with the value of the `label` field.

If you only want to generate the slug value from the label field at some point in times, but edit it on others, the `sync` option doesn't seem like a good fit for you. But rather try the `wizard` option that adds a button for one-click generation of the slug value from the other field - https://getkirby.com/docs/reference/panel/fields/slug

```yaml
wizard:
  text: "Generate from label"
  field: label
```

Does this solve your question? Or did I misunderstand your general problem?

**Comment by plain-solutions-gmbh** [comment]
Hm. that's right. You can use the wizard-option indeed.
But then i missed the idea behind of the sync-option.
In this case i could remove the slug-field and convert the label-field programmatically.

**Comment by distantnative** [comment]
@bastianallgeier might correct me, since he built the field:

I think the `sync` option does exactly what the word says, it keeps the value of the referenced field (label) always in sync with the value of the slug field.

Not sure why the wizard option wouldn't be the solution for your use case.

**Comment by plain-solutions-gmbh** [comment]
The wizard where an alternative solution. It's more about the understanding of the `sync` option.
It's pretty confusing if you change a value and after saving, there's a different value.

**Comment by bastianallgeier** [comment]
This is indeed a bug. The slug field should indeed keep the value in sync, but once a custom slug has been stored it should only resync again once the value of the synced field actively changes. This should not happen when the form is reloaded, but only when you start typing again.

**Comment by plain-solutions-gmbh** [comment]
But then the `wizard` option would not make sense. 🙈
I thought the Wizard option would be available on every field.

Which brings me to the thought: What a huge sensation it would be if `wizard` would be available on every field. Especially if you could use it to execute methods within the field. Returning the content of the field.

This as a thought experiment. But that would be another topic...

**Comment by plain-solutions-gmbh** [comment]
> But then the `wizard` option would not make sense. 🙈
Okay, maybe in case, the slug-field is not required... 🙊

**Comment by medienbaecker** [comment]
FYI: I thought setting the slug field to `disabled: true` would be a good UX workaround for this issue, but it disables syncing too. Not sure if this should receive its own issue, though.

```yml
# synced and editable but value is not saved
anchor:
  type: slug
  sync: title
```
```yml
# not synced and not editable
anchor:
  type: slug
  sync: title
  disabled: true
 ```

**Comment by bastianallgeier** [comment]
This turns out to be a much bigger brainfuck than I anticipated. It's easy in the dialogs where we normally use it. But with the way our content forms work, I haven't found a way yet to get it right. I'm still on it, but it will probably take longer than expected.

**Comment by afbora** [comment]
I actually have a solution for this. But as @distantnative said `sync` does exactly the right thing. If we have a new prop like `immutable` we can offer a permanent solution.

If `immutable` is enabled, the entered value cannot be changed after the page is saved/refreshed. It can also work independently of the `sync` feature. What do you think?

````yaml
anchor:
  type: slug
  sync: title
  immutable: true
````

**Comment by bastianallgeier** [comment]
@afbora I have a knot in my head. I think the current implementation is not correct. IMHO the field should automatically "know" if the value has been modified manually and in this case the value should no longer be synced afterwards. I think this should be the default behaviour without an additional option, but we need to discuss and test this further. I have actually no idea how to implement that knowledge state about a manual modification in the field without converting the value to an object. Something like: 

``` 
mySlugField: 

value: something
synced: true
```

But this is of course not what we want. Let's move this to 3.6.x and rethink it again.

**Comment by youngcut** [comment]
I don't understand the idea behind the `immutable`-props either.
@bastianallgeier I see in the code, you let the backend do the job of the sync. It is a pragmatic solution, but why not put an event listener on the sync element with js..?

**Comment by youngcut** [comment]
That would also make the discussion about the `disabled`-behavior obsolet.

**Comment by plain-solutions-gmbh** [comment]
@bastianallgeier Told you I would like to fix this bug. 😉  Hope you are not angry when I removed your wizard. 🧙‍♂️

**Comment by plain-solutions-gmbh** [comment]
The only thing i see right now is, that, when the user change the sync field, the slug field sync again. Or did i overlooked something else?
In my view, it's less confusing, then changing after reload. I thing it depends on editors use case.
Or we can make a button (like wizard) to lock the sync.

**Comment by plain-solutions-gmbh** [comment]
Why is this case still open? Is something wrong with my solution?

**Comment by distantnative** [comment]
@youngcut It does take some time to review this one, it's not a very straightforward scenario. But we'll try for 3.6.3!

**Comment by plain-solutions-gmbh** [comment]
Okay.
Btw: I'm so sorry to rip the wizard out of the slug field. I think, it's something really needed (or not annoying if not in use).
So please just add Line 75 - 79 to SlugInput.vue.
