### ISSUE TITLE
Empty writer field contains <p></p>

### ISSUE THREAD

**Issue by maxackerman** [k-next/kirby#3943]
**Describe the bug**  
When an empty writer field (without inline: true) is saved it leaves `<p></p>`. Thus, methods such as isNotEmpty() won't work.

**To Reproduce**  
1. Type something in a writer field, save the page.
2. Remove text from the field, save page.
3. Content file will now have <p></p>

**Kirby Version**  
3.6.0

**Reated**  
https://github.com/getkirby/kirby/issues/3115
https://github.com/getkirby/kirby/pull/3128

**Comment by distantnative** [comment]
@afbora since you were working on the initial PR https://github.com/getkirby/kirby/pull/3128, could you please have a look at this?

**Comment by afbora** [comment]
@bastianallgeier This issue occur from following line and commit:
https://github.com/getkirby/kirby/commit/5969115f724b8ec20ee34e4526b2b007749cb48b#diff-01c95df67f5cecc380b19d27d4f939f52649f3eb80cd31e83cb9a13d5c031046R203

What do you think about moving this payload line to before `if`  condition, this should work.

**Comment by afbora** [comment]
@bastianallgeier Need your review to fix on next release.

**Comment by bastianallgeier** [comment]
@afbora looks right to me!

**Comment by bastianallgeier** [comment]
✅
