### ISSUE TITLE
Dots in list items overlay popup menu

### ISSUE THREAD

**Issue by fabianmichael** [k-next/kirby#3944]
**Describe the bug**  
In `<k-items>` components, the dots of following list items have a higher stacking index, than the actual popup. This does not only cause visual artifacts, but also creates an unwanted hit area for the popup buttons of other list items.

**To Reproduce**  
1. Go to the panel
2. Click on any list items that opens a popup

**Expected behavior**  
The dots icon should be hidden behind the popup

**Screenshots**  
<img width="307" alt="Bildschirmfoto 2021-11-18 um 18 38 00" src="https://user-images.githubusercontent.com/395617/142467616-843bd86e-51a1-408c-aec5-98a8e212c6c7.png">

Dots have been colored red for demonstration. This becomes only visible, if the text of items in the popup is long enough, so it reaches the right side of the popup and there is actual overlap.

![Bildschirmfoto 2021-11-18 um 18 43 08](https://user-images.githubusercontent.com/395617/142468342-3bbabd68-6171-4394-89c7-685261741283.png)

**Kirby Version**  
3.6.0

**Desktop (please complete the following information):**  
 - OS: macOS 12.0.1 
 - Browser: Firefox
 - Version: 94.0.1 (64-Bit)

Note: Also affects Chromium 98.0.4694.0

**Comment by bastianallgeier** [comment]
✅
