### ISSUE TITLE
Adding an `Obj` object to a `Collection`: `add()` doesn't work while `append()` does?

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#3954]
I have (and often use) the `toolkit/collection` and `toolkit/obj` Objects for a custom data, and I expect `$collection->add($object)` to append an object to a collection, but this does not work.

```php
$collection = new Kirby\Toolkit\Collection();
$object = new Kirby\Toolkit\Obj();

$collection->add($object);
dump($collection->count());
$collection->append($object);
dump($collection->count());
```

## Expected behavior

Output `1 2`, and a collection with two items.

## Actual behavior

Output `0 1`, and a collection a single item.

## Kirby Version

3.6.0, tested with plainkit

**Comment by texnixe** [comment]
The `Kirby\Toolkit\Collection` class doesn't have an `add()` method, therefore it doesn't do anything. The `Kirby\Cms\Collection` class has.

**Comment by adamkiss** [comment]
@texnixe 🤦‍♂️ That explains so much.

So the `Kirby\Cms\Collection` is the one to use? What is the purpose of Toolkit and Cms having feature divergent components here?

**Comment by texnixe** [comment]
What's wrong with using `append()` for your use case?

> What is the purpose of Toolkit and Cms having feature divergent components here?

The `Kirby\Cms\Collection` extends the toolkit collection and is specialized as foundation for pages, users, files etc.
