### ISSUE TITLE
Non-standard MIME type "application/force-download" breaks Response::download()

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#3956]
**Describe the bug**  
`Response::download()` triggers a response that includes the HTTP header `Content-Type: application/force-download`. While this works fine in most browsers, it may cause issues (e.g. occured on at least two iOS devices) as that is not a valid MIME type.

https://github.com/getkirby/kirby/blob/630597e72599bfaa0cb9742d0ff4965376d17fd9/src/Http/Response.php#L170

**To Reproduce**  
1. Create a route that returns `return Response::download($file->root(), $file->filename());`
2. Enter the URL to that route on an iOS device
3. See error as in screenshot below: file is not offered for download but binary content displayed instead

**Expected behavior**  
The HTTP response from `Response::download()` should lead to a file download on all devices. Its `Response-Type` header should contain the correct file MIME type (e.g. `Content-Type: application/pdf; charset=UTF-8` for a PDF file).

**Screenshots**  
![IMG_2763](https://user-images.githubusercontent.com/6355217/142845975-767cbc7a-c18a-48f9-9126-41aa48152e49.PNG)

**Kirby Version**  
at least 3.4.x–3.6.0

**Smartphone:**  
Reported by third party via client, so I only know it was reproducible on iOS on both an iPad and an iPhone (can try to get more info if required)

**Additional context**  
While tracking down my client's issue, I did a bit of research:
- `Content-Type: application/force-download` apparently was a hack at some point, never a standardized MIME content type
- The `Content-Disposition` header alone should be enough to trigger download instead of browser display of the file: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition (this is already sent out by Kirby)
- [The “right way” to handle file downloads in PHP](https://www.media-division.com/the-right-way-to-handle-file-downloads-in-php/) appears to have a very comprehensive documentation of best practices
- For reference, an 8-years-old Drupal ticket on related issues: https://www.drupal.org/project/file_entity/issues/2101017

PR follows below…

**Comment by bastianallgeier** [comment]
✅
