### ISSUE TITLE
Error when converting blocks after renaming custom block type

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#3962]
**Describe the bug**  
After renaming a custom block type, it's not possible to convert existing instances of the block still referencing the original name to the new one using the context menu (the three dots). Selecting the new block type as replacement throws an error: 

> TypeError: t is undefined

**To Reproduce**  
1. Create a custom block type.
2. Add this block to a page.
3. Rename custom block type.
4. Try to convert the existing instance to the new one.

**Expected behavior**  
There should be no error and the block should be converted to the new name.

**Kirby Version**  
Kirby 3.6

**Comment by bastianallgeier** [comment]
✅
