### ISSUE TITLE
Getting logged out of 3.6.0 at random

### ISSUE THREAD

**Issue by foobartel** [k-next/kirby#3971]
**Describe the bug**  
Since the final release of 3.6.0 I keep getting logged out randomly. It happens quickly after logging in and is not tied to any other action or task. It did not happen with any of the 3.6 rc installations. With 3.6.0 I have seen the JSON error modal mentioned in #3508 a few times again with this version, which did not happen in prior versions. 

After getting logged out, it shows a dialog with "Cannot set properties of undefined (setting 'changes')".

**To Reproduce**  
1. Log in
2. Do something or simply wait
3. Get logged out

**Expected behavior**  
To not get logged out randomly.

**Kirby Version**  
3.6

**Console output**  

```
Fetch finished loading: POST "<URL>".
index.js:1 GET https://foobartel.com/api/auth 403
request @ index.js:1
get @ index.js:1
user @ index.js:1
setInterval (async)
onSuccess @ index.js:1
request @ index.js:1
await in request (async)
get @ index.js:1
load @ index.js:1
reload @ index.js:1
(anonymous) @ vendor.js:12
emit @ vendor.js:12
onSave @ index.js:1
await in onSave (async)
(anonymous) @ vendor.js:12
emit @ vendor.js:12
keydown @ index.js:1
index.js:1 Fetch failed loading: GET "https://foobartel.com/api/auth".
index.js:1 GET https://foobartel.com/api/auth 403
index.js:1 Fetch failed loading: GET "https://foobartel.com/api/auth".
index.js:1 GET https://foobartel.com/api/auth 403
index.js:1 Fetch failed loading: GET "https://foobartel.com/api/auth".

```

**Desktop (please complete the following information):**  
 - OS: macOS 12.0.1
 - Browser: any
 - Version: any

**Comment by foobartel** [comment]
FYI, it seems this still had to do with my service worker intercepting the fetch request. I have now removed the service worker and it seems to work as expected now, hence closing this issue. It's a little strange that this issue did not appear throughout all of the 3.6 rcs.

**Comment by bastianallgeier** [comment]
I would love to be more helpful, but I have zero knowledge of serviceworkers and why this is breaking at all. I'm just glad it works again.
