### ISSUE TITLE
[3.6.0] Copy & Paste in list blocks doesn't work on the first try

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#3974]
**Describe the bug**  

https://github.com/getkirby/kirby/issues/3728 issue appeared again.

**Kirby Version**  

3.6.0

**Comment by afbora** [comment]
@bastianallgeier I've tracked down the issue and this is related with https://github.com/getkirby/kirby/pull/3899 PR
When I revert the changes works great. But I have no idea about solution for now.

**Comment by bastianallgeier** [comment]
That's so weird. Why would it happen this way? I think we need to investigate some more. ProseMirror is often really killing me.

**Comment by bastianallgeier** [comment]
✅
