### ISSUE TITLE
PHP8 deprecation Exception for http_build_query

### ISSUE THREAD

**Issue by SQRR** [k-next/kirby#3975]
Exception Message in PHP8:
http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated

File: /kirby/src/Http/Query.php
Line: 46

currently: 
`$query = http_build_query($this, null, '&', PHP_QUERY_RFC3986);`

fix:
`$query = http_build_query($this, '', '&', PHP_QUERY_RFC3986);`

**Comment by bastianallgeier** [comment]
✅
