### ISSUE TITLE
Plainkit-main

### ISSUE THREAD

**Issue by alicericci** [k-next/kirby#3978]
**Describe the bug**  

The current version of plainkit-main available on the kirby website doesn't work, it displays the error page. I tried setting the debug is to true but it didn't change anything. Starterkit-main works as expected

**Screenshots**  

<img width="1552" alt="Screenshot 2021-11-29 at 13 29 53" src="https://user-images.githubusercontent.com/43652271/143868970-a81c12a3-dff5-47d7-a733-4311964cd90d.png">

**Kirby Version**  

Version 3.6.0

**Desktop:**  
macOS Monterey 12.0.1

**Comment by bastianallgeier** [comment]
I cannot reproduce this. How do you run Kirby? Which local dev environment are you using?

**Comment by alicericci** [comment]
I'm using Mamp, version 6.3 with php 7.4.12

**Comment by bastianallgeier** [comment]
Oh, that's in a subfolder, right?

**Comment by bastianallgeier** [comment]
I still cannot reproduce it though. I'm also using MAMP. Is there anything else you can tell about the setup?

**Comment by alicericci** [comment]
I just noticed that starterkit-main was also not working, I edit the issue to add a screenshot as well. 
About my setup, there isn't much to it, I have my Mamp root in a custom folder and older kirby projects are still working fine (the one I tested is kirby version 3.5.7.1). I switched mamp to php version 8 but it didn't change anything.

**Comment by alicericci** [comment]
I changed my subfolder so that it doesn't have any space and it's now working.
Is there anything i can change in the config to be able to keep spaces in the name of the folder ?

**Comment by bastianallgeier** [comment]
Where is the space in your setup? I would always recommend not to use spaces in folders for web projects.

**Comment by alicericci** [comment]
The space is not in the name of the kirby folder it self, but in its parent folder so it's something like: 

> mamproot/folder with spaces in the name/plainkit-main

I think for local development spaces in folder name are nice because it allows freedom in the way one chooses to organize their computer

**Comment by bastianallgeier** [comment]
I'm really sorry, but we cannot fix this on our end. You should use folder names without spaces instead.

**Comment by alicericci** [comment]
No worries, thanks for helping me figuring out what I did wrong !
