### ISSUE TITLE
Panel: pages field with „link: true“ clickable only after reload

### ISSUE THREAD

**Issue by hannesherold** [k-next/kirby#3983]
**Describe the bug**  
If the option `link: true` is set for a Pages Field in the blueprint, the referenced page is only clickable after reloading the page in the panel. Immediately after setting the reference or saving the page, the field behaves like `link: false`.

**To Reproduce**  
1. Install current plainkit and panel
2. Create pages field with `link: true` in blueprint
3. In the panel, add a page to the pages field and save
4. Try to klick the referenced page in the pages field

**Expected behavior**  
The referenced page should be clickable right after it has been selected.

**Screenshot-Video**  
https://user-images.githubusercontent.com/46819942/144401413-f7cec2fd-fcc4-4eaa-8d4a-09a9a6439b18.mov

**Kirby Version**  
3.6

**Console output**  
No console messages.

**Desktop (please complete the following information):**  
 - OS: macOS 12.0.1 
 - Browser: Opera, Firefox, Safari

**Comment by afbora** [comment]
@distantnative Also doesn't work for `link: false`. I think this prop got corrupted when moving to items/item component.

**Comment by distantnative** [comment]
Are we sure this is a regression. At first look, I don't think it's related to `items/item` refactoring, but rather that the picker does not pass the link data for freshly selected pages to the field itself. I would assume that bug existed before too.

UPDATE: Ok I checked, it is a regression - not present in 3.5.8.

**Comment by bastianallgeier** [comment]
✅
