### ISSUE TITLE
k-form-dialog: Default Values of Fields not taken into Account

### ISSUE THREAD

**Issue by steirico** [k-next/kirby#3994]
**Describe the bug**  

Fields of a custom dialog built with `k-form-dialog` do not show the configured default value.

I became aware of the problem by [this issue](https://github.com/steirico/kirby-plugin-custom-add-fields/issues/55) of the `Add Fields Plugin`. My investigations showed that the problem is not related to the plugin.

**To Reproduce**

1. Get a fresh kirby starterkit 3.6.0
2. Add an additional field with a default value to the `Change Title Dialog` by adding the following code at `kirby/config/areas/site/dialogs.php` line 191:
  ```php
'defaultTest' => [
    'label' => 'Default Test',
    'type' => 'text',
    'required'  => false,
    'default' => 'Hello World',
    'disabled'  => false
],
  ```
3. Login to the panel and navigate to a page, e.g. `Exploring the universe`
4. Click `Settings` -> `Rename` in order to open the `Change Title Dialog`

**Expected behavior**  

I would expect to see the `Change Title Dialog` with the additional field labeled `Default Test` and the default text `Hello World`.

Instead, the additional field appears but the default text is missing:

![image](https://user-images.githubusercontent.com/10421363/144709632-185160d8-9f7d-41cb-8436-74b280997794.png)

The default value is transmitted with the API response:

![image](https://user-images.githubusercontent.com/10421363/144709761-12a0a325-7091-41b5-a4ef-01c813ad660c.png)

**Kirby Version**  
3.6.0

**Comment by crisgfx** [comment]
I stumbled upon this while following along the advanced panel area tutorial and would love to see a fix on this as well.
Thank You!

**Kirby Version**
3.6.3-rc.1

**Comment by bastianallgeier** [comment]
Passing default values to the form dialogs works with the value prop: 

Here's the full example for the changeTitle dialog: 

```php
return [
    'component' => 'k-form-dialog',
    'props' => [
        'fields' => [
            'title' => Field::title([
                'required'  => true,
                'preselect' => $select === 'title',
                'disabled'  => $permissions->can('changeTitle') === false
            ]),
            'slug' => Field::slug([
                'required'  => true,
                'preselect' => $select === 'slug',
                'path'      => $page->parent() ? '/' . $page->parent()->id() . '/' : '/',
                'disabled'  => $permissions->can('changeSlug') === false,
                'wizard'    => [
                    'text'  => t('page.changeSlug.fromTitle'),
                    'field' => 'title'
                ]
            ]),
            'defaultTest' => [
                'label'    => 'Default Test',
                'type'     => 'text',
                'required' => false,
                'disabled' => false
            ],
        ],
        'autofocus' => false,
        'submitButton' => t('change'),
        'value' => [
            'title' => $page->title()->value(),
            'slug'  => $page->slug(),
            'defaultTest' => 'Hello World'
        ]
    ]
];
```
