### ISSUE TITLE
Class not found when extending a page model

### ISSUE THREAD

**Issue by yandodov** [k-next/kirby#4013]
## Description
I have a page model `site/models/article.php`:

```php
use Kirby\Cms\Page;

class ArticlePage extends Page { ... }
```

Then, I have another model `site/models/article-custom.php` that extends the first one:

```php
class ArticleCustomPage extends ArticlePage { ... }
```

If I try to open anything in Kirby, I get the following error:

> Class 'ArticlePage' not found

My guess is that this happens due to the file order. In VS Code, the files are ordered like this:

```
site/models/article-custom.php
site/models/article.php
```

It appears that Kirby tries to load `article-custom.php` before `article.php`, causing the error. If I rename my model (and template) to `article2.php`, it goes below `article.php` and the error goes away.

Another solution I've found is to simply add this in the `article-custom.php` model:

```php
require_once 'article.php';
```

## Your setup
**Kirby Version**  
3.5.7.1

**Comment by neildaniels** [comment]
I've run into the same issue before, and have resorted the the `require_once` as well.

Another potential solution: move your models (at a minimum, the base `ArticlePage` one) to a plugin and use the `load()` helper function.

**…/site/plugins/article/index.php**
```php
<?php

load([
    'ArticlePage' => 'models/article.php',
], __DIR__);

Kirby::plugin('example/article', [
    'pageModels'    => [
        'article' => 'ArticlePage',
    ],
    'controllers'   => [
        'article' => require __DIR__ . '/controllers/article.php',
    ],
    'templates'     => [
        'article' => __DIR__ . '/templates/article.php',
    ],
    'blueprints'    => [
        'article'   => __DIR__ . '/blueprints/article.yml',
    ],
]);
```

When your `ArticleCustomPage` class extends, `ArticlePage` it should automatically load the base class if necessary.

**Comment by distantnative** [comment]
I am not sure if we could solve this tbh.

**Comment by lukasbestle** [comment]
I agree with Nico. Kirby can't automatically autoload the referenced class without parsing the PHP code and also without knowing where this class is defined (doesn't have to be in `site/models`, it could also be a plugin).

The two solutions (`require_once()` and autoloading in a plugin) solve this well.
