### ISSUE TITLE
"this.load is not a function" in custom section

### ISSUE THREAD

**Issue by yandodov** [k-next/kirby#4016]
I have a custom section in my [kirby-git plugin](https://github.com/OblikStudio/kirby-git). Since the latest version of Kirby, I get the following error:

> this.load is not a function

I tested on the [latest version of the plainkit](https://github.com/getkirby/plainkit/commit/f67366b309d6fdbd8f58bfcd259449a11d68610d) using the exact same code from [the extensions documentation about sections](https://getkirby.com/docs/reference/plugins/extensions/sections):

```php
Kirby::plugin('yourname/modified', [
  'sections' => [
    'modified' => [
      'props' => [
        'headline' => function (string $headline) {
          return $headline;
        },
      ],
      'computed' => [
        'text' => function () {
          return 'The page has been modified at ' . $this->model()->modified('d.m.Y H:i:s');
        }
      ]
    ]
  ]
]);

```

```js
panel.plugin("yourname/modified", {
  sections: {
    modified: {
      data: function () {
        return {
          headline: null,
          text: null,
        };
      },
      created: function () {
        this.load().then((response) => {
          this.headline = response.headline;
          this.text = response.text;
        });
      },
      template: `
        <section class="k-modified-section">
          <k-headline>{{ headline }}</k-headline>
          <k-text>{{ text }}</k-text>
        </section>
      `,
    },
  },
});
```

I get the same error:

![localhost_plainkit_panel_site](https://user-images.githubusercontent.com/5570098/145208760-f59c1920-d9c1-4b97-b679-cad30e5b946a.png)

## Your setup
**Kirby Version**  
3.6.1

**Comment by distantnative** [comment]
Trying to fix it over here https://github.com/getkirby/kirby/pull/4009

If you would like to test if that solves it.

**Comment by yandodov** [comment]
How should I test it? Do I just have to build the panel JS at the commit you've made and drop it in my plugin setup?

**Comment by distantnative** [comment]
Have a look at the comments, I posted the new `panel/dist` folder in there. You should replace that and clear the `media/panel` folder iy you would like to test it.

**Comment by bastianallgeier** [comment]
✅
