### ISSUE TITLE
Error in panel: this.$refs.options.toggle is not a function

### ISSUE THREAD

**Issue by jasminsallam** [k-next/kirby#4031]
## Description
no dropdown appears when clicking on any files field to upload or select a file. Error `this.$refs.options.toggle is not a function`

**Expected behavior**  
dropdown to select file

**Screenshots**  
![Bildschirmfoto 2021-12-10 um 12 46 34](https://user-images.githubusercontent.com/56875105/145569751-ea37a612-4b4c-478c-813f-b3cd630abe18.png)

## Your setup
**Kirby Version**  
3.6.1.1

**Console output**  
console warnings:

`Plugin is replacing "k-options-dropdown"`

```
TypeError: this.$refs.options.toggle is not a function
    prompt https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/index.js:1
    Vt https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
    n https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
    _wrapper https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
    to https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
    ae https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
    no https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
    g https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
    f https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
    Ho https://thaler.test/media/panel/b3a806218f035122e3a0d6319430a39f/js/vendor.js:6
```

**Your system (please complete the following information)**
 - Device: macmini
 - OS: macOS
 - Browser: Chrome 96.0.4664.93, Firefox 91.0.2

**Comment by jasminsallam** [comment]
plugin https://github.com/distantnative/retour-for-kirby is causing this issue. cannot be used properly with Kirby 3.6.

**Comment by afbora** [comment]
Yes, this is known issue:
https://github.com/distantnative/retour-for-kirby/issues/252
