### ISSUE TITLE
PHP 8.1: "is_file(): Passing null to parameter #1 ($filename) of type string is deprecated"

### ISSUE THREAD

**Issue by HYR** [k-next/kirby#4032]
## Description

<img width="433" alt="CleanShot 2021-12-10 at 09 46 33@2x" src="https://user-images.githubusercontent.com/5200901/145613450-0646a2ad-73f6-4395-be51-a8b95ce4626c.png">

I have 3 snippet calls for prepending or appending code as needed. **None of these snippets exist** until I need them. Until now this method has worked well. When upgrading to PHP 8.1 I get the following error:

<img width="593" alt="CleanShot 2021-12-10 at 10 10 17@2x" src="https://user-images.githubusercontent.com/5200901/145613940-08575f19-693e-4ed5-b376-c09ee0bc75b8.png">

With PHP 8.1 the [deprecation](https://php.watch/versions/8.1/internal-func-non-nullable-null-deprecation) shown in the screenshot above is not handled by Kirby as of version 3.6.1.1.

**Expected behavior**  
I expect Kirby to ignore snippets that don't exist, without producing an error.

## To reproduce

1. Be sure to have PHP 8.1 installed
2. In PHP call a snippet that doesn't exist.
3. You should see the Error

## Your setup
**Kirby Version**  
Kirby 3.6.1.1

**Comment by afbora** [comment]
✅
