### ISSUE TITLE
`$file->niceSize()` doesn't allow for local formatting

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#4037]
## Description
While `F::niceSize()` accepts a locale for regional number formatting, `$file->niceSize()` does not. Numbers are also output following English notation rules using a dot as decimal separator.

**Expected behavior**  
The file method should accept a locale as parameter and – ideally – default to the current locale set in the config (on single language installs) or defined by the current language (on multilingual sites).

**Comment by lukasbestle** [comment]
✅
