### ISSUE TITLE
License does not get recognized for subfolder installations

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/kirby#4038]
## Description

The license is not registered correctly when the URL contains a subfolder. 

This happens when the license is registered and downloaded from our license server.

**Comment by lukasbestle** [comment]
That's intended behavior. The registered license URL needs to contain the subfolder.

**Comment by bastianallgeier** [comment]
This is what I mean. When you want to run Kirby under https://example.com/subfolder and you enter the URL into our manual license download form including the subfolder, the license file will not work correctly afterwards.

**Comment by lukasbestle** [comment]
The license URL for this example should be `example.com/subfolder` without the protocol. I haven't been able to try it, but that's what the code expects if I read it correctly.

**Comment by bastianallgeier** [comment]
This was an issue on our license server. It's now fixed.
