### ISSUE TITLE
Pages field preview: ampersand shows as `&amp;`

### ISSUE THREAD

**Issue by fabianmichael** [k-next/kirby#4041]
## Description
It seems, like HTML special characters are escaped twice in the field previews used by structure fields.

**Expected behavior**  
The page title should appear as entered by the user

**Screenshots**  
![Bildschirmfoto 2021-12-13 um 18 53 54](https://user-images.githubusercontent.com/395617/145863646-379ff222-dd0a-4537-8bbf-918c456c4368.png)

## To reproduce
Select any page with an ampersand in its title in a structure field that has a `pages` field.

## Your setup
Kirby Version: 3.6.1.1

**Your system**
 - Device: MacBook Pro 14"
 - OS: macOS 12.0.1
 - Browser: Firefox
 - Version: 95.0

**Comment by distantnative** [comment]
# Summary
The issue arises as the data shown here originates in `Panel\Model::pickerData()` where text gets escapes via `->toSafeString()`. While the preview bubble itself would be safe without escaping (as escaping is already handled by Vue, the data from `::pickerData()` also gets shown in other places in `k-item`, which does output them via `v-html`. So we cannot simply get rid of the escaping.

## Solution
I think we can only safely tackle this once we separate the picker fields' value from the data to show `k-items` in the dialog.

**Comment by seeligmx** [comment]
Same issue here on structure field :-(
<img width="357" alt="issue" src="https://github.com/getkirby/kirby/assets/432286/275eb031-9c9b-474b-be2a-850c1bfbd255">
