### ISSUE TITLE
Missing filesize value in alert on fileupload when panel language is set to german

### ISSUE THREAD

**Issue by MatthiasWeisz** [k-next/kirby#4042]
## Description
The desired filesize for upload is missing in alert in german language.
Instead there is '-' shown

**Expected behavior**  
Value of minwidth / maxwidth set in blueprint 

**Screenshots**  
![Bildschirmfoto 2021-12-14 um 07 23 17](https://user-images.githubusercontent.com/66673653/145945459-40fd212c-84c1-41ed-918a-9c1897f45f69.png)

## To reproduce
Checkout Kirby 3.6.1.1, set panel language to german, set minwidth for files in blueprint, try upload smaller file

**Comment by afbora** [comment]
We will fix the issue on transifex and `{height]` placeholder in `error.file.minwidth` translation key should be `{width}` for DE and IT languages.

**Comment by bastianallgeier** [comment]
I fixed both in Transifex
