### ISSUE TITLE
User creation fails when Spanish is the only language

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#4048]
## Description
In a multilanguage setup, when Spanish is the only language, a new user cannot be created, the error is "Please enter a valid language".

In my test this did not happen when choosing other languages like English, French or German as the only language, or when adding additional languages to Spanish as default.

**Expected behavior**  
A user should be created.

**Screenshots**  

## To reproduce

1. In a fresh Starterkit, enable languages in config.
2. In the Panel, add Spanish as new (and only) language.
3. Try to create a new user.

## Your setup
**Kirby Version**  
3.6.1.1.

**Console output**  
{"$dialog":{"code":400,"error":"Please enter a valid language","path":"dialogs\/users\/create","referrer":"\/users"}}

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 11.2.2
 - Browser: Firefox

**Additional context**  
https://forum.getkirby.com/t/error-creating-users-on-3-6/24129

**Comment by bastianallgeier** [comment]
✅
