### ISSUE TITLE
Files field - after file is changed, not possible to open its panel page

### ISSUE THREAD

**Issue by janherman** [k-next/kirby#4052]
## Description
I have a files field that is limited to one file only (max: 1 or multiple: false). After I change the file in files field (through the change button), I am not able to click the file to open its panel page. I have to refresh the page, then everything works as expected.

## To reproduce
1. upload a few files to the page
2. select file in files field and save
3. in the files field click the "change" button and select different file
4. try to click the newly selected file in files field to open its panel page - it is not possible

**Kirby Version**  
I tested on 3.6.1.1 and on 3.5.7.1. The problem seems to appear only on 3.6.1.1

**System*
 - OS: Windows 10
 - Browser: Firefox Developer Edition
 - Version: 3.6.1.1

**Comment by afbora** [comment]
Thanks for report. This is known issue as #3983
