### ISSUE TITLE
User blueprint: `home` option redirect fails for users w/out panel access

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4056]
## Description
Setting a frontend URL in the `home` option of a user blueprint (e.g. `home: "{{ site.find('notes').children.first.url }}"`) leads to a pop-up with an error "You are not allowed to access the panel" if `panel: false` is set for that user.

**Expected behavior**  
Forwarding a user without panel access to a frontend URL should not lead to an error. This is a precondition to making use of the Kirby core's login flows for frontend-only users.

As discussed in [this Discord thread](https://discord.com/channels/525634039965679616/921888554521616444).

## To reproduce
1. Install a fresh Starterkit and create an admin user
2. Add `panel: false` and `home: "{{ site.find('notes').children.first.url }}"` to the `user/default.yml` blueprint
3. Try to log in

## Your setup
**Kirby Version**  
3.6.1

**Your system (please complete the following information)**
 - Device: PC
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 95

**Additional context**  
Possibly related to #4054 (probably need to be fixed first, before this will work)

**Comment by bastianallgeier** [comment]
✅
