### ISSUE TITLE
Nested (Builder) Blocks not working in Migration from old Kirby Builder plugin to new Blocks

### ISSUE THREAD

**Issue by MichaelPrecel** [k-next/kirby#4061]
Hi there. Longtime Kirby user!

## Description
I have an older project that I'm trying to migrate across to the new Kirby 3.6 (mainly to make use of the new webp/avif image processing abilities). 

In this project I have created a pretty complicated page-builder using the old TimOetting/Builder plugin. This includes nested builders. Eg a 'slider' block will have nested 'slide' sub-blocks (image slide/video slide/etc). When I adjust the fields from 'builder' to 'blocks' and update the data, these nested blocks are not being rendered.

Looking at the template.txt file reveals that the top-level blocks are being correctly converted to JSON, but the nested blocks are not. They are converted to JSON, although all special characters are escaped.

<img width="645" alt="Screen Shot 2021-12-20 at 4 10 48 pm" src="https://user-images.githubusercontent.com/27719652/146714904-bba27a2a-3d30-4286-8a93-e3566044d457.png">

I think as a result of this, the top-level blocks are silently failing when I try to render them on the page.

Any help would be much appreciated!

**Comment by afbora** [comment]
@bastianallgeier I think this issue should be closed since we've removed the migrations from 3.7 release.
