### ISSUE TITLE
`link: false` doesn't working on picker fields

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4062]
## Description

`link: false` doesn't working on picker fields. I've tested on 3.5.7.1 and this feature is working as well.

````yaml
cover:
  type: files
  link: false
````

https://getkirby.com/docs/reference/panel/fields/files#field-properties

**Expected behavior**  

When link disabled, items shouldn't be clickable.

## To reproduce

1. Go to panel
2. Edit any page that have picker fields
3. Disable clickable with `link: false`
4. Select any item from picker field
5. Still clickable

## Your setup
**Kirby Version**  

3.6.1.1 & Develop branch

**Console output**  

None

**Your system**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome 96.0.4664.110

**Additional context**

**Comment by distantnative** [comment]
@afbora Could you give https://github.com/getkirby/kirby/tree/fix/4062-picker-field-disable-links a try if it solves it for you (and doesn't break links when enabled)?

**Comment by afbora** [comment]
Works great for all picker fields 👍

**Comment by afbora** [comment]
✅
