### ISSUE TITLE
Selected site tab resets after language change

### ISSUE THREAD

**Issue by ennemoserandre** [k-next/kirby#4071]
## Description
After changing the language with a selected site tab, you will be redirected to the first tab. Sometimes the translated content was not saved in the backend (there is always the value from the default language) even though it was changed correctly in the content text file.

## To reproduce

1. Install a fresh Starterkit and create tabs in the site.yml file
2. Add multilanguage support to the kirby installation
3. Add a field to the tabs
4. Click on a tab and switch language
5. You will be redirected to the first tab

-- For the problem that some values are not shown in the right language in the backend i could provide you my kirby project.

## Your setup
3.6.1.1
 - Device: PC
 - OS: Windows
 - Browser: Google Chrome
 - Version: 96.0.4664.110

**Comment by afbora** [comment]
This is regression due to works as expected in 3.5.7.1

**Comment by bastianallgeier** [comment]
✅
