### ISSUE TITLE
Rightmost area of dropdown item triggers hidden button below

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4072]
## Description
With a regular dropdown open (tested on a Starterkit pages section), the rightmost part of each dropdown element/row does not trigger the desired action but instead the "Open dropdown" button of the list element below.

![clickable-area-bug](https://user-images.githubusercontent.com/6355217/147331381-1cef6bd3-8877-43dc-a321-4a6204540104.png)

This appears to be a z-index issue, where the event listener of the underlying `<span class="k-dropdown k-options-dropdown k-item-options-dropdown">` or the `<button>` element within it is triggered instead of the `<a class="k-link k-button k-dropdown-item">` element of the dropdown entry.

**Expected behavior**  
It should be possible to click on a dropdown element at full width and not trigger a button hidden behind.

## To reproduce
1. Go to the panel on a 3.6.1.1 Starterkit
2. Click on the meatballs icon
3. Try to select "Open" by clicking in the area highlighted in the screenshot above

## Your setup
3.6.1.1 Starterkit

**Your system (please complete the following information)**
 - Device: PC
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 95.0.1

**Comment by mattwolff** [comment]
Yes, can confirm this issue. Seems to extend to any dropdown that lands on top of an options button. The image below shows the meatballs for a file (in red) landing above the dropdown for  page settings.

<img width="439" alt="Screen Shot 2021-12-24 at 2 17 13 PM" src="https://user-images.githubusercontent.com/21694984/147370714-aad2269d-eb7e-4c2a-8b2c-be3d2042002c.png">

I suppose this has to do with how dropdowns are added to the DOM... Looks to me like dropdowns are appended as children within the `span.k-dropdrown` element. Those spans all share the same z-index — they use the root variable `--z-navigation`. If they all share the same z-index, actual DOM order supersedes. Hence, the next meatball span with the same z-index as its sibling appears above...

So, I'm thinking a possible fix would be to toggle a class _on the span_ when a dropdown is opened, and giving that class a style like `z-index: var(--z-dialog);` ... but maybe there's a better easier way.

---
- Device: Mac
- OS: Catalina
- Browser: Checked both Firefox 95.0 and Safari 13.1.1

**Comment by bastianallgeier** [comment]
✅
