### ISSUE TITLE
Dropdowns route on files causes server error since 3.6.0 due to change in method (GET to POST) on .jpg etc. 

### ISSUE THREAD

**Issue by belugaed** [k-next/kirby#4083]
The /panel/dropdown calls appear to do a POST to retrieve the API data to populate the dropdown. It posts to it’s own page, which is fine for the most part e.g. posting to https://my.domain/panel/site.

However, since the file/image page has a url such as https://my.domain/panel/pages/about/files/my-image.jpg, it’s posting to this URL structure:

http://my.domain/panel/dropdowns/pages/about/files/my-image.jpg

Since it’s an extension some shared hosting would not naturally allow - Posting to a jpg/png etc. presumed to be exclusively GETs by most host specs.

As a result we get a 403 / Forbidden.

![image](https://user-images.githubusercontent.com/86915641/148559250-9fb0165a-eefb-4caf-82b4-f003ec7e548b.png)
 
The call seems to work as a GET so not sure why it needs to POST for this panel function to dropdowns.

This appears to be an issue since 3.60 and it’s pre-releases. Pre this version the url structure was a GET to

https://my.domain/api/pages/about/files/my-image.jpg?select=options

**Comment by bastianallgeier** [comment]
✅

**Comment by belugaed** [comment]
I've checked this out on the 3.6.2 pre-release (thanks!).

It works to a point, but 404s if there is an @ in the filename (typical if somebody exports 2x, 3x etc. from photoshop).

Shows fine in the file picker, but then when you click through (e.g. /panel/pages/about/files/my-file-2@2x.jpg) it shows the "URL not found on server".

URL encoding the @ to %40 doesn't seem to help either.

![image](https://user-images.githubusercontent.com/86915641/151587073-2d048256-62da-44d8-8738-d50c2e15b08a.png)

![image](https://user-images.githubusercontent.com/86915641/151587132-55e6f10f-0ad1-41af-afa6-2013ac730df9.png)

@bastianallgeier

**Comment by bastianallgeier** [comment]
@belugaed I tried but was not able to replicate this. It all works fine over here. What kind of server are you using?

**Comment by belugaed** [comment]
Hi @bastianallgeier 

It's a cloud based provider (CloudNext / https://www.20i.com/), but ultimately it's a Linux installation with Apache, PHP 7.4.

Happy to share the git basecode with you personally or give FTP access it helps debug it.

**Comment by distantnative** [comment]
@belugaed does this continue with https://github.com/getkirby/kirby/releases/tag/3.6.3-rc.1 for you? If so, yes please share your setup/code, might help to replicate the problem for us.

**Comment by bastianallgeier** [comment]
We fixed this.
