### ISSUE TITLE
$page->prevUnlisted() shows first instead of previous collection item

### ISSUE THREAD

**Issue by andreasfehn** [k-next/kirby#4086]
## Description
$page->prevUnlisted() shows always the first (instead of previous) collection item.
Probably a copy&paste bug within /kirby/src/Cms/PageSiblings.php at the end of line 113 (shoud be "->last()" instead of "->first()")

**Expected behavior**  
$page->prevUnlisted() shall return the previous collection item.

**Screenshots**  
<img width="544" alt="Bildschirmfoto 2022-01-12 um 12 16 21" src="https://user-images.githubusercontent.com/551764/149131007-c0bcb8cf-7710-4e5b-9986-34fedfdaad3a.png">

**Comment by bastianallgeier** [comment]
✅
