### ISSUE TITLE
Passing string to `panel.favicon` config option throws error

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#4092]
## Description
[According to the docs](https://getkirby.com/docs/reference/system/options/panel#custom-panel-favicon), it should be possible to pass a path to the `panel.favicon` config option.

```php
return [
  'panel' => [
    'favicon' => 'assets/favicon.ico'
  ]
];
```

However, this throws an error on line 34 in `/kirby/views/panel.php` where an array is expected (foreach() argument must be of type array|object, string given). The tests also only test with an array.

**Expected behavior**  
The option should work as advertised in the docs.

## Your setup
**Kirby Version**  
3.6.6.1

**Comment by bastianallgeier** [comment]
✅
