### ISSUE TITLE
Table block preview uses too much padding

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#4096]
## Description

The rows and / or cells of the table block preview use too much padding. The less horizontal space the block has to use, the more obvious it gets.

**Expected behavior**  

The rows and / or cells to use less padding.

**Screenshots**  

<img width="874" src="https://user-images.githubusercontent.com/9334305/149805356-f0aa7f89-1570-4d0d-b7fb-989a9b86f6ba.png">

<img width="340" src="https://user-images.githubusercontent.com/9334305/150527516-317c8d0b-482b-4507-ab5a-852739bc9918.png">

## To reproduce

1. Create a table block blueprint (e. g. the [one from the docs](https://getkirby.com/docs/reference/panel/blocks/table)).
2. Use it in a `blocks` or `layout` field.
3. Add at least one row.

## Your setup
**Kirby Version**  

3.6.1.1

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 12.1
 - Browser: Google Chrome
 - Version: 97.0.4692.71

**Comment by silllli** [comment]
This bug was introduced in version 3.5.7.

**Comment by bastianallgeier** [comment]
✅
