### ISSUE TITLE
Panel shows old content after re-opening tab

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4101]
## Description
This is a bit of an odd one, but I'll try to explain as good as I can. I first noticed this with the MarkdownField plugin, but ran some tests and it can be replicated with the Textarea field as well.

When editing text in a textarea/markdown field and saving, then closing the browser tab (Ctrl+W) and reopening it with Ctrl+Shift+T, the textarea/markdown field shows an outdated version of the content (the version that was initially loaded when first visiting that Panel page).

I have also been able to replicate this by visiting another site like `http://example.com` in the same tab and then going back with the browser's "back" button, but that has not been quite so consistent to replicate (not sure what affects it).

**Expected behavior**  
When closing and reopening a tab with the panel (or coming back to a Panel URL using the browser's "back" button after opening another URL in the same tab), I'd expect to see the content as I last saved it.

## To reproduce
1. Create a page blueprint that contains a textarea field and set up a pages section for that page type
2. Use "Add" in the panel to create a new page of that blueprint
3. Write `My first line.` into the textarea
4. Save with Ctrl+S
5. Close the browser tab with Ctrl+W
6. Reopen the tab with Ctrl+Shift+T
7. Now write `My second line.` into the textarea, right below the first
8. Save with Ctrl+S
9. Close the browser tab with Ctrl+W
10. Reopen the tab with Ctrl+Shift+T
11. See error: the second line is not shown, even though the page had been saved before closing the tab; there is no indication in the UI that this is an outdated version
12. Reloading the Panel page with F5 reveals the content as saved, i.e. with both lines of text

## Your setup
3.6.2-rc.1 (issue exists with 3.6.1 as well, but I am unable to say whether this is a new thing since 3.6.x or if I simply never noticed before)

**Console output**  
Nope.

**Your system (please complete the following information)**
 - Device: PC
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 96.0

**Comment by afbora** [comment]
I can reproduce the issue with Chrome either

**Comment by afbora** [comment]
I tracked down the issue. I couldn't figure out but I've a clue. I think this issue related with `cache-control`.

Works as expected when I set header `cache-control` from root `.htaccess`  like below and may be this give you an idea about solution.

````
<IfModule mod_headers.c>
    Header set Cache-Control "no-cache, no-store, must-revalidate"
</IfModule>
````

**Comment by afbora** [comment]
Also works when set header from [Panel::router()](https://github.com/getkirby/kirby/blob/3.6.2-rc.1/src/Panel/Panel.php#L286) method like that:

````php
public static function router(string $path = null)
{
  header("Cache-Control: no-cache, no-store, must-revalidate");
  header("Pragma: no-cache");
  header("Expires: 0");
  
  ...
}

**Comment by lukasbestle** [comment]
Is this because of Fiber (first set of data included in the Panel HTML response) or because of a separate response from the API? If possible, I'd avoid to use these headers globally.

Basically the question is: Was this issue introduced in 3.6 or later?

**Comment by afbora** [comment]
@lukasbestle I can reproduce the issue on 3.6.0.alpha.1 and 3.6.0. So introduced with 3.6.

**Comment by rasteiner** [comment]
This may come from the bfcache. Could possibly be solved by implementing a "pageshow" event handler.
Here some info: https://web.dev/bfcache/#observe-when-a-page-is-restored-from-bfcache

something like:

```js 
window.addEventListener('pageshow', (event) => {
  if (event.persisted) {
    //update content with fresh data from the server
  }
});
```

-----------------

edit: it's not bfcache.

**Comment by lukasbestle** [comment]
@afbora Have you tried setting these headers just for the initial Panel HTML response?

**Comment by afbora** [comment]
@lukasbestle Can you share the exact location for me to try? 🙈

**Comment by lukasbestle** [comment]
For testing it would probably be the quickest to put them in `views/panel.php` right at the top.

**Comment by afbora** [comment]
Yes, works `header()` as expected for top of `views/panel.php` file.

**Comment by sebastiangreger** [comment]
Thank you for looking into this! I just tested the outlined approach and this indeed seems to fix the issue. I'll try to simulate the error scenario with the fix applied over the next days as I am working on my production site and report back in case it should occur again, but this appears to be solved :slightly_smiling_face:

**Comment by bastianallgeier** [comment]
✅
