### ISSUE TITLE
`$pages->find()` doesn't work with slug for the default language in a multilang installation

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#4105]
## Description
This code used to work:

```
<?= $site->grandChildren()->find('exploring-the-universe')?>
```

And still does in a non-language installation.

However, it doesn't work in a multilanguage installation **for the default language**, while it works for the non-default languages.

**Expected behavior**  
The code should return the given page in all circumstances.

## Your setup
**Kirby Version**  
3.6.1.1

**Additional context**  
[](https://forum.getkirby.com/t/pages-find-not-working-as-expected/24531)

**Comment by afbora** [comment]
~Also doesn't work with single language. When you write page id (`notes/exploring-the-universe`), it will work.~

I can confirm that this issue related following line (PR https://github.com/getkirby/kirby/pull/2763)
https://github.com/getkirby/kirby/blob/3.6.1.1/src/Cms/Pages.php#L252

**Comment by afbora** [comment]
Maybe @neildaniels has an idea for a solution to this issue 👀

**Comment by neildaniels** [comment]
Does this actually work in a single-language installation? I haven't had a chance to test that setup type, but that would be surprising.

For context: `$pages->find()` relies on the method `$pages->findById()`.

As part of the PR https://github.com/getkirby/kirby/pull/2763#issuecomment-830705693, I called out this breaking change:
> In multi-lang setups, calling `$pages->findById()` on a non-children collection with an id that is actually slug no longer works. This makes the Pages class more consistent between single and multi language setups.

What's interesting about the `$object->grandChildren()` method is that the resulting `Pages` collection _does_ have a `$parent` but it's really the "grandparent" not a direct parent. The fact that it has _a_ `$parent` makes it be treated as if it's a children collection.

I would argue that calling `$pages->children()` on an existing collection should _not_ pass on the `$this->parent`. In other words, your code _shouldn't_ work, even on a non-default language.

https://github.com/getkirby/kirby/blob/351b6348348cf78aed9a65920358caf218473102/src/Cms/Pages.php#L93-L104

That would cause `grandchildren` to be treated as a non-children collection and make `->find()` "correctly" fail on non-default language setups.

Either way,  I would defer the suggestion I had in the PR comment:
> If similar behavior is desired, `$pages->findBy('slug', $slug)` should be used instead.

So, I would suggest rewriting the statement as:

```php
$site->grandChildren()->findBy('slug', 'exploring-the-universe')
```

**Comment by lukasbestle** [comment]
Thank you @neildaniels for your detailed comment. I agree with your thoughts. We did have that breaking change in 3.6 and for a reason. So after thinking about it again I don't consider this a regression. Unfortunately it looks like we forgot to document the breaking change in the 3.6 release notes.

## Possible solution

- [x] Add the breaking change to 3.6 release notes for future reference for those updating their existing sites to 3.6.
- [x] Document the expected usage of the `find()` and `findBy('slug', ...)` methods in collections better.
- [x] In 3.7: Stop passing the parent to grandchildren (and other non-direct-children) collections (which is another breaking change).
- [x] Ensure that the new behavior is consistent between single-lang, multi-lang default lang and multi-lang secondary lang.

*Additional TODOs moved to the PR*

**Comment by bastianallgeier** [comment]
✅
