### ISSUE TITLE
Field attributes and props parsing : php vs vuejs behave differently

### ISSUE THREAD

**Issue by Daandelange** [k-next/kirby#4110]
## Description
I'm not really sure of what's happening here, but there seems to be some unexpected behaviour between how the php parses props compared to how vue-js parses them. As an example I've taken the `translate` attribute+prop but it seems to happen to other props/attrs too.

With the steps from below, try different configurations, here's the results :

| blueprint.translate | props.translate | Saves in non-default lang | Panel field enabled in non-default lang | Expected | Note |
| ----|----|----|----|----|----|
| not set | false | Yes | Yes | Yes | |
| not set | true | Yes | Yes | No | |
| true | true | Yes | Yes | Yes | |
| false | false | No | No | Yes | |
| true | false | Yes | Yes | No (?) | the vue inspector shows `$props.translate=false` |
| false | true | No | No | Yes (?) | the vue inspector shows `$props.translate=true` |

So maybe there is an issue with php ignoring props, or prioritising attrs while on the vuejs side props take over from attrs ?
Or a'm-I missing something here ? ([properties should over-ride field options](https://getkirby.com/docs/reference/plugins/extensions/fields#php-definition__properties), right ?)

**Expected behaviour**  
Difficult to explain the expected behaviour, I feel confused about this, but I'd definitely not expect a different behaviour between php/kirby and vuejs/Fiber field objects.

## To reproduce
- Install this plugin :
````php
// site/plugins/notranslate/index.php
Kirby::plugin('kirbybugs/notranslate', [
  'fields' => [
    'notranslate' => [
      'extends' => 'number',
      'props' => [
        'label' => 'No translation',
        'translate' => false, // <-- props.translate
      ],
    ],
  ],
]);
````
````js
// site/plugins/notranslate/index.js
panel.plugin("kirbybugs/notranslate", {
  fields: {
    notranslate: {
      extends: "k-number-field",
    }
  },
});
````
- Add to any fields section in your blueprint:
````yml
fields:
  notranslation:
    type: notranslate
    #translate: false # <-- blueprint.translate
````
- Visit the corresponding panel page and test saving from a non-default language.

## Your setup
**Kirby Version**  
Kirby 3.6.0 and 3.6.1.1

**Comment by distantnative** [comment]
I don't think I fully understand what you are trying to do. The Vue component props have nothing to do with the PHP-side of things. They are expected to be set from the blueprint props which also steer the behaviour in PHP. Setting the `translate` prop to false in a Vue component by overwriting the default component won't change it's backend behaviour.

**Comment by Daandelange** [comment]
Indeed, sorry, I didn't clearly explain what I'm trying to do...

Do you mean that all the php field logic is meant to be used by vue components only ? (I'm not setting props in the vue component but in the php part of the field.)

Anyways, I'm extending a field which should never be translated. So I'm trying to ensure that the `translate` property gets forced to `false` even when the blueprint defines `translate: true` on the field. This works as expected in the vue components part, but for properties (supposedly) used outside of the vue components, there's seemingly something wrong or different on the php side when the save happens.

 - `'translate' => function($translate=null){ return $translate; })`
   Accordingly to the docs, that should take the `translate` property from the blueprint as argument and set it to that value, eventually defaulting it to false.
- `'translate' => function($translate=null){ return false; })`
  So this should take any value from the blueprint and force the field not to be translateable, right ?
- `'translate' => true` (prop) and `translate: false` (blueprint)
  Similarly, this combination should  enable translating the field even if the blueprint disables it, right ?

This works perfectly for a field `label` property, as the values sent from php to vue are correct and only used in the panel view. But for the `translate` property *(and maybe others)*, while saving a page from the panel, php seems to parse the translate property from the blueprint without resolving `$field->props`.

**Comment by Daandelange** [comment]
Things are getting clearer for me, still a bit confused.
This could be related to #4107 , but for the `translate` prop : maybe the php code sometimes uses the attributes instead of the parsed props ?

With the `translate` prop, I've observed similar behaviour using `$page->update(['fieldName'=>values], nonDefaultLanguageCode)`.
Saving is prevented only when `translate: false` is explicitly set in the blueprint, and the corresponding `translate` prop seems ignored on the php side.
