### ISSUE TITLE
Invalid CSRF token when trying to install panel/login on Safari

### ISSUE THREAD

**Issue by guidoferreyra** [k-next/kirby#4116]
## Description
I get invalid CSRF token when I try to install or login into panel in Safari. All other browsers work as expected.

**Screenshots**  
![imagen](https://user-images.githubusercontent.com/1755590/151010122-64fd3969-4256-4291-abcf-00165ba461ce.png)

## To reproduce
Download Starter kit, open in Safari,  try 

## Your setup
**Kirby Version**  
Kirby version. Latest and 3.5
Laravel Valet, tested with and without TLS encrypted mode.

**Console output**  
```
http://starterkit-main.test/api/system/install
Failed to load resource: the server responded with a status of 400 (Bad Request)
onError — index.js:1:6820
```

```
[Error] {status: "error", message: "Invalid CSRF token", code: 400, exception: "Kirby\\Exception\\InvalidArgumentException", key: "error.invalidArgument", …}
	onError (index.js:1:6820)
	(función anónima) (index.js:1:3488)
	asyncFunctionResume
	(función anónima)
	promiseReactionJob

```

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: Mac Os Mojave 10.14.6
 - Browser: Safari
 - Version: 12.1.2

**Comment by distantnative** [comment]
Difficult, I wasn't able to reproduce it so far.
You get this with a blank starter kit? No additional plugins or config?

**Comment by guidoferreyra** [comment]
Yes, starterkit. Here the files.

[starterkit-main.zip](https://github.com/getkirby/kirby/files/7986574/starterkit-main.zip)

And a screenshot from a few minutes ago.
![imagen](https://user-images.githubusercontent.com/1755590/152158160-b7f31d2f-739d-4148-b997-2f9bab435a7b.png)

**Comment by lukasbestle** [comment]
@guidoferreyra Do you still have this issue? And if so, can you consistently reproduce it in Safari? Have you tried clearing the cookies and browser cache for your test site?

**Comment by guidoferreyra** [comment]
I formatted my computer, can’t reproduce anymore. When I had this issue I cleared cache and everthing but didn’t work

**Comment by lukasbestle** [comment]
Thanks for your reply. Glad it works now.

I think the issue might have been caused by a locked up session.
