### ISSUE TITLE
[3.6.2]: kirbytextinline()/kti() incorrectly wraps with <p>/</p> tags

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4126]
## Description
I believe this is a new regression in 3.6.2:

When using `kirbytextline()`/`kti()` the resulting strings are wrapped in paragraph tags.

**Expected behavior**  
The result should just be the inner contents.

## To reproduce

```php
<?php

echo kirbytextinline('Hello');
// output: <p>Hello</p>
// expected: Hello

// assume field is just Foo
echo $page->field()->kirbytextinline();
// output: <p>Foo</p>
// expected: Foo
```

## Your setup
**Kirby Version**  
`3.6.2`

**Comment by neildaniels** [comment]
This was caused by a plugin that was providing a Markdown component override.

The call signature changed in `3.6.2` and the `$inline` parameter is no longer passed.

https://getkirby.com/docs/reference/plugins/components/markdown
```php
Kirby::plugin('my/markdown', [
    'components' => [
        'markdown' => function (Kirby $kirby, string $text = null, array $options = [], bool $inline = false) {
            return YourMarkdownParser::parse($text);
        }
    ]
]);
```

Perhaps use this issue to:
1. Update the [documentation](https://getkirby.com/docs/reference/plugins/components/markdown)
2. Temporarily keep passing an `$inline` parameter until `3.7.0`?

**Comment by bastianallgeier** [comment]
✅
