### ISSUE TITLE
[Panel] Cannot copy multiple blocks

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4129]
## Description
The button to copy multiple blocks does not work when an input element is focused. 

**Expected behavior**  
The focused input should "blur" before the copy operation is tried or the copy operation should work "anyway" when started from the button click.

## To reproduce
1. In a blocks field, create at least 1 text block
2. Select the block via Ctrl/Cmd + Click
3. Notice that the writer instance in the text block did not loose focus
4. Click on the copy button

Nothing is copied.

## Your setup
**Kirby Version** : 3.6.2, but also previous versions. 

**Console output**  
No console output

**Your system (please complete the following information)**
 - Device: PC
 - OS: Win 10
 - Browser: Chrome
 - Version: 97

**Additional context**  
The execution of the copy function in "Blocks.vue" is halted here:
```js
// don't copy if an input is focused
if (this.isInputEvent(e) === true) {
  return false;
}
```

## Quick fix
In **BlockOptions.vue**, the click on the copy (and also delete) button is handled by a `mousedown` event. This event fires before the browser has a chance to change focus from Input element to Button. As I understand it, the `mousedown` event was chosen, instead of a normal `click` event, because there is also a global "onOutsideFocus" that fires when a button is clicked that "deselects the blocks", and therefore the copy event has to fire before this "focus" event. 
The quickest fix would be to manually `blur()` the `activeElement` when the copy button receives "mouseDown".

**Comment by distantnative** [comment]
@rasteiner could this actually be related to https://github.com/getkirby/kirby/issues/3941?

**Comment by rasteiner** [comment]
> @rasteiner could this actually be related to #3941?

Oh haven't see that. Yes, it looks like the same issue

**Comment by bastianallgeier** [comment]
✅
