### ISSUE TITLE
[Panel] Cannot remove multiple blocks

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4131]
## Description
Trying to remove multiple blocks does not work. I click on "Delete" in the confirmation dialog, but nothing happens. 

**Expected behavior**  
The previously selected blocks should be deleted. 

**Screenshots**  

https://user-images.githubusercontent.com/6684137/152362459-6e085178-8747-44b1-b446-86c7a3a28a7f.mov

## To reproduce

1. Select multiple blocks
2. Try to delete them via the  batched selection flow. 

## Your setup
**Kirby Version**: 3.6.2

**Console output**  
No console output

**Your system (please complete the following information)**
 - Device: Desktop PC
 - OS: Win 10
 - Browser: Chrome
 - Version: 97

**Additional context**  
In the moment I click on the 🗑 button, the `onOutsideFocus` method in Blocks.vue fires and removes the blocks from the selection. Once I get to click on the confirmation "Delete" button, the blocks are no longer selected and are therefore not deleted.

**Comment by rasteiner** [comment]
Depending on the approach we want to take, I think this could be solved in a few ways:
1. pass selection to confirmation dialog, so that the dialog itself remembers which blocks you wanted to delete
2. change how onOutsideFocus works, making it do exceptions when you click on the options buttons **and** in the following dialog? 

--- 
edit:
actually the exact problem (or at least one of the problems) seems to be the dialog cancel button that automatically receives focus when shown.

**Comment by bastianallgeier** [comment]
✅
