### ISSUE TITLE
Cannot disable file sorting in user permissions

### ISSUE THREAD

**Issue by trych** [k-next/kirby#4137]
## Description
Currently, in the user permissions, it is possible to disable almost anything, which is ideal to set up a visitor role that can only look at panel, but not change anything. I sometimes need this, when I want to show potential clients an example backend that I did in the past.

However, the one thing that I can not disable is the sorting of files, so those users could potentially happily change the order of files and mess up the site.

Disabling the page sorting is easily possible though, like so:
```
permissions:
  pages:
    sort: false
```

**Expected behavior**  
Disabling file sorting should also be possible, like so:
```
permissions:
  files:
    sort: false
```

**Kirby Version**  
Kirby 3.6.2

**Comment by afbora** [comment]
I guess this is same with https://github.com/getkirby/kirby/issues/1969 issue.

**Comment by afbora** [comment]
Closing this in favor of #1969

**Comment by afbora** [comment]
Closing this in favor of #1969
