### ISSUE TITLE
Thumbnail creation doesn't work as expected when using webp

### ISSUE THREAD

**Issue by andreasotto** [k-next/kirby#4145]
## Description
Thumbnail creation doesn't work as expected when using `'format' => 'webp'`.
As soon as one switches the `format` to `webp`, the creation of thumbs doesn't work any more. Although images are converted to webp, as expected, the image has not the right size. Instead of that, the original, full size is given out. 

**Expected behavior**  
Even if webp format is used, the thumb settings should be taken into account and the thumbs should be generated in the required size.

## To reproduce
Setup `config.php`with these settings:

```
    'thumbs' => [
        'format' => 'webp',
        'presets' => [
            '1950w' => ['width' => 1950, 'quality' => 30],
        ]
    ],
```

Then use in a template like this:
```
<img src="<?= $image->thumb('1950w')->url() ?>">
```

Result:
- Image is converted to webp (as expected)
- But the preset setting was not taken into account. The image is output in full size (not expected).
- (As soon as you remove format webp, the thumb will be output in the correct size again.)

**Kirby Version**  
3.6.1.1

**Comment by distantnative** [comment]
Which thumb driver are you using? https://getkirby.com/docs/reference/system/options/thumbs#thumbs-driver
Default `gd`?

**Comment by andreasotto** [comment]
Yes, default (changed no setting for that).

Update: Just switched to `im` for a test, but makes no difference.

**Comment by afbora** [comment]
I've tested your settings on Starterkit 3.6.2 and works great for me. 

## Don't forget:

### Smaller image width

If the image width (for ex: 800x600px) is less than the desired (1950px) width, the full size (800px) is displayed.

### Crop option

If you do not want the above situation, you can use the `crop` option. So the size you want is always shown.

````php
'thumbs' => [
    'format' => 'webp',
    'presets' => [
        '1950w' => ['width' => 1950, 'quality' => 30, 'crop' => true],
    ]
],
````

**Comment by afbora** [comment]
@andreasotto Have you tried my last post?

**Comment by bastianallgeier** [comment]
Maybe your GD and IM installations don't support webp yet. It has been introduced in more recent versions.

**Comment by andreasotto** [comment]
Debian 11.2
PHP 8.1.4
Kirby 3.6.2

Everything is up-to-date

Converting to webp seems to work, but the file is not resized.

`config.php` (as suggested by @afbora ):
```
    'thumbs' => [
        'format' => 'webp',
        'presets' => [
            'background' => ['width' => 1950, 'quality' => 30, 'crop' => true],
        ]
    ]
```

Template:
```
            <?php if($image = $block->image()->toFile()) : ?>
                <img class="w-full h-full object-cover" src="<?= $image->thumb('background')->url() ?>" alt="">
            <?php endif ?>
```

Result:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/2129515/160170906-e1a90a12-dc70-413d-970a-a72cc64969f6.png">

As you can see, the image is 4.4 mb and has not been resized.

What can i do to deliver better information to find the problem?

**Comment by texnixe** [comment]
I can't reproduce the issue, at least not with images that are larger than the target size. An image that was smaller than the target size was blown up though, tested with PHP 8.1 on Mac with Laravel Valet.

**Comment by andreasotto** [comment]
It does not work on Linux (latest Debian, latest PHP8). Maybe there are some system libraries missing. But that means we need some more documentation of dependencies. But these are all just guesses. The fact is that images from other formats are not converted to WebP in this configuration:
- Debian 11
- PHP 8.1

Installed package: `libwebp-dev`

gd is configured with `gd --with-freetype=/usr/include/ --with-webp --with-jpeg=/usr/include/ && docker-php-ext-install -j$(nproc) gd`

`phpinfo()` says: `WebP Support: enabled`

I have loaded jpg and other formats into Kirby. The output format chosen was webp. The images look like they would habe been converted to webp, but the size is not changed. So the images are way too big to use in the website. But in reality, no image has been created in the media folder.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/2129515/160201635-dd31fbed-b2b4-4b11-84bf-002dd9b64890.png">

There is only a job file, but no image has been saved:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/2129515/160201870-96fec943-aca6-4866-a8d3-f70dc1aa67e5.png">

content of jobs file:
```
{"width":1950,"quality":30,"crop":true,"format":"webp","filename":"stocksnap_btg0uzk1nx-1.jpg"}
```

This looks like the webp conversion is not working, but unfortunately no error message is displayed either.

**Comment by andreasotto** [comment]
It worked. The key point was the configuration of `gd`. This is how it works:

```
gd --with-freetype=/usr/include/ --with-webp=/usr/include/ --with-jpeg=/usr/include/
```

**Comment by afbora** [comment]
@andreasotto Closing the issue then, right?

**Comment by andreasotto** [comment]
Maybe a short discussion about the requirements or dependencies would be useful, because I think there are two aspects: 
1. missing documentation 
2. check (e.g. show in the panel if requirements are not met - there is no error message and no hint).
