### ISSUE TITLE
Kirby and PHPMailer differ in their $text initialisation which fails in PHP8.1

### ISSUE THREAD

**Issue by anselmh** [k-next/kirby#4155]
## Description

Kirby fails to send emails via PHPMailer when using PHP8.1. This is due to the [initialization of `$text` in Kirby](https://github.com/getkirby/kirby/blob/main/src/Email/Body.php) which differs from [the one in PHPMailer](https://github.com/PHPMailer/PHPMailer/blob/master/src/PHPMailer.php#L138).

**Expected behavior**  
Emails can be sent without a PHP error.

## To reproduce

1. Send email via form in Kirby via PHPMailer
2. Returns error `preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated`

## Your setup
**Kirby Version**  
3.6.2, same in 3.6.1.1

**Console output**  
```
Passing null to parameter #2 ($subject) of type string is deprecated" object(Uniform\Exceptions\PerformerException)#339
```

**Comment by afbora** [comment]
✅
