### ISSUE TITLE
Panel layout broken in Esperanto

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4159]
## Description
The panel layout is broken when visiting it with an esperanto user profile.

**Expected behavior**  
It should not break.

**Screenshots**  
![image](https://user-images.githubusercontent.com/6684137/154054764-2c499264-01db-4625-8d5f-29b4496abef8.png)

## To reproduce

1. Go to `/panel/account`
2. Change your language to Esperanto

## Your setup
**Kirby Version** : 3.6.2

**Console output**  
No console output

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 98

**Additional context**  
It seems like the direction variable was translated. In fact, in Esperanto the panel Dom reads like this:
```html
<div data-role="admin" data-translation="eo" data-user="***" dir="demaldekstre" class="k-panel k-panel-inside" tabindex="0">...
```

Notice `dir="demaldekstre"` instead of `dir="ltr"`

**Comment by afbora** [comment]
### Summary

Should be fixed the `translation.direction` key from transifex for `eo` and `ko` languages.

**Comment by bastianallgeier** [comment]
I love your "Expected behaviour" description

**Comment by bastianallgeier** [comment]
I fixed it for both languages on transifex.
