### ISSUE TITLE
Table Block throws error when value is empty

### ISSUE THREAD

**Issue by mayfinn** [k-next/kirby#4164]
## Description

If a value is added in a table block and left empty the table fails to render in Vue due to an `Cannot read properties of undefined` error.

If the file is saved and the page is reloaded the table renders as expected.

**Expected behavior**  

An empty value should render the cell with `–` as shown in the screenshot below.

**Screenshots**  

![Bildschirmfoto 2022-02-17 um 15 21 23](https://user-images.githubusercontent.com/19761338/154500933-57e94ff8-d3d3-4ae2-b180-794235f2a5da.png)
![Bildschirmfoto 2022-02-17 um 15 26 17](https://user-images.githubusercontent.com/19761338/154501897-645d1cf9-c60e-432e-a4ce-be913160bcf2.png)

## To reproduce

1. Create Table Block blueprint with rows (Types could be text, number etc.)
2. Insert one row with an empty value
3. Save block

## Your setup
**Kirby Version**  
3.6.2

**Console output**  
```
index.js:1 TypeError: Cannot read properties of undefined (reading 'toString')
    at a.displayText (index.js:1:177608)
    at index.js:1:293333
    at a.be [as _l] (vendor.js:6:16323)
    at index.js:1:293013
    at a.be [as _l] (vendor.js:6:16023)
    at a.<anonymous> (index.js:1:292964)
    at a.t._render (vendor.js:6:35359)
    at a.r (vendor.js:6:68538)
    at vn.get (vendor.js:6:26734)
    at vn.run (vendor.js:6:27621)
```
**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS
 - Browser: Chrome
 - Version: 98

**Additional context**

**Comment by afbora** [comment]
✅

**Comment by mayfinn** [comment]
Thanks guys 🎉
