### ISSUE TITLE
WebP and PNG thumbnails generated in root folder with IM driver

### ISSUE THREAD

**Issue by theamnesic** [k-next/kirby#4178]
## Description
Randomly, webp thumbs are generated in the root folder with a double .webp extension.

**Expected behavior**  
Thumbs in media folder, not root.

**Screenshots**  
![kirby-github](https://user-images.githubusercontent.com/242203/155510633-5b9d8346-4c48-478c-a4d2-332a38ac68b4.png)

## To reproduce

Set this 'srcset' in config, **with `im` driver**: 

```

'thumbs' => [

	'driver' => 'im',

	'srcsets' => [

		'default' => [
			'480w' =>  ['width' => 480,  'quality' => 78],
			'768w' =>  ['width' => 768,  'quality' => 78],
			'1024w' => ['width' => 1024, 'quality' => 78],
			'1440w' => ['width' => 1440, 'quality' => 78],
			'1920w' => ['width' => 1920, 'quality' => 78],
			'2048w' => ['width' => 2048, 'quality' => 78]
		], 

		'webp' => [
			'480w'  => ['width' => 480,  'quality' => 90, 'format' => 'webp'],
			'768w'  => ['width' => 768,  'quality' => 90, 'format' => 'webp'],
			'1024w' => ['width' => 1024, 'quality' => 90, 'format' => 'webp'],
			'1440w' => ['width' => 1440, 'quality' => 90, 'format' => 'webp'],
			'1920w' => ['width' => 1920, 'quality' => 90, 'format' => 'webp'],
			'2048w' => ['width' => 2048, 'quality' => 90, 'format' => 'webp']
		], 
	]
],

```

Upload multiple images and check your root folder.

## Your setup
**Kirby Version**  
3.6.2 - no plugins

**Your system (please complete the following information)**
Same on my local MAMP on macOS Monterey and my OVH web hosting (PHP 7.4).

**Additional context**  
It seems OK with GD driver. I use IM because of some animated GIFs I need to convert.

**Comment by theamnesic** [comment]
A workaround could be use a different driver by preset, for example only for GIFs:
`'gif' => ['width' => 100, 'driver' => 'im']`.
But this doesn't work...

**Comment by theamnesic** [comment]
Update, same root folder generated images with PNGs:

![Capture d’écran 2022-03-01 à 13 51 35](https://user-images.githubusercontent.com/242203/156172496-5c16d2fa-de0f-441b-94fe-e01624eca6ce.png)

Maybe all images with transparency are concerned?

**Comment by distantnative** [comment]
This definitely will be hard to debug without replication - will see if we can reproduce this somehow. Any other config settings you have?

**Comment by HashandSalt** [comment]
I am also seeing this happen on my local Valet using:

PHP 8.0.16
ImageMagick 7.1.0-27
Kirby 3.6.2

Let me inow if i can help at all. My source images are jpegs no transpency involved. I am also using AVIF as well WebP (only seeing AVIF files in the root)

Thumbs config

```
'thumbs' => [
    'driver' => 'im',
    'bin' => '/opt/homebrew/bin/convert',
    'quality' => 95
],
```

**Comment by HashandSalt** [comment]
Issue still exists, im getting it in another project now, using PHP 8.1 and Valet 3. Also updated Imagemagick to current. :(

**Comment by HashandSalt** [comment]
Seems its down to the focuscrop plugin. I just pieced my project together bit by bit in a clean starterkit and and happened as soon used FocusCrop. Theres an issue for it:

https://github.com/flokosiol/kirby-focus/issues/65

So i guess this can be closed as its down to the plugin?

**Comment by distantnative** [comment]
@theamnesic ate you using that plugin as well?

**Comment by HashandSalt** [comment]
Its odd cos the plugin is still using standard thumb(), srcset() and crop() internally so its a bit crazy why this happens.

**Comment by theamnesic** [comment]
> @theamnesic ate you using that plugin as well?

My mistake, I thought I didn't have any plugin but `flokosiol/focus` was installed, even if I don't use it.

Anyway, everything works fine now!

**Comment by lukasbestle** [comment]
Thanks for your replies. Closing this as the issue is related to the Focus plugin.
Discussion continues at flokosiol/kirby-focus#65.
