### ISSUE TITLE
[3.6.3-rc.1] PHPMailer Exception: Message body empty

### ISSUE THREAD

**Issue by ralfgoeke** [k-next/kirby#4183]
## Description
After upgrading to 3.6.3. RC1 from 3.6.2, at least on my local machine sending E-Mails in a route via $kirby->email() seems to be broken. Downgrading to 3.6.2 makes everything work again.

**Expected behavior**  
Mails should be sent without error

**Exception**  
```php
PHPMailer\PHPMailer\Exception {[#2016 ▼]()
  #message: "Message body empty"
  #code: 2
  #file: "/Users/XXXXXXXXX/vendor/phpmailer/phpmailer/src/PHPMailer.php"
  #line: 1580
}
```

## Your setup
**Kirby Version**  
3.6.3 RC1

**Your system**
 - OS: macOS 12.2.1
 - Mamp Pro
 - PHP 8.0.8

**Additional context**  
Maybe a regression from https://github.com/getkirby/kirby/issues/4155?

**Comment by afbora** [comment]
Previously it was `null` and working. We updated it to empty string and it doesn't work. It's really weird. I reviewed the codes, but I don't understand why it is not working now while it was `null`.

Can you share a sample email data array please?

**Comment by ralfgoeke** [comment]
Sure.

Simplified it, but same effect.
Works with 3.6.2, fails with 3.6.3. RC1.

```php
try {
  $kirby->email([
    'from' => 'noreply@example.com',
    'replyTo' => 'foo@example.com',
    'to' => 'me@example.com',
    'subject' => 'Some Subject',
    'body' => 'Some Body Text',
  ]);
} catch (Exception $error) {
  ray($error);
}
```

I just recognized that PHPMailer gets bumped from 6.5.3 to 6.5.4 in K 3.6.3. when running composer update.
Maybe something with their code changed?

**Comment by afbora** [comment]
Thank you @ralfgoeke 👍 I found the source of issue. I'll create PR for it.

**Comment by afbora** [comment]
@ralfgoeke You can test the bug-fix PR #4184

**Comment by ralfgoeke** [comment]
Yay, fixes are working in my setup now. Thanks a lot @afbora :)

**Comment by afbora** [comment]
✅
