### ISSUE TITLE
Fix inconsistencies in properties naming 

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#4194]
## Description
With a codebase that has grown over time, elements' properties, especially when writing Kirby blueprints, have generated quite some inconsistencies in naming. The most prominent example would be in naming elements:

**Example**
- Blueprints use `title`
- Fields use `label`
- Blocks use `name`
- Sections use `headline`, while the field section has no such property

**Expected behavior**  
The user would expect to be able to set the name of such elements with the same property. Especially sections using `headline` is often confused with a Fields' `label`, while both even share the same look and feel.

**Additional context**  
While it might not be possible to effectively change all properties' names, as such would cause a huge breaking change for most Kirby blueprints, it'd be possible to alias several properties to the computed (translated) props. An example for the sections' headline mixin would be:

```php
<?php

use Kirby\Toolkit\I18n;

return [
    'props' => [
        /**
         * The headline for the section. This can be a simple string or a template with additional info from the parent page.
         */
        'headline' => function ($headline = null) {
            return I18n::translate($headline, $headline);
        },
        'label' => function ($label = null) {
            return I18n::translate($label, $label);
        }
    ],
    'computed' => [
        'headline' => function () {
            if ($this->headline) {
                return $this->model()->toString($this->headline);
            }

            if ($this->label) {
                return $this->model()->toString($this->label);
            }


            return ucfirst($this->name);
        }
    ]
];
```

There might be more inconsistencies, although, those, like the ones mentioned above for naming elements, are the properties I always confuse while working with blueprints.

> Follow up of discussion [on Discord](https://discord.com/channels/525634039965679616/525641819854471168/950499993209413742)

**Comment by bastianallgeier** [comment]
We've now fixed the inconsistencies by introducing aliases. Here's what we have now: 

- Blueprint: title
- Block: title & label with two individual functions
- Field: label
- Section: label

The old props will keep on working but will be deprecated eventually.

**Comment by mrflix** [comment]
@tobimori thanks for bringing this topic up and thanks @bastianallgeier and team that you adjusted things. Being able to use "label" instead of "headline" for sections was a wonderful change. These days I still often run into accidentally naming blocks using "label". I then realize it when I try to add the new block:
![Screenshot 2024-01-12 at 17 26 31](https://github.com/getkirby/kirby/assets/60777/0d290855-e03d-4a14-a299-bbbe0997bfc7)
TIL that "name" is outdated and "title" is the preferred way of naming blocks. And that label can be used for the subtitle.
![Screenshot 2024-01-12 at 17 26 54](https://github.com/getkirby/kirby/assets/60777/34546a0b-7ffc-4ce5-b446-43d5f2f4ed62)

I want to suggest to fallback to the label when there is a label defined but no title is empty.

**Comment by distantnative** [comment]
@mrflix Please post it as separate issue. It's really hard for us to keep track of suggestions/comments on closed two year old issues 😅

**Comment by mrflix** [comment]
Reopen the gates!
I understand. Here is the new issue: https://github.com/getkirby/kirby/issues/6137
TIL also that you can sort issues [by recently updated](https://github.com/getkirby/kirby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). Maybe that's a better sorting for you, so old issues can continue to be used when they get relevant again.

**Comment by lukasbestle** [comment]
Thanks for the new issue. 👍

> TIL also that you can sort issues [by recently updated](https://github.com/getkirby/kirby/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). Maybe that's a better sorting for you, so old issues can continue to be used when they get relevant again.

Yes, but that won't help with closed issues. We get notifications for new comments, but we can't realistically scan those for missed changes via the list.
