### ISSUE TITLE
[3.6.3-rc.1] `url` option: Constants instead of `true`, `false`, `null`

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4198]
I feel like the `true` and `false` values are too nondescript. What if we replace them with constants like `Server::HOST_ANY_EMPTY` (= null, default), `Server::HOST_ANY` (currently false, new constant value e.g. 1) and `Server::HOST_ANY_INSECURE` (currently true, new constant value e.g. 2)?
Considering that `Server` is already globally aliased, that should be viable even for non-techy users.

**Discussion:**
https://discord.com/channels/525634039965679616/525637437494657024/950339023120003104

**Comment by bastianallgeier** [comment]
✅
