### ISSUE TITLE
[3.6.3-rc.1] Optical accessibility of the current day highlight in the Date Picker

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4202]
I'm just testing the 3.6.3-rc.1 and would like to suggest an improvement to the "current day highlight" re accessibility. At the moment, the current date is only highlighted by a very subtle colour highlight (light yellow vs. white; contrast between those two foreground colours is only 2.77:1) and an almost inconceivable increase in boldness.

Quick-fire idea: maybe add an underline?

_Originally posted by @sebastiangreger in https://github.com/getkirby/kirby/issues/4124#issuecomment-1068770507_

**Comment by bastianallgeier** [comment]
I think this could work

![Screenshot 2022-03-17 at 14 07 46](https://user-images.githubusercontent.com/24532/158815008-afe21dba-34da-4f99-af47-ad49b04af22d.png)

The two colours are making the problem actually worse. Is yellow selected or blue selected? I think it's clearer this way.

**Comment by afbora** [comment]
It is clearer that today text and today's date are in the same style, at the same time this style looks more minimal. I liked that 👍

**Comment by bastianallgeier** [comment]
I've added it to the rc-2 PR.

**Comment by sebastiangreger** [comment]
Looks great, and entirely solves the original issue :slightly_smiling_face:

**Comment by sebastiangreger** [comment]
Just testing rc-2 … there is a small glitch on FF96/Linux:

![Screenshot from 2022-03-17 17-24-16](https://user-images.githubusercontent.com/6355217/158847667-3afef121-4f35-4986-b437-91cf790c3c4a.png)

If you can reproduce this (i.e. it's not something wrong on my end), overriding the `vertical-align` property for the span in this specific button appears to solve the issue:

```
.k-calendar-today .k-button-text {
  opacity: 1;
  display: inline;
  vertical-align: baseline;
}
```

(It might be an actual, long-standing Firefox rendering quirk/bug, I found at least [one similar issue on SO](https://meta.stackexchange.com/questions/344916/code-snippet-link-text-conflicts-with-underline-in-firefox))

**Comment by afbora** [comment]
I can confirm that glitching FF for me too and `vertical-align: baseline` works.

**Comment by distantnative** [comment]
@afbora will you add a PR?

**Comment by bastianallgeier** [comment]
✅
