### ISSUE TITLE
Add attributes to svg helper

### ISSUE THREAD

**Issue by dgsiegel** [k-next/kirby#4209]
## Description

Currently, using the `svg` helper function (e.g. `<?= svg("assets/icon.svg") ?>`) will simply read the contents and return them. Sometimes however you want to add attributes to that svg, for example adding a class name or the `aria-hidden` attribute if it is just a decorative element. Both are currently not possible.

## Your setup
**Kirby Version**  
3.6.2

**Comment by bastianallgeier** [comment]
I think this is a feature request that I've seen on Nolt already. I'd keep it there to be honest.

**Comment by distantnative** [comment]
True: https://kirby.nolt.io/417 - please upvote
