### ISSUE TITLE
`allow="fullscreen"` not acknowledged by YouTube - working (deprecated) alternative `allowfullscreen` automatically removed

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#4212]
## Description
The [`Html::videoAttr()`](
https://github.com/getkirby/kirby/blob/04127160ed1ab8dc277763cd8ba4ebc5a097bc18/src/Toolkit/Html.php#L494) static used by the video() helper for YouTube URLs automatically removes the `allowfullscreen` attribute as it's said to be deprecated. The automatically set alternative attribute `allow="fullscreen"` was not acknowledged by YouTube in my test. There's no way to manually set it, as it's always removed. 

https://github.com/getkirby/kirby/blob/04127160ed1ab8dc277763cd8ba4ebc5a097bc18/src/Toolkit/Html.php#L507

**Expected behavior**  
YouTube iFrames would allow full screen mode.

## To reproduce

**Example Function**
```php
video('https://youtube.com/watch?v=Iq2gv4fPiuM', ['youtube' => ['autoplay' => 1]], ['frameborder' => '0']);
```

**Output**
```html
<iframe allow="fullscreen" frameborder="0" src="https://youtube.com/embed/Iq2gv4fPiuM?autoplay=1"></iframe>
```

**Result**
<img width="258" alt="CleanShot 2022-03-21 at 20 56 25@2x" src="https://user-images.githubusercontent.com/29142128/159353595-91a7c8f9-cb60-41e7-b8e7-1cabc2fde4b9.png">

## Your setup
**Kirby Version**  
Kirby v3.6.2

**Your system**
 - Device: MacBook Pro
 - OS: macOS 12.3
 - Browser: Chrome
 - Version: 99.0 / arm64

**Comment by afbora** [comment]
Really weird. I think we should keep `allowfullscreen` attribute for a while..

**Comment by bastianallgeier** [comment]
✅
