### ISSUE TITLE
Pagination no longer working in 3.6.3

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#4219]
## Description
Pagination stopped working in 3.6.3.

**Expected behavior**  
Pagination should work as before.

## To reproduce
In a 3.6.3 Starterkit, modify the photography.php template like this:

```
<?php snippet('header') ?>
<?php snippet('intro') ?>

<ul class="grid" style="--gutter: 1.5rem">
  <?php foreach ($page->children()->listed()->paginate(2) as $project): ?>
  <li class="column" style="--columns: 3">
    <a href="<?= $project->url() ?>">
      <figure>
        <span class="img" style="--w:4;--h:5">
          <?= ($cover = $project->cover()) ? $cover->crop(400, 500) : null ?>
        </span>
        <figcaption class="img-caption">
          <?= $project->title()->html() ?>
        </figcaption>
      </figure>
    </a>
  </li>
  <?php endforeach ?>
</ul>
<?php if ($pagination->hasPages()): ?>
  <nav class="project-pagination grid">
    <?php if ($pagination->hasPrevPage()): ?>
    <a class="column" href="<?= $pagination->prevPageURL() ?>" style="<?= $pagination->hasNextPage() ? '--columns: 6' : '--columns: 12' ?>">
    ‹ previous projects page
    </a>
    <?php endif ?>
    <?php if ($pagination->hasNextPage()): ?>
    <a class="column next" href="<?= $pagination->nextPageURL() ?>" style="<?= $pagination->hasPrevPage() ? '--columns: 6' : '--columns: 12' ?>">
      next projects page  ›
    </a>
    <?php endif ?>
  </nav>
<?php endif ?>
<?php snippet('footer') ?>
```
Open page in browser and click on next page link. See how you are redirected to the home page instead of to the next page.

## Your setup
**Kirby Version**  
Kirby 3.6.3

**Your system (please complete the following information)**
 - Device: MacBook Pro (14", 2021)
 - OS: 
 - Browser: Firefox
 - Version: 98.0.1 (64-Bit)

**Additional context**  
This was originally brought up by the Ajax recipe not working anymore, but turned out that even normal pagination doesn't work.

**Comment by afbora** [comment]
Works great for me, am I missing something on setup?

https://user-images.githubusercontent.com/3393422/159572979-c71b86dd-bd90-4189-84f9-b6a98f363d94.mp4

**Comment by bastianallgeier** [comment]
✅
