### ISSUE TITLE
Setting 'home' to a panel-generated page does not work (folder name pattern)

### ISSUE THREAD

**Issue by krokodok** [k-next/kirby#4220]
I want to set my home page to a page created and maintained by the panel in `config.php`. The folder name pattern "Number Underscore Name" does not appear to work.

Works:
`'home => 'home'`
`'home' => '1home'`
`'home' => 'test_home'`

Does not work:
`'home' => '1_home'`

I was not able to find out why in the source code.

**Comment by afbora** [comment]
`NUMBER_SLUG` syntax is special format for `listed` pages. So there is no page with `1_home` slug. `1_home` means, `home` page order is first.

**Comment by krokodok** [comment]
Thank you for clearing this up, could not find the explanation in the manual!

**Comment by afbora** [comment]
You can check out `Editing & publishing workflow` page:
https://getkirby.com/docs/guide/content/publishing-workflow#publishing-drafts__in-the-content-folder
