### ISSUE TITLE
Cropping doesn't work with PHP 8.1

### ISSUE THREAD

**Issue by mynameisfreedom** [k-next/kirby#4228]
Hi, the problem is simple, cropping doesn't work with PHP 8.1. 

Windows, Apache, PHP 8.1. 
Default Kirby setup.

**Comment by texnixe** [comment]
I cannot reproduce that, tested with Kirby 3.6.3 on Mac with Valet and PHP 8.1. Might be that your version of 8.1 doesn't have gd enabled? Do thumbs work at all? Do you get the original image in the media folder or no image at all?

**Comment by mynameisfreedom** [comment]
Oh my, you are right, I checked that now, turned it on, and it works. 

Sorry, closing this issue.
