### ISSUE TITLE
Tabs bar more button not working

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4230]
## Description
The "more" button for longer tab bars doesn't appear until the first periodic GET request.

**Expected behavior**  
The tab bar is usable on page load.

**Screenshots**  

![image](https://user-images.githubusercontent.com/7975568/160015629-8632909e-42dc-4686-b763-3d737c16cfd9.png)

<img width="641" alt="load" src="https://user-images.githubusercontent.com/7975568/160015652-987887b3-170a-4a5e-8b6f-ff2241da4019.png">

## To reproduce

1. Add more than three tabs to any blueprint
2. Open the panel in a smaller window or on a mobile device
3. See the error
4. Wait 10 seconds
5. See the error disappear

## Your setup
**Kirby Version**  
3.6.0 — 3.6.3.1

**Console output**  
I can see this issue being automatically resolved after exactly 10 seconds when the first GET request appears in the dev tools. Nothing in the console, though.

**Your system (please complete the following information)**
 - Device: iPhone, Mac
 - OS: macOS, iOS
 - Browser: All of them

**Comment by distantnative** [comment]
Can reproduce

**Comment by bastianallgeier** [comment]
✅

**Comment by bastianallgeier** [comment]
@medienbaecker your battery status is triggering me 🤣

**Comment by medienbaecker** [comment]
@bastianallgeier Don't worry, I've charged it since taking the screenshot 😅

Thanks for fixing this issue so fast!

**Comment by distantnative** [comment]
Thanks for the good description and already identifying the 10 seconds behaviour. Made it super quick to find the solution.
