### ISSUE TITLE
File droppable in "translate: false" files-field

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#4231]
## Description

- multi-language setup
- structure with a file field that's `translate: false`
- dropped a file in the secondary language (the new cool direct drag and drop – really nice!!)
- the file landed which shouldn't be possible
- the file reference was not stored on save

**Expected behavior**  
I'd expect to see an error message when dropping the file or that it wouldn't even be possible to drop the file.

**Screenshots**  
![Screenshot 2022-03-25 at 16 25 06](https://user-images.githubusercontent.com/60777/160150561-1e66a36e-1668-4d09-856a-e253217100a0.png)
Successful file-drop. English is the secondary language.

## Your setup
**Kirby Version**  
3.6.3

**Comment by bastianallgeier** [comment]
✅

**Comment by mrflix** [comment]
Thank you Amet & Bastian! That was fast :)
