### ISSUE TITLE
Uncaught TypeError: t.target.closest is not a function

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#4233]
## Description
Console is spammed with this error since v3.6.3.

**Expected behavior**  
No error thrown.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/6271057/160238227-46339031-9e08-41f8-8056-6d763e533226.png)

## To reproduce

1. Go to a page with a text field, user field, tag field, date field and a structure
2. click in an existing block in the text field
3. Error is thrown in browser console (see screenshot)

## Your setup
v3.6.3

**Console output**  
Uncaught TypeError: t.target.closest is not a function
    onOutsideFocus http://localhost/kirby/media/panel/d569c10cce8640c7659eb139caaeb416/js/index.js:1
    emit http://localhost/kirby/media/panel/d569c10cce8640c7659eb139caaeb416/js/vendor.js:12
    emit http://localhost/kirby/media/panel/d569c10cce8640c7659eb139caaeb416/js/vendor.js:12
    focus http://localhost/kirby/media/panel/d569c10cce8640c7659eb139caaeb416/js/index.js:1
    install http://localhost/kirby/media/panel/d569c10cce8640c7659eb139caaeb416/js/index.js:1
    use http://localhost/kirby/media/panel/d569c10cce8640c7659eb139caaeb416/js/vendor.js:6
    <anonymous> http://localhost/kirby/media/panel/d569c10cce8640c7659eb139caaeb416/js/index.js:1
[index.js:1:304997](http://localhost/kirby/media/panel/d569c10cce8640c7659eb139caaeb416/js/index.js)

**Your system (please complete the following information)**
WAMP with php8.0 and latest Firefox

**Additional context**  
this is a multilang page, error didn't occur before updating

**Comment by afbora** [comment]
I can reproduce the issue only with Firefox. No console error for Chrome.

**Comment by afbora** [comment]
This issue occurs when you enter or click on a page includes a block field from outside (another browser page/tab or anywhere except current browser page).

**Comment by bastianallgeier** [comment]
✅
