### ISSUE TITLE
Structure field: several problems

### ISSUE THREAD

**Issue by Werbschaft** [k-next/kirby#4242]
There are currently some problems with the structure field. Tested with Kirby 3.6.3.1 with Chrome on Mac

1. if you use a structure field in the drawer the sticky header does not fit. Quick fix:
```css
.k-drawer-body .k-structure-table th {
  top: -1.5rem;
}
```
![Kapture 2022-03-29 at 12 57 37](https://user-images.githubusercontent.com/2178466/160597045-dffb77a8-70e4-42b8-90f1-2a5f2d82a8ae.gif)

2. the text overflow is ignored when dragging and dropping. This ensures that it can become very very confusing when dragging.

![Kapture 2022-03-29 at 13 00 35](https://user-images.githubusercontent.com/2178466/160597399-3ea89b78-6bd1-4eac-bbeb-651e215005b7.gif)

3. further it is not possible within the Drawer with a structure field by drag and drop that the page scrolls up or down. I don't think this is a bad thing, but it should still be mentioned.

**Comment by afbora** [comment]
@distantnative I want to ask before working on this issue. Should we fix this issue in your structure PR (#4215) or not?

**Comment by distantnative** [comment]
Regarding 2:
I think it's a general bug that the text is floating again beneath the cursor. Not just the overflow.

But it seems like https://github.com/getkirby/kirby/pull/4215 already fixes this.

Before PR:

https://user-images.githubusercontent.com/3788865/161744456-9de53e0a-f145-40bd-98c7-7f1e8f3d49d1.mov


After PR:

https://user-images.githubusercontent.com/3788865/161744478-ea3185c3-5652-4abd-8e34-0d9f2dcc2511.mov

**Comment by afbora** [comment]
Great! Also fixing first issue is so easy. So we can solve this issue in your PR.

**Comment by bastianallgeier** [comment]
✅  will be solved in 3.7
