### ISSUE TITLE
Default cache driver

### ISSUE THREAD

**Issue by FabienYt** [k-next/kirby#4243]
## Description
According to the documentation [here](https://getkirby.com/docs/reference/system/options/cache#cache-driver), it's possible to redefine the default cache driver but it does not work

## To reproduce
In _config.php_

```php
return [
    'cache' => [
        'pages' => ['active' => true],
        'type' => 'memory'
    ],
];
```

## Your setup
Version -> 3.6.3.1

**Console output**  
Result with xdebug -> AppCaches.php -> line 34

```php
Array
(
    [active] => 1
    [type] => file
    [extension] => cache
    [root] => C:\kirby_test\cache
    [prefix] => localhost/pages
)
```

The problem comes from the AppCaches.php -> cacheOptions method :
```php
$defaults = [
            'active'    => true,
            'type'      => 'file',
            'extension' => 'cache',
            'root'      => $this->root('cache'),
            'prefix'    => $prefix
];
```
should be
```php
$defaults = [
            'active'    => true,
            'type'      => option('cache.type', 'file'),
            'extension' => 'cache',
            'root'      => $this->root('cache'),
            'prefix'    => $prefix
];
```

**Comment by distantnative** [comment]
I'm wondering if the docs are just wrong and the `type` key needs to be inside your `pages` array.

Wouldn't be the default driver - but the docs also don't talk about that. So maybe yours is less a bug and more a feature request.

**Comment by afbora** [comment]
As Nico said, cache type should be set from inside of each cache item. Thus, you can work with different caches for each resource. If no type is set, it is file cache.

For example:

````php
<?php

return [
    'cache' => [
        'pages' => [
            // no need to set type for file cache
            'active' => true,
        ],
        'plugins' => [
            'active' => true,
            'type'   => 'apcu'
        ],
        'reference' => [
            'active' => true,
            'type'   => 'memcached',
            'host'   => 'localhost',
            'port'   => '11211'
        ]
    ]
];
````

**Comment by bastianallgeier** [comment]
I'm sorry. The docs were indeed wrong. I just fixed it.
