### ISSUE TITLE
Panel: Lists inside the writer field have incorrect alignment

### ISSUE THREAD

**Issue by manuelmoreale** [k-next/kirby#4245]
## Description
The screenshot is pretty self explanatory I believe.
This is mainly a CSS issue inside the writer field

**Screenshots**  
![Screenshot 2022-03-31 at 10 06 45 AM](https://user-images.githubusercontent.com/1738077/161008346-6e3b0ae1-ba26-4e57-a58d-54d1e41461a3.png)

**Comment by afbora** [comment]
Seems well for me for blocks and layout field. Do you have custom CSS or plugin for blocks?

![screen-capture-1397-About us - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/161031150-1d85a728-83a9-42ed-bc63-10188e815fdd.png)

**Comment by distantnative** [comment]
✅ fixed in next release
