### ISSUE TITLE
Meta data file without corresponding file inside the folder crashes page content

### ISSUE THREAD

**Issue by kevinvennitti** [k-next/kirby#4246]
## Description
When there is a meta data file (eg: `myimage.png.txt`) inside a page folder _without_ the corresponding file (`myimage.png`), the page content is not used because the content file (eg: `default.txt`) is not recognized.

**Expected behavior**  
The content file `default.txt` should be used to display page content.

## To reproduce
The bug is reproduced here with the _plainkit_: https://github.com/kevinvennitti/kirby-bug-report-31-03-2022
- `/photography/trees` is working (no change)
- `/photography/sky` is not working (bug reproduced on this page)

1. Create a page
2. Add any image file with its corresponding meta data file
<img width="268" alt="before" src="https://user-images.githubusercontent.com/9624530/161080517-014216b0-9ffb-4413-8e1b-58e3fa982860.png">

3. Open the page in the browser: everything is fine
<img width="648" alt="screencapture-2022-03-31-16 35 25@2x" src="https://user-images.githubusercontent.com/9624530/161081025-900a52bf-5a45-47f5-b5e7-3bfa339565ec.png">

4. Now, delete the image file (without deleting the meta data file)
<img width="268" alt="after" src="https://user-images.githubusercontent.com/9624530/161080512-88988e0f-4017-4e19-8782-713a9a3b2c29.png">

5. Open the page in the browser: the render is broken
<img width="648" alt="screencapture-2022-03-31-16 36 01@2x" src="https://user-images.githubusercontent.com/9624530/161081049-8241e81b-2025-421e-b6a3-786dcf2db164.png">

## Your setup
**Kirby Version**  
3.6.3.1

**Your system (please complete the following information)**
 - Device: MacBook Pro 2021 
 - OS: macOS
 - Browser: Chrome
 - Version: 99.x

**Comment by distantnative** [comment]
How should the system know which text file is the correct one? `album.txt` or `blood-moon.jpg.txt` could both be the real content file.

**Comment by texnixe** [comment]
Otherwise we would have to check the content file name for all possible file extensions. File meta data files are deleted automatically when a file is deleted via the Panel, so this can actually only happen when you delete files manually from the file system.

**Comment by kevinvennitti** [comment]
What about looping through all blueprints file names from `/site/blueprints` to check if any `xyz.txt` file is the content one?

**Comment by distantnative** [comment]
That would be a huge performance hit. Also as you wrote in your first post yourself, your page might actually use the default template not a dedicated one. In your example, which of the text files would relate to the default template?

EDIT: just realized that you're referring to blueprints, not templates. My answer also fits to that but your suggestion would also ignore all users that don't use blueprints/the Panel.

**Comment by kevinvennitti** [comment]
Sure: maybe this issue isn't something to work on, but this would be a warning to mention in meta data files documentation (especially for direct files manipulation)?

https://getkirby.com/docs/guide/content/files#adding-meta-data-to-your-files

When this issue happened to me, it was not that obvious: 
- The content file (`default.txt`) was still in the folder, with all data fields
- The panel did not show any fields (empty blueprint) so I can't understood why
- When I saved title modifications in the panel, nothing happened (no new file content created, no `default.txt` update)

**Comment by texnixe** [comment]
@kevinvennitti Could you please create an issue for that in the getkirby.com repo (or feel free to even create a PR with an info in that page)? Then we can close it here.

**Comment by kevinvennitti** [comment]
Done! ✅ (feel free to adjust the PR: https://github.com/getkirby/getkirby.com/pull/1707)
