### ISSUE TITLE
The organisation's readme link to the contributing guide is broken

### ISSUE THREAD

**Issue by philipmarnef** [k-next/kirby#4256]
The link to the contributing guide in [.github/profile/README.md](https://github.com/getkirby/.github/blob/7e9f2a683caf9b23622276299ea142142758c523/profile/README.md?plain=1#L27) is broken. Not sure what it should link to.

**Comment by afbora** [comment]
Thanks. I've fixed in https://github.com/getkirby/.github/commit/ebd39cb601ae4de4d53a2515216e4ebb03c6e98f
