### ISSUE TITLE
Updating content doesn't clear cache of secondary language in language-domains setup

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#4259]
## Description
I set up a page with [Using different domains for each language](https://getkirby.com/docs/guide/languages/introduction#using-different-domains-for-each-language). When the editors edit content in the secondary language, the website doesn't update because the cache is not getting cleared. Only the cache of the primary language clears.

**Expected behavior**  
That the cache of the secondary language clears when I update content in the secondary language. It would also be fine if both caches clear.

## Your setup
3.6.4

## Issues you might also be interested in:
- https://github.com/getkirby/kirby/issues/2248
- https://github.com/getkirby/getkirby.com/issues/1489

**Comment by afbora** [comment]
Doesn't work the `prefix` option for you?

````php
return [
    'debug' => true,
    'languages' => true,
    'cache' => [
      'pages' => [
        'active' => true,
        'prefix' => 'kirby'
      ]
    ]
];
````
Like in https://github.com/getkirby/getkirby.com/issues/1489#issuecomment-768551209

**Comment by mrflix** [comment]
Yes that works, thank you. Is that a workaround or how it should be done? If it's the later I'm missing it in the docs.

**Comment by afbora** [comment]
> I feel like we should document this more clearly and then close these two issues.

Yes, we'll document like [Lukas said](https://github.com/getkirby/getkirby.com/issues/1489#issuecomment-882811097).
