### ISSUE TITLE
Support for animated PNGs in the ImageMagick thumb driver

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#4272]
## Description
The cropping or resizing action on a file that is an Animated PNG results in only the first frame being manipulated and the others being ignored.

**Expected behavior**  
The Animated PNG will be cropped and resized with all frames included.

## To reproduce
Use the crop method on the following image:
![Original](https://yallayalla.moeritz.io/media/pages/images/e539839d0b-1649933497/ezgif-2-205120e8d4.png)

Results in only the first frame:
![Cropped](https://yallayalla.moeritz.io/media/pages/images/e539839d0b-1649933497/ezgif-2-205120e8d4-960x430-crop.png) 

## Your setup
**Kirby Version**  Kirby 3.6.4.

**Your system**
 - Device: MB Pro 14"
 - OS: macOS Monterey 12.3.1
 - Browser: Chrome
 - Version 100.0.4896.75 (Offizieller Build) (arm64)

**Comment by lukasbestle** [comment]
Which thumb driver do you use? The default is GDLib, which does not support reading animated images. [ImageMagick](https://getkirby.com/docs/guide/templates/resize-images-on-the-fly#configuring-your-thumbnails) should however support them.

**Comment by tobimori** [comment]
ImageMagick doesn't seem to handle Animated PNGs too, stays on first frame.

Edit: GIFs work, will be correctly handled by ImageMagick. I'll suggest to use GIFs, and this probably seems more like an ImageMagick/GDLib issue than a Kirby issue now. Thanks for your help!

**Comment by tobimori** [comment]
It seems like this very much is a kirby issue in terms of animated PNGs. In order for ImageMagick to recognize the input image file as Animated PNG, they need to be prefixed with `APNG:` - which results in the following options:

- We can read the file contents and look for the `acTL` bytes in it, and then automatically add that prefix. [see stackoverflow](https://stackoverflow.com/questions/4525152/can-i-programmatically-determine-if-a-png-is-animated)
- We can add an option that marks the image as `apng` and thus returns the prefix.

We would also need to update the `coalesce` function to respond to such filetype and/or option, as otherwise cropping and resizing would not work.

I haven't checked if transforming of animated WebP works out of the box, but transforming to does.

**Comment by tobimori** [comment]
I don't know if there's anything that speaks again passing APNG to all pngs, someone might check that.
