### ISSUE TITLE
Thumbs not generated in a custom media root

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4278]
Moved from #4276 by @andreasotto:

> `3.6.4`
> 
> As soon as the media folder is in a different location, no more images are generated either. Again, only the .jobs files are generated there. This should be easy to reproduce, e.g. with this index.php:
>
> ```
> <?php
> require 'kirby/bootstrap.php';
> 
> $kirby = new Kirby([
>     'roots' => [
>         'media'    => '/../some-other-place/media',
>     ]
> ]);
> 
> echo ($kirby)->render();
> ```
>
> The images are not generated in the media folder. (Has nothing to do with changing URLs because the /media path has been configured in the webserver and that works). The problem here is that kirby does not generate a file (only .jobs json files).

**Comment by lukasbestle** [comment]
I cannot reproduce this in the Plainkit with the code you provided.

@andreasotto Have you verified this is not caused by your custom webserver configuration for `/media`?

**Comment by texnixe** [comment]
I cannot reproduce this either.

**Comment by lukasbestle** [comment]
@andreasotto Ping for the question above
