### ISSUE TITLE
Creating pages from frontend creating draft

### ISSUE THREAD

**Issue by theamnesic** [k-next/kirby#4293]
## Description
When using the [Eventkit](https://getkirby.com/docs/cookbook/forms/creating-pages-from-frontend), the pages created are drafts instead of subpages.

**Expected behavior**  
Programmatically, `$page->createChild` should create pages instead of drafts, as explain [here](https://getkirby.com/docs/guide/content/creating-pages#creating-pages-programmatically).

**Screenshots**  
![Capture d’écran 2022-04-28 à 17 43 40](https://user-images.githubusercontent.com/242203/165791684-063a6b49-abd7-4bfe-8f67-fe6554b74c63.png)

## To reproduce
Install Eventkit (link at [the end](https://getkirby.com/docs/guide/content/creating-pages#creating-pages-programmatically).)
Subscribe to an event.

## Your setup
Tested with 3.1 and 3.6.5.

**Comment by texnixe** [comment]
This is expected behavior, not an issue. If you need a published page, you can set the `draft` property:

```
$newPage = $page->createChild([
  'slug' => 'some-page',
  'draft' => false,
  'template' => 'default'
]);
```

**Comment by theamnesic** [comment]
Sorry but the `'draft' => false,` create an `Unlisted` status, not `Public` :

<img width="889" alt="Capture d’écran 2022-04-29 à 20 17 58" src="https://user-images.githubusercontent.com/242203/166000991-c62f3d5f-a0fd-47d9-8782-01c6eb919dd3.png">

**Comment by texnixe** [comment]
You can sort the page afterwards:

```
$newPage = $page->createChild([
  'slug' => 'some-page',
  'draft' => false,
  'template' => 'default'
]);

$newPage->changeSort(1);
```

In any case, new pages should always be created as drafts (which is particularly important when creating content from user generated content).

If you want to create a listed case by default, you can use the `Page::create()` method instead and pass the `num` property:

```
$newPage = Page::create([
  'parent' => $page,
  'slug' => 'some-page,
  'draft' => false,
  'num' => 1,
  'template' => 'default'
]);
```
