### ISSUE TITLE
[3.6.5] Panel constantly reloads and logins frequently fail (unauthenticated / invalid CSRF token)

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4299]
## Description

After updating to Kirby 3.6.5, we were seeing strange Panel behavior. If you were already logged in and looking at a page, the Panel would just randomly reload the Panel page over and over. Some sections would show errors like "Unauthenticated". Some users were getting popups like "Attempt to use history.pushState() more than 100 times per 30 seconds."

Further, when trying to log in we would sometimes get errors like "Invalid CSRF Token".

Even after rolling back to Kirby 3.6.4 were still getting some wonky behavior, mostly about the login page complaining that session tokens were read-only.

What's somewhat peculiar is that I don't get this erratic behavior on our Dev server or my local setup. So, it's possible that this issue is specific to my Production setup, but I'm unsure where to even look next.

**Expected behavior**  

**Screenshots**  

https://user-images.githubusercontent.com/417182/166346461-43513a59-67c2-4f68-a844-35c886d5148a.mov
![2022-05-02 at 1 22 PM](https://user-images.githubusercontent.com/417182/166346473-0a996dc7-0ac7-4ff3-baa2-063c74a55e5e.jpg)

## Your setup
**Kirby Version**  
`3.6.5`
PHP 8.1.4 and 8.1.5

**Console output**  
None

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS
 - Browser: Safari 15.4; Microsoft Edge 101.0.1210.32

**Additional context**  
We use file-based sessions. I tried clearing out our "sessions" folder to see if that would help anything.

After reverting back to Kirby 3.6.4 _some_ Panel calls would still error out and include the following:
```
<b>Fatal error</b>:  Uncaught Kirby\Exception\LogicException: Cannot write to session &quot;1651543253.6a7dee26d03f46c0a8a9&quot;, because it is not locked in /var/www/html/kirby/src/Session/FileSessionStore.php:263
Stack trace:
#0 /var/www/html/kirby/src/Session/Session.php(373): Kirby\Session\FileSessionStore-&gt;set(1651543253, '6a7dee26d03f46c...', '4d7378aed8a740b...')
#1 [internal function]: Kirby\Session\Session-&gt;commit()
#2 {main}
  thrown in <b>/var/www/html/kirby/src/Session/FileSessionStore.php</b> on line <b>263</b><br />
<br />
<b>Fatal error</b>:  Uncaught Kirby\Exception\LogicException: Cannot write to session &quot;1651543253.6a7dee26d03f46c0a8a9&quot;, because it is not locked in /var/www/html/kirby/src/Session/FileSessionStore.php:263
Stack trace:
#0 /var/www/html/kirby/src/Session/Session.php(373): Kirby\Session\FileSessionStore-&gt;set(1651543253, '6a7dee26d03f46c...', '4d7378aed8a740b...')
#1 /var/www/html/kirby/src/Session/Session.php(493): Kirby\Session\Session-&gt;commit()
#2 [internal function]: Kirby\Session\Session-&gt;__destruct()
#3 {main}
  thrown in <b>/var/www/html/kirby/src/Session/FileSessionStore.php</b> on line <b>263</b><br />
```

**Comment by neildaniels** [comment]
I tried looking the list of changed files between `3.6.4` and `3.6.5` but I didn't see any obvious things that should cause the Panel to just full-on reload. https://github.com/getkirby/kirby/compare/3.6.4...3.6.5

**Comment by lukasbestle** [comment]
This could be related to #3981. Do you consistently only get the errors on 3.6.5? I.e. if you update again, do the errors reappear?

**Comment by neildaniels** [comment]
Yes, the second time I re-deployed 3.6.5 and got the same type of errors and wonkiness.

**Comment by ovenum** [comment]
> Yes, the second time I re-deployed 3.6.5 and got the same type of errors and wonkiness.

Had troubles in the past when deploying to hosting providers that are running nginx caching proxies in front of the actual website (domainfactory does this). They will cache requests to the panel and if more than one user is using the panel at the same time you will end up with weird Errors in the panel or can’t event login or logout. 

Maybe your panel routes got cached? Just a guess though.

**Comment by neildaniels** [comment]
I do all my deployments with a Docker container consisting of it's on Nginx, PHP, and Kirby installation, so I don't think that's quite what's going on. I know Linode won't be doing any caching of its own.

But, our caching setup (Cloudflare + Kirby-level) only exists on Production, so that's a good place for me to start trying to replicate on Dev to see if that's part of the problem.

**Comment by neildaniels** [comment]
I think I've narrowed-down the conditions that cause the problem. But it's kind of a mess. TLDR at the end.

I was able to reproduce on my Dev environment when I enabled Cloudflare's "Cache Everything" functionality.

Context:
Cloudflare has a "Page Rule" feature that enables Cloudflare to cache HTML pages, not just images/js/css. This operates on everything that does _not_ include `max-age=0`, `private`, `no-cache`, or an `Expires` header with an already expired date. https://developers.cloudflare.com/cache/best-practices/customize-cache/
- Of note: `no-store` is **not** a directive to opt-out of this caching.

Prior to Kirby 3.6.5, I would emit some `Cache-Control` with `header()` at the top of my `config.php` file. I also had a `route:before` hook that would attempt to apply special cache headers. While this hook does run for `/panel/` routes, the resulting headers wouldn't have effect, which I believe #4144 actually addressed (because they would be replaced by the headers configured in their resulting Response object). The `header()` calls at the top were put in place to work around this behavior.

Sample `config.php`:
```php
$path = Url::path();
if (Str::startsWith($path, 'api', true) || Str::startsWith($path, 'k-api', true) || Str::startsWith($path, 'panel', true)) {
    header('Cache-Control: no-store, private, no-cache, must-revalidate, max-age=0');
    header('Expires: Fri, 01 Jan 1990 00:00:00 GMT');
    header('X-Robots-Tag: noindex');
}

return [
    'hooks' => [
        'route:before' => function (Route $route, string $path, string $method) {
            $kirby = kirby();
            
            $response = $kirby->response()
            ->header('X-Frame-Options', 'DENY')
            ;
            
            $query = Url::query() ?: '';
                        
            $shouldCache =  'GET' === $method
                            && $kirby->option('cache.pages.active')
                            && !Str::startsWith($path, 'api', true)
                            && !Str::startsWith($path, 'k-api', true)
                            && !Str::startsWith($path, 'panel', true)
                            // extras paths omitted
                            ;
            
            if ($shouldCache) {
                $response
                ->header('Cache-Control', 'max-age=1800, must-revalidate') // 30 minutes (60 * 30)
                ;
            }
            else {
                $response
                ->header('Cache-Control', 'no-store, private, no-cache, must-revalidate, max-age=0')
                ->header('Expires', 'Fri, 01 Jan 1990 00:00:00 GMT')
                ;
            }
        },
    ],
];
```

What I've also realized from debugging this is that the `route:before` hook actually gets called _twice_ (both in Kirby 3.6.4 and 3.6.5). Given going to a URL such as `http://localhost/panel/login` the route hook gets invoked first with path `panel/login` and then with just `login`. I would have expected #3958 to address that, but it seemingly doesn't (unless something regressed after that).

Under 3.6.4, the fact that the route hook for Panel calls would run twice was somewhat inconsequential because the headers set in this hook were basically ignored.

Now with 3.6.5, the top-level `Cache-Control` header is actually overwritten. But because `login` runs second it actually starts emitting headers that indicate that it _should_ be cached.

I believe that the fact the hook runs multiple times is the root cause of the issue.

----

TLDR Takeways:
- Given a URL like `http://localhost/panel/login` the `route:before` hook is called multiple times, which I believe is not expected.
  - If it is expected, is there a way to check if we're dealing with "top level" routes?

Additionally:
- I think it's great that something like `Cache-Control: no-store` is included for API/Panel responses by default, but I think should be modified to return something like `no-store, private` or `no-store, private, max-age=0` to ensure max compatibility with Cloudflare.

**Comment by lukasbestle** [comment]
The `route:before` hook is indeed called for multiple routes if one of them refuses to handle the request (`NextRouteException`). For setting headers I actually recommend the `route:after` hook.

We will improve our cache header handling in 3.7.0 with #4277. Have you tried if this improves the situation for you?

Thanks for the input on CloudFlare compatibility. Do you have a link to resource(s) on that?

**Comment by ovenum** [comment]
> Thanks for the input on CloudFlare compatibility. Do you have a link to resource(s) on that?

Hello @lukasbestle from the [Cloudflare Docs](https://developers.cloudflare.com/cache/about/default-cache-behavior/)

> Cloudflare respects the origin web server’s cache headers in the following order unless an Edge Cache TTL page rule  overrides the headers.
> 
> Cloudflare does not cache the resource if the `Cache-Control` header is set to private, `no-store`, `no-cache`, or `max-age=0` or if there is a cookie in the response.
>
> Cloudflare caches the resource in the following scenarios:
> - The Cache-Control header is set to public and the max-age is greater than 0.
> - The Expires header is set to a future date.
> - If both the max-age and an Expires header are set, max-age is used.

Maybe panel routes should always set the `Cache-Control` Header to something like `no-store, private, no-cache, must-revalidate, max-age=0`, like what @neildaniels tried to do manually? 

Some hosters run caching proxies in front of PHP Application which can break the panel if multiple users use the panel at the same time. This probably needs some more investigation as to what is causing the redirect loops and CSRF validation failures. I would assume Kirby does not create a session because the request is served from a static cache (cloudflare, nginx, …)

**Comment by neildaniels** [comment]
Admittedly, when I originally set up my headers, I misunderstood the intent of `no-cache` and I probably would omit that going forward. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

@lukasbestle Even `route:after` is called twice for `panel/login` (and both are marked as `$final = true`). The order though is flipped, so `$path = 'login'` is first, then `$path = 'panel/login'`.

Because of this, it's seemingly impossible to cleanly discern between someone visiting `login` directly from the internal router also branding off `panel/` for `panel/login`.

```php
'route:after' => function (Route $route, string $path, string $method, mixed $result, bool $final) {
    echo "[$path $final]";
},

// echos: [login 1][panel/login 1]
```

**Comment by lukasbestle** [comment]
@basics09 Thanks! Currently we use `Cache-Control: no-store`, which should cover CloudFlare use cases already according to the docs you quoted, but not according to the docs @neildaniels linked. So maybe we should go with `Cache-Control: no-store, private` to cover both and also ensure compatibility with other cache software? The other values are pretty redundant with these two already in place. To be honest I'd like to keep the header as short as possible.

> Even `route:after` is called twice for `panel/login` (and both are marked as `$final = true`). The order though is flipped, so `$path = 'login'` is first, then `$path = 'panel/login'`.

@neildaniels You are right. What happens is that first the core router calls the Panel route and then the Panel router calls the actually used route. The `after` hooks are then called in reverse (first from the "inner" Panel router and then from the "outer" core router). Both routers explicitly call the router hooks. Ideally only the Panel router would fire the hooks, but it looks like our current setup doesn't allow that. By the time the Panel router gets to do its job, the `route:before` hook of the core router will already be fired.

---

**Summary:** I have updated #4277 to use `Cache-Control: no-store, private`. This should fix this issue because the custom `header()` call for `Cache-Control` is no longer needed.

**Comment by distantnative** [comment]
@lukasbestle but shouldn't our hooks only be tied to the core router? And no hooks on the Panel router?

**Comment by lukasbestle** [comment]
@distantnative Oh, I misread the code. The Panel has its own set of hooks with a `panel.` prefix:

https://github.com/getkirby/kirby/blob/005fc78fcc0e7f99f61e6973efa8ea8ec85741d9/src/Panel/Panel.php#L316-L336

So it's weird that the core hooks are called for the Panel routes as well. That's a bug then. But maybe it's already fixed by #4260.

@neildaniels Could you please check if you get the same behavior with the `develop` branch? If so, please open a separate issue on this and we'll take another look.

**Comment by ovenum** [comment]
> @basics09 Thanks! Currently we use `Cache-Control: no-store`, which should cover CloudFlare use cases already according to the docs you quoted, but not according to the docs @neildaniels linked. So maybe we should go with `Cache-Control: no-store, private` to cover both and also ensure compatibility with other cache software? The other values are pretty redundant with these two already in place. To be honest I'd like to keep the header as short as possible.

Read through the link provided by @neildaniels regarding custom Cloudflare Pagerules and rethought this.  It seems that `no-store` and `private` could be conflicting. [Reading the mdn docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) `private` allows caching in private stores (browser) whereas `no-store` does not allow caching of any type.  To just handle Cloudflares custom page rules `Cache-Control: no-store, max-age=0` will have the same effect. 

Not sure it’s the responsibility of Kirby to handle this beyond sending `no-store`, it’s already a very good choice but some providers, custom CDN setups ignore it. 

Maybe adding a note to the [Panel Troubleshooting docs](https://getkirby.com/docs/guide/troubleshooting/panel) further detailing this issue?

**Comment by neildaniels** [comment]
@lukasbestle The `develop` branch has the intended behavior and only calls the route hook for the complete `panel/login` path.

@basics09 I believe the `private` header should still be included as it correctly articulates the fact that "authenticated" calls are specific to an individual user and should never be placed in a shared cache.

Per the [Cache-Control RFC](https://datatracker.ietf.org/doc/html/rfc7234#section-5.2.1.5) the `no-store` directive will correctly apply to both private and shared caches _and_ that `no-store` alone is insufficient to ensure privacy. Emphasis mine:

> **[5.2.2.3](https://datatracker.ietf.org/doc/html/rfc7234#section-5.2.2.3).  no-store**
> 
>    The "no-store" response directive indicates that a cache MUST NOT
>    store any part of either the immediate request or response.  **This
>    directive applies to both private and shared caches.**  "MUST NOT
>    store" in this context means that the cache MUST NOT intentionally
>    store the information in non-volatile storage, and MUST make a
>    best-effort attempt to remove the information from volatile storage
>    as promptly as possible after forwarding it.
> 
>    **This directive is NOT a reliable or sufficient mechanism for ensuring
>    privacy.**  In particular, malicious or compromised caches might not
>    recognize or obey this directive, and communications networks might
>    be vulnerable to eavesdropping.

**Comment by ovenum** [comment]
@neildaniels thanks for taking the time and clarifying the `no-store` and `private` options. Looks good to me now : )

**Comment by bastianallgeier** [comment]
✅
