### ISSUE TITLE
Routes with Language Parameter are called twice if it returns false

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4305]
## Description
In a multi-language setup, if a route has a language parameter (either a default language code or simply `'*'`) and it returns false then the entire route gets invoked a 2nd time.

This happens if the default language uses the "base" URL and doesn't add its own prefix

**Expected behavior**  
I would expect there route action to only ever be called once and a 404 be immediately returned.

## To reproduce

Assume default language code of `en-us` with no URL suffix.
Assume second language code of `de-de` with URL suffix of `/de`.

```php
return [
    'routes' => [
        [
            'pattern' => 'custom/response-1',
            'action'  => function () {
                echo '[*]';
                return false;
            },
        ],
        [
            'pattern' => 'custom/response-2',
            'language' => '*',
            'action'  => function ($language) {
                echo '[*]';
                return false;
            },
        ],
        [
            'pattern' => 'custom/response-3',
            'language' => 'en-us',
            'action'  => function ($language) {
                echo '[*]';
                return false;
            },
        ],
        [
            'pattern' => 'custom/response-4',
            'language' => 'de-de',
            'action'  => function ($language) {
                echo '[*]';
                return false;
            },
        ],
    ],
];

// http://localhost/custom/response-1
// echos: [*]

// http://localhost/custom/response-2
// echos: [*][*]

// http://localhost/de/custom/response-2
// echos: [*]

// http://localhost/custom/response-3
// echos: [*][*]

// http://localhost/de/custom/response-4
// echos: [*]
```

I doubt there is a scenario where you would really want to echo out within a route, but it does illustrate that the code _is_ being invoked twice.

For the default language version, it first gets called:
https://github.com/getkirby/kirby/blob/3de403cabcd6755bdd95c159bd282ec63ec14658/src/Cms/LanguageRoutes.php#L37

Then:
https://github.com/getkirby/kirby/blob/3de403cabcd6755bdd95c159bd282ec63ec14658/src/Cms/LanguageRoutes.php#L99

Based on the docs (https://getkirby.com/docs/reference/router/responses/empty) I would expect that a 404 should be immediately returned.

## Your setup
**Kirby Version**  
`3.6.4`

**Comment by lukasbestle** [comment]
I wonder why we handle it the way we do at the moment. If the selected route returns a falsy value (which doesn't need to be `false`, there could be another scenario behind this!), we explicitly render the fallback route. But that immediately conflicts at least if really the value `false` gets returned. As you write, `false` means that the error page should be rendered.

To be honest I feel like we cannot fix this until we have answered that question of intended behavior. Otherwise we might break existing behavior.

**Comment by distantnative** [comment]
I think this is rather a mistake - just testing if `->call()` returns something but `null` - but not considering that it could also return a falsy value that then actually should be used.

Fixing this could be considered a small breaking change but I would say we should do it.

**Comment by lukasbestle** [comment]
Ah, that makes sense. 👍

**Comment by bastianallgeier** [comment]
✅
