### ISSUE TITLE
[panel] Subpages option for the pages field is currently a bit buggy

### ISSUE THREAD

**Issue by manuelmoreale** [k-next/kirby#4309]
## Description
The `subpages` option for the `pages` field is currently working a bit oddly.
There's a few things going on so I'm opening a single issue since are all related to the same thing rather than creating multiple issues.

### Issue 1: Differences in the modal layout

With `subpages : true` the modal is showing the current parent page as well as the back arrow in the left corner

![Screen Shot 2022-05-18 at 17 20 28](https://user-images.githubusercontent.com/1738077/169079279-88d4b418-723b-47dc-a768-6de357154adb.png)

With `subpages : off` the entire top part is gone leaving only the list of subpages. I think a good idea would be to maintain the top part and maybe replace the current page title with an instruction like **"select a page"**

![Screen Shot 2022-05-18 at 17 21 07](https://user-images.githubusercontent.com/1738077/169080279-fbfdc73e-dc42-4364-8243-e82be3066e9f.png)

I know this is not really a bug, more like a feedback/consideration.

The next one though I think it is a bug.

### Issue 2: Subpages are accessible even when the subpages option is set to off.

The video is pretty self explanatory and I believe it's not the intended behaviour.
Even when the `subpages`  option is set to `false` I am still able to click on the right arrow and access the subpages

https://user-images.githubusercontent.com/1738077/169082027-ef59646e-ceed-4d59-93fd-f1e38a5daad9.mov

This is the code for the section inside `site.yml`

```
mypage:
    label    : Pick a page
    type     : pages
    subpages : false
```

Now, this is **not happening** when I have a query option set. In that case I am unable to click the arrow.

### Issue 3: The right arrow is somewhat confusing

Lastly, I think the right arrow is somewhat confusing. Right now has two possible states. It's either black to indicate that a page has children or gray when the page does not have children.

It could use an hover state but I'm aware the entire panel basically doesn't have hover states.

And also I'd personally remove the arrow entirely when the subpages option is set to false since it serves no purpose at that point.

**Comment by bastianallgeier** [comment]
✅
