### ISSUE TITLE
Writer fields with `inline: true` only store first paragraph when multiple are pasted

### ISSUE THREAD

**Issue by crisgfx** [k-next/kirby#4310]
## Description
First off, sorry if someone posted this already, I couldn't find it.
If I paste something from MS Word into the writer field, only the first paragraph gets saved.

**Screenshots**  

https://user-images.githubusercontent.com/16305374/169342389-32d3787a-ca04-427f-98d3-0f0947b5bc51.mp4

## To reproduce

1. Go to About Us page of the starter kit
2. paste something from MS Word into the address field
3. Hit save
4. Reload

**Kirby Version**  
3.6.6

**Your system (please complete the following information)**
Tested with:
- Mac OSX 11.6.4, Firefox latest
- Windows 10, MS Edge latest

**Comment by lukasbestle** [comment]
Thanks for the detailed issue description. 👍

The writer field from your example [uses the `inline` mode](https://github.com/getkirby/starterkit/blob/d515908e2e773575106cc2012dd5838ac76cea6a/site/blueprints/pages/about.yml#L57), which only supports one paragraph. Does it work for you if you remove the `inline` property?

**Comment by crisgfx** [comment]
Thanks Lukas!
It works fine when I'm turning off the inline mode.
However it's still a bit confusing to see the whole text getting pasted when only the first paragraph gets saved in the end.
My client has made changes to quite a couple of fields already when he first noticed, that some content is missing.
But now that I know, I guess it's my part to take care of that.

**Comment by lukasbestle** [comment]
I agree, the current behavior is quite confusing.

## Issue Summary

### Status quo

If the user gets the `Editor` to contain multiple paragraphs (for example by pasting formatted content), a `writer` field with `inline: true` will only store the first paragraph and ignore the rest.

### Source of the issue

I think the issue is caused by this line:

https://github.com/getkirby/kirby/blob/005fc78fcc0e7f99f61e6973efa8ea8ec85741d9/panel/src/components/Forms/Writer/Editor.js#L325

It just takes the contents of the first `<p>` element and ignores the rest.

### Possible solution

We could instead use `querySelectorAll('p')` and concat the contents of all matched elements. Between the paragraphs, a `<br>` should be inserted (maybe even two?).

**Comment by distantnative** [comment]
Isn't that quite negating the purpose of inline then? I'd think you get one line from this, not faked paragraphs via breaks. So not sure that's reducing confusion, rather shifting it.

**Comment by lukasbestle** [comment]
You can already enter multiple lines in an `inline` writer and it will also generate hard breaks instead of paragraphs. So it would only be consistent if the same happens on paste.

**Comment by lukasbestle** [comment]
Thinking about it again: I think the conversion should already happen on paste, not on export. This way the UI won't jump on save/reload.

**Comment by afbora** [comment]
> We could instead use querySelectorAll('p') and concat the contents of all matched elements. Between the paragraphs, a <br> should be inserted.

@lukasbestle This solution works great. After the paragraphs are converted to `<br>` and the page is refreshed, the savebar does not appear when pasting the same text again. Do you want me to create a PR for your solution?

**Comment by lukasbestle** [comment]
@afbora Yes, that would be great. Bonus points if you find a way to do the conversion on paste. :)

**Comment by afbora** [comment]
> find a way to do the conversion on paste. :)

Do you mean instant conversion (paragraphs to breaks) on paste, not after save, right?

**Comment by lukasbestle** [comment]
If the writer field has inline mode activated, yes. :)

**Comment by afbora** [comment]
@lukasbestle I've two solutions (Only one of them needs to be merged). But I couldn't find a way to conversation on paste.

- First solution https://github.com/getkirby/kirby/pull/4350: Enclosing all paragraphs
- Second solution https://github.com/getkirby/kirby/pull/4351: Use editor's `inline*` mode

**Comment by lukasbestle** [comment]
Thanks! To be honest I don't have enough knowledge of the writer and ProseMirror to review which of the options is best or if there's another possible implementation. @bastianallgeier?

**Comment by bastianallgeier** [comment]
✅
