### ISSUE TITLE
kirby->url() adding port and wrong protocol on nginx / reverse proxy

### ISSUE THREAD

**Issue by jangoedde** [k-next/kirby#4311]
## Description

Upgrade installation on nginx / reverse proxy environment from 3.5 to 3.6.6 breaks urls.

We're running a kirby installation in a nginx / reverse proxy environment (listening to port 85).
'url' => 'HTTPS://www.domain.com' ist hardcoded in custom config file (config.www.domain.com.php).

$kirby->url() and $site->url() return 'HTTP://www.domain.com:85' while $kirby->option('url') returns 'HTTPS://www.domain.com'

So it seems like, the url option is completely irgnored since the update.

**Comment by afbora** [comment]
@jangoedde Is this related or same with #4234?

**Comment by jangoedde** [comment]
@afbora it's kind of related - but not the same.

The added port in the url broke everything in our installation.
For example: opening panel https://www.domain.com/panel redirects to https://www.domain.com:85/panel/login ... which doesn't exit.

**Comment by bastianallgeier** [comment]
✅

**Comment by jangoedde** [comment]
Do I still have to make adjustments in the config after the update or should it work "out of the box"?

At the moment the behavior hasn't changed after updating to 3.7.0.

**Comment by lukasbestle** [comment]
@jangoedde It should work out of the box. Could you please post the output of `var_dump($kirby->environment()->toArray())` (put this temporarily somewhere in any of your templates or snippets)?

**Comment by jangoedde** [comment]
```
Array
(
    [baseUrl] => http://dev.domain.de:85
    [host] => dev.domain.de
    [https] => 
    [info] => Array
        (
            [USER] => www-data
            [HOME] => /var/www
            [HTTP_COOKIE] => _pk_id.59.9359=f4a669773daf3086.1656404250.; _pk_ses.59.9359=1
            [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
            [HTTP_ACCEPT_LANGUAGE] => de-DE,de;q=0.9
            [HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
            [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
            [HTTP_CONNECTION] => close
            [HTTP_X_FORWARDED_PROTO] => https
            [HTTP_X_FORWARDED_FOR] => 111.111.111.111
            [HTTP_X_REAL_IP] => 111.111.111.111
            [HTTP_HOST] => dev.domain.de
            [SCRIPT_FILENAME] => /var/www/domain.de/dev.domain.de/index.php
            [REDIRECT_STATUS] => 200
            [SERVER_NAME] => dev.domain.de
            [SERVER_PORT] => 85
            [SERVER_ADDR] => 222.222.222.222
            [REMOTE_PORT] => 33272
            [REMOTE_ADDR] => 333.333.333.333
            [SERVER_SOFTWARE] => nginx/1.22.0
            [GATEWAY_INTERFACE] => CGI/1.1
            [REQUEST_SCHEME] => http
            [SERVER_PROTOCOL] => HTTP/1.0
            [DOCUMENT_ROOT] => /var/www/domain.de/dev.domain.de
            [DOCUMENT_URI] => /index.php
            [REQUEST_URI] => /
            [SCRIPT_NAME] => /index.php
            [CONTENT_LENGTH] => 
            [CONTENT_TYPE] => 
            [REQUEST_METHOD] => GET
            [QUERY_STRING] => 
            [FCGI_ROLE] => RESPONDER
            [PHP_SELF] => /index.php
            [REQUEST_TIME_FLOAT] => 1656404340.6772
            [REQUEST_TIME] => 1656404340
        )

    [ip] => 222.222.222.222
    [isBehindProxy] => 
    [path] => 
    [port] => 85
    [requestUrl] => http://dev.domain.de:85
    [scriptPath] => 
)
```

**Comment by lukasbestle** [comment]
@jangoedde Thank you, that was really helpful. 👍

Two things:

- Your reverse proxy doesn't set the `X-Forwarded-Host` and `X-Forwarded-Port` headers. With these (or at least with the host), Kirby will be able to detect the correct base URL when you configure an array of URLs. But this doesn't change anything when only a single fixed URL is configured.
- I just read your first post again and spotted that you write "'url' => 'HTTPS://www.domain.com' ist hardcoded in custom config file" (missed that before). This won't work at the moment as the `url` option is only respected in the main `config.php` (Kirby needs it already to load the domain-specific config file). Thinking about this again, this is a breaking change/regression we already had in 3.6.3 but didn't document. We are discussing this in the team, but for the time being you can set an array with all allowed base URLs in the main `config.php`.

**Comment by jangoedde** [comment]
@lukasbestle : thanks a lot! x-forwared-host fixed it in 2 of 3 cases :)

Unfortunately, our live environment is running in a subfolder "domain.de/subfolder" the BaseUrl is detected as "domain.de".
Until 3.6. we fixed it with adding a domain specific config with hard coded url.
Now, we added "domain.de" (if not, nginx error appeared) and "domain.de/subfolder" to allowed urls in main config, but the baseUrl remains "domain.de" - of course ...

Pretty specific constellation, i know.

**Comment by lukasbestle** [comment]
@jangoedde I'm curious because I'll be working on fixes for 3.7.1:

> Unfortunately, our live environment is running in a subfolder "domain.de/subfolder" the BaseUrl is detected as "domain.de".

Do you mean if you don't define a `url` option at all, Kirby 3.7.0 doesn't detect the subfolder and instead generates URLs based on the domain without subfolder? That would be another bug.

> Now, we added "domain.de" (if not, nginx error appeared)

Which nginx error?

**Comment by jangoedde** [comment]
@lukasbestle:

if we do not define an url in the config at all, baseUrl is HTTP://www.domain.de:PORT

if we define an url '*', baseUrl is HTTPS://www.domain.de

if we define an url 'https://www.domain.de', baseUrl is HTTPS://www.domain.de

if we define an url 'https://www.domain.de/subfolder', nginx is 500 and Kirby error is: 
`throw new InvalidArgumentException('The environment is not allowed');`
(because BaseUrl seems to detect HTTPS://www.domain.de, which does not match)

if we define both urls  'https://www.domain.de' AND 'https://www.domain.de/subfolder', baseUrl is HTTPS://www.domain.de

it took a while before we were able to reconstruct the error ...

**Comment by lukasbestle** [comment]
@jangoedde According to your environment data you posted above, Kirby is served at the domain root. Maybe your nginx reverse proxy routes `https://www.domain.de/subfolder` to `http://www.domain.de:85/`? Kirby will never be able to detect this as the original path is not passed in the request.

> if we define an url 'https://www.domain.de/subfolder', nginx is 500 and Kirby error is:
`throw new InvalidArgumentException('The environment is not allowed');`

Ah, OK. nginx returns HTTP 500 because Kirby does.

This exception should however only be thrown if multiple allowed base URLs are configured. What do you get if you define this in your main `config.php` (not in any domain-specific configs):

```php
<?php

return [
  'url' => 'https://www.domain.de/subfolder'
];
```

**Comment by lukasbestle** [comment]
@jangoedde Kirby 3.7.1 (which will be released tomorrow) will fix both issues you were having: Reverse proxies are accepted even if they don't set `X-Forwarded-Host` and you will be able to override the `url` option from domain-specific configs again. So in your main `config.php` you can define the general hosts and the domain-specific config can then define the full base URL including the subfolder.

**Comment by jangoedde** [comment]
@lukasbestle Here is an info after some tests (last also with version 3.7.2).
First of all: most of the problems have been fixed (routing in the frontend, urls, assets, ...) . However, we currently have the problem that after logging into the panel https://www.domain.de/subfolder/panel we are redirected to https://www.domain.de/panel. Attempting to access or reload this url directly means that the panel is no longer loaded...
In the individual config (config.www.domain.de.php) 'https://www.domain.de/subfolder' is also stored as the url, which basically seems to work - except in the panel.

**Comment by lukasbestle** [comment]
@jangoedde Could you please open a new issue with the following information:

- Excerpt from your main `config.php`
- Excerpt from your `config.www.domain.de.php`
- Output of `var_dump($kirby->environment()->toArray())` on that domain (can be anonymized)
