### ISSUE TITLE
Multi select mode in blocks field is triggered without click

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4319]
## Description
When I select a block, switch tabs and come back I'm suddenly in multi select mode. I think this happens because the last state the panel sees is me holding the option key for ⌘⌥→. Releasing the option key happens outside of the tab, though.

**Expected behavior**  

Multi select mode should only be triggered on click.

**Screenshots**  

![CleanShot 2022-05-27 at 17 22 26 2022-05-27 17_23_46](https://user-images.githubusercontent.com/7975568/170729991-aa735ba1-c822-4deb-92e5-e00b4bd00097.gif)

## To reproduce
1. Select a block
2. Hold the option key
3. Switch the tab
4. Switch back to the tab with the block

## Your setup
**Kirby Version**  
3.6.6

**Comment by afbora** [comment]
Not same but guess related issue https://github.com/getkirby/kirby/issues/3800

**Comment by afbora** [comment]
@medienbaecker Could you test https://github.com/getkirby/kirby/pull/4349 PR please?

**Comment by distantnative** [comment]
Which browser are you using? Cannot reproduce with Chrome on macOS as the key combinations are different.

**Comment by medienbaecker** [comment]
> @medienbaecker Could you test #4349 PR please?

I tested the PR and couldn't reproduce the issue with Chrome 102.0.5005.115 on macOS 12.3.1 anymore 👍

**Comment by distantnative** [comment]
✅
