### ISSUE TITLE
Kirby v3.6.6 is incredible slow (unusable/broken for me)

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#4322]
## Description
Since I updated to Kirby 3.6.6., my local admin panel is enormously slow and full of network issues that I can't work with it anymore. Previous versions worked fine. I cleared caches, sessions, updated PHP from v8.1.5 to v8.1.6, updated Windows 11 and tried other things. It looks like this Kirby release is faulty; not my local setup :/.

**Expected behavior**  
No performance/network issues.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/6271057/170817908-18304fcb-3eaf-4e4b-936e-de61919a7846.png)

## To reproduce
It happens on any site, e. g. regardless if I navigate to the system page, try to add a new draft or if I try to load an existing page.

## Your setup
**Kirby Version**  
v3.6.6

**Console output**  

**Your system (please complete the following information)**
Windows 11, latest Firefox, PHP 8.1.6, Apache2 webserver (wampserver v3.2.8, x64)

**Additional context**  
- only one plug-in (to create a comments directory on page creation)
- multilang site with 1 language only
- didn't happen with previous Kirby 3 versions
- happens since multiple Firefox versions so doesn't seem to be a browser issue

Config (indentation wrong due to GitHub, it's fine in my original file):

```
return [
    'debug'  => true,
	'languages' => true,
	'markdown' => [
		'extra' => true
	],
	'api' => [
		'basicAuth' => true,
		'allowInsecure' => true
    ],
	'hooks' => [
		'page.create:after' => function ($page) {
			if($page->template()->name() == 'article') {
				$comment = $page->createChild([
                    'slug'     => 'comments',
                    'template' => 'comments',
                    'content'  => null,
					'draft'	   => false
                ]);
			$page->update(['Children' => Yaml::encode($page->childrenAndDrafts()->toArray())]);
			}
        }
	]
];
```

**Comment by distantnative** [comment]
Do you have the same issues with a fresh starterkit?

**Comment by GiantCrocodile** [comment]
Hi @distantnative. Thank you for your quick response. I just tried it: Not at all. The starterkit-main just runs very fast (beside a bit lower loading time for some of the images in a page but I think that's due to the size of the example pics). Could this be related to some specific field type in my blueprints? On the other hand, even the system page is slow and I think there's no customer-specific content loaded at all, right?

**Comment by afbora** [comment]
Any chance you can share a testable copy of your app?

**Comment by GiantCrocodile** [comment]
I tried to send you an email with a zip attachment but your getkirby-email-server/forwarder denies my email. Can I send it to somewhere else?

**Comment by afbora** [comment]
You can upload to your server and share the link via email.

**Comment by afbora** [comment]
I got the files from @GiantCrocodile and tested it. This issue seems to be related to Clemens local setup. I'm closing for now. When we find a more concrete lead, we can reopen and will review the issue again..

**Comment by GiantCrocodile** [comment]
Issue seems to be related to wampserver or php8.x of wampserver. I updated to wampserver 3.29 and PHP8.1.7 and the issue still occurs. I hope this gets fixed soon. It's annoying.
