### ISSUE TITLE
A::append not working as expected for non-associative arrays

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4345]
## Description
The toolkit function `A::append` doesn't do what I would expect it to do, or what its name or docs would suggest: append one array to another. 
Currently it appends only array items whose key is not defined in the original array; this is problematic when the array isn't associative. 

```php
A::append(['a','b','c'], ['d','e','f']); // currently returns ['a','b','c']
```

**Expected behavior**  
```php
A::append(['a','b','c'], ['d','e','f']); // expected ['a','b','c','d','e','f']
```

## Your setup
**Kirby Version**  
3

**Comment by afbora** [comment]
We use `+` operator on `A::append` method that do actually merge. I think we need to use `array_push` for append. Something like that:

````php
public static function append(array $array, array $append): array
{
    array_push($array, ...$append);
    
    return $array;
}

````

**Comment by lukasbestle** [comment]
It's a bit difficult unfortunately. The current implementation only works with associative arrays while your implementation @afbora only works with non-associative arrays. We need an implementation that works with both, otherwise it would be a breaking change.

The huge problem: There can be arrays with mixed key types. How should they be treated?

**Comment by distantnative** [comment]
@lukasbestle My first answer would be that mixed types shouldn't be supported. I don't see any logical result that could be expected. So maybe there is a way how we could check for mixed and throw an error.

**Comment by afbora** [comment]
I agree with Nico. I think the method should determine how to append behavior (array_push or union `+`) based on the first index of the array.

**Comment by lukasbestle** [comment]
How would we even check whether an array is associative? I mean we have `A::isAssociative()`, but that returns `true` if a single key is non-numeric and it returns `false` for numeric string keys. For `A::append()`, every single key matters, otherwise the returned result will be inconsistent (with int and string keys being treated differently).

**Comment by afbora** [comment]
It doesn't make sense to check the items of the mixed array one by one and throw an error. I think it is best to determine the behavior according to the first `$array`.

````php
public static function append(array $array, array $append): array
{
    if (A::isAssociative($array) === false) {
        array_push($array, ...$append);
    
        return $array;
    }
        
    return $array + $append;
}

**Comment by rasteiner** [comment]
Doesn't `array_merge` essentially do what `A::append` is meant to do? 
https://onlinephp.io/c/f40a0

`array_merge` always appends numeric keys (despite its name - it doesn't "merge" them). It merges associative arrays though. 
The difference (besides for numeric keys) to the current `A::append` is that for identical string keys it keeps the right-hand side, while the `+` operator keeps the left-hand side. 
So simply changing it to `array_merge` would be a breaking change of not documented behavior (the docs don't explicitly state how identical keys are merged).

If you want a non breaking change, an approach would be looping through the second array:
```php
    public static function append(array $array, array $append): array
    {
        foreach($append as $key => $value) {
            if(is_int($key)) {
                $array[] = $value;
            } else {
                if(!isset($array[$key])) {
                    $array[$key] = $value;
                }
            }
        }
        return $array;
    }
```

**Comment by lukasbestle** [comment]
That makes me think: Isn't this exactly what `A::merge()` does? It doesn't use PHP's `array_merge()` function, but the behavior is the same while adding the flag to customize the behavior.

**Comment by bastianallgeier** [comment]
✅
