### ISSUE TITLE
`Environment::sanitizeHost()`: No support for multibyte characters?

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4353]
## Description

`EnvironmentTest::testSanitize()` fails on my local machine:

```txt
1) Kirby\Http\EnvironmentTest::testSanitize with data set #1 ('HTTP_HOST', 'öxample.com', 'öxample.com')
Failed asserting that null is identical to 'öxample.com'.

kirby/tests/Http/EnvironmentTest.php:1225
```

I traced it down to this line:

https://github.com/getkirby/kirby/blob/e8122b8762a8f11e1ba6a6fe9f9b22dd32a895d8/src/Http/Environment.php#L868

If I replace it with `mb_strtolower` or `Str::lower()`, the test succeeds.

## Open question

Can host headers ever actually contain Unicode characters like the `ö` in the test example? Or wouldn't the headers rather use Punycode encoding (in this example: `xn--xample-vxa.com`)?

Depending on the answer to that question, we should either replace the test case or modify the code.

**Comment by distantnative** [comment]
Even if they use Punycode encoding, replacing the method wouldn't do harm, right @lukasbestle? 

PS: I'd love to have these local errors gone 😍

**Comment by lukasbestle** [comment]
Probably, yes. 👍

**Comment by distantnative** [comment]
I would just do it then
