### ISSUE TITLE
[3.7.0-rc.1] Same border radius for parent/child elements

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4363]
## Description

Sorry about the nitpicky issue but I noticed something about the UI update in 3.7.0 — the `border-radius` in particular. When using rounded corners for parent/child elements it looks a lot better to gradually increase/decrease the size than to use the exact same `border-radius`. Otherwise you get ugly edges.

I'd suggest introducing `var(--border-radius-large)` and `var(--border-radius-small)` for dialogs/tags and every other nestable element:

<img alt="CleanShot 2022-06-14 at 14 54 12@2x" src="https://user-images.githubusercontent.com/7975568/173582764-dde03c28-eae3-4411-8906-e9ec6deb31f1.png">
<img alt="CleanShot 2022-06-14 at 15 19 52@2x" src="https://user-images.githubusercontent.com/7975568/173587119-71203f3b-5ae8-497d-89f8-85de5b6decdf.png">

**Comment by bastianallgeier** [comment]
Totally fine to be nitpicky here. I constantly switched between more rounded borders and a smaller radius for tags. Within the input they look shit with the larger ones, but we also use them in the field previews for tables for example, where they look a lot better. But I guess the correct version here is to go for the better look for inputs. 

I like the idea to solve this via two variables.

**Comment by bastianallgeier** [comment]
✅
