### ISSUE TITLE
[3.7.0-rc.1] Sorting pages in panel via drag&drop no longer works 

### ISSUE THREAD

**Issue by FynnZW** [k-next/kirby#4364]
## Description
Sorting pages in the Panel no longer works.
Sorting via selectbox still works.
 
## To reproduce
1. Open Panel
2. Sort a page by drag&drop
3. Error pops up: `this.$api.pages.status is not a function`

## Your setup
**Kirby Version**  
3.7.0-rc.1

**system**
 - Device: Mac
 - OS: macOS
 - Browser: Chrome
 - Version: 102

**Comment by distantnative** [comment]
Will be fixed in RC2 ✅
