### ISSUE TITLE
Files according to health check not found in 3.7.0-rc.1

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#4365]
## Description
Firefox's browser console throws error about missing files. This might be true for some of the files but site.yml in blueprints folder is there.

I'm not sure this HTTP call for localhost makes sense the way it is done if it wants to check for the existence of a local file on the filesystem.

**Expected behavior**  
No error.

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/6271057/173635081-a32cc216-cbaa-45b6-b259-e9186c0a030c.png)

![grafik](https://user-images.githubusercontent.com/6271057/173635204-fd44461c-1de8-431a-a23a-543b3754c3bb.png)

## To reproduce

1. Go to http://localhost/kirby/panel/system
2. See browser console for errors

## Your setup
**Kirby Version**  
3.7.0-rc.1

**Console output**  
see above

**Your system (please complete the following information)**
 Windows 11 setup with WAMP

**Comment by afbora** [comment]
This is an intended behavior that controls/checks the accessibility of files. There should be info texts before and after like following. Doesn't it show up for you?

> Running system health checks for the Panel system view; failed requests in the following console output are expected behavior.
> ...
> System health checks ended.

**Comment by GiantCrocodile** [comment]
I see; I was surprised it doesn't find the file(s). Yep, makes sense now and I found out why the info texts were not displayed; I filtered for error and warning by default because I didn't expect Kirby to throw useful info messages (because nearly no application does ...). Looks fine to me:

![grafik](https://user-images.githubusercontent.com/6271057/173636830-19701292-1041-4f3d-97cf-7f1c1d00c1af.png)

**Comment by lukasbestle** [comment]
@GiantCrocodile These files aren't (and shouldn't) be accessible via HTTP as the `.htaccess` configuration blocks access. If they were accessible, the Panel would warn you.

**Comment by GiantCrocodile** [comment]
@lukasbestle Yep, I see and makes sense. I think that's why it's a HTTP(S) call and not a local lookup . . . I think my issue was that I thought it tells you it's there but not accessible (not finding it made me suspect either it checks wrong file or I have some issue in my filesystem). Btw. is it intended that the onclick URLs for the warnings do not work (yet)?

**Comment by lukasbestle** [comment]
Yes, we will set up redirects for them with the release.
