### ISSUE TITLE
[3.7.0-rc.1] kirbytextinline() helper triggers deprecation notice

### ISSUE THREAD

**Issue by thathoff** [k-next/kirby#4366]
## Description
When using the kirbytextinline() helper method the deprecation notice for $inline parameter is triggered.

**Expected behavior**  
kirbytextinline() should work as before

## Your setup
Kirby 3.7.0-rc.1

**Comment by afbora** [comment]
### Summary

`bool $inline` param should be removed and use `$data['markdown']['inline']` in `kirbytextinline()` and  `kti()` functions.

**Comment by distantnative** [comment]
Will be fixed in RC2 ✅
