### ISSUE TITLE
[3.7.0-rc.1] Panel ignores port configured in config

### ISSUE THREAD

**Issue by thathoff** [k-next/kirby#4367]
## Description
When using a non standard port in the `url` option inside `config.php`  the panel does not load.

The console logs:
```
Failed to execute 'pushState' on 'History': A history state object with URL 'http://localhost/panel/installation' cannot be created in a document with origin 'http://localhost:8090'
```

The detection in the new Environment class seems to work since `$kirby->environment()->url()` returns the right path.

**Comment by lukasbestle** [comment]
Might be a frontend issue. Somewhere in the chain, the port seems to be dropped.

**Comment by bastianallgeier** [comment]
I think I found the reason and it should be fixed with the new RC. Could you test and reopen if it still happens?

**Comment by thathoff** [comment]
It works with RC 2 👍
