### ISSUE TITLE
[3.7.0-rc.1] Upload icon missing from files section

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4368]
## Description
The upload icon has been replaced with a plus icon. I guess this was a mistake?

<img width="210" alt="CleanShot 2022-06-14 at 21 24 50@2x" src="https://user-images.githubusercontent.com/7975568/173673177-965d3a2f-f32b-434b-8f60-2a276ebbd45f.png">

**Expected behavior**  
The upload icon should be shown like in earlier releases. This way there's a visual distinction between selecting and uploading files (files section vs files field).

<img width="210" alt="CleanShot 2022-06-14 at 21 24 27@2x" src="https://user-images.githubusercontent.com/7975568/173673183-dfd5e8dd-539a-4fc6-bc2d-c62feea2e493.png">

## To reproduce

1. Add a files section
2. Look at the icon

## Your setup
**Kirby Version**  
3.7.0-rc.1

**Comment by afbora** [comment]
This appears to be the case because the pages and files sections are combined into a common component as `ModelsSection.vue` and this is related commit https://github.com/getkirby/kirby/commit/d39f3521e18135b99fe329b6d3669a8be4463963

Pinging @distantnative to ask is this mistake or intended?

**Comment by distantnative** [comment]
Mistake!

**Comment by distantnative** [comment]
Will be fixed in RC2 ✅
