### ISSUE TITLE
[3.7.0-rc.1] Clicking on empty pages sections does not open modal

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4369]
## Description
Clicking on empty pages sections does no longer open the page creation dialog, even though it's using the `pointer` cursor.

**Expected behavior**  
The page creation dialog should be triggered. It did so in previous versions.

## To reproduce

1. Add a pages section, doesn't matter which layout you use
2. Try to click on the dotted area

## Your setup
**Kirby Version**  
3.7.0-rc.1

**Console output**  
No errors in the console.

**Your system (please complete the following information)**
 - OS: macOS 12.3.1
 - Browser: Chrome 
 - Version: 102.0.5005.115

**Comment by medienbaecker** [comment]
I just found out it also applies to _files_ sections.

**Comment by distantnative** [comment]
Will be fixed in RC2 ✅
