### ISSUE TITLE
[3.7.0-rc.1] Several UI issues with the table layout

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4374]
## Description
I love the new table layout for pages sections. However I noticed a few UI issues that I try to collect here.

![CleanShot 2022-06-14 at 23 06 19@2x](https://user-images.githubusercontent.com/7975568/173689197-d774f82b-ffbc-4c98-a020-adad71277035.png)

1. The index number is not flipped when using `flip: true` — the pages are. It should always display the actual page index number, just like the status dialog.
2. The table headers are not vertically centered. This might be related to the different system fonts and unfortunately unsolvable.
3. Thankfully the status circle should be easy to vertically align by setting `.k-button` to `display: flex` and `align-items: center; justify-content: center`.
4. The images are cut off on the right — probably because of the border.
5. The mobile version <= 1040px hides every single field including the title. The title should never be hidden because the pages become inaccessible without the title.

**Comment by medienbaecker** [comment]
Adding to the last point: the fact that pages are only accessible by clicking the link in the title field is generally not great, especially on touch devices. The structure field is visually and technically identical, it's also using the table component. There you can click on the full row.

While the Panel does a great job with large enough click areas pretty much everywhere else, the link in the pages table is too small. In my opinion you should at least make the whole cell clickable.

<img width="415" alt="CleanShot 2022-06-14 at 23 29 19@2x" src="https://user-images.githubusercontent.com/7975568/173692498-2381dc55-22df-4abd-a62c-90d20fec7683.png">

**Comment by distantnative** [comment]
@medienbaecker Please don't bundle too many things into one issue - this makes it much harder to tackle them (creates the burden to solve everything all at once). Better to keep it one thing at a time to make issues actionable.

Keeping this issue for
- [ ] table headers are not vertically centered
- [x] images are cut off on the right — probably because of the border.

No 3 should be solved when https://github.com/getkirby/kirby/issues/4377 is.

And then:

- #4386
- #4387
- #4388

**Comment by bastianallgeier** [comment]
We decided that we really cannot do much about the font issue. The other parts have either been solved or have their own ticket.
