### ISSUE TITLE
[3.7.0-rc.1] It is no longer possible to change the sorting of pages using drag & drop

### ISSUE THREAD

**Issue by Werbschaft** [k-next/kirby#4378]
In Kirby 3.7 it is no longer possible to change the order of pages using drag & drop. This happens regardless of the layout or the new search function. It happens in my main instance due to an update and also in a new starter kit.

As soon as you want to move the page using drag and drop, an error dialogue appears.

<img width="652" alt="Bildschirmfoto 2022-06-15 um 12 42 01" src="https://user-images.githubusercontent.com/2178466/173809336-775fab9b-526b-453a-9f90-17e40aff680a.png">

**Comment by afbora** [comment]
Thanks for report. This is known issue as #4364

**Comment by Werbschaft** [comment]
Sorry, have not seen this
