### ISSUE TITLE
[3.7.0-rc.1] New security option leads to non-existent links

### ISSUE THREAD

**Issue by Werbschaft** [k-next/kirby#4379]
The new view with security has incorrect links deposited.

- Debugging goes to https://getkirby.com/security/debug and results in a 404
- HTTPS goes to https://getkirby.com/security/https and results in a 404

There may also be other links that are incorrect. Unfortunately, I have not found the corresponding links in the core.

<img width="1438" alt="Bildschirmfoto 2022-06-15 um 12 48 38" src="https://user-images.githubusercontent.com/2178466/173809937-7a8490f1-87ee-428d-b828-7d8df48e3672.png">

**Comment by afbora** [comment]
Thanks for report 👍 We know this situation. Since it is now RC, our document page has not been completed yet. The links will work when we release the stable version.
