### ISSUE TITLE
[3.7.0-rc.1]   Error 500 after update: PHP Fatal error:  Cannot redeclare e()

### ISSUE THREAD

**Issue by wdebusschere** [k-next/kirby#4381]
## Description
After update:

PHP Fatal error:  Cannot redeclare e() (previously declared in /var/www/html/sitename/vendor/illuminate/support/helpers.php:108)

## Your setup
**Kirby Version**  
3.7.0-rc.1

**Additional context**  
2 plugins: [afbora/blade](https://getkirby.com/plugins/afbora/blade) and [pedroborges/meta-tags](https://github.com/pedroborges/kirby-meta-tags)

**Comment by distantnative** [comment]
It seems like one of your composer dependencies is registering a global function with the same name as Kirby's core functions (`e()`). Before 3.7, other libraries would just overwrite Kirby's functions which could lead to problems that were really hard to debug (not knowing why that function suddenly would behave differently). 

So from 3.7 onwards, you need to set the constant `KIRBY_HELPER_E` to `false` if you want to allow another library/code to define their `e()` function and not Kirby its own.

**Comment by wdebusschere** [comment]
Caused by https://github.com/afbora/kirby-blade/issues/20
