### ISSUE TITLE
TextSelection endpoint not pointing into a node with inline content (doc)

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4383]
On http://sandbox.test/panel/pages/notes+in-the-jungle-of-sumatra

I get a console warning

```
TextSelection endpoint not pointing into a node with inline content (doc)
```

from vendor.js:12

**Comment by afbora** [comment]
I guess, related with new changes:

### prosemirror-state 1.4.0 (2022-05-30)
### bug fixes
> Creating a TextSelection with endpoints that don't point at inline positions now emits a warning. (It is technically an error, but crashing on it might be too disruptive for some existing setups.)

https://prosemirror.net/docs/changelog/

**Comment by bastianallgeier** [comment]
@distantnative how do you get that? I cannot reproduce it.

**Comment by afbora** [comment]
Just enter `Exploring the universe` page in starterkit

![image (4)](https://user-images.githubusercontent.com/3393422/174795996-0eb6c56c-b19a-44a2-8ecc-f54989f726eb.png)

**Comment by distantnative** [comment]
Exactly, in chrome

**Comment by bastianallgeier** [comment]
Oh, it seems not to be an issue in Firefox. Weird.

**Comment by afbora** [comment]
I can see this console warning for Firefox 🤔

**Comment by bastianallgeier** [comment]
✅
