### ISSUE TITLE
[3.7.0-rc.1] Date field with time - UI improvement

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4384]
<img width="409" alt="Screen Shot 2022-06-15 at 19 45 44" src="https://user-images.githubusercontent.com/3788865/173891908-21f614e5-76af-4a33-891f-0246ef9129ac.png">

I would suggest not to have rounded corners at the intersection of both inputs

**Comment by distantnative** [comment]
Actually that'd be quite too hard when they are aligned side-by-side

**Comment by lukasbestle** [comment]
An option could be to put the `border-radius` on the `k-date-field-body` instead of the inputs. But I'm wondering: Other fields don't seem to have rounded corners at all, why the date inputs?

**Comment by distantnative** [comment]
@lukasbestle all/most fields have rounded corners in 3.7 

![image](https://user-images.githubusercontent.com/3788865/174162804-b6a7dc87-0ddc-4946-bdcb-55768aa94b4e.png)

**Comment by distantnative** [comment]
And I think it could get messy when using the inputs separate then if you just style the field body. I'd leave it as is.

**Comment by lukasbestle** [comment]
You are right, I somehow had a weird intermediate state of dist files locally. Now after resetting to `develop`, all fields have rounded corners as intended.

> And I think it could get messy when using the inputs separate then if you just style the field body. I'd leave it as is.

We could still have rounded corners for the inputs, but add a rule to the `DateField` that then removes the rounded corners on the inputs again when they are used inside the field.

**Comment by lukasbestle** [comment]
For reference, it would look like this:

![Vertical layout](https://user-images.githubusercontent.com/1595007/174274591-edd2857b-b991-42b6-acf4-7e5834bd90a0.png)
![Horizontal layout](https://user-images.githubusercontent.com/1595007/174274593-155b463c-e3cf-40c5-b537-b92c6fae2150.png)

**Comment by lukasbestle** [comment]
Oh wait. We can't actually do this because it would need `overflow: hidden`. But then the pickers will be cut off.
