### ISSUE TITLE
[3.7.0-rc.1] Cursor pointer on empty sections that not creatable

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4389]
Cursor pointer on empty sections that not creatable (`create: false` or listed or unlisted) This issue not exists on 3.6.x

I just found [why empty box rendered as button](https://github.com/getkirby/kirby/blob/3.7.0-rc.1/panel/src/components/Layout/Empty.vue#L42) (`k-empty` has `@click.stop` event).

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/4372#issuecomment-1155681876_

**Comment by bastianallgeier** [comment]
✅
