### ISSUE TITLE
[3.7.0-rc.1] URL with params redirect to error page

### ISSUE THREAD

**Issue by jonasfeige** [k-next/kirby#4394]
A URL like this: `website.test/view:list` worked as expected in `3.6.6` and directed to the homepage, making the `view` param accessible.

In `3.7.0-rc.1.` the same URL redirects to the error page.

**Comment by afbora** [comment]
I just tracked down the issue and seems this issue related with https://github.com/getkirby/kirby/pull/4285 PR and especially https://github.com/getkirby/kirby/commit/b83c0b1fb795c02748cf955d4a13156ed58b6109 commit. I'm not sure about the solution 🤷‍♂️

**Comment by bvdputte** [comment]
I experience the same issues, this is a serious regression!

**Comment by bastianallgeier** [comment]
✅
