### ISSUE TITLE
[panel] Password reset by code: Back button is broken

### ISSUE THREAD

**Issue by FynnZW** [k-next/kirby#4397]
## Description
On the panel login, after the clicking "forgot your password?" the view is stuck on  the code challenge input.
Clicking 'back' does not switch back to password input.

The route `/logout` gets fetched, responds with a 302 to login and does not have an effect.

**Expected behavior**  
Clicking 'back' should return to the default email & password form.
This should happen even while the code challenge is still active.

## To reproduce

1. Go to /panel
2. Click on 'forgot your password?'
3. Click 'back'
4. Nothing changes, even after the challenge has timed out. The only workaround is to delete the `kirby_session` cookie

## My setup
**Kirby Version**  
3.6.6

**System**
 - OS: macOS, iOS 15.1 
 - Browser: Chrome 102, iOS Safari 15.4 

**Config**  
```php
return [
  'auth' => [
    'methods' => ['password', 'password-reset'],
    'challenge' => [
      'timeout' => 10 * 60, // 10 minutes
      'email' => [
        'from'     => 'me@example.com',
        'fromName' => 'Example',
        'subject'  => 'Login code'
      ]
    ]
]
```

**Comment by afbora** [comment]
I think this is same or related issue with #4087

**Comment by lukasbestle** [comment]
It's related but not the same since it also happens before the timeout. But it certainly makes sense to tackle both together.

**Comment by afbora** [comment]
✅
