### ISSUE TITLE
[Panel] Empty file upload fields not visually clear enough marked as non-translatable

### ISSUE THREAD

**Issue by renestalder** [k-next/kirby#4398]
## Description
This is a matter of user experience. When an image field with upload capability is empty and is marked as `translate: false`, the field looks visually the same in other languages, except for the “Add” button being missing.

It currently shows the `cursor: pointer` and that is misleading.

**Expected behavior**  
The file field makes it visually clear that it is not broken, but that the upload is disabled. This could be `cursor: not-allowed` and any other form of visual indication when hover over the drop-in box (the dashed box where the files would be listed).

**Screenshots**  
![Screenshot from 2022-06-20 14-23-15](https://user-images.githubusercontent.com/105358/174600850-38f6c91c-8666-439c-8520-3a3ac1fa7f12.png)

_Field of `type: files` in a secondary language. Looks the same and the pointer cursor is visible, even though the click will not work_

## To reproduce

1. Add a field of type `files` to your blueprint and set it to `translate: false`
2. Keep it empty and switch to a secondary language in the Kirby panel
3. Check the visual difference of the field between the main language and the secondary language.

## Your setup
**Kirby Version**   
3.6.6 

**Console output**  

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: Any
 - Browser: Chrome
 - Version: Latest

**Additional context**  

The issue came up because a customer of mine reported a bug in the CMS, that they are not able to upload images. After I checked and didn't find an issue, they sent me a video where I noticed they are in the second language. And also noticed, they do everything right and the field is the misleading part.

I believe ultimately the issue could and should be solved for all fields more clear by introducing an error toast message or similar, that is display every time the user tries to interact with a field that is marked as non-translatable in the current language. A message that tells them why they can't interact with it. That would be the best solution I see for everything, as even though I can't interact with the fields and it might be visually marked, there is still no explanation what's happening currently. And that is not clear at all for most users.

**Comment by manuelmoreale** [comment]
This is probably related to #4306

**Comment by distantnative** [comment]
Can confirm, this is a duplicate of https://github.com/getkirby/kirby/issues/4306 (bug has same cause).

Regarding the error toast messages for interacting with non-translatable fields, please open a feature request at https://kirby.nolt.io if that's still of your interest, @renestalder .
