### ISSUE TITLE
Text jumps during drag/sorting

### ISSUE THREAD

**Issue by manuelmoreale** [k-next/kirby#4400]
## Description
The title of the item inside a pages section jumps left during drag.
Video should be self explanatory. It's probably just a simple CSS issue

**Screenshots**  

https://user-images.githubusercontent.com/1738077/174623027-14acd1a4-6855-4de8-9397-61034c607196.mp4

**Comment by bastianallgeier** [comment]
Is that a new effect or does it really only appear since 3.7.0-rc.1?

**Comment by afbora** [comment]
@bastianallgeier No, already exists in 3.6.6

**Comment by manuelmoreale** [comment]
@bastianallgeier honestly only noticed while starting a new project on 3.7.0 that's why I assumed it was related to the RC. Thanks @afbora for checking

**Comment by afbora** [comment]
### Summary 

We have `dir` attribute on `div` wrapper of panel. But cloned item outside of the wrapper when drag start. So following margin style doesn't effect to item title:

https://github.com/getkirby/kirby/blob/3.6.6/panel/src/components/Layout/Item.vue#L223

**Comment by medienbaecker** [comment]
This is probably related: the `cards` layout items also have some weird style changes while dragging:

<img width="686" alt="CleanShot 2022-06-24 at 13 32 43@2x" src="https://user-images.githubusercontent.com/7975568/175526347-5964f9a7-bae9-4cf9-871a-5abf78a25851.png">

**Comment by afbora** [comment]
✅
