### ISSUE TITLE
Closing `</source>` tag in `<picture>` element with `markdown.extra`

### ISSUE THREAD

**Issue by helllicht** [k-next/kirby#4406]
## Description
Kirby adds a closing `</source>` tag inside a `picture` element when `markdown.extra` is `true`.

**Screenshot**
![kirby-picture-bug](https://user-images.githubusercontent.com/3918898/174785344-93a8bd13-677d-4c0c-940b-5b36acabf6ee.png)

## To reproduce
- Manually add a `<picture>` element with `source` in a panel `textarea` field, see code below for an example
- Set `markdown.extra => true` in `config.php`
- Fetch content in the template via `$page->text()->kt()`

**Example panel field**
```yml
fields:
  text:
    type: textarea
```

**Example field content**
```html
Some Text

<picture><source srcset="https://via.placeholder.com/800x600.webp 1400w" sizes="100vw" type="image/webp"><img src="https://via.placeholder.com/800x600.jpg" alt=""></picture>
```

## Setup
- Kirby plankit v3.6.6
- PHP 8
- OS: macOS 12.4
- Browsers: Latest stable Chrome, Latest stable Firefox

**Additional context** 
[Validator](https://validator.w3.org) says: "Error: Stray end tag source."

**Comment by afbora** [comment]
@helllicht Can you share how you use it in textarea field (directly markdown codes) to test it please?

**Comment by helllicht** [comment]
@afbora You're right! Added some example code in the description for easier reproduction. Hope that helps.

**Comment by afbora** [comment]
I can reproduce the issue with `picture > source`, `audio > source` and `video > source`. So generally related with nested tags with void elements.

But seems this issue related with parsedown library. I'm not sure that we can fix it 🤔

**Comment by lukasbestle** [comment]
Parsedown Extra uses PHP's `DOMDocument` class to parse and output the markup. Seems like `DOMDocument` doesn't know about the `source` element and its void nature. Or maybe Parsedown doesn't tell it that we target a HTML5 output, so it uses XHTML mode.

It may help to manually self-close the `source` tag as if it was XHTML:

```html
Some Text

<picture><source srcset="https://via.placeholder.com/800x600.webp 1400w" sizes="100vw" type="image/webp" /><img src="https://via.placeholder.com/800x600.jpg" alt=""></picture>
```

**Comment by afbora** [comment]
As far as I have looked the Parsedown codes, it seems a little difficult to solve this on the Parsedown side. IMO @lukasbestle solution is ideal 💯 

Also here was the related idea/issue about quitting Parsedown: https://github.com/getkirby/kirby/issues/1961

**Comment by helllicht** [comment]
> Parsedown Extra uses PHP's `DOMDocument` class to parse and output the markup. Seems like `DOMDocument` doesn't know about the `source` element and its void nature. Or maybe Parsedown doesn't tell it that we target a HTML5 output, so it uses XHTML mode.
> 
> It may help to manually self-close the `source` tag as if it was XHTML:
> 
> ```
> Some Text
> 
> <picture><source srcset="https://via.placeholder.com/800x600.webp 1400w" sizes="100vw" type="image/webp" /><img src="https://via.placeholder.com/800x600.jpg" alt=""></picture>
> ```

Good suggestion, but unfortunately this doesn't work – it's only moving the `</source`> tag directly after the opening tag:

```html
<picture><source srcset="[https://via.placeholder.com/800x600.webp 1400w](https://via.placeholder.com/800x600.webp)" sizes="100vw" type="image/webp"></source><img src="https://via.placeholder.com/800x600.jpg" alt=""></picture>
```

**Comment by lukasbestle** [comment]
Could you please try if it works if you put the following in line 580 of `kirby/dependencies/parsedown-extra/ParseDownExtra.php`:

```php
$DOMDocument->loadHTML('<!DOCTYPE html>' . $elementMarkup);
```

It should also work with your original example.

**Comment by helllicht** [comment]
@lukasbestle Just tried it, unfortunately does't change anything in the outcome…

**Comment by lukasbestle** [comment]
Then I'm afraid this is an issue with the PHP `DOMDocument` class. It just seems to lack proper support for HTML5. :(

There is an [extended `HTML5DOMDocument` library](https://github.com/ivopetkov/html5-dom-document-php), but I'm not sure about its performance impact and stability.

So to be honest I feel like we cannot solve this directly in Kirby. What you could do is the following:

- Create a plugin that loads the `HTML5DOMDocument` library.
- From the plugin, register a Kirby `markdown` component.
- This component would then load a custom extended version of `ParsedownExtra` that uses this `HTML5DOMDocument` library.

Alternatively you can make your `markdown` component use a totally different Markdown implementation. In https://github.com/getkirby/kirby/issues/1961 we have collected some candidates.
