### ISSUE TITLE
[3.7.0] Info field height taller than other fields

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4408]
## Description
The new layout increased the info field height. It's now larger than other fields. 

**Expected behavior**  
In previous Kirby versions the Info field had the same height as other fields. It's nit picking, I know, but the old look made the screenshotted use case nicer to look at, IMHO. 

**Screenshots** 
3.7:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/6684137/174819489-116f638f-ed5a-40df-9dad-e205e147acfc.png">
3.6:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/6684137/174820053-f2743bad-61a8-4dc1-9b0f-d25e94231cb8.png">

**Comment by distantnative** [comment]
@bastianallgeier Is it actually intended that the left darker border is gone too?

**Comment by bastianallgeier** [comment]
✅
