### ISSUE TITLE
[3.7.0] Plugins with no homepage should not fallback to getkirby.com

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4409]
## Description
In the panel System view, all plugins now link somewhere. Those that don't have a `homepage` setting in composer.json fall back to `getkirby.com/plugins/...`. This is kind of a big assumption. I often add functionality to individual sites with plugins that aren't public and don't have a homepage. Adding a link to getkirby.com will just result in 404 errors.

**Expected behavior**  
Plugins without homepage should not be presented as links. IMHO

**Screenshots**  
<img width="234" alt="image" src="https://user-images.githubusercontent.com/6684137/174825171-1bf36008-bf83-4c2f-bd63-d3023ebe35db.png">

**Comment by afbora** [comment]
I agree, if there is no homepage, the link should not be given.

Also, some plugins are available in the directory, but their links are wrong (for ex: https://getkirby.com/plugins/rasteiner/pagesdisplay). GitHub and getkirby.com plugin addresses/urls should be checked.

**Comment by lukasbestle** [comment]
✅
