### ISSUE TITLE
Panel translations should work without setting locale territory code (e.g. `es` vs `es_ES`)

### ISSUE THREAD

**Issue by doup** [k-next/kirby#4412]
## Description

- If the panel user has the locale `es_ES` or `es_419`
- And the blueprint translation is defined as `es` (just language code, no territory)
- Then the translation is not detected; instead the first translation on the translation object is taken

**Expected behavior**  

- The `es` translation should match for both `es_ES` or `es_419` and show accordingly.

## To reproduce

1. In the panel, go to `Your Account`, select either `Español` or `Español (América Latina)`
2. On a blueprint, set a `label` translation using the `es` key (without territory code)
3. Open the blueprint related form
4. The account locale is ignored and the first translation is used instead

## Your setup

**Kirby Version**: `3.6.6`

**Your system**
 - Device: Macbook Pro
 - OS: macOS
 - Browser: Firefox
 - Version: 100

**Additional context**  

- By [Wikipedia](https://en.wikipedia.org/wiki/Locale_(computer_software)) the locale format is as follows: `language[_territory][.codeset][@modifier]`; `territory`, `codeset` & `modifier` are optional.
- From this, `es_ES` and `es_419` are subsets of `es`; hence these should match for `es`.
- **A workaround** is to just use the complete language code in the blueprints, e.g. `es_ES`. The downside is that it won't work for users with `es_419`, which is non-sense..

**Comment by lukasbestle** [comment]
## Possible solution

I think the `I18n::translate()` method would need to be updated to also check for the language code if the `$locale` contains an underscore. This check would be inserted after here:

https://github.com/getkirby/kirby/blob/d57e2b575e61e11836f6d487c7182f6276d13042/src/Toolkit/I18n.php#L144-L146

A pull request for this is welcome.

**Comment by distantnative** [comment]
✅
