### ISSUE TITLE
Initializing plugins which don't require PHP

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#4419]
When building a small UI plugin for the panel I noticed that – although my plugin only features CSS and JavaScript – I had to include an `index.php`. Although this PHP file's requirements are really minimal, I was surprised by the fact that it forced me to pass an empty array of options to work:

```php
Kirby::plugin('hananils/my-plugin', []); // this works
Kirby::plugin('hananils/my-plugin'); // this doesn't
```

This can be difficult to debug when you think you already defined your plugin and don't understand why your CSS and JavaScript files are not included in the panel. 

### Expected behaviour

1. If the plugin could also work without an "empty" `index.php`, this would be preferred. 
2. If this barebone definition is actually required for the system to work, it should be forgiving regarding the empty/missing options array and should accept both.

### Kirby version

Kirby 3.7 RC2 – not tested with prior versions, but my guess is it's the same.

**Comment by afbora** [comment]
Without `index.php` or the empty `index.php` file may not make sense, but I think it makes sense not to send the second parameter for `Kirby::plugin`. Because the plugin is registered with `index.php`. If the plugin is not registered, no source (`index.js`, `index.css`) will be loaded.

Also, if the second parameter is not sent, it works as a getter. 
https://github.com/getkirby/kirby/blob/3.7.0-rc.2/src/Cms/AppPlugins.php#L821

Maybe alias method can be created. For ex: `Plugin::register` targets to `Kirby::plugin`.

**Comment by nilshoerrmann** [comment]
> I think it makes sense not to send the second parameter for Kirby::plugin. Because the plugin is registered with index.php. 

That's what I guessed and that it makes perfectly sense :+1:

The important part of this issue is that I thought I had registered my plugin although I hadn't and it took me a while to understand why. If you can find a good solution that removes the need for the empty array that would be great - thanks!

**Comment by lukasbestle** [comment]
I like `Plugin::register()`. This could then be the new official way to register plugins throughout the docs. The only issue is that we would need a new global class alias for `Plugin`.

**Comment by rasteiner** [comment]
If we're already here, why not `new Plugin('rasteiner/plugin');`?

**Comment by distantnative** [comment]
Wouldn't it be easier to change the better to a new name (that we likely only use internally anyways, if at all) than trying to steer registering to a new way? Feels like a lot of change and effort for the small problem this is solving.

**Comment by afbora** [comment]
I think, the problem is not the name. `App::plugin()` is both getter and setter. The purpose of `Plugin::register()` is to create a setter, a completely independent method for registration. It is also more consistent in usage.

**Comment by rasteiner** [comment]
> I think, the problem is not the name. `App::plugin()` is both getter and setter. The purpose of `Plugin::register()` is to create a setter, a completely independent method for registration. It is also more consistent in usage.

I think @distantnative was referring to a comment I made and then deleted after a few seconds because I realized that it was just complicating things even more (I suggested permitting `new Plugin($name)` instead of `Plugin::register($name)`). Sorry 😶

I personally don't despise `Kirby::plugin('rasteiner/my-plugin', []);`, it's explicit.

**Comment by lukasbestle** [comment]
We could deprecate the getter behavior and move that to somewhere else. But the name of `App::plugin()` already fits so well as a getter...

**Comment by distantnative** [comment]
My rational:
- `Kirby::plugin('rasteiner/my-plugin')` not working as setter currently and having to write `Kirby::plugin('rasteiner/my-plugin', [])` is a rather small issue with little impact; we shouldn't spend a lot of work and effort on a solution here
- Moving the setter over to e.g. `Plugin::register()` means changing all docs, asking people to change their setups etc, asking people to learn something new (even over long time)

I don't see how that is worth it. So I'd argue either for leaving it as is or for changing the getter to a new method, e.g. `Plugin::get()` while then `Kirby::plugin()` remains as setter with default `[]` as parameter.

**Comment by afbora** [comment]
> I don't see how that is worth it. So I'd argue either for leaving it as is or for changing the getter to a new method, e.g. Plugin::get() while then Kirby::plugin() remains as setter with default [] as parameter.

I agree 100% with @distantnative I think we should leave `App::plugin()` as it is. Still, two new methods would be great: `Plugin::get()` and `Plugin::register()`

**Comment by distantnative** [comment]
But what was the reason again why we can't parse for plug-in folders without index.php but with index.css/.js?

**Comment by rasteiner** [comment]
> But what was the reason again why we can't parse for plug-in folders without index.php but with index.css/.js?

Having an "author/plugin" name without relying on composer? Just guessing

**Comment by distantnative** [comment]
@rasteiner 

But I was wondering if we couldn't have some "anonymous" plugins for just providing panel js and/or
css

**Comment by rasteiner** [comment]
I guess only Mr. Allgeier can answer that 🤷

**Comment by lukasbestle** [comment]
You are completely right that any change to the existing method isn't worth the effect because of either the huge breaking change (if the setter is changed) or the less than elegant code (if the getter is changed).

> But I was wondering if we couldn't have some "anonymous" plugins for just providing panel js and/or css

I really like this idea. 👍

**Comment by distantnative** [comment]
As I see it:
- https://github.com/getkirby/kirby/blob/main/src/Cms/AppPlugins.php#L891 don't yet skip the loop if no `index.php` is present (though only do `F::loadOnce($entry)` for `index.php`)
- instead check if `index.css` or `index.js` are present instead
- if so, call `static::plugin($dirname, ['root' => $dir])` to register the plugin anonymously

**Comment by lukasbestle** [comment]
Yes, I think this should work. 👌

**Comment by lukasbestle** [comment]
✅
