### ISSUE TITLE
Drag target in section ambiguous

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#4420]
## Description
When reordering items in a section, the selected item gets highlighted with a dark outline on click. This outline vanishes when starting dragging. This makes it hard to see for the users where their item will actually be inserted after drop.

**Expected behavior**  
It should be clear which item is currently sorted and where it will be places. Either the actual item or its ghost representation should keep the outline to make the context clear to the user.

## Your setup
**Kirby Version**  
3.7 RC 2

**Comment by afbora** [comment]
This is exists since 3.6.

**Comment by distantnative** [comment]
✅
