### ISSUE TITLE
[3.7.0-rc.3] `cursor: pointer` on structure field table header

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4422]
## Description
When hovering over table headers in structure fields the cursor changes to pointer. This is bad because you'd expect some kind of interaction, especially on table headers. You often have some kind of sorting functionality on those.

**Expected behavior**  
The pointer cursor should only be used for interactive elements.

```diff
- .k-table-column {
+ td.k-table-column {
  cursor: pointer;
}
```

**Screenshots**  
<img width="489" alt="CleanShot 2022-06-24 at 13 22 24@2x" src="https://user-images.githubusercontent.com/7975568/175524936-d09b5702-d3d9-49d6-9eec-f15c73f7c3d8.png">

**Comment by distantnative** [comment]
✅
