### ISSUE TITLE
[3.7.0-rc3] Structure field not saving some content

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4425]
## Description

Field content goes missing when I edit fields in multiple structure entries by using the arrows to navigate:

![structure-bug](https://user-images.githubusercontent.com/7975568/175774702-56c37edd-8389-497c-9c4f-013bc91cf6bf.gif)

It seems like the `change` event doesn't trigger when I'm not click on the OK button.

## To reproduce

1. Add a structure field
2. Create an entry
3. Duplicate it multiple times
4. Try changing something in every entry by using the arrows

## Your setup
**Kirby Version**  
3.7.0-rc3

**Console output**  
Nothing in the console

**Your system (please complete the following information)**
 - OS: macOS 12.4
 - Browser: Chrome
 - Version: 103.0.5060.53

**Comment by afbora** [comment]
I was thinking of creating the same issue today 👍

**Comment by bastianallgeier** [comment]
✅
