### ISSUE TITLE
[3.7.0-rc.3] New table layout doesn't support translations / "unfamiliar" default Cell label

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#4430]
## Description
When setting the label for a table section (hereby files table) and trying to use the familiar translation structure, a JSON object gets set as label.

When leaving the label empty, it gets set to "XxxCell", which differs from the known behavior that fields or section use when specifying no label, which is setting the ID capitalized: "Xxx" instead of "XxxCell"

**Expected behavior**  
The user would see a translated cell label or a cell label that's just the Column ID.

**Screenshots** 
 ![image](https://user-images.githubusercontent.com/29142128/175807661-30940f55-761e-49e9-993f-0cdc77e3dc15.png)
<img width="916" alt="CleanShot 2022-06-26 at 11 24 27@2x" src="https://user-images.githubusercontent.com/29142128/175807829-321d8b73-d4fc-4758-90fb-291d2177f2f9.png">

## To reproduce

Create a files section (or pages section, but I haven't tested that yet), use the table layout and add new columns without label or with a translated label.

## Your setup
**Kirby Version**  
3.7.0-rc.3

**Your system (please complete the following information)**
 - Device: MB Pro 14"
 - OS: macOS Monterey 12.4
 - Browser: Chrome
 - Version: 103.0.5060.53

**Comment by afbora** [comment]
Will be fixed with #4428 in next release
