### ISSUE TITLE
[3.7.0] Textarea - Image with caption throws deprecation notice

### ISSUE THREAD

**Issue by doldenroller** [k-next/kirby#4435]
## Description

Might be associated with #4366 and #4375
When using the image-tag with a caption, i.e. (image: myimage.jpg caption: My awesome caption) the deprecation notice for $inline parameter is triggered.

**Expected behavior**  

Image with caption should appear.

**Screenshots**  

<img width="430" alt="Bildschirmfoto 2022-06-27 um 13 57 34" src="https://user-images.githubusercontent.com/29595303/175939216-703e84c9-c81e-4fe5-a41a-76f46a03a5f7.png">

## To reproduce

1. insert image-tag with caption in textarea field

## Your setup
**Kirby Version**  

3.7.0

**Comment by afbora** [comment]
### Summary 

Missing changes for `$inline` param
https://github.com/getkirby/kirby/blob/3.7.0/config/tags.php#L147

**Comment by distantnative** [comment]
@doldenroller we'll fix this soon. For the meantime, disabling develop mode in your config should also help

**Comment by bastianallgeier** [comment]
✅
