### ISSUE TITLE
[3.7.0] Filesfield - change button not working when upload: false

### ISSUE THREAD

**Issue by doldenroller** [k-next/kirby#4436]
## Description

When the upload-property is set to False in the blueprint the change button is not working anymore. So you have to delete the image and then select the new one.

**Expected behavior**  

Image dialog should be triggered

**Screenshots**  

## To reproduce

1. Create a files field in page-blueprint with upload set to false
````
myimage:
  label: Image
  type: files
  upload: false
````
2. Add fiel in panel and save
3. Click on change (Auswählen in German)
4. Nothing happens

## Your setup
**Kirby Version**  

Kirby 3.7.0.
Firefox Developer 102.0b9
MacOS

**Comment by afbora** [comment]
### Summary

Related PR https://github.com/getkirby/kirby/pull/4395 @bastianallgeier already had his doubts about that. https://github.com/getkirby/kirby/pull/4395#discussion_r901595574 🙈

**Comment by distantnative** [comment]
@afbora Are you sure it's about this? And not in the files field the more/moreUpload logic?

**Comment by afbora** [comment]
Yes, works great when I add `v-bind="options[0]"` to `<k-button>`  component in `OptionsDropdown.vue`. This is about not triggering `open` method.

**Comment by bastianallgeier** [comment]
✅
