### ISSUE TITLE
[Panel] Panel throws error when using new stats section and relative links

### ISSUE THREAD

**Issue by ghost** [k-next/kirby#4439]
## Description

When adding a relative link to the new stats section the panel throws a warning as seen in the screenshot below. 
Tested with a new starterkit.

**Expected behavior**  

The stats "card" should link to the relative link set in the blueprint.

**Screenshots**  

![localhost_test_panel_site](https://user-images.githubusercontent.com/105460332/176030547-13cc81b2-a9c4-42d8-8ca1-ce9d8880c1d7.png)

## To reproduce

1. Go to `site.yml` and add a new stats section as mentioned in the doc [here](https://getkirby.com/docs/reference/panel/sections/stats#reports__links). Set the relative link to an existing page. 
```
sections:
  stats:
    type: stats
    reports:
      - label: Revenue
        value: €29,682
        info: +112.5%
        link: /about
```
2. Go to panel and click on the stats card.
3. See error

## Your setup
**Kirby Version**  3.7.0

**Console output**  

```
GET http://localhost/test/panel/about 500 (Internal Server Error)
```

**Your system (please complete the following information)**
 - Device: Windows PC
 - OS: Windows 11
 - Browser: Edge
 - Version: 103

**Comment by distantnative** [comment]
Looks like the Panel is exactly doing what you tell it - to open the relative link based on the current Panel view. What you seem to want is that it converts a relative link to a relative link based on the site url. But that could then actually prevent relative links within the spaniel that maybe another user would like to do.

**Comment by afbora** [comment]
If you want to link panel page, you can try `link: /pages/about`

**Comment by ghost** [comment]
Gotcha. Sorry I somehow expected it would link to `https://example.com/about`. But I do see the flexibility in being able to link to panel pages etc.
