### ISSUE TITLE
[3.7.0] Visitor user agent is not read from $_SERVER

### ISSUE THREAD

**Issue by mzur** [k-next/kirby#4440]
## Description
The recent update to Kirby 3.7.0 broke [this test](https://github.com/mzur/kirby-uniform/blob/51970602582c3426353725362e31dc1ddec1396a/tests/Actions/LogActionTest.php#L29-L38) of Uniform. In the test, `$_SERVER['HTTP_USER_AGENT']` is set and should be read with `$visitor->userAgent()`. However, since Kirby 3.7.0 the returned value is empty.

**Expected behavior**  
`$visitor->userAgent()` should return the value set in `$_SERVER['HTTP_USER_AGENT']`.

## To reproduce
Write a test such as:

```php
use Kirby\Cms\App;

$_SERVER['HTTP_USER_AGENT'] = 'Mozilla';
$this->assertSame('Mozilla', App::instance()->visitor()->userAgent()); //fails
```

## Your setup
**Kirby Version**  3.7.0

**Additional context**  
Since Kirby 3.7.0, `Environment::getGlobally` is [used](https://github.com/getkirby/kirby/blob/d210f26602cf72c926d8ccf8befd61d7831888da/src/Http/Visitor.php#L59) to get the user agent. Maybe it should check if the [variable is set](https://github.com/getkirby/kirby/blob/d210f26602cf72c926d8ccf8befd61d7831888da/src/Http/Environment.php#L696-L698) in the environment and fall back to `$_SERVER` if not.

**Comment by afbora** [comment]
As workaround, you can set server headers like following from tests:

````php
$app = App::instance()->clone([
    'server' => [
        'HTTP_USER_AGENT' => 'Mozilla'
    ]
]);

$this->assertSame('Mozilla', $app->visitor()->userAgent());
````

**Comment by lukasbestle** [comment]
A fallback to `$_SERVER` would make the behavior unpredictable. The idea behind the change was to make testing without changing PHP globals possible.

The example that Ahmet posted is the way to go, we also do that in our tests.

**Comment by mzur** [comment]
@afbora Ok, thanks for the example. But what can I do here (which is closer to the actual failing test)? Imagine the `LogAction` to be an actual class defined in another file.

```php
// This is the class file.
use Kirby\Cms\App;

class LogAction {
   public function getUserAgent() {
      return App::instance()->visitor()->userAgent();
   }
};
```
```php
// This is the test file.
$_SERVER['HTTP_USER_AGENT'] = 'Mozilla';
$this->assertSame('Mozilla', (new LogAction)->getUserAgent());
```

@lukasbestle But isn't `getGlobally()` [meant](https://github.com/getkirby/kirby/blob/d210f26602cf72c926d8ccf8befd61d7831888da/src/Http/Environment.php#L708) to fall back to `$_SERVER` (if the environment key is not set)?

**Comment by lukasbestle** [comment]
@mzur The same actually. `App::instance()` always returns the current singleton instance. If you use `App::instance()->clone()`, that instance is overwritten with the clone. So your plugin code that calls `App::instance()` afterwards will also get that new instance back.

> But isn't `getGlobally()` meant to fall back to `$_SERVER` (if the environment key is not set)?

Only if there is no singleton app instance (checked in the very first `if`). This can only occur if any of the Kirby classes are used outside the CMS environment, e.g. when using the MIT-licensed parts of Kirby in other projects.

**Comment by mzur** [comment]
While the behavior of `App::instance()->clone()` that you describe is totally not what I would expect, I can work with that, thanks!
