### ISSUE TITLE
Encoding-issue in the new table-layout

### ISSUE THREAD

**Issue by KGS-Rastede** [k-next/kirby#4442]
I just converted a blog to the new table-layout: https://getkirby.com/docs/reference/panel/sections/pages#layout__table-layout

Using "'" in titles breaks the table-layout encoding. Here is an article:

![grafik](https://user-images.githubusercontent.com/17048988/176251588-c08b3f7e-4058-412b-9ced-a726dcd96591.png)

Here is the same article in the panel

![grafik](https://user-images.githubusercontent.com/17048988/176251709-c6269919-12b5-4c59-9e62-3fedf773ca0d.png)

In the regular view it works:

![grafik](https://user-images.githubusercontent.com/17048988/176251860-d346192f-9747-41c6-8c8b-5a42da61e843.png)

Some kind of encoding issue. The original file is encoded in UTF8 and can be found here:

https://gitlab.com/cniehaus/homepage/-/blob/master/content/1_blogs/20220624_rassismus-geht-uns-alle-an/blogartikel.txt

**Comment by KGS-Rastede** [comment]
I forgot to mention: This is PHP 7.4.9 on Windows 10 / WAMP with Kirby 3.7.0.1

**Comment by gilbertnigg** [comment]
Same here with ampersand; PHP 8.0.8 MAC/MAMP / Kirby 3.7.0.1
<img width="577" alt="Bildschirmfoto 2022-06-28 um 20 31 19" src="https://user-images.githubusercontent.com/30411415/176256895-0c4912e1-65f7-4aaa-8548-ef61437f478b.png">
But (again) a great extension to Kirby anyway, congrats!

**Comment by teichsta** [comment]
can confirm this:

![image](https://user-images.githubusercontent.com/2108636/176450323-3122b89b-4011-47f2-ab5e-8b24c372abf5.png)

blueprint seems to be configured correctly:

```
columns:
  topic:
    label: Themenwelt
    html: true
    value: "{{ page.topic.toPage.title }}"
```

**Comment by teichsta** [comment]
any idea, where this issue is being positioned on the kirby roadmap @distantnative ? Any chance to get it into 3.7.1 ?

**Comment by lukasbestle** [comment]
Workaround: If you set the column to `type: text` or `type: html` explicitly, it seems to render correctly.

**Comment by medienbaecker** [comment]
<img width="385" alt="CleanShot 2022-08-01 at 08 43 17@2x" src="https://user-images.githubusercontent.com/7975568/182088080-9d5a2439-f23b-44f2-aa66-aa1d209531c9.png">

It also happens for special structure previews like select fields.

**Comment by distantnative** [comment]
If any of you want to try this fix https://github.com/getkirby/kirby/pull/4543
would be great to get additional feedback if this solves the issues.

**Comment by bastianallgeier** [comment]
✅
