### ISSUE TITLE
[3.7.0.1]: `Url::query()` and `$uri->query()` both return empty results

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4446]
## Description
Using the `Url::query()` or `Uri` method `->query()` both return empty results.

This is a pretty serious regression from 3.6.x

## To reproduce
Add the following to a hook or template and go to a url such as `http://example.com/test-page?token=xyz&foo=bar`

```php
echo Url::query(); // returns nothing
```

even something like
```php
echo Url::current(); // returns http://example.com/test-page
```

returns the current url *without* the query parameter.

## Your setup
**Kirby Version**  

`3.7.0.1`

**Comment by afbora** [comment]
Not a solution but may be give you an idea;

I realized that when I remove the `App::instance()` check from following lines, works great with just `$url = (new Environment())->requestUrl()`
https://github.com/getkirby/kirby/blob/3.7.0.1/src/Http/Uri.php#L246-L250

So in this issue, `App::instance()->url('current')` doesn't include the query string.

**Comment by bastianallgeier** [comment]
✅
