### ISSUE TITLE
`$block->toHtml()` renders error message on error even if not in debug mode.

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#4448]
## Description
This is the code in the `html()` method that causes this behavior. 
```
   try {
            return (string)snippet('blocks/' . $this->type(), $this->controller(), true);
        } catch (Throwable $e) {
            return '<p>Block error: "' . $e->getMessage() . '" in block type: "' . $this->type() . '"</p>';
        }
```

**Expected behavior**  
There should be a check if debug is on or off and only show the message in debug mode, otherwise an empty string.

**Screenshots**  

## To reproduce

1. Disable debug mode
2. Create block snippet with error
3. see error message

## Your setup
**Kirby Version**  
Tested with 3.7.0.1

**Comment by texnixe** [comment]
We should probably also double-check if there are other places where the frontend might give information away in non-debug mode.

**Comment by lukasbestle** [comment]
✅
