### ISSUE TITLE
I18n : config option for locale (single-lang site)

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4461]
I hope you don't mind me copying this issue over from the former "ideas repo" to ensure it is not forgotten. The issue was first brought up in Dec 2019 in https://github.com/getkirby/ideas/issues/459 that contains some technical assessments along with a few workarounds. There once was PR https://github.com/getkirby/kirby/pull/2490, initially targeted for 3.5, and based on a quick research (though I do see some activity around I18n and language codes, hard to frame for a reader without deep core knowledge) it seems after the PR got closed and the ideas repo archived, it may not currently be actively tracked?

> In a single language site, it is not possible to set a I18n locale, so that exception messages are rendered in English unless you manually translate the keys using I18n::template().
> 
> ```
> I18n::template($e->getKey(), null, $e->getData(), 'de');
> ```

**Comment by distantnative** [comment]
Since this is a feature idea, better located over at Nolt: https://kirby.nolt.io/495
Please make sure to upvote.
