### ISSUE TITLE
View don't update on username change with hook

### ISSUE THREAD

**Issue by enzo-martellucci** [k-next/kirby#4477]
## Description

When the username is changed through a Kirby hooks, it is not changed instantly on the page, we need to refresh page.

**Expected behavior**  

The username to change instantly.

**Screenshots**  

![image](https://user-images.githubusercontent.com/84910340/177352801-d9612236-d528-43ed-a065-6c64c1a042bd.png)
Example of hook above.

## To reproduce

1. Change programmaticaly the username in the function of 'user.update:before' hooks.
2. Create a field in the user account.
3. Modify the fields and save (doesn't update)
4. Refresh page (update)

## Your setup
**Kirby Version**  

3.6.6

**Console output**  

**Your system (please complete the following information)**
 - Device:  Fixe computer
 - OS:  Windows 10
 - Browser:  Google Chrome
 - Version:  103.0.5060.66

**Additional context**

**Comment by distantnative** [comment]
Changes within hooks are not reflected directly in the Panel. So this is not a bug, but I can understand this is a feature you would like to see. Please open an idea over here for this: https://kirby.nolt.io
