### ISSUE TITLE
`$block->prev()` & `$block->next()` return hidden blocks

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#4480]
## Description
I use `$block->prev()` & `$block->next()` to change a block's contents based on the previous or next block's type. When testing, I noticed that blocks that are marked as hidden in the CMS won't be echo'ed, but returned by prev() or next() as they're seemingly still part of the Blocks collection. 

**Expected behavior**  
The next visible block will be returned, whilst hidden blocks will be ignored. As an alternative, `nextVisible()` or `prevVisible()` methods should be provided.

## To reproduce
Run `$block->prev()` or `$block->next()` on any block while the next or previous block is hidden. It will still return the hidden block and not the next shown block.

## Your setup
**Kirby Version**  3.7.0.1

**Comment by bastianallgeier** [comment]
✅
