### ISSUE TITLE
[Panel] Apply gallery block images field's image settings to preview too

### ISSUE THREAD

**Issue by renestalder** [k-next/kirby#4481]
## Description

This is about the [gallery block](https://getkirby.com/docs/reference/panel/blocks/gallery).

Maybe this is considered a feature request. For me, it's rather a bug.

Currently, the images in the gallery block are rendered with the ratio 1:1 in the editing drawer. This can be overwritten by overwriting the block blueprint.

The image ratio settings and other settings are currently only applied to the editing drawer, not to the vue preview component.

**Expected behavior**  
Either that the same image settings apply to the preview rendering of the gallery too, or that there are other options to configure the preview of the gallery block itself.

**Screenshots**  
![Screenshot from 2022-07-06 14-57-12](https://user-images.githubusercontent.com/105358/177555374-762df3de-ea95-40e5-a351-03b1480f4aa0.png)

_What the preview looks like_

---

![Screenshot from 2022-07-06 14-57-02](https://user-images.githubusercontent.com/105358/177555380-5ea6e6f8-6185-4ae3-94b4-e2dcac9bf444.png)

_What the editing drawer looks like and what I would expect the preview to look like too (in terms of ratio and cover settings)._

## To reproduce

No specifics.

## Your setup
**Kirby Version**  

**Console output**  

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Version: 102

**Additional context**  
In general, it would be a nice addition to being able using the gallery images in the same way as the individual image block: Having all fields like alt text, ratio etc. available in the panel. But that would be certainly more of a feature then.

**Comment by distantnative** [comment]
I'd think some fields from the image block make sense, e.g. ratio, caption, crop. Then one could also use the ratio field value for the preview. Fields like alt text don't really make sense as one would apply the same alt text to all the gallery images.

**Comment by bastianallgeier** [comment]
✅
