### ISSUE TITLE
Text input elements clip descenders on Chrome, Windows

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#4484]
## Description
The tail of some descenders are clipped by the text inputs (all of them: text, email, etc.)

**Expected behavior**  
Don't cut tail. Poor tail. Bad box!

**Screenshots**  
Kirby 3.7
<img alt="image" src="https://user-images.githubusercontent.com/6684137/177723531-b0d77b55-7485-4e94-bc74-aea0d0c79a4b.png">

Kirby 3.6
<img alt="image" src="https://user-images.githubusercontent.com/6684137/177725246-4ec9023f-ea80-41aa-8319-a559f341f40d.png">

## To reproduce

1. Buy a Windows machine and a 4k screen
2. Open Edge or install and open Chrome
3. Go to https://getkirby.com/try and click on "Start Demo"
4. Click on "Open the panel"
5. Insert `ggg@jjj.com` into the email box

## Your setup
**Kirby Version**  
3.7, but actually also prior versions. 

**Your system (please complete the following information)**
 - Device: Desktop PC
 - OS: Windows 10/11
 - Browser: Chrome, Edge
 - Version: latest

**Additional context**  
Firefox on the same machine, rendering the same font (Segoe UI) does **not** have this problem.
Chrome on Android does not have the problem (not rendering Segoe UI, though).

I have no idea why I didn't notice this before. Maybe because none of the names I normally write have descenders.

**Comment by rasteiner** [comment]
OH! 

this also only seems to happen on 4k screens with Windows set to 150% magnification. At 100% or 200% it doesn't clip the text. 
I guess it's a subpixel rounding problem. 

150% is the windows default for 4k screens though.

**Comment by afbora** [comment]
The input line height of 1.25rem doesn't seem sufficient for the font used in the panel. Two solutions I can think of: font or increasing line-height of inputs. I don't know if there is a more stable solution 🤷‍♂️

**Comment by rasteiner** [comment]
<img alt="image" src="https://user-images.githubusercontent.com/6684137/216946569-97bb1e92-59d3-4af5-b1e6-b9ad90da9210.png">
The problem is still there in current kirby

**Comment by bastianallgeier** [comment]
@rasteiner can you also reproduce this in v4?

**Comment by rasteiner** [comment]
Seems to be ok in v4 👍

<img alt="image" src="https://github.com/getkirby/kirby/assets/6684137/c117a436-d25e-40d5-8dd9-1740a0d85e36">

**Comment by bastianallgeier** [comment]
I will close this issue. For v3, there are more important issues to fix and with v4 it will then be fixed anyway. This is great. Thanks for testing again.
