### ISSUE TITLE
Wrong header location when using url => /

### ISSUE THREAD

**Issue by andreasotto** [k-next/kirby#4486]
## Description
The browser receives a wrong header location result when using `'url' => '/'` in config.php:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/2129515/178004419-3f9447b6-8d5d-4ed4-aac7-99d305361bdc.png">

After reloading the problem seems to have gone. But the problem keeps occurring sporadically. There are still problems with the `url` method behind proxies like Traefik, where e.g. the http scheme or the port number are not recognized correctly.

**Kirby Version**  
3.6.6

**Comment by afbora** [comment]
Could you test on 3.7.1 please? Because this area refactored since the 3.7

**Comment by afbora** [comment]
Please feel free reply to reopen when you've the issue on latest release.
