### ISSUE TITLE
Kirby 3.7 does not pick `url` from config.localhost.php anymore

### ISSUE THREAD

**Issue by LeBenLeBen** [k-next/kirby#4487]
## Description

I dynamically override Kirby URL in a `config.localhost.php` file using the following code so I always stay on the frontend server when navigating:

```php
if (Server::get('HTTP_X_WEBPACK_DEV_SERVER') == 'yes') {
    $config['url'] = 'http://localhost:3000';
}
```

Since Kirby 3.7, this stopped working. So I tried to hardcode the `url` thinking it was linked to the `Server` class or the header, but it’s not.

Moving this code into `config.php` works though. So there seems to be a problem defining a value for the `url` option in `config.localhost.php` only.

However it doesn’t seems to be as simple as `config.localhost.php` is not picked up, because other settings in this file seems to work.

**Expected behavior**  

Kirby should use the `url` defined in `config.localhost.php` when the host is `localhost`.

## To reproduce

See https://github.com/LeBenLeBen/kirby-localhost-config-repro

## Your setup
**Kirby Version**  
3.7.0.2

**Comment by bastianallgeier** [comment]
Hey @LeBenLeBen could you give our RC for 3.7.1 a try? We might have already fixed it with this: https://github.com/getkirby/kirby/pull/4474

**Comment by distantnative** [comment]
@LeBenLeBen 3.7.1 is out - please try this release, it should fix your problem. If not, please let us know so we can reopen the issue.

**Comment by LeBenLeBen** [comment]
Yes it works now using 3.7.1, thank you and sorry to have overlooked the existing MR. ✌️
