### ISSUE TITLE
Double-slashes when using assets helper 

### ISSUE THREAD

**Issue by lmgringhuis** [k-next/kirby#4508]
## Description
After running with panel issues as mentioned in issue #4443 we placed `'url' => '/'` in the config.php to get the panel working again. But that somehow breaks the assets helper, it now puts two slashes before the url:

`<img src="//assets/images/logo.png" />`

With this in the snippet:

`<?= asset('assets/images/logo.png')->url() ?>`

**Expected behavior** 

A correct asset link, in this example:
`"/assets/images/logo.png"`

## To reproduce

1. Place `'url' => '/'` in config.php
1. Place asset on snippet/template using asset helper
2. It is rendered with double slashes and becomes unresolvable

## Your setup
**Kirby Version**  
3.7.1

We updated to the latest version after learning it fixes panel issues regarding https, but this issue remains somehow.

**Comment by lukasbestle** [comment]
✅
