### ISSUE TITLE
CSS files in panel sections: wrong MIME type

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#4516]
This is related to or a reoccurence of #1177:

Given a files simple files section:

```yaml
sections:
  styles:
    type: files
    label: Styles
```

When trying to upload a CSS file, I get this error message:

![Bildschirmfoto am 2022-07-18 um 13 50 31](https://user-images.githubusercontent.com/25466/179505289-f640b724-b184-4e83-8777-bb5079598c04.png)

This is on latest Firefox for macOS and Kirby 3.7.1.
Looking a the file type in the Terminal, macOS treats the CSS file as `text/plain` and not `text/css`. There is a mapping for this in `Mime.php` but it doesn't seem to have an effect here: 

https://github.com/getkirby/kirby/blob/cfac315bc685193d0fe1b10fe3bf45a96e48fd15/src/Filesystem/Mime.php#L126-L157

**Comment by nilshoerrmann** [comment]
I still think this is a bug because Kirby is [officially supporting CSS files](https://getkirby.com/docs/guide/content/files#example-page-with-files__supported-file-types), but this can be fixed by specifying the `accept` setting in the related **files** blueprint:

```yml
title: Style
accept:
  extension: css
  mime: text/plain, text/css
```

It would be great to add this in the files section docs because this might be easier than creating a [file type extension](https://getkirby.com/docs/reference/plugins/extensions/file-types). It's important to note that this has to be defined in the files blueprint and not the files section definition (something that can easily be confused).

**Comment by distantnative** [comment]
Wondering why the fix mapping is not working as it seems to be exactly set up to fix this mime inconsistency

**Comment by distantnative** [comment]
I think I tracked it down - and it's not related to what we wrote above:

When no `accept` is configured, these lines https://github.com/getkirby/kirby/blob/main/src/Cms/FileBlueprint.php#L151-L160 will restrict the types of files. Excluding `code` files. And a CSS file is detected as such.

**Comment by lukasbestle** [comment]
Oh yes, that's exactly it. We even have it in the docs, but the paragraph about it was quite hidden.

Fixed by https://github.com/getkirby/getkirby.com/commit/57a4cf023fde09457b7dcc9ae26c3df6b7aa27e2.

**Comment by lukasbestle** [comment]
Well, partly fixed. The error message is still weird. Shouldn't it be `Invalid file type: code` (`error.file.type.invalid`)? For some reason, Kirby cannot detect the file as code when generating the error message.

**Comment by distantnative** [comment]
For me in Firefox in Mac that is exactly the error message. But I see that for Nils somehow the type isn't even detected.

**Comment by nilshoerrmann** [comment]
I‘m using MAMP. Might that be related?

**Comment by lukasbestle** [comment]
I don't think so. Have you tried it with a clean Starterkit?
