### ISSUE TITLE
[3.7.2] Structure field overwrites data

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4537]
Forum discussion: https://forum.getkirby.com/t/structure-field-just-one-entry-possible-latest-entry/26085

![chrome-capture-2022-6-28 (1)](https://user-images.githubusercontent.com/3393422/181512128-e1c40590-2ef8-4191-a345-f8d6184e5ddf.gif)

**Comment by afbora** [comment]
I can confirm that this issue is related https://github.com/getkirby/kirby/pull/4513 `onInput` listener PR.

**Comment by Foddy** [comment]
I have the same issue unfortunately… :S

**Comment by afbora** [comment]
@bastianallgeier When I removed the `onInput` listener, works great!

I think, `onInput` listener isn't right usage for structure field, right? Because `emit` should be run only form submitted, not while input.

**Comment by afbora** [comment]
✅
