### ISSUE TITLE
V::time() strange validation

### ISSUE THREAD

**Issue by flokuek** [k-next/kirby#4563]
## Description

When using the V::time() validator some times are getting validated as true and some as false. 

**Expected behavior**  

V::time() validator should validate times correctly. e.g V::time('32:36') -> true

## To reproduce

echo V::time('17:13') ? 'true' : 'false';   -> returns true
echo V::time('32:36') ? 'true' : 'false';   -> returns false

## Your setup
**Kirby Version**  3.7.3

**Your system (please complete the following information)**
 - Device: PC
 - OS: Windows 11
 - Browser: Edge
 - Version: 104

**Comment by distantnative** [comment]
Time validates `hours:minutes` - as in time of day. So 32 hours isn't a valid time.

**Comment by afbora** [comment]
You can use `V::match` for this like following. Of course, you can improve the regex pattern.

````php
$pattern = '^/\d+:([0-5]?[0-9]|60)$/';

V::match('17:13', $pattern); // true
V::match('32:36', $pattern); // true
V::match('5:57', $pattern); // true
V::match('39:72', $pattern); // false
V::match('a:b', $pattern); // false
V::match('36', $pattern); // false
````

**Comment by flokuek** [comment]
Thanks guys that makes sense. I ended up using pattern `/^(?:(?:([01]?\d|2[0-3]):)?([0-5]?\d):)?([0-5]?\d)$/` as this will work for hh:mm:ss and mm:ss
