### ISSUE TITLE
Constantly logged out of panel (3.7.1)

### ISSUE THREAD

**Issue by p-mylecharane** [k-next/kirby#4579]
I’ve been using 3.7.1 daily of late and I’m getting constantly logged out the panel after saving or updating the frontend. As in, nearly every browser reload.

**Comment by distantnative** [comment]
Could you please provide more information? What system are you running Kirby on? What pho version? Are there any errors in the browser console, in the PHP logs...?

When you say saving or updating the front end? Does that mean you have custom build dringend forms that edit content?

Is that problem only occurring with your specific site (with configs, plugins etc) or ist it also happening for you with a fresh starter kit in the same machine?

**Comment by p-mylecharane** [comment]
Hey @distantnative – oops, yes of course.

This is locally, php7.4.2. For instance of console, see below: a 403 on an image i was writing a caption to. There’s nothing in the php logs.

<img width="1381" alt="Screen Shot 2022-08-17 at 11 30 01 am" src="https://user-images.githubusercontent.com/18585409/185015229-aab82865-e951-4d21-9bc0-4b37593f549f.png">

In terms of the frontend, no, just making text changes in the panel and reloading the actual site to check text edits, when I flip back to the panel tab, I’m logged out.

It’s a fresh starter kit, not running any plugins yet.

**Comment by lukasbestle** [comment]
Which server do you use? I see you are on localhost:8888.

**Comment by p-mylecharane** [comment]
I’m just using MAMP. I’ve noticed every now and then it’s throwing this error:

`GET http://localhost:8888/bhp_sm/api/auth 403 (Forbidden)` along with `{status: 'error', message: 'Unauthenticated', code: 403, exception: 'Kirby\\Exception\\PermissionException', key: 'error.permission', …}`

**Comment by lukasbestle** [comment]
I was thinking it could be Kirby's environment detection because of the custom port number, but in my tests with the built-in PHP server I didn't see the behavior you are getting. So that can't be it.

@p-mylecharane Have you tried a different browser? Could be that a browser extension or configuration causes it.

**Comment by p-mylecharane** [comment]
Hey @lukasbestle I’ll give that a try. The funny thing is it goes away and comes back, is not project dependent. So it baffles me ...
