### ISSUE TITLE
Incomplete translation of headings in writer field (spanish)

### ISSUE THREAD

**Issue by plagasul** [k-next/kirby#4586]
## Description

In spanish, the writer field headings h1 to h3 are not translated, while h4 to h6 are. 

**Expected behavior**  
All of them should be translated.

**Screenshots**  
![image](https://user-images.githubusercontent.com/13966673/185463634-6b8bafb7-2202-45c4-bba2-6e63c51c8b38.png)

## To reproduce
Just create a writer field in a spanish translated panel, select a word, and check translation of headings.

## Your setup
**Kirby Version**  
3.6.1.1

**Comment by lukasbestle** [comment]
✅

We manage our translations in [Transifex](https://www.transifex.com/getkirby/panel/). You can contribute changes there directly if you ever come across other issues.
