### ISSUE TITLE
Wrong `margin-bottom` in info fields since 3.7.4-rc.1

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#4587]
## Description
The latest rc added a `margin-bottom` to all `<p>` elements in info fields.

**Expected behavior**  
The last child should not receive a `margin-bottom`, just like it was before. I tried to find the reason/commit but couldn't find it.

**Screenshots**  

![schwankhalle test_panel_pages_veranstaltungen+test-veranstaltung-2](https://user-images.githubusercontent.com/7975568/185466539-6f411a9a-ec60-4e45-8a95-a2291884b541.png)
![schwankhalle test_panel_pages_veranstaltungen+test-veranstaltung-2 (1)](https://user-images.githubusercontent.com/7975568/185466550-c53b554d-0fee-42a1-a19f-fe66fa6adbcd.png)

## To reproduce

1. Create an info field:
```yml
 info:
    text: Katzenklo, Katzenklo, ja, das macht die Katze froh
```
2. Look at the panel and notice the `margin-bottom`

## Your setup
**Kirby Version**  
3.7.4-rc.1

**Comment by lukasbestle** [comment]
Thanks for that earworm. 😝

Comparing the markup, there's the following difference:

```html
<!-- 3.7.3 -->
<div data-theme="info" class="k-box"><div class="k-text"><p>Bla bla</p></div></div>

<!-- 3.7.4-rc.1 -->
<div data-theme="info" class="k-box"><div class="k-text"><span><p>Bla bla</p></span></div></div>
```

The extra `<span>` comes from here:

https://github.com/getkirby/kirby/blob/9f9ecdf396cb4ff96569bb19c14c54f24f06fc3d/panel/src/components/Misc/Text.vue#L4

Don't think `v-html` works on a `<template>` tag though, right? So we might need to duplicate the `<div>` once for HTML mode and once for slot mode. Or find an entirely different solution. @distantnative?

**Comment by distantnative** [comment]
`v-html` does not work on `template` tags indeed

**Comment by lukasbestle** [comment]
@distantnative With what we discussed, I think it makes sense to keep the `html` prop for `<k-text>` and not revert to `v-html` throughout the codebase. We only need to get rid of that `<span>` somehow.

**Comment by distantnative** [comment]
@lukasbestle I have added a potential fix https://github.com/getkirby/kirby/commit/e90fd61e4e3befba62565b4830f5e6b1de710771- what do you think?

**Comment by lukasbestle** [comment]
@distantnative Haven't tested it, but looks good.

**Comment by lukasbestle** [comment]
✅
