### ISSUE TITLE
Video Kirbytag should render `playsinline` attribute

### ISSUE THREAD

**Issue by tillprochaska** [k-next/kirby#4595]
## Description
I’m not 100% sure if this should be considered a bug or a feature request. When setting `autoplay: true`, the video Kirbytag renders `autoplay` and `muted` attributes. On iOS, a third attribute, `playsinline` is required:

> Video elements that include `<video autoplay>` play automatically when the video loads in Safari on macOS and iOS, only if those elements also include the playsinline attribute. – [Source](https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari#3030251)

That means that HTML videos rendered by the video Kirbytag won’t start playback automatically on iOS.

**Expected behavior**  
* The video Kirbytag should have a `playsinline` attribute.
* If the `playsinline` attribute isn’t explicitly set, it should default to `true` if `autoplay` is set, and `false` otherwise. (This is behavior is analogous to the `mute` attribute.)

## To reproduce

1. Render the following Kirbytext:
   ```
   (video: https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 autoplay: true)
   ```
2. Open the page in iOS Safari.
3. The playback should start automatically, but it doesn’t.

## Your setup
**Kirby Version**  
3.7.1

**Your system (please complete the following information)**
 - Device: iPHone SE 2 (Xcode simulator)
 - OS: iOS 15.5
 - Browser: Safari
 - Version: 15.5

**Additional context**
I have a branch with a fix ready and can open a PR if you consider this to be a sensible change.

**Comment by lukasbestle** [comment]
I agree with the expected behavior. A PR is welcome. :)

**Comment by distantnative** [comment]
✅
