### ISSUE TITLE
'Subpage deletion' dialog for virtual subpages

### ISSUE THREAD

**Issue by S1SYPHOS** [k-next/kirby#4599]
## Description
When I delete a page whose children are all virtual, I'm asked to confirm this in order to prevent data loss. I can see how this is desired behaviour for 'real' pages, and even virtual pages coming from eg a CSV or JSON file inside the page's root, but if there's nothing except the content file, there would be no need to confirm anything, given that all children are defined solely in the `model` file of the corresponding page. 

**Expected behavior**  
If a page has only virtual children, there's no need to confirm its deletion. The popup should not show.

## To reproduce
Virtual children setup via `models/mytemplate.php`, defining `public function children()`.

## Your setup
**Kirby Version**  
3.7.3

**Your system (please complete the following information)**
 - Device: Thinkpad T440p
 - OS: pop_OS (22.04) using 5.18 Linux
 - Browser: Firefox
 - Version: latest

**Comment by lukasbestle** [comment]
The Panel cannot know if the virtual pages are generated dynamically or if they are real content that come from a different source (e.g. a database). This complicates it.

**Comment by distantnative** [comment]
I'm not even sure if this should be the behavior if technically possible. Yes, technically there would be no difference between deleting just the parent or parent wit subpages. However, it might be still quite valuable to alert the user that their actions also involve the subpages (no matter whether real or virtual).

**Comment by afbora** [comment]
Agree. The developer can know if a page is virtual or physical, but I don't think the end user/customer can. IMO there is no harm. Also I'm not sure it's worth the effort.

**Comment by S1SYPHOS** [comment]
You've got a point, I can see that. From a user perspective, this means "data loss inevitable" which in my case is something I want to avoid being asked about. May I disable this dialog at least? 🤔

**Comment by lukasbestle** [comment]
@S1SYPHOS The message is generated here:

https://github.com/getkirby/kirby/blob/44158e8a5856384f35b07263240abc96db16ae7e/config/areas/site/dialogs.php#L379-L401

You can disable it or only render it conditionally by [overriding the dialog in a plugin](https://getkirby.com/docs/reference/plugins/extensions/panel-dialogs#extending-dialogs)
