### ISSUE TITLE
Periodic API ping breaks login view

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4613]
## Description

The Panel periodically pings the API to keep the session fresh:

https://github.com/getkirby/kirby/blob/44158e8a5856384f35b07263240abc96db16ae7e/panel/src/config/api.js#L61

If no user is logged in, this request fails and triggers a logout:

https://github.com/getkirby/kirby/blob/44158e8a5856384f35b07263240abc96db16ae7e/panel/src/config/api.js#L22-L29

This causes a UI reset if the login page is left open for 5 minutes. This is bad e.g. during a code challenge (normal timeout for that is 10 minutes) and also when the user leaves the login page open to lookup a password etc.

**Expected behavior**  

The redirection to logout shouldn't happen.

## To reproduce

1. Open login page
2. Enter some text but don't submit (or request a code challenge and leave that open)
3. Wait for 5 minutes

## Your setup
**Kirby Version**  

`develop`

**Additional context**  

We need to check if the session actually needs refreshing before login. Might be that we only set the session inactivity timeout on login.

If the session *does* need refreshing, the ping should occur but the Panel should not redirect to logout when no user is logged in.
If it *doesn't* need refreshing, the ping should be disabled completely during login.

**Comment by lukasbestle** [comment]
OK, so it seems like our backend code doesn't differentiate between sessions with a logged in user and sessions without user. Both have a timeout of half an hour by default (can be overridden or disabled with the `session.timeout` option).

So we do need the regular ping, but the `$go('logout')` shouldn't be called if there isn't an active user in the frontend store. This is the easy part.

More difficult: The ping response also triggers a dialog:

<img width="516" alt="Bildschirmfoto 2022-08-27 um 21 10 53" src="https://user-images.githubusercontent.com/1595007/187044775-1d5f87d2-518c-4ea5-a686-bdef9f34f0a1.png">

Where is this triggered and how can we suppress it?

**Comment by distantnative** [comment]
Where do you get the dialog? Is that only when you remove `$go('logout')`?

**Comment by lukasbestle** [comment]
Yes. With the current code that dialog flashes for a tiny moment before the view is reloaded. If I disable `$go('logout')`, the dialog stays.

**Comment by distantnative** [comment]
Ok so this happens because our API library while passing errors to the onError callback (where our app puts its logic then) still throws all errors: https://github.com/getkirby/kirby/blob/main/panel/src/api/request.js#L84-L85

**Comment by lukasbestle** [comment]
Ah, I see.

Maybe we could allow `onError` to return a special value (maybe `true`) to disable the error from being thrown?

**Comment by distantnative** [comment]
Yep, that's what I am trying out right now (just with `false`) :D

**Comment by lukasbestle** [comment]
Another option: We could add a new `POST auth/ping` API endpoint that doesn't require auth. Then there won't be an error in the first place.

**Comment by distantnative** [comment]
I think we should do both - it's not quite right that a dialog opens just before redirecting to logout anyways.

**Comment by lukasbestle** [comment]
✅
