### ISSUE TITLE
Panel arbitrarily disallow field width when parent column width is 1/3 or 1/4

### ISSUE THREAD

**Issue by miragecraft** [k-next/kirby#4617]
I could not set two fields 1/2 wide when they are contained in a column with 1/3 width.

This seems strange to me because you are allowed to create 1/3 width field within 1/2 width column, with the same final width (this is done for the "license" field within the `image.yml` blueprint in the starterkit)

I dug around and the offending CSS is
```
.k-sections>.k-column[data-width="1/3"] .k-fieldset .k-grid,
.k-sections>.k-column[data-width="1/4"] .k-fieldset .k-grid {
	grid-template-columns: repeat(1, 1fr)
}

.k-sections>.k-column[data-width="1/3"] .k-fieldset .k-grid .k-column,
.k-sections>.k-column[data-width="1/4"] .k-fieldset .k-grid .k-column {
	grid-column-start: initial
}
```

Which seems extremely arbitrary, as I was able to get around it by just setting the column width to 2/6 instead of 1/3, so what's the point of those styles?

I just don't want to worry in the back of my mind that my "hack" of setting the column width to 2/6 will break down the line.

**Comment by foxacid** [comment]
I have _not_ dug around in the CSS code yet, but possibly this is related: https://github.com/getkirby/kirby/issues/4460

**Comment by distantnative** [comment]
> Which seems extremely arbitrary, as I was able to get around it by just setting the column width to 2/6 instead of 1/3, so what's the point of those styles?

The point of these styles is that we try to make our grid responsive and not to have too narrow grid columns on smaller viewports. These need to be arbitrary until we can use container queries - only they are an actual solution here. For the moment we can only do these workarounds and, as you pointed out, these surely can be limited and not apply to every user's use case. But we need something that serves at least most user's interest for now. That Kirby's flexibility of supporting just any fraction you can think of allows you to circumvent it doesn't negate it - it's not feasible to define CSS rules for all linkable factions.

**Comment by lukasbestle** [comment]
Given that browsers start to ship container queries, could we already add support for them with a fallback to the old behavior for browsers that don't support container queries?

**Comment by distantnative** [comment]
The support is still very limited https://caniuse.com/css-container-queries - of course that work could already make sense, but I think for it to rise in priority browser support should be a bit more widespread first.

**Comment by lukasbestle** [comment]
The table seems out of date: https://chromestatus.com/feature/6525308435955712

**Comment by distantnative** [comment]
Maybe on a. detail, I think my general statement still applies

**Comment by lukasbestle** [comment]
## Summary

We currently limit columns within columns to ensure that columns won't get too narrow.

Once container queries are available in more browsers, we can replace this logic with a container query that bases the decision whether "child columns" are allowed on the actual parent widths.

**Comment by distantnative** [comment]
This is now handled more consistently in v4 (doesn't matter which order the width fractions are, child elements will either be at their specified with when enough space or wrap to single column).
