### ISSUE TITLE
table layout: alignment does not affect column heading

### ISSUE THREAD

**Issue by miragecraft** [k-next/kirby#4630]
When aligning right in the pagetable extension, the column heading also aligns right, but in the new table layout the column heading is unaffected.

I feel this is the wrong behavior.

**Comment by afbora** [comment]
You're right. It's documented but not working
https://getkirby.com/docs/reference/panel/sections/pages#layout

**Comment by afbora** [comment]
Will be fixed in 3.8.0 ✅
