### ISSUE TITLE
Pages cache not working (neither stored not used) when checking for logged in user

### ISSUE THREAD

**Issue by sylvainjule** [k-next/kirby#4634]
## Description
Having read @lukasbestle's explanation in #4423, I figured the following would work. [This thread](https://forum.getkirby.com/t/pages-with-protected-content-cannot-be-cached/26387/2) in the forum suggests this should work too so I'm mentioning this as an issue. Starting with a fresh starterkit, I activate the cache in `config.php`:

```php
'cache' => [
    'pages' => [
        'active' => true
    ]
]
```

Pages are stored. Let's say I want to add the ability for my logged in users to have an edit button available on any front-end page which redirects to this very same page in the panel. I clear the cache and I add in my `header.php`:

```php
<?php if(kirby()->user()): ?>
    <a class="edit" href="<?php echo $page->panel()->url() ?>">Edit content</a>
<?php endif; ?>
```

As soon as I do, the cache stops storing pages, the `Cache-Control: no-store, private` header is always set despite me not being logged in. Here's a video of this:

https://user-images.githubusercontent.com/14079751/189099427-fdbd6cd6-ac20-4d42-b355-d5e5d695af95.mp4

## Your setup
Kirby 3.7.5

**Comment by lukasbestle** [comment]
@sylvainjule @LaurentTacco Could you please try if the following change in line 276 of `kirby/src/Http/Request.php` fixes it for you:

```diff
-		return $header !== null;
+		return empty($header) === false;
```

Explanation: The old line considers an empty but existing `HTTP_AUTHORIZATION` value as active, which is of course not true.

**Comment by LaurentTacco** [comment]
@lukasbestle By changing this line, cache seems to finally work as expected on my side! Thanks!!

**Comment by sylvainjule** [comment]
Same here! Thanks @lukasbestle!

**Comment by lukasbestle** [comment]
@LaurentTacco Could you please also check if changing the `SetEnvIf` line in `.htaccess` from `(.*)` to `(.+)` fixes it (without the change in the core)?

**Comment by LaurentTacco** [comment]
@lukasbestle Without changing anything in the core and by having `SetEnvIf Authorization "(.+)" HTTP_AUTHORIZATION=$1` in the `.htaccess` everything works perfectly.

**Comment by lukasbestle** [comment]
Great, thanks for the quick reply.

Then we'll fix it in both places. The `.htaccess` change ensures that no empty headers are inserted if no header was passed, while the core change ensures that any empty header (no matter where it comes from) won't break the behavior.

**Comment by LaurentTacco** [comment]
You're welcome!

**Comment by bastianallgeier** [comment]
✅
