### ISSUE TITLE
Tags field: input doesn't get separated on blur

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4638]
Maybe I add this to the same issue, as this is closely related. When enter some comma separated tags and then instead of hitting enter, I click outside the field, the tags will visually show as one big, merged tag:

![Bildschirmfoto 2022-09-12 um 16 22 27](https://user-images.githubusercontent.com/9803905/189678783-89786c2d-c1d4-421b-82d7-61de58951f90.png)

They are correctly saved to the content file though and when I leave the page and then navigate back to it, they show correctly again:

![Bildschirmfoto 2022-09-12 um 16 23 20](https://user-images.githubusercontent.com/9803905/189679011-7bafe879-75f8-4458-9084-418883853fb4.png)

When I hit enter in the tag field, the tags are separated correctly directly.

_Originally posted by @trych in https://github.com/getkirby/kirby/issues/4590#issuecomment-1243820783_

**Comment by bastianallgeier** [comment]
✅
