### ISSUE TITLE
Site search: Parameters seem to be broken

### ISSUE THREAD

**Issue by FynnZW** [k-next/kirby#4641]
The additional [site search parameters](https://getkirby.com/docs/reference/objects/cms/site/search#parameter-options) are not behaving as expected.
This is working correctly:

```php
// controllers/search.php
return function ($site) {
  $query   = get('q');

  $results = $site->search($query, 'text|title');

  return [
    'query'   => $query,
    'results' => $results
  ];
};

```
However, this is not:

**minlength**
```php
  $results = $site->search($query, [
    "fields" => ["text", "title"],
    "minlength" => 5,
  ]);
```
-->  If the search query is shorter than the `minlength`, all pages get returned (instead of zero)

 **stopwords**
```php
  $results = $site->search($query, [
    "fields" => ["text", "title"],
    "stopwords" => ["und", "and"]
  ]);
```
-->  stopwords are not being ignored, result does not change

I have not tested the other parameters. 

**Expected behavior**  
 `minlength` > query length should return zero results. 
`stopwords` should be ignored during search

**Kirby Version**  
3.7.5

**Comment by afbora** [comment]
✅
