### ISSUE TITLE
Copy (all) nested-blocks from drawer-field to a different drawer-field

### ISSUE THREAD

**Issue by peterstollenwerk** [k-next/kirby#4642]
## Description

Inside a blocks-drawer with nested blocks fields, it is not possible to copy (all) blocks to another blocks field.
Drag and drop does work though.

**Expected behavior**  
Copy (all) blocks freely around, if the targeted blocks-field allows to insert this block:
- BlockDrawerFieldBlocks -> different BlockDrawerField
- BlockDrawerFieldBlocks -> PageField
- etc.

## Your setup
3.5.7

**Comment by afbora** [comment]
Duplicated with https://github.com/getkirby/kirby/issues/4282
