### ISSUE TITLE
Check for content translations doesn't work with virtual pages

### ISSUE THREAD

**Issue by bvdputte** [k-next/kirby#4674]
## Description

There's no way to work with virtual pages where some virtual pages don't have a translation in a particular language.
In default Kirby situation (where Kirby fetches data from the `content` folder via txt files), one can use `$contentTranslation->exists()` to check if a certain page has a translation for a given language code.

With virtual pages, there's currently no way to structure an array in a way so Kirby can know if a virtual page has an existing translation (or not). [The function that checks this](https://github.com/getkirby/kirby/blob/3.7.5/src/Cms/ContentTranslation.php#L124), always looks at the filesystem.

Since checking if a translation is available is a quite common scenario in multilang websites - and can be used in multiple places/locations/situations, I'ld like to have a singular way of dealing with this, preferably by hooking into the existing API's and code paradigms. E.g. as shown to [setup a language switcher in kirby docs](https://getkirby.com/docs/guide/languages/switching-languages#switch-c).

More background + demo code on the Kirby forum: https://forum.getkirby.com/t/multilang-virtual-pages-particular-page-not-translated-howto/26510/10

**Expected behavior**  
`$contentTranslation->exists()` should also account in virtual pages scenario. Possibly with a specific way of setting up the array you feed to `Pages::factory`.

**Screenshots**  
N/A

## To reproduce
See forum for demo code: https://forum.getkirby.com/t/multilang-virtual-pages-particular-page-not-translated-howto/26510/10

## Your setup
3.6.6.1

**Console output**  
N/A

**Your system (please complete the following information)**
N/A

**Additional context**  
N/A

**Comment by distantnative** [comment]
@bvdputte 
Doe it work if your replace `ContentTranslation::exists()` with

```php
public function exists(): bool
{
	return empty($this->content) === false;
}
```
?

**Comment by bvdputte** [comment]
@distantnative , yes, this seems to fix it 👍

**Comment by distantnative** [comment]
We could probably do

```php
public function exists(): bool
{
	return empty($this->content) === false || file_exists($this->contentFile()) === true;
}
```

to avoid some breaking changes.

**Comment by bvdputte** [comment]
This works as well 👍

**Comment by bastianallgeier** [comment]
✅
