### ISSUE TITLE
Table layout:  text-overflow: ellipsis not working for title due to text wrapped in <p> tag

### ISSUE THREAD

**Issue by miragecraft** [k-next/kirby#4677]
Not sure if this is intended or a bug.

When title overflows in table layout, `text-overflow: ellipsis` property for the table cell `<td>` doesn't work because the text is wrapped in a `<p>` tag.

So to the table cell `<td>`, what's overflowing isn't the text, but the `<p>` tag, and for the `<p>` tag, the text isn't overflowing at all as nothing is cut off from `<p>` tag's perspective.

**Comment by bastianallgeier** [comment]
✅
