### ISSUE TITLE
[3.8.0-rc.1] UrlFieldPreview with disabled link is still displayed with `--color-focus`

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4687]
![Bildschirmfoto 2022-09-22 um 22 02 57](https://user-images.githubusercontent.com/1595007/191840339-e7298fb9-3f41-42e3-888a-1e255eee0fb3.png)

In 3.7.x, these disabled links were displayed with the standard text color.

Seems to be introduced by https://github.com/getkirby/kirby/commit/e2c7c20a6052e06339c3a54592d2bd5e91c0212b.

**Comment by bastianallgeier** [comment]
Fixed in my last design changes for the updates check PR.
