### ISSUE TITLE
Structure numbering changes depending on wether limit is set or not

### ISSUE THREAD

**Issue by squareclouds** [k-next/kirby#4695]
## Description
hi everyone,

I just realized, that in kirby 3.7.5 and 3.8.0-rc when a structure has a limit set, the index of the rows starts with 0. if no limit is set it starts with 1. this is only visual though (table numbering in the panel), if you are populating lets say a select/multiselect with this structure, the values are still the same.

**Expected behavior**  
when field has a pagination limit it should also start at 1

**Screenshots**  
![grafik](https://user-images.githubusercontent.com/9073054/192086047-6320d6f2-08f6-4d63-9d70-c880ec568113.png)

## To reproduce
just create 2 simple structures, one with and one without limit for pagination

## Your setup
**Kirby Version**  
3.7.5 and 3.8.0-rc

**Comment by lukasbestle** [comment]
Could be solved by #4386.

**Comment by bastianallgeier** [comment]
✅
