### ISSUE TITLE
[3.8.0-rc.1] Changing URL leads to duplicate folders because of UUID

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4696]
> in a starterkit changing the URL for  notes to blog. The change actually works (renames folder to blog, new blog folder includes all old subpages), but indeed notes remains with default blueprint. Looks like because a UUID is created in the process

<img width="714" alt="Screenshot 2022-09-24 at 14 15 56" src="https://user-images.githubusercontent.com/3788865/192097406-cd1a6ad5-021f-4140-a4e8-4d522e8971fb.png">

**Comment by distantnative** [comment]
My suspicion is that this line https://github.com/getkirby/kirby/blob/develop/src/Cms/PageActions.php#L129 doesn't just remove the old UUID from cache, but also tries to read the old UUID ID from the content file - which as already been moved/removed - and by that generating a new UUID ID and writing it to the content file path of the old page, thus re-creating that content file.

**Comment by lukasbestle** [comment]
That sounds plausible. We could solve that by creating the `Uuid::for()` instance before the actual action. This should already retrieve the UUID from the content file.

**Comment by distantnative** [comment]
Yes. Or even moving up the entire call. Think the UUID cache could be cleared even earlier in that action.

**Comment by bastianallgeier** [comment]
✅
