### ISSUE TITLE
[3.8.0-rc.1] On multi-language site `permalink()` generates URL with locale; then permalink doesn't work

### ISSUE THREAD

**Issue by doup** [k-next/kirby#4698]
## Description

- On a multi-language site
- An URL generated with `permalink()` (using the new UUID) generates URLs containing the locale
- Then Kirby doesn't understand that URL and returns an error

**Expected behavior**  

Either:
- `permalink()` generates the URL without the locale
- **Or preferably**, Kirby knows how to handle a permalink URL that has a locale prefix, e.g. `https://example.com/en/@/page/...`

## Your setup
**Kirby Version**: `3.8.0-rc.1`

**Comment by lukasbestle** [comment]
@distantnative Oh right, I remember we discussed this previously. Does the UUID implementation ensure that only the default language gets a UUID (= the secondary languages always have the same UUID)? In this case we could support the permalink route for all languages and automatically redirect to the language-specific URL.

**Comment by distantnative** [comment]
I would think so, yes. We never pass locales - so my understanding is that in regard to content files always the ones for the default language are used.

**Comment by distantnative** [comment]
@bastianallgeier is there an easy way to make that route independent of language code prefix?

**Comment by doup** [comment]
As an user, I think there is value in handling both forms:
- `https://example.com/@/page/uuid`
- `https://example.com/en/@/page/uuid`

My use case comes from an "event" content which generates a QR using the permalink. It's interesting to be able to generate that permalink/QR for each language separatelly; so it can be used in a spanish poster and a basque poster, each one with a different QR pointing to its language.

Btw, unrelated, does it make sense to shorten even more the permalink? e.g. `/@/p/<uuid>` or even `/@/<uuid>`?

**Comment by lukasbestle** [comment]
> Btw, unrelated, does it make sense to shorten even more the permalink? e.g. `/@/p/<uuid>` or even `/@/<uuid>`?

You can generate permalinks for all kinds of models, including files and later blocks or structure items. So we need the UUID scheme in the URL. Shortening the scheme could work, but then we would need a map between the short and long version, which makes it harder to extend the UUID implementation.

**Comment by bastianallgeier** [comment]
I think it's a nice idea to have language specific UUID permalinks, but we should fix this issue first and then tackle that idea as a new feature.

**Comment by bastianallgeier** [comment]
✅
