### ISSUE TITLE
[3.8.0-rc.1] Reverse relation with UUID via `findBy` not working

### ISSUE THREAD

**Issue by doup** [k-next/kirby#4704]
## Description

- Given I have two content types: `event` and `post`
- Where `post` has a field `relatedevent`, which stores an `event` UUID
- When getting `post => event` relation via `find('page://event-id')` works OK
- But, the other way around `event => post` via `findBy` doesn't work when just using `uuid()`
  - This fails: `$this->kirby()->collection('blog/posts')->findBy('relatedevent', $this->uuid())`
  - This works: `$this->kirby()->collection('blog/posts')->findBy('relatedevent', $this->uuid()->toString())`

**Expected behavior**  

- It should work with just `$this->uuid()`, without the need to cast to string.

## Your setup

**Kirby Version** : `3.8.0-rc.1`

**Comment by distantnative** [comment]
@bastianallgeier what do you think - I though relying on casting to string would work and `$mode->uuid()` could return the UUID instance. But maybe that leads to too many issues in unforeseen places?

**Comment by bastianallgeier** [comment]
@distantnative I really wonder why the string casting isn't already working in the findBy method. This is pretty weird.

**Comment by distantnative** [comment]
Because the method isn't casting it:

```php
public function findBy(string $attribute, $value)
{
	foreach ($this->data as $item) {
		if ($this->getAttribute($item, $attribute) == $value) {
			return $item;
		}
	}
	return null;
}
```

`$value` being the UUID object.

**Comment by bastianallgeier** [comment]
✅
