### ISSUE TITLE
[3.8.0-rc.1] False positives in UUID validator

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4709]
## Description
The following all return `true` despite the string not being a valid Kirby UUID:
```
`Uuid::is('page://')`
`Uuid::is('page://', 'page')`
`Uuid::is('file://')`
`Uuid::is('file://', 'file')`
// etc.
```

**Expected behavior**  

The validation should only return `true` if the string resembles the UUID format both before and (where applicable, i.e. not for `site`) after the slashes

**Additional context**  

Two apparent reasons:
- when a `$type` variable is present, the part after the slashes is not being checked for in `return Str::startsWith($string, $type . '://')`
- when only a string is given, the regex does not seem to check for the presence of at least one character (not very practical, but that would probably manifest the minimum requirement for a UUID with a custom generator?)

**Comment by bastianallgeier** [comment]
✅
