### ISSUE TITLE
3.8 Plugins compatibility

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4713]
## Broken plugins

- [x] https://github.com/getkirby/staticache
  > Declaration of Kirby\Cache\StatiCache::retrieve(string $key) must be compatible with Kirby\Cache\FileCache::retrieve(string $key): ?Kirby\Cache\Value
  
  Issue: https://github.com/getkirby/staticache/issues/12
  PR: https://github.com/getkirby/staticache/pull/13

## Minor issues

- [ ] https://github.com/pedroborges/kirby-meta-tags
  > Missing composer.json version

- [ ] https://github.com/mullema/k3-date-format
  > Missing composer.json version
  
- [ ] https://getkirby.com/plugins/microman/grid-block
  > Missing composer.json version

- [ ] https://github.com/genxbe/k3-fragments
   > Missing composer.json version

- [ ] https://github.com/genxbe/kirby3-instagram
   > Missing composer.json version

- [ ] https://github.com/sylvainjule/kirby-embed
   > Missing composer.json version

- [ ] https://github.com/HashandSalt/kirby3-webp
   > Missing composer.json version

- [ ] https://github.com/felixhaeberle/kirby3-webp
  > Missing composer.json version

- [ ] https://github.com/sylvainjule/kirby-autofocus
  > Missing composer.json version
  
- [ ] https://github.com/mzur/kirby-uniform
  > Missing composer.json version

  PR: https://github.com/mzur/kirby-uniform/pull/229

- [ ] https://github.com/HashandSalt/kirby3-snipcart
  > Missing composer.json version
  > Plugin name doesn't match with getkirby.com

- [ ] https://github.com/lukasleitsch/kirby-blade
  > Missing composer.json version
  > Plugin name doesn't match with getkirby.com

- [ ] https://github.com/sylvainjule/kirby-imageradio
  > Missing composer.json version
  > Plugin name doesn't match with getkirby.com
  
- [ ] https://github.com/jongacnik/kirby-fields-block
  > Missing composer.json version
  > Plugin name doesn't match with getkirby.com
  
  PR: https://github.com/jongacnik/kirby-fields-block/pull/11

- [ ] https://github.com/sylvainjule/kirby-matomo
  > Missing composer.json version
  
  PR: https://github.com/sylvainjule/kirby-matomo/pull/40
  
- [ ] https://github.com/sylvainjule/kirby-locator
  > Missing composer.json version
  
  PR: https://github.com/sylvainjule/kirby-locator/pull/54

- [ ] https://github.com/thathoff/kirby-git-content
  > Missing composer.json version
  
  PR: https://github.com/thathoff/kirby-git-content/pull/95
  
- [ ] https://github.com/sylvainjule/kirby-color-palette
  > Missing composer.json version
  
  PR: https://github.com/sylvainjule/kirby-color-palette/pull/24

## Updated plugins for 3.8

- [x] https://github.com/OblikStudio/kirby-memsource
   > Missing composer.json version

- [x] https://github.com/mullema/k3-image-clip
  > ~Plugin name doesn't match with getkirby.com~
  > Wrong composer.json version with tag name
  
  Issue: https://github.com/mullema/k3-image-clip/issues/26
- [x] https://github.com/schnti/kirby3-cachebuster
  > Missing composer.json version
  
  PR: https://github.com/schnti/kirby3-cachebuster/pull/10
- [x] https://github.com/shoesforindustry/kirby-plugins-alphabetise
  > Missing composer.json version
  
- [x] https://github.com/bnomei/kirby3-handlebars
  > Optional parameter $renderCacheId declared before required parameter $result is implicitly treated as a required parameter
  
  Issue: https://github.com/bnomei/kirby3-handlebars/issues/24

- [x] https://github.com/afbora/kirby-minify-html
- [x] https://github.com/afbora/kirby-template-hooks

- [x] https://github.com/youngcut/kirby-form-blocks
  > Use of deprecated `Kirby\Http\Server`
  
  Issue: https://github.com/youngcut/kirby-form-blocks/issues/25
  PR: https://github.com/youngcut/kirby-form-blocks/pull/26 
- [x] https://github.com/olach/kirby3-relationship
  > plugin does not show the already entered entries anymore
  
  Issue: https://github.com/olach/kirby3-relationship/issues/15

- [x] https://github.com/bnomei/kirby3-mysql-cachedriver
  > Release name doesn't match with composer version: `1.1.0` and `v1.1.0`

- [x] https://github.com/youngcut/kirby-form-blocks
  > Plugin name doesn't match with getkirby.com

- [x] https://github.com/mullema/k3-image-clip
  > The model object must use the "Kirby\Filesystem\IsFile" trait in file: ...\Codebase\kirby\src\Filesystem\File.php line: 448
  
  Issue: https://github.com/mullema/k3-image-clip/issues/25
  Core regression: https://github.com/getkirby/kirby/issues/4748
- [x] https://github.com/lukasbestle/kirby-roomle
  > The installed version of the Kirby Roomle plugin is not compatible with Kirby 3.8.0-rc.2
  
  Issue: https://github.com/lukasbestle/kirby-roomle/issues/1

- [x] https://github.com/lukasbestle/kirby-versions
  > The installed version of the Kirby Versions plugin is not compatible with Kirby 3.8.0-rc.2
  
  Issue: https://github.com/lukasbestle/kirby-versions/issues/11

- [x] https://github.com/tristantbg/kirby-shopify
  > Namespace declaration statement has to be the very first statement or after any declare call in the script
  
  Issue: https://github.com/tristantbg/kirby-shopify/issues/14
- [x] https://github.com/fabianmichael/kirby-markdown-field
  > The installed version of the Markdown field plugin is not compatible with Kirby 3.8.0-rc.1
  
  Issue: https://github.com/fabianmichael/kirby-markdown-field/issues/158
  
- [x] https://github.com/thathoff/kirby-git-content
  > Class "Kirby\Http\Request\Body" not found
  > Type of Kirby\Cms\Url::$home must be ?string (as in class Kirby\Http\Url)
  
  Issue: https://github.com/thathoff/kirby-git-content/issues/94

- [x] https://github.com/bnomei/kirby3-mysql-cachedriver (PHP error)
  > Declaration of Bnomei\MySQLCache::get(string $key, $default = null) must be compatible with Kirby\Cache\Cache::get(string $key, mixed $default = null): mixed

  Fixed by https://github.com/getkirby/kirby/pull/4719

- [x] https://github.com/gearsdigital/localizer-for-kirby/ (PHP error)
  > Undefined constant "DS"
  
  Fixed by https://github.com/getkirby/kirby/pull/4717

 - [x] https://github.com/mauricerenck/kirby-podcaster
   > Plugin tag name doesn't match with composer.json version
  
- [x] https://github.com/gearsdigital/localizer-for-kirby
  > Plugin tag name doesn't match with composer.json version
  
- [x] https://github.com/PaulMorel/kirby3-fathom-analytics
  > Plugin tag name doesn't match with composer.json version

- [x] https://github.com/tristantbg/kirby-shopify
  > Missing composer.json version
  > Plugin name doesn't match with getkirby.com

- [x] https://github.com/tristantbg/kirby-shopify
  > Missing composer.json version
  > Plugin name doesn't match with getkirby.com
  
  Issue: https://github.com/tristantbg/kirby-shopify/issues/14
  Commit: https://github.com/getkirby/getkirby.com/commit/d6ac87229b398bdc76c87498437f321d7211fe43

- [x] https://github.com/fabianmichael/kirby-markdown-field
  > Plugin name doesn't match with getkirby.com
  
- [x] https://github.com/wagnerwagner/merx
  > Plugin name doesn't match with getkirby.com
  
  Commit: https://github.com/getkirby/getkirby.com/commit/7626391e776b25ae25617a82d748d9687df2d2e3

- [x] https://github.com/diesdasdigital/kirby-meta-knight
  > Plugin name doesn't match with getkirby.com
  
  Commit: https://github.com/getkirby/getkirby.com/commit/9c72395e8ea242ce2e6d81c55e0eb5bc0558bfde

- [x] https://github.com/chrisbeluga/kirby-navigation
  >  Plugin name doesn't match with getkirby.com
  
  Release: https://github.com/chrisbeluga/kirby-navigation/releases/tag/3.0.1
  
- [x] https://github.com/d4l-data4life/kirby3-static-site-generator
  >  Plugin name doesn't match with getkirby.com
  
  Commit: https://github.com/getkirby/getkirby.com/commit/ddb3745f9fdfae3a4a6a01e6c15a73c2468d4e0e

- [x] https://github.com/bnomei/kirby3-janitor
   > Plugin tag name doesn't match with composer.json version
  
## Compatible plugins

- [x] https://github.com/diesdasdigital/kirby-3-imgix
- [x] https://github.com/michnhokn/kirby3-logger
- [x] https://github.com/flokosiol/kirby-focus
- [x] https://github.com/floriankarsten/kirby-plausible
- [x] https://github.com/distantnative/retour-for-kirby
- [x] https://github.com/bnomei/kirby3-cloudconvert (there is a bug that not related with 3.8)
- [x] https://github.com/bnomei/kirby3-feed
- [x] https://github.com/OblikStudio/kirby-entity-field
- [x] https://github.com/OblikStudio/kirby-git
- [x] https://github.com/OblikStudio/kirby-link-field
- [x] https://github.com/OblikStudio/kirby-plurals
- [x] https://github.com/genxbe/kirby3-ray
- [x] https://github.com/mullema/k3-panel-view-extended

**Comment by distantnative** [comment]
@lukasbestle see discussion on Discord and https://github.com/getkirby/kirby/pull/4719

**Comment by lukasbestle** [comment]
@distantnative Ah, I missed that. I wrote about this in the "Steps to 3.8.0" thread and you in headquarter. Seems like we missed each other. :D

**Comment by sebastiangreger** [comment]
/plugins/sebastiangreger --> /plugins/sgkirby :pray: ✅

**Comment by ennemoserandre** [comment]
Can you please add the following plugin to the list? https://github.com/OblikStudio/kirby-link-field

I created already a issue: https://github.com/OblikStudio/kirby-link-field/issues/65

**Comment by macx** [comment]
[kirby-form-blocks](https://github.com/youngcut/kirby-form-blocks/issues/25) us not working.

**Comment by trych** [comment]
The [Kirby Relationship Field](https://github.com/olach/kirby3-relationship) plugin does not show the already entered entries anymore. It _does_ list entries, but those are empty.

In the content file, entries are still listed by their ids, so I assume that's the reason. If I add a new entry to the field that one is shown correctly.

![Bildschirmfoto 2022-10-06 um 22 13 25](https://user-images.githubusercontent.com/9803905/194409901-58ee1738-8851-4419-a2b0-2248527b75a9.png)

![Bildschirmfoto 2022-10-06 um 22 16 48](https://user-images.githubusercontent.com/9803905/194410111-bae866b4-90a0-4d52-9f1d-fcde2b754a6d.png)

**Comment by macx** [comment]
[kirby-vite](https://github.com/arnoson/kirby-vite/issues/12) is also broken with this version.

My fault. kirby-vite IS compatible.

**Comment by olach** [comment]
The Relationship plugin is now compatible.
https://github.com/olach/kirby3-relationship

**Comment by splorp** [comment]
Here are a few plugins that I’m using that are missing the required json information, from what I can tell.

https://github.com/pedroborges/kirby-meta-tags
https://github.com/schnti/kirby3-cachebuster
https://github.com/shoesforindustry/kirby-plugins-alphabetise

**Comment by trych** [comment]
~~Unfortunately, the issue with the relationship plugin that I described before has *not* been resolved yet. I still cannot transition a relationship field's content from a 3.7.5 project to a 3.8 project.~~

~~Also, it seems to have some more errors, that seem to be related to 3.8 (they do not happen when I downgrade to 3.7.5). So I would consider it as incompatible again, unfortunately.~~

~~https://github.com/olach/kirby3-relationship/issues/16~~

~~Anybody could have a look at this? This basically broke a client's website. 😥~~

Edit: Sorry, turns out I was not updated to the latest plugin version.

**Comment by texnixe** [comment]
@trych I just tried a fresh relationship plugin in a fresh 3.8.8.1 Starterkit without issues. The example from the readme in a note.yml

```
   related:
        label: Related articles
        type: relationship
        options: query
        query: page.siblings
```

stores the content like this:

```
Related: notes/through-the-desert, notes/chasing-waterfalls
```
as it should (so no uuids), because it is based on the tags field, not the pages field. It also works if I choose to store UUIDs instead. So would be helpful if you could post your field definition that does not work.

**Comment by trych** [comment]
@texnixe Thanks for testing, and it turns out that once again you were absolutely right. For some reason my git submodule command would not show me that there's updates to the plugin, so I assumed I already was on the most recent version, when in fact I wasn't. Sorry for making a fuss about nothing.

So I stand corrected: The relationship plugin works great and is in fact compatible with 3.8.

**Comment by splorp** [comment]
The “Missing composer.json version” for the [Alphabetize](https://github.com/shoesforindustry/kirby-plugins-alphabetise) plugin was fixed with this PR:

https://github.com/shoesforindustry/kirby-plugins-alphabetise/pull/6

I’m still trying to get the developer to create a proper release for the current version.

**Comment by splorp** [comment]
I’ve created a PR to address the composer.json issues for the [Cachebuster](https://github.com/schnti/kirby3-cachebuster) plugin

https://github.com/schnti/kirby3-cachebuster/pull/10

Also contacted the developer to create a release for the current version.

**Comment by splorp** [comment]
This PR https://github.com/schnti/kirby3-cachebuster/pull/10 has been closed by the developer and a fixed version of the plugin has been tagged as a new release.

/schnti/kirby3-cachebuster/releases/tag/1.0.3

**Comment by afbora** [comment]
Information about 3.8 compatibility has been sent to all plugins to open new issue or submit PR. It is the developers decision whether to apply the necessary changes or not.

**Comment by plain-solutions-gmbh** [comment]
> [kirby-form-blocks](https://github.com/youngcut/kirby-form-blocks/issues/25) us not working.

Kirby Form Blocks is no longer under maintenance! Please use [Kirby Form Block Suite](https://github.com/youngcut/kirby-form-block-suite)
