### ISSUE TITLE
[3.8.0-rc.2]: Update check - don't show "version info" button when no info

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4716]
Currently, the button gets only disabled. Which is rather confusing as one has only one dropdown open and can't quite realise the difference between active/disabled right away. Button should simply be hidden when not available.

<img width="393" alt="Screenshot 2022-09-28 at 19 34 25" src="https://user-images.githubusercontent.com/3788865/192850633-306e1078-d0ec-4a90-8cd5-973e2a205ed9.png">

**Comment by bastianallgeier** [comment]
✅
