### ISSUE TITLE
Retrieve plugin versions from `vendor/composer/installed.php` if not provided in plugin's `composer.json`

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4733]
https://github.com/mzur/kirby-uniform/pull/227
https://github.com/mzur/kirby-uniform/pull/229

**Comment by afbora** [comment]
I looked a little. It actually looks easy to implement. Wouldn't it be like this?

````php
public function version(): string|null
{
  $version   = $this->info()['version'] ?? null;
  $version ??= \Composer\InstalledVersions::getPrettyVersion($this->name());
	
  ...
}
````

But there is a point that should not be forgotten. If the `composer.json` file does not contain version information and the plugin is installed with ZIP, the plugin vendor will not contain the plugin version. So if the plugin is installed with composer, this method will work. This means that it will be more stable if the developer always adds version information to composer.json.

For ex: https://github.com/mzur/kirby-uniform/blob/master/vendor/composer/installed.php

As a result, this method will only work for plugins that have no version information in composer.json and are installed with composer not via ZIP download.

**Comment by lukasbestle** [comment]
Yes, pretty much this. However it will throw an exception if the plugin was not installed via Composer. So we should catch that exception and return `null` if Composer doesn't know a version either.

Fully agree on the limitations you describe. It can only be a fallback for plugins installed via Composer. Devs should still set the `version` key.

**Comment by afbora** [comment]
✅
