### ISSUE TITLE
[3.8.0-rc.2] URL to updated plugin repo missing letter `v`

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4734]
## Description
Having version 1.5.1 of the [bnomei/kirby-feed](https://github.com/bnomei/kirby3-feed/releases/tag/1.5.2) plugin installed, the System overview informs about a new version 1.5.2, but the link to `https://github.com/bnomei/kirby3-feed/releases/tag/1.5.2` presents a 404 on Github.

**Expected behavior**  
The link should lead to `https://github.com/bnomei/kirby3-feed/releases/tag/v1.5.2` (with a `v` before the version number)

## To reproduce
1. Install v1.5.1 of the kirby-feed plugin
2. Go to the "Systems" view on the Panel
3. See the info that a new version is available
4. Follow the "Version information" link in the pop-up for that plugin
5. See 404 on Github

## Your setup
3.8.0-rc.2

**Comment by distantnative** [comment]
@lukasbestle could it be that our system just assumes that tags are pure version numbers? Do we need to do some parsing and storing on getkirby.com instead and pass the actual URL?

**Comment by lukasbestle** [comment]
Ah, I fixed getkirby.com yesterday to make the version comparison work by trimming the `v` prefix. But this then brought this regression.

I'll think about a solution.
