### ISSUE TITLE
[3.8.0-rc.2] UUID `mkdir(): File exists`

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#4745]
<img width="979" alt="Screenshot 2022-10-03 at 19 44 46" src="https://user-images.githubusercontent.com/3788865/193643881-53ce916d-5f8a-4773-bbcf-da54d8f2c504.png">

Race condition when multiple sections etc try to populate UUID to cache.
File cache simultaneously tries to create the directories - checks at top of `Dir::make()` don't help due to the concurrency of the requests.

**Comment by bastianallgeier** [comment]
✅
