### ISSUE TITLE
`File::setModel()`: Switch from `class_uses()` to duck test

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4748]
The following lines cause a regression when a model class is extended in a plugin (because `class_uses()` does not check parents):

https://github.com/getkirby/kirby/blob/cfdba1b81fc68d5bdf6561fc47858f6c966100d3/src/Filesystem/File.php#L447-L449

Instead we want to check for the existence of the `root()` and `url()` methods.

See https://github.com/mullema/k3-image-clip/issues/25 for the original discussion.

**Comment by bastianallgeier** [comment]
✅
