### ISSUE TITLE
Fatal errors not logged

### ISSUE THREAD

**Issue by yandodov** [k-next/kirby#4764]
## Description
Errors are never logged in the default PHP log file. On Linux systems, that's likely `/var/log/php-fpm/error.log`. This is an issue when you've disabled debug mode on your live environment and there are HTTP 500 errors. Locally, errors aren't logged even when debug mode is enabled.

**Expected behavior**  
Errors should always get logged in the error log file.

My guess is that this happens because the Whoops handler intercepts the default PHP error handling behavior. If I comment out this line, I correctly see errors logged:

https://github.com/getkirby/kirby/blob/3.5.7.1/src/Cms/AppErrors.php#L96

If I set the `whoops` option to `false` in config.php, it also seems to fix the problem. But I don't want that on production, because now the default PHP error behavior kicks in and spits out file paths, line numbers, and other sensitive information.

In summation, I need Kirby to obscure the error so bad actors can't take advantage of it, while logging it so I can debug it later.

## To reproduce
1. Call an unexisting function in a template, e.g. `lorem_ipsum()` to trigger an error
2. Open the error log file and you should see that there's no error logged

## Your setup
**Kirby Version**  
3.5.7.1

**Your system (please complete the following information)**
- OS: Windows 10

**Comment by lukasbestle** [comment]
I think we should fix this by calling `error_log()` inside this callback:

https://github.com/getkirby/kirby/blob/c77ccb82944b5fa0e3a453b4e203bd697e96330d/src/Cms/AppErrors.php#L82

**Comment by distantnative** [comment]
@lukasbestle that would only be for non-debug more, right? So we'd also need to add it above.

**Comment by lukasbestle** [comment]
Well, in debug mode the full exception and trace is already printed to the screen. So I think it's not necessary there as it would spam the error log.

**Comment by lukasbestle** [comment]
Oh, also here for JSON errors with disabled `debug`:

https://github.com/getkirby/kirby/blob/c77ccb82944b5fa0e3a453b4e203bd697e96330d/src/Cms/AppErrors.php#L134

**Comment by distantnative** [comment]
Could be still consistent to log actual any php error and not to swallow them. That's also what @hdodov stated

**Comment by yandodov** [comment]
> Well, in debug mode the full exception and trace is already printed to the screen. So I think it's not necessary there as it would spam the error log.

I don't agree. What if you have a staging server where you want `debug` mode enabled, but also want to SSH on the machine to see previously logged errors?

It'd be great if PHP errors are logged as usual, as if you're not using Kirby, but just plain PHP. This shouldn't change with either the `debug` setting or the `whoops` setting. An error occurs - it gets logged. There's no value in keeping the logs clean. Their purpose is to be verbose. Take the `access.log` for example.

**Comment by distantnative** [comment]
We could probably push another callback handler here https://github.com/getkirby/kirby/blob/c77ccb82944b5fa0e3a453b4e203bd697e96330d/src/Cms/AppErrors.php#L160 that logs any kind of error. Then we don't have to implement it in several places.

**Comment by lukasbestle** [comment]
Great idea, let's do it like that!

**Comment by distantnative** [comment]
✅
