### ISSUE TITLE
Password autofill in Chrome disables the field's `border-radius`

### ISSUE THREAD

**Issue by janstieler** [k-next/kirby#4767]
Hi,
if the password field in the panel login form is prefilled the blue background from Chrome breaks the borderradius.
I'm actually not sure if this is fixable. As we know the prefill makes some headaches.

![Bildschirmfoto 2022-10-06 um 19 41 26](https://user-images.githubusercontent.com/754880/194382652-3afc5df4-8fe8-449b-a364-b44322ee7669.jpg)

**Comment by lukasbestle** [comment]
Don't think that's fixable TBH because Chrome injects some magic into the UI that we don't have any control over.

**Comment by distantnative** [comment]
@janstieler maybe you could test with a [custom Panel CSS](https://getkirby.com/docs/reference/system/options/panel#custom-panel-css) whether the prefilling from Chrome can be styled via https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill

**Comment by janstieler** [comment]
Hi,
I tried a little bit and it was easy to fix with:
```
.k-input[data-theme=field] .k-number-input, 
.k-input[data-theme=field] .k-select-input, 
.k-input[data-theme=field] .k-text-input {
    border-radius: 3px 0 0 3px;
```
and this is in the regular panel.css .
![Bildschirmfoto 2022-10-08 um 20 44 17](https://user-images.githubusercontent.com/754880/194722819-ad278e13-5e79-4ce0-b334-d6c1e3c48150.jpg)


Cheers

**Comment by bastianallgeier** [comment]
✅
