### ISSUE TITLE
Field overflowing in structure field due to `grid-column-gap`

### ISSUE THREAD

**Issue by HYR** [k-next/kirby#4772]
## Description
Fields are not staying contained within a `width: 1/3` structure field in the sidebar. See screenshots.

**Expected behavior**  
Expected the fields to adapt to the size of the container.

**Screenshots**  
<img width="415" alt="CleanShot 2022-10-07 at 17 47 14@2x" src="https://user-images.githubusercontent.com/5200901/194676181-9156639a-82d2-4b0a-a1d0-5c805673ba66.png">

<img width="531" alt="CleanShot 2022-10-07 at 18 07 41@2x" src="https://user-images.githubusercontent.com/5200901/194677075-a4c49052-a113-4118-b1e5-aca4bd018449.png">

## To reproduce
1. Create a block or modify a `block`
2. Add a `structure` field to the `drawer`.
3. Set it's width to `1/3`
4. Add an empty `select` field
6. Open the `block settings`
7. Edit the structure field (add a new entry)
8. See the overflow

## Your setup
**Kirby Version**  
Kirby 3.7.5

**System**
 - Device: MBP
 - OS: macos 12.6
 - Browser: Brave
 - Version: Version 1.44.105 Chromium: 106.0.5249.91 (Official Build) (x86_64)

**Additional context**  
Using `clamp` seems to fix the problem though I'm not sure the right values to use:

```
.k-fieldset .k-grid {
    grid-column-gap: clamp(0rem, 1rem, 1.5rem);
}
```

**Comment by distantnative** [comment]
`clamp(0rem, 1rem, 1.5rem)` will always be just `1rem`, if I understand clamp correctly.

**Comment by distantnative** [comment]
Will be fixed in upcoming v4-alpha.5
