### ISSUE TITLE
Kirbytextinline doesn't parse most of Kirbytext & Markdown

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#4776]
## Description

Kirbytextinline seems to be broken. Running the following code or it's deviations (`$field->kirbytextinline()` and `kirbytextinline()`) doesn't parse headlines, lists and quotes:

```php
<?php echo $page->text()->kti() ?>
```

Kirbytext without inline works correctly.

**Expected behavior**  

All kirbytext should get parsed.

**Screenshots**  

The link gets parsed (made it visible by unsetting the color and text-decoration in the starterkit). Other things don't get parsed:

![Screenshot 2022-10-10 at 13 44 18](https://user-images.githubusercontent.com/60777/194859239-c2e06bb7-e1a3-458f-966d-6cbd6cf49eb2.png)

## To reproduce

1. Checkout latest starterkit (at time of writing: Kirby 3.8.0)
2. Add`<?php echo $page->text()->kt() ?>` to snippets/intro.php
3. Edit content/home/home.txt and add:

```md
----

Text:

# Test

(link: https://google.com text: Link to Google)

## List

- First
- Second

## Quote

> Lorem ipsum nulla eu ut sit cupidatat culpa anim ut in veniam.
```

## Your setup
**Kirby Version**  
 - Kirby Version 3.5.3.1 and 3.8.0. Fails in both versions.
 - PHP 8.0.21 (I hope it's not because of 8.0)

**Comment by distantnative** [comment]
@mrflix I don't think this is a bug. You are choosing the methods/helpers that are for parsing inline Markdown/Kirbyytext. But then you throw at it text that isn't inline at all but all kinds of paragraphs, headlines, blocks... that kind of negates what the inline method is meant to return.

Why would you not use the normal kirbytext methods for your case?

**Comment by mrflix** [comment]
That makes total sense 🙈 for me `kti` was always `kt` but without the paragraphs around the content. Obviously, headlines don't make sense here.
