### ISSUE TITLE
[Kirby 3.8.0] go($site->homePage()) redirects to '/home' instead of '/'

### ISSUE THREAD

**Issue by tristantbg** [k-next/kirby#4781]
## Description
go($site->homePage()) redirects to '/home' instead of '/'

**Expected behavior**  
go($site->homePage()) should redirect to '/'

## Your setup
**Kirby 3.8.0**

**Comment by afbora** [comment]
May be you need to use like that:

````php
// with site url
go($site->url());

// or homepage url
$site->homePage()->go();
````

**Comment by tristantbg** [comment]
Yes I fixed it with go($site->url()); but I was just mentioning this new behavior as it can break older websites.

**Comment by afbora** [comment]
Older? Which Kirby version are you talking about? 🤔I need to test it. 
As far as I know this behavior has not changed and is the same in 3.7.x versions.

**Comment by tristantbg** [comment]
Yes, older than this. I had a website on [3.6.6](https://github.com/getkirby/kirby/releases/tag/3.6.6) that was using this.

**Comment by afbora** [comment]
@tristantbg Thanks for report and testing. Yes, in 3.6.6 works great but in 3.8.0 broken.

**Comment by lukasbestle** [comment]
With which version and commit did we introduce this?

**Comment by afbora** [comment]
Since there are too many commits, I haven't found which PR or commit is causing this problem yet, but it doesn't work in 3.7.0-RC1. I'm not sure but I think it has to do with the `New Environment class` PR #4285

**Comment by lukasbestle** [comment]
We could find the exact commit with `git bisect`, but I guess we don't need to. It's indeed very likely that it's caused by the environment refactoring if the issue was introduced in 3.7.0.

**Comment by bastianallgeier** [comment]
✅
