### ISSUE TITLE
Content not rendered when publishing a text area in a block filed inside a layout field inside a structure.

### ISSUE THREAD

**Issue by hey-low** [k-next/kirby#4785]
## Description

Typing content with a paragraph in a textarea (from a custom block) in a layout without in a structure field. (A structure > Layout > Custom bloc > Textarea field) creates a bug.
When the content is saved, it disappears.

In the content file (.txt), creating a new paragraph (pressing Enter key) is rendered as “\n” and this seems to break the content and the reason why it is not saved.

Switching the textarea field to a writer field seems to solve the problem by applying a `<p></p>` instead of ‘\n’.

Previously asked in the forum:
https://forum.getkirby.com/t/a-new-paragraph-in-a-textarea-field-within-a-structure-field-breaks-the-content/26572

**Expected behavior**  

The content should not disappear.

## To reproduce
Create a text area in a block filed inside a layout field inside a structure.

## Your setup
**Kirby Version**  
 Kirby 3.7.5

**Comment by distantnative** [comment]
@hey-low Would you be able to provide your blueprint (or a minimal blueprint that reproduces the problem)? That would help a lot. Thanks.
