### ISSUE TITLE
Parsing issue for Youtube Shorts video url

### ISSUE THREAD

**Issue by seb-celinedesign** [k-next/kirby#4791]
## Description
When I insert a Youtube Shorts video url in a Video block, the video is not displayed.
Example : https://www.youtube.com/shorts/cEyhY3SYKCE

the `public static function youtube()` is not correctly parsing this kind of url.
Even if it's not very well documented, Youtube is currently allowing Short to be embed like any other traditionnal video, with the same iframe url.
Example : 
```
<iframe
 width="720"
 height="576"
 src="https://www.youtube.com/embed/cEyhY3SYKCE"
 title="YouTube video player"
 frameborder="0"
 allowfullscreen>
</iframe>
```

## Your setup
**Kirby Version**  
Kirby 3.8

**Comment by bastianallgeier** [comment]
✅
