### ISSUE TITLE
Svg: wrong width and height dimensions detected

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#4793]
I'm working with this svg file and got confused because `$file->width()` returned `100` while it's actually `331`:

![bistum-hildesheim-schwarz](https://user-images.githubusercontent.com/60777/196637158-290e876b-806b-4dbe-a5ca-7a64814d4e85.svg)

Turns out the width and height are set to `100%` and the real dimensions are in the the `viewBox`. I extracted the logo out of a pdf file and exported it using Affinity Photo. While I would say that the svg file is wrong it would still be cool if Kirby would master it. 

Currently (Kirby 3.8.1) `Dimensions::forSvg` reads the `width` and `height` attributes and falls back to the values in `viewBox` when either `width` or `height` are zero:

```php
$attr   = $xml->attributes();
$width  = (int)($attr->width);
$height = (int)($attr->height);
if (($width === 0 || $height === 0) && empty($attr->viewBox) === false) {
	$box    = explode(' ', $attr->viewBox);
	$width  = (int)($box[2] ?? 0);
	$height = (int)($box[3] ?? 0);
}
```

What do you think about checking the uncasted values for a percentage sign and resort in that case to `viewBox` too to get the correct dimensions?

**Comment by lukasbestle** [comment]
Yes, I think that makes sense.

It also looks like the fallback to viewBox will break if the first two values of the viewBox are not `0 0`. I think the calculation should subtract the first two values from the second two.

**Comment by distantnative** [comment]
✅

**Comment by mrflix** [comment]
Thank you Nico!
