### ISSUE TITLE
Don't allow accidental Kirby license registrations to non-existing TLDs

### ISSUE THREAD

**Issue by trych** [k-next/kirby#4795]
## Description
While deploying a new site, I registered the new site and then promptly lost the registration again by re-uploading my local site folder. Then I thought, well let me instead register it locally, so it's registered and then push it online.

Well, as you can guess (and I couldn't) that made it registered to my local testing domain `foo.test`. And now I cannot change this anymore. Not sure why it chooses to stick with the second registration that I tried and not with the first one, but ...

It would be great if the registration system would be smart enough to realize that `foo.test` is *obviously* a local testing domain and should not be the domain to marry your license with permanently.

I guess deployment issues like this can happen, so it would be good if domains like `foo.test` are just ignored and the system waits for the actual domain to register with.

**Expected behavior**  
Don't allow licenses to register to domains like `foo.test`.

**Comment by lukasbestle** [comment]
I understand your case and agree that this behavior would make sense for most sites. However there are also valid use cases where you would want to register a license on a local domain, e.g. when the site is deployed in an intranet (which requires a paid license as well). So it's difficult to find a good middle ground.

A possible option could be a warning like "You are registering Kirby on a local domain. If this site will be deployed to a public domain, please register it there. Are you sure you want to proceed?".

PS: Your license is not lost, you can still get the registration changed by contacting us at <mail@getkirby.com>.

**Comment by trych** [comment]
> A possible option could be a warning like "You are registering Kirby on a local domain. If this site will be deployed to a public domain, please register it there. Are you sure you want to proceed?".

That would be good, it would be even better to generally have a window "You are about to permanently link your license to the domain "foo.com", do you want to proceed?"

That way, I would notice when I'm about to do this with a test domain and could always double check that I am doing this to the correct domain. Also, the current locking after the second (?) attempt is super weird and intransparent. This gives me the feeling: "Oh, I did something wrong, but seems like I can re-do it" and then suddenly with the second attempt, I can not undo it anymore.

**Comment by distantnative** [comment]
@lukasbestle do you know why we use `$system->indexUrl()` in `System::register()` and not `$system->licenseUrl()`?

**Comment by lukasbestle** [comment]
`$system->licenseUrl()` performs normalization at runtime (called from `$system->license()`). If we already applied it during registration, we would "burn in" those normalizations into the license file.

Storing the "raw" index URL in the license file allows us to change the normalization code later, e.g. if there are edge cases that we want to support with a single license.

**Comment by distantnative** [comment]
Where I am currently at:
<img width="591" alt="Screenshot 2022-12-10 at 17 39 28" src="https://user-images.githubusercontent.com/3788865/206865472-7321a177-9e72-4d3c-a081-df646651c456.png">


Could use some help with the phrasing:
> You are about to register your license for your local domain sandbox.test. If that's what you want, please continue.

**Comment by lukasbestle** [comment]
I like that the message includes the domain name, which makes much more clear what's happening. But I'm missing an explanation *why* one might not want to register the license locally.

Maybe something like this:

> You are about to register your license for your local domain sandbox.test. If this site will be deployed to a public domain, please register it there. If sandbox.test is the domain you want to license Kirby to, please continue.

**Comment by distantnative** [comment]
I like that:
<img width="602" alt="Screenshot 2022-12-10 at 18 02 33" src="https://user-images.githubusercontent.com/3788865/206866589-69e68d12-5409-4098-9b13-42d2ca865438.png">

Having the domain shown might be a good idea in general. How about in addition:
<img width="622" alt="Screenshot 2022-12-10 at 18 03 43" src="https://user-images.githubusercontent.com/3788865/206866605-ae335a0c-1f1e-48c5-81b5-e3fe82b183f9.png">

(of course imagine with a real non-local domain)
> You are about to register your license for your domain sandbox.test.

**Comment by lukasbestle** [comment]
I really like that. Maybe with the `info` color though.

**Comment by trych** [comment]
I would change the second sentence of the warning to "If this site will be deployed to a public domain, please register it there *instead*." (emphasis mine, should not go into the final text). That way it's even clearer that you should not go ahead and register it to sandbox.test.

**Comment by distantnative** [comment]
✅
