### ISSUE TITLE
Pickers `Invalid value for "value"` error when model with uuid not found

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4797]
## Description

If the picker field cannot find the model with the uuid, it will throw an error and the selection will be impossible.

**Screenshots**  

![captures_chrome-capture-2022-9-20](https://user-images.githubusercontent.com/3393422/196950571-8fb42efd-7e26-47c5-bf92-752ac284d4d7.png)

## Your setup
**Kirby Version**  
3.8.1

**Comment by bastianallgeier** [comment]
✅
