### ISSUE TITLE
Domain specific .config file does not work

### ISSUE THREAD

**Issue by trych** [k-next/kirby#4799]
## Description
In my project, I have a domain specific .config file (named config.foo.de.php) that is supposed to turn off debugging in production:

```php
<?php

return [

  'debug' => false

];
```

I noticed now that in the panel, the system page tells me that debugging is still turned on. And indeed, if I create an error the debugging mechanism kicks in (yes, I double checked the domain + tld in the file name and double checked that I am testing on my production server).

I have used the same setup *without* any issues in the past.

**Expected behavior**  
Debugging should be turned off if specified in the domain specific .config file.

## Your setup
**Kirby Version**  
3.8.1

**Comment by afbora** [comment]
I've tested and works great as expected on 3.8.1. I'm not sure but do you have custom `url` option or reverse-proxy setup?

**Comment by trych** [comment]
No custom `url`option and I don't know what a reverse-proxy setup is, so I don't think so.

I have set this up on Uberspace with the setup that is described [here](https://manual.uberspace.de/web-documentroot/#example-how-to-change-documentroot-location), so on the server, there is a symlink pointing at my `public/dist` folder with bundled files.

**Comment by lukasbestle** [comment]
@trych I have set up a Starterkit on Uberspace in the same symlink setup. I then created a file `site/config/config.domain.com.php` with the following content:

```php
<?php

die('This file was loaded.');
```

The output was as expected (both with Kirby 3.8.1 and 3.8.2). Can you still reproduce the issue?
