### ISSUE TITLE
UUIDs get copied to and generated on secondary languages

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4802]
## Description

If I create a new page in a multilang setup, I get a UUID in the primary language as expected. But once a translation is created by saving a secondary language, this UUID is then copied to the content file of the secondary language.

Also if I have a migrated page (without UUID) and access `$page->uuid()` when a secondary language is active, the UUID is generated and stored for the secondary language. The `Uuid` field of the primary language stays empty.

**Why this is fatal:** If a UUID gets generated in a secondary language, a *different* UUID may later be generated in the primary language. At this point the same model will have more than one UUID.

**Expected behavior**  

- UUIDs should only be generated for the primary language.
- All content files of secondary languages must not get the `Uuid` field (basically the behavior should be that of `translate: false`).
- When querying the content for the `Uuid` field, Kirby should always look at the primary language (even if a different value is stored in the secondary language).

### Copy UUID to secondary language

**Prerequisites:**

1. Enable multilang (here with `en` as default and `de` as secondary)
2. Create a new page (gets `.en.txt` content file, which contains a `Uuid` field)

**Reproduction:**

3. Switch to the secondary language in the Panel, change something and save the content
4. See that the `Uuid` field gets copied to the secondary language.

### Generate UUID on secondary language

**Prerequisites:**

1. Enable multilang (here with `en` as default and `de` as secondary)
2. Manually create a new page without the `Uuid` field
3. Put `$page->uuid()` into the template somewhere

**Reproduction:**

4. Access the page in the secondary language
5. See that the UUID is saved to the secondary language.

## Your setup
**Kirby Version**  

3.8.1

**Comment by afbora** [comment]
✅
