### ISSUE TITLE
the number of page:xxx is not in $page

### ISSUE THREAD

**Issue by Anjade** [k-next/kirby#4828]
When i try to work with multi languages and linking from a blog-page 

page:x, x > 1; then i dont have this number x.

I have the slug, i have the num, but i dont have x; but without that x i cant link from 

lang1/blog/page:x to lang2/blog/page:x

**Comment by distantnative** [comment]
Have a look at https://getkirby.com/docs/reference/templates/helpers/param

**Comment by Anjade** [comment]
Thank you.

**Comment by Anjade** [comment]
This helps

https://getkirby.com/docs/reference/templates/helpers/params

Now i can ask

if 'page'
if 'tag'
