### ISSUE TITLE
Translation of tags

### ISSUE THREAD

**Issue by Anjade** [k-next/kirby#4829]
If i understood it right, i can:

write an article for my blog and set tags for every language

or

add options to set up tags and different translations

but there is nothing to setup

page => tags => tag1, tag2, tag3

translation_table:
tag1 => tug1, 
tag2 => tug2,
tag3 => tag3

?

This means that a user with permission to add articles for the blog cant add new tags in two languages, that are shown in the right language. This means i never can link from:

blog/tag:tag1_lang1 to blog/tag:tag1_lang2 ?

**Comment by Anjade** [comment]
Can i fetch for lang1/blog/article
all tags for lang1 and all tags for lang2?

**Comment by distantnative** [comment]
Please take such general support questions to http://forum.getkirby.com - I'm sure there you'll find help :)
