### ISSUE TITLE
Missing template meta data causes 502 in panel file field

### ISSUE THREAD

**Issue by sebastiangreger** [k-next/kirby#4830]
## Description
When a blueprint has a file field configured with `template: image` or `query: page.images.template('image')`, the Panel displays a 502 error if the file stored in the content file for that field (e.g. `Cover: - dark-forest.jpg`) does not have a template assigned in its meta data.

I have not investigated systematically, but based on a quick experiment this may even occur if the file referenced from the content file has a template meta (e.g. `Template: xyz`) that does not match the template required by the blueprint.

**Expected behavior**  
Graceful failure. While this condition is probably a rather exceptional edge case, I'd either expect some kind of error message or the display of the file that has been defined in the content file, even if it does not comply with the current requirement for a specific template? This situation of a missing template info in the file meta data can for example stem from an earlier content migration or, if it applies not only to missing but also to mismatching template names, from a change in the blueprint vs. older content created with other settings.

## To reproduce
1. In a Starterkit, open `content/2_notes/20201210_exploring-the-universe\dark-forest.jpg.txt` and remove the meta data stating the template
2. Open the Note "Exploring the Universe" in the Panel
3. See error

## Your setup
3.8.1.1

**Comment by afbora** [comment]
I've tested on 3.8.1.1 with no `template` data for file and `Cover: - dark-forest.jpg` for page data. I couldn't reproduce the issue 🤷‍♂️

**Comment by texnixe** [comment]
I can't reproduce this issue either.

**Comment by sebastiangreger** [comment]
@afbora @texnixe – I'll have another look when I find a moment and get back to you

**Comment by sebastiangreger** [comment]
Mystery solved: after digging really deep it turns out a mysterious configuration error with Nginx/PHP/Xdebug caused this. Sorry for the false alert, but it being so reproducible ("Did you try on a fresh Starterkit?" :sweat_smile:) led me to believe it's a bug.
