### ISSUE TITLE
Duplicating pages also duplicates file UUIDs

### ISSUE THREAD

**Issue by FynnZW** [k-next/kirby#4831]
## Description
**Problem A:** 
If you duplicate a page, and activate 'copy files?', the files do not get assigned a new, unique ID.
Instead the file UUID gets copied and is no longer unique.
 This is especially bad when you replace a photo on the new page, and it affects the original page as well.

**Problem B:**
Also, not activating 'copy files?' used to generate a new page with only text content and no images. Now, it still copies the file-UUIDs from the original content file, and keeps the connection to the images from the original page.
This can be confusing for the user, because it is not obvious where those images are coming from. 

### Expected behavior

Problem A:
 Duplicating a page with files should generate new UUIDs for all files.

Problem B:
Duplicating a page without files should remove links to file UUIDs not belonging to the new page.

### To reproduce
1. Create a page with images
2. duplicate that page 
    A) with files and
    B) without files

## Your setup
**Kirby Version**  
3.8.1.1

**Comment by bastianallgeier** [comment]
✅

**Comment by afbora** [comment]
> Also, not activating 'copy files?' used to generate a new page with only text content and no images. Now, it still copies the file-UUIDs from the original content file, and keeps the connection to the images from the original page.
This can be confusing for the user, because it is not obvious where those images are coming from.

FYI, the related PR doesn't fix this `B` case. This is quite a complex situation. When we consider nested fields (blocks, layout, structure, object, etc..) and kirbytags, it seems unlikely that the system will find and delete associated files. If you need such use, you can use the `store` option in the files field instead of the UUID with the ID: https://getkirby.com/docs/reference/panel/fields/files#field-properties

**Comment by FynnZW** [comment]
Great, thank you!

Regarding case `B`:
With Kirby <= 3.7, the content.txt was simply copied, and no images, pointing to an image that didn't exist anymore in that folder:
```
Cover: - monster-trees-in-the-fog.jpg
```

The panel handled that invalid link nicely by just not showing any image.
Now with UUIDs, the panel still can find that image from the original page and displays it.

Just an idea: Since the file links have a very distinctive pattern, wouldn't it be possible to use regex 
(maybe `file:\/\/[\w]{16}`) to invalidate file links during duplication?
```
Cover: - file://soTV5M2PG5DJfuHw
``` 
becomes
```
Cover: - file://
``` 

Or is that replacement operation too risky?

I would just be nice to be able to use file UUIDs while still having the old, more natural duplication behaviour: 
When duplication without images -> no images on new, duplicated page.

**Comment by afbora** [comment]
It might work, but it looks way too hacky to me. I am not sure. Let's find out what other members of the team think @getkirby/kirby-staff 👀

**Comment by FynnZW** [comment]
I've posted that again as a new issue, it's probably easier that way
