### ISSUE TITLE
Data::decode on a pure `json_encode` string fails

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#4836]
## Description
Given following code:

```php
Data::decode(json_encode('a ha!'), 'json');
```

Kirby will throw `Kirby\Exception\InvalidArgumentException: JSON string is invalid`, which is clearly (?) wrong, given that we're decoding _just encoded_ JSON string. This is due to naive (?) decode correction check in `Data::decode` for json, where it does `json_decode` and checks that the result is an array, which in this case isn't, because the encoded thing is a string.

**Expected behavior**  
string `a ha!`

## Your setup
**Kirby Version**  
3.8.1

Edit: formatting, some words.

**Comment by afbora** [comment]
> The `Data` class provides readers and writers for data.

IMHO, I think the current behavior looks correct. The `Data` namespace is not a toolkit. It is for the necessary data for Kirby. So I think if the developer sends data that is not a standart json string, I think it is correct to throw an exception to warn him.

In addition, as far as I looked the codes; if `Data::decode` returns `string` with the behavior you expect, it seems to affect the entire data read-write process. That would be a breaking change that no one would want 🙂

**Comment by adamkiss** [comment]
@afbora Of course!

The thing is - I vaguely remember the `Data` class being used not only for the core, but also for recipes and recommended on forums/Discord (I might be wrong here!) for other things, in which case this _is_ a problem, I think.

Of course, in the end, I mostly just raised this for the Kirby team to be aware of this. If you decide that "nah, good enough, for other usecases use `json_encode`", I am totally okay with it.

**Comment by distantnative** [comment]
The Data class usually has the assumption that the data to be encoded/decoded is not a single item (e.g. string) but multiple (an array).

**Comment by lukasbestle** [comment]
I agree with Ahmet and Nico. The `Data` package only supports arrays. Any non-array value would cause a fatal error because of the method's type hint.
