### ISSUE TITLE
Trailing dot on page route should trigger 404

### ISSUE THREAD

**Issue by s3ththompson** [k-next/kirby#4843]
## Description
The path `/account.` currently resolves to the page at `/account`.

Pages with nonexistant content representations (e.g. `/account.json`) currently return 404. For consistency, `/account.` should be treated the same (either as a "nonexistant content representation" or as invalid syntax).

I discovered this problem when trying to use a custom route to block access to my Account page:

```php
<?php
return [
    'routes' => [
        [
            'pattern' => ["account", "account/(:all)"],
            'action' => function () {
                if (!kirby()->user()) {
                    return go("/login");
                }
                return $this->next();
            }
        ]
    ]
];
```

The path `/account.` did not match my custom route, but Kirby resolved it to my account page, skipping the user login check entirely.

**Expected behavior**  

`/account.` should be treated as either a nonexistant content representation or as invalid syntax. This will make it possible to consistently overwrite the default path resolution behavior with a simple custom route.

## To reproduce

1. Publish a page with a given slug e.g. `/example`
1. Access the page with the path `/example.`
1. (Optionally) Compare to accessing the page with a nonexistant content representation `/example.json`

## Your setup
**Kirby Version**  
3.7.5

**Your system (please complete the following information)**
 - Device: M1 MacBook Air
 - OS: macOS 12.4
 - Browser: Chrome
 - Version: 106

**Comment by splorp** [comment]
I can confirm this behaviour under the following setup as well.

**Kirby Version**
3.8.1

**PHP Version**
8.0.8

**System**

Device: MacBook Pro (Retina, 15-inch, Mid 2015)
OS: macOS 10.13.6
Browser: Vivaldi
Version: 5.5.2805.42 (Chrome 106)

**Comment by distantnative** [comment]
✅
