### ISSUE TITLE
UUID to page conversion doesn't work when paginated, and `url` set in config

### ISSUE THREAD

**Issue by n-kort** [k-next/kirby#4860]
## Description
Using `page('page//example-uuid')`, or `$field()->toPage()` on paged templates results in this error:

<img width="1390" alt="Screenshot 2022-11-22 at 19 11 37" src="https://user-images.githubusercontent.com/1377218/203534812-d89274fc-681c-4c62-b4ca-0d0f32c56d7d.png">

I'm using a structured field for menu settings in the `site.yml`, and when trying to loop through it in the template this happens. Specifically, any URL with `/page:[n]` after it.

While investigating I tried changing the 'url' settings in the config.php, turns out this happens when `'url' => '/'`, which I had set as a fix for mixed content warnings on the server.

**Expected behavior**  
The methods should work the same on `/news` and `/news/page:2` etc etc

## To reproduce

1. Set `'url' => '/'` in your config
2. Add `page('page//any-uuid')` to a template
3. Go to eg `/news/page:2`

## Your setup
**Kirby Version**  
3.8.2
php 8.1

**Comment by lukasbestle** [comment]
I cannot reproduce this issue in the Starterkit with the steps you explained.

Is the missing colon (`page//` instead of `page://`) a typo or is this the actual code you used? In this case, please ensure you add the colon, otherwise the page lookup won't work.

**Comment by n-kort** [comment]
Hmm, no the colon I guess was irrelevant since the IDs were mainly coming from structured fields... but I can't reproduce it again either 😬 I must have changed something else or misidentified the source of that error.

Thanks for looking into it @lukasbestle, I'll close and test more in Starterkit if it crops up again!
