### ISSUE TITLE
`$page->uuid()->value()` should return the UUID's string value

### ISSUE THREAD

**Issue by igregson** [k-next/kirby#4863]
## Description

`$page->uuid()->value()` should return the UUID string value but it instead returns the page's ID. 

`$page->uuid()->id()` returns the page's UUID string. 

This is so confusing that it certainly must be a bug. If it's intended it seems it should be really well documented. Took me a good long while to sort this out (finally found someone pointing this out in Discord, [here](https://canary.discord.com/channels/525634039965679616/525641819854471168/1040138367356125255)).

**Expected behavior**  

`$page->uuid()->value()` should return the UUID string.

## Your setup

**Kirby Version**  

3.8.2

**Comment by texnixe** [comment]
The methods and what they return is documented here: https://getkirby.com/docs/reference/objects/uuid/uuid

**Comment by distantnative** [comment]
@igregson 
> $page->uuid()->value() should return the UUID string value

Is that your personal opinion or did you get anywhere from that this would be the case (contrary to the docblock/reference docs stating that you would get the cache value for that UUID)?

**Comment by johannschopplich** [comment]
I may have a similar use-case to @igregson one's. Writing API endpoints requires to call `toArray()` or `value()` on fields most of the time. Except for UUIDs, I have to weirdly use `toString()` just to make sure the ID is returned and the cache pupulated. Doesn't feel semantic:

```php
'images' => $page
  ->images()
  ->map(fn ($i) => [
    'id' => $i->id(),
    'uuid' => $i->uuid()->toString(),
    'url' => $i->url(),
    'alt' => $i->alt()->value()
  ])
  ->values()
```

**Comment by igregson** [comment]
@texnixe Thanks for pointing me to the docs on this (I hadn't found that specific page). 

@distantnative No, I hadn't seen those specific docs so was only working off of the semantics (which don't really seem semantic, as @johannschopplich points out). 

I suppose this technically isn't a bug, after all, but it does seem like a place where the API could be much more semantic/intuitive.

@johannschopplich When you say, "and the cache populated", this seems to imply that some of the other methods (that also return the string value) might not populate the cache (such as `$uuid->id()`). Anyone know if this is the case?

**Comment by lukasbestle** [comment]
> When you say, "and the cache populated", this seems to imply that some of the other methods (that also return the string value) might not populate the cache (such as `$uuid->id()`). Anyone know if this is the case?

The cache is automatically populated whenever `$uuid->toString()` or `$uuid->model()` is called, but not when calling `$uuid->id()`. The reason for this is that calling the `toString()` method signifies the intent to reference the UUID from another place, which makes a cache lookup very likely. A pure `id()` without scheme is not useful for references.

**Comment by distantnative** [comment]
@johannschopplich 
I do get your argument in some way - but it'd be quite some breaking change hassle to remap everything and make `->value()` work.

And would this be so much better?
```php
  ->map(fn ($i) => [
    'id' => $i->id(),
    'uuid' => $i->uuid()->value(),
    'url' => $i->url(),
    'alt' => $i->alt()->value()
  ])
  ```
  You'd still have some lines with and some lines without `->value()`.
  
 You could already do
  ```php
  ->map(fn ($i) => [
    'id' => $i->id(),
    'uuid' => (string)$i->uuid(),
    'url' => $i->url(),
    'alt' => (string)$i->alt()
  ])
  ```
  for more consistency

**Comment by johannschopplich** [comment]
Good point. I like the `(string)$i->uuid()` approach a lot, also for the other `value()` calls. The only downside: For KQL usage (which is my primary one), I still have to use `toString()`…

**Comment by distantnative** [comment]
Ok, I can see the perspective that a different naming could've bee better/more consistent throughout the system. As a conflicting `::value()` method already exists, this is not a simple change to make. This is neither a bug, the functionality is there and working. Just with a different naming that you would prefer. I would like to ask you to [add it to Nolt](https://kirby.nolt.io), so that we can get a better understanding for prioritising.
