### ISSUE TITLE
When duplicating a page with subpages in the panel, the newly created subpages don't have new UUIDs

### ISSUE THREAD

**Issue by MikeHarrison** [k-next/kirby#4864]
## Description
When using the panel to duplicate a page with subpages, the new subpages keep the UUIDs of the pages they were copied from, instead of having new ones generated

**Expected behavior**  
I would expect all the new subpages to have new UUIDs generated

## To reproduce

1. Create a new page, and create some subpages, in the panel
2. Click on the 3 dot menu for the new parent page and select "Duplicate"
3. Check the UUIDs of the subpages in the newly duplicated page, they will be the same as the originals

## Your setup
**Kirby Version**  
3.8.2

**Your system (please complete the following information)**
 - Device: Mac mini 2018
 - OS: 13.0.1
 - Browser: Firefox
 - Version: 107.0

**Comment by afbora** [comment]
We just copy top directory to duplicate, not loop for subpages:
https://github.com/getkirby/kirby/blob/f16b0b41db19ab5dbcf22e27f4aa2c35cb2c490c/src/Cms/PageActions.php#L482

As a solution idea; after copying the directory, looping all children of the copied page and updating the uuid data in `->adaptCopy()` method. What do you think?

````php
foreach ($copy->index() as $child) {
    $child->save(['uuid' => Uuid::generate()], $language->code());
}
````

**Comment by MikeHarrison** [comment]
Hi,
That sounds good to me - in this situation, I think all subpages should have new UUIDs generated, as well as any files duplicated as well

**Comment by lukasbestle** [comment]
@afbora Yes, that sounds good.

**Comment by bastianallgeier** [comment]
✅
