### ISSUE TITLE
Duplicating pages with relative file IDs is broken

### ISSUE THREAD

**Issue by FynnZW** [k-next/kirby#4870]
## Description
Since the introduction of file UUIDs with 3.8., duplicating pages with relative IDs is broken.
The file used to be stored in the content file like this:
```
Cover: - monster-trees-in-the-fog.jpg
```

Now, files get stored like this (if file UUIDs are disabled)
```
Cover: - parent-page/monster-trees-in-the-fog.jpg
```

Since the path is included, this leads to this behaviour:
- Duplicating without files still shows images from the duplication source, because the complete path is included.
- Duplicating with files copies files, but the wrong files are linked in the content.txt

**Expected behavior**  
Files get linked relative to the page, without any path. 
This should revert back to the correct behaviour from Kirby <3.8.

## To reproduce

1. Create a nested page with files
2. Disabled file UUIDs in blueprint with 
   ```
        type: files
        store: id
   ```
4. Duplicate the page, with or without files
5. Files are wrongly linked to duplication source

## Your setup
**Kirby Version**  
3.8.2

**Additional context**  
I cannot use file UUIDs, because of a different bug with those #4867.

**Comment by FynnZW** [comment]
Right now duplicating pages with files doesn't work at all, both UUID and the old way. 
Any chance this bug fix could make it in the 3.8.3 release?
Since it's a regression, it might be an easy fix.

**Comment by lukasbestle** [comment]
@distantnative Was there a particular reason why we switched to the `id` as the non-UUID fallback in picker fields? I don't fully remember what the Panel did when the user selected a file of a different page, wouldn't it have needed to store the ID already?

I have a very limited understanding of this at the moment, but my first reaction was that Kirby should store the ID for files of other pages and just the filename for files of the current page. The `toFiles()` method could then differentiate between these cases based on the occurrence of a slash in the path string. But as I said, I don't remember how we did it before 3.8.

**Comment by distantnative** [comment]
I just looked it up: https://github.com/getkirby/kirby/pull/4612/files#diff-f48d01ff6f4c25f3c2e8f1a34251e92010823474044243852b1654a8f6b97497L287-L303

I think before UUIDs, only the file picker did differentiate between storing ID or name.

My first idea would be:
In `Panel\File::pickerData()` add that logic again and overwrite the `id` key from `Panel\Model::pickerData()` with either the id or filename depending on the existence of `$params['model']`

With that, `store: id` should automatically use either the ID for files outside the current model/page, but the filename for direct files of the current page/model.

**Comment by lukasbestle** [comment]
OK, so we are on the same page regarding the expected end result.

I can't say much about the implementation as it's a part of the code base I'm not fully familiar with.

**Comment by distantnative** [comment]
@FynnZW could you please test if https://github.com/getkirby/kirby/pull/4892 solves the problem for you?

**Comment by distantnative** [comment]
@lukasbestle while my PR seems to work for the case outlined here, I am coming to the conclusion that this might be a bigger breaking change? If one uses `$page->file($name)` this won't be a problem. But what if people have been using `$site->file($name)`? That would break. 

Then again prior to https://github.com/getkirby/kirby/pull/4612/files#diff-f48d01ff6f4c25f3c2e8f1a34251e92010823474044243852b1654a8f6b97497L287-L303 that used to be the status quo as well.

**Comment by lukasbestle** [comment]
@distantnative I wouldn't expect anyone to use `$site->file($name)` manually on a file that is referenced in a field. I'd say the main use case is `$field->toFiles()`.

**Comment by distantnative** [comment]
True. And that would work with relative names as the method first tries to find them as direct files of the parent/page.

Then my PR should be fine, just needs some falsely tests to be fixed.

**Comment by FynnZW** [comment]
> @FynnZW could you please test if #4892 solves the problem for you?

It does! 👍 

Relative files are relative again (and files from other pages still keep their path). 

```yaml

Cover: - monster-trees-in-the-fog.jpg

----

Test-images: - global_images/screen3.png

```

**Comment by bastianallgeier** [comment]
✅
