### ISSUE TITLE
New extension for `content.uuid`

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4873]
Can be a core component or a closure in option:

````php
// uuid as core component
Kirby::plugin('my/uuid', [
    'components' => [
        'uuid' => function () {
            // todo
        }
    ]
]);

// closure option like `content.salt`
return [
  'content' => [
    'uuid' => function () {
      // todo
    }
  ]
];
````

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/4868#issuecomment-1329798834_

**Comment by distantnative** [comment]
Maybe I am missing the context, but isn't that a bit redundant to `Kirby\Uuid\Uuid::$generator = fn ($length)`?

**Comment by afbora** [comment]
Wow I didn't know that! Maybe moving this feature to options/extensions would make it more useful. You know better.

**Comment by lukasbestle** [comment]
@distantnative Most of our plugin extensions are internally static properties of some class. We do have some that are only managed inside the app class and we have some static properties that don't have an official plugin extension yet. The UUID generator is one of them.

However I just noticed that there can only be one UUID generator for the whole site, so a plugin extension won't really work – what should happen if multiple plugins define it?

The option on the other hand does feel a bit redundant as it would make the implementation more complex without an additional benefit.

I'd close this. What do you think?
