### ISSUE TITLE
Closures not working for hooks and other methods 

### ISSUE THREAD

**Issue by MoritzLost** [k-next/kirby#4876]
## Description

I'm trying to register some hooks and collection methods and want to organize those into classes. Unfortunately, Kirby expects anonymous functions, making this impossible.

```php
use Kirby\Cms\App;

App::plugin('site/collection-methods', [
    'collectionMethods' => [
        'myCustomMethod' => CollectionMethods::myCustomMethod(...),
    ],
]);
```

This throw the following error:

> Cannot bind an instance to a static closure

This is _not_ related to the callable syntax introduced in PHP 8.1. The traditional callback syntaxes don't work as well:

```php
App::plugin('site/collection-methods', [
    'collectionMethods' => [
        'myCustomMethod' => [CollectionMethods::class, 'myCustomMethod'],
    ],
]);
```

```php
use Kirby\Cms\App;

$collectionMethods = new CollectionMethods();

App::plugin('site/collection-methods', [
    'collectionMethods' => [
        'myCustomMethod' => [$collectionMethods, 'myCustomMethod'],
    ],
]);
```

Both of those throw the following error:

> Call to a member function call() on array

It seems Kirby _only_ supports anonymous functions, which is horrible. I'd have to wrap each of my static methods in an anonymous function which is bad for readability and probably performance as well:

```php
use Kirby\Cms\App;

App::plugin('site/collection-methods', [
    'collectionMethods' => [
        'myCustomMethod' => fn (...$args) => CollectionMethods::myCustomMethod(...$args),
    ],
]);
```

As far as I can tell, this is caused by Kirby trying to bind the function to the `$kirby` object (or the collection object in the case of collection methods) so I can use `$kirby` and `$this` inside the function. This could be solved in a number of ways that don't require the horrible syntax above instead.

**Expected behavior**  

Kirby should accept any closure or callable for collection methods, hooks etc. It should not throw an error if I use a closure for a hook.

## To reproduce

Create the `CollectionMethods` class and make sure it's included:

```php
<?php

class CollectionMethods
{
    public static function myCustomMethod()
    {
        return 'foobar';
    }
}
```

Put the first code example in the `index.php` and try to use `myCustomMethod` on a collection.

## Your setup

**Kirby Version**  
3.8.1.1

**Your system**
 - Device: Mac Mini
 - OS: macOS
 - Browser: Firefox

**Comment by lukasbestle** [comment]
> As far as I can tell, this is caused by Kirby trying to bind the function to the `$kirby` object (or the collection object in the case of collection methods) so I can use `$kirby` and `$this` inside the function. This could be solved in a number of ways that don't require the horrible syntax above instead.

Can you tell us more about alternative ways to achieve the instance binding?

**Comment by MoritzLost** [comment]
@lukasbestle I don't mean alternative ways for instance binding, I mean alternative ways to solve the problem that instance binding is used to address. But first of, my issue was indeed a bit strongly worded, this was after a long couple of hours trying to get this to work how I want it to … my bad.

---

For example, take hooks. For those, the case for instance binding is not very strong, the [documentation](https://getkirby.com/docs/reference/plugins/extensions/hooks#accessing-kirby-site-and-user-in-a-hook-callback) only mentions this:

```php
$kirby    = $this;
$site     = $this->site();
$user     = $this->user();
$username = $this->user()->username();
$role     = $this->user()->role();
```

Replace `$this` with `kirby()` and you're good. Because of the instance binding, right now I have to put this in my `config.php` if I want to organize my logic into classes:

```php
'hooks' => [
    'page.create:after' => fn (Page $page) => Hooks::pageCreateAfter($page),
],
```

This would be much simpler, but doesn't work because of the instance binding:

```php
'hooks' => [
    'page.create:after' => Hooks::pageCreateAfter(...),
],
```

For collection methods, I understand the motivation behind the instance methods a bit better. The collection methods need access to the collection object, and using instance binding to allow usage of `$this` is one solution. Passing the value to the collection method as the first argument would be another solution – in my opinion, a better one, since this would allow me to use any closure instead of only functions. For hooks, there's already some reflection magic 🪄  going on to figure out what variables the function accepts and passing it those variables. This could be extended to allow the collection methods to accept something like a `$value` parameter and passing the collection itself as that parameter. Or the system could handle the case that the closure cannot use instance binding and always pass the collection as the first parameter instead in those cases. Or a combination of both, this should be possible to implement in a backwards compatible way.

Another approach would be something like [Behaviors in Yii2](https://www.yiiframework.com/doc/guide/2.0/en/concept-behaviors). They essentially achieve the same thing as the instance binding, allowing you to add additional methods to core objects. Something like this could be provided as an alternative to the existing function syntax, making it completely backwards compatible as well.

Anyway, I think there are multiple possible architectures that would allow more freedom regarding the way I structure my code, and those could be implemented in a backwards-compatible way. But I get if this may be a minority concern and not something that you want to spend time on.

**Comment by distantnative** [comment]
I think the potentially hard part to this would be changing in a way that doesn't break existing usage. While you don't like the instance binding and point to other solutions, it is what so many plug-in developer currently have in use. Breaking this would be quite a big pain point for others to upgrade.

**Comment by MoritzLost** [comment]
@distantnative Absolutely! Supporting other ways to specify callbacks would need to be an addition, not a breaking change, and anonymous function using `$this` should continue to work as expected and documented, of course.

What I have in mind is some optional enhancement, like only trying to bind the function to the instance if it's possible. I did some tests, it's actually quite difficult if not impossible to tell if a closure can be bound to a new context or not. Both anonymous functions and closures created using the new callable syntax in PHP 8.1 are represented by a `Closure` object, so it's impossible to tell them apart. _Maybe_ it's possible with Reflection classes, but I doubt that's the best approach. Of course, callables can also be passed using the old array syntax `[MyClass, 'myFunction']` or string syntax (`my-namespace\my-function`). Those could be distinguished from closures more easily and called with `call_user_func`. In this case, the callable could be passed the collection as the first parameter. Using those syntaxes isn't possible at the moment, so this is completely backwards compatible since there can't be any existing code using that syntax.

However, that's a bit awkwards – it's hard to document and explain why `[MyClass, 'myFunction']` works and `MyClass::myFunction(...)` does not. Maybe introducing a different optional syntax for specifying callbacks would be a better idea. So both of those could work:

```php
'collectionMethods' => [
    // existing syntax
    'methodOne' => fn () => return 'foobar',

    // new syntax
    'methodTwo' => ['callback' => MyClass::myFunction(...)],
]
```

This would be completely backwards compatible. If a callback is specified using the second syntax, the collection could be passed as the first argument. Since it's new syntax, there's no chance of breaking existing code. The old syntax could continue to function as is. The method `HasMethods::callMethod` (in the `HasMethods` trait) could handle the distinction between the two syntaxes.

Anyway, those are just some ideas. If anything like this is implemented, it would be nice if it was supported across the board (for field methods, hooks, etc). Might need to be adapted for those use-cases.

**Comment by distantnative** [comment]
Would that new syntax really be that much better than your existing `fn () =>` workaround?

**Comment by lukasbestle** [comment]
With the syntax you propose, the method would immediately be called when the plugin is loaded and its return value will be registered as the collection method. Is this what you intended?

**Comment by MoritzLost** [comment]
> Would that new syntax really be that much better than your existing fn () => workaround?

@distantnative Hmm, good question. For hooks, the workaround is bearable – it's something everyone new working on the project will stumble over, but I'm willing to take that tradeoff so I don't have to put all my code in a single config file. But that only works because the hooks don't really need access to the bound object. The function that's bound to the object is the arrow function, so that one has access to `$this` (which in this case is the `$kirby` object if I recall correctly). But the `Hooks::pageCreateAfter` method doesn't have access to this object. This is fine because `$this` can just be replaced with `kirby()`.

For collection methods, it's a different story. Those need access to the bound object (the collection), so the anonymous function would need to pass it's `$this` scope to the function as the first parameter. That's much more complicated and difficult to read for everyone else. My current solution for a custom collection method looks like this:

```php
use Kirby\Cms\App;
use Kirby\Cms\Collection;

/**
 * Filter a collection to include only the pages related to any of the pages
 * in the given collection.
 *
 * @param Collection $relatedPages The collection of pages to filter by.
 * @param string     $field        The field to check for related pages.
 * @param string     $separator    The separator to convert the field value to a pages collection.
 * @param bool       $matchAll     Only match pages that are related to ALL the given pages.
 */
$filterByRelatedPages = function (Collection $relatedPages, string $field, string $separator = 'yaml', bool $matchAll = false): Collection {
    return $this->filter(function ($child) use ($relatedPages, $field, $separator, $matchAll) {
        $pagesForChild = $child->content()->get($field)->toPages($separator);
        $intersection = $relatedPages->intersection($pagesForChild);
        return $matchAll ? $intersection->count() === $relatedPages->count() : $intersection->isNotEmpty();
    });
};

App::plugin('site/collection-methods', [
    'collectionMethods' => [
        'filterByRelatedPages' => $filterByRelatedPages,
    ],
]);
```

This is a collection method that allows the user to filter by what pages the pages in the collection are related to. The function has four argument, so it really benefits from a docblock to explain how to use it. Assigning a variable to an anonymous function is the closest I've come to 'normal' docblocks, but it still doesn't work properly. This isn't standard syntax, so none of my tools can handle it. Intelliphense (VS Code) doesn't recognize it, and my docblock plugin can't generate a docblock for it. Feels like fighting an up-hill battle. Using a regular function and then creating a closure for it doesn't work because a closure created from a function can't be bound to a new scope.

How is everyone else handling this? What if you need to add multiple hooks, collection methods, other extensions etc? Do they all go in a single config file, or a `App::plugin` call without any structure or explanation? How does that scale, in particular across multiple team members?

The function above is used to display related blog posts (sharing a category with the current blog post), so it's not something super special or niche.

> With the syntax you propose, the method would immediately be called when the plugin is loaded and its return value will be registered as the collection method. Is this what you intended?

@lukasbestle That's not what's happening there. This syntax (`MyClass::myFunction(...)`) is not a function call, but the [first class callable syntax introduced in PHP 8.1](https://www.php.net/manual/en/functions.first_class_callable_syntax.php). The `...` aren't parameters, but special syntax to specify a function or method call as a callable. So `MyClass::myFunction(...)` is an optional replacement for the older array syntax for static method callables `[MyClass::class, 'myFunction']`. The same works for function (`myFunction(...)`) and object methods (`$myObject->myFunction(...)`). The closure created with this syntax is identical to the closure object that represents an anonymous function, with the key difference being that it can't be bound to a new scope.

**Comment by lukasbestle** [comment]
Ah, right. Sorry, I glossed over the example code and missed the dots.

What we could do is to support the array callable syntax that has been around before PHP 8.1 already. Then we could first check for `instanceof Closure` (in which case the closure is bound like before) or else for `is_callable()` (in which case the object is passed as first argument.

But you are right, there doesn't seem to be a way to support the new first class callable syntax from PHP 8.1+ at all.

In any case, I think this is not a bug in Kirby's current implementation but rather an enhancement/feature request.

**Comment by distantnative** [comment]
And to answer the question: most people put the anonymous functions etc. in a separate file (to not have all in the one plug-in index.php) and get it in via a `require_once` in the index.php

**Comment by distantnative** [comment]
I had another look at the various part of code where this would need changes. It isn't straightforward unfortunately. As you @MoritzLost wrote about, collection methods for example would still need somehow access to the collection itself and since normal binding isn't possible, we would need to add different ways of passing the instance.

It's not impossible, I think there are ways to support it, but it's also not effortless. For that reason, I would suggest to move it over to https://kirby.nolt.io and see how much general demand in the community is there for this feature. Which helps us to prioritise where we put our resources. Aside from that, a PR would of course be welcomed.

**Comment by rasteiner** [comment]
2 cents worth of opinion.

If I understand it correctly, there seem to be 2 contrasting philosophies:
1. anonymous functions loaded from separate files
2. container classes with static methods

Essentially it's "arrays vs classes". 

But only closures from philosophy 1 can be bound. It's also the only place where having a `$this` variable kind of makes sense (it wouldn't in static functions).
Given that the "array" approach is currently the kirby standard, I'd propose to make the "I wanna use classes intent" very clear.

So, if there has to be new syntax that needs to be backwards compatible, please consider one like this:

```php
use Kirby\Cms\App;

class MyCollectionMethods {
    static function foo($collection, $arg1, $arg2) {}
    static function bar($collection, $arg1) {}
}

App::plugin('site/collection-methods', [
    'collectionMethods' => MyCollectionMethods::class,
]);
```

The plugin loader then iterates over public static methods and creates anonymous closure wrappers that are bindable. 

The alternative would be to have this working:
```
'myCustomMethod' => CollectionMethods::myCustomMethod(...),
```
It can be done with ugly code, but imho that's just *more magic* that doesn't make using Kirby easier. 

---

In the meantime the above proposal could be tested with a "ponyfill" in userland:
```php
use Kirby\Cms\App;

class MyCollectionMethods {
    static function foo($collection, $arg1, $arg2) {}
    static function bar($collection, $arg1) {}
}

function closure_wrapper($class) {
    $methods = (new ReflectionClass($class))->getMethods(ReflectionMethod::IS_STATIC); 
    $map = [];
    foreach($methods as $m) {
        if($m->isPublic() === false) continue;    
        $map[$m->name] = fn(...$args) => $m->getClosure()($this, ...$args);
    }
    return $map;
}

App::plugin('site/collection-methods', [
    'collectionMethods' => closure_wrapper(MyCollectionMethods::class),
]);
```

----

It also has to be noted that "binding" doesn't only provide the `$this` variable, it also enables external anonymous functions to [access `private` and `protected` class members](https://onlinephp.io?s=HY1BDsIgEEXXknCHsWHRLnoCBFd6AG8wmWAgJQxxqKZpvLvF7X_v5V-uNVattKKMInBnhl2rU32lN7YAZgkbOBhuhbDKmrElLvBgWuQ8WK2-PTVYjtHBs4wTOA-mxSSzP1LbcaDI8HdmT5jzWMKnH032Bw%2C%2C&v=8.1.13%2C7.4.33).
While passing a Collection / Kirby instance as method parameter obviously does not.

**Comment by distantnative** [comment]
@rasteiner Even if you wrapped the class syntax automatically in an anonymous function, binding it to $this would only bind the anonymous function, not the class method. 

For class methods having access to the object, we would need to pass it as additional parameter, which can have its own pitfalls.

I think there is a path to achieve this, I'm just unsure about the priorities. And see it rather as a feature request, that we should move over to Nolt as it's not a quick fix/ implementation.

**Comment by rasteiner** [comment]
> we would need to pass it as additional parameter, which can have its own pitfalls.

yup, I do it here: `$m->getClosure()($this, ...$args);` (notice I pass `$this` as first parameter)

As I said, one would not expect binding in static functions (you don't expect a `$this` variable in a `static function() {}`). The purpose was to make it explicit. That's my whole point.
And yes, one of the major pitfalls of having the instance passed as parameter would be that you no longer have access to private properties and methods, like written above, but one wouldn't expect to have access at that point. 

My feeling, while reading the OP comments was that "[having] to wrap each of my static methods in an anonymous function [...] is bad for readability". Therefore I tried to solve *that* problem, rather than complicating the Kirby interface further by trying to be smart when calling the methods and trying to interpret what kind of closure was passed. The Kirby interface should stay clean: you only pass it bindable anonymous functions.

**Comment by MoritzLost** [comment]
Thanks for the input, everyone! I agree that this isn't strictly a bug (though it was pretty unexpected when I first encountered this issue). I've opened a feature request here: https://kirby.nolt.io/490

> What we could do is to support the array callable syntax that has been around before PHP 8.1 already. Then we could first check for instanceof Closure (in which case the closure is bound like before) or else for is_callable() (in which case the object is passed as first argument.
> But you are right, there doesn't seem to be a way to support the new first class callable syntax from PHP 8.1+ at all.

@lukasbestle Yeah, only supporting the only class method wouldn't be great, and differentiating between 'bindable' closures doesn't seem to be possible without some hacky reflection workaround (if at all). So I think introducing another syntax would be the better solution. In this case, it would be great if this syntax worked uniformly for all components that accept callbacks.

> And to answer the question: most people put the anonymous functions etc. in a separate file (to not have all in the one plug-in index.php) and get it in via a require_once in the index.php

@distantnative Yeah, that's close to my current workaround. I've written a small plugin loader that loads all plugins from a custom directory (I prefer separating site-specific plugins and community plugins) and put the anonymous function and the `Kirby::plugin` call next to each other in a single file (see my example above). Still not great that this doesn't work with any of the standard tooling (like IntelliSense in VS Code).

> I had another look at the various part of code where this would need changes. It isn't straightforward unfortunately. As you @MoritzLost wrote about, collection methods for example would still need somehow access to the collection itself and since normal binding isn't possible, we would need to add different ways of passing the instance.

I think introducing an alternative syntax and allow that across the board would be the best solution. With a new syntax, the collection could simply be passed as the first argument to the callback. In some cases, the `$this` object isn't needed at all (especially for hooks where you can just replace `$this` with `kirby()`). You're right, that would be a lot of work, especially since it needs to be fully backwards compatible, of course.

> Aside from that, a PR would of course be welcomed.

Let's see how the feature request I've posted above goes. I think it's unlikely to get much traction, it's probably a niche concern … if there's enough demand and we can agree on the best solution, I'd be happy to collaborate on building it.

> But only closures from philosophy 1 can be bound. It's also the only place where having a $this variable kind of makes sense (it wouldn't in static functions).
> Given that the "array" approach is currently the kirby standard, I'd propose to make the "I wanna use classes intent" very clear.

@rasteiner That looks like a great solution! Clearly distinguishable from the existing syntax and shouldn't be too difficult to implement. I wonder how this could work with hooks – if you pass a class string for the `hooks` object, Kirby needs to know what method to call for which hooks. Could be done by transforming the hooks name to a method name based on some rules (e.g. `page.changeTitle:before` -> `page_changeTitle__before`) or maybe using [attributes](https://www.php.net/manual/en/language.attributes.overview.php) – of course this only works in PHP 8, but 7.x is EOL anyway.

> It also has to be noted that "binding" doesn't only provide the $this variable, it also enables external anonymous functions to [access private and protected class members](https://onlinephp.io/?s=HY1BDsIgEEXXknCHsWHRLnoCBFd6AG8wmWAgJQxxqKZpvLvF7X_v5V-uNVattKKMInBnhl2rU32lN7YAZgkbOBhuhbDKmrElLvBgWuQ8WK2-PTVYjtHBs4wTOA-mxSSzP1LbcaDI8HdmT5jzWMKnH032Bw%2C%2C&v=8.1.13%2C7.4.33).
> While passing a Collection / Kirby instance as method parameter obviously does not.

For what it's worth, I think that's a huge downside of the binding approach. External code shouldn't only have access to the public interface of a class, not to its private and protected methods. If you're leaking implementation details by providing access to private members, every change to every part of the system becomes a (potentially) breaking change.

> As I said, one would not expect binding in static functions (you don't expect a $this variable in a static function() {}). The purpose was to make it explicit. That's my whole point.
> And yes, one of the major pitfalls of having the instance passed as parameter would be that you no longer have access to private properties and methods, like written above, but one wouldn't expect to have access at that point.

I absolutely agree, we don't need `$this`. Passing the collection (or whatever) as the first parameter also allows me to use a type-hint which enables all the nice features (like IntelliSense) I'm talking about above. And as mentioned, my external code should only have access to the public interface of the class anyway.

> My feeling, while reading the OP comments was that "[having] to wrap each of my static methods in an anonymous function [...] is bad for readability". Therefore I tried to solve that problem, rather than complicating the Kirby interface further by trying to be smart when calling the methods and trying to interpret what kind of closure was passed. The Kirby interface should stay clean: you only pass it bindable anonymous functions.

💯 
Having to manually wrap everything in an anonymous function is confusing and error-prone. But if Kirby does this under the hood to make the syntax compatible with the existing implementation, that's a perfectly viable solution.

**Comment by rasteiner** [comment]
> I wonder how this could work with hooks – if you pass a class string for the hooks object, Kirby needs to know what method to call for which hooks. Could be done by transforming the hooks name to a method name based on some rules (e.g. page.changeTitle:before -> page_changeTitle__before) or maybe using [attributes](https://www.php.net/manual/en/language.attributes.overview.php)

You're right, I didn't think of hook names. Kirby 3.8 already requires PHP8, so I think attributes would provide a very pleasing syntax, optionally also for other methods (not only hooks). That's the beauty of po[nl]yfills, you can experiment with stuff before committing to a solution.

**Comment by lukasbestle** [comment]
Thanks for all the input. There are some really good ideas in this thread. Thanks @MoritzLost for creating the idea ticket and linking this issue from there.

I'm closing this issue because it's not a bug and to avoid two parallel discussion threads.
