### ISSUE TITLE
[3.8.3-rc.1] Custom block previews not working

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#4877]
## Description
Custom block previews show an error in the panel. 

<img width="1504" alt="Screenshot" src="https://user-images.githubusercontent.com/77532479/205025526-eba13202-4ed0-4ecb-9661-c194ed924118.png">

It seems that `this` no longer has the block properties like `content` and `fieldset`. 
```
// Does not work
panel.plugin("plugin/block-previews", {
  blocks: {
    heading: {
      template: `
        <div>{{ content.text }}</div>
      `,
    },
},
```
Instead, the `$parent` contains the block properties.

```
// Does work
panel.plugin("plugin/block-previews", {
  blocks: {
    heading: {
      template: `
        <div>{{ $parent.content.text }}</div>
      `,
    },
},
```

## Your setup
Kirby 3.8.3-rc.1
Tested in the Starterkit

**Comment by afbora** [comment]
Custom block previews are working great as expected on 3.8.2. Not sure but I guess this issue occurred by deprecated or refactored parts of the release.

**Comment by afbora** [comment]
@distantnative I've tested with reverting #4820 PR and I can confirm that the issue related the this PR #4820 But I have no idea about the issue or solution 🤷‍♂️

**Comment by bastianallgeier** [comment]
✅
