### ISSUE TITLE
[3.8.3-rc.1] Structure field values do not save

### ISSUE THREAD

**Issue by jongacnik** [k-next/kirby#4879]
## Description
Structure field items can be added/removed/sorted, but item field values are not saved. Structure fields operate normally in 3.8.2

**Expected behavior**  
When adding/updating a structure field item, item field values should be updated.

## To reproduce
Add a structure field to a page blueprint and create an item. Item should be added, but field value will not be saved. Testing with the following structure field definition:

```yaml
teststructure:
  type: structure
  fields:
    title:
      type: text
```

## Your setup
**Kirby Version**  
3.8.3-rc.1

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS
 - Browser: Chrome
 - Version: 107

**Comment by afbora** [comment]
FYI, I've tested with reverting https://github.com/getkirby/kirby/pull/4819 PR and works great.

**Comment by distantnative** [comment]
I think this is at least related to: https://github.com/getkirby/kirby/issues/4881

**Comment by afbora** [comment]
@distantnative #4883 PR is still draft but I've tested anyway and unfortunately still doesn't work. Is #4883 PR should fix this issue, right?

**Comment by distantnative** [comment]
That's why the PR is back in draft, cause it doesn't work yet ;)

**Comment by bastianallgeier** [comment]
✅
