### ISSUE TITLE
Double mailto: in email field

### ISSUE THREAD

**Issue by rantonse** [k-next/kirby#4880]
## Description

The envelope icon (`k-input-icon`) links to `mailto:mailto:` + email address for email addresses in the email field.

**Expected behavior**  

It should link to `mailto:` + email address.

## To reproduce

I reproduced the error with the starter kit by adding an email field.

## Your setup
**Kirby Version**  
3.8.2

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS
 - Browser: Chrome, Firefox

**Comment by distantnative** [comment]
✅
