### ISSUE TITLE
URL option does not work when specified in domain-specific config file

### ISSUE THREAD

**Issue by yandodov** [k-next/kirby#4891]
## Description

I've specified a custom URL in `config.php`:

```php
return [
    'url' => 'https://example.com'
];
```

However, if I create a [domain-specific](https://getkirby.com/docs/guide/configuration#multi-environment-setup) `config.example.test.php` like this:

```php
return [
    'url' => 'http://example.test'
];
```

…and open http://example.test locally - it doesn't work.

I tested it out and the domain-specific config file is not loaded at all. If I comment out the `example.com` line in the first config file - the second config file is loaded and everything works as expected.

My guess is that the `url` option in the first config changes the actual domain checks made for loading domain-specific config files.

**Expected behavior**

Domain-specific config files should be loaded even when a `url` option is specified in the main one.

## Your setup
**Kirby Version**  
3.8.2

**Comment by distantnative** [comment]
You probably need to use `env.php` files instead https://getkirby.com/docs/guide/configuration#multi-environment-setup__deployment-configuration

Cause otherwise your logic is conflicting - your general config file sets the URL to be `.com` but you still expect the config file for a different URL that isn't the one you just told Kirby to be to be loaded.

**Comment by lukasbestle** [comment]
Yes, this is as expected, see the reference: https://getkirby.com/docs/reference/system/options/url#url-override-per-domain

The reason why custom config files are only loaded when they are allowed either by `config.php` or `env.php` is that it prevents attackers from "faking" your test environment in production with request headers. This ensures that debugging options or similar testing config can only be enabled deliberately by you and not from the request.
