### ISSUE TITLE
`The page "*" cannot be found` error when page deleted

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4897]
## To reproduce

1. Create a page from panel
2. Edit the page without save
3. Try to delete
4. See error console (a dialog appears very quickly, closes, and sometimes remains visible)

## Your setup
**Kirby Version**  
3.8.3-rc.1 & 3.8.x (and probably 3.7.x, not tested yet)

**Console output**  
````json
{
    "status": "error",
    "message": "The page \"blog/test\" cannot be found",
    "code": 404,
    "exception": "Kirby\\Exception\\NotFoundException",
    "key": "error.page.notFound",
    "file": "/test/kirby/starterkit-3.8.3-rc.1/kirby/src/Cms/Find.php",
    "line": 85,
    "details": [],
    "route": "(.*)/lock"
}
````

**Comment by distantnative** [comment]
✅
