### ISSUE TITLE
Validator `in` doesn't work with array syntax

### ISSUE THREAD

**Issue by MoritzLost** [k-next/kirby#4899]
## Description

I'm trying to use the array syntax for the `invalid()` function to validate some data. The [documentation for the built-in validators](https://getkirby.com/docs/reference/system/validators) doesn't mention the required formats for the array syntax at all, while the [documentation for the `invalid()` function](https://getkirby.com/docs/reference/templates/helpers/invalid) only includes very basic examples. The only other mention I could find of the array syntax is in the example code in the [form guides](https://getkirby.com/docs/cookbook/forms/basic-contact-form#the-contact-form-controller), which again only includes basic examples.

I'm having trouble using the `in` validation rule:

```php
$result = invalid(
    ['foo' => 'bar'],
    ['foo' => [
        'in' => [
            'one',
            'two',
            'three'
        ]
    ]]
);
```

This causes the following error:

> Uncaught TypeError: Kirby\Toolkit\{closure}(): Argument #2 ($in) must be of type array, string given in /path/to/project/vendor/getkirby/cms/src/Toolkit/V.php:425

What's the correct array syntax to use with the `in` validation? Where can I find more complete examples for the array syntax for all built-in validators, or a general explanation of the syntax?

**Expected behavior**  

The filter in the test case above should return an array with an error, not produce an exception.

## To reproduce

Put the code snippet above in any template.

## Your setup

**Kirby Version**  
3.8.1.1

**Comment by texnixe** [comment]
The syntax looks like this

```
'role' => ['required', 'in' => [['role1', 'role2']]]
```
So not a bug.

**Comment by MoritzLost** [comment]
@texnixe Thank you for the explanation! I had another look; so I need to use a nested array because arrays are used to pass multiple parameters to the validator (and the invalid function uses spread syntax to pass the array as individual arguments). This is a bit counterintuitive since scalar values can be passed directly, without wrapping them into an array.

Anyway, I've [opened a PR](https://github.com/getkirby/getkirby.com/pull/1901) to add some documentation regarding the syntax variants for the `$rules` array. Would be a nice improvement to the existing documentation – as far as I can tell, passing multiple parameters as an array isn't mentioned anywhere.
