### ISSUE TITLE
Dom unit tests

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#4906]
The annoying dom unit tests need to be fixed:
https://github.com/getkirby/kirby/actions/runs/3630541371/jobs/6124007281

**Comment by distantnative** [comment]
@afbora do you see these errors in your local setup as well? Bastian and I do, have been for a while. But e.g. I think for Lukas the tests pass as they are right now locally.

**Comment by afbora** [comment]
@distantnative Yes, my tests fails as well:

![image (5)](https://user-images.githubusercontent.com/3393422/206414963-007eb618-ea5d-411b-80f8-f0b59d29c303.png)

**Comment by distantnative** [comment]
@lukasbestle what about you? Or do we just have to adapt the unit tests?

**Comment by afbora** [comment]
I'm not sure but could it be depending on PHP, DOM/XML version or local setup settings?
