### ISSUE TITLE
HMR throws error during panel plugin development [k3.8.3]

### ISSUE THREAD

**Issue by crisgfx** [k-next/kirby#4907]
## Description
When saving a vue component while running `npm run serve`
I get the following error in the panel: `usedComponentDefs[componentName] is undefined`

![test](https://user-images.githubusercontent.com/16305374/206443721-4e4598fe-6b63-4cb5-910a-90083754e278.jpg)

## To reproduce
- Setup a simple panel plugin from the [plugin kit](https://github.com/getkirby/pluginkit).
- Run `npm run serve`
- Edit and save the `DemoSection.vue`

## Your setup
**Kirby Version**  
3.8.3
**kirbyup Version**  
2.1.0
**PHP Version**
8.1
**OS**
Mac OS 11.6.4 (Big Sur)

**Comment by lukasbestle** [comment]
You are running `npm run serve` inside the plugin, right? In that case, I think the source of the issue is somewhere inside kirbyup, not the Kirby core.

**Comment by crisgfx** [comment]
Hey Lukas,
yes, that's right, I just thought, this is the right place for the issue, since You're promoting the command on the [plugin setup page](https://getkirby.com/docs/guide/plugins/plugin-setup-panel).
Shall I open an issue in the kirbyup repo then?
Many thanks! =)

**Comment by crisgfx** [comment]
PS: There are no problems with kirby 3.8.2.

**Comment by distantnative** [comment]
@CrisGraphics yes please, and all good to report this here in the first place. But @johannschopplich needs to have a look at his plugin as I don't understand it sufficiently. He probably should have a look at https://github.com/getkirby/kirby/pull/4820 and https://github.com/getkirby/kirby/pull/4884 - I assume something changed in there that breaks his magic.

**Comment by lukasbestle** [comment]
I'm closing this issue for now. If it turns out to be a bug in Kirby, please leave a comment and we'll reopen this issue.
