### ISSUE TITLE
attr() converts attribute names to lowercase

### ISSUE THREAD

**Issue by fabianmichael** [k-next/kirby#4908]
## Description

The `attr()` helper and the underlying toolkit classes are converting all attribute names to lower-case. In HTML, this should not present any problems in daily life, but XML is case-sensitive and the SVG spec also states that attributes MUST be case-sensitive.

```php
<?php echo \Kirby\Toolkit\Html::attr('viewBox', '0 0 10 10') ?>
<?php echo \Kirby\Toolkit\Xml::attr('viewBox', '0 0 10 10') ?>
```

Output:

```
viewbox="0 0 10 10"
viewbox="0 0 10 10" 
```

**Expected behavior**  

The helper functions should respect the case of the attributes and only ensure, that the string is syntactically correct by sanitizing invalid characters or throwing an error when encountering any invalid input. The `Xml` class should always follow the spec and respect the case of attributes. If that behavior is still needed, an option could be added.

## To reproduce

Just paste the examples above anywhere …

## Your setup

**Kirby Version**  
Kirby 3.8

**Additional context**  

More information:

- https://www.w3.org/TR/2015/WD-SVG2-20150709/intro.html#TermPresentationAttribute
- https://www.w3.org/TR/2015/WD-SVG2-20150709/styling.html#CaseSensitivity

**Comment by distantnative** [comment]
✅

**Comment by fabianmichael** [comment]
@distantnative Sorry for bringing this up again, but after I had to generate some inline SVG attributes, I realized that using XML within HTML is not very uncommon. Seemingly, browsers ignore the case of inline SVG attributes, but wouldn’t it make more sense to remove "the magic" alltogether even if the function is supposed to generate HTML markup? It really seems to me, like applying a non-obvious and non-required transformation of input does not serve any purpose other than an aesthetical (to be fair, I also don’t like UPPERCASE attribues within HTML). Or am I missing something here?

**Comment by distantnative** [comment]
@fabianmichael but if you generate online svg/XML attributes, wouldn't it make more sense to use the Xml class then directly?

**Comment by fabianmichael** [comment]
@distantnative Probably, but honestly, it is way more comfortable to type `attr(['viewBox' => '0 0 16 16'])` than `\Kirby\Toolkit\Xml::attr(['viewBox' => '0 0 16 16'])` in a template or snippet.

**Comment by lukasbestle** [comment]
The `Xml` class is aliased, so `Xml::attr()` would be enough.

**Comment by fabianmichael** [comment]
@lukasbestle Unfortunately, aliased classes do not have great IDE support (you knew that before, right? ;-) ). 

<img width="565" alt="Bildschirmfoto 2022-12-13 um 19 52 00" src="https://user-images.githubusercontent.com/395617/207420074-90d3241d-fee4-4737-9abd-4bc2a0b58da5.png">

My whole point is, that `attr()` transforms the function’s input in a way that I (and probably many others) would not expect from that function. I never had problems with this, until I recently had to generate SVG attributes. If the case of attributes would not be alterered, the `attr()` helper would be able to generate both valid HTML and XML (there would be some edge-cases left, like attributes without values).

I won’t bother you any further with this, since all of us are probably working on more important issues at the moment. I would personally benefit from that change, but it is obviously up to you to decide whether this is worth adding another (breaking?) change.
