### ISSUE TITLE
Checkboxes field without options shows error on click in panel

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#4916]
## Description
A checkboxes field without options (either because none are defined or the query doesn’t provide any) shows an error after clicking on the info message in the panel.

**Expected behavior**  
No error to be shown.

**Screenshots**  
<img width="877" alt="Bildschirm­foto 2022-12-09 um 15 26 49" src="https://user-images.githubusercontent.com/9334305/206724018-635dab93-c83d-407a-a0f0-62d012e36ad8.png">
<img width="877" alt="Bildschirm­foto 2022-12-09 um 15 24 12" src="https://user-images.githubusercontent.com/9334305/206723528-235c08dc-967e-47ec-8591-1882e9798ce6.png">

## To reproduce

```yaml
fields:
  checkboxes:
    type: checkboxes
```

## Your setup
**Kirby Version**  
3.8.2

**Console output**  
`TypeError: null is not an object (evaluating 'this.$el.querySelector("input").focus‘)`

**Your system (please complete the following information)**
 - OS: macOS 13.0.1
 - Browser: Latest Safari & latest Google Chrome (Chrome shows a different error)

**Comment by distantnative** [comment]
✅
