### ISSUE TITLE
[Accessibility] Status buttons should communicate the current status of an item to screen readers.

### ISSUE THREAD

**Issue by MarcoZehe** [k-next/kirby#4927]
## Description

When in the panel of the starter kit, there are items that are published and others that are drafts. Visually, these are probably distinguishable. However, the Status button that allows to change between drafts, review, or published, does not communicate the current status to screen readers. The buttons all have a label of "Status". If these are clearly visible so sighted users can immediately see what is a draft, in review, or public, screen reader users should get the same information through the label.

**Expected behavior**  

The button label should be something like "Status (currently draft)" or similar, so that the Status information is still first, and the current status is appended.

**Screenshots**  

## To reproduce

1. Go to the panel of the starter kit and log in.
2. Turn on the operating system's screen reader, for example VoiceOver on the Mac by triple-clicking the TouchID button while holding down the CMD key.
3. Using either the tab key, or the VoiceOver commands CTRL+Option+Right/LeftArrows, navigate to the controls of each image or note. Focus on the Status button for any item.
4. Listen to VoiceOver always calling it "Status button", regardless of the actual status of the item.

## Your setup
**Kirby Version** 3.8.3 

**Console output**  None, no error, missing information in a label

**Your system (please complete the following information)**
 - Device: MacBook Pro 
 - OS: MacOS 13 
 - Browser: Safari or Firefox 
 - Version: Current release. 

**Additional context**

**Comment by distantnative** [comment]
In the sections, it would be quite hard at the moment for performance reasons to get the [customised status labels](https://getkirby.com/docs/reference/panel/blueprints/page#statuses). This is due to the way how we currently load blueprints - which isn't ideal. For the moment, I would think it would still be better to at least include the non-customised labels (draft, unlisted, listed) to improve accessibility. Do you agree, @MarcoZehe?

**Comment by MarcoZehe** [comment]
Yes, if the customized status labels aren't fetched for sighted people yet, either, that's no problem. But if the standard publish statuses are at least communicated, that would be helpful. Screen readers can search for label text, so the same way sighted people can quickly glance over the items and see which are drafts, a screen reader user can then search for the word "draft" and immediately find the one(s) that are drafts, too.

**Comment by distantnative** [comment]
@MarcoZehe Do you see a problem with implementing it as "Status: Draft"/"Status: Public" etc.? This would be easy with existing translation strings, already prepared it in [a PR](https://github.com/getkirby/kirby/pull/4928). But if you think that "Status (currently draft)" would be a lot better (even more, if the other variant would create an issue), please let me know.

Confident that we can include this in the next release.

**Comment by MarcoZehe** [comment]
No I don't see a problem with that. It still contains all relevant information.

**Comment by distantnative** [comment]
Will be included in Kirby 3.8.4 ✅
