### ISSUE TITLE
[Panel] pages dialog: can't distinguish long page titles

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#4949]
## Description
Weird edge case but in this case two titles are very similar and I have zero chance to distinguish them:

![Screenshot 2022-12-13 at 11 30 43](https://user-images.githubusercontent.com/60777/207294652-5b5bf84a-131c-4bd0-8bf3-883001181dc9.png)

**Expected behavior**  
When I hover over the title I would expect it to show the full title as a tooltip (via `title` attribute). Or that the title scrolls 😄

**Comment by afbora** [comment]
Not same just related with #2791 but I definitely agree with @mrflix Showing a simple tooltip/title on hover would be great!

**Comment by afbora** [comment]
@distantnative I've a solution about the issue but I need your help:

I think, related source line to implementing tooltip:
https://github.com/getkirby/kirby/blob/41719bd54310dfc2e321a75a8549da98ccf5cd1d/panel/src/components/Layout/Item.vue#L30

My idea is implementing like following, but quotes are escaped on title tooltip.
````js
<h3 class="k-item-title" :title="title">
````

I tried with `unescapeHTML` helper and works great. But I'm not sure about security.
````js
<h3 class="k-item-title" :title="$helper.string.unescapeHTML(title)">
````

What do you think?

**Comment by distantnative** [comment]
@afbora sorry for getting back to you so late. I think this is exactly right. It's been added on our private branch and will be in the v4-alpha.5
