### ISSUE TITLE
[Kirby 3.8.3] Multiselect field can't search

### ISSUE THREAD

**Issue by grupoactialia** [k-next/kirby#4951]
## Description

The multiselect field not working in input search. I get [object InputEvent] and I can't search.

**Screenshots**  

<img width="439" alt="Captura de pantalla 2022-12-14 a las 9 33 41" src="https://user-images.githubusercontent.com/33631434/207545928-3a11ea40-74fe-4756-845c-f0e1a2a2c42a.png">

## Your setup
**Kirby Version**  

3.8.3

**Comment by distantnative** [comment]
Have to look closer into the code, but my hunch is that somewhere it should say `event.target.value, not just `event`

**Comment by afbora** [comment]
@distantnative Here is the line

https://github.com/getkirby/kirby/blob/3.8.3/panel/src/components/Forms/Input/MultiselectInput.vue#L46

**Comment by distantnative** [comment]
Yep that should be it

**Comment by bastianallgeier** [comment]
We should check if we have more native inputs where we miss to use the event target after the refactoring. I don't think so but it can't hurt to double check

**Comment by afbora** [comment]
Absolutely. I've looked around a bit. I found a lot of lines that follow the `@input="* = $event"` format, but in general they seem to work. I don't know exactly which ones we need to fix.

**Comment by distantnative** [comment]
@afbora we need to fix those where we do it on a native `input` html element (or similar). Custom components (starting with `k-`) should be fine as is.

**Comment by afbora** [comment]
@distantnative Oh, now I get it. Thank you for the explanation 👍  I will check again.

**Comment by afbora** [comment]
I searched in all components and I couldn't find native input with `@input`. Here PR https://github.com/getkirby/kirby/pull/4952

**Comment by afbora** [comment]
✅
