### ISSUE TITLE
[Kirby 3.8.3] Text field inside a custom `<k-form>` does not update on input

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#4953]
## Description

I think we have another regression in Kirby 3.8.3 related to Vue event handling:

In my Versions plugin, the "Label" input (a `text` field) in the [version creation dialog](https://github.com/lukasbestle/kirby-versions/blob/main/src/frontend/components/Dialogs/CreateDialog.vue) no longer updates its value prop on input. This also shows because the counter does not update either and stays at "0" (see screenshot). The issue first occurs in Kirby 3.8.3, everything works fine in Kirby 3.8.2.

`text` fields in normal page forms work as expected. I haven't been able to track down where the difference may be.

**Expected behavior**  

The `value` prop and the counter should update on input.

**Screenshots**  

![Screenshot of the label input in the Versions plugin](https://user-images.githubusercontent.com/1595007/207714567-3bcf9d78-f1e8-465d-a4d6-777781a61d31.png)

## Your setup
**Kirby Version**  

3.8.3

**Console output**  

None

**Comment by distantnative** [comment]
I'll only manage to look at it in the weekend.

**Comment by distantnative** [comment]
✅
