### ISSUE TITLE
[Kirby 3.8.3] Panel Login not working - Email Field is not used when autofilled

### ISSUE THREAD

**Issue by adangel** [k-next/kirby#4962]
## Description

After upgrading from 3.8.2 to 3.8.3, I couldn't login into the panel anymore. The login request always sent an empty email field - and thus kirby coudn't find a matching account for "".

I bisected to this commit: https://github.com/getkirby/kirby/commit/578b0aa2d64d755096c8d79c64229994631fc476
But that's not really helpful - I think, the difference is in the dist/js files...

The problem is only reproducible with **Firefox** - using Chrome, there is no problem.

It seems like that some events are not fired by Firefox, when it autofills the formular.
Maybe it is a side effect of #4822 which changed the way, how binding is implemented (I think). It could be also a vuejs bug.

It might be similar to #4953 - at least, it seems to have to do with event handling in the browser.

The workaround is: First clear the email input field and click somewhere else (to make sure Firefox fires the change event). Then click into the email input field again and let Firefox autofill email and password. Click button "Login". No problem.

**Expected behavior**  

* When opening the panel login page and the browser fills in the credentials (autofill), the login button should work the first time.

## To reproduce

* Use Firefox (108.0.1)
* Open the panel login page
* Login with your credential and let Firefox save the credentials/form
* Logout and close the browser tab
* Open the panel login page again - now Firefox should automatically fill in the form
* Click "Login" button - you'll get an invalid credentials error

## Your setup
**Kirby Version**  3.8.3

**Console output**  
```
Object { status: "error", message: "Ungültige Zugangsdaten", code: 403, exception: "Kirby\\Exception\\PermissionException", key: "error.access.login", file: "/kirby/src/Cms/Auth.php", line: 566, details: [], route: "auth/login" }
```

**Your system (please complete the following information)**
 - OS: Linux
 - Browser: Firefox
 - Version: 108.0.1

**Additional context**  
Using Chrome, the autofill and login works without problems.

**Comment by afbora** [comment]
I've looked into the issue a bit. Maybe it can give you an idea.

I debug the line below. The `@onInput()` method runs twice when the page is loaded. For email and password fields. It updates the object when it works for email. But when it works for the second time for password field, the e-mail property is still empty instead of the object whose e-mail property is updated.

https://github.com/getkirby/kirby/blob/3.8.3/panel/src/components/Forms/Fieldset.vue#L119

**Comment by distantnative** [comment]
@afbora you can reproduce this with the `develop` branch?

I've tried with Firefox and Chrome but both seem to work for me:

<img width="436" alt="Screenshot 2022-12-27 at 15 42 58" src="https://user-images.githubusercontent.com/3788865/209682410-6c9a3868-11c9-46e1-8a73-3f32f0e2f1b8.png">

<img width="1020" alt="Screenshot 2022-12-27 at 15 42 44" src="https://user-images.githubusercontent.com/3788865/209682426-0f0c220c-9985-4e26-af27-47f7ae558580.png">

**Comment by afbora** [comment]
@distantnative I tested it with `console.log()` like you before, I tested it again in the `develop` branch. The problem still continues for Firefox 108.0.1 but works for Chrome 🤷‍♂️  (Windows 10)

````js
onInput(value, field, name) {
  console.log("Fielset@onInput");
  console.log(value, field, name);
  const values = { ...this.value, [name]: value };
  console.log(values);
  this.$emit("input", values, field, name);
},
````

![image (9)](https://user-images.githubusercontent.com/3393422/209717924-b72f804e-df57-4a26-8205-e64d1b6857d6.png)

**Comment by adangel** [comment]
I've had a look at it: It seems, that the property `value` is never updated and is always an empty object. The `onInput` handler only adds the currently changed field to the value object.

I'd suggest to change the method [onInput](https://github.com/getkirby/kirby/blob/develop/panel/src/components/Forms/Fieldset.vue#L122) to be the following:

```js
		onInput(value, field, name) {
			this.value[name] = value;
			this.$emit("input", this.value, field, name);
		},
```

This changes `this.value` and works on this - and not on a local var `values`. It seems, this local var was introduced with https://github.com/getkirby/kirby/commit/57df5c82b00840bd1a3c2d7109d39a5030252628.

**Update:** That's only a workaround, as the value property should be updated automatically via binding `:value="value[fieldName]"`...

**Comment by distantnative** [comment]
@adangel thanks for trying to figure this out. We'll revert some changes to fix the regression we introduced. I think your suggestion won't quite work as Vue does not allow directly mutating props (e.g. `this.value`).

**Comment by distantnative** [comment]
✅
