### ISSUE TITLE
Console errors after session timeout

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#4967]
## Description
When your user session becomes inactive on a Kirby 3 v3.9.0 admin panel page, there are errors in the console afterwards.

**Expected behavior**  
No errors.

**Screenshots**  

![Screenshot 2022-12-20 162216](https://user-images.githubusercontent.com/6271057/208702674-8178534c-6b87-4864-84c6-4d852e0f50ae.png)

![Screenshot 2022-12-20 162205](https://user-images.githubusercontent.com/6271057/208702683-11b07e88-1c06-4944-8cea-f69acf822c9c.png)

## To reproduce

1. Log in to admin panel
2. Go on some page and become inactive
3. See browser console after the auto logout happens
4. See errors

## Your setup
**Kirby Version**  
kirby-3.9.0-rc.1

**Console output**  
see screenshots

**Your system (please complete the following information)**
 - OS: Windows 11
 - Browser: latest Firefox

**Additional context**  
multilang site, local wamp setup

**Comment by bastianallgeier** [comment]
✅
