### ISSUE TITLE
Panel Sections are not unmounted

### ISSUE THREAD

**Issue by thathoff** [k-next/kirby#4970]
## Description
I’ve discovered a strange behaviour of panel section plugin’s Vue components: They don’t seem to be unmounted when changing the view oder logging out.

```js
panel.plugin('reinorange/dummy', {
  sections: {
    dummy: {
      template: `
        <div>
          This is a test section!
        </div>
      `,
      methods: {
        pollForUpdates: function () {
          console.log("POLLING %s: This is called even if the section is not active anymore", this._uid)
          if (!panel.$user) {
            return
          }

          // DO STUFF

          setTimeout(() => {
            this.pollForUpdates()
          }, 5000)
        }
      },
      mounted: function () {
        console.log("MOUNTED %s: This will be called every time a panel view with this section is viewed", this._uid)
        this.pollForUpdates()
      },
      unmounted: function () {
        console.log("UNMOUNTED %s, THIS WILL NEVER BE CALLED", this._uid)
      }
    }
  }
})
```

When putting this section onto a page it will create an instance and call the `mounted()` method every time you open a page with this section. The `unmounted()` method is never called and the polling method still gets called. Even worse: Every time you open the same page again a new instance is created so you will end up with many instances of this section when working in the panel. 

**Expected behavior**  

The section is destroyed when navigating to another view in the panel or logging out.

## Your setup
**Kirby Version**: 3.8.3

**Comment by bastianallgeier** [comment]
Did you try the created, destroyed hooks for this?

**Comment by thathoff** [comment]
Yeah I did. Sorry for not mentioning it. But I think it should work with mounted/unmounted methods too. At least it does with other Vue apps.

**Comment by bastianallgeier** [comment]
It might be related to the way we handle routing with Fiber. We didn't run into it yet, because we mostly clean up stuff in the destroyed hook. We need to look into it why the components are not unmounted properly.

**Comment by WebMechanic** [comment]
Just a hunch, but I believe you're creating a closure.
Store the timerout id from `setTimeout()` and call `clearTimeout()` in both `beforeDestroy` and the `if (!panel.$user)` condition.

**Comment by thathoff** [comment]
Sure that’s one part of the problem, but my point is `unmounted()` is not called which normally can be used to destroy the Timeout. We can do the same with `destroy()/beforeDestroy()`, yes.

**Comment by distantnative** [comment]
This is slightly awkward to only comment on so many months later: But Kirby uses Vue 2 and I don't think `unmounted` exists in Vue 2, only `destroyed`: https://v2.vuejs.org/v2/guide/instance#Lifecycle-Diagram

It does work with `destroyed`.
