### ISSUE TITLE
Tag field require pressing spacebar twice to create space

### ISSUE THREAD

**Issue by miragecraft** [k-next/kirby#4977]
## Description

When I want to add a tag with space, I have to press the spacebar twice. The first time I pressed space nothing happens.

**Expected behavior**  

I should be able to create space by pressing spacebar once

It works as expected in 3.7.4, however after I upgraded to 3.8.3 I started seeing the issue.

**Comment by lukasbestle** [comment]
I can reproduce the issue with Kirby 3.8.3 in Safari 15.6.1.

**Comment by afbora** [comment]
I've tested on few versions and this issue appeared on 3.8.3. Working on 3.8.2 as expected.

**Comment by lukasbestle** [comment]
✅
