### ISSUE TITLE
Toolkit license question

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#4980]
I'm trying to make a standalone Kirby Toolkit with some additions (namely: fully fluent interface between collections, strings and arrays), but there are some required files that are covered by Kirby license, not the MIT Toolkit itself is licensed under.

This is what I define as "the Toolkit" - everything under `src/Toolkit` and other files listed in the reference as "Tools" - all of which are MIT licensed.

But there directly used files the Toolkit depends on:

- kirby/src/Cms/App.php 
- kirby/src/Cms/Collection.php 
- kirby/src/Cms/Field.php 
- kirby/src/Cms/File.php 
- kirby/src/Cms/Helpers.php 
- kirby/src/Cms/Page.php 
- kirby/src/Cms/Site.php 
- kirby/src/Cms/User.php 
- kirby/src/Uuid/Uuid.php 

Some uses I checked:

- kirby/src/Cms/App.php - required by `Dom::isAllowedUrl()`
- kirby/src/Cms/Field.php - required by `V::size()`
- kirby/src/Uuid/Uuid.php - required by `V::uuid()`

Of course, there is also `Kirby\Query\Query` (replacing `Kirby\Toolkit\Query` since 3.8), which is useless in non-Kirby code, but is still a requirement of `Str::query`.

What would be the best way to continue? I could go through the files manually, but then I'd need to recreate the removal/changes on every update - or I'd need to do a file comparison between the standalone toolkit version and the new Kirby version, which sounds managable.

Does the Kirby team have any insights?

(as for why I'm doing this: while there are other fluent/toolkit libraries, I already use the Kirby one a lot and thought it would be nice to use the same utility classes with the same naming scheme)

**Comment by lukasbestle** [comment]
In Kirby 2, the Toolkit was a separate package with its own releases. We merged it in Kirby 3 to make updates easier, both for us and for users (no more recursive submodules). It also enables us to make the classes more useful when used inside the CMS environment.

Our general goal still is that all MIT-licensed classes are useful on their own, without the CMS code. So e.g. you see in a lot of places that we use `App::instance(null, true)`, which returns a "lazy" instance. Meaning: If the CMS is not running, it will just return `null` and will not hinder the operation of the MIT-licensed class.

If you really want to extract the MIT-licensed classes into your own package, I'd recommend to "shim" the core classes. Basically reimplement the minimum-viable logic that is required for Toolkit compatibility. E.g. in the `App` example, you would just define a static `instance` method that always returns `null`. `Field` could be just an empty class as the class only needs to be there for `V::size()`, it won't get instantiated by it. Etc.

If your additions are generally useful, we welcome contributions via pull requests, then you wouldn't have to maintain a separate package.

**Comment by adamkiss** [comment]
@lukasbestle That was of course my intention - there are a couple of `A::` functions I plan to implement that will be PR'd, of course, but the separate packaging is for two reasons:

1. Pulling the whole Kirby for system scripting, or other non-Kirby libraries just doesn't make sense - I may even try to do a single PHP file build a la [F3](https://www.fatfreeframework.com/3.8/home)
2. I don't think Kirby is interested in fully fluent version of (off the top of my head) `Str`, `A` and `Collection`, and sometimes I do processing where I just enjoy going fully fluent.

Shimming the files makes sense, thanks.

**Comment by lukasbestle** [comment]
Regarding fluent interfaces for Toolkit classes (at least `Str` and `A`; `Collection` is already fluent): I'd love that. We could even do it quite easily by implementing a `__call()` method that calls the respective static methods on the instance prop. There could be a new helper class for that which those Toolkit classes could extend.

**Comment by adamkiss** [comment]
In that case, I'll work on some PRs. After further consideration, for scripting uses, I'll probably work out a small, single file variation of the toolkit.
