### ISSUE TITLE
`object` field rendered in a k-drawer do not correctly expand the value column

### ISSUE THREAD

**Issue by renestalder** [k-next/kirby#4984]
## Description

Using an `object` field that is rendered in a Kirby drawer, the second column containing the field value is rendered with a `max-width: 0`. Therefore, the contents are not visible.

**Expected behavior**  
The `object` field should render label and value correctly when the preview is shown in a Kirby drawer.

**Screenshots**  
![Screenshot from 2023-01-03 14-04-31](https://user-images.githubusercontent.com/105358/210363090-1e135f68-7211-427e-8e52-1658adefcebe.png)
_Screenshot of a sample `object` field. The image and the alternative text are currently set, but not rendered in the preview of the `object` field._

![Screenshot from 2023-01-03 14-07-43](https://user-images.githubusercontent.com/105358/210363377-005cd78b-3873-4b92-acb6-c4f436e8abf1.png)
_Removing the `max-width` in the browser dev tools_

![Screenshot from 2023-01-03 14-08-20](https://user-images.githubusercontent.com/105358/210363423-8a777efc-8d88-40f2-b4ac-e2db16a094c5.png)
_Renders the value when removing the `max-width`_

## To reproduce

1. Create a custom content block
2. Add a `object` field with text and image fields to this custom block
3. Now edit this custom block in the panel and set values for the two subfields of the `object` field

## Your setup
**Kirby Version**  
Tested with 3.8.2 and 3.8.3

**Console output**  

**Your system (please complete the following information)**
 - Device: PC
 - OS: Linux
 - Browser: Chrome
 - Version: 110.0.5478.4

**Additional context**  

It's not entirely clear to me why there is a `max-width: 0` set, or what the correct solution is. I just noticed that this is blocking the contents from being shown.

**Comment by distantnative** [comment]
This has been fixed in the upcoming v4-alpha.5
