### ISSUE TITLE
Panel: Changing year on Date field says "Maximum call stack size exceeded."

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4993]
## Description

When changing the year on a Panel date field, the field shows an error "Maximum call stack size exceeded."

Reproduces on Kirby Demo site.

**Screenshots**  

https://user-images.githubusercontent.com/417182/211374769-2dfca8fb-94a1-4118-b292-21f1235c0ef9.mov

## To reproduce

1. Go to page in Panel with a Date field
2. Click on calendar icon
3. Click on Year dropdown
4. Select a different year

## Your setup
**Kirby Version**  
`3.8.3`

**Console output**  

Didn't see any output.

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS 12.6.2
 - Browser: Safari
 - Version: 16.2

**Additional context**

**Comment by afbora** [comment]
Thanks for report! This is known issue as https://github.com/getkirby/kirby/issues/4968 and will be fixed in 3.8.4
