### ISSUE TITLE
Panel: Tags field suggestions no longer selectable with keyboard

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#4994]
## Description
When typing in a Tags field, you should be able to use the arrow-down key to accept a suggestion.

I'm pretty sure this worked as expected in 3.8.2, but broke in 3.8.3. Now you have to select with a keyboard.

Reproduces on Kirby demo site.

**Expected behavior**  

**Screenshots**  

<img width="549" alt="Screen Shot 2023-01-09 at 11 25 37 AM" src="https://user-images.githubusercontent.com/417182/211391583-e32b2990-0845-4026-986f-2194fb129844.png">

## To reproduce

1. Click in Tags field
2. Type a couple letters
3. Press down arrow key

## Your setup
**Kirby Version**  

`3.8.3`

**Console output**  

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS 12.6.2
 - Browser: Safari
 - Version: 16.2

**Additional context**

**Comment by afbora** [comment]
I can confirm that works for 3.8.2. Also multiselect arrow actions doesn't work for 3.8.3.

**Comment by afbora** [comment]
@distantnative I've done some tests and I can confirm that this issue is related with https://github.com/getkirby/kirby/pull/4818 PR.

**Comment by distantnative** [comment]
Unfortunate, but I think the best way here is to revert the PR. Since it was just Vue3 preparation and just this component, we are not losing anything by reverting it.

**Comment by bastianallgeier** [comment]
✅
