### ISSUE TITLE
Block hooks

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#4998]
I want to give more visibility to this nolt wish by @MaluNoPeleke: [a block :before and :after hook](https://kirby.nolt.io/340). I have the same use case as Frederik: adding id's to headlines like described in [this cookbook](https://getkirby.com/docs/cookbook/extensions/table-of-contents#replace-headlines-with-anchors). In my case for [jump links](https://ux.stackexchange.com/questions/141720/what-should-we-call-the-mouse-over-heading-link-pattern-and-where-is-it-best-do):

![Screenshot 2023-01-11 at 17 12 04](https://user-images.githubusercontent.com/60777/211857555-7adcbeff-3cc3-463e-b6de-aef2d775098e.png)

It has also been requested in [the forums](https://forum.getkirby.com/t/hook-into-block-s-writer-field/22780) by @S1SYPHOS. Yes, you can use a field method. A block hook would just be way cleaner and in line with Kirby.

**Comment by afbora** [comment]
We do not bring ideas from Nolt here and do not discuss new ideas here. Please use Nolt for existing and new ideas. Nolt is always on our agenda.

**Comment by mrflix** [comment]
Fair enough. It feels like Nolt is dead. Good to know that it's still on your agenda.

**Comment by S1SYPHOS** [comment]
Feature requests are probably best posted on Nolt 😅 as much as I want this feature to happen, this is the way of user feedback around here 😉

**Comment by S1SYPHOS** [comment]
If you want to advertise great ideas already posted on Nolt, try to rally some support and get people to vote! It's the hardest part (it always is), but that's the way around here. If the Kirby devs have time and resources to make new things happen, they will turn to Nolt and see what's on there.

Not posting new ideas all the time doesn't mean it's dead! 😉

**Comment by bastianallgeier** [comment]
@mrflix I wrote a bit more about it on Discord that will hopefully explain the situation: https://discord.com/channels/525634039965679616/525634039965679618/1063054918652526612

Discord felt like a better place for that because more people will see it.
