### ISSUE TITLE
Panel: Language selector out of sync when using browser back and forward

### ISSUE THREAD

**Issue by chaeringer** [k-next/kirby#5007]
(First of all thanks a lot for your amazing work with Kirby over the years! 👏)

## Description

**Expected behavior**  

Language selector and `language` URL parameter should always be in sync and content changes should only affect the current active language. 

**Screenshots**  
![Screenshot 2023-01-17 at 19 59 47](https://user-images.githubusercontent.com/1009778/212989329-54a3ef1b-e772-4066-b213-5a2e7eddd5f9.png)

https://user-images.githubusercontent.com/1009778/212992306-d4ddc60e-0541-474a-835c-6efb8db1279a.mov

## To reproduce

0. Kirby page with multiple languages
1. Go to any page and change the language with the language selector
2. Use the browser back or forward button
3. Language selector and `language` URL parameter are out of sync
4. Change content in one language. Save the changes. Content in other language is overwritten 
5. In my example above english content is overwritten with german content.  This issue "works" in both directions.
6. 🚨 Content is lost

https://github.com/chaeringer/kirby-starterkit-testcase (newest starterkit with multiple languages)

## Your setup
**Kirby Version**  
Kirby 3.9.0 
I was able to reproduce the issue also with 3.8.1.1 

**Your system**
- Chrome Version 108.0.5359.124
and
- Firefox 109.0
- macOS BigSur Version 11.6.2

**Comment by afbora** [comment]
@distantnative Could we solve with listening `onpopstate`?

````js
window.onpopstate = function () {
  // reload page with fiber or native
};
````

**Comment by stananiev** [comment]
Yep, I have the same issue!

**Comment by distantnative** [comment]
@afbora definitely is on the right track that Fiber hasn't handled popping the state properly. I've a first PR that could solve the issue, have to test for side effects etc.

**Comment by bastianallgeier** [comment]
I think I have a fix (see PR above)
