### ISSUE TITLE
`Dir::index` - `ignore` argument doesn't do anything

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#5010]
## Description
One of the parameters of `Dir::index` doesn't do anything other than being pass along to a recursive, call where it doesn't do anything again.

**Expected behavior**  
Makes `Dir::index` ignore file, either by relative name (`file.txt`), or absolute name.

## To reproduce
Just look at the source: https://github.com/getkirby/kirby/blob/066b0506a81fdd331edc54add601d907a61ebbb4/src/Filesystem/Dir.php#L143-L165

`$ignore` is used only once, and that's when the recursion is called.

**Comment by lukasbestle** [comment]
Good catch! This method is basically unchanged since the very first commit of Kirby 3, so we have this bug for quite a while now.

**Comment by bastianallgeier** [comment]
✅
