### ISSUE TITLE
'Invalid argument "-" in method "-"'

### ISSUE THREAD

**Issue by adamkiss** [k-next/kirby#5012]
I'm trying out Bruno's [Boost](https://github.com/bnomei/kirby3-boost) plugin, but something is wrong with my cache configuration.

When the `(trait) AppCaches->cache()` tries to warn me about it, something about how the `InvalidArgumentException` is constructed is broken:

<img width="712" alt="CleanShot 2023-01-19 at 20 04 51@2x" src="https://user-images.githubusercontent.com/481362/213536681-ba9350a7-e083-402e-a226-616d269159df.png">

I don't know if this is purely my bad (i.e. extremely wrong configuration), or `InvalidArgumentException` constructor changed and this wasn't updated.

---

Find my error - I had cache set to something I haven't the driver for. I'm still not sure that exception is constructed right.

**Comment by bastianallgeier** [comment]
✅
