### ISSUE TITLE
Panel account view: Undefined variable $id error when uploading a user avatar

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#5022]
## Description
When trying to upload an image to a user account, an error message Undefined variable $id is shown. 

**Expected behavior**  
The user avatar should be uploaded without error.

## To reproduce

1. Go to 'user account'
2. Click on avatar
3. Select an image to upload

## Your setup
**Kirby Version**  
Kirby 3.9.0
When downgrading to 3.8.4, the error doesn't appear.

**Console output**  
See https://forum.getkirby.com/t/user-profile-pic-error-undefined-variable-id/27673/3

**Comment by lukasbestle** [comment]
✅
