### ISSUE TITLE
Search results in a flipped pages section are also flipped

### ISSUE THREAD

**Issue by chris-corby** [k-next/kirby#5025]
## Description
If you have a pages section with a blueprint like:

```yml
events:
  label: Events
  type: pages
  flip: true
  search: true
```
When you search within the section the results will be shown least > most relevant — they are also flipped.

**Expected behavior**  
I would expect that `flip: true` would be ignored once you initiate a search. I don’t think a user would ever expect to see the least relevant results first.

## To reproduce
1. Go to a flipped pages section in the panel with lots of pages to search through
2. Search for a term
3. See the most relevant result at the bottom of the list

## Your setup
**Kirby Version**  
3.8.2

**Your system (please complete the following information)**
 - Device: iMac
 - OS: Ventura 13.0
 - Browser: Chrome
 - Version: 109

**Comment by distantnative** [comment]
✅
