### ISSUE TITLE
Default API endpoint for fields

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5029]
## Description

Requesting a Page Field endpoint from within the panel results in a 404 error. 
```js
window.panel.app.$api.get(`/pages/${pageId}/fields/${fieldName}`);
```
Where `pageId` is a page path like `parent-page+child-page` and `fieldName` is a field registered with the requested page.

**Expected behavior**  

Get the correct field response.

## To reproduce

1. Log into the Kirby panel
2. Make sure a page with fields exists.
3. Take note of a field name and the page path.
4. Open the Browser Dev Console 
5. Run command from Issue Description from the Browser dev console
```js
window.panel.app.$api.get(`/pages/${pagePath}/fields/${fieldName}`); 
```

## Your setup
**Kirby Version**  
3.9.0

**Console output**  

```js
{
  "status": "error",
  "message": "No route found for path: \"\" and request method: \"GET\"",
  "code": 404,
  "exception": "Exception",
  "key": null,
  "file": "../kirby/src/Http/Router.php",
  "line": 172,
  "details": [],
  "route": "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)/fields/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)(?:/(.*))?"
}

```

**Comment by lukasbestle** [comment]
I can reproduce this. For some reason, `$field->api()` in [this line](https://github.com/getkirby/kirby/blob/066b0506a81fdd331edc54add601d907a61ebbb4/src/Cms/Api.php#L59) is `null` (tested with a simple text field in the Starterkit). This means that there is no route that could be matched.

**Comment by rasteiner** [comment]
for that to work, the code behind [`Kirby\Form\Field::api()`](https://github.com/getkirby/kirby/blob/066b0506a81fdd331edc54add601d907a61ebbb4/src/Form/Field.php#L95) would suggest that the field needs an `api` entry in the options configuration array. The [text field](https://github.com/getkirby/kirby/blob/main/config/fields/text.php) doesn't do that, neither does the [`select`](https://github.com/getkirby/kirby/blob/main/config/fields/select.php) field the OP is asking for (according to discord). 

You'd need to check the endpoint on a field that offers an api, like the [pages field](https://github.com/getkirby/kirby/blob/main/config/fields/pages.php#L81-L103) or the [files field](https://github.com/getkirby/kirby/blob/main/config/fields/files.php#L88-L129). 
In fact the endpoint seems to work there as expected

**Comment by lukasbestle** [comment]
@rasteiner Thanks for the additional information. You explain it very well: So far the field API is only intended for more complex fields that need to provide additional data to the Panel.

What we could do is to have a default route that just returns basic information or even just a simple response with `HTTP 200` that just confirms that the field is there. Actually I think this is more of an enhancement.

@ovenum What is your use case for using the API like this?

**Comment by rasteiner** [comment]
This is the discord thread: https://discord.com/channels/525634039965679616/1069643179881676800

The use case is retrieving the options for a select field of a different page in the panel. So basic info about the field, or even the field value wouldn't be enough.

**Comment by ovenum** [comment]
> @ovenum What is your use case for using the API like this?

Currently this is more a nice-to-have information displayed in a custom block with a `pages` field. 
The Block preview should load and display a field value once a page is selected. 

A convenient way to fetch Fields from a page can be useful and most of the code is already in place (?). Using the `/pages/page-id?selection=content` will get the values stored with the pages content-text file. But for Structure or any of the Select fields this is usually not enough when the value is a or uuid/slug which is mapped to Label. 

Reading @rasteiner explanation in the [Discord thread](https://discord.com/channels/525634039965679616/1069643179881676800) i understand how the `pages/field` route is meant to be used a bit better. But maybe we can have a default endpoint for each responding with a Field response as `pages/.../sections/` will do?

**Comment by rasteiner** [comment]
I guess a default route could produce whatever is produced for fiber?

**Comment by distantnative** [comment]
Updated the title to make it clearer what this is about in the end

**Comment by distantnative** [comment]
Move to https://kirby.nolt.io/576
