### ISSUE TITLE
`$page->next()` not returning correct class type

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5039]
## Description
When using `$page->next()->url()`, my IDE returns that `url()` is an undefined function.
This was first posted by me in a discussion on [Discord](https://discord.com/channels/525634039965679616/525641819854471168/1070854232221155418).
![image](https://user-images.githubusercontent.com/29142128/216572923-a35bc173-8dcd-4edc-afa4-d6e5240227e7.png)

This most likely happens because the `next()` (and probably also `prev()`) methods that are defined in https://github.com/getkirby/kirby/blob/main/src/Cms/HasSiblings.php were typed to always return a `Kirby\Cms\Model` object, which obviously do not contain page-related methods.

**Expected behavior**  
Ideally, my IDE would detect that the return value of `$page->next()` is a `Page` class, and thus I can use `url()` or other page-specific methods.
<img width="671" alt="CleanShot 2023-02-03 at 11 11 53@2x" src="https://user-images.githubusercontent.com/29142128/216573596-7be8f71b-8ecd-4862-ab1b-b506c9d16873.png">

## Workaround
@lukaskleinschmidt posted the following workaround on Discord, which (option B) works quite well for me.
```php
<?php
// You can put a file called autocomplete.php in the root folder for example.

/**
 * A helper file for Kirby, to provide autocomplete information to your IDE
 */

namespace Kirby\Cms {

    /**
     * Option A.
     * 
     * @method \Kirby\Cms\Page|null next($collection = null)
     */
    class Page {}

    /**
     * Option B will also work for custom page models.
     * 
     * @method static|null next($collection = null)
     */
    class Page {}

}
```

Pretty sure that this can be adapted to be included 'by default'.

## Your setup
**Kirby Version**  
3.9.0

**Comment by lukasbestle** [comment]
I wonder if there's anything that speaks against type-hinting `HasSiblings::next()` and `HasSiblings::prev()` with a return value of `static` in the first place. The CMS collections like `Cms\Pages` validate that each element is of the same type, so these methods should always return an object of the same type as the current one.

**Comment by distantnative** [comment]
I was thinking about the same thing, I don't think we've ever really mixed collections.

But what about page models? Static would be fine or will it take on the more specific class?

**Comment by lukasbestle** [comment]
Right, that's a problem. I think we need to add `@method` type hints to each model class with the fixed class name then.

**Comment by lukaskleinschmidt** [comment]
`static` will always hint to the current class implementation. So for custom page models it will resolve to the custom model.
Using `static` is probably the right choice here. Not sure why but you could also typehint `self` which would refer to the class the method is actually defined in.

**Comment by distantnative** [comment]
But then static would be problematic. In a collection of pages I might have one with a custom page model, the other not. The custom page model cannot expect the next collection item to be of the same custom page model.

**Comment by lukasbestle** [comment]
Yep. Regarding `self`: Does that work inside a trait?

**Comment by lukaskleinschmidt** [comment]
It actually does not.

Edit: I think the only way to make `self` work in this context would be to add something like this to the class definition:
```php
/**
 * @method self next(\Kirby\Cms\Collection|null $collection)
 */
class Page extends ModelWithContent
{
    // ...
}
 ```
 
 Edit2: Or even `@method self|static next(\Kirby\Cms\Collection|null $collection)`

**Comment by lukasbestle** [comment]
Yes, that matches my conclusion. I think at this point we might as well use `@method \Kirby\Cms\Page next(...)` for added clarity. `self|static` doesn't really add anything valuable as the only methods one can rely on are the ones of the `Page` class, not of models.

**Comment by afbora** [comment]
Let's say we add `@method` this for the `->next()` method. But I just wonder that what do we do with all the methods in all traits? It's the same for all of them. Do we add all methods in all traits to the doc-block of the related class? 🤔

**Comment by lukasbestle** [comment]
Unfortunately that seems to be the logical conclusion. The way Kirby uses OOP is more dynamic/less strict than tools can understand. So if we want to add full support for tools, we need to add a lot of manual hints. E.g. also for field methods. But I'm not sure if that's viable as we need to keep all manual hints updated with every change to the code base.

**Comment by distantnative** [comment]
Indeed that would be a lot of extra hints to manually maintain, given that this isn't just for `HasSiblings` but other traits probably too.

**Comment by lukasbestle** [comment]
That's true. We also saw the same issue in https://github.com/getkirby/kirby/pull/5038#issuecomment-1435720272.

What we could do as a compromise is to change the type hints of `next()` and `prev()` to `static`. That's actually more specific than the current state. Not as specific as it needs to be, but given our findings from this thread I honestly don't think we'll be able to define any more correct type data without massive sets of manual hints.

A possible option for the future would be a separate stub file that contains all those manual hints in one place and that can be used with IDEs and also with our Psalm type checker tooling.

**Comment by lukaskleinschmidt** [comment]
I also think that especially in the case for the `next()` method in this example the current `Kirby\Cms\Model` typehint is just too unprecise. Upgrading it to `static` will most likely be good enough for most use cases.

If someone has more specific needs you can still add more specific hints to a custom page models if needed.
Perhaps a cookbook article on how to do something like this would help too.

For Laravel projects I often use https://github.com/barryvdh/laravel-ide-helper to create a file for (more) specific type hints. Perhaps having something like this for Kirby could also be a viable option to have as a standalone package to make it work for/with custom user code as well.

**Comment by lukasbestle** [comment]
That's nice, we could add something like that to the CLI in the future.
