### ISSUE TITLE
Page::create ignores isDraft

### ISSUE THREAD

**Issue by SeriousKen** [k-next/kirby#5042]
## Description

The code I have written to populate a blog with a mix of drafts and published articles prefixed with the value from the date field for sorting fails, all pages are drafts. The `isDraft` prop is documented here https://getkirby.com/docs/reference/objects/cms/page/create.

## To reproduce

1. `composer create-project getkirby/plainkit`
2. Change dir into the project
3. `composer require fakerphp/faker`
4. Create a file `seed-blog.php` in the root of the project with the following:

```
<?php

use Kirby\Cms\Page;

require 'kirby/bootstrap.php';

$app = new Kirby();
$app->impersonate('kirby');

$blog = $app->site()->find('blog');

$faker = Faker\Factory::create();
$faker->seed(12345);

for ($i = 0; $i < 100; $i++) {
    $date = $faker->dateTimeThisDecade();
    $page = Page::create([
        'parent'   => $blog,
        'slug'     => $slug = join('-', $faker->words(5)),
        'isDraft'  => $faker->boolean(25),
        'template' => 'article',
        'content'  => [
            'title' => $faker->sentence(),
            'date'  => $date->format('Y-m-d H:i:s'),
            'body'  => $faker->paragraphs(5, true),
        ],
    ]);
}
```

4. Create `content/blog` folder
6. Create `site/blueprints/pages/article.yml` with the following:

```
num: '{{ page.date.toDate("Ymd") }}'

fields:
  date:
    type: date
  body:
    type: textarea
```

7. `php seed-blog.php`

**Kirby Version**  

3.9.1

**Comment by texnixe** [comment]
I think the problem is in the above code, see this thread for more information, the prop needs to be `draft` instead of `isDraft` (the docs are wrong at this point) and I think and the `num` prop needs to be set for listed pages. This works, for example:

```
$faker = Faker\Factory::create();
$faker->seed(12345);
$kirby->impersonate('kirby');

for ($i = 0; $i < 10; $i++) {
  $date = $faker->dateTimeThisDecade();
  $bool = $faker->boolean(0);
  $newPage = Page::create([
    'parent'   => page('blog'),
    'slug'     => implode('-', $faker->words(3)),
    'draft'    => $bool,
    'template' => 'article',
    'num'      =>  (int) $date->format('Ymd'),
    'content'  => [
      'title' => $faker->sentence(),
      'date'  => $date->format('Y-m-d H:i:s'),
      'body'  => $faker->paragraphs(5, true),
    ],
  ]);
}
```

**Comment by SeriousKen** [comment]
Using `$faker->boolean(0)` gives `false` all the time (the parameter is the chance of getting true). Using your code I get an exception:

```
Kirby\Exception\PermissionException: The page "fugit-soluta-officiis-sit-a" cannot be sorted in /home/serious/project02/kirby/src/Cms/PageRules.php:153
```

**Comment by texnixe** [comment]
Forgot to mention that `time` needs to be set to `true`on the date field for your date format in the content to work.

**Comment by distantnative** [comment]
✅
