### ISSUE TITLE
System view: word wrapping in update checks

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#5046]
## Description

Using the German localisation, the update check on the system view breaks in strange ways:

<img width="316" alt="grafik" src="https://user-images.githubusercontent.com/25466/217208356-85cec88c-132b-493b-bca8-c72f20350232.png">

**Expected behavior**  
The definitions should always be single line for better readability.

## Your setup

- Kirby 3.9.1
- Firefox
- MacOS

## Possible solution

This issue can be solved by not specifying a width on `.k-plugin-info` (or by switching to `min-width`) and then setting `white-space: nowrap;` on the nested `dt` and `dd` elements.

<img width="318" alt="grafik" src="https://user-images.githubusercontent.com/25466/217210662-75c93280-7fd7-4a13-ae0d-aaa7143f7005.png">

**Comment by afbora** [comment]
I can't reproduce the issue on Windows & Chrome & Kirby 3.9.1 🤷‍♂️ Which browser do you use?

![image (16)](https://user-images.githubusercontent.com/3393422/220348767-43b27897-d2f2-4b83-b065-71b87d296ff3.png)

**Comment by nilshoerrmann** [comment]
That's Firefox on macOS. Looks like your system font is smaller than Apple's.

**Comment by lukasbestle** [comment]
I cannot reproduce the issue in Firefox 113.0.1 on macOS either. Is this still an issue for you @nilshoerrmann?

<img width="441" alt="Bildschirmfoto 2023-05-13 um 13 31 44" src="https://github.com/getkirby/kirby/assets/1595007/bbeb831d-b6b1-473a-87c6-be0266c13780">

**Comment by nilshoerrmann** [comment]
I'll check next week.

**Comment by nilshoerrmann** [comment]
This is what I get, same Firefox version, macOS 13.3.1 (a):

<img width="336" alt="grafik" src="https://github.com/getkirby/kirby/assets/25466/6dfc4661-b183-4979-9920-dfbf7576a7f6">
<img width="334" alt="grafik" src="https://github.com/getkirby/kirby/assets/25466/6a34f850-c3ba-4636-81ae-3a1b91d51dc3">

This is how it looks like in small/mobile view:

<img width="390" alt="grafik" src="https://github.com/getkirby/kirby/assets/25466/5b58a331-1928-4a29-bdae-eb5804525965">

**Comment by lukasbestle** [comment]
Thank you for your tests and screenshots. I still can't replicate the issue unfortunately.

Using `white-space: nowrap` would certainly be a general solution for such wrapping issues. However I'm worried that we may instead introduce issues where the box overflows the browser canvas. We would trade one potential issue for another potential issue and TBH I don't think that would be worth it.

Leaving this issue open for input from the team, but I have to be honest: A purely visual imperfection that cannot be reproduced reliably is not among the most urgent issues.

**Comment by distantnative** [comment]
This will be fixed in the next v4 alpha
