### ISSUE TITLE
Can't change template of file in `file.create:after` hook on multi-lang setup

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5049]
Forum discussion: https://forum.getkirby.com/t/cant-change-template-of-file-in-file-create-after-hook/27781

**Comment by afbora** [comment]
I think this is about related line: https://github.com/getkirby/kirby/blob/3.9.1/src/Cms/File.php#L179-L184
I've a simple solution. I'll create a PR in next week.

````php
public function contentFileData(array $data, string $languageCode = null): array
{
    return A::append($data, [
        'template' => $data['template'] ?? $this->template(),
    ]);
}
````

**Comment by bastianallgeier** [comment]
✅
