### ISSUE TITLE
asset() helper breaks when using an image file since 3.9

### ISSUE THREAD

**Issue by anselmh** [k-next/kirby#5065]
## Description

When using the `asset()` helper to display an svg or image from the assets folder, the site breaks in Kirby 3.9.0 with the following error:
```
The method: "alt" does not exist in /kirby/src/Filesystem/IsFile.php:67
```
The related Pull Request ist https://github.com/getkirby/kirby/pull/4915/files#diff-7031b31652730041abe5f4d32a50811dbe847ec7a189b645f7e9b533979fa370R117 and if I comment out the highlighted line, it works again.

Example code would be: 

```
<?php echo asset('assets/icons/kirby-logo.svg') ?>
```

**Expected behavior**  
In previous versions, using this helper worked fine. Now it produces a sever error. It should work or be declared as breaking change but then we’d need some sort of replacement for this behavior as the `image()` is using a page path while `asset()` and svg()` use other file paths as arguments so it’s not exactly the same functionality.

## Your setup
3.9.x

**Additional context**  

[Initial verification and discussion is here](https://discord.com/channels/525634039965679616/1078239629356056586)

**Comment by afbora** [comment]
@distantnative @lukasbestle What do you think about adding new `Asset::alt()` method?

````php
public function alt(): string|null
{
  return null;
}
````

**Comment by distantnative** [comment]
I think it would be cleaner to let https://github.com/getkirby/kirby/pull/4915/files#diff-7031b31652730041abe5f4d32a50811dbe847ec7a189b645f7e9b533979fa370R117 check for the `alt` method before using it

**Comment by lukasbestle** [comment]
`$image->model` comes from `Filesystem\File::$model`, which needs to be an instance of a class that implements the `IsFile` trait. So if we wanted to cover all bases, we would need to implement the `alt()` method there. But I agree with Nico that this is not very clean as non-image files won't have an alt text.

Unfortunately the `alt()` method is never explicitly defined but called from the magic `__call()` method of `Cms\File`. So I see three different routes:

- A new `Cms\File::alt()` method that can then be checked for with `method_exists($this->model, 'alt')`. However this seems oddly specific.
- A check for `$this->model instanceof CmsFile` (with `CmsFile` being imported with `use Kirby\Cms\File as CmsFile`). However this would limit this feature to CMS files.
- A check for `method_exists($this->model, 'content')` and a call to `$this->model->content()->alt()`. Seems to be a good compromise between the first two options.

**Comment by afbora** [comment]
> * A check for `method_exists($this->model, 'content')` and a call to `$this->model->content()->alt()`. Seems to be a good compromise between the first two options.

@lukasbestle I think this is almost same with first option. What about like following?

````php
use Kirby\Cms\Content;

if (
  method_exists($this->model, 'content') && 
  $this->model->content() instanceof Content
) {
  $attr['alt'] ??= $this->model->content()->alt()->value();
}
````

**Comment by lukasbestle** [comment]
Before that I'd also add `$this->model !== null &&`, but apart from that I like it a lot.

**Comment by distantnative** [comment]
✅
