### ISSUE TITLE
When disabling uuids (via `content.uuid`) File fields lose reference to their files when changing slug

### ISSUE THREAD

**Issue by thathoff** [k-next/kirby#5084]
## Description

When `content.uuid` is set to false in `config.php` the Files field stores the complete file path. This will break changing the pages slug because all linked files inside a page are broken.

Before UUID support Kirby did only store the file’s name so changing the slug of a page did not brake all images. I would expect Kirby to behave as before when disabling UUID support.

This seems to be related to https://github.com/getkirby/kirby/pull/4892

## To reproduce

- set `content.uuid` to fals in `config.php`
- Create a blueprint with a files field
- Upload a file to this field
- Change the slug of the page
- Reference to file is broken because it contains the path including the page’s slug

## Your setup
**Kirby Version** : 3.9.1

**Comment by thathoff** [comment]
I know that adding `store: id` to all Files fields should fix this but it’s not practical as we use the same blueprints on pages that support UUIDs and others that don’t.

**Comment by lukasbestle** [comment]
To be honest I'm a bit confused. If you set the `content.uuid` option to `false`, UUIDs will be disabled on the entire site, so it isn't possible to use UUIDs in some blueprints, no? Or do you mean that you use the same blueprints in other *sites* where UUIDs are disabled globally?

**Comment by thathoff** [comment]
Sorry for the confusion. I’m talking about sites, not pages: We use the same blueprints (via plugins) on sites that have UUIDs enabled and some that don’t. So we don’t want to add `store: id` to all File fields because in this case it would not store the UUID on sites that have it enabled.

**Comment by lukasbestle** [comment]
Makes sense, thanks for clarifying.

So do I understand the issue correctly that the behavior introduced by #4892 correctly works when you use `store: id` but doesn't take effect when UUIDs are disabled completely with the `content.uuid` option?

**Comment by thathoff** [comment]
Exactly!
