### ISSUE TITLE
Finalize "`Dir::index()`: fix `$ignore` parameter"

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#5085]
The PR https://github.com/getkirby/kirby/pull/5069 still has open questions. I think we should resolve those until the final release of 3.9.2 because any future change would be a breaking change:

**No-brainers:**

- [x] Check if `$ignore` is an array in line 154.
- [x] Deprecate the `null` value for `$ignore`.
- [x] Add a `@todo` comment to remove support for `$ignore = null` in a major release.

**Still to be discussed:**

- [x] Should the `$ignore` param be consistent with `Dir::read()` (ignore on each path segment level) or with `Dir::copy()` (full paths)?
  - I still feel like it should ignore on the full path because of the recursive mode that `Dir::read()` does not have but that `Dir::copy()` does have.
- [x] Do we want to support `$ignore = false` for consistency with `Dir::copy()` (ignores the global ignore list)?

**Comment by lukasbestle** [comment]
@distantnative How do we proceed with this? TBH I feel like we should also revert #5069 and include it in a later release. If we release it as-is, we will not have the opportunity to get the feature right later without a breaking change.

**Comment by distantnative** [comment]
Tbh I don't quite understand what happened with the discussion etc when it got merged. Probably something rather for @bastianallgeier.

**Comment by lukasbestle** [comment]
I think it just got approved and merged without having the discussion at all.

**Comment by bastianallgeier** [comment]
I misunderstood the discussion. I thought that all the open questions could/should be retrofitted other repo in because they would already introduce breaking changes. I will take care of the no-brainers today and also check the remaining discussion points again. Sorry for merging it too quickly.

**Comment by bastianallgeier** [comment]
Ok, I had another look at it and I agree with @lukasbestle. The `Dir::index()` method is way closer to `Dir::copy()`. I wonder why `$recursive` is false by default. I think it should actually be true. But well, that's another breaking change. 

I aligned the two methods now and I think it's the right way forward. What do you think? 

Ideally it should be possible to pass wildcards at some point, but this is another future project.

**Comment by bastianallgeier** [comment]
✅
