### ISSUE TITLE
Intended template incorrect when using `php` as content file extension

### ISSUE THREAD

**Issue by yandodov** [k-next/kirby#5087]
## Description
I tested in a Plainkit Kirby setup with the following `config.php`:

```php
return [
	'content' => [
		'extension' => 'php'
	]
];
```

If I create a content file `content/home/test.php` and a template `site/templates/test.php`, that template is not loaded and I get the error:

> The default template does not exist

If I create a default template, it is used, but the content is not loaded from the PHP file.

It appears that this happens because PHP files are ignored in the `Dir` class:

https://github.com/getkirby/kirby/blob/617a07aa0151aa4b1a3735b3b5e1a41ccc244a43/src/Filesystem/Dir.php#L255-L270

If the `$contentExtension` case is handled first, it works as expected:

```php
switch ($extension) {
	case $contentExtension:
		$content[] = pathinfo($item, PATHINFO_FILENAME);
		break;
	case 'htm':
	case 'html':
	case 'php':
		// don't track those files
		break;
	default:
		$inventory['files'][$item] = [
			'filename'  => $item,
			'extension' => $extension,
			'root'      => $root,
		];
}
```

**Kirby Version**  
3.9.1

**Comment by texnixe** [comment]
But the only allowed content file extensions according to the documentation are .txt and .md, everything else is treated as files, apart from the skipped ones (htm(l), php).

https://v37.getkirby.com/docs/reference/system/options/content#content-file-extension

**Comment by yandodov** [comment]
Well, then in that case it would make a lot of sense to support PHP files for content. [As I've suggested on Nolt](https://kirby.nolt.io/504), doing this could be a huge performance boost because PHP files, unlike TXT ones, can be optimized by PHP's OPcache.

I thought that all formats in the Data class are suitable for content files:

https://github.com/getkirby/kirby/blob/617a07aa0151aa4b1a3735b3b5e1a41ccc244a43/src/Data/Data.php#L40-L46

That's why I opened the issue. It appears I was wrong, though.

**Comment by lukasbestle** [comment]
At the moment this is not supported as Sonja wrote. I get how it could be useful, however it could also create issues with a stale cache. OPcache is not always reliable with cache invalidation.

Could you please create a suggestion on https://feedback.getkirby.com for this feature?

**Comment by yandodov** [comment]
I've already made a [suggestion on Nolt](https://kirby.nolt.io/504), as I wrote in my previous comment.

Regarding OPcache being unreliable - I don't think so. I wrote a script that converted all TXT files of an old site to PHP ones and it works normally, except it's faster. Panel is working alright, templates…

Ignoring this looks like a missed opportunity to me.

**Comment by yandodov** [comment]
@bastianallgeier I know you're a fan of performance, so I'll tag you in.

**Comment by bastianallgeier** [comment]
We currently struggle quite a bit with parts where we made Kirby too flexible in the past and now need to fight inconsistencies and multiple options to solve a problem. So while I'm a fan of the idea, I also think that this would need a proper refactoring of the reading and writing mechanisms of content files before we move forward.

**Comment by yandodov** [comment]
Hm, I'm not so sure. The biggest change you'd have to make is the one I've already described in my initial post. I also had to comment out a couple of `json_encode()` calls to avoid JSON in PHP strings for blocks and structure fields, but that's about it. This is on production, works beautifully, and lead to **50% smaller response times**.

I understand where you're coming from, though. Perhaps I've missed something and it really is tough to implement (we're on Kirby 3.5.7.1, not the latest version). In that case, you should still consider it at some point in the future.

**Comment by distantnative** [comment]
> Perhaps I've missed something

This is the problem with making everything as flexible as possible. You and us might miss things. Or don't anticipate changes in the future where this will make it really hard and we are suddenly in the deadlock. This is why we need to first sort out things, refactoring big parts of the system etc. so we can sure adding more flexibility won't bite us. Just adding flexibility is easy - but then quickly everything starts going down. We've been burnt by this recently quite a bit and thus rather cautious. It's good to have the suggestion in Nolt cause that way this nice idea won't get lost and we can tackle it once the rest is ready for such additions.
