### ISSUE TITLE
UUIDs in writer field

### ISSUE THREAD

**Issue by crisgfx** [k-next/kirby#5092]
## Description
Dear kirby team,

I know, feature requests belong to [nolt.io](https://kirby.nolt.io/268),
but I wanted to suggest this as more of an enhancement rather than a new feature,
'cause I think that’s what it is since UUIDs were introduced.
It would be so much of a help, if we can finally paste page- and file id’s into the url mark of the writer field.
For example (with params):
`page://wwZfUaAonRARD3oL?param1=val1&param2=val2#footer` or
`file://MiS3i2Nc5wtVFltK`.

It would also be easy enough to provide an info field on every page with the corresponding 
uuid string, that any panel user can use to copy and paste.
Plus, all the urls would finally be in sync both on production and dev server.

I would modify the writer field myself if I had enough knowledge to do so.
Unfortunately even in a page update before hook it’s not possible 
to parse the string myself, because the href attribute is already missing at that point
(any tips are welcome).

I know, You guys are busy, so thanks a lot for reading! <3

Best,

Cris

## Your setup
**Kirby Version**  
3.9.2-rc.1

**Comment by iskrisis** [comment]
Lets please just let team finish the core UUID functionality and allow for structure/blocks to have UUIDs. IMHO that's more important than UI work around it because they are foundational capabilities that are not really possible to do outside of core.

**Comment by distantnative** [comment]
@CrisGraphics as you correctly pointed out this is something more for feedback.getkirby.com - and as I see you also commented on the existing ticket there. Closing this here as we need this space really for bug tracking etc.
