### ISSUE TITLE
Structure field – better loading feedback

### ISSUE THREAD

**Issue by andreasnymark** [k-next/kirby#5093]
## Description
As mentioned in [4554](https://github.com/getkirby/kirby/issues/4554), structure fields can often be slow. Panel users are sometimes left in an unknown state, not aware the panel is currently working. This happens when user adds a new item, saves an edit or paginates between items.  

**Expected behavior**  
Visual feedback in relation to where the user is working. Disable fields and show a spinner? Dim fields and show a spinner on top? Spinner on button/pagination?

## To reproduce
Look at [4554](https://github.com/getkirby/kirby/issues/4554)

**Comment by afbora** [comment]
@andreasnymark Can you move this suggestion under #4554 please?

**Comment by andreasnymark** [comment]
@afbora Sure. Moved to [4554](https://github.com/getkirby/kirby/issues/4554)

**Comment by afbora** [comment]
Thank you for the feedback and moving @andreasnymark 👍
