### ISSUE TITLE
Site error because of missing closing photo statement PrettyPageHandler.php

### ISSUE THREAD

**Issue by Zaptronic** [k-next/kirby#5098]
## Description
My site doesn't show up because of a missing closing php statement (?>) in PrettyPageHandler.php

**Expected behavior**  
No error so the page renders properly

## Your setup
**Kirby Version**  

**Console output**  
[Fri Mar 10 11:14:40.205308 2023] [error] [pid 25415] mod_proxy_fcgi.c(887): [client 2a01:7c8:7c8:f866:10::1018:0] AH01071: Got error 'PHP message: PHP Parse error: Unmatched '}' in /data/sites/web/zaptronicnl/www/kirby/vendor/filp/whoops/src/Whoops/Handler/PrettyPageHandler.php on line 835'

**Your system (please complete the following information)**
 - php version: 8.1

**Comment by afbora** [comment]
> If a file contains only PHP code, it is preferable to omit the PHP closing tag at the end of the file. This prevents accidental whitespace or new lines being added after the PHP closing tag, which may cause unwanted effects because PHP will start output buffering when there is no intention from the programmer to send any output at that point in the script.

The problem seems not to be related to `?>`. Can you delete the `kirby` directory and replace with the fresh one?

**Comment by Zaptronic** [comment]
I just did. Seems to work!
