### ISSUE TITLE
Sort order is random when uploading files in panel

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#5101]
## Description

I have a page with a files section (at the moment about 1000 images). When I upload new files, they get a somewhat random sort number assigned—one that already exists (!). It seems to have something to do with the pagination / `limit` setting in the blueprint, since it’s often the number set as `limit` + 1. But it also depends on the current pagination page of the files section, so e. g. when I’m on the last page the file(s) get a different sort number (a lower one, to be precise).

**Expected behavior**  

The files being added to the beginning or end of the files section.

## To reproduce

1. Create a blueprint with a files section that is `sortable`
2. (Add some / 1000 files)
3. Upload a new file

## Your setup
**Kirby Version**  

3.9.2

**Your system (please complete the following information)**
 - Device:  MacBook Pro 16" 
 - OS:  macOS 13.1
 - Browser:  Safari
 - Version:  16.2

**Comment by distantnative** [comment]
✅
