### ISSUE TITLE
[3.9.2] Blocks field: copy/paste regression

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5109]
@distantnative is it possible that I found a regression on this fix. Nothing breaking though. I've tested it with a plainkit to be sure it has nothing to do with my setup:

* When you copy a block and paste in the "add block" area it doesn't work
* When copy copy a block and paste in the dedicated "paste block" area, it does work

Screen recording: https://x.gnx.li/js9MwZH8

_Originally posted by @samzzi in https://github.com/getkirby/kirby/issues/4282#issuecomment-1472757094_

**Comment by distantnative** [comment]
✅
