### ISSUE TITLE
HTML entities not interpreted in some blocks fields

### ISSUE THREAD

**Issue by stairjoke** [k-next/kirby#5112]
## Description
When adding, for example, a headline block to a blocks field, HTML-entities are not interpreted. If you need to add a particularly long word in a headline, you might run into trouble, as adding `&shy;` to headlines is not possible.

**Example**
For German Websites the title “Datenschutzerklärung” is used at least once on every website, but displaying this text in a large font on a mobile device will cause problems, and the browser will often need to break the word into multiple lines to fit it on screen. To ensure the word is broken correctly, or broken at all (depending on browser and overflow behavior) and remains legible, adding a `&shy;` entity is usually the way to go: `Daten&shy;schutz&shy;erklärung`.

If you type `Daten&shy;schutz&shy;erklärung` into a headline-block in a blocks field, the `&shy;` will be rendered on your website, instead of the word breaking in that location.

**Workaround**
If you use a Markdown-blocks and type `<h1>Daten&shy;schutz&shy;erklärung</h1>` it works.

### Expected behavior
Typing HTML-entities into any blocks-field renders them correctly on the web.

### Actual behavior
HTML-entities in some blocks-fields show up in plain text.

### Screenshots
View in Editor:
<img width="786" alt="CleanShot 2023-03-17 at 09 20 09@2x" src="https://user-images.githubusercontent.com/991380/225850882-211e3fe0-f464-4c8c-877a-d00b0f82a7f1.png">

Result on website:
<img width="839" alt="CleanShot 2023-03-17 at 09 19 56@2x" src="https://user-images.githubusercontent.com/991380/225850906-0a8d88f5-d6cc-4f20-b1ae-d46356de95f4.png">

Result on mobile, if you leave out the `&shy;` entity:
![httpswenzels designprivacy](https://user-images.githubusercontent.com/991380/225851301-7183d729-bb0c-4e6c-bf99-3f4bb12bbcc5.png)

## To reproduce
1. Add a headline block to a blocks-field
2. Type in a word containing HTML-entities, example: `Daten&shy;schutz&shy;erklärung`
3. Save
4. Open/view the page

## Your setup
Kirby 3.9.2

**Console output**  
-
**Your system (please complete the following information)**
 - Device: iPhone 12 Pro, macBook Pro
 - OS: iOS 16, macOS 13
 - Browser: Safari (both)
 - Version: -

**Additional context**  
Theme used here: https://github.com/stairjoke/wenzels.design version (commit) d97f0fe5ecb68da73dcdfa1b7bc63df000f8c7e8

**Comment by afbora** [comment]
AFAIK This is because some of the fields (heading, list, text, quote) you use in the blocks field use the ProseMirror library (WYSIWYG editor). ProseMirror also escapes the content by default.

**Comment by stairjoke** [comment]
Interesting, I’m not sure how these parts interact. I’d just like it if text entered into a headline was allowed to contain `&shy;` and that worked ☺️

I’m a designer and mostly front-end guy, so I’m pretty much clueless how ProseMirror plays into this. It just felt like a bug to me that I couldn’t format the text correctly in the correct field — totally subjective perspective, I know. I hope this helps.

**Comment by lukasbestle** [comment]
We treat text input literally (as text) to prevent cross-site scripting (XSS) attacks. If we would treat the text input as HTML, malicious Panel users could inject HTML code into the content. Your `&shy;` example is harmless, but it would be really difficult to filter just malicious inputs as it's often very easy to circumvent such filters. Removing the protection entirely is also not an option unfortunately because Kirby is also used in large companies where not every editor can be trusted.

You can however use the actual Unicode character for a soft hyphen in blocks fields. How to type that depends on your operating system. E.g. on Windows it's `Alt-173`. On macOS you can use the "Edit > Emoji & Symbols" pane and search for "Soft Hyphen".

**Comment by stairjoke** [comment]
I understand, and thanks for the suggestion.
