### ISSUE TITLE
Date field with display property changes value while editing

### ISSUE THREAD

**Issue by imitono** [k-next/kirby#5118]
## Description
Date fields with a display property that does not include a day e.g `display: MM-YYYY` change value while editing. In my case it always changes to 08-2024.

## To reproduce

1. Add the following field to a blueprint
```php
date:
    type: date
    display: MM YYYY
```
2. Select a date using the date picker
3. Focus the date field text input
4. Blur the date field text input

## Setup
**Kirby 3.9.2**  

**System**
 - OS: macOS
 - Browser: Chrome
 - Version: 109

**Comment by bastianallgeier** [comment]
✅
