### ISSUE TITLE
Self overwriting custom methods

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5120]
## Description
I came across an issue for some classes which extend a class using hte `HasMethods` trait.
The `Kirby\Cms\Layouts` or `Kirby\Cms\Blocks` classes for example extend the `Kirby\Cms\Collection` class (at least at the end).

This makes all declared `Collection` methods also available in the extended classes. However you could run into issues (or at least unexpected behaviour) when you extend those classes and use the same name for the methods.

```php
App::plugin('my/plugin', [
    'blocksMethods' => [
        'test' => function () {
            return 'blocks method';
        },
    ],
    'layoutsMethods' => [
        'test' => function () {
            return 'layouts method';
        },
    ],
]);
```
```php
$collection = new Collection([]);
var_dump($collection->test()); // layouts method

$collection = new Layouts([]);
var_dump($collection->test()); // layouts method

$collection = new Blocks([]);
var_dump($collection->test()); // layouts method
```
If you would define `public static $methods = [];` in the `Blocks` or `Layouts` classess this would fix the "bleeding" but you would loose the inherited custom methods from the `Collection` class itself.

Fortunately the `$methods` are already static so you could actually kinda extend them like this without having the problem of possible method overwrites.
```php
trait HasMethods
{
    public static array $methods = [];

    public static function getMethods(): array
    {
        $methods = static::$methods;

        if ($parent = get_parent_class(static::class)) {
            $methods = array_merge($parent::getMethods(), $methods);
        }

        return $methods;
    }
}
```
Or maybe prefix the methods for the actually targeted class?
Let me know what you think and I might be able to help prepare a PR for this.

Those two classes where just an example I was currently working with.
So there could be more classes with the same problem.

## Your setup
**Kirby Version**  
3.9.2

**Comment by lukasbestle** [comment]
I like the idea to query the parent class or even all parent classes to allow inheritance. That would definitely allow a much more deterministic behavior. Because the inheritance chains are typically not that long, I don't think there would be a huge performance impact either.
