### ISSUE TITLE
Panel: Command-K in textarea field shows "Add Link" and "Search" dialog at the same time

### ISSUE THREAD

**Issue by neildaniels** [k-next/kirby#5130]
## Description

In a `textarea` Panel field, if you press Command-K (to insert a link), it will also show the Search dialog.

**Expected behavior**  

I would expect it to only offer the Add Link dialog.

**Screenshots**  

<img width="951" alt="Screenshot 2023-03-30 at 8 53 41 AM" src="https://user-images.githubusercontent.com/417182/228894512-b1230f8b-78c2-4169-a013-6c8facc4c5c5.png">

## Your setup
**Kirby Version**  
`3.9.3`

**Console output**  

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS 13.3 (22E252)
 - Browser: Safari
 - Version: Version 16.4 (18615.1.26.11.22)

**Additional context**

**Comment by afbora** [comment]
Related PR https://github.com/getkirby/kirby/pull/5077

**Comment by distantnative** [comment]
✅
