### ISSUE TITLE
Alt text from image source does not get adopted

### ISSUE THREAD

**Issue by holmey** [k-next/kirby#5132]
https://github.com/getkirby/kirby/blob/ce4aaace87ceca1f019a9cfc0293a69e662f9648/config/blocks/image/image.php#L14
In this line the `$alt` is not null so the field value of the image source never gets adopted even there is no text entered in the image block.
I could provide you with a PR with the fix i created for my project, but i wanted to ask if this intended behaviour before submitting it.

**Comment by lukasbestle** [comment]
Thanks for spotting, it's certainly not intended.

I'd say the easiest fix would be appending `->or(null)` to line 4.

**Comment by distantnative** [comment]
@lukasbestle `->or` still gives you a field object, so `??` wouldn't work. But I think line 14 could be `$alt->or($image->alt())`.

**Comment by lukasbestle** [comment]
You are right, much better.

**Comment by holmey** [comment]
#5133

**Comment by bastianallgeier** [comment]
✅
