### ISSUE TITLE
"noopener noreferrer" is redundant

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5134]
## Description
Kirbytext puts `rel="noopener noreferrer"` on rendered links that use `target: _blank`. The writer field, parsley, etc, all do the same. 

**Expected behavior**  
[According to specs](https://html.spec.whatwg.org/multipage/links.html#link-type-noreferrer), `noreferrer` actually implies `noopener`, so specifying both is kind of superfluous.
To keep the current behaviour using less bytes, `noopener` should be removed when `noreferrer` is specified.

## To reproduce
```php
<?= kirbytext("(link: https://example.com target: _blank)") ?>
```
produces

```html
<p><a href="https://example.com" rel="noopener noreferrer" target="_blank">example.com</a></p>
```

## Your setup
**Kirby Version**: 3

## Additional context
https://github.com/search?q=repo%3Agetkirby%2Fkirby+noopener+noreferrer&type=code
https://html.spec.whatwg.org/multipage/links.html#link-type-noreferrer
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noreferrer

**Comment by distantnative** [comment]
✅
