### ISSUE TITLE
user permissions: support for `options` broken

### ISSUE THREAD

**Issue by jaro-io** [k-next/kirby#5147]
**hey there lovely kirby team 🌻**
i am struggling with two things related to user permissions. i don’t know if they are related.
[this](https://github.com/getkirby/kirby/issues/5146) is the other issue. feel free to merge if needed.

## description
i would like users with some roles to be able to create only users with certain roles. for example a `manager` should be able to add an `assistant`. but an `assistant` shouldn’t be able to add a `manager`. both roles however should be able to add a `customer`. to me this sounds like a very common use-case.

i found [this](https://forum.getkirby.com/t/setting-default-user-role-on-creating-in-panel/14927/4) post by @texnixe from some time ago but the code doesn’t seem to work anymore. don’t know if it ever did, but seems like it. also seems like `options` have been removed from user blueprints, and now there’s only `permissions`. at least this is what the latest docs say. anyway, something like the code down below also doesn’t seem to work.

could you please let me know if this is a bug? or a feature request? i guess i could build a workaround with hooks. so when a user tries to create another user with a certain role, an error is being shown. but i would like if some users can’t even see all roles in the "add a new user" modal.

## to reproduce
```yml
permissions:
    users:
        create:
            manager: false
            assistant: true
            customer: true
```

## your setup
kirby 3.9.3

thank you for your help!
🤍 ✨

**Comment by afbora** [comment]
As I understand it, this is a issue [we have had before](https://github.com/getkirby/kirby/issues/2919) and [we are trying to solve it](https://github.com/getkirby/kirby/pull/3850). According to @lukasbestle [comment](https://github.com/getkirby/kirby/issues/2919#issuecomment-834475018) I see that this also valid for the `create` prop.
