### ISSUE TITLE
Horizontal scrollbars shown when using the panel on mobile, dialogs etc are not fitting to the viewport

### ISSUE THREAD

**Issue by garethworld** [k-next/kirby#5148]
## Description

The panel does not scale correctly to the viewport on phone. I get horizontal scrollbars, dialogues and the save bar do not fit without scrolling. 

**Expected behavior**  

The panel UI fits the viewport 

**Screenshots**  

![Screenshot 2023-04-14 at 09 33 17](https://user-images.githubusercontent.com/55981730/231990371-f7242e11-47fa-4a7f-93aa-46f406ff3daf.png)

## To reproduce

View the panel on a phone or at phone size

## Your setup
**Kirby Version**  
3.9.3

**Your system (please complete the following information)**
 - Device: Motorola g6
 - OS: Android 
 - Browser: Chrome
 - Version: 112

Adding this to my panel css does fix it:
`.k-panel {overflow: hidden;}`

**Comment by afbora** [comment]
@garethworld This issue is same/related with #4172 issue and #4362 PR?

**Comment by garethworld** [comment]
Not sure, maybe #4172.  I included a css fix in my first post, which so far does not seem to have any downsides.

**Comment by distantnative** [comment]
@garethworld could you please test with beta.1 and see if this already solved it?
