### ISSUE TITLE
Links in structure overview clickable but not visible

### ISSUE THREAD

**Issue by fritzlaszlo** [k-next/kirby#5157]
Heya,

thanks once again for the fantastic Kirby development and support!
I recently kept stumbling on the following issue, that I couldn't spot anywhere else in the issue list, and that, I think, is not preferable behavior:
I am working on a project that makes use of many structure fields. Inside these structure fields, we use the writer field a lot. And the links that are inside the writer field are not shown in the overview-view, but are still clickable. 

**Example:**
First: Overview of the Structure. A click here expands the entry in the structure and makes the field editable. So easy, so good.
![Screenshot 2023-04-21 at 18 04 33](https://user-images.githubusercontent.com/3307040/233683744-e3ae763b-46c0-454d-8e4b-b08a68e0fafa.png)

Second: Still overview of the structure. Here, the cursor is on a link, that is not highlighted. If I click here, it will open this link and not expand the entry. This is not desirable, as I cannot know all links in all structures by heart and avoid clicking on the unintentionally.
![Screenshot 2023-04-21 at 18 04 46](https://user-images.githubusercontent.com/3307040/233683862-5dbaedb1-0e39-4e9d-908c-fa60e0ff4235.png)

Third: Now in the expanded view the link is visible, and I can avoid clicking on it unintentionally 
![Screenshot 2023-04-21 at 18 03 31](https://user-images.githubusercontent.com/3307040/233684139-577194f7-436f-4f85-b29a-13e324f6f6a4.png)

**Possible solutions:**

- Highlight links in the structure overview visually
- Dont render links as clickable links the structure overview.

Any fix would be much appreciated! 

Thanks,

Fritz

**Comment by afbora** [comment]
Which would be the correct behavior? Removing the link or making the link visible? 🤔

**Comment by fritzlaszlo** [comment]
From my experience, speaking:
The only field in my structure use cases that redirects me to a different field is files, which then redirect me to individual file pages inside kirby. All other fields I use expand the structure and make the entry editable.
In my current use case, I sometimes have multiple links in a single sentence inside a text/writer field. Making the links visible would still challenge me to “click around” the links in order to expand the writer field to edit it. 
Inside a dedicated URL field, I would see more reason to keep the link visible and clickable. 
In the writer field, I am not so sure about keeping it clickable.

**Comment by lukasbestle** [comment]
When we strip links but keep all other formatting, it would IMO be quite inconsistent both within the writer field but also compared to other field previews in the structure field. I can imagine that some users will be confused and think that they forgot to add the link. Which is exactly what happens right now, but I feel like doing it on purpose by removing the link all-together is weird.

So to answer your question @afbora: I'd personally lean towards making the link visible.

@bastianallgeier Can you confirm that the "existing but unstyled link" behavior is an unintended bug?

**Comment by bastianallgeier** [comment]
I think it really is just a visual glitch. The link should be styled in my opinion.
