### ISSUE TITLE
Writer Field Content gets cleared after changing URL of page

### ISSUE THREAD

**Issue by mourique** [k-next/kirby#5161]
## Description
After changing the URL of a page with the default template, a writer field in the blueprint gets cleared of its content and the page switches into the unsaved status (orange bar). When reverting the changes the original content of the field reappears, when saving the page, the field stays empty. This does not happend with a textarea field.

**Expected behavior**  
When changing the URL of a Page nothing else should change. The content of the page should stay the way it is.

**Screenshots**  
i added a small video showing the problem

## To reproduce

1. Go to a page with a writer field 
2. Click on Settings >> Change URL and change the url

## Your setup

**Kirby Version**  
3.9.3

**PHP**
8.0.22

**Console output**  

**Your system (please complete the following information)**
 - Device: Macbook Pro 
 - OS: macOS 12.5.1
 - Browser: Firefox 112.01 (and Vivaldi 5.7.2921.63 (chromium-based))

**Additional context**  

https://user-images.githubusercontent.com/247940/234294245-99618fb1-e015-4315-b07c-e415b3e4412f.mp4

**Comment by afbora** [comment]
I can't reproduce the issue on Chrome-Firefox & WinOS & Kirby 3.9.4. Do you have any plugins?

**Comment by mourique** [comment]
yes! sorry, i do have two plugins installed:

- distantnative/retour 4.4.2
- fabianmichael/meta 0.4.0-beta

i will try to reproduce it myself with a blank plainkit install and check back here!

edit: i could reproduce the behaviour on a completely new and otherwise untouched plainkit installation. It does not seem to be connected to the use of plugins.

**Comment by texnixe** [comment]
Just leaving it here for reference, because we had this issue (or at least almost the same) reported before: https://github.com/getkirby/kirby/issues/4181

**Comment by mourique** [comment]
this issue by medienbaecker in the fabianmichael/kirby-markdown-field repo also seems to be related: https://github.com/fabianmichael/kirby-markdown-field/issues/164

**Comment by afbora** [comment]
@mourique Have you looked at the issue https://github.com/getkirby/kirby/issues/4181 @texnixe mentioned?

**Comment by texnixe** [comment]
I also tested this again in my Valet environment with the normal Starterkit, which has a writer field in album.yml, and cannot reproduce the issue, not even when the content is not saved yet.

**Comment by mourique** [comment]
@afbora yes i looked at the issue and followed your linked article (https://getkirby.com/docs/guide/troubleshooting/panel#opcache-server-side-caching-in-general) but it didnt have any effect in my local valet installation, i also tried disabling opcache via htaccess locally but it did not work.

BUT: Today i uploaded the plainkit install to my server (cyon.ch) and disabled opcache there via htaccess and the bug is gone. so it does seem to be related to opcache.

it is still weird because i have a lot of kirby installs locally and they all work, except for these newest ones. 

i will try to do more research.

**edit:** disabling opcache on the clients host (domainfactory) did not have the desired effect. So it is still something else? it seems to be related to a very specific server config, but i can not pinpoint it yet.

**second edit:** to make matters more complicated all three environments use different servers:

- local: valet -> nginx (disabling opcache not working)
- my own host: cyon -> lightspeed (disabling opcache working)
- clients host: domainfactory -> apache (disabling opcache not working)

**Comment by tobimori** [comment]
I had this issue a while ago too but I can't replicate it anymore. It's really weird.
