### ISSUE TITLE
Plugin asset CSS files miss timestamp in URL

### ISSUE THREAD

**Issue by stairjoke** [k-next/kirby#5164]
## Description
According to [Plugin Basics > Timestamps](https://getkirby.com/docs/guide/plugins/plugin-basics#plugin-assets__timestamps) any asset included inside a plugin folder should automatically receive a timestamp when cached in the media folder. This is not happening, and it seems this has not worked for several years:

- Case 1: https://forum.getkirby.com/t/my-plugin-assets-are-missing-the-timestamp-in-the-file-name/28477
- Case 2: https://forum.getkirby.com/t/plugin-asset-url-helper/18209

**Expected behavior**  
Referring to an asset included inside a plugin should return a URL that points to a cached file which has a URL such as this:
`/media/plugins/superwoman/superplugin/myCss.1520265293.css`

**Actual Behavior**
The actual result of referring to an asset inside  a plugin folder is:
`/media/plugins/superwoman/superplugin/myCss.css`

**Screenshots**  
<img width="675" alt="CleanShot 2023-04-30 at 11 35 23@2x" src="https://user-images.githubusercontent.com/991380/235346210-2e1d52c1-4746-4240-a181-e8cbe4a7b1e5.png">

<img width="665" alt="CleanShot 2023-04-30 at 11 34 45@2x" src="https://user-images.githubusercontent.com/991380/235346163-b03eefc5-d9b5-4e20-9316-d2b704bf693d.png">

## To reproduce
1. Go to create a plugin and add a CSS file inside the asset folder of your plugin
2. Include the CSS file in a page template using `css('PATH')`
3. Open a page using this template
4. Look for the `<link>`-tag in the HTML

## Your setup
Kirby v3.9.1

**Console output**  
-

**Your system (please complete the following information)**
- PHP: 8.1.17

**Additional context**  
-

**Comment by rasteiner** [comment]
related: https://github.com/getkirby/getkirby.com/issues/148

**Comment by distantnative** [comment]
@lukasbestle I think even with our changes https://github.com/getkirby/kirby/issues/5247 this remains too complicated for developers. I think we need to rewrite it once more to allow something like

```php
$plugin->asset('foo.js')->url();
// -> URL to media folder with timestamp included (based on modified)

// maybe also more methods
$plugin->asset('foo.js')->exists();
$plugin->asset('foo.js')->publish();
$plugin->asset('foo.js')->unpublish();
$plugin->asset('foo.js')->path();
$plugin->asset('foo.js')->root();
```

Unfortunately, I think `Filesystem\Asset` is currently very much tied to the `assets` folder. Ideally, we'd make that class more flexible as well and reuse here.

**Comment by lukasbestle** [comment]
@distantnative I like that syntax. However I wouldn't add `->exists()`, IMO the `asset()` method should still return `null` if the asset does not exist. Otherwise it would be really hard to find bugs because the asset URL would still be generated and one would have to search for reasons why the URL doesn't work. If it returns `null`, there's immediately an error.
