### ISSUE TITLE
Database::lastError() throws exception when there is no error.

### ISSUE THREAD

**Issue by Jayshua** [k-next/kirby#5165]
## Description
The lastError method on the Database class is typed to return a Throwable, but if there was no error from the database it tries to return null triggering a PHP TypeError.

**Expected behavior**  
Calling lastError when there was no error should return null. Or maybe some other way to check if there was an error?

## To reproduce
```php
$db = Db::connect();
$db->query('select 1');
if ($db->lastError()) {
  echo 'Error';
} else {
  echo 'No Error';
}
```

## Your setup
**Kirby Version**: 3.9.4
**MariaDB Version**: 10.19

**Comment by bastianallgeier** [comment]
This will be fixed in 3.9.5
