### ISSUE TITLE
KirbyText might escape KirbyTag markup

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#5167]
## Description
When rendering custom KirbyTags with KirbyText, e. g. `$page->text()->kirbytext()`, the KirbyTag's markup will be escaped if it contains a break after the HTML tag name. This might happen easily if you are generating the KirbyTag result with a snippet call involving either conditions or calling helper methods:

```php
Kirby::plugin('example-kirbytag', [
    'tags' => [
        'figure' => [
            'attr' => ['class'],
            'html' => function ($tag) {
                return snippet(
                    'figure',
                    [
                        'file' => $file,
                        'class' => $tag->class
                    ],
                    true
                );
            }
        ]
    ]
]);
```
`/site/snippets/figure.php`:

```php
<figure 
    <?= attr([
        'class' => $class
    ]) ?>
>
    <?= snippet('image', ['file' => $file]) ?>
</figure>
```

This example is simplified for illustration purposes.

**Expected behavior**  

KirbyTags should not fail.

## To reproduce
Create a KirbyTag as above that generates the following markup:

✅ This works, the HTML is passed forward:

```html
<figure class="my-custom-class"><img src="image.jpg" /></figure>
```

✅ This will work, too:

```html
<figure class="my-custom-class"
>
    <img src="image.jpg" />
</figure>
```

❌ This won't work and the HTML will be escaped:

```html
<figure 
    class="my-custom-class"
>
    <img src="image.jpg" />
</figure>
```

## Your setup
**Kirby Version**  
Seems to be an issue in all Kirby versions at least down to 3.5.

## Possible solution

This is certainly an issue with the Parsedown lexer not accepting a line break which might be solved in the future or not. This is very hard to debug though from a Kirby development perspective. You just see your markup broken and don't understand why. I see two things Kirby can do:

1. Add a note to the KirbyTag documentation to make sure people know about this issue.
2. Add a helper to normalize the KirbyTag output.

Two methods we have used successfully for normalization:

```php
function normalizeDom($html = null)
{
    if (empty($html)) {
        return null;
    }

    $internal = libxml_use_internal_errors(true);

    $document = new DomDocument();
    $document->loadHTML('<?xml encoding="UTF-8">' . $html);
    $body = $document->getElementsByTagName('body')->item(0);

    libxml_clear_errors();
    libxml_use_internal_errors($internal);

    $content = '';
    foreach ($body->childNodes as $child) {
        $content .= $document->saveHTML($child);
    }

    return $content;
}
```

```php
function normalizeWhitespace($html = null)
{
    if (empty($html)) {
        return null;
    }

    $search = [
        // Remove whitespaces after tags
        '/\>[^\S ]+/s',

        // Remove whitespaces before tags
        '/[^\S ]+\</s',

        // Remove multiple whitespace sequences
        '/(\s)+/s',

        // Removes comments
        '/<!--(.|\s)*?-->/'
    ];
    $replace = ['>', '<', '\\1'];

    return trim(preg_replace($search, $replace, $html));
}
```

This could be an addition to the `Html` class or an additional attribute of the `snippet` helper that invoces normalization.

**Comment by nilshoerrmann** [comment]
As I just stumbled into this again: `normalizeDom` works well for snippets returning block content, while `normalizeWhitespace` helps with inline content (no wrapping element).

So we've settled with a combination now which will make sure that inline `br` tags will also be handled correctly:

```php
function normalizeBlock($html)
{
    if (empty($html)) {
        return null;
    }

    $internal = libxml_use_internal_errors(true);

    $document = new DomDocument();
    $document->preserveWhiteSpace = false;
    $document->formatOutput = false;
    $document->loadHTML('<?xml encoding="UTF-8">' . $html);
    $document->normalizeDocument();
    $body = $document->getElementsByTagName('body')->item(0);

    libxml_clear_errors();
    libxml_use_internal_errors($internal);

    $content = '';
    foreach ($body->childNodes as $child) {
        $content .= normalizeInline($document->saveHTML($child));
    }

    return trim($content);
}

function normalizeInline($html = null)
{
    if (empty($html)) {
        return null;
    }

    $search = [
        // Remove whitespaces after tags
        '/\>[^\S ]+/s',

        // Remove whitespaces before tags
        '/[^\S ]+\</s',

        // Remove multiple whitespace sequences
        '/(\s)+/s',

        // Removes comments
        '/<!--(.|\s)*?-->/'
    ];
    $replace = ['>', '<', '\\1'];

    return trim(preg_replace($search, $replace, $html));
}
```

**Comment by lukasbestle** [comment]
I've opted to document this in the reference. I think it's useful for plugin devs to know this limitation.

In the long term we still plan to replace Parsedown as it is unmaintained, but we haven't found a suitable replacement and migration path yet.

Cleaning the whitespace could indeed be a solution, but I'm afraid it would have quite a noticeable performance impact. Given that such whitespace can often be avoided in the first place, I think it's not worth it in the core.
