### ISSUE TITLE
[v4] Translate function doesn't work with field values anymore

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5185]
## Description
I use the following code to get a translated label for a value from a site field, which worked fine in Kirby 3:

https://github.com/tobimori/kirby-seo/blob/main/blueprints/fields/og-group.yml#L35
```yaml
    placeholder: "{{ t('default-select') }} {{ t(site.twitterCardType) }}"
```

Yet, with Kirby 4, I'm missing the output for the translated card type:
<img width="404" alt="CleanShot 2023-05-25 at 12 06 11@2x" src="https://github.com/getkirby/kirby/assets/29142128/15bf45fb-11cb-4ed8-bf3a-1c6b31bcb10c">

When removing the translation helpers, I can see that the data can be accessed correctly.
<img width="384" alt="CleanShot 2023-05-25 at 12 06 38@2x" src="https://github.com/getkirby/kirby/assets/29142128/05b2ed83-2c9c-485e-971b-4f15163725e8">

It works correctly when appending `.value` to `site.twitterCardType`:
```yaml
    placeholder: "{{ t('default-select') }} {{ t(site.twitterCardType.value) }}"
```

<img width="377" alt="CleanShot 2023-05-25 at 12 07 53@2x" src="https://github.com/getkirby/kirby/assets/29142128/cafc1f86-3b0b-4308-a3df-5de791c5606e">

## To reproduce
Install my SEO plugin with Kirby 4.0, or test using the code snippets above.

## Your setup
**Kirby Version**  4.0-alpha.1

**Comment by distantnative** [comment]
@tobimori if you have any quick way to double check that this isn't already broken in3.9.4, would be helpful. If not, don't worry - just won't get myself on a laptop that soon to do myself and trying to debug via GitHub on my phone 🤣

**Comment by afbora** [comment]
@distantnative I've tested on 3.9.4 and works great.

**Comment by tobimori** [comment]
Yep, works on the sites where this plugin is running with v3.9.4.

**Comment by distantnative** [comment]
Does ist work for you when removing `declare(strict_types = 1);` from `src/Query/Query.php`?

**Comment by distantnative** [comment]
That would be my current hunch - that previously the `Field` object implicitly got casted to its value and due to this line Kirby now would want you to add `.value` (which would not be great, we would look into easing this - just trying to find the reason for the bug first).

**Comment by afbora** [comment]
I can't see `declare(strict_types = 1);` in any files.

**Comment by afbora** [comment]
Also not working with `.value` (but works in 3.9.x)

**Comment by distantnative** [comment]
@afbora https://github.com/getkirby/kirby/blob/v4/main/src/Query/Query.php#L3 - and @tobimori  described that it's working with `.value`

**Comment by afbora** [comment]
@distantnative Sorry, I tested on `v4/develop` and it hasn't that line.

**Comment by afbora** [comment]
But `v4/main` still doesn't work for me. With removing `strict_types` and `.value`

````
placeholder: "{{ t('foo') }} {{ t(model.text.value) }}"
````

**Comment by tobimori** [comment]
It doesn't seem to fix it. `.value` still works.

**Comment by distantnative** [comment]
Observation: works on `v4/develop` but not `v4/main`

**Comment by distantnative** [comment]
Works when removing strict mode from `src/Query/Segment.php`
