### ISSUE TITLE
4.0 Plugins compatibility

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5187]
Please let us know which plugins do not work in Kirby 4.0 or need help with 4.0 compatibility.

## Broken

- [ ] https://github.com/fabianmichael/kirby-markdown-field
  Issue: https://github.com/fabianmichael/kirby-markdown-field/issues/174
- [ ] https://github.com/chrisbeluga/kirby-navigation
  Issue: https://github.com/chrisbeluga/kirby-navigation/issues/40
- [ ] https://github.com/diesdasdigital/kirby-meta-knight
  Issue: https://github.com/diesdasdigital/kirby-meta-knight/issues/76
- [ ] https://github.com/Daandelange/kirby3-simplestats
  Issue: https://github.com/Daandelange/kirby3-simplestats/issues/40
- [ ] https://github.com/Adspectus/k3-feedreader
  Issue: https://github.com/Adspectus/k3-feedreader/issues/1
- [ ] https://github.com/rasteiner/k3-whenquery
  Issue: https://github.com/rasteiner/k3-whenquery/issues/20
- [ ] https://github.com/benediktengel/google-calendar-plugin
  There are another K3 issues
- [ ] https://github.com/bnomei/kirby3-utm
  Issue: https://github.com/bnomei/kirby3-utm/issues/3
- [ ] https://github.com/bvdputte/kirby-vpkit
  Issue: https://github.com/bvdputte/kirby-vpkit/issues/1
  PR: https://github.com/bvdputte/kirby-vpkit/pull/2
- [ ] https://github.com/dgtl-one/kirby-chunky
  Issue: https://github.com/dgtl-one/kirby-chunky/issues/9
- [ ] https://github.com/fabianmichael/kirby-meta
  Issues: 
   - https://github.com/fabianmichael/kirby-meta/issues/60
   - https://github.com/fabianmichael/kirby-meta/issues/67
- [ ] https://github.com/felixhaeberle/kirby3-webp/issues/15
  Issues:
  - https://github.com/felixhaeberle/kirby3-webp/issues/14
  - https://github.com/felixhaeberle/kirby3-webp/issues/15
- [ ] https://github.com/fendinger/kirby3-consent-gate
  Issue: https://github.com/fendinger/kirby3-consent-gate/issues/4
- [ ] https://github.com/flokosiol/kirby-focus
  Issue: https://github.com/flokosiol/kirby-focus/issues/75
- [ ] https://github.com/gearsdigital/enhanced-toolbar-link-dialog
  Issue: https://github.com/gearsdigital/enhanced-toolbar-link-dialog/issues/96
- [ ] https://github.com/gearsdigital/localizer-for-kirby
  Issue: https://github.com/gearsdigital/localizer-for-kirby/issues/8
- [ ] https://github.com/gearsdigital/reporter-for-kirby
  Issue: https://github.com/gearsdigital/reporter-for-kirby/issues/62
- [ ] https://github.com/hananils/kirby-choices
  Issue: https://github.com/hananils/kirby-choices/issues/3
- [ ] https://github.com/hananils/kirby-tracker
  Issue: https://github.com/hananils/kirby-tracker/issues/3
  PR: https://github.com/hananils/kirby-tracker/pull/4
- [ ] https://github.com/hananils/kirby-typographer
  Issue: https://github.com/hananils/kirby-typographer/issues/15
- [ ] https://github.com/hananils/kirby-xslt
  Issue: https://github.com/hananils/kirby-xslt/issues/10
- [ ] https://github.com/HashandSalt/carver
  Issue: https://github.com/HashandSalt/carver/issues/2
- [ ] https://github.com/HashandSalt/Kirby3-Gilmour
  Issue: https://github.com/HashandSalt/Kirby3-Gilmour/issues/2
- [ ] https://github.com/HashandSalt/kirby3-schema
  Issue: https://github.com/HashandSalt/kirby3-schema/issues/6
- [ ] https://github.com/jongacnik/kirby-fields-block
  Issue: https://github.com/jongacnik/kirby-fields-block/issues/20
- [ ] https://github.com/kerli81/kirby-securedpages
  Issue: https://github.com/kerli81/kirby-securedpages/issues/17
- [ ] https://github.com/michnhokn/kirby3-logger
  There are another K3 issues
- [ ] https://github.com/moritzebeling/kirby-panel-button
  Issue: https://github.com/moritzebeling/kirby-panel-button/issues/3
  PR: https://github.com/moritzebeling/kirby-panel-button/pull/4
- [ ] https://github.com/mullema/k3-image-clip
  Issue: https://github.com/mullema/k3-image-clip/issues/33
- [ ] https://github.com/mullema/k3-panel-view-extended
  Issue: https://github.com/mullema/k3-panel-view-extended/issues/19
- [ ] https://github.com/mzur/kirby-calendar-plugin
  Issue: https://github.com/mzur/kirby-calendar-plugin/issues/34
- [ ] https://github.com/OblikStudio/kirby-link-field
  Issue: https://github.com/OblikStudio/kirby-link-field/issues/82
- [ ] https://github.com/pju-/kirby-webhook-field
  Issue: https://github.com/pju-/kirby-webhook-field/issues/29
- [ ] https://github.com/ragi96/table-field
  Issue: https://github.com/ragi96/table-field/issues/13
- [ ] https://github.com/robinscholz/better-rest
  Issue: https://github.com/robinscholz/better-rest/issues/32
- [ ] https://github.com/steirico/kirby-plugin-custom-add-fields
  Issue: https://github.com/steirico/kirby-plugin-custom-add-fields/issues/68
- [ ] https://github.com/steirico/kirby-plugin-image-crop-field
  Issue: https://github.com/steirico/kirby-plugin-image-crop-field/issues/46
- [ ] https://github.com/sylvainjule/kirby-multilist
  Issue: https://github.com/sylvainjule/kirby-multilist/issues/13
  PR: https://github.com/sylvainjule/kirby-multilist/pull/12
- [ ] https://github.com/sylvainjule/kirby-color-palette
  Issue: https://github.com/sylvainjule/kirby-color-palette/issues/31
- [ ] https://github.com/sylvainjule/kirby-pagetable
  Issue: https://github.com/sylvainjule/kirby-pagetable/issues/90
- [ ] https://github.com/sylvainjule/kirby-previews
  Issue: https://github.com/sylvainjule/kirby-previews/issues/7
- [ ] https://github.com/yoanmalie/kirbytextWrap
  Issue: https://github.com/yoanmalie/kirbytextWrap/issues/2
- [ ] https://github.com/genxbe/kirby3-instagram
  Issue: https://github.com/genxbe/kirby3-instagram/issues/10
- [ ] https://getkirby.com/plugins/owebstudio/tinymce
  Issue: https://github.com/owebstudio/kirby-tinymce-field/issues/4
- [ ] https://getkirby.com/plugins/owebstudio/tui-image-editor
  Issue: https://github.com/owebstudio/kirby-tui-image-editor/issues/2

## OK

- [x] https://github.com/rasteiner/k3-pagesdisplay-section
- [x] https://github.com/getkirby/kql
- [x] https://github.com/getkirby/cli
  Issue: https://github.com/getkirby/cli/issues/52
- [x] https://github.com/adamkiss/kirby-goat-counter
- [x] https://github.com/adamkiss/kirby-icons-heroicons
- [x] https://github.com/Adspectus/k3-date-extended
- [x] https://github.com/afbora/kirby-minify-html
- [x] https://github.com/afbora/kirby-loader
- [x] https://github.com/afbora/kirby-template-hooks
- [x] https://github.com/anselmh/kirby-uniform-turnstile
- [x] https://github.com/getkirby/staticache
  Issue: https://github.com/getkirby/staticache/issues/24
- [x] https://github.com/tristantbg/kirby-shopify
  Issue: https://github.com/tristantbg/kirby-shopify/issues/20
- [x] https://github.com/tristantbg/kirby-stripe
- [x] https://github.com/arnoson/kirby-template-sugar
- [x] https://github.com/arnoson/kirby-vite 
- [x] https://github.com/beebmx/kirby-env
- [x] https://github.com/beebmx/kirby-db
- [x] https://github.com/bnomei/autoloader-for-kirby
- [x] https://github.com/bnomei/kirby-blueprints
- [x] https://github.com/bnomei/kirby3-boost
- [x] https://github.com/bnomei/kirby3-cloudconvert
- [x] https://github.com/bnomei/kirby3-collect
- [x] https://github.com/bnomei/kirby3-security-headers
- [x] https://github.com/bnomei/kirby3-dotenv
- [x] https://github.com/bnomei/kirby3-feed
- [x] https://github.com/bnomei/kirby3-field-ecco
- [x] https://github.com/bnomei/kirby3-fingerprint
- [x] https://github.com/bnomei/kirby3-fontselector
- [x] https://github.com/bnomei/kirby3-handlebars
- [x] https://github.com/bnomei/kirby3-htmlhead
- [x] https://github.com/bnomei/kirby3-htmlpurifier
- [x] https://github.com/bnomei/kirby3-thumb-imageoptim
- [x] https://github.com/bnomei/kirby3-janitor
- [x] https://github.com/bnomei/kirby3-lapse
- [x] https://github.com/bnomei/kirby3-mailjet
- [x] https://github.com/bnomei/kirby3-mobile-detect
- [x] https://github.com/bnomei/kirby3-monolog
- [x] https://github.com/bnomei/kirby3-mysql-cachedriver
- [x] https://github.com/bnomei/kirby3-php-cachedriver
- [x] https://github.com/bnomei/kirby3-plopfile
- [x] https://github.com/bnomei/kirby3-posthog
- [x] https://github.com/bnomei/kirby3-postmark
- [x] https://github.com/bnomei/kirby3-random
- [x] https://github.com/bnomei/kirby3-qrcode
- [x] https://github.com/bnomei/kirby3-recently-modified 
- [x] https://github.com/bnomei/kirby3-redirects
- [x] https://github.com/bnomei/kirby3-redis-cachedriver
- [x] https://github.com/bnomei/kirby3-robots-txt
- [x] https://github.com/bnomei/kirby3-seobility
- [x] https://github.com/bnomei/kirby3-sqlite-cachedriver
- [x] https://github.com/bnomei/kirby3-stopwatch
- [x] https://github.com/bnomei/kirby3-storybook
- [x] https://github.com/bvdputte/kirby-autopublish
- [x] https://github.com/bvdputte/kirby-bettersearch
- [x] https://github.com/bvdputte/kirby-fingerprint
- [x] https://github.com/bvdputte/kirby-log
- [x] https://github.com/bvdputte/kirby-queue
- [x] https://github.com/chrfickinger/kirby-jsonld
- [x] https://github.com/DanielRivers/nuxt-kirby-kql
- [x] https://github.com/diesdasdigital/kirby-3-imgix
- [x] https://github.com/distantnative/retour-for-kirby
- [x] https://github.com/Diverently/laravel-mix-kirby
- [x] https://github.com/errnesto/kirby-plugin-webhooks
- [x] https://bitbucket.org/vitamin2/retrotree
- [x] https://github.com/floriankarsten/kirby3-vipsthumbnail
- [x] https://github.com/flupe/kirby-cas
- [x] https://github.com/genxbe/k3-fragments
- [x] https://github.com/genxbe/kirby3-instagram
- [x] https://github.com/genxbe/kirby3-ray
- [x] https://github.com/hananils/kirby-colors
- [x] https://github.com/hananils/kirby-date-methods
- [x] https://github.com/hananils/kirby-list-methods
- [x] https://github.com/hananils/kirby-methods-folder
- [x] https://github.com/hananils/kirby-snippetwhen-helper
- [x] https://github.com/hananils/kirby-structure-textarea-preview
- [x] https://github.com/hananils/kirby-tiles
- [x] https://github.com/hananils/kirby-tree-methods
- [x] https://github.com/hananils/kirby-type-methods
- [x] https://github.com/HashandSalt/kirby3-abt
- [x] https://github.com/HashandSalt/chopper
- [x] https://github.com/HashandSalt/kirby3-forms
- [x] https://github.com/HashandSalt/kirby-recurr
- [x] https://github.com/HashandSalt/kirby3-snipcart
- [x] https://github.com/HashandSalt/kirby3-video
- [x] https://github.com/HashandSalt/kirby3-yasumi
- [x] https://github.com/isaactopo/xmlsitemap
- [x] https://github.com/jbeyerstedt/kirby-kirbytag-download
- [x] https://github.com/jbeyerstedt/kirby-kirbytag-quote
- [x] https://github.com/johannschopplich/kirby-algolia-docsearch
- [x] https://github.com/johannschopplich/kirby-blurry-placeholder
- [x] https://github.com/johannschopplich/kirby-hashed-assets
- [x] https://github.com/johannschopplich/kirby-headless
- [x] https://github.com/johannschopplich/kirby-highlighter
- [x] https://github.com/johannschopplich/kirbylog
- [x] https://github.com/johannschopplich/kirby-locked-pages
- [x] https://github.com/johannschopplich/kirby-punctuation-section
- [x] https://github.com/junohamburg/kirby-visual-block-selector
- [x] https://github.com/kx550/kirby3-arena
- [x] https://github.com/kx550/kirby3-fathom
- [x] https://github.com/lukasleitsch/kirby-blade
- [x] https://github.com/lukaskleinschmidt/kirby-laravel-vite
- [x] https://github.com/lukaskleinschmidt/kirby-resolve
- [x] https://github.com/lukaskleinschmidt/kirby-snippet-controller
- [x] https://github.com/lukaskleinschmidt/kirby-terminal
- [x] https://github.com/lukaskleinschmidt/kirby-types
- [x] https://github.com/mauricerenck/indieConnector
- [x] https://github.com/mauricerenck/komments
- [x] https://github.com/mauricerenck/kirby-podcaster
- [x] https://github.com/mauricerenck/rate-page
- [x] https://github.com/medienbaecker/kirby-autofavicon
- [x] https://github.com/medienbaecker/kirby-autoresize
- [x] https://github.com/michnhokn/kirby3-cookie-banner
- [x] https://github.com/youngcut/kirby-components
- [x] https://github.com/youngcut/kirby-grid-block
- [x] https://github.com/youngcut/kirby-inherit
- [x] https://github.com/youngcut/kirby-map
- [x] https://github.com/moritzebeling/kirby-favicon
- [x] https://github.com/moritzebeling/kirby-headless-image-transformations
- [x] https://github.com/moritzebeling/kirby-maintenance
- [x] https://github.com/mzur/kirby-form
- [x] https://github.com/mzur/kirby-uniform
  Issue: https://github.com/mzur/kirby-uniform/issues/252
- [x] https://github.com/nerdcel/kirby3-responsive-images
- [x] https://github.com/OblikStudio/kirby-git
- [x] https://github.com/OblikStudio/kirby-memsource
- [x] https://github.com/OblikStudio/kirby-plurals
- [x] https://github.com/olach/kirby3-relationship
- [x] https://github.com/pgfactory/KirbyCMS-MarkdownPlus
- [x] https://github.com/presprog/kirby-route-attributes
- [x] https://github.com/rowdyrabouw/kirby3-plausible
- [x] https://github.com/schnti/kirby3-cachebuster
- [x] https://github.com/schnti/kirby3-cookie
- [x] https://github.com/sylvainjule/kirby-bouncer
- [x] https://github.com/sylvainjule/kirby-footnotes
- [x] https://github.com/sylvainjule/kirby-subtitler
- [x] https://github.com/thathoff/kirby-clear-cloudflare-cache
- [x] https://github.com/tobimori/kirby-blurhash
- [x] https://github.com/tobimori/kirby-magick-extended
- [x] https://github.com/tobimori/kirby-tailwind-merge
- [x] https://github.com/tobimori/kirby-thumbhash
- [x] https://github.com/wearejust/kirby-meta-tags
- [x] https://github.com/wearejust/kirby-twig
- [x] https://github.com/Werbschaft/kirby-upload-extended
- [x] https://github.com/wagnerwagner/merx
- [x] https://github.com/zephir/kirby-contentsync
- [x] https://github.com/zephir/kirby-cookieconsent
- [x] https://getkirby.com/plugins/owebstudio/accordion-field
- [x] https://getkirby.com/plugins/owebstudio/clear-cache
- [x] https://getkirby.com/plugins/owebstudio/detect-adblock
- [x] https://getkirby.com/plugins/owebstudio/google-translate
- [x] https://getkirby.com/plugins/owebstudio/instagram-feed
- [x] https://getkirby.com/plugins/owebstudio/merx-mercadopago
- [x] https://getkirby.com/plugins/owebstudio/merx-mollie
- [x] https://getkirby.com/plugins/owebstudio/move-pages
- [x] https://getkirby.com/plugins/owebstudio/plates
- [x] https://getkirby.com/plugins/owebstudio/pwa
- [x] https://getkirby.com/plugins/owebstudio/template-stacks
- [x] https://getkirby.com/plugins/owebstudio/whatsapp-button
- [x] https://github.com/d4l-data4life/kirby3-static-site-generator
  Issue: https://github.com/d4l-data4life/kirby3-static-site-generator/issues/86
- [x] https://github.com/mauricerenck/pexels-image-field
  Issue: https://github.com/mauricerenck/pexels-image-field/issues/1
- [x] https://github.com/floriankarsten/kirby-plausible
  Issue: https://github.com/floriankarsten/kirby-plausible/issues/8
- [x] https://github.com/junohamburg/kirby-block-preview-fields
  Issue: https://github.com/junohamburg/kirby-block-preview-fields/issues/4
- [x] https://github.com/junohamburg/kirby-reload-on-save
  Issue: https://github.com/junohamburg/kirby-reload-on-save/issues/1
- [x] https://github.com/splorp/kirby-paperback-export
- [x] https://github.com/youngcut/kirby-column-blocks
  Issue: https://github.com/youngcut/kirby-column-blocks/issues/7
- [x] https://github.com/youngcut/kirby-form-block-suite
  Issue: https://github.com/youngcut/kirby-form-block-suite/issues/26
- [x] https://github.com/texnixe/kirby3-similar
  Issue: https://github.com/texnixe/kirby3-similar/issues/5
- [x] https://github.com/tobimori/kirby-icon-field
  Issue: https://github.com/tobimori/kirby-icon-field/issues/11
- [x] https://github.com/Treast/kirby-debugbar
  Issue: https://github.com/Treast/kirby-debugbar/issues/7
- [x] https://github.com/schnti/kirby3-video
  Issue: https://github.com/schnti/kirby3-video/issues/19
  PR: https://github.com/schnti/kirby3-video/pull/20
- [x] https://github.com/tobimori/kirby-seo
  Issue: https://github.com/tobimori/kirby-seo/issues/40
- [x] https://github.com/HashandSalt/kirby3-seo
  Issue: https://github.com/HashandSalt/kirby3-seo/issues/6
- [x] https://github.com/lukasbestle/kirby-roomle
  Issue: https://github.com/lukasbestle/kirby-roomle/issues/2
- [x] https://github.com/thathoff/kirby-oauth/issues/33
  Issue: https://github.com/thathoff/kirby-oauth
  PR: https://github.com/thathoff/kirby-oauth/pull/32
- [x] https://github.com/thathoff/kirby-sentry
  Issue: https://github.com/thathoff/kirby-sentry/issues/13
- [x] https://github.com/lukasbestle/kirby-downloads
  Issue: https://github.com/lukasbestle/kirby-downloads/issues/2
- [x] https://github.com/lukasbestle/kirby-versions
  Issue: https://github.com/lukasbestle/kirby-versions/issues/16
- [x] https://github.com/medienbaecker/kirby-modules
  Issue: https://github.com/medienbaecker/kirby-modules/issues/39
- [x] https://github.com/sylvainjule/kirby-annotator
  Issue: https://github.com/sylvainjule/kirby-annotator/issues/23
- [x] https://github.com/sylvainjule/kirby-embed
  Issue: https://github.com/sylvainjule/kirby-embed/issues/20
- [x] https://github.com/sylvainjule/kirby-locator
  Issue : https://github.com/sylvainjule/kirby-locator/issues/57
- [x] https://github.com/sylvainjule/kirby-colorextractor
  Issue: https://github.com/sylvainjule/kirby-colorextractor/issues/18
- [x] https://github.com/bnomei/kirby3-pageviewcounter
  Issue: https://github.com/bnomei/kirby3-pageviewcounter/issues/6
- [x] https://github.com/sylvainjule/kirby-matomo
  Issue: https://github.com/sylvainjule/kirby-matomo/issues/45
  PR: https://github.com/sylvainjule/kirby-matomo/pull/47
- [x] https://github.com/sylvainjule/kirby-imageboxes
  Issue: https://github.com/sylvainjule/kirby-imageboxes/issues/9
- [x] https://github.com/sylvainjule/kirby-imageradio
  Issue: https://github.com/sylvainjule/kirby-imageradio/issues/18

## Unknown

- [ ] https://github.com/sylvainjule/kirby-autofocus
- [ ] https://github.com/thathoff/kirby-git-content
- [ ] https://github.com/thathoff/kirby-migrations
- [ ] https://getkirby.com/plugins/microman/theme-picker

## Archived

- [x] https://github.com/bnomei/kirby3-htmlpurifier
- [x] https://github.com/datamints/kirby-plugin_ldap
- [x] https://github.com/HashandSalt/kirby3-webp
- [x] https://github.com/Liftric/kirby-cloudfront-invalidations
- [x] https://github.com/mullema/k3-date-format
- [x] https://github.com/omz13/kirby3-badges
- [x] https://github.com/omz13/kirby3-byline
- [x] https://github.com/omz13/kirby3-feeds
- [x] https://github.com/omz13/kirby3-honehome
- [x] https://github.com/omz13/kirby3-suncyclepages
- [x] https://github.com/omz13/kirby3-wellknown
- [x] https://github.com/omz13/kirby3-whatever
- [x] https://github.com/omz13/kirby3-xmlsitemap
- [x] https://github.com/PaulMorel/kirby3-fathom-analytics
- [x] https://github.com/texnixe/kirby3-codepen
- [x] https://github.com/texnixe/k3-filesdisplay-section
- [x] https://github.com/texnixe/kirby3-related
- [x] https://github.com/texnixe/kirby3-spreadsheet
- [x] https://github.com/sebastiangreger/kirby3-commentions
  Issue: https://github.com/sebastiangreger/kirby3-commentions/issues/155
- [x] https://github.com/OblikStudio/kirby-entity-field
  Issue: https://github.com/OblikStudio/kirby-entity-field/issues/21

**Comment by tobimori** [comment]
https://github.com/getkirby/kirby/issues/5182 
https://github.com/getkirby/kirby/issues/5183
https://github.com/getkirby/kirby/issues/5185

**Comment by rasteiner** [comment]
https://github.com/rasteiner/k3-whenquery/issues/19

**Comment by bnomei** [comment]
https://github.com/getkirby/staticache can not be installed `composer require` with k4 since it requires k3.8+

**Comment by medienbaecker** [comment]
[kirby-markdown-field](https://github.com/fabianmichael/kirby-markdown-field) has issues with the removed `k-toolbar-buttons` wrapper and displays the buttons vertically. I [created a PR](https://github.com/fabianmichael/kirby-markdown-field/pull/172) but as I mentioned in the comments I'm not sure if this is something that will change in the core.

**Comment by tobimori** [comment]
https://github.com/getkirby/kirby/issues/5263

**Comment by mrflix** [comment]
https://github.com/sylvainjule/kirby-multilist/pull/12

**Comment by Thiousi** [comment]
https://github.com/tristantbg/kirby-shopify/issues/20
https://github.com/diesdasdigital/kirby-meta-knight/issues/76

**Comment by Thiousi** [comment]
> [tristantbg/kirby-shopify#20](https://github.com/tristantbg/kirby-shopify/issues/20) [diesdasdigital/kirby-meta-knight#76](https://github.com/diesdasdigital/kirby-meta-knight/issues/76)

PR submitted for kirby-shopfiy. Waiting for review to merge. Tested the changes with K3 without issues.
Thanks @afbora for the support.

PR merged. OK for Kirby shopify

**Comment by JerikoOne** [comment]
https://github.com/chrisbeluga/kirby-navigation is broken

**Comment by distantnative** [comment]
@JerikoOne Could you please post an issue in the plugin's repo so we can keep track of it?

**Comment by JerikoOne** [comment]
@distantnative sure thing: https://github.com/chrisbeluga/kirby-navigation/issues/40

**Comment by animaux** [comment]
- [x] [lukaskleinschmidt/kirby-snippet-controller](https://github.com/lukaskleinschmidt/kirby-snippet-controller) ([according to the author](https://github.com/lukaskleinschmidt/kirby-snippet-controller/issues/2#issuecomment-1775216854))

**Comment by bnomei** [comment]
kirby cli
https://github.com/getkirby/cli/issues/52

**Comment by flokosiol** [comment]
As you all know, [Kirby Focus](https://github.com/flokosiol/kirby-focus) will be part of the core in v4. 

@FynnZW documented a way how to migrate the focus values by doing a regex search and replace:
https://github.com/flokosiol/kirby-focus/issues/75

I think Focus can be seen as ready for v4 😉

**Comment by gbdesign2023** [comment]
https://github.com/ragi96/table-field

The buttons are out of position. A CSS fix may be sufficient here.
https://github.com/ragi96/table-field/issues/13

**Comment by mrflix** [comment]
https://github.com/sylvainjule/kirby-imageradio/issues/18

Broken because of the `Kirby\Form` → `Kirby\Option` refactor.

**Comment by animaux** [comment]
https://github.com/fabianmichael/kirby-markdown-field
Issue: https://github.com/fabianmichael/kirby-markdown-field/issues/174

Seems to be running fine in [version 3.0.0-alpha2](https://github.com/fabianmichael/kirby-markdown-field/releases/tag/3.0.0-alpha.2) now! `\o/`

**Comment by afbora** [comment]
Thanks @animaux We're going to mark it as compatible when https://github.com/fabianmichael/kirby-markdown-field/issues/174 is closed.

**Comment by splorp** [comment]
Is there a reason why my [Kirby Paperback Export](https://github.com/splorp/kirby-paperback-export) plugin is listed under “Archived”?

I am working on testing it with K4 as we speak.

**Comment by afbora** [comment]
@splorp I think we moved your plugin to the archived list by mistake. Your plugin is still listed in the directory. So no problem.

https://getkirby.com/plugins/splorp/paperback-export

**Comment by splorp** [comment]
@afbora Ok, thanks for checking!

**Comment by steirico** [comment]
There is a [discussion and poll in the forum](https://forum.getkirby.com/t/future-of-the-custom-add-fields-plugin) about the future of the [Custom Add Fields Plugin](https://github.com/steirico/kirby-plugin-custom-add-fields).

**Comment by afbora** [comment]
We thank everyone who contributed ❤️ We are closing this issue. 

We tried to help as much as we could with the plugins that had issues. We know that some of them are still not K4 compatible, but it's hard to deal with all of them. Feel free to contact us anyway if you need help 👍
