### ISSUE TITLE
[v4] Model with children() decleration throws exception

### ISSUE THREAD

**Issue by HashandSalt** [k-next/kirby#5188]
## Description
Model throws exception

```
Declaration of ClientPage::children() must be compatible with Kirby\Cms\Page::children(): Kirby\Cms\Pages
```

**Expected behavior**  
No whoops!

## To reproduce

1. Create a page model that manipulates the pages children.

Heres my model that turns images and videos into virtual pages

```php
<?php

class ClientPage extends Page
{

    // Use images as pages
    public function children()
    {
        $mediapages = [];

        foreach ($this->files()->filterBy('template', 'in', ['shot', 'video']) as $media) {
        
          if($media->type() == "image")  {
            $mediapages[] = [
                'slug'     => $media->name(),
                'num'      => $media->sort()->isNotEmpty() ? $media->sort()->value() : null,
                'template' => 'image',
                'model'    => 'image',
            ];
        } elseif ($media->type() == "video") {
            $mediapages[] = [
                'slug'     => $media->name(),
                'num'      => $media->sort()->isNotEmpty() ? $media->sort()->value() : null,
                'template' => 'video',
                'model'    => 'video',
            ];
        }


        }

        return Pages::factory($mediapages, $this);
    }

}
```

**Comment by distantnative** [comment]
This is kind of an expected result: we moved a lot more type hinting from docblocks to native PHP type hints, which PHP enforces a lot more downwards when extending classes.

I am not sure if we can do much here to remove the need for developers to add those type hints - except if we would move back to docblocks which isn't quite where we want to head. Personally, I think this one is a breaking change we could allow, as it only requires adding `: \Kirby\Cms\Pages` (or just `: Pages` when using `use Kirby\CmsPages`).

We definitely need to add this to the breaking changes list though: "Throughout the system more PHP type hints got added which might require you to update your method definitions to include those type hints as well when extending core classes."

**Comment by HashandSalt** [comment]
Thanks @distantnative yes, definatly worth adding the breaking changes list until a decision has been.

**Comment by lukasbestle** [comment]
In the long run we won't be able to avoid this breaking change as it just doesn't make sense to keep type hints in the docblocks forever.

**Comment by bastianallgeier** [comment]
I was thinking about this yesterday as well. Especially for people who don't work a lot with PHP, this will definitely increase the complexity to create page models. On the other hand, the type checks will automatically validate the custom code in such extended classes and will drastically improve error handling and debugging. This in return will make it easier down the line to keep custom page models stable. When we address this properly in the docs, I think it really is the better way to move forward.

**Comment by distantnative** [comment]
I have added it to the list of breaking changes.

**Comment by mrflix** [comment]
Just stumbled upon this breaking change when upgrading von alpha.7 to beta.1:

```php
Declaration of ProjectPage::changeStatusToListed(?int $position = null) 
must be compatible with Kirby\Cms\Page::changeStatusToListed(?int $position = null): static
```

My code is based on code samples from [this virtual pages guide](https://getkirby.com/docs/guide/virtual-pages/content-from-database#advanced-setup__the-extended-comment-php-model). Keep in mind to update it there too.

**Comment by lukasbestle** [comment]
@mrflix Thanks for the heads up. I've already updated the recipe as the new code will work with both v3 and v4, but the old code only with v3.
