### ISSUE TITLE
[v4] Moving pages into site not possible

### ISSUE THREAD

**Issue by Werbschaft** [k-next/kirby#5189]
## Description

It is not possible to move a page directly to the site. An error always appears there.

**Screenshots**  
<img width="480" alt="Bildschirmfoto 2023-05-25 um 14 12 01" src="https://github.com/getkirby/kirby/assets/2178466/07c66bd8-9c40-4652-86fd-a4ed60b50d65">

## To reproduce

Just try to push a page that has a parent page into the site. With me there always appears an error

**Comment by distantnative** [comment]
## Summary
- Page move dialog should use `identifier: id` on `k-page-tree` and use `Find::parent()` for the new page in the submit handler
- `k-page-tree` doesn't pass `identifier` prop though to subtrees due to how `k-tree` handles the recursive components.
