### ISSUE TITLE
Selected link issue for textarea field

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5198]
## Description

![screen-capture-1585-Test - Kirby Demo-localhost](https://github.com/getkirby/kirby/assets/3393422/5e21c0c0-f575-407d-b188-29a7398bd34d)

**Comment by distantnative** [comment]
What's the error here? Seems to me like the same in v3

**Comment by afbora** [comment]
I asked Bastian about it. He said it was a bug. But I realized that it's a problem that existed in 3.x as you said. But the inability to edit the link is still a problem/bug. It would be great if we could fix that.

**Comment by bastianallgeier** [comment]
I actually thought that we already check for the link tag in v3 and then explode it properly. But I guess I was wrong.

**Comment by bastianallgeier** [comment]
It's not v4 related. The same behaviour happens indeed in v3
