### ISSUE TITLE
[v4] Nested blocks recursion issue

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#5205]
## Description
The docs for the [blocks field preview ](https://staging.getkirby.com/releases/4.0/block-field-improvements#field-preview)have an example for a nested block inside the `foo` block. This nested block gives me a recursion error, though.

Object { status: "error", message: "Recursion detected", code: 500, exception: "Error", key: null, file: "Api.php", line: 214, details: [], route: "pages/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)/fields/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)(?:/(.*))?" }
index.js:1:259815

**Expected behavior**  
The nested block should not show an error.

**Screenshots**  

<img width="413" alt="Screenshot 2023-05-20 at 19 50 13" src="https://github.com/getkirby/v4/assets/5312492/07ad3bcc-c36f-4113-9503-8fa78659ebe3">

Tested on the current v4 develop branch

**Comment by distantnative** [comment]
@texnixe Could you give me a step by step what you did to get the error?

Added the blueprint as in the docs and didn't get any error clicking a little bit around:
<img width="870" alt="Screenshot 2023-05-29 at 15 07 33" src="https://github.com/getkirby/kirby/assets/3788865/61df11b6-a25c-4486-a6f8-06bed167c0d6">

**Comment by texnixe** [comment]
@distantnative The error happens when you start adding blocks to the `blocky` blocks field.

**Comment by distantnative** [comment]
@texnixe cannot reproduce that

https://github.com/getkirby/kirby/assets/3788865/59b6cba0-3925-47ad-bff6-698ca06e5603

**Comment by afbora** [comment]
I can't reproduce the `Recursion detected` issue either.

**Comment by distantnative** [comment]
@afbora can you please move this to its own issue? - doesn't seem to be related to what @texnixe described

**Comment by distantnative** [comment]
@texnixe would be great if you could add a step-by-step instruction/video as we haven't been able to reproduce it ourselves so far.

**Comment by tobimori** [comment]
I'm also using this nested blocks fine and can't reproduce it.

**Comment by distantnative** [comment]
Closing this for now - @texnixe if you know how to reproduce it, please let us know and we can reopen it
