### ISSUE TITLE
Virtual Pages: manual UUID generation not working in multi-language installations

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#5225]
## Description
As mentioned in [the docs](https://getkirby.com/docs/guide/virtual-pages/content-from-api)(since [this PR](https://github.com/getkirby/getkirby.com/pull/1886)) you have to manually generate UUIDs for virtual pages. Otherwise Kirby will generate an actual folder in the file system. This is unfortunately not working in multi-language setups.

**Expected behavior**  
Kirby should not create actual folders for virtual pages, just like it does in single-language setups.

## To reproduce

1. Add a page model overwriting the children function according to [the docs](https://getkirby.com/docs/guide/virtual-pages/content-from-api)
2. Manually generate the UUID in the content array
3. Open the page in the panel
4. See it work, there are no folders in the filesystem
5. Enable multi-language
6. Open the page in the panel
7. See it fail, there are folders in the filesystem

I've forked the Starterkit and did exactly this so you don't have to: https://github.com/medienbaecker/starterkit/tree/uuid-multilanguage-bug

You can easily switch on and off multi-language by checking out the commits.

## Your setup
**Kirby Version**  
3.94.

**Comment by distantnative** [comment]
For multilang, your virtual pages would need to receive a `translations` array, not a `content` array. Though that's an uglier part of the system we're currently working on. But for now that's probably the answer.

Have a look e.g. at https://github.com/getkirby/kirby/blob/main/tests/Cms/Pages/PageTranslationsTest.php#L33-L50

**Comment by medienbaecker** [comment]
@distantnative Alright, that works for now. Thanks for the quick help. Do you think this should be mentioned in the docs?

**Comment by distantnative** [comment]
It kinda does:

> It's also possible to create a multi-language version of this page, by adding the translations array with the content for every language version.

https://getkirby.com/docs/guide/virtual-pages/simple-virtual-page
