### ISSUE TITLE
[v4] Tags field with query error in page create dialogue 

### ISSUE THREAD

**Issue by orbiting-station** [k-next/kirby#5231]
## Description
Adding a tags field in the new page create dialogue throws an error `this.options.filter is not a function` when I start typing a tag. This seems to happen when the tags field on the page uses dynamic options with query of tags from sibling pages. If I remove the query options it works fine.

**Screenshots**  
<img src="https://github.com/getkirby/kirby/assets/76222526/e58a566f-6821-4b1e-83ce-f3e853d0b52c" width=40% >
<img src="https://github.com/getkirby/kirby/assets/76222526/02908811-031c-4bd4-8071-f7364171d37b" width=40% >

## To reproduce

1. Get the [starterkit](https://github.com/getkirby/starterkit/releases/tag/3.9.4)
2. In `album.yml` add a page create option with a `tags` field
3. In `album.yml` add query options to the `tags` field with `page.siblings.pluck("tags", ",", true)` 
4. In the panel go to the photography page and click + to add a new subpage
5. Start writing a tag in the page create dialogue, see error

## Your setup
**Kirby Version**  
4.0.0-alpha.2 

**Console output**  
```
TypeError: this.options.filter is not a function
    search http://localhost/starterkit/media/panel/9a459044c0e9d589a8dfb36aa8947cc2/js/index.js:1
    onType http://localhost/starterkit/media/panel/9a459044c0e9d589a8dfb36aa8947cc2/js/index.js:1
    input http://localhost/starterkit/media/panel/9a459044c0e9d589a8dfb36aa8947cc2/js/index.js:1
    VueJS 3
```

**Your system (please complete the following information)**
 - PC with XAMPP local development 
 - OS: Windows 10
 - Browser: Firefox
 - Version: 113.0.2

**Comment by distantnative** [comment]
@bastianallgeier seems like the fields in the dialog aren't properly processed (their blueprints). Instead of the options from the query, it receives the raw blueprint pattern

**Comment by distantnative** [comment]
Found a solution
