### ISSUE TITLE
[v4] Support `textarea` + `writer` fields in page create dialog

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5237]

**Comment by bastianallgeier** [comment]
That makes sense. Maybe we need to block those fields for now. I have no idea how we could get multiple dialog layers working at the moment. It's not impossible, but a lot of work.

**Comment by afbora** [comment]
Isn't it possible to have dialogs in layers like drawers?

**Comment by bastianallgeier** [comment]
Yes, but then we would need to invent a proper way to handle them first. We could use the same logic as in Drawers, but then we also need some sort of breadcrumb logic or similar to navigate between them.

**Comment by distantnative** [comment]
@bastianallgeier I don't think it would need a breadcrumb logic for dialogs. They just stack and the only way to get back to the previous is to submit or cancel the current/top one.

**Comment by bastianallgeier** [comment]
Ok, that sounds possible. But there still need to be quite a few new logic considerations. When a submit handler reloads the view for example, the parent dialog would be dismissed.

**Comment by distantnative** [comment]
I guess that's the problem when moving the dialog load/submit logic to the backend - the backend wouldn't know the context of the Panel state. Or only if we would actually keep track of the stack on the backend.

**Comment by bastianallgeier** [comment]
The backend is only sending back a success response and the modal.js is handling that. I guess we could actually check in there if the reload can happen already. But we sould need to keep track of that anyway somehow. Hm, not easy. 

Or maybe we need to switch to refresh for all of this. It's unfortunately quite complex.

**Comment by distantnative** [comment]
For the issue at hand, one could also think about checking in writer/textarea toolbars if they are inside a dialog already and disable certain buttons etc. that would open another dialog in that case.

**Comment by distantnative** [comment]
Moved it to https://kirby.nolt.io/575
