### ISSUE TITLE
[v4] Nested drawers broken for nested blocks

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5238]
> Cannot read properties of undefined (reading 'show')

https://github.com/getkirby/kirby/assets/3393422/acb657cb-a680-4f89-b3a7-532a5536064c

**Comment by bastianallgeier** [comment]
Is that maybe related to the same issue that @texnixe mentioned? https://github.com/getkirby/kirby/issues/5205

**Comment by distantnative** [comment]
@bastianallgeier no, Ahmet first thought so as well, but this is really about nested drawers getting messed up when not using fibre drawers but components (as block field) does as far as I could tell.

**Comment by bastianallgeier** [comment]
I was thinking about this for a bit and I wonder if we should at least stop supporting the old drawers. For dialogs it would probably kill too many plugins, but the drawer wasn't documented for plugin devs so far and there are probably only a few that used it. It would help to get this stable a lot easier. 

We also need to keep in mind that Fiber Drawer does not mean that it has to be on the backend. It just means that the drawer isn't defined as a component inside a template. 

This would also be a fiber drawer: 

```js 
panel.drawer.open({
  component: "k-form-drawer"
 ...
});
```

**Comment by distantnative** [comment]
I would agree
