### ISSUE TITLE
Allow plugins to explicitly define their assets

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5247]
## Description
Only some hardcoded file extensions can be served via the core plugin assets media route. 

**Expected behavior**
The plugin assets media route should behave like the other media routes. 

**Screenshots**  
https://github.com/getkirby/kirby/blob/282b1e25faa0bc24c903237a7484dc45fa475c36/config/routes.php#L62-L68

## Your setup
**Kirby Version** 
Since 3.0

**Additional context**  
Avowedly this is done to protect the client side from dangerous files, but in my opinion this thought ignores the fact that the most dangerous files in the context of browsers (js files) are already allowed. 

From the outside it looks like "plugin code" is considered inherently unsafe, this would make it deserve *special rules to protect the user*... While being questionable (imo it's just "user code"), this in all cases ignores the fact that plugin code is anyway executed with the same privileges as Kirby and the rest of the user code - there just doesn't exist a "protect the user from plugins", be it server or client side. 

Forcing plugin devs to write their own route to serve "unknown assets" (because plugin devs don't have the choice to "just not serve them") in my opinion just leads to more, potentially unmaintained, code duplication.

**Comment by distantnative** [comment]
I think I remembered why: This is maybe less about the user but rather the developer. Plugin folders could contain a number of files that you might not want publicly accessible - composer/packagejson files that reveal what versions of the plugins you use, READMEs, maybe even license files.

Not sure if it's a real problem, but I think that was the thought to define a list of extension types that are very likely intended to be published/public.

**Comment by rasteiner** [comment]
In my humble opinion it would be safe to assume that files that are put into the "assets" folder are meant to be public. 

I mean the route doesn't publish the whole plugin folder, only the "assets" folder. Package and composer files normally stay in the plugin root (and if put under assets, the current route would already serve them). Finally, if a dev puts his secret files into a folder called "assets", I think that could be smoothly considered user error.

**Comment by distantnative** [comment]
You're right. I missed that part.

**Comment by bastianallgeier** [comment]
While I agree with the notion that this shouldn't be too opinionated. I don't agree that this is just a user error. A plugin can easily do quite some damage here by using a PHP file as asset for example. Intentionally or not. There are other vectors that this could introduce. I think it should be an allow list that can be extended. But it needs to happen deliberately in my opinion.

**Comment by rasteiner** [comment]
Since there is no stopping of intentional damage in this context (a bad plugin author doesn't need this route to copy bad files into `/media`), I think the problem can be reduced to the unintentional damage: a dev puts his secret files into `/assets`, unaware that kirby publishes them. If that is your concern, filtering by extension is not enough. At this point, for v4 I'd propose to either change the folder's name from "assets" to something more significant, like "public", or to ditch the implicit publishing alltogether and replace it with an explicitly declared list of asset paths in the plugin:

```php
Kirby::plugin('some/assets', [
  'assets' => fn($request) => [
    'plugin-logo.svg' => 'public/logo.svg',
    'plugin.js' => 'dist/some.min.js',
    'plugin.css' => 'dist/some.min.css',
  ]
]);
```

At that point this could also solve the [other issue](https://github.com/getkirby/kirby/issues/5164) of plugin asset paths not containing their timestamp, as the `["url" => "file"]` mapping would become the plugin devs responsability. 

---- 
PS: I've written the property as closure to enable devs to eventually list "all their files" dynamically, but without having that file scan run on every page load, but only if actually a file in the plugin's media folder namespace is requested:
```php
Kirby::plugin('some/assets', [
  'assets' => AssetScanner::fromPath(
    __DIR__ . '/public', 
    allowExtensions: ['svg', 'js', 'css']
  )
]);
```

**Comment by lukasbestle** [comment]
I really like that idea.

We could deprecate the automatic `assets` dir but still treat it like before for a while so devs can migrate. Once the assets extension is defined for the plugin, only the allowlisted files are published and the deprecated automatic behavior is disabled.

**Comment by distantnative** [comment]
I started with a first implementation (https://github.com/getkirby/kirby/commit/4bc3dac225b7e493becb57268f3c9debab360e06). But it also raised some question with me:

- How does this solve https://github.com/getkirby/kirby/issues/5164. exactly? It's not like these assets are easily exposed. Or how should they?
- What's the exact intention behind `name => filepath`? Why not a simple non-associative array with paths?
- What's the behaviour of `PluginAssets::resolve(string $path)`? Check if the path is included in the array? If not, return null.

**Comment by rasteiner** [comment]
> * How does this solve [Plugin asset CSS files miss timestamp in URL #5164](https://github.com/getkirby/kirby/issues/5164). exactly? 
> * What's the exact intention behind `name => filepath`? Why not a simple non-associative array with paths?

It doesn't directly solve #5161, but having a `'URL' => 'filepath'` mapping would allow users (or future you) to create their own logic to timestamp the assets. It solves the issue by making it become a user problem, rather than a not implemented feature. 

A future implementation (let's call it "thing"), made either by you people or by a user, could scan the files and generate paths mappings like:
```php
[
//   virtual url               physical filepath
    'plugin.1691259966.js' => 'dist/plugin.min.js',
]
```
The same "thing" could then also be used in the frontend to echo the URLs with timestamp. I mean, that "thing" could ideally also be used to generate the inverse mapping:

```php
<?php
// this is generated by a Thing™
$inverseMapping = [
    'dist/plugin.min.js' => '/media/plugins/superwoman/awesomeplugin/plugin.1691259966.js',
];
?>
<script src="<?= $inverseMapping['dist/plugin.min.js'] ?>"></script>
<blockquote>
  I am a happy developer because I didn't need to change this file to include a timestamp.
</blockquote>
```

While **not** having such a mapping part of the extensions API, would mean that the timestamping feature has to come from Kirby. 

> It's not like these assets are easily exposed. Or how should they?

I'm not sure I understand the question. The whole point of plugin assets is to have them exposed: if you have a plugin asset, you want to expose it. 
The point of fingerprinting / timestamping them is to have browsers load new versions of otherwise cached assets (cache busting); it's not a security feature. 

----

> * What's the behaviour of `PluginAssets::resolve(string $path)`? Check if the path is included in the array? If not, return null.

I think you know better than I do? 😅

**Comment by distantnative** [comment]
> I'm not sure I understand the question. The whole point of plugin assets is to have them exposed: if you have a plugin asset, you want to expose it.

I was talking about what you call inverse mapping. It's all nice to have the mapping in the plugin extensions to be used by the router. But that doesn't let a developer/user use it in templates etc.. So any time stamping etc. would then have to be added manually in templates, snippets etc.?

**Comment by lukasbestle** [comment]
> What's the exact intention behind `name => filepath`? Why not a simple non-associative array with paths?

We could support both: If a string key is given, it is used as the asset name. Otherwise the `basename()` of the file path is used. Overriding the asset name could e.g. be used if you want to expose a file from the vendor folder with a different name, for example if two files have the same name but should be exposed as different assets.

**Comment by distantnative** [comment]
Shouldn't we use the relative path from the plugin directory then? Imagine using `basename()` but we have `foo/test.js` and `bar/test.js`.

**Comment by lukasbestle** [comment]
Hm, I feel like the paths would get too long then, e.g. if you want to expose a file from the vendor folder. To prevent such collisions, we would have the string keys with a custom path/name. The key would be able to contain slashes as well.

**Comment by rasteiner** [comment]
Yes on "relative path from plugin root".

> would then have to be added manually in templates, snippets etc.?
That's up to the plugin dev. They would be in control of generating routes, therefore they would then also be responsible for providing such routes to the "plugin user". 

If we don't let plugin devs provide the route mapping, it's Kirby's responsibility again, and that just seems like a perfect way of getting in a developer's way: some plugin assets might need time-stamping, others might work better with a fingerprinting hash or whatnot. Others might be better off without any form of cache busting or actually rely on having an exact filename that should never change.
It's a really large scope to expect from Kirby, and I have the feeling that it would create an opportunity for "edge cases" which aren't accounted for. 
Giving plugin devs the control over routes for assets seemed like an elegant solution to this. Kirby would just take those routes and and copy the assets into /media. But of course there are other solutions as well to the same problem, I guess you also don't want to create "too much overlay" with the route plugins... It's hard.

**Comment by rasteiner** [comment]
Oh wtf, I misclicked on my phone, didn't want to close...

**Comment by rasteiner** [comment]
> Hm, I feel like the paths would get too long then, e.g. if you want to expose a file from the vendor folder. To prevent such collisions, we would have the string keys with a custom path/name. The key would be able to contain slashes as well.

I mean at that point, since we're talking about a fallback strategy for non associative arrays, "a key containing slashes" would already be the full relative path. If you don't like the length of the default key, you make your own and use the associative array.

**Comment by lukasbestle** [comment]
Both ways are fine for me :)

**Comment by distantnative** [comment]
Tried to implement it as described https://github.com/getkirby/kirby/commit/c54adffdc01424c60e06ecf1a1d7120681f0cc72
But would be great if you two could have a look at if if I understood it correctly.

**Comment by lukasbestle** [comment]
Goes into the right direction I think. I left some comments. Remaining part that's missing is to allow any file extension when the assets were provided by the plugin extension and only apply the current allowlist if the files were auto-detected.

**Comment by rasteiner** [comment]
Sorry for the late answer, it was a busy week. 

In the tests, you keep adding a `$root` variable to the paths, does this mean that the Plugin has to specify its own install dir? (or is it just because of how tests work?). 
I mean passing an absolute path could be useful for specifying assets that are outside of the plugin folder, but I wonder if the added verbosity is worth it? 

In my head, the callback function also received a `$path` argument which corresponds to the `$path` argument of the `Plugin::resolve()` function, so that the callback function could either return a string (directly the relative path pointing to the resource) or an array (like now in your implementation) or `null` if it doesn't have that asset (or any asset).

```php
'assets' => function(string $path): array|string|null {}
```

in `Plugin:resolve`
```php
$asset = $plugin->asset($path);

if (F::exists($asset, $plugin->root()) === true) {
    // ...
```

Just because the plugin might be smarter than just, for example, `Dir::index`ing everything in a subfolder. 

I don't know if we actually need a `Plugin::assets()` function which lists everything. I mean for the plugin author, being able to just list all his assets can be handy if they're few, but I don't know if having that functionality "mirrored" into the kirby internals is useful. 

So... Plugin::assets can imo be removed, and its functionality can be moved into Plugin::asset:

Plugin.php
```php
function asset(string $path): string|null {
    if(isset($this->assets[$path]) === true) {
        return $this->assets[$path];
    }

    $assets = $this->extends['assets'] ?? PluginAssets::createFileResolver($this->root . '/assets');

    if($assets instanceof Closure) {
        $assets = $assets($path);
    }

    return $this->assets[$path] = match(true) {
        is_string($assets) => $assets,
        is_array($assets) => $assets[$path] ?? null,
        default => null
    };
}
```

PluginAssets.php (or somewhere else)
```php
function createFileResolver($root): Closure {
    // really banal implementation here
    // todo: better
    return fn($path) => "$root/$path";
}
```

**Comment by lukasbestle** [comment]
> In the tests, you keep adding a `$root` variable to the paths, does this mean that the Plugin has to specify its own install dir? (or is it just because of how tests work?).

The path would need to be absolute, yes. Just like with other extensions like `snippets` and `templates`. In real-world usage you would use `__DIR__ . '/assets/whatever`, PHP will insert the correct path for you.

> In my head, the callback function also received a `$path` argument which corresponds to the `$path` argument of the `Plugin::resolve()` function, so that the callback function could either return a string (directly the relative path pointing to the resource) or an array (like now in your implementation) or `null` if it doesn't have that asset (or any asset).
> [...]
> So... Plugin::assets can imo be removed, and its functionality can be moved into Plugin::asset

The `Plugin::assets()` method already existed before, so removing it would be a breaking change. But I see how having dynamic access to the requested asset path could be useful.

If we do it, I'd vote to only support `string|null` as the possible return values though in the long run. Since the callback is called with the path, it should return `$whatever[$path]` directly and not the full array. We could still support the array for backwards-compatibility, but deprecate it.

**Comment by rasteiner** [comment]
> The path would need to be absolute, yes. Just like with other extensions like snippets and templates. In real-world usage you would use `__DIR__ . '/assets/whatever`, PHP will insert the correct path for you.

Fair enough :)

> The `Plugin::assets()` method already existed before, so removing it would be a breaking change. But I see how having dynamic access to the requested asset path could be useful.

Yeah I had that doubt, but didn't actually find the function in [the docs](https://getkirby.com/docs/reference/objects/cms/plugin) or the [source](https://github.com/getkirby/kirby/blob/3.9.6.1/src/Cms/Plugin.php) [code](https://github.com/search?q=repo%3Agetkirby%2Fkirby+%2Ffunction+assets%2F&type=code). What does it do currently? I honestly can't find it anywhere. Isn't this some kind of "Mandela effect" caused by the `PluginAssets` class? 

> I'd vote to only support string|null as the possible return values though in the long run. 

Are we talking about the internal `Plugin::asset` function or the Closure for the plugin option?
In case of the internal function, I agree (my pseudo code implementation above even actually just returns `null|string` - having left `array` in there was an error - edit: I've removed it now).

If we're talking about the plugin option, I would lobby for the inclusion of `array`, just because of the expectation to be able to return the same kind of value as the "plain option". IMO I'd expect to be able to upgrade from:
```php
Kirby::plugin('some/assets', [
  'assets' => [
    'plugin-logo.svg' => __DIR__ .  '/public/logo.svg',
    'plugin.js' => __DIR__ .  '/dist/some.min.js',
    'plugin.css' => __DIR__ .  '/dist/some.min.css',
  ]
]);
```

to:
```php
Kirby::plugin('some/assets', [
  'assets' => fn() => [
    'plugin-logo.svg' =>  __DIR__ .  '/public/logo.svg',
    'plugin.js' =>  __DIR__ .  '/dist/some.min.js',
    'plugin.css' =>  __DIR__ .  '/dist/some.min.css',
  ]
]);
```

without having to go directly to:
```php
Kirby::plugin('some/assets', [
  'assets' => fn($path) => [ 
    'plugin-logo.svg' =>  __DIR__ .  '/public/logo.svg',
    'plugin.js' =>  __DIR__ .  '/dist/some.min.js',
    'plugin.css' =>  __DIR__ .  '/dist/some.min.css',
  ][$path] ?? null
]);
```

Like: let the plugin author choose the complexity they prefer. There could be different reasons to "upgrade" from a plain array to a closure, writing "custom router code" which resolves to a single file is just one of them<sup>[1]</sup>, and the Kirby code has to contain the `$array[$path] ?? null` part anyway. 

----

<sup>1.</sup> an example could banally be:
```php
Kirby::plugin('some/assets', [
  'assets' => fn() => A::map([ 
    'plugin-logo.svg' =>  'public/logo.svg',
    'plugin.js' =>  'dist/some.min.js',
    'plugin.css' => 'dist/some.min.css',
  ], fn($p) => __DIR__ . "/$p")
]);
```

**Comment by lukasbestle** [comment]
> Yeah I had that doubt, but didn't actually find the function in [the docs](https://getkirby.com/docs/reference/objects/cms/plugin) or the [source](https://github.com/getkirby/kirby/blob/3.9.6.1/src/Cms/Plugin.php) [code](https://github.com/search?q=repo%3Agetkirby%2Fkirby+%2Ffunction+assets%2F&type=code). What does it do currently? I honestly can't find it anywhere.

Sorry, you are right. I took this from the diff of the commit Nico linked, but there is actually a [commit before that on the same branch](https://github.com/getkirby/kirby/commit/4bc3dac225b7e493becb57268f3c9debab360e06) that introduced the `Plugin::assets()` method. Both commits are not already in any release. So there is in fact no breaking change.

> If we're talking about the plugin option, I would lobby for the inclusion of array, just because of the expectation to be able to return the same kind of value as the "plain option".

That's a good point. I agree with that.

**Comment by distantnative** [comment]
Tried to follow your comments https://github.com/getkirby/kirby/pull/5557

I still would keep/add `Plugin::assets()` tbh. It feels a lot more Kirby to me that there's a method to gather the whole list and one to access a specific one. Shoving all the logic into `Plugin::asset()` would feel a bit weird.
