### ISSUE TITLE
[v4] Textarea scrolls to start when inserting newlines

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5251]
Using `4.0.0-alpha.2` I experience the following behavior when editing long text in the textarea: the page scrolls up when I add newlines.

https://github.com/getkirby/kirby/assets/60777/b0dc2244-59c0-48b7-8dde-318bb9b210ab

**Comment by distantnative** [comment]
@mrflix by editing you mean simply typing a character or something special like pasting?

**Comment by mrflix** [comment]
Pressing Enter makes the page scroll to the top. Inserting text also makes the scroll jump when I move the cursor and type.

https://github.com/getkirby/kirby/assets/60777/2513743f-c5b6-4831-b17d-abcdc8811428

Seems like a `scrollIntoView` party. Browser is latest Chrome on macOS Catalina.

**Comment by distantnative** [comment]
@mrflix my hunch is rather a focus party

**Comment by distantnative** [comment]
@bastianallgeier I think this is actually caused by the new `Autoresize` custom element. Do you remember why on every resize you first set the height to `0`?

**Comment by bastianallgeier** [comment]
That's doing the trick to calculate the overscrolling height as far as I remember.

**Comment by distantnative** [comment]
I think that's what makes jump the viewport to somewhere completely else on very long textareas.

Also saw https://css-tricks.com/the-cleanest-trick-for-autogrowing-textareas/ which is based on mainly CSS. Maybe an alternative.

**Comment by bastianallgeier** [comment]
Uh, that looks neat indeed. We should give it a try.

**Comment by distantnative** [comment]
For that implementation, it would be much easier to directly integrate it into `k-textarea-input` instead of trying got offer a standalone `k-autosize` wrapper. I don't think we're using it at all in any other way than for the texture input. So maybe we shouldn't burden ourselves with trying to offer a standalone solution?

**Comment by bastianallgeier** [comment]
Sounds good to me.

**Comment by distantnative** [comment]
I did replace it and it's nice, but it doesn't fix the mentioned issue. Enter seems to cause the viewport to jump, putting the new line on top (below the toolbar). Might be a common browser behaviour, which is why the autosize library caches and restores scroll position constantly.

**Comment by bastianallgeier** [comment]
@distantnative Hm, maybe we need to get back to the old library then? It seems like a pretty complicated part that could actually not be worth the effort right now.

**Comment by distantnative** [comment]
I think you are right. The old one wasn't that bad and it solves all these edge cases. Not worth it spending our time to re-fix these.

**Comment by distantnative** [comment]
@bastianallgeier I have the same issue still even when bringing back the autosize library 🙈

**Comment by distantnative** [comment]
@mrflix I actually can reproduce it even with 3.9.5 - can you confirm this?

**Comment by bastianallgeier** [comment]
Uh, but when did we introduce this? and how? 🤯

**Comment by distantnative** [comment]
@afbora if you have some time, your detective skills in hunting down the release or even commit when this occurs for the first time would be really helpful.

**Comment by mrflix** [comment]
@distantnative you're right: I can reproduce the behavior in 3.9.5 in Chrome. Now here is where it gets complicated: in Safari 15.6.1 I can't reproduce it in 3.9.5. But in 4.0.0-alpha.2 its jumping there too.

**Comment by afbora** [comment]
Sorry @distantnative I missed your comment. I'll track down the issue.

**Comment by afbora** [comment]
@distantnative I found the source of issue that even exists in 4.0.0-alpha.1. When I've remove following line, issue disappears.

````js
textarea.addEventListener("input", () => textarea.autosize());
````
https://github.com/getkirby/kirby/blob/4.0.0-alpha.6/panel/src/components/Forms/Autosize.js#L23

**Comment by bastianallgeier** [comment]
@afbora does resizing still work without it though?

**Comment by afbora** [comment]
@bastianallgeier No, fixed height that input size after opening page.

**Comment by distantnative** [comment]
@afbora but then it would be broken. cause the textarea needs to automatically resize to fit the content. so just removing that line is not the solution.

**Comment by afbora** [comment]
@distantnative That was not a solution. Just for giving idea to you.

**Comment by distantnative** [comment]
@afbora can you still reproduce this with the `v4/fix/input-fixes` branch?

**Comment by afbora** [comment]
@distantnative Yes, still I can.

**Comment by distantnative** [comment]
@afbora I couldn't manage. Do you have a dead-proof step-by-step how to trigger it?

**Comment by afbora** [comment]
Sure, it's so easy:

1. Create a textarea field
2. Enter/type a so long long text (longer than `vh`)
3. Try to insert new line to end of text
4. You'll jump/focus to start of textarea field

**Comment by distantnative** [comment]
Indeed. I don't know why sometimes I can reproduce it, sometimes I can't.
