### ISSUE TITLE
[v4] Color field: odd placement of 6+ options

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#5253]
## Description
I love the new color field! Today I noticed when adding more than 5 options to a color field, the options in the second line are oddly placed.

**Expected behavior**  
I'd expect the options to be left aligned so they're directly under the options of the first line. Or to put it differently, I'd expect `justify-content` it to be `start` instead of `space-around`. Personally I also find a single line of e.g. 3 boxes better left aligned. But you probably had a reason to use `space-around`?

**Screenshots**  

![Color field with 7 options](https://github.com/getkirby/kirby/assets/7975568/cb1639c6-532d-4f15-93f2-36f9bd0f3c18)

## To reproduce

1. Add a color field to your blueprint
2. Add more e.g. 7 options to it
3. Have a look at the Panel

## Your setup
**Kirby Version**  
Kirby 4.0.0-alpha.2

**Comment by bastianallgeier** [comment]
Haha, nice flex

**Comment by medienbaecker** [comment]
I think you forgot `mode: options` exists 😬 

Do you want me to open a new issue?

<img width="1472" alt="CleanShot 2023-06-13 at 12 01 11@2x" src="https://github.com/getkirby/kirby/assets/7975568/95c0d57c-7fad-40f2-b6fe-a863553e07a1">

**Comment by bastianallgeier** [comment]
Hahahah, yep. That's my fault. I think we can just reopen this one.

**Comment by distantnative** [comment]
Oops, already created new one https://github.com/getkirby/kirby/issues/5275
