### ISSUE TITLE
[v4] Error text not visible in create dialog when using not supported fields

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5255]
### Panel UI

![screen-capture-1593-Site - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/82d7df9d-d97a-4fb6-ba23-68788cff850a)

### Console

> Field type "writer" not supported in create dialog

### Expected

The error should be visible for users.

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/5243#issuecomment-1576746229_

**Comment by distantnative** [comment]
@bastianallgeier So `panel.request.responder` checks for `response.json?.status === "error"`, however in the case of dialogs this field is missing
