### ISSUE TITLE
[v4] Search view: too wide with long titles/slugs

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#5257]
## Description
The search view gets too wide when the titles/slugs of the results are wider than the available width.

**Expected behavior**  
There should be some kind of limit/truncation.

**Screenshots**  
![spirit21 test_panel_search_type=pages query=jobs%2F](https://github.com/getkirby/kirby/assets/7975568/89071a05-0536-4a04-9d13-1ed136d70ed2)

## Your setup
**Kirby Version**  
4.0.0-alpha.2

**Your system (please complete the following information)**
 - OS: macOS 13.4
 - Browser: Chrome
 - Version:  114.0.5735.106

**Comment by distantnative** [comment]
Has already been fixed on a non-public branch. No further action needed for now. But keeping this open until that branch has been merged into our main development branches.

**Comment by distantnative** [comment]
Will be included in final v4 release (also a pre-release, just unsure which one).
