### ISSUE TITLE
[v4] `toUrl()` of empty link field returns page url

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#5258]
## Description
When using `toUrl()` on an empty link field, the page url is returned. This is bad because you might want to check if the link is valid by using something like this:

```php
<?php if($url = $block->link_field()->toUrl()): ?>
  <a href="<?= $url ?>">My link</a>
<?php endif ?>
```

**Expected behavior**  
I'd expect the `toUrl()` method to return `false` when the field is empty. This way the code example above would not result in an a tag at all.

## To reproduce

1. Add a link field and leave it empty
2. Return the field with the `toUrl()` method

## Your setup
**Kirby Version**  
4.0.0-alpha.2

**Comment by distantnative** [comment]
I agree but wondering if it should rather return `null`. Would be consistent with toPage etc

**Comment by tobimori** [comment]
Agree for returning `null`.

**Comment by medienbaecker** [comment]
You're absolutely right of course.
