### ISSUE TITLE
Panel url redirect issue when running on subfolder

### ISSUE THREAD

**Issue by philipptrenz** [k-next/kirby#5266]
## Description

When running Kirby from a subfolder, e.g. `example.com/sub` by configuring the `url` parameter in *config.php*, there occurs a redirect error when logging into the panel at `/sub/panel` or when opening `/sub/panel/site` (cf. screenshots). 

**Expected behavior**  

Not being redirected to `/ndc-sdg/panel/ndc-sdg/panel/site`, which leads to an error, but to `/ndc-sdg/panel/site`, which works as expected when the url is entered manually or is selected from the top menu bar.

**Screenshots**  

<img width="501" alt="Bildschirmfoto 2023-06-11 um 12 50 29" src="https://github.com/getkirby/kirby/assets/11627598/f83d15df-2307-4afc-8cdb-79cdeac5db67">
<img width="1459" alt="Bildschirmfoto 2023-06-11 um 12 45 18" src="https://github.com/getkirby/kirby/assets/11627598/ce1b589a-7ab4-4e35-9512-1cbb1fdc286f">

### Configure Kirby to run under a subdirectory
(e.g. `example.com/ndc-sdg`)
1. Configure `'url' => '/ndc-sdg'` in *config.php*
2. Use the following *RewriteRules* in *.htaccess*:
```
RewriteRule ^ndc-sdg/assets/?(.*)$ /assets/$1 [L]
RewriteRule ^ndc-sdg/media/?(.*)$ /media/$1 [L]
```
### Open the panel

1. Open `example.com/ndc-sdg/panel`

## Your setup
**Kirby Version**  
3.9.5

**PHP Version**
8.2.6  

**Console output**  
```
site:1     GET http://127.0.0.1:8989/ndc-sdg/panel/ndc-sdg/panel/site 500 (Internal Server Error)
```

**Your system (please complete the following information)**
 - Device: not relevant
 - OS: not relevant
 - Browser: Chrome 
 - Version: 114.0.5735.106

**Comment by lukasbestle** [comment]
@afbora Can you replicate this in your local subfolder setup?

**Comment by afbora** [comment]
@lukasbestle Yes, I can. Works when enter manually `/sub/panel/site` directly. But doesn't work when enter `/sub/panel`. Redirects to `/sub/panel/sub/panel/site`. 

Is there a part you want me to test?

**Comment by afbora** [comment]
A clue for the issue; `static::url('/sub/panel/site')` in `Panel::go()` returns `/sub/panel/sub/panel/site`

**Comment by philipptrenz** [comment]
Just checked, it doesn't matter if the `url` in *config.php* is configured as `/sub` or `sub`.

**Comment by philipptrenz** [comment]
Any ideas for an interim workaround?

**Comment by afbora** [comment]
@philipptrenz As workaround, you can set the option as full url like: `https://domain.com/sub` instead `/sub`.

**Comment by lukasbestle** [comment]
@afbora I don't have the capacity to work on this myself at the moment. Could you please debug this further and create a PR if you find the source?

**Comment by afbora** [comment]
I need your help with this (especially from the author of the class @bastianallgeier ). HTTP class is a very complex class for me. I think there is a problem with two methods, but I can't decide which one is the incorrect use case.

Which case(s) incorrect?
 - return value of `Home::url()` containing the root directory
 - to send an argument containing the root directory to the `Url::to()` method
 - failure to recognize/detect when a relative argument containing the root directory is sent to the `Url::to()` method

````php
\Kirby\Panel\Home::url();              // /sub/panel/site
\Kirby\Cms\Url::to('/sub/panel/site'); // /sub/sub/panel/site
````

**Comment by bastianallgeier** [comment]
I think `Home::url()` should already be smart enough to not include the subfolder if it passes the path to `Url::to()`. `Url::to()` always resolves paths based on the base URL and in this case the base URL is /sub and it is correct that it adds a redundant subfolder.
