### ISSUE TITLE
[v4] Issues with keyboard shortcuts in text blocks

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#5268]
## Description
I appreciate the new keyboard shortcuts for the blocks field. However, they're really getting in the way of efficient text processing — no matter if you use the core text block or a custom text block with a textarea using `preview: fields`.

**Expected behavior**  
⌘⌫: Delete whole line
⌘↑: Move to start of text
⌘↓: Move to end of text

**What actually happens**
⌘⌫: Delete block
⌘↑: Select previous block
⌘↓: Select next block

## To reproduce

1. Add a blocks field
2. Try to use the aforementioned keyboard shortcuts in a writer/textarea.

## Your setup
**Kirby Version**  
Kirby 4.0.0-alpha.2

**Your system (please complete the following information)**
 - OS: macOS 13.4
 - Browser: Chrome
 - Version: 114.0.5735.106

**Comment by lukasbestle** [comment]
Maybe `Cmd-Shift` as modifiers for whole blocks?

**Comment by distantnative** [comment]
@lukasbestle `Cmd+Shift+Up/Down` is already taken by sorting.

I would suggest to only support `Ctrl+` variants then and remove the `Cmd/Meta+` listeners. What do you think?

**Comment by lukasbestle** [comment]
Hm, that's unfortunate. 

I don't know TBH. Do we have a full overview of all shortcuts somewhere to get an overview of the general systematics? I think it's really important to keep the use of modifiers consistent throughout the entire Panel.

**Comment by mrflix** [comment]
+1 for not overwriting the ⌘⌫↑↓ shortcuts. Just used writer in a v4 block for the first time and directly ran into the ⌘⌫ clash multiple times because I wanted to delete lines and not the whole block. <kbd>ctrl+</kbd> sounds fine. (by the way the new split feature is awesome!!)

Edit: On my Mac <kbd>ctrl+↓</kbd> is preoccupied by "show all windows of current app".
