### ISSUE TITLE
[v4] Writer field: Allow any URI scheme as Urls in Link field

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#5278]
## Description
I want to add a link with a less common [URI scheme](https://en.wikipedia.org/wiki/List_of_URI_schemes) in a writer field, for example:
```
facetime://+123456789
smb://server
maps:q=Berlin
```
It is possible to add these Urls in the Link dialog of the writer field. But after saving the changes and reloading the panel, the links in the writer field are gone. 

## Your setup
**Kirby Version**  
4.0.0-alpha.3

**Comment by tobimori** [comment]
This applies to the Link field in general imho 
Maybe allow users to customize the validation via Regex - similar to the text field?

**Comment by SebastianEberlein-JUNO** [comment]
In the Link dialog in the writer field, I can add `facetime://+123456789` as the Url.
When I add the same Url in a `link` field I added in a blueprint, I get the error "Please enter a valid URL".

**Comment by distantnative** [comment]
Would those other schema go into `Url`?

**Comment by SebastianEberlein-JUNO** [comment]
Yes, I would probably allow any schema for the `Url` link option. 

And also `mailto:` and `tel:`, even tough there is a separate `Email` and `Phone` option. Because I might want to add a subject to my email link like: `mailto:name@website.com?subject=Hello`

**Comment by lukasbestle** [comment]
Because the field needs to parse the type back from the stored value, tel and mailto will always end up in the Phone and Email modes. We could have a check though like "if mailto contains question mark, treat as Url, otherwise as Email".

**Comment by lukasbestle** [comment]
And yes: I agree everything not recognized by the other types should also end up in Url mode.

**Comment by distantnative** [comment]
Adding vom Discord:
> a) allow disabling url validation or b) add another option to the link field thats unvalidated “text”
