### ISSUE TITLE
Structure Form Buttons overlapping

### ISSUE THREAD

**Issue by carstenjaksch** [k-next/kirby#5281]
## Description

The buttons of the structure field form are overlapping when the structure field is placed in a narrow column.

**Expected behavior**  

The buttons should not overlap.

**Screenshots**  

![Bildschirm­foto 2023-06-13 um 16 39 32](https://github.com/getkirby/kirby/assets/82714642/fe97c9fc-db80-463d-a1b4-b9daee76c819)

## To reproduce

Place a structure field in a 1/4 column and open a row to edit.

## Your setup
**Kirby Version**  

3.9.5

**Console output**  

No output.

**Your system (please complete the following information)**
 - Device:  Macbook Air M2
 - OS:  MacOS 13.0.1
 - Browser:  Chrome
 - Version:  114

**Additional context**

**Comment by distantnative** [comment]
We will revisit this I version 4 where we will start using CSS container queries. Without these, we won't really have  a chance to fix this in v3 properly.

**Comment by distantnative** [comment]
Double checked, this will be fixed in the final release of v4.
