### ISSUE TITLE
No preview for color in structure fields

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#5282]
## Description
If you're using the color field in a structure field. There's only the HEX code showing.

**Expected behavior**  
In a structure list should be the possibility to choose a color ride away. (Or at least showing the color)

**Screenshots**  
<img width="511" alt="Bildschirmfoto 2023-06-13 um 18 03 33" src="https://github.com/getkirby/kirby/assets/4754476/e105f24e-229c-4108-9123-a339fdc18893">

## To reproduce

1. Create a structure field with a color field
2. Go to panel and insert an item
3. Close the edit box

## Your setup
**Kirby Version**  
4.0.0-alpha.2

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: MacOS
 - Browser: Brave
 - Version: v1.52.122

**Comment by lukasbestle** [comment]
Looks like we need a field preview component for the Color field.
