### ISSUE TITLE
[v4] Layout field layout should also collapse when dragging for consistency with Blocks field

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5289]
## Description
When dragging layouts in a Layouts field, they will not be collapsed and all blocks inside stay full size. I expect them to be collapsed similar to when dragging single blocks.

## Your setup
**Kirby Version**  v4.0.0-alpha.2

**Comment by distantnative** [comment]
Only the dragged block can collapse. Collapsing all other blocks would make the whole page jump around unavoidably.

**Comment by lukasbestle** [comment]
I think that's not what he meant. This issue is about the layouts field that should behave like the blocks field.

**Comment by tobimori** [comment]
> I think that's not what he meant. This issue is about the layouts field that should behave like the blocks field.

yeah exactly. the blocks collapsing is a huge UX improvement, and it would be great to get it for Layouts as well.
