### ISSUE TITLE
[v4] Gallery Block Caption field removes trailing white space while typing

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5295]
## Description
Gallery Block Caption field, edited from the Drawer, trims trailing whitespace while typing. 
Editing the Caption from the Block preview does work though. 

**Expected behavior**  
Allow trailing white spaces while typing. Otherwise it’s not possible to construct a sentence with more than one word : )

**Screenshots** 

https://github.com/getkirby/kirby/assets/47149622/ceaf3d98-c9a6-46f9-87dc-91bc2f7eb089

## To reproduce
Create a core gallery block. Open the drawer and try to edit its caption. 

## Your setup
**Kirby Version**  
Kirby 4.0.0-alpha.3

**Comment by ovenum** [comment]
Currently can not reproduce this on a `plainkit` installation. So some part of my current installation must be of. Will close this and ask to re-open if i can reproduce this with a `plainkit` installation

**Comment by distantnative** [comment]
Tracked down the bug so far:
`k-writer` of the preview still emits an `@input` event, even when the caption value gets updated from within the drawer. That loop seems to kill the whitespace somehow.
