### ISSUE TITLE
Clear thumbs from media (only) when changing focus point

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#5311]
Would be nice if Kirby would automatically throw away all/certain thumbs from the media folder when the focus point is changed by a user. That way, the media folder doesn't bloat up as much.

**Comment by distantnative** [comment]
Doubting my own sanity, I added this already 5 months ago: https://github.com/getkirby/kirby/blob/v4/develop/src/Cms/FileActions.php#L390C1-L393

Question is: Does it work?

**Comment by lukasbestle** [comment]
I have tested it, works fine for me. As soon as the file form is saved in the Panel, all thumbs of that image are deleted from the `media` folder.

But actually it may be too aggressive as the thumbs are also deleted if another field value is changed or even if nothing changed at all (just <kbd>Cmd-S</kbd> was pressed on an unchanged form). Maybe we could compare the new focus point to the current focus point and only throw away the thumbs if they differ?

**Comment by distantnative** [comment]
Guess the array key exists here even if the value wasn't changed https://github.com/getkirby/kirby/blob/v4/develop/src/Cms/FileActions.php#L391

**Comment by lukasbestle** [comment]
I think so too. I think `$input` contains the whole content array.
