### ISSUE TITLE
[v4] Dragging a block causes the following blocks to jump up

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5314]
## Description
Dragging a block will remove it from the original blocks flow causing the following blocks to jump up. This can cause _disorientation_ when dragging the block to its new position and feels a bit broken.

Looks like a regression. in 3.9.4. it works as expected and feels way better.

Really like the collapsing of the dragged block copy.

**Expected behavior**  
Keep the dragged block in the original block flow to avoid content jumps. 

## Your setup
**Kirby Version**  
Kirby 4.0.0-alpha.3

**Comment by distantnative** [comment]
I cannot quite reproduce this:

**v3**

https://github.com/getkirby/kirby/assets/3788865/d2b90244-5296-40fb-8d7d-d147317c4dae

**v4**

https://github.com/getkirby/kirby/assets/3788865/feb712ba-1849-4553-acae-d6e6cb49c115

Both seem to work for me.

@ovenum Could you please provide a blueprint snippet and screen recording to better reproduce this? Thanks.

**Comment by ovenum** [comment]
Thanks for looking into this @distantnative 

Revisiting the issue, i think it works as intended. 
What caused my confusion was, that the block minimises only after drag-start and when dragging up, the block looks like it just disappeared from the original block flow.  Maybe minimise the block when the drag handle receives a pointer down event?  So certainly not a bug but a possible enhancement?


https://github.com/getkirby/kirby/assets/47149622/1a251543-25ee-4c58-b009-e3da940aad5c

**Comment by distantnative** [comment]
I'm afraid that won't be possible based on the drag library that we rely on, there we don't have the control to make that differentiation you suggest.
