### ISSUE TITLE
[v4] Any file with Image Preview allows setting the Focus Point, not only images

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5316]
## Description
I have a file template, that allows the client to upload documents (pdf) which has a Files field for selecting a poster/thumbnail image that's shown in the frontend.

Using the following syntax, I make the thumbnail available as preview in the panel too:
```yaml
image:
  icon: file
  back: "#f3f3f3"
  cover: false
  query: file.content.thumbnail.toFile
```

As soon as such an image is set, the focus point option is available - even if the file isn't an image:
![CleanShot 2023-06-19 at 19 58 33@2x](https://github.com/getkirby/kirby/assets/29142128/61035a72-1148-4ff2-80ce-5bba7b928b86)

**Expected behavior**  
This might be the expected behavior, but I'd assume it will confuse my clients in some cases. (e.g. Why can I set two focus points for such a document, one for the thumbnail, and one for the document itself?)

My recommendation would be the following:
- Automatically have it active when the file type is image, not when the image preview is set.
- Allow manual activation for other file types, and also disable for image file type, in file blueprint.

## Your setup
**Kirby Version**  v4.0-alpha.3

**Comment by distantnative** [comment]
Ok, indeed that was stupid of me to tie it to the preview image. Will fix that.
Blueprint option maybe a later step, always cautious there where/how to add these.

**Comment by mrflix** [comment]
[kirby-focus](https://github.com/flokosiol/kirby-focus) allows to set the focus for both videos and images. While videos sounds a bit exotic I did use it at one point. Maybe it makes sense to add videos to the media types that can have a focus per default.

**Comment by distantnative** [comment]
@mrflix it would be weird for videos that don’t have a preview (by default they don’t have one)

**Comment by mrflix** [comment]
@distantnative good point. But it should be possible to enable it on for videos.

A bit of-topic but I wouldn't mind if videos would preload to show a preview. And if Kirby would have built in support to match a video with a poster.

**Comment by distantnative** [comment]
@mrflix could you add the second part as an idea on feedback.getkirby.com?

**Comment by mrflix** [comment]
@distantnative done https://kirby.nolt.io/555 and https://kirby.nolt.io/554.
