### ISSUE TITLE
Error for `set_error_handle`

### ISSUE THREAD

**Issue by f1-outsourcing** [k-next/kirby#5317]
set_error_handler can be in disable_functions (which is recommend in security setups) most cms/frameworks will just generate a warning, but your solution completely fails with a hard error.

I assume that everyone does get that you do not want to echo errors to the website in a production environment not? I would suggest that the core development team reads about php security. These are functions that are advised to be disabled. 
`disable_functions = error_reporting,dl,shell_exec,exec,system, passthru,popen,proc_open,set_time_limit,max_execution_time,curl_multi_exec,parse_ini_file,show_source`

The idea behind disabling functions and forcing static values is that when the website is hacked, some things can't be changed which are important for the incident research.

This is what you get when set_error_handler()

`[Tue Jun 20 11:41:30.285669 2023] [proxy_fcgi:error] [pid 917:tid 140235832776448] [client n.n.n.n:31477] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Whoops\\Util\\set_error_handler() in /home/xxxxx/www.example.coml/kirby/vendor/filp/whoops/src/Whoops/Util/SystemFacade.php:33\nStack trace:\n#0 /home/xxxxx/www.example.coml/kirby/vendor/filp/whoops/src/Whoops/Run.php(183): Whoops\\Util\\SystemFacade->setErrorHandler()\n#1 /home/xxxxx/www.example.coml/kirby/src/Cms/AppErrors.php(167): Whoops\\Run->register()\n#2 /home/xxxxx/www.example.coml/kirby/src/Cms/AppErrors.php(101): Kirby\\Cms\\App->setWhoopsHandler()\n#3 /home/xxxxx/www.example.coml/kirby/src/Cms/AppErrors.php(63): Kirby\\Cms\\App->handleHtmlErrors()\n#4 /home/xxxxx/www.example.coml/kirby/src/Cms/App.php(109): Kirby\\Cms\\App->handleErrors()\n#5 /home/xxxxx/www.example.coml/index.php(5): Kirby\\Cms\\App->__construct()\n#6 {main}\n  thrown in /home/xxxxx/www.example.coml/kirby/vendor/filp/whoops/src/Whoops/Util/SystemFacade.php on line 33'`

**Comment by rasteiner** [comment]
I have no affiliation with Kirby, but I'd like to learn more about PHP security 🤓

Could you point me to an authoritative resource on the web which suggests what functions should be disabled? I'd like my websites to be super safe 🥷🦄

I've tried googling for the list you posted, but [didn't find anything conclusive](https://www.google.com/search?q=error_reporting,+dl,+shell_exec,+exec,+system,+passthru,+popen,+proc_open,+set_time_limit,+max_execution_time,+curl_multi_exec,+parse_ini_file,+show_source), also the list doesn't actually include `set_error_handler` 😟


As far as I know, Kirby shows errors only in debug mode (you have to actively enable it in the config), and normally those errors are swallowed (or shown in debug mode) via a custom error handler.

**Comment by f1-outsourcing** [comment]
I guess you just have to google for this.  However with a bit of common knowledge when you read this page[1] you can understand that the default error handler can be bypassed "It is important to remember that the standard PHP error handler is completely bypassed for the error types specified by error_levels "
So if they are somehow able to upload a php script and change the error handler, nasty stuff (trying exec function stuff etc) will not appear in your forced error log.


[1]
https://www.php.net/manual/en/function.set-error-handler

**Comment by rasteiner** [comment]
Interesting.

Have you tried [turning it off](https://getkirby.com/docs/reference/system/options/whoops)? 
Otherwise it might be enough to declare a mock version of it, one that doesn't do anything, in your index.php somewhere above `new Kirby`:

```php
if(!function_exists('set_error_handler')) {
    function set_error_handler() {}
}
```

I'm writing this on a phone, so I can't check if it works.

**Comment by f1-outsourcing** [comment]
@rasteiner Is this meant for me or for the development team?

**Comment by rasteiner** [comment]
Those are both configuration options Kirby offers, so it's for you. 👍

The custom error handler, which your error above complains about, comes from ["whoops"](https://github.com/filp/whoops) (a third party dependency of Kirby). Kirby offers you the option to turn that off:

[config.php](https://getkirby.com/docs/reference/system/options/whoops):
```php
return [
  'whoops' => false
];
```
Since you disabled `set_error_handler`, I'd say that telling Kirby "I don't want error handlers" would be a good start. 

----

The other option (not mutually exclusive) would be to create a mock version of `set_error_handler`, simply to have such a function in your namespace and therefore prevent the "Call to undefined function" error. 
Besides "whoops", Kirby relies on `set_error_handler` to "catch" errors from some old PHP functions (Exceptions were introduced only in PHP 5). Disabling `set_error_handler` and replacing it with a mock version of it will of course break that error handling functionality (error handlers are the only option to handle those errors), but at least it will execute. 

The `index.php` in your project webroot isn't strictly part of Kirby, but part of your application code. 
That would make it a good place to put such code which is specific to your environment, as you can run it before Kirby gets instantiated:
```php
<?php

require 'kirby/bootstrap.php';

if(!function_exists('set_error_handler')) {
    function set_error_handler() {
        return false;
    }
}

echo (new Kirby)->render();
```

---- 

> I guess you just have to google for this

I've googled for [disable_functions php.ini security](https://www.google.com/search?q=disable_functions+php.ini+security), and after having read through every result of the first two pages, I haven't found any recommendation of putting `set_error_handler` into `disable_functions`. They're probably all wrong or google hides the correct results from me, but I think it's an indicator of how common (or not) a setup without set_error_handler actually is. It really might be easier to work around the issue on your end, with the methods written above🤷

**Comment by f1-outsourcing** [comment]
> Those are both configuration options Kirby offers, so it's for you. 👍

I am not doing anything with Kirby. I am getting a 'lazy' kirby user on the phone that does not want to fix this himself because he does not understand errors. 

> The custom error handler, which your error above complains about, comes from ["whoops"](https://github.com/filp/whoops) (a third party dependency of Kirby). Kirby offers you the option to turn that off:
> 
> [config.php](https://getkirby.com/docs/reference/system/options/whoops):

If Kirby has this whoops by default, and kirby seems to be targetting the click next, next next audience. Than I think Kirby is responsible for fixing this. By either addressing this at whoops, not offering this whoops by default or having a default configuration file comment that maybe warns for this.

> 
> Since you disabled `set_error_handler`, I'd say that telling Kirby "I don't want error handlers" would be a good start.

I would conclude that this is a "we are to lazy to fix this" so you do it. Fact is still this a bad default setup. There are lots of php admin values that can't be changed and you have to test for that as well, same is in this situation. Messing with the set_error_handler is just dumb in production. 


> They're probably all wrong or google hides the correct results from me

What do you need from google or others? You do not master reading and thinking yourself? Previously I posted you a link to the php function description, which has even an example you can test with. So don't be lazy and just verify it yourself, wtf do you need google for?

>, but I think it's an indicator of how common (or not) a setup without set_error_handler actually is. It really might be easier to work around the issue on your end, with the methods written above

Even at this wordpress they are not touching these functions that results in critical failure. Maybe everyone understands it clearly that is sysadmin specific and nobody is touching it. I would say ditch this crappy whoops. 

I think I have made my point and everyone is informed. It is just now a matter for Kirby developers to decide to continue as amateurs or professionals. Amateurs are just coding shit without thinking/testing.

**Comment by rasteiner** [comment]
Whatever 👍

> I would conclude that this is a "we are to lazy to fix this" so you do it.

Just as a reminder, I have no affiliation with the team, I'm not even partner, just a community member trying to be helpful 😉. So, whatever I tell you, it can't represent the teams opinion. 

> What do you need from google or others? You do not master reading and thinking yourself? Previously I posted you a link to the php function description, which has even an example you can test with. So don't be lazy and just verify it yourself, wtf do you need google for?

Google helps me understand what is common and what not, not whether what is common is right.
The paragraph you linked to suggests that your concern is that via `set_error_handler` a bad actor might suppress errors in his malware code, making it harder to find out about it. 
This is correct, it is in fact possible to suppress error logging (up to the `E_ERROR` level) with a `set_error_handler(fn() => true)`. 

However, a much simpler way of suppressing errors (via the [`@` error control operator](https://www.php.net/manual/en/language.operators.errorcontrol.php)) is used in most malware code I've personally seen, and you can't disable that. Prohibiting set_error_handler therefore seems to give only a false sense of certainty. 

In my personal opinion, the security gain of disabling this function is, for this reason, negligible when compared with the functionality of "handling errors" it provides. I understand that this is an opinion, just like yours, the kirby team probably has a completely different opinion; but even if they're going to change something about this, it won't be released before the next release cycle. In the meantime I'd advise your "lazy user" [sic] to either change their hosting for a less *strict* solution, or to add the 5 lines of code to their `index.php` file.

**Comment by bastianallgeier** [comment]
@f1-outsourcing we don't tolerate this tone in our community. Not towards us and especially not towards community members who try to be helpful. If you are able to communicate on a professional level and provide any helpful source to back your claims, we are happy to have a look at it.

**Comment by f1-outsourcing** [comment]
@bastianallgeier Why are you not communication at a professional level? I would think if you make such statement you at least have read everything and understood everything. The latter you clearly did not, otherwise you would not be stating this.

> and provide any helpful source to back your claims

Instead of everyone whining here, be a professional a stick to the essence, find someone in your team that understands this and stop wasting time.

**Comment by distantnative** [comment]
@f1-outsourcing since you keep insulting people and don’t show any interest in a constructive exchange, I’m closing this

**Comment by f1-outsourcing** [comment]
@distantnative there is not constructive exchange possible if you do not READ and do not UNDERSTAND what you read.
