### ISSUE TITLE
Call to a member function toArray() on bool 

### ISSUE THREAD

**Issue by f1-outsourcing** [k-next/kirby#5318]
## Description
Because of this issue #5317 there is totally nothing logged in my php error logs file, so I have no idea what is going on. I can't even see what files are unable to access

**Expected behavior**  
no error 

**Screenshots**  
accessing this page /panel/retour/redirects

Call to a member function toArray() on bool 

## Your setup
**Kirby Version**  
3.9.1

**Console output**  
```
Error: Call to a member function toArray() on bool
    request http://www.example.coml/media/panel/441d63ebbc39eba359c9061ece8482bd/js/index.js:1
index.js:1:297582
    error http://www.example.coml/media/panel/441d63ebbc39eba359c9061ece8482bd/js/index.js:1
    Qm http://www.example.coml/media/panel/441d63ebbc39eba359c9061ece8482bd/js/vendor.js:1
    dispatch http://www.example.coml/media/panel/441d63ebbc39eba359c9061ece8482bd/js/vendor.js:1
    dispatch http://www.example.coml/media/panel/441d63ebbc39eba359c9061ece8482bd/js/vendor.js:1
    onunhandledrejection http://www.example.coml/media/panel/441d63ebbc39eba359c9061ece8482bd/js/index.js:1
```

**Comment by distantnative** [comment]
Can you please open up this issue in the Retour repo? As you mention, this occurs when accessing the plugin view, do I don’t believe this would be about Kirby itself.cm Closing this here, as the plugin developer will look into it sometime next week - but please open the issue there, so I won’t forget. Thanks.
