### ISSUE TITLE
Old session token keys should (temporarily) be able to read and write to new session data

### ISSUE THREAD

**Issue by s3ththompson** [k-next/kirby#5319]
## Description
I have a Kirby site that lazily loads two session-based pieces of content after initial page load: error messages (flashed to the session during the previous request) and a shopping cart (initialized with session data). For reasons that will become important later, both pieces of content need to read AND write session data to load.

Lazy loading this information also allows me to ensure that the rest of my Kirby pages don't use auth or session data, so they can be cached for all users.

In the wild, one or the other of these requests often return a 500 error: 

> Session "1687782686.0fba42e0ea550758ac47" is currently read-only because it was accessed via an old session

In [this very helpful comment](https://github.com/getkirby/kirby/issues/2505#issuecomment-596743043) on #2505, @lukasbestle explains why:

> Sessions are regularly renewed for security. Each time a session is renewed, the session token (= the session cookie) changes and is retransmitted to the browser. So in normal operation the browser will have the new session cookie already for the next requests and will use that – which will work without issues. If the API still receives requests with the old token however, it will internally use the new session data for a limited time of 30 seconds, but in a read-only mode. If the API request tries to modify any data (like when trying to log in), the error is thrown.

Here is a timeline of what happens:

<img width="702" alt="waterfall" src="https://github.com/getkirby/kirby/assets/970121/301fcd56-26ca-4bce-9b26-a866857ce22a">

0. [Before page load] Current session times out (but has not yet expired)
1. Initial page load (`/events`) (from pages cache, does not use auth or session data)
2. Two parallel requests (`/cart` and `/flash`) are sent for lazy-loaded content (both attempt to read/write session data using old token key)
3. `/flash` successfully returns response (after attempting to write to the timed out session with an old token key, Kirby successfully renewed session, returning new token key with this response)
4. `/cart` returns above 500 error (after attempting to write to the new session using old token key) 

**Expected behavior**  

Both parallel requests (`/cart` and `/flash`) succeed, because Kirby's 30 second grace period (see [above comment](https://github.com/getkirby/kirby/issues/2505#issuecomment-596743043)) for accessing sessions with old token keys should be extended to support reading *and* writing data to the new session.

As far as I can tell from @lukasbestle's comment, the main reason that the existing feature only supports read-only session access during the 30 second grace period is simply because most Panel access is read-only after login.

## Your setup
**Kirby Version**  
3.9.5

**Your system (please complete the following information)**
 - Device: Server
 - OS: Linux 5.15.0
 - Browser: Chrome
 - Version: 114

**Comment by lukasbestle** [comment]
This is unfortunately a bit more complex. I will get back to you with a more detailed explanation.

Workaround or even solution: I'd use a single request for both actions, this will be much more reliable even when Kirby doesn't throw the "currently read-only" error.
