### ISSUE TITLE
Language detects doesn't working correctly with custom locale

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5320]
## Description

Language detects doesn't working correctly with custom locale. Here my setup:

````php
// accepted languages
// tr,en-US;q=0.9,en;q=0.8,ar;q=0.7,fr;q=0.6,hu;q=0.5,pl;q=0.4,de;q=0.3,ru;q=0.2,es;q=0.1

// /site/config/config.php
return [
    'languages' => true,
    'languages.detect' => true
];

// /site/languages/tr.php
return [
    'code' => 'tr',
    'default' => false,
    'direction' => 'ltr',
    'locale' => [
        'LC_ALL' => 'tr_TR.utf-8',
        'LC_COLLATE' => 'tr_TR.utf-8',
        'LC_MONETARY' => 'tr_TR.utf-8',
        'LC_NUMERIC' => 'tr_TR.utf-8',
        'LC_TIME' => 'tr_TR.utf-8',
        'LC_CTYPE' => 'en_US.utf-8'
    ],
    'name' => 'TR',
    'translations' => [],
    'url' => NULL
];
````

Works great if I set `'LC_ALL' => 'tr'` instead `tr_TR.utf-8` or `tr_TR`.

## Your setup
**Kirby Version**  
3.9.5

**Comment by afbora** [comment]
@lukasbestle last time we made [this enhancement](https://github.com/getkirby/kirby/pull/5142), but it seems that some cases are still missing. Do you have a solution?

**Comment by lukasbestle** [comment]
I guess we also need to compare the `$acceptedLang->locale()` to the first two characters of the configured locale if a full match was not successful. The first two chars in a locale string are always the language code.

That fallback needs to happen in the same loop iteration, not in a separate loop below. With an accepted locale list of `tr,en_US` and configured languages with locales of `tr_TR.utf8` and `en_US.utf8` the Turkish locale should still win.
