### ISSUE TITLE
[v4] Writer field: page link doesn't get saved

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5334]
## Description
When I select text in a text block and add a link to a page using the new link explorer, the link get's stored as `<a>Text</a>` without the `href`.

## Your setup
**Kirby Version**  
4.0.0-alpha.3

**Console output**  
None

**Your system (please complete the following information)**
Latest Chrome

**Comment by distantnative** [comment]
Sounds like a duplicate of https://github.com/getkirby/kirby/issues/5208

Is you installation inside a subfolder?

**Comment by mrflix** [comment]
Yes, it's in a subfolder. That explains it – thanks!
