### ISSUE TITLE
[v4] Color Field Options styling

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5338]
## Description
This is merely a nitpicky bug about the styling of the options mode of the new Color field.

Right now, no matter how many options, they're styled that 6 of them fit in the field and take up 100% of the size:
![CleanShot 2023-06-30 at 18 33 24@2x](https://github.com/getkirby/kirby/assets/29142128/e3e2e89a-166a-4722-9b95-b2cdb4c1e3e5)

This means, when setting a large width, the color field inputs grow immensely in size:
![CleanShot 2023-06-30 at 18 34 18@2x](https://github.com/getkirby/kirby/assets/29142128/634233fa-1a71-4f7f-865c-72d618241111)

Or they can get very small:
![CleanShot 2023-06-30 at 18 35 34@2x](https://github.com/getkirby/kirby/assets/29142128/1a5485f4-96d3-47e5-87d5-8e8c2c9b5c43)

## My approach
![CleanShot 2023-06-30 at 18 36 35@2x](https://github.com/getkirby/kirby/assets/29142128/fc72b2c0-b052-4d74-b770-fa13548d33f0)

In my opinion, they should stay faithful to the field size used everywhere else, there shouldn't be a fixed limit of how many colors can fit in a row, but it should rather be determined dynamically (e.g. flex w/ wrap instead of grid)

## Your setup
**Kirby Version**  4.0-alpha.3

**Comment by distantnative** [comment]
This will be fixed in alpha.4 https://github.com/getkirby/kirby/blob/v4/develop/panel/src/components/Forms/Field/ColorField.vue#L186
