### ISSUE TITLE
Panel: Custom block label not working with unescaped HTML

### ISSUE THREAD

**Issue by lassereinboeng** [k-next/kirby#5346]
## Description

Hi everyone! 
I found something weird in the Kirby panel when working with custom blocks and their labels.
In my project I defined a custom block type which includes a headline field of type _Writer_ (configured with the inline option). 

**Expected behavior**  

The content of that headline field should be the label of the block in the preview. When using `label: '{{ headline }}'` I get the correct field content as my block preview label. So far, so good, but special characters in the field like "&" will be rendered as "&amp;amp;". 
So I tried `label: '{< headline >}'` as it is explained [here](https://getkirby.com/docs/guide/blueprints/query-language#querying-information-to-display__escaping-html). Then, the label does not show up anymore.

## To reproduce

- Create a custom block type
- Add a field of type Writer (maybe it must have the inline option also)
- Add `label: '{< headline >}'` to the custom block's blueprint
- Add content with special chars (e.g. "&") to the custom block and save

## Your setup
**Kirby Version**  

Kirby version is 3.9.5

**Console output**  

No messages in the console.

Thanks in advance! :-)
Best regards,
Lasse

**Comment by SebastianEberlein-JUNO** [comment]
As far as I can tell from the code ([1](https://github.com/getkirby/kirby/blob/main/panel/src/components/Forms/Blocks/BlockTitle.vue#L36), [2](https://github.com/getkirby/kirby/blob/main/panel/src/helpers/string.js#L200-L201)), the block label does not support `label: '{< headline >}'`, only `label: '{{ headline }}'`.

**Comment by afbora** [comment]
Block labels do not have [query language support like other parts (headline, info, label of fields)](https://getkirby.com/docs/guide/blueprints/query-language#querying-information-to-display__escaping-html). You can only output the static data of the block with a simple string.

As you can see in the following line, the output is cleaned from HTML tags:
https://github.com/getkirby/kirby/blob/main/panel/src/components/Forms/Blocks/BlockTitle.vue#L41C55-L41C64

**Comment by lassereinboeng** [comment]
Thanks for your replies!
@afbora I also think it is important to strip HTML tags for the block labels (e.g. line breaks). 
It is just unfortunate, that special characters also get escaped and look a little ugly in the field preview. 
I like to provide the clients with some more context in the block preview so they can find particular sections on the page more easily. Wit the regular Text field it is no problem and the special chars are displayed correctly.  
Maybe (as kind of feature request) there is a way of stripping the markup but keeping the field's content intact?
