### ISSUE TITLE
[v4] Wrong Border Radii for selected state in Options Color Field

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5348]
## Description
See the gap in the screenshot.
![CleanShot 2023-07-04 at 17 04 59@2x](https://github.com/getkirby/kirby/assets/29142128/8d2c0a0e-c2f2-4221-928c-b7bc5fcf2607)

## Your setup
**Kirby Version**  4.0.0-alpha.4

**Comment by distantnative** [comment]
👍 Already fixed on a private branch. Will be in the next alpha.
