### ISSUE TITLE
User blueprint `home` does not redirect on Panel login

### ISSUE THREAD

**Issue by olivertedwards** [k-next/kirby#5359]
## Description

Previously, we could specifiy in a user blueprint where a user should be redirected upon login via the panel login form. I set up two blueprints (admin.yml and user.yml) where admin has panel access and user does not, and specified that the user should be redirected to the frontend home page after login.

However, when trying to log in as a user (associated with user.yml) I get a Load failed error, and when trying to reload the panel, the page fails completely with a Too many page redirects error. This results in a total panel failure, and the only way to make it work again, is to delete all session files in `site/sessions`.

Here is the user.yml setup, that works in the latest Kirby 3.9.5 versions, but not in the latest 4.0.0-alpha.4 version (have double checked and tested in both versions):

```yml
title: User
home: /
permissions:
  access:
    panel: false
```

**Expected behaviour**
As in the stable K3 release version, I was expecting the user to be redirected to the home page as instructed through `home: /`.

**Screenshots**
Before login
<img width="946" alt="Screenshot 2023-07-09 at 15 47 00" src="https://github.com/getkirby/kirby/assets/2511797/47be1973-26a9-41ab-9544-3d3ea0529d79">
After entering user credentials and clicking login
<img width="1074" alt="Screenshot 2023-07-09 at 15 57 57" src="https://github.com/getkirby/kirby/assets/2511797/ff680aa8-64e6-4181-933d-dc176d26481b">
After trying to reload the panel login page
<img width="1080" alt="Screenshot 2023-07-09 at 15 46 32" src="https://github.com/getkirby/kirby/assets/2511797/371ec247-93fd-4f72-babc-36728bebfa11">

## Setup
- Kirby 4.0.0-alpha.4

**Console output**  
- TypeError: Load failed (error index.js:1:368579) — see screenshot above

**System**
 - Device: MacBook Pro
 - OS: macOS
 - Browser: Safari
 - Version: 16.5

**Comment by distantnative** [comment]
I can track it back to this change: https://github.com/getkirby/kirby/pull/5313/files

Even though, even when reverting the change, a console error flashes before the redirect happens:

```
panel.js:163 TypeError: Cannot read properties of undefined (reading 'json')
    at Object.get (:3000/src/panel/panel.js:194:19)
    at async Object.open (:3000/src/panel/panel.js:215:19)
    at async Object.load (:3000/src/panel/feature.js:86:4)
```

**Comment by distantnative** [comment]
@afbora @bastianallgeier I think https://github.com/getkirby/kirby/pull/5313 wasn't the correct fix after all but now prevents any redirect value that is not inside the Panel. I fear we have to revert it.

Wondering if the proper solution to https://github.com/getkirby/kirby/issues/5266 isn't rather located in `Panel::path()` or `Home::url()` but not affecting urls outside the panel.
