### ISSUE TITLE
[v4] Create listed pages bypassing permissions

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5365]
## Description
Utilizing the new [page creation dialogs](https://getkirby.com/releases/4.0/page-creation-dialogs) with the [custom page creation status](https://getkirby.com/releases/4.0/page-creation-dialogs#custom-page-creation-status) currently has some limitations.

```yml
create:
  status: listed

options:
  changeStatus: false
```
Assuming the bluprint specified above. When you create a new page you currently get the following error:
```
The status for this page cannot be changed
```

Even though the `changeStatus` option is set to `false` the error was unexpected. It may be beneficial to be able to bypass permissions for that particular occasion. There should be no harm in that as the intention to create a page as listed is still coming from the blueprint itself.

Edit:
The current implementation will still `publish` a page so it is at least `unlisted` and not a `draft` anymore. In some cases, this may be the preferred behavior. But in my opinion both ways should be possible. Perhaps having an additional option to `force` the status might work. In general, such a method or flag in the page method would give developers a bit more flexibility for some edge cases.

```yml
create:
  forceStatus: listed
```

For reference:
https://discord.com/channels/525634039965679616/1111220342522904706/1127913109311459470

**Comment by lukasbestle** [comment]
Assigning the bug label as from the user/developer perspective this is unexpected and the reason for it is not visible to the user. As Nico already wrote on Discord, this is caused by a limitation of the current implementation. We will need to check if there is a way to directly set the status without having to do it in two steps. Or if we can safely override the permission check with the internal `kirby` superuser without opening a potential attack vector.

**Comment by distantnative** [comment]
I currently think that wrapping the `$page->changeStatus($status)` call in `PageCreateDialog::submit()` in an `$kirby->impersonate('kirby', function () {})` would probably be the best option.

**Comment by lukaskleinschmidt** [comment]
Not sure if I'm missing something but it does not seem to work for me. I'm currently using Alpha 7 and tested it with the current project I'm working on and the startkit
