### ISSUE TITLE
Problem extending `text` field

### ISSUE THREAD

**Issue by apademide** [k-next/kirby#5369]
## Description
I'm trying to extend the text field but it appears to modify the markup and break the field: where the default text field uses `<input>`, the extended field uses `<k-hello-input>` making it unusable.
Reproducible with a 1:1 copy of https://getkirby.com/docs/reference/plugins/extensions/fields#extending-existing-fields

It appears to be very specific to the text field (number works, date works, textarea work; didn't test more advanced fields)

**Screenshots** 
Using the exact field from the ref exemple above
```yaml
text:
  type: text
  label: Text Field
hello:
  type: hello
  label: Hello Field
```
<img width="447" alt="Capture d’écran 2023-07-13 à 14 39 03" src="https://github.com/getkirby/kirby/assets/63295420/3f51465b-7762-4499-a7b3-33c36cb9cbb9">

## Your setup
**Kirby Version**  
4.0.0-alpha.4

**Console output**  
blank

**Your system (please complete the following information)**
 - Device: MacBook 
 - OS: macOS 13.0 
 - Browser: Safari

**Comment by distantnative** [comment]
I don't think this is a v4 problem but already exists in v3.
The issue is that our text field automatically uses a `k-TYPE-input`, to automatically use k-url-input etc. when needed. So it's looking for a `k-hello-input` that does not exist.
