### ISSUE TITLE
`kirbytext()` method mangles characters ➜ and▕  

### ISSUE THREAD

**Issue by miragecraft** [k-next/kirby#5375]
## Description

The characters ➜ and▕ are mangled when rendered via `$page->text()->kirbytext()` as `âžœ` and `â–•`.

However, they are rendered correctly when rendering via `$page->text()`.

**Comment by lukasbestle** [comment]
I cannot reproduce this. Have you checked that all your files (especially the content text file) are encoded with UTF-8?

**Comment by miragecraft** [comment]
Did you try them in a `textarea` field or `writer` field?

It looks like `writer` fields are immune to this problem.

**Comment by lukasbestle** [comment]
Writer fields store HTML, so they don't use and don't need KirbyText. I've tried it with a `markdown` block (which is like a `textarea` with `$page->text()->kirbytext()`) as well as by manually calling the `kirbytext()` helper:

```php
echo kirbytext('The characters ➜ and▕ are mangled when rendered');
```

**Comment by miragecraft** [comment]
Sorry, false alarm.

The problem is with the plugin https://getkirby.com/plugins/johannschopplich/highlighter

I will close this issue and open issue over there.
