### ISSUE TITLE
[v4] Structure field: no validation of fields in drawer

### ISSUE THREAD

**Issue by jaro-io** [k-next/kirby#5390]
## description
really like that in alpha 5 structures are being edited in the new sidebar view. however its validation can currently be tricked. when there are required fields in the structure, you can add a new item, leave all fields blank and then click outside the sidebar to close it. this way the item will be added to the structure and bypass validation. the page can be also saved.

**expected behavior**  
structure fields are being validated when clicking out of the sidebar.

**screenshots**  
<img width="1450" alt="Screenshot 2023-07-19 at 19 24 43" src="https://github.com/getkirby/kirby/assets/20298313/a7481346-cb9c-41dc-bda9-e30c87c1da68">

## your setup
**kirby version**  
[4.0.0-alpha.5](https://github.com/getkirby/kirby/releases/tag/4.0.0-alpha.5)

**Comment by jaro-io** [comment]
just saw that i can also publish a page with a required field that is not set. don’t know if this is related to the stuff above? 🤔 

<img width="1440" alt="Screenshot 2023-07-19 at 20 16 42" src="https://github.com/getkirby/kirby/assets/20298313/3f814145-7f30-4699-a77f-23019a2d84c4">

**Comment by distantnative** [comment]
> just saw that i can also publish a page with a required field that is not set. 

@jaro-io cannot reproduce that. if you can, please open a new ticket with a reproducible example.

**Comment by jaro-io** [comment]
@distantnative hm, i can’t reproduce it myself anymore. but i will open a new issue if i stumble over it again! 👍🏻
