### ISSUE TITLE
[v4] CheckboxInput: wrong prop type

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#5392]
```
vue.js:5108 [Vue warn]: Invalid prop: type check failed for prop "value". Expected Number, String, got Boolean with value false.

found in

---> <KCheckboxInput> at /kirby/panel/src/components/Forms/Input/CheckboxInput.vue
```

**Comment by distantnative** [comment]
@bastianallgeier 

I don't quite understand the `k-choice` component, which somehow tries to feature both `value` and `checked` at the same time. 

But then `CheckboxInput` cannot use `value` prop for the `checked` attribute.

**Comment by bastianallgeier** [comment]
I just fixed it. input[type=checkbox] and input[type=radio] can both have values and a checked attribute, so imho that's fine. But of course a value can also be a boolean.
