### ISSUE TITLE
[v4] Drawer buttons bar right padding issue

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5393]
There is a unnecessary padding on right of drawer buttons bar

![image (23)](https://github.com/getkirby/kirby/assets/3393422/6c0db1a2-0b6a-4b6e-b439-b8b17c4e4bd8)

**Comment by distantnative** [comment]
@afbora is this due to `scrollbar-gutter: stable` on `html`?

**Comment by afbora** [comment]
@distantnative Yes. I have no idea about `scrollbar-gutter: stable` but fixes when I removed.

**Comment by bastianallgeier** [comment]
The scrollbar-gutter: stable rule makes sure that the main layout doesn't shift when you open a dialog and overflow on the body is hidden.

**Comment by distantnative** [comment]
@bastianallgeier What does this mean then? I don't think we can remove `crollbar-gutter: stable` in that case. Is there a way to still style it? Or are we fine with everyone with actual scrollbars (no floating Mac ones) to have that gap?

**Comment by distantnative** [comment]
Maybe we could just add a pseudo-element `::after` the header that would have the white bar fill the gap.

**Comment by afbora** [comment]
Note that `scrollbar-gutter: stable` removes drawer scroll bar.

**Comment by afbora** [comment]
Some browsers still doesn't support:
https://caniuse.com/mdn-css_properties_scrollbar-gutter
