### ISSUE TITLE
[v4] Blocks options not clickable when multiple selected in Safari

### ISSUE THREAD

**Issue by HYR** [k-next/kirby#5399]
## Description
While testing the v4 I noticed in Safari the block merge feature doesn't seem to work. Block splitting does work but merging doesn't. Tested Brave as well and it work as expected there.

**Expected behavior**  
The expectation was that it would join two text blocks shown in the video.

**Video**  
https://share.cleanshot.com/GLP1LCxw7V4Bnctphff1

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: MacOS 13.3.1
 - Browser: Safari
 - Version: 16.4

**Comment by distantnative** [comment]
Nothing to do with the merge feature, none of the block options can be clicked when multiple blocks have been selected in Safari.

**Comment by bastianallgeier** [comment]
I spent an hour on it, but need to stop to not get angry. Safari somehow does not send the right target with the focusin event. Our onFocusIn method in the block component can then not know if the focus is coming from one of the options and happily ignore it. This will kill the batch selection and set the focus on a single block instead again.

**Comment by afbora** [comment]
Also doesn't work for me on Chrome in beta.1. Work for you in Chrome?

Not sure this issue related or same with https://github.com/getkirby/kirby/issues/5626

**Comment by distantnative** [comment]
Rather seems to be solved are as https://github.com/getkirby/kirby/issues/5442#issuecomment-1773831677
