### ISSUE TITLE
[v4] Panel breaks on large breakpoints when site is proxied and minified by Cloudflare

### ISSUE THREAD

**Issue by vincentrouleau** [k-next/kirby#5401]
![image](https://github.com/getkirby/kirby/assets/11572524/2a00eef4-583f-4b1c-8aea-471241a65fcd)
![image](https://github.com/getkirby/kirby/assets/11572524/4450abf1-92ea-4933-948f-3eacc4c1bda0)

Disabling Auto Minify for CSS and clearing the CF cache fixes the issue.
Inspecting the panel's CSS, It looks like a lot of missing semicolons.

![image](https://github.com/getkirby/kirby/assets/11572524/12583e44-224a-4571-86a0-5e93fbd790e9)

**Comment by distantnative** [comment]
Final semicolon in a set of statements is optional, so that shouldn't be an issue. 
 What does the broken CSS look like? What rules actually break?

**Comment by vincentrouleau** [comment]
![image](https://github.com/getkirby/kirby/assets/11572524/a83b677a-e705-47f2-9a1a-a7915e8d0670)
 looks like a typo. That's in the proxied file so I guess there's something preceding that.

**Comment by distantnative** [comment]
@hotdoy can you please check if the space between `span` and `var(--span)` is really missing in the compressed file? If so, I'd think this is a Cloudflare bug then.

**Comment by vincentrouleau** [comment]
Really seems to be this set of rules. 

```
@container (min-width: 50rem) {
    .k-grid {
        grid-template-columns: repeat(var(--columns),1fr)
    }

    .k-grid>* {
        grid-column: span var(--span)
    }
}
```

I'll try it out on another site just by itself see how cloudflare deals with it and escalate to them is it really is a bug with CF.

**Comment by vincentrouleau** [comment]
https://k4bug.calotte.dev/
Looks like a CF minifier bug. I'll be damned. 

By the time people ship K4 to production, there is a high chance this will come back one way or another.
I'll try and report to CF in the meantime.

**Comment by vincentrouleau** [comment]
https://community.cloudflare.com/t/cf-css-minifier-messes-up-one-specific-line/535654

**Comment by vincentrouleau** [comment]
In the meantime, you can bypass CF auto-minify for the Panel with a page rule.
![image](https://github.com/getkirby/kirby/assets/11572524/69c15b09-d074-4f98-bec6-229c38ca9e3d)

**Comment by distantnative** [comment]
Seems like Cloudflare isn't interested in addressing it at https://community.cloudflare.com/t/cf-css-minifier-messes-up-one-specific-line/535654 :(

**Comment by vincentrouleau** [comment]
Yep. Kinda sucks. I could maybe open up a ticket with their support. Or, if we knew what algo they are using to minify, there might be a way to go around the issue. For now I'll keep my CF Rule.

**Comment by lukasbestle** [comment]
I'm afraid we can't really do anything in Kirby to prevent this, right? Should we maybe add it to https://getkirby.com/docs/guide/troubleshooting/panel with a workaround?

**Comment by vincentrouleau** [comment]
Per CloudFlare docs, any file with .min in its name will not be re-minified. I know it is wrong to make decisions like this based on a vendor but that's one way.

**Comment by lukasbestle** [comment]
That could indeed be a solution. `.min` is at least not wrong, so it wouldn't be a hack. Not re-minifying the files at all would also reduce the processing and in theory increase performance a little bit.

We would need to test if we can update our Vite/Rollup config without breaking anything else.

**Comment by bastianallgeier** [comment]
I honestly wonder how far this can be considered a standard (.min in the filename) or how much this is just a rather ignorant assumption of Cloudflare. I find it highly disappointing that they don't even comment on the issue and just close it. It kind of kills the mood to now spend extra time on such a custom fix just for them. On the other hand, I really don't want to leave our users hanging with that. I assume that there will be quite a few who use Cloudflare.

**Comment by bastianallgeier** [comment]
Ok, I gave it a try and it doesn't take too much work to fix this on our end. @distantnative @afbora @lukasbestle you should really double-check my PR. Maybe you can spot any trapdoors that I might have missed. 

I really don't want to start working on such custom work-arounds for hosting providers. But I think this could actually be seen as a more clear distinction between minified and unminified files for us as well. That's why I think we could argue that this is also an enhancement for us.

**Comment by vincentrouleau** [comment]
The post was made on the community forum since I'm not a paying customer. 
It might have been different if we had an Enterprise customer in our ranks.

**Comment by bastianallgeier** [comment]
@hotdoy that might be true.
