### ISSUE TITLE
Predefined variable types

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#5405]
I have often noticed that more and more variable types are getting predefined in new releases. This can certainly limit fault liability, but it does limit the extensibility of classes via plugins. 

In the example below, I no longer have the option to work with customized fieldset(s) classes.

https://github.com/getkirby/kirby/blob/6490609df2cf83ddb9d4638eba63f6aa2e16dd48/src/Form/Field/BlocksField.php#L27
https://github.com/getkirby/kirby/blob/6490609df2cf83ddb9d4638eba63f6aa2e16dd48/src/Form/Field/BlocksField.php#L83
https://github.com/getkirby/kirby/blob/6490609df2cf83ddb9d4638eba63f6aa2e16dd48/src/Form/Field/BlocksField.php#L94

If it is not mandatory, I would be happy if the declaration is removed.

**Comment by distantnative** [comment]
@youngcut This is about type safety and pretty important for Kirby to mature further and making regressions less likely. You can still use custom classes that extend the base classes. PHP will accept child classes as well.

If that somehow does not cover your use case, please share all the details of your use case to understand if it’s something we can/want to support or a hack that we don’t seem healthy for Kirby's future.

**Comment by plain-solutions-gmbh** [comment]
Here's the point, where i getting in trouble:

https://github.com/youngcut/kirby-components/blob/187616879132d3c6db959c4a28a055d534986530/lib/ComponentsField.php#L20

PHP expecting `$fieldsets` to be `Kirby\Cms\Fieldsets`. But i need Fieldsets to be `Microman\ComponentFieldsets`

**Comment by distantnative** [comment]
And why isn't `Microman\ComponentFieldsets` extending `Kirby\Cms\Fieldsets`?

**Comment by plain-solutions-gmbh** [comment]
Because of that error message:

<img width="724" alt="Bildschirmfoto 2023-07-24 um 10 36 53" src="https://github.com/getkirby/kirby/assets/4754476/bc2f52b7-92e3-4f10-a00e-27337d640f69">

**Comment by plain-solutions-gmbh** [comment]
Later [on Line 184](https://github.com/youngcut/kirby-components/blob/187616879132d3c6db959c4a28a055d534986530/lib/ComponentsField.php#L184) i set the `$this->fieldsets` with the extended `Microman\ComponentFieldsets` (as Fieldsets) instance.
At the latest then he will not find it good.

**Comment by distantnative** [comment]
Yes, I get that. But why is your custom class extending the Items class and not our Fieldsets class? If it would extend the Fieldsets class it wouldn’t throw the error

**Comment by plain-solutions-gmbh** [comment]
A very good point. Once upon a time i extended the fieldsets class, but...
I have the problem that the original [factory method](https://github.com/getkirby/kirby/blob/6b5dda600472b59a3a779f7e6b8e9e130cc414a1/src/Cms/Fieldsets.php#L93)  overrides my `$result`. Have no way to call the grandparents here, so my idea was to use the items class.

Maybe, you find another solution for that.

**Comment by distantnative** [comment]
Ok I see why you practically went this way, but I think the new type hint still needs to happen: Kirby needs to be sure this is Fieldsets object, not just an Items object (which could be also Blocks etc.). So your custom class needs to extend Fieldsets. The other way to solve this without inheritance would be PHP interfaces, but that's not a part Kirby has pursued so far.

I think your code should work when you extend Fieldsets and you do

```php
    public static function factory(array $items = null, array $params = []): static
    {
        static::$components = $components = new Components();
        static::initTabs($params["tabs"] ?? null);
        $items ??= array_keys($components->components(false, true));

        return parent::factory($items, $params);
    }
```

As `Fieldsets::factory()` will make the call to `::createFieldsets()` for you then.

**Comment by plain-solutions-gmbh** [comment]
You save my day. 🙌
Thank you, Nico.
