### ISSUE TITLE
Search component broken when query is `null`

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5428]
## Description

> Kirby\Cms\Core::{closure}(): Argument #3 ($query) must be of type string, null given, called in /kirby/src/Cms/Search.php on line 40

Regression PR: [Clean up search component](https://github.com/getkirby/kirby/pull/5297)

## To reproduce
````php
$results = $site->search(get('not-exists-param'), 'title|text');
````

## Your setup
Kirby 3.9.6

**Comment by gbdesign2023** [comment]
The search does not generate an error message if a GET value is specified in the domain, e.g. with a saved search word:
https://domain.com/search?q=smartkeyword

**Comment by afbora** [comment]
@gbdesign2023 What do you get as error when you entered `/search?q=smartkeyword`?

**Comment by gbdesign2023** [comment]
I do not receive any error message. The search result is displayed as expected. Only when I go to the search page, the error is displayed. (I use the search function from the Cookbook.)
