### ISSUE TITLE
Uuid not corrected when cached

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#5430]
## Description
If a cached UUID points to a wrong id (pseudo folder path), it is not corrected when retrieved. 
However, when a UUID is not cached, it is created upon retrieval. 

**Expected behavior**  
The cached value should be updated when it is found to be incorrect. Just like when it is not found. 
The wrong cache could at least be removed, so that it's corrected one page load later. 

## To reproduce
1. have a page
2. make sure a UUID is generated
3. change the page's folder path manually in your explorer / finder
4. search for the page with `page('page://myuuid')`, a page will be found anyway (although by doing a full index scan)
5. search for the page with `page('page://myuuid')` again, a full index scan is done again

## Your setup
**Kirby Version**  
I've noticed this in v4, but I guess this is the same in earlier versions

**Additional context**
Deleting the cache resolves the problem.

**Comment by afbora** [comment]
3.9 also has the same issue.
