### ISSUE TITLE
[v4] svg preview in file upload & file replace not working

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5436]
## Description
When uploading and replacing files, no preview gets loaded for svg files.

**Expected behavior**  
I'd expect to be able to preview the svg file.

**Screenshots**  
![Screenshot 2023-08-01 at 11 04 16](https://github.com/getkirby/kirby/assets/60777/73fa5613-875e-4e3b-8a98-b4c297db6060)

![Screenshot 2023-08-01 at 11 00 34](https://github.com/getkirby/kirby/assets/60777/5b63ded1-3340-48c8-8c17-8ab32c0e9a2e)

**Kirby Version**  
4.0.0-alpha.5

**Comment by distantnative** [comment]
Worried that directly outputting an SVG could have security implications.

**Comment by distantnative** [comment]
@lukasbestle you probably have the best overview on that aspect: the upload preview currently works in-place in Javascript. We just use `URL.createObjectURL` to get a temporary URL which we can use to preview the image. But with SVG I fear this could be abused with malicious SVGs to be executed. 

I don't think backend sanitizing is an option - adding the extra roundtrip to the feature doesn't seem in reach currently. So either we can display it as is from the JS data or I'd vote to close the issue.

**Comment by lukasbestle** [comment]
@distantnative Browsers don't execute JS or load external resources when an SVG is loaded from an `<img>` tag. So if we convert the SVG into a data URI and load that as `<img src="data:image/svg+xml,...">`, it should be fine.

We should still test the implementation for potential attack vectors. Fortinet has a good overview: https://www.fortinet.com/blog/threat-research/scalable-vector-graphics-attack-surface-anatomy
