### ISSUE TITLE
[v4] [v4 alpha.6] Panel: error when saving

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5446]
## Description
When I press save after changing something, an error pops up:

**Screenshots**  
![Screenshot 2023-08-02 at 15 58 33](https://github.com/getkirby/kirby/assets/60777/3275acb6-751e-4366-bb3f-0229c64f91c3)

![Screenshot 2023-08-02 at 16 02 27](https://github.com/getkirby/kirby/assets/60777/4017b825-d933-478c-ab14-b4a975209aae)

I tested it in another project to softly rule out that it has something to do plugins: (writer field)

![Screenshot 2023-08-02 at 16 02 08](https://github.com/getkirby/kirby/assets/60777/2fcaa761-68ab-4330-b37e-36d683afbfeb)

**Comment by bastianallgeier** [comment]
Argh, I can unfortunately reproduce this. Sorry.

**Comment by bastianallgeier** [comment]
That was too critical to leave it in there. I re-released the alpha with a quick patch.

**Comment by mrflix** [comment]
I was a bit hesitate to report it so soon after the release because I don't want to make you folks feel bad with all the hard work you put into it. But at the same time I was thinking that it's better to solve it as soon as possible and patch it quickly.

**Comment by mrflix** [comment]
Can confirm that its fixed.
