### ISSUE TITLE
[v4] Header Disappears

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5447]
## Description
The header (Article One) disappears when opening a modal or drawer.
Just cosmetic but maybe an easy fix by adding something like this to the header.

```css
position: relative;
top: var(--scroll-top);
```
![disappearing_header](https://github.com/getkirby/kirby/assets/10027897/2b511628-27d6-4cac-b76c-9bd5709debeb)

## Your setup
**Kirby Version**  
4.0.0-alpha.6

**Your system (please complete the following information)**
 - Browser: Firefox
 - Version: 117

**Comment by bastianallgeier** [comment]
Who would have thought that scroll bars can be such a pain in the ass. We were really happy about our latest solution that would keep the scroll bars consistently on the document to avoid layout shifts, but still don't have double scrollbars when the drawer is open. Seems like we missed the header shift though 🙈 The scroll top idea is nice!

**Comment by lukaskleinschmidt** [comment]
Indeed a nice solution for the jumping scroll bars. Probably gonna steal that for some projects 😉
