### ISSUE TITLE
[v4] Awkward Block Table Preview

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5451]
## Description
The block `preview: table` is currently awkward to use.
You have to double click on the block that opens the drawer with all entries and you have to click again to open the actual line you want to edit. It would be nice if `preview: table` would work like `preview: fields` in that regard. Not sure if this is limited to v4 though.

![preview_block](https://github.com/getkirby/kirby/assets/10027897/f786f0bc-73db-426d-88ee-e490864ab8bb)

**Comment by distantnative** [comment]
@lukaskleinschmidt I think this really belongs rather on http://feedback.getkirby.com/ - could you add it there please?

**Comment by lukaskleinschmidt** [comment]
https://kirby.nolt.io/565
