### ISSUE TITLE
[v4] Save button not working

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5452]
## Description
Clicking the `Save` button currently throws an error.
Using the keyboard `cmd+ s` still works as expected.

I cleared the media folder and also checked in Chrome but still having the same problem.

![save_issue](https://github.com/getkirby/kirby/assets/10027897/80c1dd2e-6a9b-4cce-8293-38c2f083f293)

## Your setup
4.0.0-alpha.6

**Your system (please complete the following information)**
 - Browser: Firefox
 - Version: 117

**Comment by afbora** [comment]
We've re-published `4.0.0-alpha.6` release with quick patch that fixed that issue. Could you re-download the release please?

https://github.com/getkirby/kirby/releases/tag/4.0.0-alpha.6
