### ISSUE TITLE
Error message for required field in layout

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5453]
## Description
Having a required field in a custom block shows the following error when trying to save the page.

![saving_layout](https://github.com/getkirby/kirby/assets/10027897/7385ea31-32c5-4ff2-8a0d-98a59185bcc3)

## Your setup
4.0.0-alpha.6

**Your system (please complete the following information)**
 - Browser: Firefox
 - Version: 117

**Comment by afbora** [comment]
Sorry, I don't quite understand what is wrong here 🙈

**Comment by lukaskleinschmidt** [comment]
The image field is set to required in the block. And when I try to save the page it blocks me (as expected). But the error message shown is not really helpful for the end users.

I was using `cmd + s` to save the page because I had the older alpha version #5452

**Comment by afbora** [comment]
AFAIK this error message has not changed since the layout field was released. What kind of message would be more descriptive? Also this is not related to v4.

**Comment by lukaskleinschmidt** [comment]
Oh wasn't aware of that. I think what threw me off is that it is not directly visible where the error comes from.

![grafik](https://github.com/getkirby/kirby/assets/10027897/be57da4d-d5b1-4699-923d-4877515c63e6)

It is relativley clear for this one as it is the first layout and there are not many blocks. But this could get hard to track down once you are in layout 7 out of 9 with 12 blocks I guess. At least that's where the "issue" came from.

**Comment by distantnative** [comment]
I still don't quite understand what's the expectation, @lukaskleinschmidt.

**Comment by lukaskleinschmidt** [comment]
I was expecting something more than just the popup if that makes sense. The popup has the right informations but I see some issues when you have a lot of layouts and you kinda need to go for a little hunt to find the right block.

I expected something like this:

![grafik](https://github.com/getkirby/kirby/assets/10027897/35f438cd-f437-4d70-87a9-55b234efde69)

Just checked an older version where fields got a red outline/shadow if they were required and not filled out.
I think thats where the initial impression came from. It is the first time that I'm actually working with the layout/block fields for real instead of just messing around with it. So please bare with me if all of this has already been discussed in full at some point 😅 

![grafik](https://github.com/getkirby/kirby/assets/10027897/6153444f-2cce-42f5-a28f-ac0ee639ed58)

**Comment by distantnative** [comment]
I understand the wish, would vote for it too. But it's not really a bug or ne. And it's also to totally trivial to implement these the way how blocks, layouts and structure fields function currently. Could you please add this to http://feedback.getkirby.com/ as well? We need to be a little strict here as it gets otherwise hard to track what's an immediate bug, regression and what's more a feature and/or enhancement people would like to see.

**Comment by lukaskleinschmidt** [comment]
Yeah, I think in my mind it always was like this. But well 🙈 

https://kirby.nolt.io/566
