### ISSUE TITLE
[v4] long dialog's top cut-off in Firefox

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5466]
Drop a lot of files into the panel in Firefox 116 (Works in Chrome). Scrolled to the top:

![Screenshot 2023-08-07 at 16 53 31](https://github.com/getkirby/kirby/assets/60777/4feaade7-1905-4f3f-869f-1c7b3d3e0ab9)

Query a lot of files in a file dialog in Firefox 116, again scrolled to the top:

![Screenshot 2023-08-07 at 17 15 56](https://github.com/getkirby/kirby/assets/60777/10896199-7c52-4ad3-9fd2-9e65df46c75b)

Reminds me of the old flex-bug where you'd have to use `margin: auto` instead of `align-items: center`. The dialog is placed via `display: grid` though. Can't find it in this [gridbugs list](https://github.com/rachelandrew/gridbugs).

alpha.6

(We're using Firefox now to save the web, right?)

**Comment by distantnative** [comment]
So for me it does scroll but part of the top is cut off. Also no padding when scrolled to bottom. I think that's what you also mean.

**Comment by mrflix** [comment]
Yeah it does scroll down. Just not further up so no chance to see the top part.

**Comment by bastianallgeier** [comment]
This is a super weird fix, but Firefox isn't happy with grid and center placement. The only working solution seems to be a combination of inline-flex and margin auto

https://github.com/getkirby/kirby/pull/5523
