### ISSUE TITLE
[v4] Page-Link in Link Node in Writer not rendered correctly

### ISSUE THREAD

**Issue by moriweb** [k-next/kirby#5471]
## Description
In Starterkit on any note-Page just change written Text via Node inside of a writer field to a Link. Dropdown-Select "page" and select one Page.

**Expected behavior**  
Correctly rendered link with a href to the url of the selected Page.

**Screenshots**  
To Reproduce the error:
<img width="2255" alt="screen_produce-error" src="https://github.com/getkirby/kirby/assets/23299522/57e273fd-f286-49c7-9f7a-6bab4fe4217d">

What comes out in Code:
<img width="2140" alt="screen_output_link" src="https://github.com/getkirby/kirby/assets/23299522/87078ed2-bd7e-4247-8298-5acd72cecf52">

## To reproduce

1. Go to Subpage "notes/exploring-the-unierse".
2. Select the Text you want to add a link to.
3. In the Node-Menu chose "Link" Icon
4. In the Modal select "page" instead "url"
5. Select a Page you want to link to e.g "trees"
6. Save and preview the page

## Your setup
- Starterkit, Kirby 4.0.0-alpha.6

**Your system (please complete the following information)**
 - Device: Macbook 2020
 - OS: Ventura 13.4.1
 - Browser: Google Chrome 115.0.5790.170

**Comment by afbora** [comment]
Issue exists since 4.0.0-alpha.1

**Comment by distantnative** [comment]
@mohorii is your Kirby set up in a subfolder? Thinking this could be the same as https://github.com/getkirby/kirby/issues/5208

**Comment by afbora** [comment]
I remembered this issue before but couldn't find the issue. I test it in a subfolder and the author's screenshot shows that is using it in a subfolder. I think it's the same issue.
