### ISSUE TITLE
[v4] escaped <strong>html</strong> in lock message

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5475]
![Screenshot 2023-08-09 at 15 28 48](https://github.com/getkirby/kirby/assets/60777/0d65688c-dad7-49bc-b63b-7711962f2c63)

**Kirby Version**
alpha.6

**Comment by distantnative** [comment]
Oh yes that's due language variables haven't been updated yet. Should be fine in English already

**Comment by mrflix** [comment]
![Screenshot 2023-08-09 at 16 42 57](https://github.com/getkirby/kirby/assets/60777/1b61cbd8-68ad-4931-b8d6-37d3cd4d4acb)

Ah, I see. So in the english translation the html got removed. Are you planning on supporting markdown there or will you just remove all html?

**Comment by distantnative** [comment]
Leaning to removing it as buttons currently don't support html via prop. But that might change.
