### ISSUE TITLE
[v4] Email function throwing pagination error

### ISSUE THREAD

**Issue by skyeewers** [k-next/kirby#5484]
## Description
The `$kirby->email()` function appears to be broken in the current alpha6 of Kirby v4. It throws an `Invalid page number` error when trying to send any eMails.

**Expected behavior**  
An eMail would be sent by Kirby

**Error output**  
```json
{"status":"error","exception":"Kirby\\Exception\\Exception","code":"error.general","message":"Invalid page number: site","details":[],"file":"\/kirby\/src\/Toolkit\/Pagination.php","line":372}
```

## To reproduce
Try to send an email using the following code on v4 alpha6. Code taken straight from the Kirby docs, too.
```php 
kirby()->email([
    'from' => 'welcome@supercompany.com',
    'replyTo' => 'no-reply@supercompany.com',
    'to' => 'someone@gmail.com',
    'cc' => 'anotherone@gmail.com',
    'bcc' => 'secret@gmail.com',
        'subject' => 'Welcome!',
        'body'=> 'It\'s great to have you with us',
    ])->send()
```

## Your setup
**Kirby Version**  
`^4.0.0-alpha.6`

**Comment by distantnative** [comment]
I tried, but couldn't reproduce it. Email got sent for me.

What's your email setup in `config.php` and is there any other code around this that could cause the error?

**Comment by afbora** [comment]
I couldn't reproduce the issue either. The page you sent the email to appears invalid/not exists. (Like `/page:99`)

**Comment by skyeewers** [comment]
I'm sorry, I was being silly 🤦🏻‍♀️
The code triggering this was completely unrelated to e-mail and seems to not be a Kirby v4 problem at all.
