### ISSUE TITLE
[v4] Link Field: Pages are not visible when UUID's are turned off

### ISSUE THREAD

**Issue by modufolio** [k-next/kirby#5489]
## Description
Pages are not visible when UUID's are turned off

Only one is displayed

## To reproduce
Add this to the config file:
`    'content' => [
        'uuid' => false
    ],
`

One will be displayed,
when this is removed, the error page is shown too.

## Your setup
**Kirby Version**  
4.0.0-alpha.7

**Comment by afbora** [comment]
Seems link field only works with UUID.

And when clicked to first one:

> Cannot read properties of null (reading 'trim')

**Comment by afbora** [comment]
Important question is; now link field detects based on `file://` and `page://` strings. How can we detect pages and files when UUID disabled?

**Comment by lukasbestle** [comment]
We could use URIs with the page ID like `page://projects/project-a`. But then we need to make sure that those URIs also work when UUID support is enabled (otherwise sites will break when the UUID option is changed with existing content). So not simple.

**Comment by distantnative** [comment]
I don't think the link field can meaningfully support the page or file option without UUIDs. IMO when UUIDs are disabled, the link field should not allow these options.

Or it allows them for picking, but then absolute URLs get inserted and on editing, the url option is used.

**Comment by lukasbestle** [comment]
> Or it allows them for picking, but then absolute URLs get inserted and on editing, the url option is used.

That sounds like a manageable solution to me. The UX really isn't great, but everything else is a huge technical challenge just for those who need to disable UUIDs.

**Comment by afbora** [comment]
I think @distantnative solution makes sense 👍

**Comment by bastianallgeier** [comment]
I think that this will become a lot easier after this PR https://github.com/getkirby/kirby/pull/5531

**Comment by distantnative** [comment]
@bastianallgeier do you think with this PR there is a different solution than

> I don't think the link field can meaningfully support the page or file option without UUIDs. IMO when UUIDs are disabled, the link field should not allow these options.
> 
> Or it allows them for picking, but then absolute URLs get inserted and on editing, the url option is used.

**Comment by bastianallgeier** [comment]
@distantnative no, I just think it will be easier to implement now.
