### ISSUE TITLE
Textarea field converts numbers to unwanted ol list

### ISSUE THREAD

**Issue by MatthiasWeisz** [k-next/kirby#5500]
## Description
i've noticed a strange behaviour in textarea field: When entering a number with dot for a date in my case like '25.' kirby try to generate a ol list automatically thats annoying. I am not able to write "25. - 26. Juni" without messing up the frontend.

**Expected behavior**  
I've a button for lists so i expect lists only by use of that list-button. 

**Screenshots**  
<img width="261" alt="Bildschirmfoto 2023-08-24 um 12 16 14" src="https://github.com/getkirby/kirby/assets/66673653/2398681f-03f9-4de7-b4e1-5f64edc18aa9">

will output

<img width="253" alt="Bildschirmfoto 2023-08-24 um 12 15 50" src="https://github.com/getkirby/kirby/assets/66673653/d357428f-dec8-43af-9fc4-ca5e02673662">

## To reproduce
Type a dotted numbers in textarea like '25. - 26.' and output that with kirbytext() function.

**Comment by lukasbestle** [comment]
You can circumvent this behavior by escaping the first dot:

```md
25\. - 26. Juni
```
