### ISSUE TITLE
[v4] Move: Page not extendable

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#5504]
## Description
The move dialog shows a tree of all available pages of the projects. If a page contains only subpages with status 'draft', the tree of that page is not extendible. But if only one page is published/listed you could open that tree. Then all the subpages (also drafts) appears.

**Expected behavior**  
The tree should be extendible, even if no subpages are published/listed.
(And it would be nice, if only allowed pages for moving appears - put that's another story)

## To reproduce
1. Create a page.
2. Create a subpage (But leave it on draft)
3. Try to move another page into this created subpage. (The tree of the main page is not extendable)
4. Set the status of the subpage to listed
5. Try again (The tree of the main page is now extendable)

**Comment by afbora** [comment]
> So far, the dialog shows all available pages in the page tree. We are aware that this isn't the perfect UX to move pages yet. But we wanted to have this ready for the alpha and plan to simplify the process of picking a new parent

https://getkirby.com/releases/4.0/moving-pages

**Comment by distantnative** [comment]
I agree that while we cannot hide invalid pages/options, the toggle needs to appear also for pages that only have drafts as children.
