### ISSUE TITLE
Pages and subpages with long titles are overlayed in the panel’s breadcrumbs

### ISSUE THREAD

**Issue by maxime-pigeon** [k-next/kirby#5518]
## Description

When a page and a subpage both have a long title, the appear on top of each other in the panel’s breadcrumbs.

**Expected behavior**  

I suggest long titles should be shortened visually to avoid this.

**Screenshots**  

<img width="984" alt="Screen Shot 2023-08-28 at 4 35 02 PM" src="https://github.com/getkirby/kirby/assets/37006580/06ae884a-0924-40a1-b6b1-7fd14464be6c">

## Your setup
**Kirby Version**  

4.0 Alpha 5

**Console output**  

None

**Your system (please complete the following information)**
 - Device: MacBook Air M1
 - OS: Monterrey
 - Browser: Safari (same in Chrome, in Firefox the breadcrumps overflow the window)
 - Version: 16.5

**Additional context**

**Comment by bastianallgeier** [comment]
This has already been fixed. Please update to https://github.com/getkirby/kirby/releases/tag/4.0.0-alpha.7

**Comment by maxime-pigeon** [comment]
Hi Bastian,

I’ve updated to alpha 7, but the issue persists.

<img width="995" alt="Screen Shot 2023-08-29 at 9 13 08 AM" src="https://github.com/getkirby/kirby/assets/37006580/7bf37958-ac35-4db9-b3c7-08b20ff2c64d">

**Comment by bastianallgeier** [comment]
That's weird. I know that I took care of this. I wonder where we undid our own fix.

**Comment by distantnative** [comment]
@maxime-pigeon cannot produce this with beta.1

<img width="1344" alt="Screenshot 2023-09-09 at 10 34 33" src="https://github.com/getkirby/kirby/assets/3788865/411e3500-cc55-43c7-b958-8c2668f59067">

Maybe it was already fixed on the `v4/develop` branch, just after alpha.7

If it persists, please provide an example of page titles.

**Comment by afbora** [comment]
I can't reproduce the issue either.

**Comment by maxime-pigeon** [comment]
I just tested it with the new beta version and it seems to be fixed. Do note however that there’s no ellipsis on Safari. 

I’ll close the issue. Thank you.
