### ISSUE TITLE
url set in config doesn’t pick up the right protocol.

### ISSUE THREAD

**Issue by piotrfonte** [k-next/kirby#5532]
## Description

`url` variable doesn’t pick up the specified protocol. I have `url` variable set in my config file to `https://thefontes.com`. When I open the panel on https://thefontes.com/panel my media images are not loading.

**Expected behavior**  

I’d expect both the panel and the front-end site to look for assets via `https` and to load them just fine. Currently only the front-end site does.

## Your setup

4.0.0-alpha.7 although I noticed the same issue with v3.9

**Console output**

```Mixed Content: The page at 'https://thefontes.com/panel/site' was loaded over HTTPS, but requested an insecure image 'http://thefontes.com/media/pages/albums/trees/4f4e11b36f-1690769098/monster-trees-in-the-fog-1408x1126-crop.jpg/'. This request has been blocked; the content must be served over HTTPS.```

**Comment by bastianallgeier** [comment]
This is interesting. I cannot reproduce this. The panel should actually use the exact same settings as the frontend. Do you maybe use any plugins to create custom file urls?

**Comment by piotrfonte** [comment]
Nope, no plugins. Mine is a clean Kirby v4 starter install. However—I have to add—I’m running it on a non-standard (?) setup: AWS EC2, with a Load Balancer that does all the http to https redirect magic 🤔.

**Comment by distantnative** [comment]
@piotrfonte could you please share your full config?

**Comment by piotrfonte** [comment]
Sure:

`config/config.php`:

```
<?php

/**
 * The config file is optional. It accepts a return array with config options
 * Note: Never include more than one return statement, all options go within this single return array
 * In this example, we set debugging to true, so that errors are displayed onscreen.
 * This setting must be set to false in production.
 * All config options: https://getkirby.com/docs/reference/system/options
 */
return [
    'date.handler'  => 'intl',
    'languages' => true,
    'languages.detect' => true,
    'panel' => [ 'language' => 'pl' ],
    'routes' => [
        [
            // Refer to: https://getkirby.com/docs/cookbook/content/sitemap
            'pattern' => 'sitemap.xml',
            'action'  => function() {
                $pages = site()->pages()->index();
                // fetch the pages to ignore from the config settings,
                // if nothing is set, we ignore the error page
                $ignore = kirby()->option('sitemap.ignore', ['error']);
                $content = snippet('sitemap', compact('pages', 'ignore'), true);
                // return response with correct header type
                return new Kirby\Cms\Response($content, 'application/xml');
            }
        ],
        [
            'pattern' => 'sitemap',
            'action'  => function() {
                return go('sitemap.xml', 301);
            }
        ]
    ],
    'sitemap.ignore' => ['error'],
];
```

`config/config.thefontes.com.php`:

```
<?php

return [
    'cache' => [ 'pages' => [ 'active' => true, ] ],
    'debug' => false,
    'url' => [ 'https://thefontes.com', ]
];
```

**Comment by piotrfonte** [comment]
I’m sorry. This is now fixed. I reckon some set-up changes took a while to propagate on AWS. 🤔 Feel free to close.

**Comment by piotrfonte** [comment]
Sure. For a moment there I thought it magically fixed itself, but after a few hard-refreshes the issue is back. Here’s my config:

**config.php:**

```
<?php

/**
 * The config file is optional. It accepts a return array with config options
 * Note: Never include more than one return statement, all options go within this single return array
 * In this example, we set debugging to true, so that errors are displayed onscreen.
 * This setting must be set to false in production.
 * All config options: https://getkirby.com/docs/reference/system/options
 */
return [
    'date.handler'  => 'intl',
    'languages' => true,
    'languages.detect' => true,
    'panel' => [ 'language' => 'pl' ],
    'routes' => [
        [
            // Refer to: https://getkirby.com/docs/cookbook/content/sitemap
            'pattern' => 'sitemap.xml',
            'action'  => function() {
                $pages = site()->pages()->index();
                // fetch the pages to ignore from the config settings,
                // if nothing is set, we ignore the error page
                $ignore = kirby()->option('sitemap.ignore', ['error']);
                $content = snippet('sitemap', compact('pages', 'ignore'), true);
                // return response with correct header type
                return new Kirby\Cms\Response($content, 'application/xml');
            }
        ],
        [
            'pattern' => 'sitemap',
            'action'  => function() {
                return go('sitemap.xml', 301);
            }
        ]
    ],
    'sitemap.ignore' => ['error'],
];
```

**config.thefontes.com.php:**

```
<?php

return [
    'cache' => [ 'pages' => [ 'active' => true, ] ],
    'debug' => false,
    'url' => [ 'https://thefontes.com', ]
];
```

**Comment by afbora** [comment]
@piotrfonte Could try to move `url` config to `config.php` from `config.thefontes.com.php`?

````php
'url' => 'https://thefontes.com'
````

Let's see what's happen?

**Comment by piotrfonte** [comment]
Tried it just now—no luck. This is bizarre: it all works just fine when I launch a new Kirby Panel session in private mode. It’s only in my default Safari window that the issue appears. Tried disabling all browser extensions—it doesn’t have any effect.

**Comment by bastianallgeier** [comment]
One more try (sorry for the hassle). Could you try to move it to the env.php https://getkirby.com/docs/reference/system/options/url#url-override-for-the-production-deployment

**Comment by piotrfonte** [comment]
No worries. Added `env.php` to the production server. No luck.

**Comment by piotrfonte** [comment]
It may as well have to do something with my browser as it only happens in my default browser (Safari) session. Chrome works well both in normal and incognito. Even Safari works well in private mode. 🤷🏻

**Comment by afbora** [comment]
@piotrfonte Do you have the same issue with Safari on your phone or tablet? Or you can try from Safari on another computer or a friend's computer. That way we can see if it's a general bug or if it's just your Safari.

**Comment by piotrfonte** [comment]
Tried it from the iPad just now. Works fine. I’m using the fresh public beta of MacOS Sonoma, maybe something’s not right with the browser indeed. 🤷🏻

**Comment by bastianallgeier** [comment]
I'm honest with you, I have zero ideas how this is even possible.

**Comment by piotrfonte** [comment]
This is bizarre indeed. FYI, it works just fine now across all browser 🤔 No idea what changed. Must’ve really been something local. In any case, thanks for helping me investigate this and apologies for taking your time :(

**Comment by bastianallgeier** [comment]
Don't apologize. Such issues are incredibly annoying for you and for us. But even if they turn out to be a local problem, it's still important to talk this through together. If there's a chance that there's a problem on our end, we somehow need to find a solution. URL configuration is quite crucial after all.
