### ISSUE TITLE
[v4] Multiselect field always offers search & create features / cuts off long options

### ISSUE THREAD

**Issue by twiro** [k-next/kirby#5533]
## Description

1. [x] The multiselect field always shows a **search/filter**-field _(ignoring the blueprint-setting `search: false`)_
2. [x] The multiselect field always comes up with a misleading **create**-option whenever a search for a non-existing option is performed. _(This happens with both static and dynamic options, using the feature doesn't do anything at all.)_
3. [x] The multiselect field cuts of **options with long titles** due to its limited width.

**Expected behavior**  

1. The multiselect field should not contain a **create**-option by default. _(if at all, this would have to be extensively configurable)_
2. The multiselect field should not contain a **search/filter**-field if the blueprint is set to `search: false`.
3. The multiselect field should not **cut off options** as long as there is enough space left to show them properly.

**Screenshots**

![kirby-multiselect-bug-v4](https://github.com/getkirby/kirby/assets/870227/3373a78b-8268-46a1-b242-d49e77497f2b)

## To reproduce

1. Take the first example from the official **[multiselect-field-reference](https://getkirby.com/docs/reference/panel/fields/multiselect)** and try it out in the [latest alpha-release](https://github.com/getkirby/kirby/releases/tag/4.0.0-alpha.7).
2. Add/Remove the `search: false`-setting to the blueprint.
3. Try to use the **create**-option.
4. Try out some options with really long names

## Your setup

**Kirby Version:**   [4.0.0-alpha.7](https://github.com/getkirby/kirby/releases/tag/4.0.0-alpha.7).

**Comment by bastianallgeier** [comment]
Thanks for the issue. When there's more than a single problem, it's super helpful for us if you break it down into separate issues. Then we can check them off individually when a fix is ready. I've turned this now into a todo list and might also break it down some more later.

**Comment by twiro** [comment]
> Thanks for the issue. When there's more than a single problem, it's super helpful for us if you break it down into separate issues. Then we can check them off individually when a fix is ready. I've turned this now into a todo list and might also break it down some more later.

Makes sense and I will try better next time – this was my first issue report in this repo.

And thank _you_ for the quick response and fixes and great work in general – Version 4 feels great so far!
