### ISSUE TITLE
[v4] Shortcut for deleting a block overwrites Windows shortcut for deleting a word

### ISSUE THREAD

**Issue by bezin** [k-next/kirby#5534]
## Description
CTRL+BACKSPACE is an OS-wide shortcut for deleting the last word in a text field. It works across all Windows-application.

**Expected behavior**  
When I edit text in a Kirby text block, I expect the exact same behavior described above.

**Actual Behavior**
Kirby will ask me, if I really would like to delete this text block. 

## To reproduce

1. Add a text block to any page
2. Start typing text in this text block
3. Press CTRL+BACKSSPACE on a Windows machine

## Your setup
**Kirby Version**  
Kirby 4 Alpha 7

**Your system (please complete the following information)**
 - OS: Windows 11 Pro

**Comment by bastianallgeier** [comment]
I think we could check for a focused input and ignore the shortcut here. @distantnative what do you think?
