### ISSUE TITLE
[v4] Button group: collapsed layout - wrong styling when button prepends dropdown

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#5563]
<img width="276" alt="Screenshot 2023-09-03 at 02 00 59" src="https://github.com/getkirby/kirby/assets/3788865/28faccdd-0fe4-48e6-b280-6a02c317fa98">

**Comment by bastianallgeier** [comment]
Does this use k-dropdown as wrapper? You should really just remove that one in this case. We no longer need the wrapper with the positioning JS and I really think that we should deprecate it
