### ISSUE TITLE
[v4] Support for php8.3

### ISSUE THREAD

**Issue by modufolio** [k-next/kirby#5568]
## Description

In a few months php8.3 will be released, would be nice if Kirby 4 would support it.

This is the first bug I found for php8.3 

Optional parameter $lang declared before required parameter $fields is implicitly treated as a required parameter

kirby/src/Content/ContentStorage.php

```
/**
     * Creates a new version
     *
     * @param string $lang Code `'default'` in a single-lang installation
     * @param array<string, string> $fields Content fields
     */
    public function create(
        string $versionType,
        string|null $lang = null,
        array $fields
    ): void {
        $lang = $this->language($lang);
        $this->handler->create($versionType, $lang, $fields);
    }
```

## To reproduce
use php8.3

## Your setup
**Kirby Version**  
4.0.0-alpha.7

**PHP**
8.3

**Comment by afbora** [comment]
> Optional parameter $lang declared before required parameter $fields is implicitly treated as a required parameter

As far as I know, this already deprecated in 8.0. Also currently related lines that you referenced in v4:
https://github.com/getkirby/kirby/blob/4.0.0-beta.1/src/Content/ContentStorage.php#L102-L109
