### ISSUE TITLE
[v4] Missing Panel Tabs in SimpleStats Plugin

### ISSUE THREAD

**Issue by zeljkovorel** [k-next/kirby#5571]
Link to plugin: https://github.com/Daandelange/kirby3-simplestats

- Kirby Version: 4.0.0-alpha.7
- SimpleStats Version: 0.6.2-beta

Clicking initially the "Simple Stats" in the left menu, it shows "Information" in the top menu
![image](https://github.com/getkirby/kirby/assets/88711468/2f5da88d-d83c-4362-ba52-20976e151f5a)

Clicking "SimpleStats" in the top menu, it changes "Information" to "Page Visits" - but page did not change:
![image](https://github.com/getkirby/kirby/assets/88711468/700ec6ab-e006-41b9-a93b-14fb73c14294)

---------------------------------------
Running Version
- Kirby Version: 3.9.6.1
- SimpleStats Version: 0.6.2-beta

![image](https://github.com/getkirby/kirby/assets/88711468/27fc2136-aa17-49c7-9036-8a6174e595b1)

**Comment by afbora** [comment]
Moved to https://github.com/getkirby/kirby/issues/5187
