### ISSUE TITLE
[v4] Missing selected item indicator in move page dialog

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5573]
## Description

Actually `Blog` item selected but there is no visible indicator

![image (26)](https://github.com/getkirby/kirby/assets/3393422/923c6179-a62f-4101-82bd-444027b92ac5)

## Your setup
4.0.0-beta.1

**Comment by distantnative** [comment]
@bastianallgeier what was the motivation to complete remove the `identifier` prop from PageTree?
Cause I think that broke this - as the move dialog always wants to use the id, even when uuid support is present.

**Comment by bastianallgeier** [comment]
I completely missed this issue. I think the idea was to decide this on the backend instead. But I need to have a closer look.
