### ISSUE TITLE
[v4] Color field HSL `deg|rad|grad|turn` detection

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5580]
## Description

https://github.com/getkirby/kirby/assets/3393422/5dd6aaad-8e3e-4d00-933d-6459d3aa02b3

## Your setup
4.0.0-beta.1

**Comment by distantnative** [comment]
I'm tempted not to support `rad` and `turn` just because their decimal markup really adds more complexity to the already hard regex - and I don't think their usage is very common.

@afbora to my understanding `150rad` is also not a real value as radians would be between 0 and 6.28319.

**Comment by afbora** [comment]
I don't have knowledge about color formats. I can't comment about we need to support some formats or not.
