### ISSUE TITLE
[v4] _set method should have the same parameter names in all the types of collections

### ISSUE THREAD

**Issue by modufolio** [k-next/kirby#5597]
## Description

_set method should have the same parameter names in all the types of collections

**Toolkit Collection**
public function __set(string $key, $value): void

**CMS Collection**
public function __set(string $id, $object): void

## Fix

Cms/Collection

Line: 75

```
public function __set(string $key, $value): void
{
$this->data[$key] = $value;
}

```

## Your setup
**Kirby Version** 
4.0.0-beta.1

**Comment by distantnative** [comment]
@modufolio is this your opinion or does it cause actual errors?

**Comment by modufolio** [comment]
PHPstorm have me a warning about this; for now this is more a good coding practice.

**Comment by distantnative** [comment]
It'd be also an extra breaking change, that's why I'm a bit hesitant to just change it.

**Comment by modufolio** [comment]
I think we should move to this to v5
