### ISSUE TITLE
[v4] Remove users from collection list for performance.

### ISSUE THREAD

**Issue by modufolio** [k-next/kirby#5607]
## Description

When using the collection helper, the user collection is loaded too.
```
	public function collection(string $name, array $options = [])
	{
		return $this->collections()->get($name, array_merge($options, [
			'kirby' => $this,
			'site'  => $site = $this->site(),
			'pages' => $site->children(),
			'users' => $this->users()
		]));
	}
```

$notes = collection('notes');

When you have 1000 users in the user collection, you want to avoid using this helper at the moment or use a custom app class.

## Fix

```
	public function collection(string $name, array $options = [])
	{
		return $this->collections()->get($name, array_merge($options, [
			'kirby' => $this,
			'site'  => $site = $this->site(),
			'pages' => $site->children(),
		]));
	}
```

## Your setup
**Kirby Version**  
4.0.0-beta.1

**Comment by distantnative** [comment]
I would suggest to remove `pages` as well as `users`. It's a breaking change, so 4.0 would be a good time. Via `$site` the collection could still access those but we don't create them if not needed.
