### ISSUE TITLE
[v4-beta.1] Can not create child page with a page model that differs from the parent page

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#5617]
## Description
Using `$page->createChild()` to create a child page will throw a TypeError when the page created has a different page model than the parent page.

`TypeError: Kirby\Cms\Page::createChild(): Return value must be of type ParentPageModelPage, ChildPageModelPage returned`

**Expected behavior**  
Succesfull creation of the child page.

## To reproduce

Create a custom page model 
```php
class TestingPage extends Kirby\Cms\Page {}
```

Get a page instance and try to create a child page with a different page model than the parent page.

```php
$page = page('some-page-id)
$page->createChild([
    'template'	=> 'testing',
    'isDraft'   => false,
    'slug'      => Str::slug("New Child Page"),
    'content'   => [
        'title' => 'New Child Page'
    ]
]);
```
This will throw the TypeError

## Your setup
**Kirby Version**  
4-beta.1

Php 8.1.22

**Additional context**  
Kirby 4-beta.1 introduced a return type of `static` to  PageActions::createChild().
https://github.com/getkirby/kirby/blob/bc43ab0bc3cf3bebe7ad0116b484ca5470210260/src/Cms/PageActions.php#L539

This should probably just be `Kirby\Cms\Page` to allow the creation of child pages with different page models

**Comment by ovenum** [comment]
Looking further into PageActions.php, the problem seems to exist for every action that is returning a new Page instance and allows a template name to be passed as option

**Comment by afbora** [comment]
Duplicated of https://github.com/getkirby/kirby/issues/5586
