### ISSUE TITLE
[v4] Don’t override fill color for custom panel icon

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#5619]
## Description
Panel icons with custom fill color are always displayed with a black fill.

```js
panel.plugin('junohamburg/panel-icons', {
  icons: {
    'color-green': '<rect x="2" y="2" width="12" height="12" fill="green" />',
    'color-red': '<rect x="2" y="2" width="12" height="12" fill="red" />'
  }
});
``` 

![Screenshot](https://github.com/getkirby/kirby/assets/77532479/2ebdf6a8-38ed-4dfc-83b3-d891d0682527)

There is a workaround by replacing `fill="green"` with `style="fill: green"`. But it would be nice if custom panel icons worked like in Kirby 3.

## Your setup
**Kirby Version**  
v4-beta.1

**Comment by distantnative** [comment]
Simply removing this rule isn't an option as then the core icons won't receive color anymore. Does the issue remain when changing it to

```css
:where(svg) {
	fill: currentColor;
}
```
?

**Comment by tobimori** [comment]
I think that introduces a different issue, and that is setting the background of the svg to currentcolor. I'd say the core icons should've rather hardcode `fill="currentcolor"`.

**Comment by SebastianEberlein-JUNO** [comment]
Changing the panel css to 

```css
:where(svg) {
  fill: currentColor;
}
```
solves the issue. I tested it in Safari, Firefox and Chrome on macOS.

Also wrapping the `<rect>` in a `<svg>` like this, does not add a background color:

```js
panel.plugin("junohamburg/panel-icons", {
  icons: {
    "color-green": '<rect x="2" y="2" width="12" height="12" fill="green" />',
    "color-red": '<svg viewBox="0 0 16 16"><rect x="2" y="2" width="12" height="12" fill="red" /></svg>',
  },
});
```
