### ISSUE TITLE
[v4] Plugin assets no longer publicly available

### ISSUE THREAD

**Issue by SebastianEberlein-JUNO** [k-next/kirby#5620]
## Description
My test plugin has the following files:

`site/plugins/test/index.php`
```php
<?php Kirby::plugin('junohamburg/test', []); ?>
```

`site/plugins/test/assets/style.css`
```css
html {
  font-family: sans-serif;
}
```

I load the `style.css` in the `<head>` like this:

```html
<?php $mediaUrl = Kirby::plugin('junohamburg/test')->mediaUrl(); ?>
<link rel="stylesheet" href="<?= $mediaUrl ?>/style.css">
```

In Kirby 3 and Kirby 4 alpha the style.css was copied / linked to the media folder. 
In the Kirby 4 beta the file is no longer copied / linked. The browser shows a 404 error for `http://localhost:8888/media/plugins/junohamburg/test/style.css `

## To reproduce
1. Download plainkit
2. Add test plugin
3. Update to Kirby 4 beta, delete `media` folder

## Setup
**Kirby Version**  
Kirby v4-beta.1

**System**
 - OS: macOS 13.5.2
 - PHP: 8.2.10
 - Tested in Valet and PHP's built-in server

**Comment by afbora** [comment]
I can reproduce the issue and @distantnative I've reverted your `Plugin assets extension` PR and works great: https://github.com/getkirby/kirby/pull/5557

**Comment by rasteiner** [comment]
I kinda feel responsible for the issue. The PR introduces the possibility to serve files from anywhere in the plugin, "assets" being just a naming convention. So the asset path is now relative to the plugin root, this means that the "assets" part of the path has to be included:

```
http://localhost:8888/media/plugins/junohamburg/test/style.css 
becomes:
http://localhost:8888/media/plugins/junohamburg/test/assets/style.css 
``` 

I'm not sure if this is a planned breaking change, or if the default "assets handler" should have mirrored exactly the old behaviour.

**Comment by distantnative** [comment]
@rasteiner I think that's an oversight from us, we should try to mimic the old behavior to not have such a breaking change

**Comment by distantnative** [comment]
@rasteiner @SebastianEberlein-JUNO Could you check if the following change fixes it for you: 

in `kirby/src/Cms/Plugin.php` change the line https://github.com/getkirby/kirby/blob/v4/develop/src/Cms/Plugin.php#L109 to

```php
$assets[$asset] = $path;
```

**Comment by SebastianEberlein-JUNO** [comment]
@distantnative Yes, changing the line fixes the problem.
