### ISSUE TITLE
[v4] Problem deleting images in pages/files field

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5623]
## Description
There is an issue when deleting images from the gallery block. It seems like the index/key of the image that should be removed is not correct. The `gallery.yml` from the GIF has been slightly modified, but the problem persists when using the unchanged default gallery block.

I also tested it in a fresh [startkit](https://github.com/getkirby/starterkit) using [4.0.0-beta.1](https://github.com/getkirby/kirby/releases/tag/4.0.0-beta.1)

![gallery_block](https://github.com/getkirby/kirby/assets/10027897/3fac6869-5b5e-4223-a3a9-32cb5c835930)

## Your setup
**4.0.0-beta.1**  

**Console output**  

**Your system (please complete the following information)**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox 118

**Comment by afbora** [comment]
Actually this issue related with picker collection (files/pages field).
