### ISSUE TITLE
[v4] Multiselect field should indicate that the user can scroll

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5627]
## Description
This is a multi select field that has so many entries that you can scroll.
![CleanShot 2023-09-14 at 12 29 18@2x](https://github.com/getkirby/kirby/assets/29142128/4b6612ab-bd80-448c-8948-3835323fc4c3)

However, on first glance, it doesn't look like you can scroll.

A better solution would be to cut the 11th item like so:
![CleanShot 2023-09-14 at 12 31 33@2x](https://github.com/getkirby/kirby/assets/29142128/22152f68-28a1-4d9e-b6cb-f5b72f9b5797)

Using v4 beta.1

**Comment by afbora** [comment]
@tobimori Which browser do you use?

**Comment by tobimori** [comment]
Chrome 116

**Comment by afbora** [comment]
For me Chrome 116 🤔 

![image (27)](https://github.com/getkirby/kirby/assets/3393422/232379e5-22fc-4baa-ac22-69367edf83ff)

**Comment by tobimori** [comment]
yes, that's the current behaviour. the second screenshot is imo the behaviour how it should be so the user knows they can scroll. there is no scroll bar on macOS.

**Comment by afbora** [comment]
My personal humble opinion; I don't know how logical it is to cut the last item when there already seems to be a scroll bar.

**Comment by tobimori** [comment]
The scrollbar is only visible on Windows devices (and maybe Linux) phones usually don't have a scrollbar as well as macOS.

**Comment by lukasbestle** [comment]
I think making the list box slightly larger to cut off the 11th item is a good cross-browser and cross-OS solution. It doesn't break anything on Windows while it really helps on macOS.

**Comment by luxuryluke** [comment]
Love this solution.
