### ISSUE TITLE
[v4] Panel margins on Firefox/Windows wrong

### ISSUE THREAD

**Issue by mit-stauffer** [k-next/kirby#5632]
## Description
The panel lacks outside margins in the right window every screen size.

**Expected behavior**  
The panel should have the same margins as in other browsers.

**Screenshots**  
Expected (Chrome): 

![expected](https://github.com/getkirby/kirby/assets/27286029/795be3ce-c7ad-44d2-b2e0-368fcb1443b7)

Not Expected (Firefox): 

![not-expected](https://github.com/getkirby/kirby/assets/27286029/9778f0e0-cb5c-4ff3-bc34-19baeefd9703)

## Your setup
**Kirby Version**  
Latest starterkit (3.9.6.1) with Kirby 4.0.0-beta.1

Firefox 102.0.1 on Windows 10 (19045.3448)

**Comment by afbora** [comment]
I can't reproduce the issue with Firefox 117.0.1 & Windows 10

**Comment by mit-stauffer** [comment]
I tried the panel on a different webserver to rule out anything related to that - same result.
I try some different machines to replicate.

**Comment by afbora** [comment]
I think your issue about Firefox version since v4 use `container-query-units`:
https://caniuse.com/css-container-query-units

**Comment by mit-stauffer** [comment]
In a newer Firefox the issue is gone. Thanks!

**Comment by SamuelRiversMoore** [comment]
+1 

Same problem on Firefox 102 ESR (default Firefox on Debian).

It seems the `--main-padding-inline` css var is not working as intended. 
 
More precisely if I replace the `var(--cq-cqw-d9e4ef39)` in `--main-padding-inline: clamp(var(--spacing-6),calc(5*var(--cq-cqw-d9e4ef39)),var(--spacing-24));` by an absolute value, it works.

**Comment by lukasbestle** [comment]
v4 relies on container queries. This unfortunately means that we need to raise the browser requirements. Firefox supports container queries since v110.

@distantnative Do we already document this as a breaking change somewhere? Can't find it at the moment.

**Comment by distantnative** [comment]
@lukasbestle No the browser requirements we wanted to check towards the end when we really know what features are needed
