### ISSUE TITLE
Reponse-Headers from .htaccess not being set, unless also set in config.php [3.9.6.1]

### ISSUE THREAD

**Issue by FynnZW** [k-next/kirby#5658]
## Description
This is regarding the security update since [version 3.9.6](https://github.com/getkirby/kirby/releases/tag/3.9.6) 
I have updated the `.htaccess` with the new headers, just like [this](https://github.com/getkirby/starterkit/commit/db49a55c00e7bccea28556a98429130e69ce6184), plus an additional for iframes:  `Header set X-Frame-Options "SAMEORIGIN"`

But those headers were not sent. I was only able to get them by also setting the headers in the `config.php`, like here:
https://github.com/getkirby/getkirby.com/blob/main/site/config/config.php#L3-L5
```php
header('X-Frame-Options: sameorigin');
header('X-XSS-Protection: 1; mode=block');
header('X-Content-Type-Options: nosniff');
```
Is this a bug? Or is something wrong with my server config?
If it's not, and this is always necessary, it would be good to document this (e.g. also add those config-header to the starter kit repo).

**Your system (please complete the following information)**
 - Kirby version: 3.9.6.1
 - Server: Apache
 - PHP: 8.0.29

**Comment by lukasbestle** [comment]
Thanks for your report. Could you please check if the following works:

```apache
Header always set X-Frame-Options "sameorigin"
Header always set X-XSS-Protection "1; mode=block"
Header always set X-Content-Type-Options "nosniff"
```

I've added the optional "always" flag that seems to be necessary for CGI responses like dynamic PHP responses. Our default `.htaccess` doesn't need this flag because we also set the content type and nosniff headers in the CMS core when they are needed for a file response. But for your custom headers it's a different story as you want them to be applied in addition to Kirby's.

**Comment by FynnZW** [comment]
Thanks, but that does not change it, still not working.

**Comment by lukasbestle** [comment]
Do you have `mod_headers` enabled in your Apache config? You can verify this by using the `Header set` lines outside of the conditional block. If that gives you an "Internal Server Error", you need to enable `mod_headers`.

**Comment by FynnZW** [comment]
Yes, it is enabled, putting them outside the conditional does not create an 500 error.

It really seems to have something to do with CGI. Just found this on our hosters page:
https://wissen.profihost.com/wissen/artikel/apache2-header-setzen/ 
And if I set them via the `header`-function in Kirbys `config.php`, it works! - so I'll just do that and leave a comment in my `.htaccess` pointing that out. 
Is this something specific to my server/hoster, or does Kirby always use CGI and headers always have to be set this way? (Sorry, I'm mostly a frontend dev, don't know much about CGI).

**Comment by lukasbestle** [comment]
`Header always set` should even work for CGI responses. I don't have more ideas why it doesn't work in your setup unfortunately.

But setting headers in `config.php` is certainly an alternative if you want those headers to be used for any and all responses that Kirby serves directly. You still need to set the headers in Apache for static responses.

On the topic of CGI: PHP can be used in different ways, e.g. also as an Apache module. But that's quite uncommon. The most common way is FastCGI, which is a variant of CGI.

I'm closing this issue as the default headers in the `.htaccess` are only needed for static responses and those are unaffected by the CGI issue.

**Comment by FynnZW** [comment]
Thanks for the explanation!
