### ISSUE TITLE
[v4] Changing the page slug via the panel results in content loss in writer fields

### ISSUE THREAD

**Issue by alfatiharufa** [k-next/kirby#5659]
## Description
Changing the slug of an existing page via the panel results in content loss in writer fields. It is possible to retrieve the content of the writer fields back by clicking "revert", but this will then revert any other fields modified prior to the slug.

**Expected behavior**  
Changing the slug shouldn't affect writer fields.

**Screenshots**  
![kirby-4-slug-writer](https://github.com/getkirby/kirby/assets/11985948/acf7730d-0c25-4a83-b217-31c50183169e)

## To reproduce

1. Download Starterkit https://github.com/getkirby/starterkit
2. Update Kirby to v4.0.0-beta.1
3. Modify the slug of a page containing a writer field
4. Notice the writer field getting empty

## Your setup
Kirby 4.0.0-beta.1
PHP 8.2.5

**Console output**  
None

**Your system (please complete the following information)**
 - MacBook Pro
 - OS: macOS 11.7.10
 - Bowser: Chrome 117.0.5938.62

**Additional context**  
The bug occurred in Kirby v4.0.0-alpha.7 and in other project configurations as well. The Starterkit has been used for the demo.

**Comment by afbora** [comment]
I can't reproduce the issue. Does the browser console show an error?

**Comment by alfatiharufa** [comment]
There is no error logged to the browser console. 

I ran a couple more tests with an updated PHP version, still the same. The problem doesn’t occur with MAMP or the production server, on the other hand. 

So there seems to be an issue with my development server configuration I still need to figure out.

Will close the issue.
