### ISSUE TITLE
[v4] Block with missing blueprint replace the whole field with an error.

### ISSUE THREAD

**Issue by vincentrouleau** [k-next/kirby#5660]
It's not uncommon for blocks to be added or removed from a project, but the current behaviour replaces the whole block field with an error message if any of the blocks does not have a BP. The only way to fix this is to A: Add a temporary BP with the same name, delete the blocks, then remove the "fake" BP. Or B: Access the content folder and delete the related JSON.

**Expected behavior**  
Kirby 3 used to display the blocks but you were just unable to edit them (you could still copy, delete and hide them).

**Screenshots**  
<img width="1150" alt="Screenshot 2023-09-18 at 4 52 38 PM" src="https://github.com/getkirby/kirby/assets/11572524/71ab95c5-eaa9-4209-acbd-cbf539664413">

## Setup
**K4 beta 1**

**Comment by afbora** [comment]
@distantnative I've tested and this issue coming from `catch` to `finally` change in here:
https://github.com/getkirby/kirby/commit/7bb02188507296c4f29d01f73239b94c6c5145ab#diff-3419d182078e2c6e82aedd5cad3056116af7aca4bd1d96967543095b0eebd39bL63-L68

It seems that the error is not caught without the `catch` block. I think we should revert only this `catch > finally` change.
