### ISSUE TITLE
[v4] Writer field: confusing link button with no selection

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#5661]
## Description
When you click the link button in a Writer field without selecting text it results in an empty/invisible link. Combined with there being a "Title" field it's very confusing.

![link](https://github.com/getkirby/kirby/assets/7975568/4284df7c-f76a-4f03-a82b-5572c759ea19)

**Expected behavior**  
A fallback text with the URL should be used.

## To reproduce

1. Add a writer field
2. Don't select any text
3. Click on the link button

## Your setup
**Kirby Version**  
4.0.0-beta.1

**Your system (please complete the following information)**
 - OS: macOs 13.5.1
 - Browser: Arc
 - Version: 1.8.1

**Comment by afbora** [comment]
I think link and email is a `mark`, not a `node`. So it applies to inline/selected content. Not sure if we can use it as both mark and node 🤷‍♂️
