### ISSUE TITLE
[v4] Quote block: turning off inline mode breaks Panel

### ISSUE THREAD

**Issue by bensanlau** [k-next/kirby#5662]
## Description

When setting `inline` mode to `false` in the Quote block to enable multi line, it breaks the Panel.
The error reads:
```
Cannot read properties of null (reading 'destroy')
```

**Screenshots**  
![Screen Recording 2023-09-19 at 15 37 36](https://github.com/getkirby/kirby/assets/53568912/b5217c6e-a6b6-4f0f-aba9-2dd8ca6cc734)

**Expected behavior**  

Panel to continue working, and ability to add multiple paragraphs in the quote block.

## To reproduce

1. Using starterkit + v4, and go to Panel page with Quote block (i.e. About us)
2. Create a new file under `site/blueprints/blocks/quote.yml`
3. Paste blueprint from [docs page](https://getkirby.com/docs/reference/panel/blocks/quote#default-files__blueprint).
4. Set `inline:false` on either `text` or `citation` field. Alternatively, remove or comment out the line.
5. Refresh Kirby Panel to see error.

## Your setup
**Kirby Version**  

4.0.0-beta.1
PHP 8.2.7
npm 9.5.1
node v18.16.0

**Console output**  

**Your system (please complete the following information)**
 - OS: macOS 13.5.2
 - Browser: Chrome
 - Version: 116.0.5845.179

**Additional context**

**Comment by afbora** [comment]
I can't reproduce the issue on PHP 8.1.23 & 4.0.0-beta.1 & Windows 10 & Chrome 117.

**Comment by distantnative** [comment]
Can't replicate this either. Pretty much same setup as @bensanlau  – are you sure it's a completely fresh starter kit with no other customizations?

**Comment by bensanlau** [comment]
Yes, it was a fresh starter kit. I've also tried a fresh plainkit.
Steps taken here: 
git cloned plainkit, downloaded v4 from the [Try now button](https://getkirby.com/releases/4.0), and replaced the entire kirby/ directory in the project with the downloaded folder (and renamed from `kirby-4.0.0-beta.1` to `kirby`).
(Also cleared the /media/panel cache, and restarted the server)

Also switched to PHP 8.1.23 and it's the same result.
The error message differs in different browsers:
Chrome 117: `Cannot read properties of null (reading 'destroy')`
Safari 16.6: `null is not an object (evaluating 'this.editor.destroy')`
Firefox 117: `this.editor is null`

Would I need to re-compile or clear something?

**Comment by afbora** [comment]
@bensanlau Now I can reproduce the issue with your steps. Also the issue seems fixed in beta.2 for me. Could you try beta.2/development branch? Here beta.2 files: [kirby.zip](https://github.com/getkirby/kirby/files/12719708/kirby.zip) You don't need to build dist files. Just replace `kirby` folder and delete the media directory. Let see what's happen.

**Comment by bensanlau** [comment]
@afbora Thank you for this! 
Yes, I can now confirm the beta2 files work as expected 👍 
Will close this issue and wait for beta2!
