### ISSUE TITLE
[v4] Error in Page Creation Dialog in Page with Custom Model

### ISSUE THREAD

**Issue by rottstegge** [k-next/kirby#5674]
## Description
I have a page using a custom Page Model called ChallengePage. Inside that page I there is a pages section set up to create child pages with a template of `surveyresponse`. When using the Challenge Pages page creation dialog, the panel throws an error reading `Kirby\Cms\Page::createChild(): Return value must be of type ChallengePage, Kirby\Cms\Page returned`. Once I cancel the dialog and refresh the page, I can see that the page creation was successful although the error was thrown.

**Expected behavior**  
The child page should be created without an error being thrown.

**Screenshots**  
<img width="433" alt="image" src="https://github.com/getkirby/kirby/assets/25906628/1856a4ea-39fb-4789-a338-8bcd48fb11c2">

## Your setup
**Kirby Version**  
Kirby 4.0 beta 1

**Comment by afbora** [comment]
@rottstegge Could you paste your `ChallengePage::createChild()` method, please?

**Comment by rottstegge** [comment]
My ChallengePage Model does not actually contain any method named `createChild()`

**Comment by afbora** [comment]
Oh, ok. So this issue is duplicated of https://github.com/getkirby/kirby/issues/5586 and will be fixed in beta.2 Thanks for the report.
