### ISSUE TITLE
[v4] Link field allows selection of 'site'

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5708]
## Description
![CleanShot 2023-09-28 at 02 15 29@2x](https://github.com/getkirby/kirby/assets/29142128/6b1aa693-de49-4b56-87e5-8bfcd41f39c0)
![CleanShot 2023-09-28 at 02 15 14@2x](https://github.com/getkirby/kirby/assets/29142128/fb8d7ca5-7e62-4f58-88d8-a4dfcd98e3fa)

Page selector of Link field allows selection of site. UUID/Internal URL doesn't get resolved with `->toUrl()`. Selection shouldn't be possible imho as we can already select the home page. 

## Your setup
**Kirby Version**  v4.0-beta.1

**Comment by bastianallgeier** [comment]
This is already fixed in beta.2

**Comment by afbora** [comment]
@bastianallgeier This is a different case. @tobimori thinks that the `Site` item should not be selectable.

**Comment by bastianallgeier** [comment]
Sorry for being too quick about this. I guess it makes sense to also disable the button.
