### ISSUE TITLE
[v4] Page creation with custom models is not possible

### ISSUE THREAD

**Issue by modufolio** [k-next/kirby#5718]
## Description

In my setup i've a Photography model that has Album model as child.

With 4.0.0-beta.1, I can't create a new album anymore.

I'm getting the following error:

```
Kirby\Cms\Page::createChild(): Return value must be of type PhotographyPage, AlbumPage returned
```

## To reproduce

1. clone https://github.com/modufolio/Kirby-Appkit
2. create a new album page

**Comment by modufolio** [comment]
https://github.com/modufolio/Kirby-Appkit/issues/6

**Comment by distantnative** [comment]
Please try beta.2 - this should be fixed
