### ISSUE TITLE
[V4] Make it visually clear which localization the panel user is working on/with

### ISSUE THREAD

**Issue by dviate** [k-next/kirby#5719]
## Description
Not really a bug, but more like an enhancement so feel free to give it the appropriate tag(s)...

Currently, when a multi-language setup is active the current language, NL in this case, looks like this. It's just a small visual change to make it more clear which language a panel user is working on when editing a page.

![Current situation](https://github.com/getkirby/kirby/assets/2322938/eae6498f-661f-4dd6-a3b6-838b98be9419)

My idea, just made by editing in the console looks like this:

![New situation](https://github.com/getkirby/kirby/assets/2322938/e8584e96-3539-4ce3-8a9e-386906260de9)

**Comment by dviate** [comment]
However, now that I made the sample above it also seems to be achievable by writing some SCSS for the panel itself:

```
div[data-language] {
	&[data-language="nl"] {
		--flag: "🇳🇱";
	}
	&[data-language="en"] {
		--flag: "🇬🇧";
	}
	&[data-language="es"] {
		--flag: "🇪🇸";
	}
	.k-languages-dropdown {
		> .k-button {
			position: relative;
			&:before {
				content: var(--flag);
			}
		}
		.k-button-icon {
			.k-icon {
				display: none;
			}
		}
	}
}
```

**Comment by distantnative** [comment]
Country flags are usually a bad approximation for a language that often is spoken in multiple countries. It might work for your individual project, but finding a general standard, e.g. even just for English, isn't practical.

**Comment by dviate** [comment]
Aah you mean Spanish being spoken in Spain, but also in Mexico and Argentina. I get your point, it doesn't apply to my individual project. I'll close this ticket, and thanks for the ultra quick reply @distantnative! 👍🏽

**Comment by distantnative** [comment]
Yes or English: UK, USA, Australia, South Africa, India...
