### ISSUE TITLE
Upload of the identical file should not change the UUID

### ISSUE THREAD

**Issue by thin-k-design** [k-next/kirby#5730]
## Description
So normally, if you try to upload a file with the same name, you get an error like "The file with the name 'myfile.txt' already exists". Which is the behaviour you would expect to avoid replacing any file by mistake. 
If you try to upload exactly the same file, it is allowed. Which should not be really a problem as it is the same file. But the uuid of the file is also changed and therefore any field linking to this file become empty.

**Expected behavior**  
Either the same file should get the same error, that it already exists, or the uuid should not be changed at all.

## To reproduce
1. Go to any files field of files section
2. Upload a file
3. Note down the uuid in the content folder
4. Upload the same file
5. Notice that the uuid in the content folder has changed

## Your setup
I tried Kirby v3.6, v3.9 and v4.0-beta-2

**Your system (please complete the following information)**
 - OS: Windows
 - Browser: Chrome
 - Version: latest

**Comment by distantnative** [comment]
I'd say the UUID shouldn't be changed in this case.

**Comment by bastianallgeier** [comment]
I agree. The concept behind it was that this is basically treated like unchanged content. Just like when you submit the filename dialog without changing the name.

**Comment by afbora** [comment]
I've implemented an idea in https://github.com/getkirby/kirby/pull/5781. Needs your reviews, please.
