### ISSUE TITLE
[v4] Layout selector doesnt show grid when using `1/2 1/2`

### ISSUE THREAD

**Issue by mountbatt** [k-next/kirby#5734]
## Description

When i use a layout field in v4 beta and add some 1/2 1/2 grid the preview in the panel doesnt show a grid-divider. I think its a CSS bug cause there is a grid available.

![Bildschirmfoto 2023-10-06 um 13 15 52](https://github.com/getkirby/kirby/assets/2411246/977dac26-f1c8-422d-88ff-225a65ad7cac)

![Bildschirmfoto 2023-10-06 um 13 14 20](https://github.com/getkirby/kirby/assets/2411246/5ba78e7f-6ca9-4124-9636-4488eb0a779b)

![Bildschirmfoto 2023-10-06 um 13 18 01](https://github.com/getkirby/kirby/assets/2411246/0200b62c-7b99-402e-b726-52f2ad99edc0)

**Comment by afbora** [comment]
I can't reproduce the issue on beta.2 & Chrome. Which Kirby and browser version do you use?

![image](https://github.com/getkirby/kirby/assets/3393422/9a3e6326-e80c-4d90-bfe0-a983e875673a)

**Comment by mountbatt** [comment]
@afbora Thanks for your fast reply. I am on 4.0.0-beta.2 and latest Chrome. 
Its funny cause when I change the available layouts always again the "second" layout gets "blank".

![Bildschirmfoto 2023-10-06 um 13 30 11](https://github.com/getkirby/kirby/assets/2411246/014d083b-dcc5-4f2c-9b8e-75586851e99a)

![Bildschirmfoto 2023-10-06 um 13 30 04](https://github.com/getkirby/kirby/assets/2411246/5a59dd25-136e-4b42-8b34-ecb6d49e9c59)

**Comment by mountbatt** [comment]
will set it to the following, then it looks correct … 
![Bildschirmfoto 2023-10-06 um 13 33 08](https://github.com/getkirby/kirby/assets/2411246/7003ece7-0992-4a3e-9c75-2ef8aae9f480)

**Comment by afbora** [comment]
Still can't reproducible for me. Do you have using custom panel css or plugins?

**Comment by mountbatt** [comment]
@afbora Thanks for checking. Will try to disable plugins. Custom CSS is not available.

**Comment by distantnative** [comment]
@mountbatt when you give us info on plugins, custom code please also include whether chrome on Mac or windows.

**Comment by mountbatt** [comment]
@distantnative @afbora Thanks for trying to help! 
I disabled all plugins and custom code but it doesnt help for Chrome! 
In Safari the divider on 1/2 1/2 is visible!

My System:
Mac OS Sonoma Version 14.0 (23A344) on M1 MacBook Pro
Google Chrome - Version 117.0.5938.149 (Offizieller Build) (arm64)

Safari: 
![image](https://github.com/getkirby/kirby/assets/2411246/4ea72bbd-05e9-4ce2-81e2-66f587857b26)

Chrome:
![image](https://github.com/getkirby/kirby/assets/2411246/3ddbc361-e8ae-4c4f-9327-4596a040bf03)

But i can see if I set the "gap" style to 2px it gets visible (but a bit thicker as the other ones …)
![image](https://github.com/getkirby/kirby/assets/2411246/8ba34f7c-c688-4a2e-b2c0-031e2291dd6c)

**Comment by mountbatt** [comment]
Additional i found out that it gets sometimes visible if i change my browsers width! So try to resize the width of your Chrome Browser and maybe the effect is also visible to you?

**Comment by afbora** [comment]
I just wonder that what's your screen resolution?

**Comment by mountbatt** [comment]
Dell U3219Q - 31,5" Zoll - 3840x2160

**Comment by mountbatt** [comment]
Oh my god, it looks like I didn't have 100% zoom set in the browser. What a stupidity. Now it's right again.

**Comment by mountbatt** [comment]
And I always thought, why the hell did they make the interface sooo small in Kirby 4? :-)

**Comment by afbora** [comment]
Glad to hear you found the issue 👍
