### ISSUE TITLE
[v4] Disabled date field still accessible by using the keyboard

### ISSUE THREAD

**Issue by sr-pb** [k-next/kirby#5735]
## Description
The disabled date field is still focusable and accessible. A date can be picked by navigating with the keyboard. 

The behavior is still correct though: the field will not be saved after updating the value

Using Kirby 4.0.0-beta.2 and latest Chrome

**Screenshots**  
<img width="705" alt="Bildschirm­foto 2023-10-06 um 14 35 57" src="https://github.com/getkirby/kirby/assets/8458887/844a3867-f14e-43c8-8275-10da2ff4976c">

<img width="722" alt="Bildschirm­foto 2023-10-06 um 14 43 19" src="https://github.com/getkirby/kirby/assets/8458887/0ce16ab0-ea2d-4a9e-ace3-efad95e8abdd">

**Comment by bastianallgeier** [comment]
I just fixed this on develop.
