### ISSUE TITLE
[v4] Tags' text is not vertically centred

### ISSUE THREAD

**Issue by manuelmoreale** [k-next/kirby#5737]
## Description
Super minor detail but I'm gonna flag it anyway. The text inside the tags is not vertically centred. This is both visually and also numerically.

The tag's height is 24px and the line height of the text inside it is 17px which means the remaining 7px have to be split unevenly top and bottom (currently there's 4 top and 3 bottom in Firefox, 3 and 4 in Safari)

In addition to that, the text is not centred inside those 17px but that's because of the typeface itself.

These two things combined make it so that the text looks way off centred.

**Screenshots**
![Screenshot 2023-10-06 at 7 49 19 PM](https://github.com/getkirby/kirby/assets/1738077/975c1ec8-2da0-4a2c-99d7-0a687715c9dd)

## Your setup
**Kirby Version**  
Kirby 4 - Beta 2

**Comment by distantnative** [comment]
`line-height: 1` would help a little bit.
More I think could be hard - but leaving this here as reference https://iamvdo.me/en/blog/css-font-metrics-line-height-and-vertical-align

**Comment by manuelmoreale** [comment]
@distantnative Yes so figuring out a way to have an even line height would already help because that would at least fix the uneven top/bottom spacing. Fixing the vertical metric of the font is way too much work.

There's also this proposal that could help at some point but I'd not count on it. https://github.com/w3c/csswg-drafts/issues/3240

**Comment by distantnative** [comment]
We fixed the line height
