### ISSUE TITLE
[v4] Plugin label cannot translatable for `textareaButtons` extension

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5738]
I'm not sure this is a bug or I don't know how to use it. I can not use translate method for textarea plugin labels like following:

```js
panel.plugin("my/textarea-buttons", {
  textareaButtons: {
    smile: {
      label: this.$t('welcome'),
      icon: "smile"
    }
  }
});
````

I've tested following formats, but no luck:

- `$t('welcome'),`
- `this.$t('welcome'),`
- `panel.$t('welcome'),`
- `window.panel.$t('welcome'),`

> this.$t is not a function

### Additional context

`panel.$t('welcome')` works for `writerMarks` extension.

**Comment by afbora** [comment]
As workaround, works with getter:

````js
panel.plugin("my/textarea-buttons", {
  textareaButtons: {
    smile: {
      get label() {
        return panel.$t('avatar')
      },
      icon: "smile"
    }
  }
});
````

**Comment by distantnative** [comment]
Not sure there is a solution for this other than the workaround.

My thinking:
- Plugins have to registered first as they might register things the Panel needs to pay attention to. So your code runs before any of the Panel code
- That's why at that time `panel.$t` hasn't been defined yet.

**Comment by afbora** [comment]
OK. If this is expected behavior, we should document it or add getter sample to release/extension page.

**Comment by lukasbestle** [comment]
Why does it work with the `writerMarks` extension though?

**Comment by distantnative** [comment]
I wouldn't know how - @afbora could you please post an example where it works for writerMarks?

**Comment by afbora** [comment]
Because writer marks registry a little different from textarea buttons. It's already in getter.

```js
  writerMarks: {
    smile: {
      get button() {
        return {
          icon: "smile",
          label: panel.$t("smile"),
        }
      }
    }
  },
  textareaButtons: {
    smile: {
      get label() {
        return panel.$t('smile')
      },
      icon: "smile"
    }
  }
````

I think, getter solution is enough fine to close the issue.
