### ISSUE TITLE
[v4] Fix panel menu

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5772]
After https://github.com/getkirby/kirby/pull/5768 PR:

![image (2)](https://github.com/getkirby/kirby/assets/3393422/b87d089b-7a57-4a8a-b39e-19a53cdcb98f)

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/5768#issuecomment-1754864769_

**Comment by distantnative** [comment]
This is a lot harder than I'd thought. Will revert the PR for now.
