### ISSUE TITLE
[v4] Dialog fields width issue

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5773]
## Description

In language dialog, `code` and `direction` width 1/2 but show as 1/1

![image (3)](https://github.com/getkirby/kirby/assets/3393422/09eaa590-84d2-4d49-b12c-32f3ca81a5f2)

Kirby v4/develop branch

**Comment by distantnative** [comment]
It's because the dialog is too narrow and either our container queries the grid will fall back to single column layout.

**Comment by bastianallgeier** [comment]
We could think about adjusting the grid breakpoint for fields. But I wonder if it is a good idea. Two fields here will be really narrow.

**Comment by lukasbestle** [comment]
I'd say it depends on the expected field value. In this example, there would be more than enough room for a language name and a language code in the same row. But for other types of fields there may not be.

So I think this is hard to fine-tune via container breakpoints. We cannot adapt them to every use case.

Could we replace the container breakpoints with a prop per field (like `width: small|medium|large`)? This prop would then control the base width (possibly via `flex-basis`?) so the browser can allocate the right amount of space for the particular field. I don't know if this is viable for our CSS setup, feel free to discard my idea if it's not.

**Comment by bastianallgeier** [comment]
We use grid for the fields so this would be really difficult.

**Comment by bastianallgeier** [comment]
I would close this. We had the same in v3 and a solution for smaller widths is really difficult.

**Comment by distantnative** [comment]
@bastianallgeier but maybe we could remove our own with fractions than if they are now ineffective?

**Comment by bastianallgeier** [comment]
Is this necessary though. If the dialog is wider, the columns would work so we would need to check which dialog size is used and the remove the widths just to keep the HTML cleaner. Not sure if that's really important to be honest.

**Comment by distantnative** [comment]
@bastianallgeier But the dialog is always just the same max size, isn't it?

**Comment by distantnative** [comment]
It's less about keeping HTML cleaner. But we're also giving developers the idea that we intend them to be shown at half width and then they are never able to be shown at 1/2 - seems like a bug then. Or confusing if they would try to mimic a similar dialog.

**Comment by bastianallgeier** [comment]
I think of the narrow dialog like I think of the mobile widths.

**Comment by distantnative** [comment]
I don't understand that answer 😅
To phrase it differently: to me this is dead code that we carry forward.

**Comment by bastianallgeier** [comment]
We also don't consider it a bug when the grid breaks down in a single column on mobile or when the container is too narrow in other places. I.e. if you have a 1/4 column and fields in there, the field widths will also have no effect.

**Comment by distantnative** [comment]
The difference: the grid can actually become a real grid again when the size changes. The fields in the dialog will never be anything but single column.

**Comment by bastianallgeier** [comment]
Ok, I'm totally on the wrong side here. This is our language dialog 🙈 I didn't recognize it. Of course we had them break into columns in v3. I'm wrong. We obviously set the breakpoint too high.

**Comment by bastianallgeier** [comment]
Turns out, we didn't even define a container for dialogs so far. The grids cannot work at all. PR incoming.
