### ISSUE TITLE
Writer field does not work with kirbytextinline or has no equivalent

### ISSUE THREAD

**Issue by trych** [k-next/kirby#5777]
As we discussed a11y on the Discord channel and Bastian encouraged us to report a11y related topics as bugs, here we go:
I was trying to output some writer field's content to my frontend, only to find out that it "force wraps" my field's content into a p tag and to find out that I cannot really use the `kirbytextinline` helper or method on it. Upon closer inspection that seems to make sense, as the writer field saves html in the content file unlike a text area field.

However, this poses an issue when I want to output the field's content *without* surrounding tags and makes it hard to write proper semantic HTML with it. Let's say I want to place its output into a `figcaption` tag or something, then it still would get wrapped into p tags first.

Also, this makes it really difficult to put custom attributes such as aria lables into the surrounding tags.

I propose that either there is a way to disable the default paragraph wrapping (although I suspect that might be very confusing for editors) or that there is some method similar to kirbytextinline that I can use with the writer field output that allows me to output its contents without surrounding tags (basically make it work the same way as it works with text areas).

To answer the question why I would not just use a text area field instead: I would like to keep the text editing experience consistent for editors in the backend. I find the "inline styling" much more intuitive with writer fields, so that's why I use those. If I now have to use text area fields in certain places, that bold a word by wrapping it in ** instead of just showing it bold that is confusing and little understandable for editors.

**Comment by trych** [comment]
Upon thinking about this further, I think the issue is only really an issue when there is a single top level element, like a single paragraph. In this case there should be an option to strip the outer tags. I assume the text area field in combination with kti would work the same way?

**Comment by lukasbestle** [comment]
Inline mode for the writer field is already a thing, see https://getkirby.com/docs/reference/panel/fields/writer#inline-mode.

**Comment by trych** [comment]
🤦‍♂️

Wow. I am not sure how I missed this now. Even worse, now that you pointed it out, I am pretty sure that I have used this in the past already. 😂

Sorry for making a fuss and thanks for the quick response. Closed.

**Comment by lukasbestle** [comment]
Don't worry, glad we could resolve it so quickly. 🙂
