### ISSUE TITLE
Search function and non-english characters case sensitivity issue

### ISSUE THREAD

**Issue by alexpi** [k-next/kirby#5780]
## Description

When performing a site search using non-english characters, the search is performed with case sensitivity, so for example in Greek, searching for the word 'Βάρος', does not match 'βάρος' (Same word with a lowercase first letter).

**Expected behavior**  

## Your setup
**Kirby Version**  

3.9.6.1

**Your system (please complete the following information)**
 - Device: Desktop PC
 - OS: Windows 10
 - Browser: Chrome, All
 - Version: 117

**Additional context**  

I wrote about this issue in the forum, and @rasteiner explained the issue to me. I am quoting his answer (I hope that's ok):

"Kirby relies on the PCRE2 regex engine of PHP to find matches, it passes the i flag to the regex to make the search case insensitive, but in PCRE2 world, i only works for the ranges [a-zA-Z] (that’s only the 52 symbols of the English alphabet, like: it also [doesn’t match ü with Ü]. I guess Kirby could change that regular expression to [also include the u (Unicode) flag], that would fix the upper / lower case issue."

Is it possible that a small change to Kirby's code could fix this termporarily?

**Comment by rasteiner** [comment]
If you want to test it, change [this line](https://github.com/getkirby/kirby/blob/3.9.7/config/components.php#L189) to

```php
$preg    = '!(' . implode('|', $words) . ')!iu';
```

(just add a `u` after the `i`)


It should make a difference:
https://onlinephp.io?s=s7EvyCjg5eLlSk3OyFdQD88sycgvLVEotVJQ11MoKEpNj89NLEnO0FCvOTfp3Jrzjef2n2-qyVTXUVBQP7cJJqCuqaCnoBSTp2QNM0dBQQFkFCFzSoEGYTUHAA%2C%2C&v=8.2.7%2C8.1.20%2C8.0.29

**Comment by alexpi** [comment]
Yes it works!
