### ISSUE TITLE
[v4] Writer field can’t change nodes in floating toolbar only for Safari

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5782]
Forum discussion: https://forum.getkirby.com/t/k4-writer-field-cant-change-nodes-in-floating-toolbar/29710

https://github.com/getkirby/kirby/assets/3393422/9ddd246a-8bfe-4bfa-8da9-5b4dd7cff11c

**Comment by jklue** [comment]
Thanks for opening the issue @afbora. Here are my deets...
- Kirby version 4.0.0-beta.1
- Safari Version 16.6 (18615.3.12.11.2)
- Mac OS Ventura 13.5.2
- PHP 8.1.22
- Valet 4.1.4

Let me know if I can add anything else and I'll edit it in here^^

**Comment by afbora** [comment]
Thank you @jklue I just wonder that is this issue still persist for beta2 or beta3. Could you test it beta.3 (still in develop) please? 
Here beta.3 kirby folder: [kirby.zip](https://github.com/getkirby/kirby/files/12870553/kirby.zip) Just replace `kirby` folder and delete `media` folder.

**Comment by distantnative** [comment]
Duplicate of https://github.com/getkirby/kirby/issues/5442?

**Comment by afbora** [comment]
Yes looks like it is.

**Comment by jklue** [comment]
So sorry for nonresponse. The issue is fixed for me with beta3 downloaded today.
