### ISSUE TITLE
Duplicating a duplicated page

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#5787]
## Description
Duplicating an already duplicated page creates an error because Kirby seems not to append a new suffix to the page name because it already exists.

**Expected behavior**  
If a page slug already ends on `-copy`, Kirby should start adding and raising an index number to find a unique slug. This should not fail after the first attempt, trying `-copy1`, `-copy2`, `-copy3`. There might well be a limit of tries but in most cases it should be possible to find an available name within a few tries.

**Screenshots**  
<img width="499" alt="grafik" src="https://github.com/getkirby/kirby/assets/25466/b4af7174-7357-44ad-a6a0-33d6a393f03f">

## To reproduce
1. Duplicate a page.
2. Duplicate that page again.

## Your setup
**Kirby Version**  
Kirby 3.9.6.1

**Comment by afbora** [comment]
![screen-capture-1697-Exploring the universe Copy - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/ead92036-064c-4d1e-93f6-eb20d718a36d)

I can't reproduce the issue. Do you have custom model or plugin?

**Comment by nilshoerrmann** [comment]
We do have a custom model but only to generate custom info texts for the panel section display.

**Comment by afbora** [comment]
Do you have the issue on starter or plainkit?

**Comment by nilshoerrmann** [comment]
I just tested again and it does not happen on the first copy. Take this:

<img width="740" alt="grafik" src="https://github.com/getkirby/kirby/assets/25466/27ea6bb1-0801-4dc5-a22a-9abbff9ade1e">

It works, if I try to duplicate the third page.
It fails, if I do the same on the first or second page.

**Comment by nilshoerrmann** [comment]
> Do you have the issue on starter or plainkit?

I'll have to check that later because I have none installed on my machine right now.

**Comment by lukasbestle** [comment]
> It works, if I try to duplicate the third page.
It fails, if I do the same on the first or second page.

Ah, yes. That makes sense.

We only append Copy but don't check if the resulting UID is already taken. I agree with your suggestion to append numbers. It could work like this:

1. If the UID does not already end with `-copy`, append `-copy`
2. Check if the resulting page exists (`while` loop). In the loop, append a number that is counted up.
3. Finally append the same number to the suggested title of the duplicate.

**Comment by afbora** [comment]
Now I get it, it's already a page with the same `-copy` suffix. I honestly didn't think it was a bug 🙂

**Comment by afbora** [comment]
@lukasbestle I've implemented your idea in https://github.com/getkirby/kirby/pull/5788
