### ISSUE TITLE
Invalid changed data download.

### ISSUE THREAD

**Issue by modufolio** [k-next/kirby#5791]
## Description
The data that is being downloaded doesn't seem okay, getting [object Object] in a layout field back.

**Screenshots**  
![download-changes](https://github.com/getkirby/kirby/assets/18153996/5eee6932-cfbf-4924-bf45-948c2fcc3823)

``` 
layout: 

[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]

```

----

## To reproduce
No idea

## Your setup
**Kirby Version**  
3.9.7
4.0.0-beta.1

**Comment by bastianallgeier** [comment]
Have you tried with beta 2 as well?

**Comment by distantnative** [comment]
I think this could potentially be a v3 issue even

**Comment by afbora** [comment]
Yes, the issue already in v3.

**Comment by afbora** [comment]
We can use `JSON.stringify()` for array and objects. That would be correct for blocks and layout field but not for structure and object field. It needs to be encoded as yaml data (need a js yaml dependency). I think it seems difficult to detect fields type in local storage.

**Comment by lukasbestle** [comment]
I'd say pretty-printed JSON would still be better than nothing even for YAML fields. The download is only meant as a backup for manual merging of changes.

**Comment by afbora** [comment]
Make sense. If everyone agree on using pretty JSON for all non-string data, I can prepare PR for 3.9.8 release.
