### ISSUE TITLE
[v4] Programmable Blueprints: blocks not shown on empty fieldsets array

### ISSUE THREAD

**Issue by HYR** [k-next/kirby#5794]
This approach came from the [Programmable Blueprints](https://getkirby.com/docs/cookbook/panel/programmable-blueprints) cookbook article.

## Summary

I've been using the programmable blueprints approach for quite some time. It continued to work in the alphas but now in the betas, no blocks in the block chooser show. Same for page types that are loaded by default via this method. Now all page types are show by default.

## Longer Description
I'm using the system.loadPlugins:after hook in the index of my custom plugin and that part still seems to be working. I'm pulling in options via the shortcut options('...')  and merging that array with a default list of blocks. 

![image](https://github.com/getkirby/kirby/assets/5200901/e19f6913-21aa-40ac-bfe0-9814abeab4f6)

Registering them like this:

![image](https://github.com/getkirby/kirby/assets/5200901/8611277f-ce6e-4c97-843f-5eb0ff7bba5d)

Been using this approach for the last year or two. This worked in the Alphas, but now in the betas, no blocks show up.

<img width="650" alt="CleanShot 2023-10-13 at 11 32 47@2x" src="https://github.com/getkirby/kirby/assets/5200901/4673d750-7256-4627-861f-5763ab63d6f8">

Same issue with page types (you can see them added in the `->extend()` above):

<img width="993" alt="CleanShot 2023-10-13 at 11 34 35@2x" src="https://github.com/getkirby/kirby/assets/5200901/e48198a1-0294-4048-a5f1-b4a04b0733db">

**Expected behavior**  
Expected blocks and page types to continue to work like they did in the v4 alphas.

## To reproduce
Not sure how to reproduce. :(  Not sure what changed.

## Your setup
**Kirby Version**  
Kirby 4.0.0-beta.2

**Console output**  
No errors in the browser console

**Your system (please complete the following information)**
- MacOS Ventura 13.3.1 (a)
- Firefox 118.0.2
- Brave [Version 1.58.137 Chromium: 117.0.5938.153](https://brave.com/latest/)

**Additional context**  
Attached is a zip with 2 key files.
1. plugin index
2. layouts.php which is pulled in first
[index-and-layout.zip](https://github.com/getkirby/kirby/files/12897002/index-and-layout.zip)

**Comment by distantnative** [comment]
@HYR any chance you could trim the files down to a reproducing test that's easier to grasp? Right now the plugin index.php is very overwhelming to start tackling debugging. If not, we'll give our best, but it would be very helpful.

**Comment by HYR** [comment]
I agree. I'll try to do that tomorrow.

**Comment by HYR** [comment]
@distantnative I think I got it narrowed down to the `open:` option on block groups. Did something change between the alphas and betas regarding that option?

<img width="470" alt="image" src="https://github.com/getkirby/kirby/assets/5200901/a282cb57-bc42-4ff5-9dfc-ad65f48ac686">

If I comment out the `open` line on each and the blocks work again. Doesn't seem to like empty arrays anymore. I think before it must've defaulted to false?

Here's the variable definition they're referencing:`$open = option('wsp.site-panel.page.blocks.open') ?? [];`.

**Comment by HYR** [comment]
Also seems like another issue where it doest link `fieldsets` being an empty array anymore.

<img width="420" alt="CleanShot 2023-11-13 at 17 20 01@2x" src="https://github.com/getkirby/kirby/assets/5200901/aba6e349-9393-42c9-bbd6-eab3de8c04d4">

In this case `$customBlocks` was an empty array, which worked in v3. But no longer in v4.

**Comment by lukasbestle** [comment]
@HYR Could you please post example code as code, not as screenshots? That way we can reproduce it as well without having to type it manually or use OCR. Thanks.

**Comment by HYR** [comment]
@lukasbestle here is some code to reproduce. In the alphas (and before) it seems that the empty array was acceptable, but starting in the betas an empty array would cause the blocks to not display at all. We have a lot of site relying on the previous way it worked.

Using the code below you can see it cause the empty block chooser. Add any block into the `$testBlocks` array and it displays the blocks again.

### Bare bones plugin index (index.php):
```php
<?php
use Kirby\Cms\App as Kirby;

Kirby::plugin('test/dynamic-blocks', [
    'blueprints'    => [
        'shared/layout' => function ($kirby) {
            return include __DIR__ . '/layout.php';
        },
    ],
    'hooks' => [
        'system.loadPlugins:after' => function () {
            $commonBlocks = ['heading','text','image','video'];
            $testBlocks = []; // empty

            kirby()->extend([
                'blueprints' => [
                    'fieldset/common' => [
                        'fieldsets'=> $commonBlocks
                    ],
                    'fieldset/test' => [
                        'fieldsets'=> $testBlocks
                    ],
                ],
            ], kirby()->plugin('test/dynamic-blocks'));
        }
    ]
]);
```

### Bare bones dynamic blueprint (layout.php):
```php
<?php
use Kirby\Data\Yaml;
$yamlFilePath = __DIR__ . '/layout.yml'; // Path to YAML file
$yamlContent = file_get_contents($yamlFilePath); // Read the file contents
$parsedContent = Yaml::decode($yamlContent); // Parse the YAML content
$defaultLayouts = ["1/1"];
$layouts = ['layouts' => $defaultLayouts];

$fieldsets = [
    'fieldsets' => [
        'common' => [
            'label' => 'Common',
            'type' => 'group',
            'extends' => 'fieldset/common',
        ],
        'test' => [
            'label' => 'Test',
            'type' => 'group',
            'extends' => 'fieldset/test',
        ],
    ]
];

$data = array_merge($parsedContent, $fieldsets, $layouts);
return $data;
```

### Bare bones yaml to import for dynamic blueprint (layout.yml):
```yml
type: layout
label: Page Content
```

**Comment by distantnative** [comment]
But wouldn't you consider it to be correct that if you pass an empty array as a fieldsets, that those show up as zero/none? An empty array doesn't quite read as "no value, please ignore and use default" like `null` would do

**Comment by HYR** [comment]
I would expect the one that receives an empty array to not work but I wouldn't expect it to break the other fieldsets. And correct me if I'm wrong, it seemed be how it worked before.

**Comment by distantnative** [comment]
I didn't get that it also breaks other field sets - I haven't been able to reproduce it, your examples still include more files that you haven't shared. And yes it very well can be that v4 in some areas does stricter value checks. But can't say for sure until we understand where it goes wrong/differently.

**Comment by HYR** [comment]
Sorry, the only page I didn't include was the `about.yml` in the starterkit. And the only change was to update the layout field to use the new dynamically created fieldset definition, the rest was default code from the starterkit's about page.

```yaml
tabs:
  content:
    icon: text
    label: content
    fields:
      layout:
        extends: shared/layout
 ```

I ran through it from scratch again to make sure. Here are the steps I took: 

1. Install kirby starter kit
2. Update kirby installtion with Kirby4 RC1
3. Create plugin with the 3 files from previous comment (index.php, layout.php, layout.yml)
4. Update `about.yml` blueprint to use the new `shared/layout` fieldset (above in this comment)
<br>

At this point the block chooser should be empty because of the array `$testBlocks` is empty. Which looks like this:

<img width="600" alt="CleanShot 2023-11-21 at 21 02 59@2x" src="https://github.com/getkirby/kirby/assets/5200901/655129c3-1565-4ca0-ada4-0217c8f91cf0"><br>

Once you put any valid block name (ex: 'heading') into the array, the chooser works again. Which looks like this:

<img width="566" alt="CleanShot 2023-11-21 at 21 01 41@2x" src="https://github.com/getkirby/kirby/assets/5200901/ef70da64-6ea3-4379-95ab-85564b7ca616">

**Comment by distantnative** [comment]
But what about the layout.yml?

**Comment by HYR** [comment]
It's super short at the bottom of this comment: https://github.com/getkirby/kirby/issues/5794#issuecomment-1820069306

```yaml
type: layout
label: Page Content
```

In the actual sites it has all of the tabs with extra fields I use but in this example wanted it to be bare bones.

**Comment by distantnative** [comment]
@HYR are you getting any errors in the console?

**Comment by distantnative** [comment]
Ahhh think I got it
