### ISSUE TITLE
[v4] Color field in Blocks Fields preview doesn't work

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5795]
## Description
![CleanShot 2023-10-13 at 21 15 22@2x](https://github.com/getkirby/kirby/assets/29142128/1a66449a-621d-47f7-8c9a-bbcfe7006117)

It's not possible to click the color field in this setup. It works fine when opening the block in a drawer.
In addition to that, setting it in the drawer, and closing it, will also reset the value in the fields preview to the value it was before.

## Your setup
**Kirby Version**  4.0-beta.2
Chrome  118.0.5993.70

**Comment by distantnative** [comment]
Can painfully reproduce it.
Since I didn't find an obvious source, I am wondering if this is related to the various focus issues on blocks. That somewhere in the code a listener for a focus event is swallowing the click.

**Comment by tobimori** [comment]
I'm pretty sure that it did work in a previous version if that's helpful

**Comment by distantnative** [comment]
Reactivity headache one - at least partially related to https://github.com/getkirby/kirby/issues/5845

**Comment by bastianallgeier** [comment]
This line is the culprit https://github.com/getkirby/kirby/blob/e72d4dc3b0ac98e7a7b1cdcd4626d5a267b33c13/panel/src/components/Forms/Blocks/Blocks.vue#L34
