### ISSUE TITLE
[v4] Freeze after splitting text in blocks field

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5811]
## To reproduce

1. Go to any blocks field
2. Edit any text block in preview
3. Try to split text
4. Panel will be freeze

## Your setup
Kirby beta.3(v4/develop)

**Comment by distantnative** [comment]
Any console output?
Just tried it and worked for me without issues.

**Comment by afbora** [comment]
No console error. I've checked now on fresh v4/develop branch. Still same for Chrome and Firefox.

**Comment by afbora** [comment]
https://github.com/getkirby/kirby/assets/3393422/212e3df6-a255-4eea-af46-420750adc610

**Comment by distantnative** [comment]
Tried again - works just fine for me :/

**Comment by lukasbestle** [comment]
Can't reproduce it either in Safari or Chrome.

@afbora If you look at the DOM in Dev Tools, is there a transparent element over the whole Panel that captures clicks and prevents interaction?

**Comment by afbora** [comment]
Now I can't reproduce the issue on up-to-date `v4/develop` branch 🤷‍♂️
