### ISSUE TITLE
[v4] Toggle preview doesn't update when toggling multiple times.

### ISSUE THREAD

**Issue by f-mahler** [k-next/kirby#5813]
## Description
When using the toggle in a structure, the preview doesn't update correctly, when toggling multiple times without saving.

Also it opens the sidebar everytime, which seems redudant in the case of a toggle field.

**Screenshots**  

<img width="526" alt="Screenshot 2023-10-18 at 10 56 22" src="https://github.com/getkirby/kirby/assets/16965122/435ef120-6d0e-433f-aeae-f7d94e1587ef">

## To reproduce

1. Click once on toggle preview. Close sidebar
2. Click again on toggle preview. Close sidebar

## Your setup
**Kirby Version** v4.0.0-beta2

**Comment by distantnative** [comment]
I cannot reproduce that it stops updating.

But opening the drawer indeed doesn't make sense.
