### ISSUE TITLE
Code block within a structure field not parsed correctly

### ISSUE THREAD

**Issue by zakgreene** [k-next/kirby#5820]
I have a structure field that includes blocks. If I add a code block, it doesn't parse as HTML in my templates if the block includes multiple lines. My workaround has been to include one code block for each line, but this is not ideal.

Using latest Kirby (3.9.7)

This block setup:
<img width="1307" alt="Screen Shot 2023-10-18 at 9 02 36 PM" src="https://github.com/getkirby/kirby/assets/107688/cc109a88-e75e-4f51-a761-e1fe7a141d39">

and this template code:
```
<?php foreach ($page->reference_css()->toStructure() as $item): ?>
    <div id="<?= $item->item()->html() ?>">
        <h1><code><?= $item->item()->html() ?></code></h1>

        <?= $item->info()->toBlocks() ?>
    </div>
    <?php endforeach ?>
```

Results in this
<img width="991" alt="Screen Shot 2023-10-18 at 9 03 25 PM" src="https://github.com/getkirby/kirby/assets/107688/bca116bc-0915-4960-a8fd-29ec29609b77">

**Comment by zakgreene** [comment]
Looks like a duplicate of #3831

**Comment by afbora** [comment]
Yes, this is duplicated issue. We are tracking this in the backlog because there is more than one of the similar/same issue. I cannot give a date when it will be fixed.
