### ISSUE TITLE
[v4] Panel NetworkError doens't disappear when coming back online

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5821]
## Description
When I put my computer to sleep and later come back I often have to dismiss an error modal with the following message:

"NetworkError when attempting to fetch resource."

**Expected behavior**  
I'd expect the modal to disappear on it's own once I'm back online.

**Screenshots**  
![Screenshot 2023-10-19 at 11 59 22](https://github.com/getkirby/kirby/assets/60777/1b3a1fc8-0016-42fc-9b11-328e81428da8)

## Your setup
**Kirby Version**  
4.0.0-alpha.7

**Console output**  
> Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.

**Comment by distantnative** [comment]
Note for us: NetworkError is uncaught - which causes a regular error dialog. Not our offline warning component that reacts on `window.offline`/`window.online`. Thus, it'll stick around as normal error dialog.

**Comment by bastianallgeier** [comment]
This is probably caused by the lock requests. I think we should stop those when the panel is offline

**Comment by distantnative** [comment]
Maybe easier not to stop the interval but only wrap the actual api call in an if statement checking for not offline

**Comment by chrfickinger** [comment]
I still get sometimes the error "NetworkError when attempting to fetch resource"
(4.0-beta.3)

**Comment by bastianallgeier** [comment]
@chrfickinger does it still happen to you in the latest rc?

**Comment by chrfickinger** [comment]
I'm not on the latest rc yet, but I haven't seen the error again
