### ISSUE TITLE
[v4] Plugin assets resolves as JSON (500 Internal Server Error)

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5836]
## Description

Sometimes plugin assets resolves as JSON. This issue does not always occur. I don't know exactly when it occurs.

> Request URL: /media/plugins/afbora/test/2538303991-1697822431/css/style.css
> Request Method: GET
> Status Code: 500 Internal Server Error
> Content-type: application/json; charset=UTF-8
>
> Refused to apply style from '/media/plugins/afbora/test/2538303991-1697822431/css/style.css' because its MIME type ('application/json') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Use following code to reproduce:
````php
<?= css(kirby()->plugin('afbora/test')->asset('css/style.css')) ?>
````

## To reproduce

1. Download plainkit with v4 here: [plugin-assets-resolve.zip](https://github.com/getkirby/kirby/files/13056794/plugin-assets-resolve.zip)
2. Go to homepage and open browser console
3. Try to refresh the page multiple times
4. Check browser console after each refresh
5. You'll see 500 internal server issue for a asset

## Your setup
Kirby 4.0.0-beta.3/v4-develop

## Additional context
When I checked `/media/plugins/afbora/test` directory, It's empty. When I visit `/media/plugins/afbora/test/2538303991-1697822431/css/style.css` url from browser, opens correctly in browser and I can see the `style.css` in `/media/plugins/afbora/test`. But I refresh the homepage, `/media/plugins/afbora/test` directory cleared again.

**Comment by distantnative** [comment]
Sounds like something in `PluginAssets::clear()` removing files that are actually still in use and not stale

**Comment by afbora** [comment]
Seems `PluginAssets::resolve()` always clean before process: https://github.com/getkirby/kirby/blob/v4/develop/src/Cms/PluginAssets.php#L140-L141

**Comment by distantnative** [comment]
That is right, that's the only time it can run. But `::clean()` must not match still active files. So I'd think the bug is there

**Comment by afbora** [comment]
@distantnative Looks like works like following. Not sure but I think bug is related with `array_diff` arguments order. Do you think it could be that easy? 🙂 

````diff
- $stale = array_diff($files, $active);
+ $stale = array_diff($active, $files);
````

https://github.com/getkirby/kirby/blob/v4/develop/src/Cms/PluginAssets.php#L49

**Update**: Nvm, I think this is not related with the issue.

**Comment by afbora** [comment]
Another clue is about getting current files via `Dir::index()`. This returns dirs and files. But `$active` files only includes files. So `array_diff` compares wrong lists. I think it should be like that:

````diff
- $files = Dir::index($media, true);
+ $files = Dir::files($media);
````
https://github.com/getkirby/kirby/blob/v4/develop/src/Cms/PluginAssets.php#L37

**Comment by distantnative** [comment]
Yes that's part of the problem. Another part is that actually with our new asset plugin extension the names might not even match. So we would probably also add calls like `$plugin->asset($file)` to really match names. And then the question remains how to clean up empty folders in media.

**Comment by lukasbestle** [comment]
I think the main issue right now is indeed that the folders are only included in the current index, not the `$active` list. This makes them always appear in `$stale`, so I guess all subdirectories are always deleted.

We could fix this by including all parent directories up to the plugin's media root for all assets in `$active` as well. Then `array_diff()` will not put them in `$stale` anymore.

**Comment by distantnative** [comment]
That's but also `assets/css/style.css` will be just as `css/style.css` in the media folder. And if we register an asset with a custom key as path that doesn't match the actual filesystem
path, it can even be that `css/style.css` in the media folder would belong to `framework/styling/index.css` in the plugin folder

**Comment by lukasbestle** [comment]
Yeah, we definitely also need to look up the resulting paths for each asset.
