### ISSUE TITLE
[v4] Layout bug in Languages and Users views in Safari after resizing browser window

### ISSUE THREAD

**Issue by lukasbestle** [k-next/kirby#5844]
## Description

If I open the Languages or Users views, resize the window smaller and then resize the window back to the original size, the view contents are displayed over the full window width but in the background.

I could only reproduce this in Safari. The Site and System views don't seem to be affected as they don't go into "hamburger menu mode" in the most narrow window width.

**Expected behavior**  

The view should reset to its original layout.

**Screenshots**  

https://github.com/getkirby/kirby/assets/1595007/4310d3a6-9fa8-4457-9dba-a037230aeda7

## To reproduce

1. Open the Panel in Safari
2. Go to the Languages or Users views
3. Resize the window as small as it gets
4. Resize the window back to a desktop size

## Your setup
**Kirby Version**  

`v4/develop` branch

**Console output**  

**Your system (please complete the following information)**
 - Device: 
 - OS: macOS Ventura 13.6 
 - Browser: Safari
 - Version: 17.0 

**Additional context**

**Comment by distantnative** [comment]
We thought we had fixed it (https://github.com/getkirby/kirby/issues/5606) but @manuelmorale also wrote me that it still occurs at times.

Based on what we understood back then, Safari is tripping over unrelated heavy CSS rules (e.g. the positioning of the file preview coords component) and starts glitching.

**Comment by distantnative** [comment]
This could indeed be a browser bug, don't you think?
I can reproduce it, but as soon as I scroll just a tiny bit, or click at any CSS property in the inspector... it's back to normal. Which seems to me that maybe nothing in our CSS or JS is wrong but Safari is just tripping.

**Comment by distantnative** [comment]
Just noting down observations to not forget them later:
When the menu is collapsed with wide browser window, after resizing, the menu is not shown at all. So after resizing to wide, Safari is in the right panel.isOpen mode (closed/shown = collapsed/expanded) but the styling change is lagging behind.

**Comment by distantnative** [comment]
It is container queries related: If I remove those e.g. from `k-inside` and `k-grid`, the glitches stop for me. Looks like Safari's implementation of container queries isn't the best.

**Comment by lukasbestle** [comment]
OK, I guess we can ignore this issue then. It's not like end-users are resizing their browser window all the time. 😄
