### ISSUE TITLE
Querying options for color field

### ISSUE THREAD

**Issue by maxime-pigeon** [k-next/kirby#5852]
## Description

Querying options is unsupported in the color field. Returns `Unsupported color: "query”`.

**Expected behavior**  

I expected to be able to use query for the color field. Is this planned?

## Your setup
**Kirby Version**  

4.0b2

**Your system (please complete the following information)**
 - Device: MacBook Air M1
 - OS: macOS
 - Browser: Safari
 - Version: 16.6

**Comment by afbora** [comment]
This feature is already in ideas, you can vote from here: https://kirby.nolt.io/577

**Comment by maxime-pigeon** [comment]
Good to know. Thanks for quick response.
