### ISSUE TITLE
[v4] Cropping a jpg with focus point results in wrong aspect ratio

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5855]
## Description
So I'm cropping an image to **512x683**:

![in](https://github.com/getkirby/kirby/assets/60777/2b7e03d9-d08a-4839-9352-96673cd393bd)

```php
$image->crop(512, 683, ['crop' => '35.7% 48.1%']);
```

**Expected behavior**  
A 3/4 ratio image of the size 512x683:
![correct](https://github.com/getkirby/kirby/assets/60777/7f5e2449-ac2d-4358-b49c-c1e7500956b1)

**Actual behavior**
And thumbs says "best I can do is **732x683**":

![out](https://github.com/getkirby/kirby/assets/60777/41f8c725-893e-42de-8205-b65edca9bf63)

## To reproduce

1. it has to be a jpg image
2. there has to be a focus point set
3. you have to use ImageMagick
4. ...
5. fun

## Your setup
**Kirby Version**  
v4 beta 2

## Digging 
So I investigated a bit. This is the ImageMagick command that the php statement produces:
```
convert -limit thread 1 -define 'jpeg:size=512x683' 'in.jpg' -auto-orient -crop 1770x2362+379+0 -resize 512x683^ -quality '85' 'out.jpg'
```

Let's look at the relevant parts:
```
-define 'jpeg:size=512x683'
```
[jpeg:size](https://imagemagick.org/script/command-line-options.php?#define) is a performance optimization setting that gets added to jpg files. Based on it, the jpg loader will load the image smaller to save memory. It was introduced to Kirby with this [PR](https://github.com/getkirby/kirby/pull/4106).

```
-crop 1770x2362+379+0 -resize 512x683^
```
The image is 3543x2362. The setting correctly tells the process to cut out a 1770x2362 rectangle in the desired aspect ratio of 0.75.
`+379+0` offsets this rectangle based on the focus point of 35.7% 48.1% (it moves the frame a bit left from the center).
`-resize 512x683^` scales it down.

All looking good.

Now, if we remove the performance optimization `-define 'jpeg:size=512x683'`, the resulting image has the correct aspect ratio. I'm not 100% sure yet why but I guess it has to do with `jpeg:size` scaling the image down when loading it into memory and `-crop 1770x2362` working with the original image sizes.

For comparison a crop call without focus point:

```
convert -limit thread 1 -define 'jpeg:size=512x683' 'in.jpg' -auto-orient -thumbnail '512x683^' -gravity 'Center' -crop '512x683+0+0' -quality '85' 'correct.jpg'
```

No pixel value goes outside the 512x683 bounds.

My temporary fix is to remove the performance optimization. That's no problem in my case because the server has lot's of ram. I hope though that we find a solution that keeps the performance optimization.

**Comment by distantnative** [comment]
Sounds like a tricky one.

> However for thumbnails of JPEG images, you can limit the size of the image read in from disk using the special option "-define jpeg:size={size}" setting. See [Reading JPEG Images](https://imagemagick.org/Usage/formats/#jpg_read) for more details. As such this speed improvment is rarely needed for JPEG in thumbnail generation, though profile stripping is still very important.
https://imagemagick.org/Usage/resize/

Which sounds really like we're hitting a wall there with im as we want to do calculations on the full size when we're telling it at the same time to load a much smaller size.

A simpler solutions could probably be to remove the `-define` parameter whenever a focus point is set. To not affect images' performance that don't have a focus point.

More complicated solution that we would need to experiment with, is, whether for im we can do the commands in a way that works already on the thumbnail resolution and can use the crop to offset it from that size set then.

**Comment by lukasbestle** [comment]
Could we maybe modify the width and height passed to `jpeg:size` to be the resized image without cropping? So basically the original image's aspect ratio but resized so that the resulting cropped image fits into it. As far as I understand it, ImageMagick should then have enough pixels to work with again.

**Comment by distantnative** [comment]
@lukasbestle sounds like a worthy approach to me

**Comment by distantnative** [comment]
Trying to operationalize this. If we have `-crop 1770x2362+379+0 -resize 512x683`

- Take the target `width` and `height` of the thumb
- get the scale factor how this relates to the crop dimension (so here `1770x2362`)
- choose the scale factor that's larger (?) for width/height
- apply that factor on both width and height of `1770x2362` to get the new pair to use for `-resize`

that?

**Comment by lukasbestle** [comment]
I don't think we can change anything about `resize` as that is the final output size. I might have misunderstood you though.

What I just realized: The aspect ratio of the `crop` and `resize`/`jpeg:size` sizes is in fact already the same, which makes sense and must be like this. So my comment above does not really make sense.

After reading the original comment again (thanks @mrflix for your detailed explanations!), I think the issue is just that focus cropping passes the original image dimensions instead of the scaled target dimensions. So what we need to change is the `-crop` argument in focus cropping mode so that it is based on the target dimensions, no? That's what already happens with normal cropping without focus.

**Comment by distantnative** [comment]
@lukasbestle I think you're on the right track. However, `Focus::coords()` is right IMO to return the original size crop as we need for Gd to first crop and then resize. I recall there were weird results if not done in this order but first allowing the resize before focus cropping.

Maybe these side effects aren't true for ImageMagick? We'll have to try. 

The current code

```php
$focus = Focus::coords(
	$options['crop'],
	$options['sourceWidth'],
	$options['sourceHeight'],
	$options['width'],
	$options['height']
);

return sprintf(
	'-crop %sx%s+%s+%s -resize %sx%s^',
	$focus['width'],
	$focus['height'],
	$focus['x1'],
	$focus['y1'],
	$options['width'],
	$options['height']
);
```

to adjust to output sizes


```php
$focus = Focus::coords(
	$options['crop'],
	$options['sourceWidth'],
	$options['sourceHeight'],
	$options['width'],
	$options['height']
);

$thumbRatio = $focus['width'] / $options['width'];

return sprintf(
	'-crop %sx%s+%s+%s -resize %sx%s^',
	$options['width'],
	$options['height'],
	$focus['x1'] / $thumbRatio,
	$focus['y1'] / $thumbRatio,
	$options['width'],
	$options['height']
);
```

My issue is that IM doesn't want to work for me locally, so I'd need someone else to test this.

**Comment by mrflix** [comment]
@distantnative this is the result when testing your output-size adjustment:

![result](https://github.com/getkirby/kirby/assets/60777/55010baf-bb47-4e13-ae0e-305b5a17c638)

The aspect ratio is correct 🙌
But it's zoomed in 😟 The stones at the bottom should be fully visible because it should keep its full height.

**Expected behavior**

![truth](https://github.com/getkirby/kirby/assets/60777/c406a4b1-52bc-44d0-99fe-778e9e29ccdc)

**Comment by distantnative** [comment]
Puh,... I am trying to take this on again.

What I gathered still:
1. the problem is the optimization, likely already putting the target size into memory, so the cropping parameters that are base don the original size fail
2. to use those cropping parameters, we would have the original size in memory... but putting the original dimensions into the optimization call would mean no optimization at all, I fear


What would speak against reordering the process steps? Currently we first convert the image and then apply all kind of effects. Does it matter for IM what the order of commands is? Would it help to move the conversion after resizing?

**Comment by distantnative** [comment]
Also if anyone has tips on how to get `im` running with Herd... failing horribly here.

**Comment by mrflix** [comment]
Thanks for taking another stab at it Nico. I think this bug is so sever that the performance optimization should be removed until this is solved. That's what I do in my installations.

>What would speak against reordering the process steps?

I remember that I read somewhere that `-define 'jpeg:size'` has to come in the beginning before the filename because the whole clue is that this lowers the memory footprint by shrinking the image while loading it into memory before all the other processing. Can't verify it right now but in the example in the [imagemagick documentation](https://www.imagemagick.org/Usage/formats/#jpg_read), they also put it in front of the input filename:

```bash
magick -define jpeg:size=64x64   jpeg_large.jpg jpeg_size_hint.jpg
magick -define jpeg:size=128x128 jpeg_large.jpg -thumbnail 64x64  jpeg_thumbnail.jpg
```

I still tried it out and it "works" but it just seems to skip the optimization. I directly felt slower, so I measured it to make sure that the optimization is getting skipped.

Initial command. The output is squared instead of portrait:
```bash
magick -limit thread 1 -define 'jpeg:size=512x683' 'in.jpg' -auto-orient -crop 1770x2362+379+0 -resize 512x683^ -quality '85' 'out.jpg'
```

With `-define 'jpeg:size` moved to the back the result is correct:
```
magick -limit thread 1 'in.jpg' -auto-orient -crop 1770x2362+379+0 -resize 512x683^ -define 'jpeg:size=512x683' -quality '85' 'out.jpg'
```

I let both calls and one call without `define` as a baseline, run four times and I prepended it with `time` to get these timing measurements:

| `-define` before | `-define` behind | without `-define` |
| ------------- | ------------- | ------------- | 
| 0.236s  | 0.656s  | 0.662s  |
| 0.226s  | 0.619s  | 0.643s  |
| 0.402s  | 0.591s  | 0.670s  |
| 0.231s  | 0.626s  | 0.653s  |

The duration of running magick with `-define` behind the filename is very similar to running magick without `-define`. Judging from the 3x as fast computation with the `-define` command in front of the filename it seems like the optimization only works with that setup.

> Also if anyone has tips on how to get im running with Herd... failing horribly here.

TIL about [Herd](https://herd.laravel.com/). Sounds exciting!
You *could* find a solution for the problem by just working with the imagemagick cli `magick` (used to be called `convert` before ImageMagick version 7).

**Comment by iskrisis** [comment]
> Also if anyone has tips on how to get `im` running with Herd... failing horribly here.

The `im` driver is not related to Herd it execs `convert` command directly. So `brew install imagemagick` should be enough. If its not working you specify `bin` option in Kirby thumbs config (`which convert`)

**Comment by distantnative** [comment]
@iskrisis `bin` option was the missing piece, thanks!
