### ISSUE TITLE
[v4] Can't select multiple blocks via CTRL and ALT keys

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5858]
I can't select multiple blocks via CTRL and ALT keys (Windows 10). Only `win` key works. But in 3.x, CTRL/ALT/WIN keys work great! The issue related with this issue or should I create separate one?

In Windows, the CTRL-SHIFT-ALT keys are usually used for multiple selection, not the WIN key.

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/5626#issuecomment-1774922448_

**Comment by distantnative** [comment]
@afbora can you please try again if the last PRs changed anything?

What happens if you out `console.log(event)` in `Blocks.vue::onKey`? What's the value for `event.metaKey`, `event.ctrlKey` and `event.altKey`?

The line is this `this.isMultiSelectKey = event.metaKey ?? event.ctrlKey ?? event.altKey` - I think `??` in this case is the error that (probablY I) introduced and it should be `||`

**Comment by afbora** [comment]
````
# CTRL Pressed
event.altKey: false
event.ctrlKey: true
event.metaKey: false
event.shiftKey: false

this.isMultiSelectKey: false
````

When I changed `??` to `||` works.

**Comment by distantnative** [comment]
That's the bug then (and the solution). Do you want to add the PR?

**Comment by afbora** [comment]
Also I realized that multiple selecting still doesn't work correctly like before. Can't select when wysiwyg enabled. Selects works only clicking corners of the block (non-wysiwyg areas).

### Steps
1. Add multiple list blocks and fill it
2. Try to select all list blocks (clicking to editable areas that center of the list block)
3. You'll see that can't be selected

Should I create separate issue for this one?

**Comment by distantnative** [comment]
Interestingly, it does work for text and heading blocks for me, which are also based on writer - but see the same issue like you with list blocks. But yes, separate issue always good.

**Comment by afbora** [comment]
Actually doesn't work correctly for text blocks. Selecting all text in block and toolbar appears.
