### ISSUE TITLE
File preview broken for images if "gd" is not enabled.

### ISSUE THREAD

**Issue by stupkad** [k-next/kirby#5859]
## Description
When uploading images via the panel, the preview (both in detail and list view) does not work. Upload works fine, as I can use the uploaded image. Additionally, when i open the v3 panel, the image is shown both in the detail and list view as expected.

I was able to fix this by updating php.ihi, but a hint in the "breaking changes" section would be helpful.

**Comment by tobimori** [comment]
`gd` or `im` has been required by Kirby since v3: https://getkirby.com/docs/guide/quickstart#requirements

**Comment by bastianallgeier** [comment]
I think we can close this. It's in our requirements. In Kirby 3, the issue was just not visible because Kirby would use the original images instead. But I think that is actually a worse way to handle it.
