### ISSUE TITLE
[v4] Field label overflows and icons stack vertically

### ISSUE THREAD

**Issue by manuelmoreale** [k-next/kirby#5866]
## Description
Screenshot should be self explainatory. The field's label doesn't wrap or gets trimmed and as a result first it spills outside of the field container and second it forces the icons to stack vertically.

**Expected behavior**  
The text should either wrap on a new line or have some text overflow in place and the two icons for the file upload/select should stay horizontal.

**Screenshots**  
![Screenshot 2023-10-24 at 10 04 29 AM](https://github.com/getkirby/kirby/assets/1738077/4079f661-2e58-48d3-bfd1-b1fd2f79cb10)

Screenshot is from latest firefox. Latest Safari does have text overflow in place with ellipses but still suffers from the vertical stacking of the icons.

## To reproduce
Create a file field with a very, very long title.

## Your setup
**Kirby Version**  
Kirby 4 - Beta 2

**Comment by afbora** [comment]
I've also like following in narrow screen (600px):

![screen-capture-1711-Test - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/5337412b-a2ae-4de3-8385-64e2898901c8)
