### ISSUE TITLE
[v4] Textarea: doesn't restore size after revert changes

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5871]
## To reproduce

1. Go to textarea field
2. Enter long long text
3. Revert page changes 
4. See issue that textarea size still long (should be restore initial size)

## Your setup
**Kirby Version**  
Beta.3 (v4/develop)

**Comment by distantnative** [comment]
For this to be fixed, we need to add the `.autosize()` command back to the `value` watcher. To not have the event called twice, we should then remove the automatic set-up event listener from `k-autosize`
