### ISSUE TITLE
[v4] Long textarea field scrolls on field input.

### ISSUE THREAD

**Issue by vincentrouleau** [k-next/kirby#5876]
## Description

When working with long text where the field is resized to be larger than the viewport, keyboard inputs triggers a scroll, moving things around and making it impossible to properly edit the text without frustration.

https://github.com/getkirby/kirby/assets/11572524/aea2c7e6-a024-4f1b-84a3-23c7de91043b

The expected behavior would be to ... do nothing.

**Comment by afbora** [comment]
Thanks for the report. This is known issue as https://github.com/getkirby/kirby/issues/5251 and already fixed in beta.3 that will be release soon.
