### ISSUE TITLE
Memcached flush issue

### ISSUE THREAD

**Issue by lukaskleinschmidt** [k-next/kirby#5882]
## Description
I found an issue when using multiple memcached caches.
Here is a small example to replicate the issue.

```php

<?php

// config.php

return [
  'cache' => [
    'a' => [
        'active' => true,
        // 'type'   => 'file',
        // 'type'   => 'memory',
        'type'   => 'memcached',
    ],
    'b' => [
        'active' => true,
        // 'type'   => 'file',
        // 'type'   => 'memory',
        'type'   => 'memcached',
    ],
  ],
];

// Somewhere where kirby is loaded like a template or hook

$kirby->cache('a')->set('key', 'a');
$kirby->cache('b')->set('key', 'b');

$kirby->cache('a')->flush();

dump([
  $kirby->cache('a')->get('key'),
  $kirby->cache('b')->get('key'),
]);
```

The results for the three different cache drivers looks like this:
```php
// using "file" or "memory"
[
  null,
  'b',
]

// using "memcached"
[
  null,
  null,
]
```
I expected the same result across the board for the `file`, `memory` and `memcached` driver.

## Your setup
**Kirby Version**  
4.0.0-beta.2

**Comment by afbora** [comment]
Is this issue only occurs for v4? What about v3?

**Comment by lukaskleinschmidt** [comment]
Only have a `3.9.4` at hand currently. But the same issue. Also tested it on a server and locally.

**Comment by lukasbestle** [comment]
This is unfortunately a known limitation of the Memcached driver:

https://github.com/getkirby/kirby/blob/8bb22df36cd6ef9728153a9081c63b875fce1ffc/src/Cache/MemCached.php#L100

The reason for it is that Memcached does not allow to flush entries by prefix. We could only get a list of all entries, filter them by the prefix and then delete them, but that wouldn't be an atomic operation and Memcached doesn't guarantee that all entries are returned.

A workaround can be to use separate Memcached servers for each cache.

**Comment by lukaskleinschmidt** [comment]
Good to know. was not aware of that. In general other framworks seem to store "tag" like stuff in a separate entry where they just store key references to get around the issue that not all entries might get returned. So you always have a proper list of keys associated to a tag/prefix.

Is this something that would be of interest to add to the core as a PR or just not worth it?
