### ISSUE TITLE
Deprecation Warning: urldecode()

### ISSUE THREAD

**Issue by bogdancondorachi** [k-next/kirby#5895]
## Description
I found this by mistake when I've added two slashes or more after localhost:8000 and followed by a page (ex. localhost:8000//panel)

When two slashes are added I get this deprecated warning:
`Deprecated: urldecode(): Passing null to parameter #1 ($string) of type string is deprecated in C:\Users\bogda\OneDrive\Projects\htdocs\double-check\vendor\getkirby\cms\router.php on line 3`

![image](https://github.com/getkirby/kirby/assets/39380741/196a4b13-50ec-403f-a89e-6eded7c6cf4c)

When more than two slashes are added I get this deprecated notice:
`Deprecated: Automatic conversion of false to array is deprecated in C:\Users\bogda\OneDrive\Projects\htdocs\double-check\vendor\getkirby\cms\src\Http\Uri.php on line 114`

![image](https://github.com/getkirby/kirby/assets/39380741/9bba8349-caf9-425a-8589-429267a1cdd7)

**Expected behavior**  
I gues it should not show any errors or correct the url maybe??

## To reproduce

1. Go to localhost:port and place two or more slashes after it followed by panel or anything else
2. You should see a deprecated warning with two slashes and a deprecated notice when more than two slashes placed

## Your setup
**Kirby Version**  
3.9.7

**Console output**  
nothing relevant

**Your system (please complete the following information)**
 - OS: Windows 11
 - Browser: Edge
 - Version: 118

**Additional context**  
I've tested on other projects and the errors are to be reproduced only on local dev and not on production.

Edit: I've tested this on a starterkit with v4 and it still happens

**Comment by distantnative** [comment]
I've tried to replicate it but I cannot reproduce the deprecation notice.
What I do see is that adding additional slashes in between results in the home page being shown. This could be expected.

**Comment by bogdancondorachi** [comment]
For me, it happens on any project I'm trying [localhost:8000//panel](url) for example. I expect to get the home page but IDK what's up with this deprecation notice.

If you have any ideas on how to test this further, I'm eager to try out

![image](https://github.com/getkirby/kirby/assets/39380741/23411172-9e22-4328-b6bb-69bc7e369c22)

![image](https://github.com/getkirby/kirby/assets/39380741/d7244be7-cea0-4584-a4de-85b689f98a86)

![image](https://github.com/getkirby/kirby/assets/39380741/78f5a05c-6585-43b5-a061-65e6b4ff1901)

**Comment by lukasbestle** [comment]
I can reproduce this with the built-in PHP server.

`parse_url('//panel', PHP_URL_PATH)` returns `null` because the double-slash is treated as the beginning of a protocol-relative URL. So `urlencode(null)` triggers the deprecation notice and the homepage is rendered.
