### ISSUE TITLE
[v4] Blocks field: multiple blocks selection action button position

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5896]
Multiple block selection action button is only available for last block (as index). If I want to select blocks randomly and have many blocks, not useful to click copy/delete button (need to be always find last selected block)

https://github.com/getkirby/kirby/assets/3393422/c2cebf4e-9f02-41ba-8a84-bcd4960c40d8

In v3, actions button was always available for last selected block.

_Originally posted by @afbora in https://github.com/getkirby/kirby/issues/5884#issuecomment-1786678546_

**Comment by bastianallgeier** [comment]
I think this is the same as in v3. It's not great from a UX perspective, but showing the toolbar in every block also feels weird. I would remove the v4 though. It is something that is older than v4.

**Comment by afbora** [comment]
@bastianallgeier No, it's not same with v3.

v3: Buttons are available for last selected block
v4: Buttons are available for last of selected blocks (as index) (try to select indexes: 1-10-2)

**Comment by bastianallgeier** [comment]
Oh, now I understand what you mean. Then we really need to fix that.

**Comment by distantnative** [comment]
Guess we could solve this by removing https://github.com/getkirby/kirby/blob/v4/develop/panel/src/components/Forms/Blocks/Blocks.vue#L641

Just need to see if this has any unwanted side effects

**Comment by afbora** [comment]
@distantnative I didn't understand that line what exactly do but works as expected for me by removing that line. Because I tried copy/paste with and without that line and I can't see the difference.
