### ISSUE TITLE
[v4] Heading blocks preview always shows toolbar

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#5901]
## Description
![CleanShot 2023-11-01 at 21 56 10@2x](https://github.com/getkirby/kirby/assets/29142128/795bde63-c69c-4f64-938c-4abb9785ed66)

When using the Blocks heading preview and setting `marks: false` in the blueprint, the toolbar is still visible as a tiny line (without entries).

Unsure if this is already fixed as I reported a maybe related issue regarding the Image preview caption already

## Your setup
**Kirby Version**  v4.0-beta.2

**Comment by distantnative** [comment]
@tobimori please let us know if you still encounter this with beta.3

**Comment by tobimori** [comment]
nope, fixed
