### ISSUE TITLE
[v4] Panel unaware of custom slug rules

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#5929]
## Description
Kirby allows for the creation of custom slugs rules by setting the static property of the `Str` class:

```php
Str::$defaults['slug']['allowed'] = 'my rules here';
```

These settings are not passed to the `create` and `changeTitle` dialogs.

**Expected behavior**  
The panel should respect the general slug settings.

## To reproduce
Set custom rules in a page model or the config, create a page or update a title. The slug will always be created based on the default settings.

**Additional context**  
Passing `'allow' => Str::$defaults['slug']['allowed']` to the slug field will fix this issue, see here:

- https://github.com/getkirby/kirby/blob/v4/develop/src/Panel/PageCreateDialog.php#L116-L120
- https://github.com/getkirby/kirby/blob/v4/develop/config/areas/site/dialogs.php#L212-L221

**Comment by nilshoerrmann** [comment]
PS: The same issue exists for custom separator settings in `Str::$defaults['slug']['separator']`.

**Comment by distantnative** [comment]
The fix is not quite as easy, as the JS helper will not use the passed allowed characters, but only add them to the default `a-z0-9`, so that wouldn't allow overwriting default allowed with a. more restricting set.

**Comment by nilshoerrmann** [comment]
Wouldn't changing https://github.com/getkirby/kirby/blob/v4/develop/panel/src/helpers/string.js#L173C2-L173C30 to `allowed = allowed ? allowed : "a-z0-9";` solve this issue?

**Comment by nilshoerrmann** [comment]
I understand that this would not be backwards compatible but I'd technically consider this a bug because the panel behaves differently compared to the backend (and the backend actually allows for complete customization).
