### ISSUE TITLE
[v4] Tags field: UX issues

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5939]
## Description

It's really hard to add new tag. Watch the video please:

https://github.com/getkirby/kirby/assets/3393422/dd63d191-fb40-4884-b465-ea1b289fae3b

## Your setup
Kirby Beta.3 & Windows 10

**Comment by bastianallgeier** [comment]
Hm, seems like something is wrong with the focus event on windows. But this is going to be replaced by the new picklist input anyway, so we need to check that again once @distantnative's PR is finally ready.

**Comment by afbora** [comment]
I think also there is a focus issue:


https://github.com/getkirby/kirby/assets/3393422/be4ec95a-cac5-4360-b0b5-1b92ec44908f

**Comment by afbora** [comment]
You mean this one https://github.com/getkirby/kirby/pull/5822?

**Comment by bastianallgeier** [comment]
Yes, exactly.

**Comment by bastianallgeier** [comment]
Should be fixed. Feel free to reopen if it persists for you after the latest changes from today.

**Comment by afbora** [comment]
Yes, seems fixed 🎉
