### ISSUE TITLE
[v4] Pages Section DropDown disappears, before we can select another set of pages

### ISSUE THREAD

**Issue by dennisbaum** [k-next/kirby#5940]
## Description
In a Pages Section with many pages, i would like to use the dropdown to go to another set of pages.
If i click on the dropdown, it disappears instantly.
The Prev/Next-Stepper is working.

**Expected behavior**  
I would expect, to choose another set of pages, by its number in the dropdown,
like it was in v3

**Screenshots**  
![Kapture 2023-11-08 at 09 32 12](https://github.com/getkirby/kirby/assets/562826/55da0c9e-3684-4941-a113-819c14a3c2d9)

## To reproduce
Make a Page with many Subpages, and try to select another Number in the Pages-Section-dropdown

## Your setup
**Kirby Version**  
4.0.0-beta.3

**Console output**  

**Your system (please complete the following information)**
 - Device: MacBook
 - OS: macOS 13.4.1
 - Browser: Chrome, Safari
 - Version: 119

**Comment by bastianallgeier** [comment]
Ahhh, another one of those cases where we need to stop the click event from propagating. @afbora could you give it a go?

**Comment by afbora** [comment]
Sure @bastianallgeier Let me try.
