### ISSUE TITLE
[v4] Structure field: pagination position broken

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5941]
## Description

![screen-capture-1732-Test - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/d41a17fd-1106-421c-aecf-fa22700c604c)

## Your setup
**Kirby Version**  
Beta.3

**Comment by bastianallgeier** [comment]
@afbora could you try to fix it? I think it would be better to put the pagination below the table and not try to have it in the tfoot

**Comment by afbora** [comment]
Already not in `<table>`.

````html
<div class="k-table">
  <table></table>
  <div class="pagination"></div>
</div>

<footer>
  +
</footer>
````

 I've no idea about correct solution. I think pagination should be in left or right of plus icon. Something like following. But table and footer is in separated components.

![screen-capture-1733-Test - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/7334d2b0-b8f2-48c6-bb9f-1ec41834b88c)
