### ISSUE TITLE
[V4] Adding `->widont()` to writer field causes malformed link, if that is the last element

### ISSUE THREAD

**Issue by MikeHarrison** [k-next/kirby#5944]
## Description
I have a writer field set up like this:

`$page->document()->widont()`

If I add a link as the last element in the field, the `->widont()` function causes the link to be malformed on output. For instance this is an email link, added as the last element in the writer field:

`<a&nbsp;href="mailto:test@email.com">test@email.com</a&nbsp;href="mailto:test@email.com">`

**Expected behavior**  

The `->widont()` function should add a non-breaking space between words at the end of paragraphs, but not interfere with links added to the field

## To reproduce

1. Set up a new writer field
2. In the template, output it using the `->widont()` function
3. Add a link as the last element in the writer field

## Your setup
**Kirby Version**  
4.0.0-beta.3

**Your system (please complete the following information)**
 - Device: Mac Mini
 - OS: macOS Sonoma
 - Browser: Firefox
 - Version: 119.0.1

**Additional context**  
The `->widont()` function may not be suitable for use on the writer field, if so please ignore!

**Comment by lukasbestle** [comment]
> The `->widont()` function may not be suitable for use on the writer field, if so please ignore!

Unfortunately I think this is the case. It does not parse HTML and treats its input as plain text.

We have a suggestion here, feel free to upvote that: https://kirby.nolt.io/43

**Comment by MikeHarrison** [comment]
No worries, thanks for the quick response. I will remove it from my writer fields, for the time being at least  👍
