### ISSUE TITLE
Created content files for virtual pages with multi-lang setup and uuid enabled

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#5945]
## Description

Reported by @bnomei, content files creating for virtual pages with multi-lang setup and uuid enabled.

> the uuid in virtual pages. setting the uuid from the content array does not prevent the file to be written anymore. it will also create a different UUID than the one defined in content (until saved from panel view).

Discord: https://discord.com/channels/525634039965679616/1111220342522904706/1172170427532062793

````yaml
<?php // site/models/home.php

use Kirby\Cms\Pages;

class HomePage extends Kirby\Cms\Page
{
    public function children(): Pages
    {
        $children[] = [
            'slug' => 'hello',
            'template' => 'default',
            'model' => 'default',
            'content' => [
                'uuid' => 'XXXXXXX',
                'title' => 'hello',
            ],
        ];

        return Pages::factory($children, $this);
    }
}
````

## Your setup
**Kirby Version**  
3.9.7 & 4.0.0-beta.3

**Comment by distantnative** [comment]
The data is wrong, see https://getkirby.com/docs/guide/virtual-pages/simple-virtual-page

Needs not content, but translations key

**Comment by afbora** [comment]
Sorry, we missed that part. You're right 👍
