### ISSUE TITLE
[v4] Panel: don't show Changes btn in menu if access to site and pages is forbidden

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#5953]
<img width="227" alt="Screenshot 2023-11-11 at 17 51 10" src="https://github.com/getkirby/kirby/assets/3788865/501c8dac-053e-454b-957f-49060cc8dda4">

**Comment by dviate** [comment]
Wouldn't it be better to show this button only when there are changes? It can be confusing for less tech savvy people.

**Comment by distantnative** [comment]
@dviate This will not always be possible as querying all pages for changes could be quite the performance hit
