### ISSUE TITLE
[v4] Display error of the toggle buttons

### ISSUE THREAD

**Issue by gbdesign2023** [k-next/kirby#5954]
## Description
I updated a page from 3.9 → 4.0.0-rc.1 and noticed a display error of the toggle buttons on the iPhone. 
The buttons look flawless on the desktop browsers Chrome and Safari.

![IMG_8008](https://github.com/getkirby/kirby/assets/140849227/dddd08f2-5e2f-47c2-9d14-394dd0bffedd)

**Kirby Version**  
4.0.0-rc.1

**My system**
 - Device: iPhone 11
 - OS: iOS 17.1
 - Browser: Chrome, Safari

**Comment by bastianallgeier** [comment]
Could you please check if this is related to something in your custom css?

**Comment by gbdesign2023** [comment]
@bastianallgeier I have uploaded a fresh starterkit with 4.0.0-rc.1 to my server and added two toggle fields to the blueprint. I have the same problem under Safari and Chome for iOS. I do not use a custom-panel.css.

![IMG_8010](https://github.com/getkirby/kirby/assets/140849227/afad803a-6b60-4b8f-a172-43f0731270bb)

**Comment by texnixe** [comment]
I can actually reproduce this with Safari on iPhone.

**Comment by gbdesign2023** [comment]
@texnixe I was able to find the cause. 
The video should be self-explanatory.

https://github.com/getkirby/kirby/assets/140849227/3ee8a95c-2f38-4c0b-b865-47a833753473

**Comment by bastianallgeier** [comment]
@gbdesign2023 I already fixed it in the PR above.
