### ISSUE TITLE
Object Field with `translate: false` is not dimming appearance 

### ISSUE THREAD

**Issue by dennisbaum** [k-next/kirby#5957]
## Description
An `object-field` with `translate:false` does not change it's appearance, if i switch to a non-default-language,
like other fields does. it only disables the inner fields

**Expected behavior**  
The Object-Field should look like other fileds, with `translate:false`

DE (default) vs. EN:  (compare the text-field below)
<img width="182" alt="image" src="https://github.com/getkirby/kirby/assets/562826/59ceef44-2fa2-4662-9d89-3ba37e847e10">  <img width="174" alt="image" src="https://github.com/getkirby/kirby/assets/562826/36a54040-cfa4-4ac3-a03d-a7ca73004169">

## To reproduce
add an object field and set `translate:false` and switch to a non-default language

## Your setup
**Kirby Version**  
k4-rc.1

**Your system (please complete the following information)**
 - Device: macbook
 - OS: macOS, 13.4.1
 - Browser: Chrome, Safari, FF

**Comment by gbdesign2023** [comment]
This display of inactive fields is identical to version 3. Or what exactly is the error?
![IMG_8012](https://github.com/getkirby/kirby/assets/140849227/2dc123f5-d675-4769-9d5d-99b569514bca)

**Comment by dennisbaum** [comment]
Each non translatable field is changing its appearance when selecting a non-default language. 
For example also structure-fields and date-fields does. But object-fields does not. 
In our opinion that is an visual error in the design-language of the panel - also in k3. 

<img width="1499" alt="image" src="https://github.com/getkirby/kirby/assets/562826/d5bc5bac-ffee-4e7c-baf5-d51d6e36f0ba">
<img width="1486" alt="image" src="https://github.com/getkirby/kirby/assets/562826/8ce9c934-2389-46e0-8599-63aa0567b9a1">

**Comment by bastianallgeier** [comment]
I agree. The object table should look like the structure table above.
