### ISSUE TITLE
[v4] Long help texts overflow the layout

### ISSUE THREAD

**Issue by gbdesign2023** [k-next/kirby#5966]
## Description
Long help texts overflow the layout and do not behave responsively. Although it is a rare case, it can happen that a help text becomes somewhat more detailed. Then the frame does not expand and the text covers other areas.

**Screenshots**  
<img width="708" alt="overflow" src="https://github.com/getkirby/kirby/assets/140849227/57266896-5308-426b-b78a-402f8a6b2032">

The help text is assigned a fixed height of 1.5 rem. The height should be dynamic.
<img width="245" alt="css" src="https://github.com/getkirby/kirby/assets/140849227/b61498d7-f4f8-4a03-a741-99d8f0ed3e55">

The problem does not affect all help texts. I have found blocks with different CSS classes:

```
<footer class="k-field-footer">
<div class="k-help k-field-help k-text">
<p>Help text</p>
</div>
</footer>
```

```
<footer class="k-bar k-collection-footer">
<div class="k-help k-collection-help k-text">
<p>Help text</p>
</div>
</footer>
```

Is the CSS class "k-bar" required? Here, the help text is only assigned a height of 1.5 rem.

**Your setup**
- Kirby 4 RC1

**Your system**
 - Device: MacBook
 - OS: macOS 14.1
 - Browser: Chrome 118

**Comment by yulieyulie** [comment]
+1

**Comment by gbdesign2023** [comment]
The problem was described by another user in the forum:
https://forum.getkirby.com/t/long-help-texts-break-layout-in-kirby-4-rc1-panel/30028/8
