### ISSUE TITLE
page->isOpen() incorrectly returns true when child of page is open

### ISSUE THREAD

**Issue by trych** [k-next/kirby#5972]
## Description

See title.

If there is for example a nav like shown in the [Kirby docs](https://getkirby.com/docs/cookbook/templating/previous-next) on the page:

```php
<nav>
  <ul>
    <?php foreach($items as $item): ?>
    <li><a<?php e($item->isOpen(), ' class="active"') ?> href="<?= $item->url() ?>"><?= $item->title()->html() ?></a></li>
    <?php endforeach ?>
  </ul>
</nav>
```

then the isOpen will evaluate to true, even if a child page of the page in the nav menu is open (and not the page in the nav menu itself).

**Expected behavior**  
page->isOpen() should only return true when the page is actually open.

## Your setup
**Kirby Version**  
Kirby v4 rc1

**Your system (please complete the following information)**
macOS 12.6
all major browsers

**Comment by afbora** [comment]
Maybe you need to use `->isActive()` method. `isOpen` works like that.

https://getkirby.com/docs/reference/objects/cms/page/is-active

**Comment by distantnative** [comment]
Yes, a page is open also when a subpage is active. What you want is isActive
