### ISSUE TITLE
Color field pasting from Clipboard

### ISSUE THREAD

**Issue by mit-stauffer** [k-next/kirby#5981]
## Description
When pasting a value into the new color field (e.g. 808080) without the number sign (#), the color field input changes to #000000.

**Expected behavior**  
The field should accept the value with and without number sign.

## To reproduce
Create a color field and try to paste 808080 instead of #808080

## Your setup
Kirby 4 RC1 (tested with RC2 also)

 - Device: Desktop
 - OS: Windows 10
 - Browser: Firefox 102.0.1 / Chrome Version 119.0.6045.106

**Comment by distantnative** [comment]
That'd be an enhancement, but need to contemplate if this goes against cases where one might not want such a non-color string forced into a hex color

**Comment by gbdesign2023** [comment]
You should bear in mind that some people only want to allow numbers and the # character is already stored in the template. An optional setting would therefore make more sense.

**Comment by distantnative** [comment]
@gbdesign2023 I know you keep suggesting settings, which might seem the logical way: Allow everyone to have it how they like it. But from our experience adding more options and settings really doesn't make the experience better for developer. Kirby is strongest where we try to find a good solution, not adding settings everywhere. It gets overwhelming.

The color field should always store actual color values (hex, rgb or hsl). This is only about whether it accepts on paste values without the `#` - those would for sure need to be transformed to the actual hex value and the hex value would be stored.

**Comment by gbdesign2023** [comment]
@distantnative You're right, of course. Too many options make it too complex, even for you as Kirby developers, and the susceptibility to errors increases proportionally with the functions. 

As an alternative, you can assign a help text to the color-field to guide the editor in the right direction.
<img width="527" alt="colorful" src="https://github.com/getkirby/kirby/assets/140849227/ff6fa32a-2323-4779-849b-c78d2aa46e42">
