### ISSUE TITLE
[v4] Error when focus-cropping an image that's already in the correct ratio in ImageMagick

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#5982]
## Description
I replaced some images and then got this error:
![Screenshot 2023-11-21 at 13 58 51](https://github.com/getkirby/kirby/assets/60777/a205cea1-aa80-4d74-9562-f985a3d77425)

The images are cropped like this:
```php
$image->crop(400, 400, ['crop' => $image->focus()]);
```

The previous images were of arbitrary size and the replaced images were already prepared in the final aspect ratio.
I suspect that this is the culprit:

![Screenshot 2023-11-21 at 14 00 24](https://github.com/getkirby/kirby/assets/60777/60c0695f-225a-47d5-a3fa-f343c9f6ddae)

## To reproduce

You have to call crop with the focus option on an image in the same aspect ratio the image already has. `Focus::coords()` will return `null` and this will break the ImageMagick.php.

## The fix

Moving `$focus = Focus::coords()` into an `if` construct like you already do it in GdLib.php fixes it:

![Screenshot 2023-11-21 at 14 07 29](https://github.com/getkirby/kirby/assets/60777/100e9ba6-7ddf-42ab-934e-497d484d4434)

Almost:

![Screenshot 2023-11-21 at 14 16 23](https://github.com/getkirby/kirby/assets/60777/8c6f2f05-5c70-40d3-8bad-2b66c0a3fe14)

We need to fall back to a supported crop gravity when not using the focus coords:

![Screenshot 2023-11-21 at 14 18 07](https://github.com/getkirby/kirby/assets/60777/2f88ef09-154c-4940-9a71-8a001a40460d)

**Comment by distantnative** [comment]
Love how detailed this report is 💛
