### ISSUE TITLE
Stats section: support for icon

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6006]

**Comment by bastianallgeier** [comment]
Is this about adding it to the docs, or is something not working with the icons?

**Comment by distantnative** [comment]
@bastianallgeier I think we only added it to the components but not the section (backend support)

**Comment by bastianallgeier** [comment]
Oh right.

**Comment by lukasbestle** [comment]
Probably for 4.x though, right?

**Comment by distantnative** [comment]
Yes, I opened the issue as I didn't want to push this last minute into 4.0.0.
It's an easy addition for the next release right after.
