### ISSUE TITLE
[v4] Pagination UI issue in picker dialogs

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#6010]
![image (1)](https://github.com/getkirby/kirby/assets/3393422/39b88d96-a116-4695-b6bd-610323417a01)

Kirby 4.0.0-rc.4
PHP 8.1.23

**Comment by distantnative** [comment]
Due to https://github.com/getkirby/kirby/blob/main/panel/src/components/Dialogs/Dialog.vue#L109

@bastianallgeier do you remember what this was solving?
