### ISSUE TITLE
System view: update status shows 3.10 available while on 4.0

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6013]
![Screenshot_2023-11-28_at_10 46 53_AM](https://github.com/getkirby/kirby/assets/3788865/9e61587f-572c-4ea8-b2ac-07099188b8ae)

**Comment by lukasbestle** [comment]
Purged the URL from the KeyCDN cache and tested it on <https://trykirby.com>. Now shows as "up to date" as it should.
