### ISSUE TITLE
Broken page list in "move page" and "select page" widgets (server error)

### ISSUE THREAD

**Issue by fvsch** [k-next/kirby#6020]
## Description

I’m testing an update of a 3.9 site to 4.0 and it looks like the page list widget used in a few places, namely in the "Move page" dialog and in the page selection widget of the [Retour for Kirby plugin](https://github.com/distantnative/retour-for-kirby), breaks with a server error:

```json
{
    "code": 500,
    "error": "array_merge(): Argument #3 must be of type array, bool given"
}
```

Some URLs for GET requests from the Panel that show this exact error:

- `http://localhost:8000/panel/site/tree?parent=%2Fsite`
- `http://localhost:8000/panel/site/tree?move=%2Fpages%2Fcontact&parent=%2Fsite`

**Expected behavior**  

The request to `/panel/site/tree` doesn't fail.

**Screenshots**  

![Screenshot 2023-11-29 at 11 12 13](https://github.com/getkirby/kirby/assets/243601/97eeeeb4-827f-497e-91d3-5a5303229960)

## To reproduce

I don't have steps to reproduce or a minimal reproduction yet.

I understand this is very little information to go with, and I suspect it's something in my setup (otherwise there would be issues for this filed already). I’m not confident I can make a simple repro through trial and error.

Any pointers on how I could investigate this?

I have `'debug' => true, 'whoops' => true` in my config, but those Panel API requests don't show more information about where the issue occurred.

## Your setup

**Kirby Version**  

4.0.0

**Console output**  
See above for the failing API request. There's another JS error after that, which I suspect comes from not handling the error response from the API when rendering the UI.

**Your system (please complete the following information)**
 - Device: M1 Mac
 - OS: macOS
 - Browser: Chrome
 - Version: 119

**Comment by fvsch** [comment]
Alright, I found the issue.

Using XDebug, I found where the error was generated:

https://github.com/getkirby/kirby/blob/40eae8e8a4e1705412c64de63984376eeaa8b259/src/Panel/Model.php#L115-L120

The issue was that I had one page blueprint (`site/blueprints/pages/error.yml`) which had `image: false` at the root:

```yml
title: Error page
image: false

sections:
  fields:
    # …
```

This faulty value (probably the result of writing blueprints through a lot of trial and error ^^) gets returned as-is by `$this->model->blueprint()->image()`, and since `false ?? []` is `false`, we end up with a PHP error.

So this is definitely my fault and not a bug per se, but this was _very hard_ to identify. Could something be improved here?

There is some blueprint data normalization going on here, maybe there should be more?

https://github.com/getkirby/kirby/blob/40eae8e8a4e1705412c64de63984376eeaa8b259/src/Cms/Blueprint.php#L74-L84

**Comment by fvsch** [comment]
By the way I checked the cookbook (because earlier in the year I had copied page blueprint examples from the cookbook that were triggering bugs in Kirby 3.9, so I was wondering if that was from a faulty example). Couldn't find an instance of `image: false` for a page blueprint. So it's probably just my mistake.

**Comment by distantnative** [comment]
Will need look into this as these lines https://github.com/getkirby/kirby/blob/40eae8e8a4e1705412c64de63984376eeaa8b259/src/Panel/Model.php#L101-L104 should in theory cover the case you describe.

**Comment by distantnative** [comment]
Got it, it's not the `$settings` one but the third argument.
