### ISSUE TITLE
Renaming any file results in "The name must not be empty"

### ISSUE THREAD

**Issue by mit-stauffer** [k-next/kirby#6024]
## Description
I cannot rename ANY files in 4.0.0
When I click rename the dialog appears, but instead of the name it has only a dash in it.

![grafik](https://github.com/getkirby/kirby/assets/27286029/54354a99-6c96-4955-957c-fe994482a294)

After inserting any name I get this error:

![grafik](https://github.com/getkirby/kirby/assets/27286029/c557b875-c2f6-4996-a9e7-f09c7e761f92)

## To reproduce
Install Kirby 4.0.0 Starterkit on Apache 2 with PHP 8.1 or 8.2.12

- I tried it on a local XAMPP on Windows with Apache 2 and PHP 8.1 and a remote server with Apache 2 and PHP 8.2.12
- All requirements are met (https://getkirby.com/docs/guide/quickstart#requirements)
- I had this in 2 client sites I tried to upgrade as well as in the Kirby starterkit
- It doesn't matter what filetype or if it's an existing or recently uploaded file (I can upload and delete, just renaming is faulty)
- I can also set different name during a first upload of a file, but after that, its faulty

**Comment by distantnative** [comment]
@mit-stauffer I'm sorry we missed this regression, we will try to have a patch out soon.

Until then, you should be able to fix this problem by changing the line https://github.com/getkirby/kirby/blob/main/config/areas/files/dialogs.php#L29 to

```php
'allow'     => 'a-z0-9@._-',
```
