### ISSUE TITLE
Custom textareaButtons load but do not function as expected

### ISSUE THREAD

**Issue by scottboms** [k-next/kirby#6028]
## Description

Custom textareaButtons via plugins are listed as a 4.0 feature but seem to have been broken since 4.0b2 based on the sample code shown on the getkirby.com website. I [posted in the forum](https://forum.getkirby.com/t/creating-custom-textarea-toolbar-button/30010) about this a couple of weeks back and have been tracking changes in the RC releases, but this still appears broken in the 4.0 release. It looks like something is broken in how the command is bound in Vue maybe?

I've confirmed this behavior using a clean install of the starterkit and in Chrome, Firefox and Safari so it's not a browser-specific issue.

**Expected behavior**  

1. Button is added to a textarea via the `buttons:` property in a blueprint.
2. `click: () =>` should trigger the appropriate action [as defined in the docs](https://getkirby.com/docs/reference/plugins/extensions/textarea-buttons).

## To reproduce

1. Create a new plugin using the sample code from getkirby.com/releases/4.0 for a new textareaButton in an index.js file.

`panel.plugin("getkirby/custom-textarea-buttons", {
  textareaButtons: {
    highlight: {
      label: "Highlight",
      icon: "wand",
      click: () => this.command("toggle", "<mark>", "</mark>"),
      shortcut: "m"
    },
  }
});`

2. Add the `highlight` button to a textarea field in a blueprint.
3. Load the panel and edit the page.
4. Click on the custom button. Nothing will happen in the textarea -- no markup is inserted whether text is selected or not.

## Your setup
**Kirby Version**  
4.0.0

**Console output**  
`TypeError: this.command is not a function. (In 'this.command("toggle", "<mark", "</mark>")', 'this.command' is undefined)`

**Your system (please complete the following information)**
 - Device: Apple MacBook Pro
 - OS: macOS 13.6.1
 - Browser: Safari
 - Version: 17.1
 - Tested against PHP 8.2 and 8.3

**Comment by distantnative** [comment]
It seems like you need to use the long-form 

```js
click: function () {
  this.command("toggle", "<mark>", "</mark>")
}
```

or 

```js
click() {
  this.command("toggle", "<mark>", "</mark>")
}
```

with the short form `() => ` syntax, our rebinding of `this` doesn't seem to have an effect.

**Comment by distantnative** [comment]
> Arrow functions don't have their own [bindings](https://developer.mozilla.org/en-US/docs/Glossary/Binding) to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this), [arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments), or [super](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/super), and should not be used as [methods](https://developer.mozilla.org/en-US/docs/Glossary/Method).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

So yes, we cannot rebind `this` which we need in this context. Will fix the docs.

**Comment by scottboms** [comment]
Thanks Nico!

**Comment by mattwolff** [comment]
The long-form only works in a single instance of the textarea. When I navigate the panel to another page using a custom button, the button then fails. Or in a blueprint with two different textareas that both use the custom button, the page grinds to a halt.

**Comment by distantnative** [comment]
@mattwolff that sound alike a separate problem, could you please open an issue?
