### ISSUE TITLE
Broken file name modal

### ISSUE THREAD

**Issue by medienbaecker** [k-next/kirby#6032]
## Description
The file name modal seems to be broken. You can't change the name and initially it's something like "-" instead of the actual file name.

**Screenshots**  
![CleanShot 2023-11-30 at 12 39 08@2x](https://github.com/getkirby/kirby/assets/7975568/54f53f38-c409-4887-ab70-9cee7c597f6d)

## To reproduce

1. Upload an image
2. Click on the filename
3. The file name will be something like "-"
4. Try to change the name

## Your setup
**Kirby Version**  
4.0.0

**Console output**  
```
POST http://example.test/panel/dialogs/site/files/filename.jpg/changeName 400 (Bad Request)
```

**Your system (please complete the following information)**
 - OS: macOS
 - Browser: Chrome
 - Version: 119.0.6045.199

**Comment by bastianallgeier** [comment]
We've already fixed it :) https://github.com/getkirby/kirby/pull/6027

**Comment by medienbaecker** [comment]
Sorry, I guess I used the wrong keyword while searching. Best kind of issue for sure :)
