### ISSUE TITLE
Custom textareaButtons: crash when multiple times rendered

### ISSUE THREAD

**Issue by mattwolff** [k-next/kirby#6039]
## Description
Using a plugin to add a custom textareaButton (as described in the docs and [this recent issue](https://github.com/getkirby/kirby/issues/6028)) fails to work reliably, can cause entire page to timeout/crash.

Creating a custom button and registering a click event for it will only works in one single instance of the textarea. That's to say, in one field on one page. Navigating the panel to another page to use the custom button again fails. What's worse, setting up a blueprint with two unique textarea fields that both use the custom button will grind the page to a halt.

**Expected behavior**  
1. Button is added to one textarea or several textareas via the `buttons:` property in a blueprint.
2. `click: function() { // do something }` should trigger the appropriate action.
3. Navigate to a new page or the next textarea, the button should continue to trigger the appropriate action

## To reproduce
Create a new plugin using the sample code from getkirby.com/releases/4.0 for a new textareaButton in an index.js file.
Use a long-form function rather than arrow function as [uncovered here](https://github.com/getkirby/kirby/issues/6028)
```
panel.plugin("getkirby/custom-textarea-buttons", {
  textareaButtons: {
    highlight: {
      label: "Highlight",
      icon: "wand",
      click: function() {
        this.command("toggle", "<mark>", "</mark>")
      },
      shortcut: "m",
    },
  }
});
```
**Test 1: Sibling Failure**
Add the highlight button to a textarea field in a blueprint.
Load the panel and edit the page.
Click on the custom button. It should work. 
Navigate to a sibling page and click the custom button. Nothing will happen in the textarea -- no markup is inserted whether text is selected or not.
**Test 2: Multiple textareas crash page**
Add the highlight button to two different textarea fields in a blueprint.
Load the panel and edit the page.
The page times out / crashes.

## Your setup
**Kirby Version**  
 4.0.0

**Your system (please complete the following information)**
 - Device: Apple iMac
 - OS: MacOS 12.7
 - Browser: Firefox 120.0 and Safari 17.0
 - PHP 8.2

**Comment by distantnative** [comment]
Corresponding console error

```
[Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <KTextareaToolbar> at /Users/nhoffmann/Sites/kirby/sandbox/kirby/panel/src/components/Forms/Toolbar/TextareaToolbar.vue
```

**Comment by scottboms** [comment]
Confirming this is definitely an issue after running into it myself last night. Hoping a fix for this might land in one of the next updates.

**Comment by paresy** [comment]
Just wanted to give a +1 that we are affected by this too, which is blocking our Kirby 4.x upgrade 😄

**Comment by bastianallgeier** [comment]
I finally found a fix for it. We "just" need to test it properly. But so far it seems to be working great.
