### ISSUE TITLE
Kindly add Twitter icon

### ISSUE THREAD

**Issue by olivertedwards** [k-next/kirby#6045]
I know realise there is a great deal of debate around the whole Twitter situation. However, I ask kindly if we could add the Twitter icon to the lab, since every other social media icon is present?

**Comment by afbora** [comment]
Unfortunately we haven't plan to add Twitter icon at future. As workaround you can add own icons via extension:

https://getkirby.com/docs/reference/plugins/extensions/icons

**Comment by lukasbestle** [comment]
In fact we've just removed it in Kirby 4: https://getkirby.com/releases/4.0#breaking-changes
We provide a plugin you can install if you need it. It's linked from the changelog :)
