### ISSUE TITLE
Support Internationalized Domain Names (IDNs)

### ISSUE THREAD

**Issue by nmanngit** [k-next/kirby#6046]
## Description
It's possible to create domains and thus email addresses with special characters like umlauts. Kirby however doesn't yet allow us to use them without converting them to punycode first.

**Expected behavior**  
Support IDNs e.g. in the Kirby email input field.

## To reproduce
1. Log into the Kirby panel
2. Create a new user
3. Enter email address: `höh@exämple.com`

Kirby should recognise the email as valid, but it doesn't. One would need to manually convert it to `xn--hh@exmple-z2a7q.com` which is cumbersome.

## To fix
In the panel `TextInput.vue` component, you use `vuelidate` (version ^0.7.7). Either use custom validation logic or update vuelidate to a newer version as a quick test with 2.0.1 worked for me.

## Your setup
**Kirby Version**  
4.0.1

**Comment by distantnative** [comment]
I don't think unfortunately it's just a matter of `vuelidate` - we've removed it for v5 and rely more on native HTML validation, but seems like `<input type="email">` doesn't like those either.

**Comment by bastianallgeier** [comment]
Yep, it seems like Safari's email input does not like IDNs. I really think we cannot solve it because of that. Even once we get rid of vuelidate, we still need to wait for Safari to fix it as well.
