### ISSUE TITLE
[Panel] Pages Section wont start on Page 1 on Reload Panel Page? Bug or Feature?

### ISSUE THREAD

**Issue by dennisbaum** [k-next/kirby#6052]
## Description
beforehand: i am not sure if this is a bug or a feature:
If we use the pager of a pages section to page 2 and hard reload the page or go back to another page and come back to the first page, the pager of the pages section is still on page 2
(like the number stored in the local storage btw.)

**Expected behavior**  
Our editors expect to be on page 1 of these pages section, if they reload the page or come back from another page

**Screenshots**  
<img width="549" alt="image" src="https://github.com/getkirby/kirby/assets/562826/1719abc7-d3f8-47bc-ada0-bee6cdc6e301">
<img width="406" alt="image" src="https://github.com/getkirby/kirby/assets/562826/84aa27b1-9a48-4890-8d7b-975ab355a099">

## To reproduce
Go to a Page with many subpages. Use the pager of the pages section to the next pages-set and reload the panel page.
The set of pages in the pages section should still be from f.i. 21-40 

## Your setup
4.0.0
MacOS, Chrome 119

Like i said, i am not sure if this behavior is intended or not, but some editors have asked.
Tnx!

**Comment by gbdesign2023** [comment]
You wrote that you are using version 4.0.0. 
Have you also tested it with 4.0.1?

**Comment by distantnative** [comment]
@gbdesign2023 Nothing was changed there. Neither from v3.9 to 4.0.0 nor to 4.0.1

It is indeed intentional, where the pagination page gets stored in localStorage.

**Comment by bastianallgeier** [comment]
This is indeed intended. We didn't store the pagination before and it was a feature request years ago to do that.

**Comment by dennisbaum** [comment]
ok. thank you guys for clarifying
