### ISSUE TITLE
No real URL in text-block rendering

### ISSUE THREAD

**Issue by mountbatt** [k-next/kirby#6054]
## Description
When I add a page-link in to a "text" block, it renders not like `mypage.com/restaurant`. Its more like `mypage.com/@/page/IvUPpa7KNNiLQpJs`

I think the writers-field does not render page-urls correctly. 

I was able to reproduce it in the trykirby.com demo too.

**Screenshots**  

![image](https://github.com/getkirby/kirby/assets/2411246/3e7dc1f5-35b0-4301-b8e9-30cf486acfbc)

![image](https://github.com/getkirby/kirby/assets/2411246/cfad71a0-c93f-4289-aef6-4fe9261e8cdb)

## To reproduce
I was able to reproduce it in the trykirby.com demo too.

1. Go to a page where you can add blocks
2. Click on "Add", add "Text"
3. Mark a word in your text and use the node "Hyperlink" to add a page-link
4. Set it to "Page" and choose a page.

## Your setup
**Kirby Version**  
v4.0.1

**Comment by gbdesign2023** [comment]
This is not an error. It is a UUID. 
https://getkirby.com/docs/guide/uuids

It must be rendered as a readable link in the output, e.g. with this function:
https://getkirby.com/docs/reference/templates/field-methods/permalinks-to-urls

**Comment by mountbatt** [comment]
Okay, thanks @gbdesign2023 , thanks for clarifying! I never thought that the output of UUIDs in a text-block is the default. I got it working now by overriding the /blocks/text.php output. Thanks again!

**Comment by gbdesign2023** [comment]
@mountbatt I had also assumed that links were permanently rendered automatically. However, this was not the case. The solution is therefore also quite fresh for me. Greetings from Cologne to Cologne.
