### ISSUE TITLE
Content of a deleted page reappears after creating a new page with same title

### ISSUE THREAD

**Issue by jnetzlr** [k-next/kirby#6057]
## Description
When you delete a draft and subsequently create a page with the same name, all the content reappears. This occurs even after deleting the folder in 'site/cache' and checking the 'content' folder.

**Expected behavior**  
Deleting a page should delete the content permanently.

**Setup**
4.0.1

**System**
 - OS: macOS 14.1.2
 - Browser: Chrome
 - Version: 119

**Comment by afbora** [comment]
I can't reproduce the issue.

**Comment by bastianallgeier** [comment]
This could either be a cache problem on the server level or maybe the changes didn't get removed from local storage

**Comment by distantnative** [comment]
@jnetzlr Did you delete the page/draft via the Panel or manually in the filesystem?

**Comment by jnetzlr** [comment]
Ok, the content is still stored on local storage.

I tried again, and it only happens if the page I'm deleting has **unsaved changes**. When I delete that page, the content is still there in local storage.

If I create a new page with the same name, the content appears with broken images.

**Comment by bastianallgeier** [comment]
I thought that this might be the case. That's definitely an issue on our end. The local storage changes must get deleted of course

**Comment by distantnative** [comment]
Can confirm it via the Panel

**Comment by distantnative** [comment]
Source is that it seems we're applying inconsistently `?language=null` (or actual language code) to the id used for the store. So the unsaved changes can be stored under an id with that suffix, while the delete dialog dispatches a remove event without the suffix.

**Comment by bastianallgeier** [comment]
Will be fixed in 4.1. We've already added it to the develop-minor branch.
