### ISSUE TITLE
Page create permission false, but create dialog can still be opened

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#6064]
## Description
When I migrated to Kirby 4, I replaced the Pages Display Section plugin with the new ability to query pages and set the page creation to false to retrieve the same UX as the plugin. With the Pages Display Section plugin, the “+Add” button is hidden and there’s no link to open the page creation pop-up on “No pages yet.”

Indeed, I often have user roles that I want to be able to open a page but not create a new one. And I’d love not to let them think they can do it, but in fact they can’t.

But now with the new K4 page filter (query) even if the page create permission is set to false, we have the possibility to open the creation page pop-up, it implies that you can do it. So you try … and only then are you told that it’s not possible.

I find this misleading from a UX point of view.

Wouldn’t it make more sense to hide the “+Add” button and disable the link to “No pages yet” when the permission to create the page is set to false?

**Expected behavior**  
When the page create permission is set to false, the "+Add" button and the link on "No pages yet" are respectively hidden/disabled

Sorry, it's not really a code bug, but more a UX bug to me.

**Comment by texnixe** [comment]
This is a duplicate of this one which has been closed by the stale bot: https://github.com/getkirby/kirby/issues/1855

**Comment by distantnative** [comment]
@vauvarin @texnixe I canot reproduce this in 4.3

Signed in with a user with the role

```yml
permissions:
  pages:
    create: false
```

and the Add button is not show in neither the list nor the table layout:
<img width="1095" alt="Screenshot 2024-09-01 at 5 54 13 PM" src="https://github.com/user-attachments/assets/1a9b09c3-5755-4361-b971-7b7686ed1577">
<img width="1116" alt="Screenshot 2024-09-01 at 5 54 09 PM" src="https://github.com/user-attachments/assets/7094efb0-536d-4819-b615-9f9c4f5d735e">

There is not difference for me whether using the `query` option or not.
