### ISSUE TITLE
Assets crop issue: `The method: "focus" does not exist` 

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#6065]
## Description

I've found an issue in my plugin. There is also in forum discussion: https://forum.getkirby.com/t/custom-image-not-showing-since-kirby-4/30259

Try to crop a asset like following. You'll get error: `The method: "focus" does not exist` 

````php
$asset = new Asset("sample.jpg");
$asset->crop(400, 300)->url();
````

## Your setup
**Kirby Version**  
4.0.1

**Comment by distantnative** [comment]
I suspect this line https://github.com/getkirby/kirby/blob/main/src/Cms/FileModifications.php#L179
We should probably wrap it with a check for `instanceof ModelWithConent`
