### ISSUE TITLE
Sidenav stuck as open on safari

### ISSUE THREAD

**Issue by bogdancondorachi** [k-next/kirby#6066]
## Description
As mentioned on Discord, a colleague of mine is facing a bug on Safari where the sidenav is stuck as open (also it seems to appear as the modal nav from the mobile). No actions could be done in the panel cause of the overlap and no actions can fix it as reloading, resizing the window, etc... You simply get the below view whenever you go to the panel. 

**Screenshots**  
![image](https://github.com/getkirby/kirby/assets/39380741/11ee3d87-1c0b-4599-a3c1-14356a17b340)

## Your setup
**Kirby Version**  
4.0.1

**Console output**  
nothing relevant 

**Your system (please complete the following information)**
 - Device: MacBook
 - OS: MacOS Ventura 13.0
 - Browser: Safari
 - Version: 16.1 (16614.2.9.1.13, 16614)

**Additional context**  
We are open to trying more tests if you have suggestions to get to the end of this.

**Comment by distantnative** [comment]
@bogdancondorachi is it really everytime going to the Panel?

I have encountered this bug with Safari (sadly clearly a bug within Safari of tripping over container queries) but only when seizing the window to very narrow and back.

**Comment by davidjablonski** [comment]
Have encountered the same bug, there seems to be a very narrow area next to the navigation that actually closes it, on the remaining screen I can interact with elements beneath (i.e. navigate to different site in the panel) but navigation won’t close.

https://github.com/getkirby/kirby/assets/9139357/c71488f4-f676-4de7-a5d2-05f070e9a7ff

**Comment by distantnative** [comment]
@davidjablonski same question to you, what are the steps for this to occur or reproduce on your end?

**Comment by davidjablonski** [comment]
For me, this always occurs when opening the sidebar in a Safari window that’s wider than ca. 860px. Stays the same when reloading the page.

**Comment by distantnative** [comment]
@davidjablonski also on a similar Safari version like @bogdancondorachi ?

**Comment by davidjablonski** [comment]
Yes, I’m also on Safari 16.1. Will test with Safari 17 asap and will let you know if the bug persists.

**Comment by davidjablonski** [comment]
Bug is not persisting in Safari 17, just tried and checked – sorry for not doing so earlier.

**Comment by bogdancondorachi** [comment]
Indeed, my colleague updated to Safari 17 and the bug it's not present anymore. Unfortunately, I'm not able to debug this further but hopefully there's enough info to look into the issue on Safari 16.

**Comment by distantnative** [comment]
Thank you! I think we do have all the info needed, will look more if we can find a bugfix somehow or if it's really just a nasty Safari bug that needs to be fixed browser-side (as it seems to have been with Safari 17)

**Comment by distantnative** [comment]
@davidjablonski @bogdancondorachi has this been resolved for you with Apple's updates to Safari 16?

**Comment by distantnative** [comment]
Closing this as it seems to not be an issue anymore. Please let us know if you experience otherwise.
