### ISSUE TITLE
Button label overflow in the password reset UI when in french.

### ISSUE THREAD

**Issue by vincentrouleau** [k-next/kirby#6068]
![image](https://github.com/getkirby/kirby/assets/11572524/0643f2ca-d34a-45b3-a99b-4d7cef1f4349)

Button label overflow in the password reset UI when in french.

**Comment by distantnative** [comment]
@hotdoy Do you think there could be a short expression or is that the best term in French and the UI just really has to adapt?

**Comment by vincentrouleau** [comment]
Simply `Réinitialiser` should be enough. I mean, the context is pretty clear at that point.

**Comment by distantnative** [comment]
Realizing the English version is also rather long with `Confirm the new password…`
