### ISSUE TITLE
Structure field: Third item automatically added when hitting `Cmd-Enter` in the second item

### ISSUE THREAD

**Issue by doldenroller** [k-next/kirby#6076]
## Description

When a Structure contains two or more fields that are required, the field can not be saved and a form error is thrown.

**Expected behavior**  

The field should be saved.

**Screenshots**  

<img width="390" alt="Bildschirmfoto 2023-12-18 um 11 22 31" src="https://github.com/getkirby/kirby/assets/29595303/4acc9bb3-4ba7-4e70-b0b5-90c54d1e45e3">
<img width="497" alt="Bildschirmfoto 2023-12-18 um 11 22 41" src="https://github.com/getkirby/kirby/assets/29595303/df1c284b-3e18-46c5-8f82-52966960e1f2">

## To reproduce

1. Create Structurefield in Page Blueprint
2. Add two or more Fields withe the property ````required: true````
3. Add new Structureentry in Panel and save changes

## Your setup
**Kirby Version**  

4.0.1

**Console output**  

**Your system (please complete the following information)**
 - Device: Mac
 - OS: macOS
 - Browser: Firefox Developer
 - Version: 121

**Additional context**  

A little bit of topic, but is it intended that an empty Entry is added to the Structure when the input is aborted? It happens when you open a new Structureentry and click outside the Drawer or the Trashicon.

**Comment by afbora** [comment]
I can't reproduce the issue. Here my field:

````yaml
fields:
  addresses:
    label: Addresses
    type: structure
    fields:
      street:
        label: Street
        type: text
        required: true
      zip:
        label: ZIP
        type: text
        required: true
      city:
        label: City
        type: text
        required: true
````

**Comment by doldenroller** [comment]
Ok, it's a little bit weirder than expected... I just tried it again with a fresh Starterkit and the error doesn't appear when the page is in draft mode, or the structure item is submitted with submit button (small checkbox). But when the page is listed and I click outside the drawer, or just click enter the error appears again.

**Comment by afbora** [comment]
Could you list step by step or record short screen cast, please? I couldn't still reproduce the issue.

**Comment by doldenroller** [comment]
Sorry it me a while. But Iguess I've figured it out how I created that error, it was a mixture from my workflow and the behaviour of the structure field. So my title isn't quiet correct.

When you open a new structure field with an textarea in it and you type something in the textarea, you could submit the structure entry by pressing command and enter. This adds an extra row to the structure (I missed that) and then the error appears that there is a failure in the structure and the page can't be saved.


https://github.com/getkirby/kirby/assets/29595303/00c46e6d-5128-45d5-a480-b7e860dda8fb

So sorry that I was on the wrong path with that error.

**Comment by afbora** [comment]
Thanks for detailed report. I can't still reproduce the issue on Windows (CTRL + Enter). Maybe this is only occurs in MacOS.

**Comment by lukasbestle** [comment]
@doldenroller So the issue is just that `Cmd-Enter` unexpectedly creates another structure item, correct?

I cannot reproduce this on macOS as well. Could you please try with a reduced blueprint in the Starterkit? If it still happens, please post the full blueprint you used as well as steps to reproduce. Thanks :)

**Comment by doldenroller** [comment]
Yes it only appears when you hit ````Cmd-Enter````. And I just found out that it only happens when there is already one entry in the structure.

https://github.com/getkirby/kirby/assets/29595303/b4abfd0f-706c-460c-b9bb-97d3449f5b0b

In the screencast you will that there is one entry in the structure and when I add the second entry with ````Cmd-Enter```` the third one get appended immediatly.

I used a fresh plainkit (4.0.3) and just added a structure-field with a textarea to the default-blueprint.

````
teststructure:
  label: Structure Test
  type: structure
  fields:
    text:
      type: textarea
````

Another thing that is if you cancel a new entry, it is still added to the structure. This is also different to the Kirby-3 structure-field, but probably a different issue.

**Comment by lukasbestle** [comment]
Thanks for the updated info and the video. Unfortunately I still cannot reproduce the issue of the third structure item being added automatically on `Cmd-Enter`.

> Another thing that is if you cancel a new entry, it is still added to the structure. This is also different to the Kirby-3 structure-field, but probably a different issue.

That's intended. We often got the feedback that people discarded structure items by accident when they closed the item. So we now keep the content when the drawer is closed. If you want to discard the item, you can use the trash button in the drawer.
