### ISSUE TITLE
HTTPS warning with relative URL set in config.php

### ISSUE THREAD

**Issue by dgsiegel** [k-next/kirby#6078]
## Description
As described here https://getkirby.com/docs/reference/system/options/url I've set the base URL to relative URL without a host:

```
return [
  'url' => '/'
];
```

This mostly to get absolute URLs without a host on all my links, menus etc.

On the system page (`/panel/system`) I now get the following warning: `We recommend HTTPS for all your sites`

But the page is loaded with https.

**Expected behavior**  

I'd expect Kirby to auto-detect the usage of https similar to when no url was set and not guess it based on the fixed string in config.php

## Your setup
**Kirby Version**  
4.0.1

**Comment by lukasbestle** [comment]
By setting the `url` option, you disable all auto-detection of the URL environment, the entire Kirby core will only use the information you hardcoded.

I understand that the warning on the system page may be confusing in this situation. However I'm afraid we cannot use auto-detection in this specific place when auto-detection has been disabled globally.

What is your use case for setting the `url` option to `/`?

**Comment by dgsiegel** [comment]
> What is your use case for setting the `url` option to `/`?

A matter of consistency when adding assets vs. links in the HTML, as well as being able to switch domains more easily.

**Comment by lukasbestle** [comment]
> A matter of consistency when adding assets vs. links in the HTML

If you consistently use Kirby's methods and helpers (like the `url()` helper) to generate your links, they will be consistent throughout your site.

> being able to switch domains more easily

I see. To be honest I feel like this is not something very common.

---

To explain why I'm asking: The `'url' => '/'` option was only meant for use cases like static site generation where there is no domain or the output should be fully independent of the URL the site is accessed from. In these use cases, the system view in the Panel is not relevant.

**Comment by dgsiegel** [comment]
> > A matter of consistency when adding assets vs. links in the HTML
> 
> If you consistently use Kirby's methods and helpers (like the `url()` helper) to generate your links, they will be consistent throughout your site.

True, but one might add static assets such as JS, CSS etc. without a helper, and in those cases you wouldn't really add the domain.

> I see. To be honest I feel like this is not something very common.

I'll do it all the time when switching between localhost, staging, prod etc.

I've now found a workaround by modifying `index.php` like this:

```
<?php

require 'kirby/bootstrap.php';

$kirby = new Kirby([
  'urls' => [
    'index' => '/',
  ],
]);

echo $kirby->render();
```

When in need for the full URL incl. domain (e.g. for OG images) you can then use `<?= $kirby->url('base', true)->toString() ?>`
 
The panel system page seems to be happy with this.

**Comment by lukasbestle** [comment]
Regarding multiple environments: It is possible to [configure them all](https://getkirby.com/docs/reference/system/options/url#url-override-per-domain) and [pin the production domain on the production host](https://getkirby.com/docs/reference/system/options/url#url-override-for-the-production-deployment).

I'm closing this issue for the reasons I have explained. Thanks for sharing the workaround.
