### ISSUE TITLE
[v3] hasErrors is missing in the Form class (same as #5587 for v4)

### ISSUE THREAD

**Issue by seibert-io** [k-next/kirby#6080]
## Description
[Issue 5588](https://github.com/getkirby/kirby/issues/5587) applies to Kirby 3 as well, but was only reported for /fixed in Kirby 4.

Duplicate of the original issue description by modufolio:

hasErrors() does not exist in the form class

abstract class ModelWithContent

Line: 399

	/**
	 * Checks if the data has any errors
	 */
	public function isValid(): bool
	{
		return Form::for($this)->hasErrors() === false;
	}
Solution would be:

	/**
	 * Checks if the data has any errors
	 */
	public function isValid(): bool
	{
		return Form::for($this)->isValid();
	}

## Your setup
**Kirby Version**  
3.9.8

**Comment by afbora** [comment]
I understand, but unfortunately v3 will no longer receive any updates except security updates. The latest version of K3 is 3.10 and only includes PHP 8.3 support.
