### ISSUE TITLE
Console errors when deleting page from PageView

### ISSUE THREAD

**Issue by GiantCrocodile** [k-next/kirby#6082]
## Description
I deleted an old draft. Then I clicked on the "Changes" button in the bottom left corner. There the deleted draft was listed which confused me for a second. Then I clicked on the deleted draft and saw that I can revert the deletion. I did so and saw that the draft has been restored. Now I deleted the page again to delete it permanently but after clicking again on "Changes", there are no changes left. So basically the first time the page is listed there. After a second delete, it's gone forever without being able to restore it again.

**Expected behavior**  
2nd time deleting a page should have the same effect/behavior as the first time regarding the "Changes" button.

## Your setup
**Kirby Version**  
v4.0.2

**Console output**  
no error logged

**Your system (please complete the following information)**
WAMP, latest Firefox

**Additional context**  
multilang website

**Comment by afbora** [comment]
I can't reproduce the issue on single and multi-lang setup. But I'm pretty sure this is same issue with https://github.com/getkirby/kirby/issues/6057 that already fixed and will be release 4.1.0.

**Comment by afbora** [comment]
@GiantCrocodile Could you test with fixed branch please? [kirby-develop-minor.zip](https://github.com/getkirby/kirby/files/13753325/kirby-develop-minor.zip)

**Comment by GiantCrocodile** [comment]
I will test this today or tomorrow and get back to you @afbora.

**Comment by GiantCrocodile** [comment]
@afbora I tested this with the kirby develop minor package. The behavior is different now but I'm not sure which of the two (whether it's possible to restore a deleted draft) behaviors is intended. Furthermore I might have found another minor bug about unhandled values/exceptions:

1. Create a new page like 'test123'
2. Delete the page
3. Click on 'Changes' button
4. Nothing is shown. You can't restore the deleted draft.

If you do the same again with a new draft called 'test1234' now but delete the page while you are inside the edit mode of the page (clicked on the 'test1234') and then choosing delete, triggers this in the console:

![grafik](https://github.com/getkirby/kirby/assets/6271057/88df9d37-ab3d-46fa-ba40-680eabd783d2)

Likely because it wants to update some binding that doesn't exist anymore due to the deletion in the prior step. In both cases I can't restore the page anymore now.

**Comment by distantnative** [comment]
@GiantCrocodile 

> while you are inside the edit mode of the page

Do you mean just being inside that page in the Panel or anything more specific that you call edit mode?

**Comment by GiantCrocodile** [comment]
@distantnative I mean being inside the page you want to delete then (basically where you can type/change the content of the fields of the page like when you write a new page/draft. No special term specific/special to my project.

**Comment by distantnative** [comment]
@GiantCrocodile Thanks, I can reproduce that and it's definitely a bug/regression. 

That you cannot restore deleted pages from the changes dialog is expected though.
