### ISSUE TITLE
New Link field inside writer causes wrong Urls

### ISSUE THREAD

**Issue by frankziski** [k-next/kirby#6084]
## Description
When adding a link inside a writer field with the new link-field https://getkirby.com/releases/4.0#link-field the links to internal pages or files are wrong. I linked to an uploaded pdf file inside the text and the result in the dom is "https://mydomain/@/file/gLRTn856xRNEInrG" which results in a 404 error when clicking. The same happens when linking to an internal page. It only happens inside the writer, using the link field in the blueprint itself works fine.

**Screenshots**  
![Screenshot 2023-12-21 132433](https://github.com/getkirby/kirby/assets/37303044/307433ce-8029-4252-8a51-b99894c214cf)
![Screenshot 2023-12-21 132413](https://github.com/getkirby/kirby/assets/37303044/87110c83-80fe-43ce-b642-d575b9638727)

## To reproduce

1. Using a writer field in a blueprint
2. Select any text
3. Set a link from the overlay and choose an internal page or a file

## Your setup
**Kirby Version**  
4.0.2

**Comment by gbdesign2023** [comment]
@frankziski It's not a bug, it's a feature:
https://getkirby.com/docs/guide/uuids#permanent-urls

**Comment by frankziski** [comment]
Thanks! Well its good if you have access to the link via the command described in your link. But the links inside the writer field are set automatically when rendering the whole writer field..

Am i seeing it right that the only option i have is to disable permalinks to get it to work?

**Comment by gbdesign2023** [comment]
This is the advantage of permalinks:

- _Because UUIDs never change and are unique across the site, they are perfect for permanent shortlinks (permalinks) that can be used for sharing._

Permalinks are rendered in the PHP-template with 
`<a href="<?= $page->permalink() ?>">Permalink</a>`
into readable links. 
Therefore, there should be no problems in Frontent. 
Hardcoding of links is therefore no longer necessary.

**Comment by frankziski** [comment]
I sure see the Advantage. But my problem is: the rendered links are coming from the writer field itself and they dont work. I always get 404 errors, both on my local xampp and on a live server with a subdomain. The links always Produce 404 errors.

Writer fields in the template are rendered with 
`<?= $page->writerfield() ?>`
And inside the writer field in the panel i set the link. So i cant use the syntax you described because its done by kirby directly. Do you get my problem?

**Comment by afbora** [comment]
I see that it doesn't work for subfolder setup even `url` option is set.

Output is:

````html
<a href="/@/file/h5caJ4Umo9oXt1i0">click me</a>
````

Should be like that:

````html
<a href="http://example.com/subfolder/@/file/h5caJ4Umo9oXt1i0">click me</a>
````

Duplicated of https://github.com/getkirby/kirby/issues/6003
