### ISSUE TITLE
Cannot create file with unknown mime type (pass null to string argument)

### ISSUE THREAD

**Issue by rasteiner** [k-next/kirby#6095]
## Description
Creating a file with unknown mime type via `$page->createFile(...)` fails with the error:
```
Kirby\Filesystem\Mime::matches(): Argument #1 ($test) must be of type string, null given, 
called in /var/www/html/kirby/src/Filesystem/File.php on line 284
```

**Expected behavior**  

The file should be created anyway, the mime type could be reported as `application/octet-stream`, for example, or `Mime::matches` should take `?string` as first argument and handle `null` somehow. 

## To reproduce
1. Create a file with unknown mime type (for example an EMF file) and put it into the path `$src`
2. Import it into Kirby: 
    ```php
    $page->createFile(['source' => $src,
                'filename' => 'test.emf',
                'parent' => $page,
                'content' => [
                    'uuid' => 'test'
                ]]);
    ```
3. See error

## Your setup
**Kirby Version**  
4.0.2

**Additional context**  
Related: https://github.com/getkirby/kirby/issues/5881

The problem is here:
https://github.com/getkirby/kirby/blob/4.0.2/src/Filesystem/File.php#L278-L286

```php
$mime = $this->mime();          // returns ?string
Mime::matches($mime, $pattern); // expects string
```

**Comment by lukasbestle** [comment]
I agree it's a bug that we pass a nullable value into a method that cannot accept `null`. I have prepared a fix on the branch https://github.com/getkirby/kirby/tree/fix/6095-file-match-mime.

However it won't result in the behavior you wrote down as expected. The code in question can only be called if the file blueprint contains an `accept` rule/allowlist for the MIME type. If we cannot detect the file's MIME type but only specific MIME types are allowed, we cannot let the file through IMO.

How does your file blueprint look?

**Comment by rasteiner** [comment]
> How does your file blueprint look?

I don't specify a file template in the createFile call, so I don't know where that `mime` rule comes from. I would have guessed the default file blueprint would be used. Does the default file blueprint expect a specific mine type? 
Or does the createFile call search for file templates in the parent page blueprint?

**Comment by lukasbestle** [comment]
Sorry for the delay, will get back to you.

**Comment by rasteiner** [comment]
I've worked around the issue in my project and honestly forgot about it, no hurry for me :)

**Comment by lukasbestle** [comment]
It's indeed coming from the default in this line:

https://github.com/getkirby/kirby/blob/a537a4d95c8db03ecaf3ebfd5c6a7747357fde7c/src/Cms/FileBlueprint.php#L153

I'd say it's intended in this case that the file creation fails. If we were to omit the default, unexpected file types could be uploaded, which can be a security risk.

However the type error you got is of course a bug and will be replaced with a proper error message.

The proper solution for allowing custom file types is to allow their extensions in a custom file blueprint.
