### ISSUE TITLE
Image block doesn’t crop

### ISSUE THREAD

**Issue by guidoferreyra** [k-next/kirby#6096]
## Description
When selecting crop on image block, it doesn’t crop the image on the frontend. Is this intended? If yes is kind of confusing to have a feature like this that doesn’t work by default.

## To reproduce

1. Add a Image block 
2. Toggle on "Crop"  field
3. Check frontend, image is not cropped.

## Your setup
**Kirby Version**  
4.02.

**Comment by gbdesign2023** [comment]
@guidoferreyra Without knowing the code from your blueprint and the code for the output in the template, it is difficult to analyze your problem. Have you already carried out the steps from the reference?
https://getkirby.com/docs/reference/objects/cms/file/crop
Your question would be better answered in the [forum](https://forum.getkirby.com/). This is more about error messages.

**Comment by guidoferreyra** [comment]
Hi @gbdesign2023 sorry I forgot to mention that I’m using default block snippets and the simple `<?= $page->myBlocksField()->toBlocks() ?>`
This is not something that is affecting a specific project of mine, I know how can I crop the image and make it work, in fact the new starterkit has this covered with custom snippets. 

My point is the default image block has the crop function by default but it does nothing with Kirby out of the box.
Every field on the block have an impact when the block is "rendered" with default snippets, so to me it‘s odd that crop doesn‘t do anything. 
![imagen](https://github.com/getkirby/kirby/assets/1755590/1ecff0f0-a8af-4a29-8ac3-47d30702d2d6)

**Comment by gbdesign2023** [comment]
As far as I know, the image in the starter kit is only modified with CSS, but not actually cropped. 
There was a similar question about the definition of the aspect ratio.
https://forum.getkirby.com/t/default-image-block-cropping-ratio/26788/

**Comment by lukasbestle** [comment]
The image block indeed does not crop the image by default. This is the case for two reasons:

- The block supports images from an external source (= loaded via an external URL). Kirby cannot crop these images as they are not present on the server.
- Kirby doesn't know where and how the blocks will be displayed in the frontend. Especially the size of the rendered images is unknown, so Kirby cannot determine an optimal thumbnail size.

To solve both, the image block snippet only shows an example how it could be done: It applies a `data-crop` attribute to the `<figure>` element that you can react on with CSS.

The default blocks that ship with Kirby are intended to be basic and clean starting points that can be extended or customized to fit your site. Every site uses a different design system and selector conventions (e.g. conventions for class names). We don't want to force a specific way of writing frontend code on our users to make the system as flexible as possible. With the core blocks we provide example code to make it easy to get started, however the intention is to [extend and customize the block code](https://getkirby.com/docs/guide/page-builder/block-basics#extending-core-blocks) to your project.
