### ISSUE TITLE
Option value needs to be set in any case

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#6122]
Original code:
https://github.com/getkirby/kirby/blob/ba8e9e511d797c0c2bc9278d5484020c4aa8cfce/src/Option/Options.php#L34-L44

My recommendation:
```PHP


if (is_array($option) === false) {
    //$option needs to be an array
    $option = ['value' => $key, 'text' => $option];
} else if ( ($option['value'] ?? "") === "" ) {
    //Value required a content in any case
    $option['value'] = $key;
}
```

**Comment by distantnative** [comment]
@youngcut I think you'll need to provide some context what this change intends to achieve/what the problem is with the existing code.
