### ISSUE TITLE
.DS_Store not ignored in Class::Dir

### ISSUE THREAD

**Issue by plain-solutions-gmbh** [k-next/kirby#6129]
I refer to [this issue](https://github.com/youngcut/kirby-form-block-suite/issues/34)

Recommend to ignore Mac system files here:

https://github.com/getkirby/kirby/blob/ba8e9e511d797c0c2bc9278d5484020c4aa8cfce/src/Filesystem/Dir.php#L509

**Comment by afbora** [comment]
If you pass `null` to the second parameter (`$ignore`) instead `[]`, it'll work well as expected:

````php
Dir::read($formblockfolder, null, true);
````

https://github.com/getkirby/kirby/blob/4.0.2/src/Filesystem/Dir.php#L35-L45
