### ISSUE TITLE
After update from 4.0.2 to 4.0.3, panel says it’s an unreleased version

### ISSUE THREAD

**Issue by yulieyulie** [k-next/kirby#6133]
## Description
In the panel, after update from 4.0.2 to 4.0.3, it says it’s an unreleased version

**Expected behavior**  
Panel should say it's up to date

**Screenshots**  
<img width="1257" alt="Bildschirmfoto 2024-01-11 um 16 37 35" src="https://github.com/getkirby/kirby/assets/60138223/2112caa1-9242-4da6-9afd-5315cc835526">

## To reproduce
Update from 4.0.2 to 4.0.3

1. Update from 4.0.2 to 4.0.3
2. check "System" in the panel

## Your setup
**Kirby Version**  
4.0.2 (updated to 4.0.3)

**Comment by bastianallgeier** [comment]
Could you please delete site/cache/updates and check again. We had problems with our CDN, but they should now be resolved.

**Comment by yulieyulie** [comment]
@bastianallgeier yes, it works now. thank you!
