### ISSUE TITLE
Panel: Kirby license date format wonky (4.0.2)

### ISSUE THREAD

**Issue by yulieyulie** [k-next/kirby#6134]
## Description
in the panel, the Kirby license date format look wonky  (it says 2027-53-11)

**Expected behavior**  
display: 2027-01-11 (or 2028-01-11 ... dunno how long the license lasts., 3 or four years)

**Screenshots**  
<img width="1323" alt="295975273-75c59453-20d4-4de1-bb7a-5b27f04facc3" src="https://github.com/getkirby/kirby/assets/1595007/ba8907d1-a984-4855-bf29-239fbcdb0560">

## To reproduce
Enter license in previously unlicensed Kirby backend

## Your setup
**Kirby Version**  
4.0.2

**Comment by gbdesign2023** [comment]
The error does not seem to occur everywhere. 
In my 4.0.2 project, the date is displayed correctly:
 
<img width="1010" alt="licence" src="https://github.com/getkirby/kirby/assets/140849227/a582923c-eaf4-4720-b5de-6e8cfd5ac29c">

**Comment by lukasbestle** [comment]
@yulieyulie Have you configured a custom `date.handler` in the Kirby config?

**Comment by mit-stauffer** [comment]
I use the `'date.handler' => 'strftime',` and mine is broken like this.

![Unbenannt-1](https://github.com/getkirby/kirby/assets/27286029/3e0153b2-327e-4423-a0b2-11b86fd6ddbc)

With `'date.handler' => 'intl',` the date is wrong as with yulieyulie

![Unbenannt-2](https://github.com/getkirby/kirby/assets/27286029/bd2cdfd3-2167-4675-a808-d46dffa694a3)


With the default datehandler is works as intended.

Kirby 4.0.3

**Comment by tobimori** [comment]
![CleanShot 2024-01-12 at 18 03 28@2x](https://github.com/getkirby/kirby/assets/29142128/2304c952-85da-4fa5-8c2c-7563952554ae)
![CleanShot 2024-01-12 at 18 03 49@2x](https://github.com/getkirby/kirby/assets/29142128/20b65788-c115-46f0-b275-2d6a35547862)

I can confirm this issue. See screenshot from panel (`intl` handler) and hub.

**Comment by nilshoerrmann** [comment]
Looks like the `date` format is passed to `intl` which results in `year-minutes-daywithoutleadingzero`.

**Comment by lukasbestle** [comment]
OK, so it's what I thought. Thanks for confirming. 👍

**Comment by yulieyulie** [comment]
You're right, I do use

'date.handler' => 'intl'

... I had no idea it would have an effect on anything in the panel ... I use it for the frontend output.

**Comment by lukasbestle** [comment]
@yulieyulie It shouldn't, we just didn't think about it when building the license dialog :)
