### ISSUE TITLE
Missing image dimensions / orientation of avif files

### ISSUE THREAD

**Issue by crisgfx** [k-next/kirby#6141]
Hello,
when I upload `avif` files in the panel, the resulting uploads don't have any infos about dimension or orientation.
Is it possible to add that, so that I can use file methods like `width()`, `height()` and `orientation()` etc...?

(Ps: sorry if in advance, if this has been brought up before - couldn't find any related issue.)

**Screenshots**  
<img width="1205" alt="avif-example" src="https://github.com/getkirby/kirby/assets/16305374/b8699b32-b515-4124-91c7-2179ec120a83">

## To reproduce

1. Go to 'Panel'
2. Upload an `.avif` file somewhere
4. See file info

## Your setup
**Kirby Version**  
4.0.3

**Your system**
 - OS: macOS 13.6.3
 - Browser: FF Developer 
 - Version: 122.0b9

**Comment by distantnative** [comment]
Having raised PHP requirement to 8.1 we can actually do that!

**Comment by crisgfx** [comment]
Thank You very much Nico!

**Comment by distantnative** [comment]
I have to correct myself though: only seems to work on php 8.2 without compiling special version of php
