### ISSUE TITLE
[Kirby V3] - Bump symfony/yaml to v6

### ISSUE THREAD

**Issue by ceesvanegmond** [k-next/kirby#6161]
## Description
The latest Kirby v3 release (3.10) is stuck with symfony/yaml: 5.4.30. It's possible to update to "6.4" without any problems. I would really like to do a PR, but there's no v3 branch at the moment. We have a use case where an external (non-Kirby) package requires Symfony YAML v6 but cannot be installed because of this constraint.

I would like the ```composer.json``` to look like the following.

```	
        "require": {
                ///
		"symfony/yaml": "^5.4 | ^6.4"
                ///
	},
```

Is it possible to resurrect the v3 branch to PR this change?

**Comment by afbora** [comment]
Kirby v3 supports php 8.0 but `symfony/yaml` v6 doesn't support php 8.0. So unfortunately this is not possible. Also only security support is available for v3 version.

As workaround may be you can fork kirby repository and create own branch for you needs.

**Comment by bastianallgeier** [comment]
@afbora 3.10 actually starts with 8.1 so we could definitely bump the dependency there in a follow-up release if needed. The main question would be where we put it. @distantnative @lukasbestle what do you think. Could this go into a patch release? Is it worth to release 3.11 for just that? I'm really not sure.

**Comment by lukasbestle** [comment]
I think it would be fine to do 3.10.1, which according to our old versioning scheme is a minor release.

Unfortunately the release notes for Symfony YAML 6.0 are non-existent (at least I can't find any), but I assume that the only relevant breaking change is the new PHP version requirement. Since Kirby 3.10 already only supports PHP 8.1+, I think we can safely release 3.10.1 with Symfony YAML 6.

**Comment by afbora** [comment]
@lukasbestle Here `symfony/yaml` latest v6 release changelog:

https://github.com/symfony/yaml/blob/6.4/CHANGELOG.md

**Comment by lukasbestle** [comment]
Yes, but there's nothing in there for 6.0...

**Comment by afbora** [comment]
I think no changelog when `no significant changes` for the release.

**Comment by lukasbestle** [comment]
Yes, that's also what I thought. But "no significant changes" for a major release? 😅

That's why I wrote I assume the only reason was dropped support for PHP 8.0.

**Comment by afbora** [comment]
It would be great to release 3.10.1 with 4.3.0 or lets close the issue.

**Comment by lukasbestle** [comment]
@afbora Thanks for bringing this up again. I think we can do the 3.10.1 release at any time and there is no reason to wait any longer. Could you prepare one if you have the time?
