### ISSUE TITLE
File kirbytag returns null and throws an error when no valid file and text attr present

### ISSUE THREAD

**Issue by texnixe** [k-next/kirby#6177]
## Description
When a file tag `(file: non-existing.jpg)` doesn't have a valid file object, the `text` attribute is returned, but this returns `null` instead of an empty string (` kirby/config/tags.php`, #64) when this attribute is not present and therefore throws an error down the line.

See also: https://forum.getkirby.com/t/bnomei-rss-feed-not-working-since-upgrade-to-kirby-4/30543/1

## Your setup
**Kirby Version**  
4.0.3

**Comment by distantnative** [comment]
I'd probably not return an emtpy string but fall back to `value` if file is not found and `text` not set.

Easier to spot such a problem for the developer then, instead of just nothing rendering.
