### ISSUE TITLE
LinkField: selected option does not update when reverting unsaved changes

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6193]
<img width="403" alt="Screenshot 2024-01-23 at 20 21 46" src="https://github.com/getkirby/kirby/assets/3788865/ced4fb97-80c1-448b-9b5c-847d9e9476b8">

**Comment by distantnative** [comment]
@bastianallgeier do you have a good idea for this?

Difficulty is that currently we run the type detect in the `value` watcher but prefer the currently set `linkType` - so on revert that type sticks around as the newly reverted detected type isn't applied. But if we would switch the order around, any manual input would also trigger detection and switch the currently selected type.

**Comment by bastianallgeier** [comment]
@distantnative I think I have a solution: https://github.com/getkirby/kirby/pull/6198/files
