### ISSUE TITLE
Custom folder for »media« breaks Panel

### ISSUE THREAD

**Issue by animaux** [k-next/kirby#6202]
## Description

When setting a custom folder for `media` the frontend seems to work fine but the panel is not loaded. It seems to still try to get content from the default `/media`location.

**Expected behavior**  

I would expect the panel to reflect the configuration and work normally.

## To reproduce

Using this in `index.php`:

``` php
<?php

include __DIR__ . '/kirby/bootstrap.php';

$kirby = new Kirby([
    'roots' => [
        'media'    => __DIR__ . '/temp/media'
    ]
]);

echo $kirby->render();
```

## Your setup

**Kirby Version**  
4.1.0-rc.2

**PHP**
8.2.4

**Comment by bastianallgeier** [comment]
If you move the media folder, you also need to set the URL for it

**Comment by animaux** [comment]
D’oh, thanks, I missed that. Now I find it’s also explained here for example —> https://forum.getkirby.com/t/cannot-relocate-media-folder/18384/4
