### ISSUE TITLE
Structure field: Drawer is closed when an entry is deleted

### ISSUE THREAD

**Issue by Werbschaft** [k-next/kirby#6209]
If a structure field is opened in the drawer and an entry is deleted, the drawer closes each time. This makes deleting the entries quite tedious and is probably not intended.

![Kapture 2024-01-26 at 07 38 54](https://github.com/getkirby/kirby/assets/2178466/01540e50-c358-49b1-b369-f09304b47f3a)

**Comment by afbora** [comment]
Your Kirby version is 4.1.0 RC, right? I can reproduce the issue on 4.1.0 RC3.

**Comment by Werbschaft** [comment]
@afbora I'm currently on 4.1.0-rc.2

**Comment by afbora** [comment]
OK. I'm pretty sure this is about replacing `uid` for the components.
