### ISSUE TITLE
Link to an internal page  dosen't render the link

### ISSUE THREAD

**Issue by jp-clerc** [k-next/kirby#6214]
## Description
The link to a page with the writer field (or text block) dosen't give the proper link but something like `https://site.com/@/page/VZlscZfc8c5gEiwM`

**Expected behavior**  
Links to the internal page.

**Screenshots**  
![image](https://github.com/getkirby/kirby/assets/81645374/872f36c1-b3ea-4832-8595-bfbd7f392609)

Then:
![image](https://github.com/getkirby/kirby/assets/81645374/a6221ced-d1db-43c9-a119-9daeb902a8f8)

## To reproduce
1. Insert a writer field in .yml template with the link option available.
2. Then write some text
3. Link to an internal page

This bug even exist in the Kirby Demo Page, when you try to insert a link to an internal page (i. e. an article in the blog).

## Your setup
**Kirby Version 4.0.3**  

**Your system**
 - Device: Laptop
 - OS: Windows 11
 - Browser: Brave

**Comment by distantnative** [comment]
This is expected. The writer field inserts permalinks as the content is stored as HTML. That way if a page gets moved, the reference is still working. If your prefer your frontend to render normal URLs instead of permalinks, please use https://getkirby.com/docs/reference/templates/field-methods/permalinks-to-urls on your writer field in your template.

**Comment by jp-clerc** [comment]
Oh ok.. sorry for that

**Comment by jp-clerc** [comment]
Oh ok ! Sorry for that.

**Comment by verstecken** [comment]
I was about to complain the same :) Good to know this is expected. But when I click, I get: "Not Found - The requested URL was not found on this server." In my case, it is a PDF I uploaded to the page and tried to link to. Should the /@/file/xyz link open the file correctly? It doesn´t work with internal links neither.

Kirby 4.1.0 / PHP 8.1.27

**Comment by favger** [comment]
> This is expected. The writer field inserts permalinks as the content is stored as HTML. That way if a page gets moved, the reference is still working. If your prefer your frontend to render normal URLs instead of permalinks, please use https://getkirby.com/docs/reference/templates/field-methods/permalinks-to-urls on your writer field in your template.

`<?= $block->text()->permalinksToUrls(); ?>`

it worked for me. thanks
