### ISSUE TITLE
UUID cache cant be synced between case-sensitive and case-insensitive filesystems

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#6232]
I just tried to sync the UUIDs cache `site/cache/example.com/uuid/` from the server (Linux) to my local environment (Mac):

![Screenshot 2024-01-31 at 21 52 00](https://github.com/getkirby/kirby/assets/60777/c51263b0-8666-4dbb-a758-eacbbac5bb41)

And I got an error. Turns out, my APFS Volume is case-insensitive. I didn't know:

![Screenshot 2024-01-31 at 21 53 24](https://github.com/getkirby/kirby/assets/60777/2b24f8b4-3968-490c-a321-1329876d848a)

Is this something Kirby should be compatible with?

**Comment by rasteiner** [comment]
I guess you could switch to the [uuid-v4 format](https://getkirby.com/docs/reference/system/options/content#uuid-generation) which is case insensitive (they're represented as just hex numbers). 

You can also write your own generator and set `Kirby\Uuid\Uuid::$generator` to it:
```php
<?php

$pool = join(array_merge(range('a','z'), range('0','9')));

// `getBytesFromString` requires PHP 8.3, but you could polyfill it yourself
Kirby\Uuid\Uuid::$generator = fn($length) => (new Random\Randomizer)->getBytesFromString($pool, $length);
```

You would need to regenerate all IDs though, which might break some links and pages / files fields on your website.

**Comment by distantnative** [comment]
@lukasbestle could we switch our default generator to only use a lowercase alphabet?

**Comment by lukasbestle** [comment]
According to https://zelark.github.io/nano-id-cc/, that would shorten the 1% collision time from ~4 million years or 30T IDs to ~46 thousand years or 399B IDs. Still not so bad, also considering that not many sites will create 1000 models per hour around the clock.

**Comment by distantnative** [comment]
@lukasbestle sounds to me like it would be an acceptable change for us. I'd suggest to make that switch not in 4.x but 5.0 though.

**Comment by lukasbestle** [comment]
Is it a breaking change? If not, I think we could do it in 4.x.

Maybe we could also increase the UUID length a bit in the same step. With 18 chars the collision probability will be roughly unchanged.

**Comment by distantnative** [comment]
I don't see the immediate breaking change but it's a big enough change and there might be assumptions by users around the current format. That's why I'd rather play it safe.

**Comment by mrflix** [comment]
> Maybe we could also increase the UUID length a bit in the same step. With 18 chars the collision probability will be roughly unchanged.

Feedback on the thought of changing UUID length: I'm currently working on a project where thousands of geographic map entries are stored in a mysql database and the UUID is stored as `char(16)`. Not a big challenge to adjust the size there but for this case it would be very important to communicate the change prominently.

**Comment by distantnative** [comment]
@mrflix length has stayed the same, only all lowercased now.

**Comment by mrflix** [comment]
I know. That's why I wrote "the thought of changing the UUID length". I read that comment by yesterday Lukas yesterday and stumbled over the `char(16)` today so I thought I'll leave this as a feedback to keep in mind if this comes up again in the future. Thanks for all your hard work!
