### ISSUE TITLE
License Error Suppression

### ISSUE THREAD

**Issue by simonscheiber** [k-next/kirby#6236]
## Description
I've been trying to work around an issue I encountered while registering my Kirby 4 version on my hosting: 
https://forum.getkirby.com/t/license-ssl-issue/30637

And the only solution that worked was by suppressing the CA error I was receiving with an `@` in [remote.php](https://github.com/getkirby/kirby/blob/4.1.0/src/Http/Remote.php#L62C35-L62C60): 

`if (empty($cainfo) === false && @is_file($cainfo) === true) {`

This way the Kirby internal CA was used. Thanks to [rasteiner](https://forum.getkirby.com/u/rasteiner) for this solution!

**Comment by bastianallgeier** [comment]
@lukasbestle does anything speak against this solution from your perspective?

**Comment by lukasbestle** [comment]
I think it's fine as long as we add a comment why we changed it (like "suppress warnings e.g. if system CA is outside of `open_basedir`").
