### ISSUE TITLE
Page creation triggers additional "new" page when " {{page.uuid.id}} " is present in blueprint info field

### ISSUE THREAD

**Issue by mit-stauffer** [k-next/kirby#6243]
## Description
Whenever a blueprint contains a field showing the uuid id of the page, the page creation with that template also triggers a simultaneous creation of unlisted page called "new".

**Expected behavior**  
The additional page "new" should not be created.

**Screenshots** 
![grafik](https://github.com/getkirby/kirby/assets/27286029/b1ed11a5-30b7-43bf-a402-d3a4e292b7d3)

## To reproduce
Add the following field (in this case to the blueprints/notes.yml) to the Kirby starterkit (4.1.0) and create a new "Notes" page

```
infofield:
  type: info
  text: " {{page.uuid.id}} "
```

**Comment by afbora** [comment]
This is known issue as  #4955 and as workaround you can use like following:

````yaml
infofield:
  type: info
  text: "{{ page.content.get('uuid') }}" 
````
