### ISSUE TITLE
[4.1.0] "Move" page very slow when there are many pages

### ISSUE THREAD

**Issue by mynameisfreedom** [k-next/kirby#6265]
## Description
As the title say, when website have many pages, when trying new "Move" page option it is very slow. It just shows empty slot where page locations should be, for more than 15-20 seconds. 

**Expected behavior**  
I suggest adding some loader to indicate pages are loading. For several days I thought it had some bug or conflict, and just now accidentally left it open longer and move locations showed up.

**Screenshots**  
![screenshot-localhost-2024 02 13-09_52_44](https://github.com/getkirby/kirby/assets/46815297/76422dd2-45eb-4e36-89a2-7fee3539188b)

## To reproduce
Just add many pages. I have 76 in my specific case.

## My setup
Kirby 4.1.0, PHP 8.2

**Console output**  
No errors. 

**My system**
 - Device: HP Omen
 - OS: Windows 11
 - Browser: Firefox Developer latest

Thank you!

**Comment by afbora** [comment]
Loading in 15-20 secs is really slow for 76 pages. There are two possibilities:

1. There is a bug or needs improvement somewhere in core
2. There is an incorrect usage in your app (we need to check on starterkit with many pages)

**Comment by afbora** [comment]
@mynameisfreedom I just also wonder that how about loading times for picker page dialogs without using filter/query pages?

**Comment by mynameisfreedom** [comment]
> I just also wonder that how about loading times for picker page dialogs without using filter/query pages?

Just tested it, and it loads in 1-2 seconds.

**Comment by mynameisfreedom** [comment]
> I just also wonder that how about loading times for picker page dialogs without using filter/query pages?

I also tested now the new Link field, which also loads all pages, or all files, it loads in 1-2 seconds maybe even less.

**Comment by distantnative** [comment]
@mynameisfreedom we will need more information (e.g. or blueprints, your content folder..) to replicate the issue
