### ISSUE TITLE
Kirby accepts empty paths like // which throw an error

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#6267]
## Description
The error only occurs when debug is enabled of course, but I expect Kirby to redirect to the correct page in this case.

Url path: http://127.0.0.1:3000//some-subpage
![CleanShot 2024-02-13 at 18 54 09@2x](https://github.com/getkirby/kirby/assets/29142128/437cb67e-8295-4e0e-83c2-de8cd5cca8ae)

Url path: http://127.0.0.1:3000///some-subpage
![CleanShot 2024-02-13 at 18 52 43@2x](https://github.com/getkirby/kirby/assets/29142128/342d29d7-d1c4-4576-a268-4ff0cadafbc8)

Url shown: http://127.0.0.1:3000/ (home)

4.1

**Comment by sebastiangreger** [comment]
Probably related to #4801

**Comment by tobimori** [comment]
yep, i'll leave it up to the team to close this as duplicate if they decide so

**Comment by distantnative** [comment]
Having reproduced it myself, I think it really is the same as https://github.com/getkirby/kirby/issues/4801
