### ISSUE TITLE
Sticky <thead> bar of plug-ins-list

### ISSUE THREAD

**Issue by gbdesign2023** [k-next/kirby#6283]
The <thead> bar of plug-ins-list table under "System" gets stuck when scrolling. 

- Tested with iOS 17.3
- Chrome and Safari
- Kirby 4.1

https://github.com/getkirby/kirby/assets/140849227/f53aea2e-7a50-49e7-adf1-11e99a9cdbe9

**Comment by distantnative** [comment]
Comment for the team:
Originates from the extra offset set to accommodate the sticky header. But the header here isn't sticky, so we need to ensure the extra offset is only applied when a sticky-able header is present.
