### ISSUE TITLE
Small typo in German translation

### ISSUE THREAD

**Issue by jakobgrommas** [k-next/kirby#6286]
## Description
There is a small typo when changing a file template, on [kirby/i18n/translations /de.json](https://github.com/getkirby/kirby/blob/2965c3124e3b141072a2d46c798a327dda710060/i18n/translations/de.json#L350), currently line 350:
  ```json
  "file.changeTemplate.notice": "Das Ändern der Dateivoralge wird alle Inhalte von Feldern entfernen, deren Feldtypen nicht übereinstimmen. Wenn die neue Vorlage bestimmte Regeln definiert, z.B. Bildabmessungen, werden diese unwiderruflich angewandt. Benutze diese Funktion mit Vorsicht."
  ```

**Expected behavior**  
Should be `Das Ändern der Dateivorlage`

## Your setup
**Kirby Version**  
4.1.0

**Comment by bastianallgeier** [comment]
How do you know we don't mean algae in this case? 🤣

I just changed it in transifex where we handle all translations.
