### ISSUE TITLE
Kirby 4 New Link-Field not showing all files from a page

### ISSUE THREAD

**Issue by frankziski** [k-next/kirby#6288]
## Description
I have a download-archive with over 200 pdf-files for a website. The goal was to have a single page, listing all pdfs from the whole system. But those files are also used in other subpages, where i want to link them inside a button.
When using the new Linkfield it only shows me the first 100 files of the page. There is no pagination or a search function.

**Expected behavior**  
The Files-List in the link-field should have a pagination, search function or just showing all files

**Screenshots**  
![files](https://github.com/getkirby/kirby/assets/37303044/0b01a466-e5c3-48dc-b05e-f3720dde36ca)
![files2](https://github.com/getkirby/kirby/assets/37303044/d14647c8-5598-4b1d-9a5b-ad64d1d4c8b7)

## Your setup
**Kirby Version**  
4.1.0

**Comment by afbora** [comment]
### Issue summary

There is default collection limit when no pagination:
https://github.com/getkirby/kirby/blob/4.1.2/src/Api/Collection.php#L117
