### ISSUE TITLE
Inconsistent behaviour with where clause in database when parameter is integer

### ISSUE THREAD

**Issue by SeriousKen** [k-next/kirby#6291]
## Description

Using the database abstraction the following should be equivalent:

`Db::table('products')->where('quantity < ?', 10)->all()`

`Db::table('products')->where('quantity', '<', 10)->all()`

**Expected behavior**  

Both should return all products which have a quantity less than 10. However, the first returns all products - the query silently ignores the _where_ part of the query when the parameter is an integer.

`var_dump(Db::table('products')->where('quantity < ?', 10)->build('select'));` gives the following output:

```
array(2) {
  ["query"]=>
  string(24) "SELECT * FROM `products`"
  ["bindings"]=>
  array(0) {
  }
}
```

## Your setup
**Kirby Version**  

4.1.0

**Your system**
 - Device: Dell Inspiron Laptop
 - OS: Ubuntu 20.04 on WSL2 on Windows11

**Comment by SeriousKen** [comment]
If I put the parameter in an array (eg. `Db::table('products')->where('quantity < ?', [10])->all();`) it works as expected:

**Comment by lukasbestle** [comment]
The bug is that in the mode of two arguments, only arrays and strings are supported.

I think the following line needs to be modified:

https://github.com/getkirby/kirby/blob/2965c3124e3b141072a2d46c798a327dda710060/src/Database/Query.php#L872

The second check should be `is_scalar($args[1])` instead of `is_string($args[1])`. However I'm not sure if `bool`s (which are scalar) will work. Maybe it instead needs to be `is_string() || is_int() || is_float()` then.

@afbora Could you work on a fix?

**Comment by SeriousKen** [comment]
What about `is_scalar()` instead? Same thing but easier to read.

**Comment by SeriousKen** [comment]
Bools do seem to work as they are converted to 1 or 0 when they are bound to parameters, so is_scalar should be OK.

Edit: Actually just checked, PDO seems to be inconsistent with treatment of boolean parameters - it works as expected with MySQL but false does not get converted to int with Sqlite.

**Comment by SeriousKen** [comment]
If you change the code here

https://github.com/getkirby/kirby/blob/2965c3124e3b141072a2d46c798a327dda710060/src/Database/Database.php#L307-L308

to explicitly bind with the correct types rather than rely on the execute method of PDOStatement then things work consistently with booleans.

```php
$this->statement = $this->connection->prepare($query);
        foreach ($bindings as $binding => $value) {
        $type = match (gettype($value)) {
	        'boolean' => PDO::PARAM_BOOL,
	        'integer' => PDO::PARAM_INT,
	        'NULL'    => PDO::PARAM_NULL,
	        default   => PDO::PARAM_STR
        };
        $this->statement->bindValue($binding, $value, $type);
}
$this->statement->execute();
```

**Comment by SeriousKen** [comment]
Ignore the previous code. I found there's a problem inserting boolean values into tables leading to different behaviour between MySQL and Sqlite. I think it could be worked around by converting booleans to integers before executing the query, I'll run a few tests to see what happens.

**Comment by SeriousKen** [comment]
@lukasbestle I made a pull request to improve handling bound parameters (https://github.com/getkirby/kirby/pull/6297) This PR doesn't address this issue, but it does mean that the `is_scalar` fix for this issue will work as expected if this PR is accepted. Do you think the change to line 872 mentioned above should be part of this PR or a seperate PR?

**Comment by lukasbestle** [comment]
@SeriousKen Thank you! I think it would be good to put the fix for this into a separate PR to keep the overview.
