### ISSUE TITLE
hook 'user.changeRole:after'  fails when args are named differently

### ISSUE THREAD

**Issue by owzim** [k-next/kirby#6308]
## Description

the example on https://getkirby.com/docs/reference/plugins/hooks/user-changerole-after is the following:

```php
return [
    'hooks' => [
        'user.changeRole:after' => function (Kirby\Cms\User $newUser, Kirby\Cms\User $oldUser) {
            // your code goes here
        }
    ]
]
```

if I use a different variable name, e.g.

```php
'user.changeRole:after' => function (\Kirby\Cms\User $user)
```

or 

```php
'user.changeRole:after' => function (\Kirby\Cms\User $user, \Kirby\Cms\User $oldUser)
```

it fails with 

```
Kirby\Cms\App::{closure}(): Argument #1 ($user) must be of type Kirby\Cms\User, null given
```

if it is intended, it is not expected and it should be documented properly

## To reproduce

```sh
git clone https://github.com/getkirby/starterkit.git rolehook
cd rolehook
cp site/blueprints/users/default.yml site/blueprints/users/foo.yml
composer install
php -S localhost:3001 kirby/router.php
```

change `site/config/config.php` to:

```php
return [
    'debug' => true,
    'hooks' => [
        'user.changeRole:after' => function (\Kirby\Cms\User $user, \Kirby\Cms\User $oldUser) {

        },
    ],
];
```

login to the panel http://localhost:3001/panel

create a user, change the role and get the error

![image](https://github.com/getkirby/kirby/assets/1720088/2fee8731-ee25-4c75-bb27-983373e4fb38)

## Your setup
**Kirby Version** : `4.1.1`
**PHP**: `8.2.15`

**Comment by distantnative** [comment]
It is documented as far as I can tell: https://getkirby.com/docs/reference/plugins/extensions/hooks - hook parameters are passed by name, not by position.
