### ISSUE TITLE
Add your own thumb generator not working

### ISSUE THREAD

**Issue by caplod** [k-next/kirby#6338]
## Description
I have big problems with animated gifs in the panel. The whole server gets unresponsive trying to resize the gifs with imagemagick.

So I want to code my own thumb generator to ignore gifs.

I placed the example code from the documentation https://getkirby.com/docs/reference/plugins/components/thumb
 into this location `/site/plugins/thumbs/index.php`

**Expected behavior**  
Since I didnot write any Code for myThumbGenerator (what in the end I am trying to do) I expect to get an error. 
But the Code never gets executed.  I even placed a `die;`

## Your setup
**Kirby Version**  
3.9.8.1

**Comment by distantnative** [comment]
It sounds what you are experiencing is the result of Kirby's async thumb generation.

When the initial requests runs Kirby's code, it's not the `thumb` component, but the `file::version` component getting called. Which creates `.job` files with all the instruction for the required modifications to the image (also name etc.).

When the actual image URL is then called, Kirby looks up if there is an already processed thumb available, or - if not - if a `.job` file is present. With the info from the job file, it then runs the `thumb` component to generate the actual thumb file. 

But this is why you won't see your initial request be interrupted by `die()` as the `thumb` component will only be called on the individual image requests, not the main request.
