### ISSUE TITLE
Disabled toggle field in object preview can still be changed

### ISSUE THREAD

**Issue by bvdputte** [k-next/kirby#6346]
## Description
When you have a toggle field in an object field with `disabled: true`, you can still change it from the object preview.

**Expected behavior**  
That this field would've been disabled there too.

## Your setup
**Kirby Version**  
4.1.1

**Your system (please complete the following information)**
 - Device: Macbook Pro
 - OS: macOS
 - Browser: N/A

**Comment by distantnative** [comment]
Currently, the field previews are trying to implement inline editing no matter what. I think each field preview needs a prop that defines whether it's `editable` or not. We should expose this prop through columns definitions etc. but also ensure to automatically set it to false, e.g. when a field is disabled.
