### ISSUE TITLE
[Panel] Pages navigation arrows not visible if breadcrumb to long

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#6348]
## Description
In the panel, when the top breadcrumb is too long, the pages arrows navigation icons are not visible anymore.

**Expected behavior**  
Whatever the size of the breadcrumb, the pages arrows navigation icons are visible.

**Screenshots**  
![4_Work_plan_HES_SO_RECTORAT](https://github.com/getkirby/kirby/assets/664089/4185eb3b-33c3-4174-8ed3-8cffbd6e0bdc)

## Your setup
**Kirby Version**  
4.1.2

**Your system (please complete the following information)**
 - Device: Laptop
 - OS: Linux
 - Browser: Firefox

**Comment by afbora** [comment]
I can reproduce the issue on Firefox. Works great in Chrome.

**Comment by mrflix** [comment]
I can reproduce the bug in Chrome 126.
