### ISSUE TITLE
Using srcset will result in very pixelated images

### ISSUE THREAD

**Issue by runxel** [k-next/kirby#6366]
## Description

When using `srcset` the output will be very pixelated. See below.
First I thought I might only be in cases when there is upscaling (btw: it would be super cool to have a config option that disables that). However I limited it for a test in my config.php and in the command itself (`$image->srcset([100, 300])`) so it would never upscale images. The results did not change though, which leads me to believe it's an issue with Kirby itself. 
I have only checked .jpg's so far.

**Expected behavior**  

Srcset should be looking good, not pixelated.

**Screenshots**  

This image is originally twice the size and was "downscaled" here to 1024px (w).
![srcsetissue](https://github.com/getkirby/kirby/assets/2277182/26b74268-1b04-4d0e-9239-c31385e6467e)

## To reproduce

Use `srcset` anywhere in your code.
Look at the result.

## Your setup
**Kirby Version**  

3.10.0.1
I know, it's not 4, so I doubt it will get fixed.

**Your system (please complete the following information)**
 - Device: MacBook
 - OS: macOS
 - Browser: Firefox
 - Version: 123

**Additional context**  
Issue started after the update to PHP 8.0 and installing 3.10.0.1

**Comment by texnixe** [comment]
In 3.10., we dropped support for PHP 8.0 and added support for PHP 8.3, so you should not use this version with PHP 8.0. Also, are you using the GD library or ImageMagick as thumb driver?

Yes, 3.x only gets security support, but I doubt that this is a Kirby issue.

**Comment by runxel** [comment]
> In 3.10., we dropped support for PHP 8.0 and added support for PHP 8.3, so you should not use this version with PHP 8.0. 

Sorry, misspelled. It's on PHP 8.1 I believe.

> Also, are you using the GD library or ImageMagick as thumb driver?

I didn't change the defaults, so it should be GD. (And yeah, it's probably not a Kirby issue, but I hoped for some insight)

**Comment by rasteiner** [comment]
Reminds me of https://forum.getkirby.com/t/image-assets-pixelated-on-frontend-after-kirby-update/29672
We never figured out what happened there either. 

Edit: summary is that images look like that when for some reason the `quality` gets set to `0`. We never actually found out why a `0` gets used, and under what circumstances, however.
