### ISSUE TITLE
changeRole permission to true as no effect for non admin user

### ISSUE THREAD

**Issue by vauvarin** [k-next/kirby#6372]
## Description
If I set the changeRole permission to true for a non admin user in the non admin user blueprint, the non admin user can't  change its role.

**Expected behavior**  
changeRole permission set to true for a non admin user allow him/her to change its own role.

**Screenshots**  
![Your_account_Site_Title](https://github.com/getkirby/kirby/assets/664089/e78395f8-41e8-4abf-8481-347e4ddebe96)
![Capture d’écran du 2024-03-26 15-00-28](https://github.com/getkirby/kirby/assets/664089/1527bbbf-f412-4649-abb8-f22f6dcb0980)

## Your setup
Kirby 4.1.2
PHP 8.3.4

**Your system (please complete the following information)**
 - Device: Laptop
 - OS: Linux
 - Browser: Firefox

**Plainkit example (available 1 month from now)**
https://www.swisstransfer.com/d/df8960ac-4e1a-43d9-91a8-8d54d445e553

**Comment by afbora** [comment]
Duplicated of https://github.com/getkirby/kirby/issues/5146
