### ISSUE TITLE
White PNG/SVG images are not visible in the panel

### ISSUE THREAD

**Issue by gbdesign2023** [k-next/kirby#6378]
- Add an `image` with the block or layout editor
- Upload a PNG/SVG with white fill and transparent background
- Only a white area is visible, which is irritating because I can't see if/which image is hidden behind it.

![image-1](https://github.com/getkirby/kirby/assets/140849227/f79506ca-c391-495e-b904-d9e9351476c6)

Wouldn't it be great to display the pattern in the background by default, as adapted by the cards/cardlets? 

It also would be great to be able to change the background using the same principle in the blueprint:
https://getkirby.com/docs/reference/panel/sections/files#preview-images__back

I solved it with a simple CSS class in `custom-panel.css`:

```
.k-block-type-image-auto {
    background: var(--pattern);
}
```

![image-2](https://github.com/getkirby/kirby/assets/140849227/92113fd2-1e16-46f9-a6bb-3d1ed84cc7b7)

I am aware that I can customize the block type. But there will be many (new) users who are happy about such useful little details if they are already part of the core functions of Kirby. 

It is not a bug, but a cosmetic improvement for the panel. 

**Kirby 4.1.2**

**Comment by distantnative** [comment]
The question is what we'd want for when `ratio` is not set (or set to auto:

Still have the pattern behind the whole container? Or should it really just be behind the `img` element?

<img width="1276" alt="Screenshot 2024-04-01 at 21 55 12" src="https://github.com/getkirby/kirby/assets/3788865/eb72b1a5-f976-496e-b13b-c91a6e4b28aa">

**Comment by gbdesign2023** [comment]
@distantnative That will be a question of personal taste. One person likes it, another doesn't. I don't mind if the entire background is patterned. This is also how I know it from the file blueprint:

<img width="1295" alt="file-blueprint" src="https://github.com/getkirby/kirby/assets/140849227/9dcdccd7-fe1d-4449-887b-4756ced8bf68">

The fundamental question is whether it makes sense to integrate this function into the core system or leave it as an individually programmable option.

The gallery block is of course also affected by this:

```
.k-block-type-image-auto, 
.k-block-type-gallery {
    background: var(--pattern);
}
```

<img width="860" alt="gallery" src="https://github.com/getkirby/kirby/assets/140849227/6dbd13b6-09d0-4bb5-86aa-dd408d848ce7">

**[Edit]** I have just noticed the difference between `k-block-type-image-auto` and `k-block-type-image`. `k-block-type-image-auto` seems to be the better choice for me. However, I have not yet tried it with image formats that do not correspond to the usual conditions.
