### ISSUE TITLE
Panel: users field doesn't fill current user as default

### ISSUE THREAD

**Issue by possible-is** [k-next/kirby#6381]
I have experienced a change from V3 to V4: The users field in the panel, for example:
```
author:
  type: users
```
is not filling in the current user as a default. This is happening in all V4 version.
I checked it against V3.9.1 and there it works.

**Comment by afbora** [comment]
Use like following:

````yaml
author:
  type: users
  default: true
````

https://getkirby.com/releases/4.0
> Users field: set default: true to always use the currently logged in user as default

**Comment by possible-is** [comment]
Thanks for clearing that up!

**Comment by twiro** [comment]
Just stumbled upon this change in behaviour myself and was glad I found the solution in this issue here, as the official documentation completely lacks this information:

**https://getkirby.com/docs/reference/panel/fields/users#default-values**

Would be great, if it could be included there too!
