### ISSUE TITLE
Impossible to remove date field content

### ISSUE THREAD

**Issue by tristantbg** [k-next/kirby#6392]
## Description
The date field has a problem and it is impossible to remove its content

**Screenshots**  
https://github.com/getkirby/kirby/assets/4832038/3ed3a9ad-6641-4005-9a37-7596a2c80444

## Your setup
**Kirby Version**  
4.2.0

**Comment by gbdesign2023** [comment]
I was able to reproduce the following behavior under 4.2: 
If I delete the value in a date field, the "save" button does not appear. This means that the change cannot be applied, and the original value appears on reload. Under 4.1.2 it worked correctly. The error appeared with 4.2.
