### ISSUE TITLE
Using the quickstart guide creating a new kirby project with composer leads into a frontpage with missing images

### ISSUE THREAD

**Issue by rpkoller** [k-next/kirby#6397]
## Description

While going through the list of existing quickstart guides on ddev.readthedocs.com, in preparation for the release of 1.23.0, we've noticed one problem with the quickstart guide for new kirby projects on https://ddev.readthedocs.io/en/latest/users/quickstart/#kirby-cms (which is, except of the php version, identical to https://getkirby.com/docs/cookbook/development-deployment/ddev#different-use-cases ). Following those instructions will lead to a page with all the images missing/not found on `ddev launch`

![Screenshot 2024-04-12 at 19 06 53](https://github.com/getkirby/kirby/assets/1665422/d237903a-7925-4947-ad3f-b22d8e3a5f95)

It has to be noted that there are no images under `media` but they are in place under `content`. 

**Expected behavior**  

Images should be shown

**Screenshots**  

## To reproduce

```
ddev config --php-version=8.3 --omit-containers=db
ddev start
ddev composer create getkirby/starterkit
ddev launch
```

## Your setup
**Kirby Version**  

`Kirby 4.2.0` 

**Console output**  

**Your system (please complete the following information)**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by rpkoller** [comment]
a quick follow up. i forgot to mention that the error described in the issue summary happened with the version of DDEV HEAD (more or less identical with DDEV 1.23.0-RC1). After creating this issue i've kept on testing and noticed that the error of the missing images does not happen with DDEV 1.22.7.

**Comment by rfay** [comment]
I think this has to do with DDEV using Debian 12 Bookworm in latest DDEV v1.23.0+

The /media directory is not properly populated when running index.php

Is image resizing failing in site/templates/home.php and not being reported?

**Comment by rpkoller** [comment]
@rfay was able to figure out the root. it wasn't debian bookworm but changes in another PR for DDEV. He has already created a new PR fixing the problem for Kirby (I've already successfully tested the artifact):  https://github.com/ddev/ddev/pull/6093 (more details in the issue summary)

**Comment by rfay** [comment]
I should note that the change that broke the Kirby quickstart was a really minor change to the nginx default configuration.

It was just the addition of this stanza that broke Kirby:

```
    location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|webp|htc)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
```

Why would adding cache expiration for images to the nginx config break Kirby's auto-image creation?
