### ISSUE TITLE
Error deleting page with virtual grandchildren

### ISSUE THREAD

**Issue by MikeHarrison** [k-next/kirby#6399]
## Description
I have a site set up where I have an Artist page, which in turn has child Artwork pages. These child Artwork pages contain images, from which I am generating virtual pages following [this method](https://getkirby.com/docs/guide/virtual-content/virtual-pages-image-gallery). If I try to delete an Artist page, with child Artwork pages, I am getting an error.

**Expected behavior**  
I would expect the deletion to occur

**Screenshots**  
1) Dialog box when I choose to Delete the Artist page (as expected):
![Screenshot 2024-04-03 at 12 20 45](https://github.com/getkirby/kirby/assets/6464063/c70f9af1-f517-4305-9aa8-ea1f30136538)
2) If I enter the page title and click Delete, I get a spinning wheel for a while and then the following screen:
![Screenshot 2024-04-03 at 12 21 52](https://github.com/getkirby/kirby/assets/6464063/aef9c13e-a1e2-4b22-aae3-60b66c1c17f8)
3) If I reload the page, the Artist is still in the page listing. If I click on the Artist page in the panel, I see the panel blueprint for a brief while, with the section for Subpages (Artworks) missing, then the following screen appears:
![Screenshot 2024-04-03 at 12 24 18](https://github.com/getkirby/kirby/assets/6464063/bde77b91-fc93-4bfb-940d-16ebebe72a33)
4) Looking in the content folder, the images and their .txt files have been deleted, but the page files remain. These still have the reference to the image in them.

## To reproduce
Create a new project with a parent page, child pages containing images, and generate virtual pages from those images. Then try and delete the parent page.

I have reproduced the error with a fresh install of Kirby Plainkit.

## Your setup
**Kirby Version**  
4.1.2

**Your system (please complete the following information)**
 - Device: Mac Mini
 - OS: MacOS Sonoma
 - Browser: Firefox
 - Version: 124.0.2

**Additional context**  
I have shared a zip file containing the minimal example with @texnixe, and am happy to send this to anyone else taking a look at this issue.

**Comment by distantnative** [comment]
@MikeHarrison could you please share the code for the virtual pages in here as well? So probably the artwork and images models

**Comment by MikeHarrison** [comment]
Hi,

Sure no problem, they are below:

**site/models/artwork.php**
```php
<?php
class ArtworkPage extends Page
{
  public function children(): Kirby\Cms\Pages
  {
    $images = [];
    
    
    if($image = $this->mainImage()->toFile()):
      $images[] = [
        'slug'     => $image->name(),
        'num'      => 0,
        'template' => 'lightbox-image',
        'model'    => 'lightbox-image',
      ];
    endif;
    

    if($this->additionalImages()->isNotEmpty()):
      foreach ($this->additionalImages()->toFiles() as $image) {
        $images[] = [
          'slug'     => $image->name(),
          'num'      => $image->sort()->value(),
          'template' => 'lightbox-image',
          'model'    => 'lightbox-image',
        ];
      }
    endif;

    return Pages::factory($images, $this);
  }
}
```

**site/models/lightbox-image.php**
```php
<?php

class LightboxImagePage extends Page
{
  public function image(string $filename = null): Kirby\Cms\File|null
  {
    if (!$filename) {
      return $this->parent()->images()->template('image')->findBy('name', $this->slug());
    }

    return parent::image($filename);
  }
}
```

I do also have a minimal example set up in the Plainkit if that is of use, I can send a zip file over

**Comment by MikeHarrison** [comment]
Hi!

Is there anything else I can do to help with getting this diagnosed or addressed? I am keen to find a resolution if possible - is it a bug, or an error in my implementation?

**Comment by MikeHarrison** [comment]
I have got this working now, with help from @texnixe . Updated model is below for reference, I will close the issue as it was my implementation not a Kirby problem.

```php
<?php
class ArtworkPage extends Page
{
    public Pages|null $children = null;

    public function children(): Kirby\Cms\Pages
    {

        if ($this->children instanceof Pages) {
            return $this->children;
        }

        $images = [];


        if($image = $this->mainImage()->toFile()):
          $images[] = [
            'slug'     => $image->name(),
            'num'      => 0,
            'template' => 'lightbox-image',
            'model'    => 'lightbox-image',
          ];
        endif;
        
    
        if($this->additionalImages()->isNotEmpty()):
          foreach ($this->additionalImages()->toFiles() as $image) {
            $images[] = [
              'slug'     => $image->name(),
              'num'      => $image->sort()->value(),
              'template' => 'lightbox-image',
              'model'    => 'lightbox-image',
            ];
          }
        endif;

        return $this->children = Pages::factory($images, $this);
    }

}
```
