### ISSUE TITLE
Adding role-specific `preview` permission to blueprint results in Panel error

### ISSUE THREAD

**Issue by pReya** [k-next/kirby#6400]
## Description
By adding this to my page blueprint

```yaml
options:
  preview:
    ncuser: true
```
I get the following error in the panel:
```
Kirby\Cms\PageBlueprint::preview(): Return value must be of type string|bool, array returned
```
Any other permissions work fine, e.g. if I add
```
options:
  update:
    ncuser: true
```
everything works fine. It's just the `preview` option that triggers this error.

**Expected behavior**  

Panel should load just fine.

**Screenshots**  

## To reproduce
1. Download plainkit
2. Create any user blueprint (e.g. `users/ncuser.yml`)
3. Add the code above to any page blueprint
4. See error in panel

## Your setup
**Kirby Version**  
4.1.2

**Comment by distantnative** [comment]
@bastianallgeier Do you remember why this is called internally via `PageBlueprint`? Shouldn't it rather somehow be involved with `PagePermissions` to support role-based config?

@pReya Currently this is not just a type-hinting bug, but the `preview` options really supports only a boolean value or a string to overwrite the default preview url.

**Comment by pReya** [comment]
> @bastianallgeier Do you remember why this is called internally via `PageBlueprint`? Shouldn't it rather somehow be involved with `PagePermissions` to support role-based config?
> 
> @pReya Currently this is not just a type-hinting bug, but the `preview` options really supports only a boolean value or a string to overwrite the default preview url.

I guess then it's rather a bug in the documentation. Because it says `You can control each option for pages, files and users in blueprints with fine-grained permissions based on user role:` (taken from [here](https://getkirby.com/docs/guide/users/permissions#specific-permissions-in-page-file-user-or-site-options))
