### ISSUE TITLE
Hide page view options dropdown with no actionable options

### ISSUE THREAD

**Issue by bezin** [k-next/kirby#6438]
The page view options dropdown is always displayed, even when there is no actionable option. I suggest to hide it, when no action is possible anyways. 
<img width="195" alt="2024-05-06 10_41_32" src="https://github.com/getkirby/kirby/assets/4400435/48625b32-dc05-4708-8a76-29c40ccf21cc">

**Comment by gbdesign2023** [comment]
@bezin A hidden settings button will certainly cause more confusion for some users than a settings button with greyed out options. One option would be to soften the icon when no options are available. As can be seen in your screenshot with the "published" field. Incidentally, this field would then also have to be hidden to maintain consistency. I wouldn't describe your issue as a bug, but rather as a suggested change.

**Comment by bezin** [comment]
Yes, I agree, hiding is not a good idea, but disabling the button as a whole would IMO be a lot better

**Comment by afbora** [comment]
Closing favor of https://feedback.getkirby.com/204
