### ISSUE TITLE
File browser: pre-select current page

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#6458]
## Description
When I use the link dialog to link to a file, the file browser starts at the root level.

**Expected behavior**  
Since files in Kirby are grouped with the pages their used in, I'd expect the browser to start out at the current page's level, listing the files of that page.

**Screenshots**  
I'm in `material/bubble-crasher`. The file browser starts at the root:

![CleanShot 2024-05-22 at 17 05 12](https://github.com/getkirby/kirby/assets/60777/db316edc-d5ff-40a6-93ff-69a1cfbe6594)

I'd expect it to start with the current page active:

![CleanShot 2024-05-22 at 17 05 24](https://github.com/getkirby/kirby/assets/60777/e5f6f27c-b976-47eb-8443-c5456713c7c5)

**100+ pages example**
Linking text to a pdf file in writer from within a blog post on a website with 100+ posts shows that the user experience is very bad.

https://github.com/getkirby/kirby/assets/60777/0535454f-d4a1-43fe-894a-630df318a901

## Your setup
**Kirby Version**  
4.2.0

**Comment by afbora** [comment]
I think this is a feature request rather than a bug.

**Comment by gbdesign2023** [comment]
However, I don't think that's a bug. I see it more as an additional feature. Personally, I think it is even beneficial to display the root menu. For a nested structure, the integrated search function is helpful to avoid clicks.

**Comment by afbora** [comment]
Also I think this idea can be solve with query support: https://feedback.getkirby.com/574

**Comment by mrflix** [comment]
> Personally, I think it is even beneficial to display the root menu.

I can't follow you here. In the screenrecording I have do dig through a large page-tree to find the page I'm currently working on, just to link to a file that I just uploaded there. That's in the writer field. For comparison, in a textarea, the file picker dialog shows me the files of the page.

**Comment by mrflix** [comment]
> Also I think this idea can be solve with query support: https://feedback.getkirby.com/574

Will it be possible to adjust the starting location of the file dialog for file-linking inside the writer field?

**Comment by mrflix** [comment]
I would like to point out once again the strange behavior of the file link dialog. I am in the process of showing a customer how to link files. It just doesn't suit Kirby at all that the file link dialog starts on the root level instead of listing the current page's files.

Kirby is organizing files by page. The dialog doesn't contain an upload button. So the editor has to upload the file to the page before creating the link. Because of that they always have to search for their current page in the page structure.

**Comment by mrflix** [comment]
I'm currently updating another website to Kirby 4 and have to jump the hops to link to a file from within a large page structure. Join me on the ride:

https://github.com/getkirby/kirby/assets/60777/9ccdcc0f-9d57-4017-b538-647e9e6e9073
