### ISSUE TITLE
Filename sanitization rules are inconsistent

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#6465]
As a followup from [the other issue](https://github.com/getkirby/kirby/issues/6461). I added [the following comment](https://github.com/getkirby/kirby/issues/6461#issuecomment-2133405202), which probably got lost:

> I found another inconsistency between server and client side. `Str::slug()` which is used by `F::safeBasename()` does
> 
>> // trim leading and trailing non-word-chars
>
> and uses `a-z0-9` in its regex pattern on the server ([source](https://github.com/getkirby/kirby/blob/c1e6ff77b056774543f201035f5dab6a02bfdb3b/src/Toolkit/Str.php#L1161)). The slug helper in the panel Vue code on the other hand, which should also
> 
>> // trim leading and trailing non-word-chars
>
> uses the passed allowed character set (`new RegExp('^[^' + allowed + ']+', 'g')`) in its regex pattern ([source](https://github.com/getkirby/kirby/blob/c1e6ff77b056774543f201035f5dab6a02bfdb3b/panel/src/helpers/string.js#L213)).
> 
> So you can enter something like `_test.jpg` in the panel when renaming and uploading a file, but the file will be saved as `test.jpg`.
> 
> Since the panel can’t handle files starting with underscores (for some reason) I would opt to use the more restrictive pattern.

**Comment by distantnative** [comment]
It's hasn't gotten lost. Let's keep it with one issue for this.

**Comment by silllli** [comment]
The other issue was and remains closed as “completed” (after me stating more inconsistencies), so I thought there is need for a new one to stay visible.

**Comment by distantnative** [comment]
@silllli as far as I see the PR https://github.com/getkirby/kirby/pull/6462 does address those as well or do you see its differently?

**Comment by silllli** [comment]
@distantnative Ah, true! But using the passed allowed character set is prone to becoming out of sync with the sanitization on the server (which is hardcoded) again. 

Also, as I mentioned, the Panel can’t handle files starting with an underscore (which was prevented so far) so there is a way to break it now by renaming a file to start with an underscore.

**Comment by distantnative** [comment]
Which is why the PR also removes them on the Panel/frontend at the start/end of the filename.

**Comment by silllli** [comment]
Perfect. Sorry, I didn’t check all commits and there was no feedback on my additional comment.
