### ISSUE TITLE
Date picker not opening when clicking on date field in Panel

### ISSUE THREAD

**Issue by silllli** [k-next/kirby#6469]
## Description
When clicking on a date field to open the date picker in the Panel, I often only get to see a small black box instead of the picker. I haven’t figured out a pattern causing this yet. A page reload usually fixes the problem.

**Expected behavior**  
The date picker to always open.

**Screenshots**
<img width="589" alt="Bildschirmfoto 2024-06-03 um 19 42 18" src="https://github.com/getkirby/kirby/assets/9334305/76df563f-f660-4cff-9561-dfde6f49a051">

## To reproduce
1. Add a `date` field to a blueprint
2. Open the page in the Panel and click on the date field

## Your setup
**Kirby Version**
4.2.0

**Console output**  
<img width="893" alt="Bildschirmfoto 2024-06-03 um 19 43 35" src="https://github.com/getkirby/kirby/assets/9334305/9bb6e3a4-f7b9-4ce2-9771-8b2a1a99700e">

**Your system (please complete the following information)**
 - Device: MacBook Pro
 - OS: macOS 14.5
 - Browser: Safari
 - Version: 17.5

**Additional context**  
This has happened in different projects, on a remote server and local, in nested structure fields and directly on the page.

**Comment by distantnative** [comment]
This will be fixed with the next release.

https://github.com/getkirby/kirby/pull/6425
https://github.com/getkirby/kirby/issues/6422

**Comment by silllli** [comment]
Sorry, I missed the other issue when checking before.

**Comment by distantnative** [comment]
No worries, not always easy to spot those that are already closed as they are done for the next version - but the next version isn't out yet.
