### ISSUE TITLE
Changing the sort number of listed pages will cause recreation of image source sets

### ISSUE THREAD

**Issue by ovenum** [k-next/kirby#6508]
## Description

Changing the page number of a listed page that has already created source set image version in `/media/pages` will cause a recreation of the already created images under a different path. 

**Expected behavior**  

Kirby should not re-create those images because their path and original file did not change. 

This can cause problems for image heavy sites where source sets are created after image upload and not on requests. 
Also see issue #5328 why this has the potential to take a site offline although source sets have been pre-created to avoid this issues. 

I noticed that Kirby seems to include the modified timestamp of the page the images belongs to in the FileVersion url. Which could be the reason copies are created.

## To reproduce

- Install the Starterkit
- navigate to /photography/desert
- check /media/pages/photography/desert folder for images created (search for death-trap)
- change the number of /photography/desert by drag and drop sorting in the panel
- check /media/pages/photography/desert folder and see the duplicated death-trap images with exactly the same dimensions, name and size as the previously created one.

<img width="856" alt="image" src="https://github.com/getkirby/kirby/assets/47149622/9c51f864-b0e7-474b-83ee-de4c439328e6">

## Your setup
**Kirby Version**  
Kirby 4.3.0

**Comment by distantnative** [comment]
@ovenum are you already using https://getkirby.com/docs/reference/system/options/content#salt-for-drafts-and-media-files as suggested on Discord to not use the page ID (which includes the sorting number) in the path?

This might not fully work as I realize that the file's `mediaRoot` also includes `$parent->mediaRoot()` (the page), which includes its id (incl. sorting number) as well: https://github.com/getkirby/kirby/blob/main/src/Cms/Page.php#L798

I haven't spotted in our code where we would use the modification timestamp of the page in the file's url. Are you sure about this? It does in fact use the modification of the file itself which is necessary as otherwise browser would not load new versions of a file that gets updated/replaced with the same name.

**Comment by ovenum** [comment]
@distantnative i have not used the config option for content salts. 
Testing with a kirby plainkit, setting `content.salt` to a fixed value will solve the issue. 

```php
// site/config.php
return [
'content' => [ 'salt' => 'test' ]
]
```
When not setting the content salt i can reproduce the issue every time with the plainkit. 
Also not sure what the root of the issue is. I could see that the modified timestamp of the folder changed and that it’s contained within the file path, so just assumed it might be the cause.

**Comment by distantnative** [comment]
The salt by default contains the parent's page ID which includes the sorting number. If you resort the parent, the page sorting number changes, the page ID changes, the salt for `contentToken` changes and in the end that's why the root for the media file changes => it gets newly created.

**Comment by ovenum** [comment]
Thanks for explaing this! Understanding now why this is happening. I would consider it a bug or at least a not optimal default setting. 

The images do not need to be re-created because their path or content did not change when just the parents sorting number is modified/added.

As mentioned on [Discord](https://discord.com/channels/525634039965679616/525641819854471168/1258344027099631678) this can cause unecessary server load and hdd usage when pages sorting numbers are changed.

**Comment by distantnative** [comment]
@ovenum this will be fixed/improved in Kirby 5 (instead using the absolute root for the hash, we're using the root to the content folder and then only the ID without sorting numbers).

https://github.com/getkirby/kirby/pull/6432

**Comment by ovenum** [comment]
Thanks @distantnative this really helps a lot!

Also noticed that this can cause Google to create duplicate content hints when a page contains PDFs that were added to the search index and now got a new url because of changing the sort order and not clearing pages media folder.
