### ISSUE TITLE
[Panel] Dragging a file from a file section into a writer field stores the panel file url

### ISSUE THREAD

**Issue by mrflix** [k-next/kirby#6519]
## Description
Dragging a file from a files section into a writer field creates a link with the filename as the text and **the panel url as the href**:

```html
<a href="https://localhost/example.com/panel/pages/home/files/document.pdf">document.pdf</a>
```

**Expected behavior**  

```html
<a href="file://Z2ozHobGVmkNEV3E">document.pdf</a>
```

## Your setup
**Kirby Version**  
Kirby 4.3.0

**Comment by distantnative** [comment]
Moved to our feedback list: https://feedback.getkirby.com/653
