### ISSUE TITLE
Resize/crop/thumb functions see longest size of images as width

### ISSUE THREAD

**Issue by kzenmatthias** [k-next/kirby#6521]
**Issue with Reference**  

When using the thumb(), resize() and crop() functions, the width specified in the parameters translates to the size of the longest side of the image.

Code example:
```
$thumb = $image->thumb([
  'width' => 812,
  'height' => 0,
  'quality' => 80,
  'format' => 'webp'
]);

$thumb = $image->resize(812, 0, 80);

$thumb = $image->crop(812, 200, 80);
```
**Expected**  

I expect the width of the image be the horizontal size of the image.

**Screenshots**  

If added the result of the crop to make it clear what is happening.
The vertical images are the images with a source image shot vertically. All the images are generated with the following code:

```
$thumb = $image->crop(812, 200, 80);
```

![claystuc3-812x200-crop-q80](https://github.com/getkirby/getkirby.com/assets/17494159/07cda687-9005-4e67-8a2c-3f453644b87f)
![claystuc1-812x200-crop-q80](https://github.com/getkirby/getkirby.com/assets/17494159/7979b09f-e957-4f7e-a90e-0eafc0114ba2)
![claystuc2-812x200-crop-q80](https://github.com/getkirby/getkirby.com/assets/17494159/f920705b-23a5-48db-bca0-12fabb1d2add)

**Comment by afbora** [comment]
I've tested `$image->crop(812, 200, 80)` code with vertical and horizontal images. Work is expected. 

Few questions:

1. Kirby version?
2. Setup environment? MAMP, Herd, Valet?
3. Image process library,  IM or GD?
4. Could you share your original images that you have issues?

**Comment by kzenmatthias** [comment]
Hmm. Maybe it's a problem at my side then.

1. Kirby version: 4.3.0
2. Setup env: DDEV running on Colima
3. I don't know. I guess the default one.
4. The images:
![claystuc1](https://github.com/getkirby/getkirby.com/assets/17494159/ae613059-f940-4002-bfe3-f852d31f08ee)
![claystuc2](https://github.com/getkirby/getkirby.com/assets/17494159/6b78e01d-f08c-4b2a-b196-581becc42fb7)
![claystuc3](https://github.com/getkirby/getkirby.com/assets/17494159/65912d67-d7ec-4e39-8e7d-06193a7e9870)
![claystuc](https://github.com/getkirby/getkirby.com/assets/17494159/2b90a944-3bca-4ff8-a979-739b0f551539)
![claystuc-baksteen](https://github.com/getkirby/getkirby.com/assets/17494159/a400faa2-3654-46cb-a6d6-b021473344ae)

**Comment by afbora** [comment]
I can reproduce the issue with your images. But there is weird thing about dimensions:

![screen-capture-1873-sample-1 jpg - Mægazine-localhost](https://github.com/getkirby/kirby/assets/3393422/e2f91af3-a5bc-4df5-a21b-99345f6ad6c1)

Kirby says that vertical image dimensions are `4000 × 1868 Pixel`. I haven't good knowledge about images but may be something broken about images exif data.

I've upload your image to exif meta checker and it says width is 4000px and height is 1868px too. Checked from: https://www.metadata2go.com/view-metadata

**Comment by kzenmatthias** [comment]
Okay, thanks for the info. I'll close this ticket as this is an error on my side. Sorry for the ticket and taking up your time.

**Comment by afbora** [comment]
No problem. Feel free reopen the issue if you have found any issue 👍
