### ISSUE TITLE
[Panel] Switching Languages triggers revert / save

### ISSUE THREAD

**Issue by HashandSalt** [k-next/kirby#6525]
## Description
Switching language and back again causes the revert/save buttons to appear, even though no content has changed.

**Expected behavior**  
Revert / Save should not appear unless content has actually changed.

**Screenshots**  

https://github.com/getkirby/kirby/assets/28439755/8c4395d6-5ab3-4bd7-93c5-8ad6731e6683

## To reproduce
On a bilingual site, swtich language and then switch back to the orginal one. The revert / save buttons appear.

## Your setup

Kirby 4.3.0

**Comment by afbora** [comment]
I think this issue is duplicated of https://github.com/getkirby/kirby/issues/6005 as @texnixe said. I can only able to reproduce the issue with non-breaking space.

@HashandSalt Could you reproduce the issue on all pages or with simple text?

**Comment by afbora** [comment]
Closing the issue favor of https://github.com/getkirby/kirby/pull/6562 PR. Feel free to reopen the issue.
