### ISSUE TITLE
Use `slugs.maxlength` when generating slugs

### ISSUE THREAD

**Issue by distantnative** [k-next/kirby#6526]
Currently, we often ignore the `slugs.maxlength` option when generating slugs but rather use the default 128 from `Str::slug()`.

I see two options:

1. Integrate `App(null, true)?->option('slugs.maxlength')` into `Str::slug()` to use as default when set. Could this be problematic if someone limits it to a very short length, as we also often use `Str::slug()` for non-slugs?

2. Create a new, e.g. `App::slug()` that takes the option and passes it with all the other parameters to `Str::slug()`. Search through the code where we should use `App::slug()` instead of `Str::slug()`. (or `Page::slug()`, `Router::slug()` or so).

@lukasbestle @bastianallgeier Which do you think would be better?

**Comment by lukasbestle** [comment]
I think your point on using the method for other reasons is what counts here. So I think option 2 is better as it doesn't involve a breaking change with hard to overlook consequences.
