### ISSUE TITLE
Sorting doesn't work as expected if some pages have fixed nums

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#6595]
## Description
I want a specific page template to have `num: 0` (and stay at the start). All other templates should be sortable as usual.

https://github.com/user-attachments/assets/b2498951-17fd-479e-a4b2-dbe6f23b3168

**Expected behavior**  
I'd not be able to sort the page with fixed num and when sorting other pages, they shouldn't jump when let go but stay at their expected position.

This can be partly treated as enhancement, however I'm still adding this as an issue. In my opinion, sorting should rather be disabled than allowing this buggy behaviour to avoid confusion.

## Your setup
**Kirby Version**  4.3

**Comment by distantnative** [comment]
@tobimori Are for you the following parts the same:
- The page that has `num: 0` in its template is actually never sortable itself (in no layout)
- With card, list and cardlets layout, I can also not drag any other (sortable) page above the `num: 0` page (as one would want/expect)
- Only with the table layout, I can suddenly drag a sortable row above the `num: 0` row (as in your video).

**Comment by tobimori** [comment]
> With card, list and cardlets layout, I can also not drag any other (sortable) page above the num: 0 page (as one would want/expect)

I can drag them above it, and then they jump to the second position (as seen in the video).

**Comment by distantnative** [comment]
@tobimori but the video is in table layout

**Comment by tobimori** [comment]
Sorry, my mistake 🤦 I haven't tested other layouts.

**Comment by distantnative** [comment]
Would be great if you could, just to be sure that we've narrowed down the extend of the issue correctly.

**Comment by distantnative** [comment]
@tobimori or please test if this is solved for your case with 4.4.0-rc.1

**Comment by tobimori** [comment]
I have this issue on 4.4.0-rc.1 now with the list layout as well.

**Comment by distantnative** [comment]
@tobimori could you please share your blueprint? Thanks!

**Comment by tobimori** [comment]
What do you need exactly? This was in a different project with the same pattern (num: 0) on one blueprint type only. I can also share the whole project privately if that helps.

**Comment by distantnative** [comment]
That would help as well. Currently, I cannot reproduce that this would happen in the list layout now, neither in the table layout anymore.

Setup:
- Pages section
- Allows 2 templates
- One template set `num: 0`, one page with this template and folder name starting with `0_`
- One template without `num`, 3 pages with this template and folder names starting wit a normal order number `1_`, `2_`...
- I can sort the three pages, but I cannot drag them above the `0_` page which remains unsortable
- Both in list as well as table layout
