### ISSUE TITLE
`Html::tag` does not accept whitespace for attributes

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#6613]
## Description
We are using `Html::tag('img', null, ['alt' => $alt])` to generate images. If `$alt` contains a whitespace only, Kirby throws an expection.

**Expected behavior**  
There should be no expection, the `alt` attribute should contain the space.

**Screenshots**  
<img width="1823" alt="grafik" src="https://github.com/user-attachments/assets/a1ccfa26-dc5a-4f98-8ca9-0103aaacea9c">

## To reproduce
Try to add a whitespace as an attribute value with `Html::tag`.

## Your setup
Kirby 4.3.0

**Comment by nilshoerrmann** [comment]
If I remember correctly the deprecation notice has to to with creating empty properties like `checked` and such on elements. This issue in our case is that the attribute text is written in the panel by an author so I don't think it's save to just trim it because the whitespace might actually be desired.

**Comment by distantnative** [comment]
> because the whitespace might actually be desired

What's the use case here to ensure that a single whitespace can be rendered as alt text?

You can suppress the deprecation notice with

```php
Helpers::$deprecations['xml-attr-single-space'] = false;
```

In a future version, this will actually render a single space, but as previous support of Kirby had this as pattern to render an empty attribute (no space), we need to transition towards it without breaking other setups in a drastic step.

**Comment by nilshoerrmann** [comment]
> What's the use case here to ensure that a single whitespace can be rendered as alt text?

It just so happened that an editor entered it like that and – from an editorial point of view – there is no reasons to forbid that. Using the deprecation suppression will work for us, thanks :+1:
