### ISSUE TITLE
Link on block can’t select the correct page

### ISSUE THREAD

**Issue by guidoferreyra** [k-next/kirby#6624]
## Description
When using a link on a text block it select two pages instead of one.

see video

https://github.com/user-attachments/assets/8ee93f28-b186-4016-9023-8f0cc8750bd6

**Comment by distantnative** [comment]
@guidoferreyra can you please provide some context information, e.g. what Kirby version?

**Comment by guidoferreyra** [comment]
latest k version 4.3.0 it happens on server and localhost.

**Comment by distantnative** [comment]
@guidoferreyra to replicate the issue it would be helpful if you could share your blueprint, whether you work with UUIDs or have them deactivated in the config file as well as the folder structure of the two pages in question (somehow Kirby maps both to the same ID it seems).

EDIT: if you use UUIDs, could you please check both pages' content file if the UUIDs in there are different?

**Comment by guidoferreyra** [comment]
both pages had the same uiid 🤦 thanks!
