### ISSUE TITLE
Translations can still be deleted without permission in 4.3.1

### ISSUE THREAD

**Issue by jensscherbl** [k-next/kirby#6645]
Just tested the new [4.3.1 release](https://github.com/getkirby/kirby/releases/tag/4.3.1) to see if it fixes a long-standing issue we had.

What we’d like to do is to give our editors the ability to translate static texts (static strings in our templates) for pre-defined languages, without accidentally breaking things.

Unfortunately, while languages now can’t be deleted without sufficient permissions, individual translations within a language still can.

We did define fallbacks in our templates, but there’s actually no way for an editor to guess the corresponding translation key and restore a deleted translation.

Not sure if this is still a bug or a new feature request. I guess technically, the language permissions are working now and permissions for individual translations are simply missing.

**Comment by afbora** [comment]
@jensscherbl What's your editor blueprint/permissions?

**Comment by afbora** [comment]
By the way, there is no separate permission for language translations. For now, create/update/deleting translation strings all depend on the `languages.update` permission. 

We are planning to add a separate permission for language variables in v5. It will be `languageVariables.create|update|delete` or something like that.

**Comment by jensscherbl** [comment]
> What's your editor blueprint/permissions?

Languages are allowed (they can navigate to the page in the panel), but creating and deleting is not allowed.

> By the way, there is no separate permission for language translations.

Yeah, I got that. That‘s why I‘m not sure if this is a bug or a feature request ;) If editors are not allowed to delete languages, is it right or wrong that they‘re allowed to delete individual translations within a language?

> We are planning to add a separate permission for language variables in v5.

Ah perfect, that‘s exactly how I think it should be. That will solve the issue for my use case then.

**Comment by afbora** [comment]
> Yeah, I got that. That‘s why I‘m not sure if this is a bug or a feature request ;) If editors are not allowed to delete languages, is it right or wrong that they‘re allowed to delete individual translations within a language?

Deleting language variables mean that updating the language. So current behavior is correct.

**Comment by jensscherbl** [comment]
> We are planning to add a separate permission for language variables in v5.

@afbora Sorry, now I‘m confused. You closed this as „not planned“ after telling me it‘s planned for v5? 😅

> Deleting language variables mean that updating the language. So current behavior is correct.

From an editor‘s perspective, deleting language variables means breaking the website, so the current language permissions are basically useless without the proposed language variable permissions. So I‘m glad you already thought about it for v5.

**Comment by afbora** [comment]
@jensscherbl I know. It's not important. @distantnative already started to implement it to v5 https://github.com/getkirby/kirby/pull/6646

**Comment by distantnative** [comment]
@jensscherbl It's closed here cause this is a feature request existing also at https://feedback.getkirby.com/606. How useless the current permissions for you and your project are is a personal assessment.

GitHub only allows two ways of closing an issue: Solved and not planned. Not planned as term is of course misleading here, but solved/implemented would be even more. So @afbora is right in the way he closed this issue.

https://github.com/getkirby/kirby/pull/6646 though does not yet tackle those additional permissions, but only replicating the add/settings/delete button disabled state from 4.3.1.

**Comment by jensscherbl** [comment]
Thanks for the explanation, now it makes more sense again 😅
