### ISSUE TITLE
Panel: Icon stroke and size inconsistency

### ISSUE THREAD

**Issue by nilshoerrmann** [k-next/kirby#6663]
## Description
We are working on a panel plugin and a section with the following button group:

```vue
            <k-button-group layout="collapsed" class="k-tracker-date">
                <k-button
                    icon="calendar"
                    variant="filled"
                    :dropdown="true"
                    size="xs"
                    @click="$refs.statsRange.toggle()"
                >
                    {{ labelRange }}
                </k-button>

                <k-dropdown-content
                    ref="statsRange"
                    :options="dropdown"
                    theme="light"
                    align-x="end"
                />

                <k-button icon="angle-left" size="xs" variant="filled" />
                <k-button icon="angle-right" size="xs" variant="filled" />
            </k-button-group>
```
This creates inconsistent icon proportions and stroke widths:

<img width="159" alt="grafik" src="https://github.com/user-attachments/assets/20c4edd4-fd23-41af-9f7a-ae1ad592006d">

**Expected behavior**  
The chevrons should match in size and stroke. Judging other areas of the system, it looks as if the dropdowns icon is to small and thin. But maybe the middelground would be better for extra small sized buttons: stronger strokes for the dropdown but an icon size between the to existing.

## Your setup
**Kirby Version**  
Latest version.

**Comment by distantnative** [comment]
I think this is a deliberate design choice to have the dropdown arrow rendered in a smaller, less dominant way compared to the main button icons (here: calendar, angle-left, angle-right).

**Comment by nilshoerrmann** [comment]
Okay, this might boil down to personal preference but I think the down pointing chevron is even too thin compared to the font weight. Feel free to close this though, if you think this is just fine in context of your design system.
