### ISSUE TITLE
previewUrl() on drafts return empty string when not logged in (4.4.0)

### ISSUE THREAD

**Issue by sciloqi** [k-next/kirby#6671]
## Description
`$site->findPageOrDraft('about')->previewUrl()` returns an emtpy string when not logged in into panel since kirby 4.4.0.

**Expected behavior**  
Return a valid url with token http://localhost:8000/about?token=xxx as in kirby 4.3.1.

## To reproduce
- Install starterkit, set "About Us" page to draft, insert `<?= $site->findPageOrDraft('about')->previewUrl(); ?>` on home for testing
- Test logged in and logged out -> returns url only when logged in
- Change composer.json to `"getkirby/cms": "4.3.1"` and update
- Test logged in and logged out -> works in both cases

**Comment by afbora** [comment]
`preview` is a permission based option. So I think this is expected behavior.

https://github.com/getkirby/kirby/blob/4.4.0/src/Cms/PageBlueprint.php#L183

**Comment by distantnative** [comment]
Yes, 4.4.0 aligned the PHP behavior with the Panel here: https://github.com/getkirby/kirby/pull/6572

Why would you expose the secret token publicly to non-users?

**Comment by sciloqi** [comment]
Wow, you guys are fast... ❤️
No other chance to generate "secret" links to drafts for normal users?

My case is: I have a hidden test page (which is a draft), on which are links to other drafts. I want to give the editors a link with a token to that test page, and then have automatically generated previewUrts on that page to the other drafts.

**Comment by distantnative** [comment]
You could probably use https://getkirby.com/docs/reference/objects/cms/app/impersonate with a user with sufficient permissions or the almighty `kirby`. I just recommend using the callback way described in the docs to ensure that right after the old non-authorized context is restored and your non-user visitors aren't running the rest of the request with superpowers.
