### ISSUE TITLE
v4.4.0 "Panel is offline" is displayed sporadically

### ISSUE THREAD

**Issue by gbdesign2023** [k-next/kirby#6679]
Since updating to **Kirby 4.4.0**, I occasionally see the message that the *"*panel is offline"** for about 1 second. Sometimes the message is displayed up to 3 times in a row. Sometimes not at all for hours. I never saw this message with Kirby 4.3.0 
I work locally under macOS 14.6 with MAMP Pro. The browser is Chrome.

https://github.com/user-attachments/assets/3acb4781-bb24-4d64-b741-161983664448

**Comment by afbora** [comment]
@gbdesign2023 I can't see the video. Could you re-upload, please?

**Comment by gbdesign2023** [comment]
![IMG_9389](https://github.com/user-attachments/assets/99318809-1b85-47f0-8134-20b126daeb85)

**Comment by gbdesign2023** [comment]
I have - however - marked the issie as closed on my iPhone. This is of course not correct.

**Comment by gbdesign2023** [comment]
@afbora I have converted the video with a different code. Can you see it now?

**Comment by nilshoerrmann** [comment]
It seems like the panel is checking if the device is online but this doesn't take a local server into account. This can be very problematic if you are developing locally without internet connection because you cannot interact with the panel anymore.

**Comment by gbdesign2023** [comment]
@nilshoerrmann My Mac is permanently connected to the Internet, as CDN content is also linked to my Kirby projects. And as I said: I never saw this message with Kirby 4.3.0.

**Comment by afbora** [comment]
Were there any other changes to files, plugins, settings, etc. when updating to 4.4.0?

**Comment by bastianallgeier** [comment]
@gbdesign2023 could you check in your browser console what you get when you type in `panel.system.isLocal`?

**Comment by gbdesign2023** [comment]
@afbora Yes, I have changed a few things since the update, but more in terms of content than functionality. I have only updated the ‘johannschopplich/seo-audit’ plug-in.

@bastianallgeier ‘panel.system.isLocal’ How can I retrieve this information from the browser console? Since the offline hint only appears sporadically and is only displayed briefly, I don't see anything suspicious in the console afterwards.

**Comment by bastianallgeier** [comment]
@gbdesign2023 

1. open the developer tools
2. go to console
3. enter `panel.system.isLocal` and hit the Enter key

This should either return `true` or `false` as output. 

It does not matter if the offline warning is shown at that point.

**Comment by gbdesign2023** [comment]
@bastianallgeier  Unfortunately, no value is displayed when entering `panel.system.isLocal`
![01](https://github.com/user-attachments/assets/bf648a87-3b5b-42f9-b024-fd3eeace67d4)

Only this messages:
![02](https://github.com/user-attachments/assets/dd6e35ee-43e2-41fa-9f1d-1375bb351c5c)

**Comment by bastianallgeier** [comment]
You've added it in the filter input. Please try adding it after the ">" symbol

**Comment by nilshoerrmann** [comment]
Different setup but maybe this helps aswell: I can trigger the offline message by simply switching my Wifi off. `panel.system.isLocal` always returns `true`. My guess is that the offline message does only take the connection into account and not if I'm in local context.

**Comment by gbdesign2023** [comment]
Thanks for the tip. 
I only use the console to read, but not to send commands. 
I get ‘true’ back. What does this value mean?

<img width="171" alt="Bildschirmfoto 2024-09-18 um 15 09 54" src="https://github.com/user-attachments/assets/d90c67d6-3814-4a42-aa99-0d208d3bb016">

**Comment by afbora** [comment]
@gbdesign2023 Could you list the your app plugins, please? We can't still reproduce the issue and we'll try to reproduce.

**Comment by bastianallgeier** [comment]
We have a solution to only show the warning if the panel isn't installed locally. We plan to release a patch release on Monday.
