### ISSUE TITLE
In Panel: Request page error 500

### ISSUE THREAD

**Issue by mogholito** [k-next/kirby#6684]
## Description
In Panel, when moving any page, the destination dialog box displays the following error message:
"The request to https://example.ddev.site/panel/site/tree/parents?page=site%3A%2F%2F failed" 
There is also a long delay before all pages are displayed (about hundred pages).
However, the page move is executed.

**Expected behavior**  
Obviously, open the move page dialog without the error. 

**Screenshots**  
<img width="531" alt="SCR-20240918-rfis" src="https://github.com/user-attachments/assets/bb1fee7a-eebf-479a-9ec6-374bafba67a0">

## To reproduce
1. Go to the Panel
2. Click on the pop-up menu (3 dots) of the page to be moved and select 'Move page'
3. Wait for all pages to be displayed

Note: With a fresh starterkit install, I cannot reproduce the issue.

## Your setup
**Kirby Version**  
4.4.0

**Console output**  
[browser-console-errors.md](https://github.com/user-attachments/files/17048306/browser-console-errors.md)

**Your system (please complete the following information)**
 - Device: Appe Mac M1
 - OS: macOS 13.6.3 (Ventura)
 - Browser: Brave
 - Version: Brave Version 1.69.168 Chromium: 128.0.6613.138 (Official Build)

**Additional context**

**Comment by bastianallgeier** [comment]
We have a patch release ready that will be released on Monday. You can already give it a try by pulling or downloading https://github.com/getkirby/kirby/tree/release/4.4.1 Please, let us know if the issue has not been fixed by this patch.

**Comment by mogholito** [comment]
Yes, the issue has been fixed. Tested in dev environment (DDEV) and in preproduction on Ubuntu Jammy 22.04 OpenLitespeed server with PHP 8.2.
