### ISSUE TITLE
[Panel] - Gallery block: wrong css applied to unrelated fields

### ISSUE THREAD

**Issue by manuelmoreale** [k-next/kirby#6747]
## Description
In a `gallery` block, some extra css is applied to unrelated fields because of a css conflict.

For example:
![Screenshot 2024-10-15 at 5 30 51 PM](https://github.com/user-attachments/assets/0172ad40-36dc-45e4-8bf5-288412946bfb)

This toggle has an extra gap in between the buttons because it is inheriting a `grid-gap` value set on the `.k-block-type-gallery ul` selector.

![Screenshot 2024-10-15 at 5 32 24 PM](https://github.com/user-attachments/assets/d754dc9f-bd82-41cf-8b13-101f030ff2e1)

**Expected behavior**  
That extra CSS shouldn't be applied to unrelated items.

## To reproduce

Add a toggle field to a `gallery` block and the bug should be there. I didn't test this with other types of field but it should be there on all fields that use an ul

## Your setup
4.4.0

**Comment by distantnative** [comment]
- [x] Make CSS selector very specific
- [x] Check other blocks if they face similar problems

**Comment by manuelmoreale** [comment]
Just noticed that the same selector is also messing up other things such as the pages selector inside a link field

![Screenshot 2024-12-06 at 6 23 39 AM](https://github.com/user-attachments/assets/e9f4f8a8-a2c1-4901-9693-4d272a3b0c23)
