### ISSUE TITLE
SQLite 3.41.0 double-quoted string literals are disabled by default

### ISSUE THREAD

**Issue by 3tlam** [k-next/kirby#6769]
Hi all!

I ran into a nasty bug, where any SQLite Queries failed with `Invalid table` and it took a long time debugging it ;)
After talking to the hoster, I learned that as of SQLite 3.41.0 double-quoted string literals are [disabled by default](https://www.sqlite.org/quirks.html#double_quoted_string_literals_are_accepted) and therefore Kirby's [check](https://github.com/getkirby/kirby/blob/eb47158e91e74184ab291ede020664f1d2829f74/src/Database/Sql/Sqlite.php#L133) if the table exists fails.

Currently I don't have a good suggestion to you as to how to verify this, but I guess "just" changing it to single-quoted literals might fix this?

**Kirby Version**  
afaik any, as the [current implementation in this repo](https://github.com/getkirby/kirby/blob/eb47158e91e74184ab291ede020664f1d2829f74/src/Database/Sql/Sqlite.php#L133) still has double-quoted  string literals

Best
Malte

**Comment by 3tlam** [comment]
re-reading the docs it seems as though there was no forcefully deprecation, but in any case, there is a [reddit thread](https://www.reddit.com/r/freebsd/comments/1chb82b/sqlite3_pkg_just_became_stricter_with_quoting/) showing the same. Currently I am using SQLite Library 3.45.1, which is the same as in the reddit post.

So I guess it's not really a fault of the sqlite maintainers, but my hoster?

**Comment by rasteiner** [comment]
Ran into this today on the staging server, which is managed by the hoster.
Changing to single quotes in that query fixes it and should be done. I'll prepare a PR.
