### ISSUE TITLE
Support for new Vimeo URL pattern

### ISSUE THREAD

**Issue by verstecken** [k-next/kirby#6777]
## Description
I got a problem with certain Vimeo-URLSs:  vimeo.com/123456789 works
but vimeo.com/accountname/somevideo doesn´t!   

**Expected behavior**  
The preview for the Video should show up. Like inserting a URL with ID like vimeo.com/123456789

## To reproduce

1. Go inside panel to a block field and add a block
2. Click on "Video"
3. Paste the Vimeo URL in format vimeo.com/accountname/somevideo 
4. See no preview is showing up

## Your setup
**Kirby Version**  
4.30

**Your system**
 - Browser: Firefox
 - Version: 131

**Comment by verstecken** [comment]
https://developer.vimeo.com/api/oembed/videos

`GET https://vimeo.com/api/oembed.json?url={video_url}`
and the response contains the video_id.

should be somehow added here:

https://github.com/getkirby/kirby/blob/eb47158e91e74184ab291ede020664f1d2829f74/panel/src/helpers/embed.js#L101

or here:

https://github.com/getkirby/kirby/blob/eb47158e91e74184ab291ede020664f1d2829f74/src/Parsley/Schema/Blocks.php#L124

or both?

**Comment by distantnative** [comment]
@verstecken i think if we could avoid a request to a third-party server, we would really try not to do that. 

We need to look into whether the URL scheme you mentioned can also easily transformed into an embed URL.

**Comment by bastianallgeier** [comment]
I was just looking through Vimeo and could not find one of those account video URLs. Do you have an example?

**Comment by verstecken** [comment]
Yeah. I also figured out, that it must be sort of redirection: http://vimeo.com/pulk/denkenohnegelaender ist a redirection to vimeo.com/123456789the official share link though is the slug and won‘t be reconized by kirby video block field.can still be added by copy the URL with video ID. Am 30.10.2024 um 12:26 schrieb Bastian Allgeier ***@***.***>:﻿
I was just looking through Vimeo and could not find one of those account video URLs. Do you have an example?

**Comment by afbora** [comment]
I couldn't find a feature on Vimeo that supports video aliases. Vimeo already redirects these URLs with 307. I would vote not to support this URL format in core.

**Comment by verstecken** [comment]
Since it is possible to embed videos by the link including the Video ID… let’s drop it 🤷🏼‍♂️
