### ISSUE TITLE
Unable to Move Pages and Modules in Kirby 5.0.0-alpha.3

### ISSUE THREAD

**Issue by jirichlebus** [k-next/kirby#6779]
## Description
In Kirby 5.0.0-alpha.3, I am unable to move pages and modules created via the Modules plugin using the "move page" function. This functionality works correctly in Kirby 4 with an identical project setup, but it does not work in the Kirby 5 alpha version.

**Expected behavior**  
I expected to be able to move both pages and modules using the "move page" function as in Kirby 4.

**Screenshots**  
![image](https://github.com/user-attachments/assets/d7172871-8129-49a5-a627-38429b72c1ec)

## To reproduce

1. Open the Kirby 5.0.0-alpha.3 version of the project.
2. Attempt to move a page using the "move page" function.
3. Attempt to move a module created with the Modules plugin.
4. Observe that neither pages nor modules can be moved.

## Your setup
**Kirby Version**  
5.0.0-alpha.3 (issue)
4.x (working as expected)

**Console output**  
Not tested.

**Your system (please complete the following information)**
Device: MacBook air
OS: macOS Monterey 12.5.1
Browser: Chrome
Version: 130

**Additional context**  
The project is identical in both Kirby 4 and Kirby 5 alpha. In Kirby 4, moving pages and modules works as expected, but in the Kirby 5 alpha, this functionality is broken for both.

**Comment by afbora** [comment]
Thanks for the report. This is already fixed in next release as 5.0.0-alpha.4 ✅ https://github.com/getkirby/kirby/pull/6726

**Comment by jirichlebus** [comment]
Thank you @afbora – is there any release day for Alpha 4 please?

**Comment by afbora** [comment]
@jirichlebus You're so lucky since today is release day 🎉 https://github.com/getkirby/kirby/releases/tag/5.0.0-alpha.4
