### ISSUE TITLE
Preview links of some files aren't working

### ISSUE THREAD

**Issue by samlinck** [k-next/kirby#6786]
## Description

The preview link for some files appears as a button instead of a standard link. As a result, clicking it does nothing. However, the file can be accessed by manually copying and pasting the URL.

Initially, I thought it was a Dreamform bug since the file was uploaded through Dreamform. However, after further testing, we found that some files not uploaded via Dreamform also have this issue. [Referring issue](https://github.com/tobimori/kirby-dreamform/issues/98)

**Expected behavior**  

The preview link opens the file url in a new tab.

**Screenshots** 
The file I have problems with
<img width="2225" alt="image" src="https://github.com/user-attachments/assets/97d337e7-de7a-4245-9fe5-2737230f75ec">

The preview button html
![image](https://github.com/user-attachments/assets/c0910c6e-bf96-4d08-a3ef-82ee9e2f91d6)

## To reproduce
1.  Go to a file
2. Try to click on the preview link

## Your setup
**Kirby Version**  
4.4.1

**Console output**  
<img width="975" alt="image" src="https://github.com/user-attachments/assets/5b6f5de6-fdc1-41a0-bfea-ea70fe546eda">

**Your system (please complete the following information)**
 - Device: Macbook Pro
 - OS: MacOs 14.5
 - Browser: Chrome
 - Version: 130.0.6723.117 (Official Build) (arm64)

**Additional context**

**Comment by distantnative** [comment]
Can you reproduce it with a fresh starter kit? Or any actual description to reproduce it? Cause the steps you describe just work fine with the demo kit: https://getkirby.com/try

**Comment by samlinck** [comment]
Hi sorry for the missing info.  I can't reproduce the issue with files uploaded via the panel. But the plugin author does have the issue with other files uploaded via the panel.

1.  Install the starterkit
2.  Install [Dreamform](https://github.com/tobimori/kirby-dreamform)
3. Make a form with an upload field
4. Upload an image (I tried jpg, png, pdf, gif, mp4) via the form
5. Visit the submission in the panel
6. Go to file in the panel
7. Try to preview file (This doesn't work)

**Comment by dominiklaube** [comment]
I can reproduce the issue as described [here](https://github.com/tobimori/kirby-dreamform/issues/98#issuecomment-2471053609). The problem occurs when uploading a file to a page with a blueprint that has the preview permission set to false.

What would be the correct solution here? Sometimes, you may want to disable the page preview while still allowing the file preview.

I also noticed in the screenshot that the button classname "k-file-view-options" might be incorrect and should perhaps be "k-file-view-preview" instead.

**Comment by nilsmielke** [comment]
Can confirm @dominiklaube’s findings. 
Setting `preview: true` in the page template of the page the file was loaded into, fixes the file preview—as a temporary fix, that is.

**Comment by distantnative** [comment]
@dominiklaube @nilsmielke thanks for figuring out how to reproduce the issue, very helpful. I can replicate it as well.

**Comment by distantnative** [comment]
It's caused by this commit: https://github.com/getkirby/kirby/commit/bc2e9fcec832e7d4c668aecc7e50c6beb9b55d18

My question to you, @samlinck @dominiklaube @nilsmielke, would be if the commit has the right intention and the file preview should also be gone if the parent page preview is disabled (and we just need to fix the UI to not show the button) or if you have use cases where this behavior is problematic and the file preview should be independent.

**Comment by nilsmielke** [comment]
@distantnative In my use case, the file preview is intended in a page, that is not previewable. The page only holds information, that is not displayed on a single page basis in the frontend, thus, the preview is futile. Still, the file needs to be downloadable from the panel.

**Comment by dominiklaube** [comment]
@distantnative so at the moment the file preview is the only way to "download" the src file from the panel. In my opionen there should always be the option to download the file from the panel independant of the page blueprint, where the file belongs to. Maybe integrate a "Download" Option in the "file settings" dropdown. But this could also be redundant to the current preview function.
