### ISSUE TITLE
Writer Fields Non-inline toolbar should not show when no marks or nodes are available

### ISSUE THREAD

**Issue by tobimori** [k-next/kirby#6804]
## Description

**Expected behavior**  

**Screenshots**  

## Your setup
**Kirby Version**  

**Console output**  

**Your system (please complete the following information)**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by afbora** [comment]
@tobimori Which Kirby version?

**Comment by tobimori** [comment]
4.4.1
