### ISSUE TITLE
`ucfirst` behavior differs from PHP default

### ISSUE THREAD

**Issue by jakobgrommas** [k-next/kirby#6834]
https://github.com/getkirby/kirby/blob/94cc37ee7c3004ebb4950a53f14e1329ed4d28d3/src/Toolkit/Str.php#L1387-L1392

### Description
The Str::ucfirst method in Kirby differs from PHP's native ucfirst() function.

#### PHP native
Converts only the first letter of the string to uppercase, leaving the rest of the string unchanged.

#### Kirby
Converts the first letter to uppercase and the rest of the string to lowercase.

### Steps to Reproduce

```php
use Kirby\Toolkit\Str;

echo ucfirst('hello WORLD'); 
// Output: Hello WORLD (PHP native behavior)

echo Str::ucfirst('hello WORLD');
// Output: Hello world (Kirby behavior)
```

### Expected Behavior

Str::ucfirst should either align with PHP's ucfirst() or clarify its differing behavior in the documentation to avoid confusion.

### Suggested Solutions

change `static::lower($rest)` to `$rest`

```php
public static function ucfirst(string $string = null): string
{
	$first = static::substr($string, 0, 1);
	$rest  = static::substr($string, 1);
	return static::upper($first) . $rest;
}
```

**Comment by afbora** [comment]
I think you're right. That's really overlooked bug. But I'm not sure if it will make a breaking change. We can also add a `bool lowercase` argument if we want, for convenience.

**Comment by afbora** [comment]
@distantnative What do you think about that?

**Comment by distantnative** [comment]
I agree that this is a bug as the method description really claims to work the same as PHP's `ucfirst()`. We should try to include it in v5, as it is a bugfix but could also seen as breaking change if anyone relied on this behavior.
