### ISSUE TITLE
[v5] Language selector still visible for single language app

### ISSUE THREAD

**Issue by afbora** [k-next/kirby#6850]
When single language environment:

- Language selector visible (was not visible for 4.x)
- Also visible unnecessary separate line under default language (ignore this if we remove the selector entirely for single language)

![5 0 0 test_panel_pages_notes+exploring-the-universe](https://github.com/user-attachments/assets/5dc0ba80-6f84-4c63-9bab-802da82b807d)

**Comment by tobimori** [comment]
man you were 55 minutes faster than me :(

**Comment by distantnative** [comment]
@afbora Does it work when you change https://github.com/getkirby/kirby/blob/v5/develop/src/Panel/Ui/Buttons/LanguagesDropdown.php#L114 to

```php
		if ($this->kirby->languages()->count() < 2) {
```

**Comment by afbora** [comment]
@distantnative Yes, it works.
